### ISSUE TITLE
review EFO github repo content

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#1]
Review text on repository home page and the release note instrcutions

**Comment by paolaroncaglia** [comment]
Looking at https://github.com/EBISPOT/efo => https://github.com/EBISPOT/efo/blob/master/README.md

Action items by sections:

Do not use!
-[ ] Delete section as soon as transition is complete.

Versions => Other release versions
-[ ] No changes needed as long as we keep providing the same versions as listed.

Versions => Term requests and contact
-[ ] Change link “EFO mailing list” to move away from SourceForge.

To do next:
-[ ] Review release notes here: https://github.com/EBISPOT/efo/blob/master/src/ontology/README-editors.md
