### ISSUE TITLE
Review biomarker axioms

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#10]
Iron biomarker - done
autoimmune disease biomarker - done
cancer biomarker - done

@daniwelter please fill in what else are left to review.

**Comment by simonjupp** [comment]
Are there other biomarkers that need review? @twhetzel please review

**Comment by daniwelter** [comment]
Virtually all biomarkers need to be reviewed and updated to the correct pattern (is_about some <concept> and has role some biomarker). The problem is that the current incorrect pattern wrongly classifies things as biomarkers, so it's not just a case of updating the patterns but also of checking each class currently inferred as a biomarker to make sure it actually is a biomarker. The cardiovascular disease biomarkers are a particularly good (bad?) example of this.

**Comment by daniwelter** [comment]
Current biomarker measurement equivalent classes:
- iron biomarker measurement - OK
- cancer biomarker measurement - OK
- inflammatory biomarker measurement - needs review!
- liver disease biomarker  - needs review!
- osteoarthritis biomarker measurement - OK
- diabetes mellitus biomarker - needs review!
- autoimmune disease biomarker - needs review!
- infection disease biomarker - needs review!
- Alzheimer's disease biomarker measurement - needs review! 
- cerebrospinal fluid biomarker measurement - OK
- respiratory disease biomarker - needs review!
- cardiovascular disease biomarker measurement - needs review!
- mental or behavioural disease biomarker - needs review!

Also:
- cardiac stress biomarker measurement - not a defined class, should be reviewed to follow the pattern.

**Comment by zoependlington** [comment]
Tagging this as a potential proposal for Open Targets. @smnorthen I believe you conducted a review of biomarkers, would it be useful to have others aid in this review too?

**Comment by smnorthen** [comment]
@zoependlington
Yes, I had a look at the biomarker groupings in EFO in connection with another project. I am happy to provide input with regards to the structure in the ontology. 

@dOchoa
Please can you take a look and see if this would be of interest to OT?

**Comment by d0choa** [comment]
The biomarker problem is within scope, what I'm not sure is what would be the task. The context of the proposal we have discussed would require to define a task that can easily be tackled by a distributed group of people with not much specific training.
