### ISSUE TITLE
NTR: ImmunoFISH

### ISSUE THREAD

**Issue by brynnz22** [EBISPOT/efo#1003]
For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
preferred term label: ImmunoFISH. 
Textual Definition: ImmunoFISH is a method combining immunolabelling (IL) with fluorescent in situ hybridisation (FISH) to simultaneously detect the nuclear distribution of proteins and specific DNA sequences within chromosomes. 
PubMed ID: 30154816. 
Suggested parent term: in-situ hybridization assay

**Comment by paolaroncaglia** [comment]
Hi @brynnz22 ,
Could you please provide your ORCID ID, so I can add it as a reference for the new term you requested?
If you don't have one yet, you may create it quickly and freely at https://orcid.org/.
Thank you,
Paola

**Comment by paolaroncaglia** [comment]
Hi again @brynnz22 ,
I added your requested new term as EFO_0011016 immunoFISH. It will be available after our next EFO release, scheduled for Monday (March 15th). 

Note for self: if the submitter provides an ORCID, I'll add it, but the term already has a PMID, so I can move this ticket to the "Done" queue in the meantime.

**Comment by brynnz22** [comment]
Hi Paola,

Thank you so very much! My Orcid ID is 0000-0003-2452-6384.

Best,


Brynn

**Comment by paolaroncaglia** [comment]
Thanks Brynn,
I'll add your ORCID in time for the April EFO release. Meanwhile, you may already use the new term after it's released early next week.
Best,
Paola

**Comment by paolaroncaglia** [comment]
Hi @brynnz22 ,
I added your ORCID to EFO_0011016 immunoFISH. It will be visible after the mid-April EFO release.
Best,
Paola

**Comment by brynnz22** [comment]
Hell Paola,

Sounds great. Thank you so much!


Best,


Brynn
