### ISSUE TITLE
Make a report of all term in EFO measurement branch with 'biomarker' in the name.

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#1005]

**Comment by matentzn** [comment]
?term	?term_label	?definition
EFO:0006848	"mental or behavioural disorder biomarker"	"Is the quantification of some marker used in the diagnosis or clinical management of some mental or behavioural disorder."
EFO:0006514	"Alzheimer's disease biomarker measurement"	"Alzheimer's disease biomarkers are used as indicators for Alzheimer's disease screening and as predictors for therapeutic responses and prognoses in Alzheimer patients"
EFO:0006845	"liver disease biomarker"	"The quantification of biomarkers used in the diagnosis or management of liver disease"
EFO:0005278	"cardiovascular disease biomarker measurement"	"cardiovascular disease biomarkers, such as ST2 cardiac biomarker and C-reactive protein, are used as indicators for cardiovascular disease and as predictors for therapeutic responses"
EFO:0006841	"respiratory disease biomarker"	"The quantitation of a biomarker used in the measurement of lung fuction used in diagnosis or management of a clinical condition."
EFO:0006843	"infectious disease biomarker"	"A quantification of some biomarker used in the diagnosis or management of infectious disease."
EFO:0006842	"diabetes mellitus biomarker"	
EFO:0006794	"cerebrospinal fluid biomarker measurement"	"A cerebrospinal fluid biomarker measurement is a quantification in cerebrospinal fluid of some molecule e.g. protein or metabolite that acts as a biomarker for some disease, eg Alzheimer's disease"
EFO:0006846	"autoimmune disease biomarker"	"Is a quantification of some substance or anatomical feature used as an indicator of biological state"
EFO:0005127	"cancer biomarker measurement"	"cancer biomarkers, such as cancer antigen 19-9, carcinoembryonic antigen and α fetoprotein, are used as indicators for cancer screening and as predictors for therapeutic responses and prognoses in cancer patient"
EFO:0004461	"iron biomarker measurement"	"An iron biomarker measurement is a measurement of some molecule e.g. protein or metabolite which is used as a measure of iron metabolism"
EFO:0005890	"osteoarthritis biomarker measurement"	"osteoarthritis biomarkers, such as  serum cartilage oligomeric protein (sCOMP) and urinary C-telopeptide of type II collagen (uCTX-II), are used as indicators for osteoarthritis screening and as predictors for therapeutic responses and prognoses in patients"
EFO:0008471	"cardiac stress biomarker measurement"	"A measurement of some protein which is used as a measure of heart failure."
EFO:0004872	"inflammatory biomarker measurement"	"Is a quantification of any molecule involved in the process of inflammatory response."
