### ISSUE TITLE
New term request for Coignard PMID 33597508

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1009]
For new term requests, please provide the following information:

## Preferred term label

BRCA2 carrier status

## Textual definition

Quantification of the presence or absence of a known harmful mutation in the BRCA2 gene.

## Suggested parent term

carrier status

**Comment by kallia-p** [comment]
Added new term EFO:0011022 'BRAC2 mutation carrier status' under parent term 'carrier status'

rdfs:label 'BRAC2 mutation carrier status'

definition "Determination of the presence or absence of known harmful mutation(s) in the BRAC2 gene. BRCA1/BRCA2 genes play a central role in DNA repair and their mutations increase sensitivity to DNA-damaging agents. BRCA1/BRCA2 germline mutations significantly increase the risk of breast and ovarian cancer."
definition_citation doi:10.1001/jama.2017.7112

alternative_term "BRAC2 carrier status"

alternative_term "BRAC2 mutation status"

database_cross_reference "PMID:33597508"

gwas_trait true

'term editor' "Elizabeth Lewis"

Added Subclass of is_about some ‘breast cancer’

Added Subclass of is_about some ‘ovarian cancer’
