### ISSUE TITLE
Implement master-> branch logical diff in Makefile

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#1011]
For @kallia-p 's work I think it will be useful to be able to track logical diffs.  Would be great to be able to run these with a Make command.  Jim posted an example here https://github.com/geneontology/go-ontology/blob/master/.github/workflows/inference_diff.yml and, IIRC, @matentzn, you have written something similar.

**Comment by matentzn** [comment]
Computing the diff takes a long time, but you can do it in an hour:

```
sh run.sh make feature_diff
```

will produce two diff reports (structural and with reasoning).

```
sh run.sh make feature_diff_md
```

will do the same, producing markdown reports (advantage, can be pasted as PR comments and has labels).
