### ISSUE TITLE
New term request for Li 33445220

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1014]
For new term requests, please provide the following information:

## Preferred term label

response to liver transplant

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of liver a transplant

## Suggested parent term

response to transplant: http://www.ebi.ac.uk/efo/EFO_0007043

## Attribution

NA

**Comment by kallia-p** [comment]
@buniello New term 'response to liver transplant' EFO:001124 added under parent measurement 'response to transplant'.

**Comment by buniello** [comment]
Thanks @kallia-p
