### ISSUE TITLE
New term request for Wu PMID:30449713

### ISSUE THREAD

**Issue by Wkt8** [EBISPOT/efo#1017]
For new term requests, please provide the following information:
Tagging @paolaroncaglia This is a HCA ticket.

## Preferred term label
Enzyme-free chemical dissociation 

## Synonyms
chemical dissociation, enzyme-free non-mechanical dissociation

## Textual definition
dissociation process which uses non-enzymatic chemicals to separate the cells in a specimen

## Suggested parent term
sample dissociation: [EFO_0009091](http://www.ebi.ac.uk/efo/EFO_0009091)

## Use Case and publication
ReLeSR used to dissociate iPSC cells. It is a non-enzymatic reagent. Publication [here](https://pubmed.ncbi.nlm.nih.gov/30449713/) 

Could not find the term in BAO. 

## Attribution
Orcid ID: 0000-0002-6583-8504

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,

Thanks. I'll add your requested term in time for the next EFO release (mid-April), and it will then be imported into HCAO ~a week later. 

Notes for self:

- [ ] expand the definition to read "A sample dissociation process which uses non-enzymatic chemicals to separate the cells in a specimen. An example is the ReLeSR reagent (STEMCELL Technologies)."
- [ ] add PMID:30449713 as dbxref
- [ ] add subset tag "added_for_HCA".

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,
Your requested new term is EFO_0011026 (enzyme-free chemical dissociation).
It will be in the next EFO release (April 15th), and in the HCA ontology after the next HCAO release (April 19th).
Thanks,
Paola
