### ISSUE TITLE
EDIT for EFO:0008634 ONT PremethION

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#1020]
## Preferred term label

The label for this term is spelt incorrectly and should be 'PromethION' i.e. `ONT PromethION`
https://nanoporetech.com/products/promethion

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Thanks for spotting this, I'll fix the typo in the label as well as definition in time for the next EFO release.

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
The correct label and definition for EFO:0008634 ONT PromethION will be in tomorrow's EFO release, and in the HCAO release scheduled for April 19th. Thanks,
Paola
