### ISSUE TITLE
[NTR] Tracheal brush

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#1026]
## Preferred term label

tracheal brush

## Synonyms

tracheal brushing

## Textual definition

A method for sampling of epithelial cells and other effector cells from the tracheal mucosa using a small nylon brush which is rotated over the epithelium and soaked and shaken in a small volume of a balanced salt solution.

> I couldn't find a suitable publication for this specific method for the trachea, I basically copied what was in the nasal brush definition. I am requesting the term to enable curation of the hca publication: https://www.medrxiv.org/content/10.1101/2021.03.09.21253012v1.full-text

## Suggested parent term

collecting specimen from organism
http://purl.obolibrary.org/obo/OBI_0600005

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
I'll add 'tracheal brush' in time for the next EFO release.

Notes for self:
- [ ] Add subset tag "added for HCA".
- [ ] Keep the definition generic as we don't have more precise details: "The process of collecting a specimen of epithelial cells and other effector cells from the tracheal mucosa using a small brush."
- [ ] DOI:10.1101/2021.03.09.21253012 
- [ ] https://orcid.org/0000-0001-7505-5418

**Comment by paolaroncaglia** [comment]
Lastly, @mshadbolt , 
The new term EFO_0011029 (tracheal brush) will also be in tomorrow's EFO release, and in the HCAO release scheduled for April 19th. Thanks,
Paola
