### ISSUE TITLE
New term request for BRB-seq (PMID: 30999927)

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1028]
For new term requests, please provide the following information:

## Preferred term label

Bulk RNA barcoding and sequencing

## Synonyms

BRB-seq

## Textual definition

BRB-seq is a UMI-based 3' protocol for low-cost, highly-multiplexed transcriptome profiling of bulk samples. (PubMed: 30999927)

## Suggested parent term

Multiple parents are possible here:

EFO:0002770 (transcription profiling by high throughput sequencing)
EFO:0001457 (RNA assay)

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
Notes for self:
- [ ] Switch label and synonym, for consistency with existing terms
- [ ] Replace "protocol" with "assay" in definition, for consistency with what EFO means by protocol
- [ ] Create as subclass of 'RNA assay' only (via same axioms as similar terms); leave the sequencing parent aside for now while we sort out the broader discussion on sequencing terms.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
The new term EFO_0011028 (BRB-seq) will be in tomorrow's EFO release.
Thanks,
Paola
