### ISSUE TITLE
'skeleton structure' logical definition is too strong

### ISSUE THREAD

**Issue by balhoff** [EBISPOT/efo#1033]
EFO has these axioms creating a hidden GCI:

- [skeleton structure](http://www.ebi.ac.uk/efo/EFO_0003858) EquivalentTo [part of](http://purl.obolibrary.org/obo/BFO_0000050) some [skeletal system](http://purl.obolibrary.org/obo/UBERON_0001434)
- [skeleton structure](http://www.ebi.ac.uk/efo/EFO_0003858) SubClassOf [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061)

This causes all parts of the skeletal system to be inferred to be anatomical structures. This extends down to chemicals, atoms, etc. If you combine EFO with Uberon and RO, there will be unsatisfiable non-anatomical structure parts of the skeleton (spaces).

My suggestion is to replace both of those axioms with this one:

- [skeleton structure](http://www.ebi.ac.uk/efo/EFO_0003858) EquivalentTo [anatomical structure](http://purl.obolibrary.org/obo/UBERON_0000061) and ([part of](http://purl.obolibrary.org/obo/BFO_0000050) some [skeletal system](http://purl.obolibrary.org/obo/UBERON_0001434))

**Comment by cmungall** [comment]
in general it might be an idea to only include an axiom if it's in uberon - and we can include more axioms upstream in uberon if required
