### ISSUE TITLE
Better name for EFO:0007832 (single cell sequencing)

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1034]
Based on the parentage of this term in the [EBI browser](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0007832&viewMode=All&siblings=false), it seems to actually describe single-cell _RNA_ sequencing, seeing as how it is a child of EFO:0002770 (transcription profiling by high throughput sequencing). 

There are at least a number of other single-cell sequencing assays such as single-cell ATAC-seq, single-cell proteomics (sort of, in CITE-seq) and CRISPR-related protocols, to name a few. One could imagine creating a new term that is the parent of all of these modality-specific terms; such a new term would conceivably be called "single cell sequencing", but it would be a different term from EFO:0007832, which specifically describes the RNA side of things.

On a related note, it would be helpful to have the `scRNA-seq` synonym attached to this term, which is what most people will be searching on.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
Thanks for your comments. The broader issue of 'transcription profiling by high throughput sequencing' and 'single cell sequencing' is described in a previous ticket, see https://github.com/EBISPOT/efo/issues/887#issue-737660331, so I made a note there to be reminded to look at your comments too. Feel free to follow that ticket to be notified of updates. I will close this ticket as a duplicate, but let me know if you have any concerns. Thanks.
