### ISSUE TITLE
Please add MONDO:0014160

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/efo#1035]
For new term requests, please provide the following information:

## Preferred term label
MONDO:0014160 TCR-alpha-beta-positive T-cell deficiency

## Synonyms
IMD7
Immunodeficiency 7
Immunodeficiency 7, TCR-alpha/beta deficient

## Textual definition

a primary immunodeficiency disorder manifesting with recurrent respiratory infections, candidiasis, diarrhea, and failure to thrive. Patients show a clear predisposition to herpes viral infections, and features of immune dysregulation, including hypereosinophilia, vitiligo, and alopecia areata. Other features include lymphadenopathy and hepatosplenomegaly. CD3+ T-cells express TCR- gamma|delta, but little or no TCR-alpha|beta.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

MONDO:0018814 non-severe combined immunodeficiency

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

0000-0003-4062-6158

**Comment by zoependlington** [comment]
This exists in EFO as Orphanet_397959 (existing mapping to MONDO:0014160), will move this ticket to done.

**Comment by bmeldal** [comment]
Thanks, I've updated my entry with the orphanet term.
