### ISSUE TITLE
Please add 'Illumina HiSeq 1500' 

### ISSUE THREAD

**Issue by pnejad** [EBISPOT/efo#1036]
## Preferred term label
 Illumina HiSeq 1500

## Textual definition
The Illumina HiSeq 1500 is a sequencing machine developed by Illumina.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0002699

## Note 
The Illumina HiSeq 1500 has been discontinued, but we still have data generators that have used this system in their experiments. Illumina is going to continue selling the reagents [until 2023](https://support.illumina.com/sequencing/sequencing_instruments/hiseq_1500.html).

**Comment by pnejad** [comment]
@paolaroncaglia @zoependlington  Once this term is added to EFO, we also need it for HCAO :)

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,
Thank you. I'll add the new term in time for the EFO April release, and it will then be imported in the HCAO release (scheduled for Apr 19th).

Note for self:
- [ ] Add HCA subset tag
- [ ] Add Parisa's ORCID

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,
The new term EFO_0011027 (Illumina HiSeq 1500) will be in tomorrow's EFO release, and in the HCAO release scheduled for April 19th. Thanks,
Paola
