### ISSUE TITLE
Please add 10X v1 5' sequencing

### ISSUE THREAD

**Issue by ESapenaVentura** [EBISPOT/efo#1037]
I would like the term `10X v1 5' sequencing` added to EFO.

It currently has the 3' end but is missing the 5' term

## Preferred term label

10x v1 5' sequencing

## Synonyms

`10x 5' v1`, `10X 5' v1`

## Textual definition

10x 5' v1 is the first version of the 10X sequencing technology that sequences from the 5' end of nucleic acid molecules. Differs from 3' v1 in the captured end from the polyadenylated transcript.

## Suggested parent term

[10X v1 sequencing](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009901&viewMode=All&siblings=false#)

**Comment by paolaroncaglia** [comment]
Note for self,
- [ ] Add HCA subset tag

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
Do you have an ORCID ID that I could add to your new term to capture microattribution, please?
If not, you might consider getting one at https://orcid.org/. Not compulsory but nice to have. Either way, I'll add the term in time for the mid-April EFO release. 
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
Your requested new term is EFO_0011025 (10x 5' v1 sequencing). 
It'll be in the April 15th EFO release, and then in the HCAO release scheduled for April 19th.
Thanks,
Paola
