### ISSUE TITLE
Requesting removal of 2 terms

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/efo#1042]
A submitter contacted us to request a change to the trait annotation of their paper in the GWAS Catalog. Studies were incorrectly annotated with herpes simplex virus 6 & 7, whereas they should be human herpes virus 6 & 7, since HSV 6 & 7 do not exist. 

The following terms should be obsoleted with reference to paper PMID33204752:

http://www.ebi.ac.uk/efo/EFO_0010901
http://www.ebi.ac.uk/efo/EFO_0010902

**Comment by ljwh2** [comment]
Requested 2 new terms to replace these in issues #1043 and #1045

**Comment by zoependlington** [comment]
Obsoleted the above two terms and replaced with:

EFO_0011038 | anti-human herpes virus 7 antibody measurement
EFO_0011037 | anti-human herpes virus 6 antibody measurement
