### ISSUE TITLE
Sleep Disorder

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#105]
For new term requests, please provide the following information:

## Preferred term label

Sleep Disorder

## Synonyms

Sleep Disorders
Sleep Disturbances
Disturbances, Sleep
parasomnia
Sleep Disturbance

## Textual definition

A change from the patient's baseline sleeping pattern, in the hours slept and/or an alteration/dysfunction in the stages of sleep. [ NCI ]

## X-refs

NCIT_C3376

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]  Create new term:
EFO:NEW1 Sleep Disorder
Subclass of mental or behavioural disorder (EFO:0000677)
Def: A change from the patient's baseline sleeping pattern, in the hours slept and/or an alteration/dysfunction in the stages of sleep. [ NCI ]
X-refs: NCIT:C3376
Synonyms: Sleep Disorders
Sleep Disturbances
Disturbances, Sleep
parasomnia
Sleep Disturbance

**Comment by paolaroncaglia** [comment]
@zoependlington 
It wasn’t straightforward to pick a parent for this one, but looking at NCIt and at MONDO, I agree. Also based on the NCIt and MONDO entries (e.g. look up MONDO:0003406 in OLS), there are a few terms already in EFO that would fit well under the new broad “sleep disorder” term: REM sleep behavior disorder, hypersomnia, insomnia and possibly others. Thanks!

**Comment by paolaroncaglia** [comment]
BTW, the ID for the new term 'Sleep Disorder' that Zoe created is EFO:0008568.

**Comment by zoependlington** [comment]
- [ ] 'REM sleep behavior disorder' (EFO:0007462) reclassified as subclass of 'Sleep Disorder' (EFO:0008568)

- [ ] insomnia (EFO:0004698) reclassified as subclass of 'Sleep Disorder' (EFO:0008568)

- [ ] hypersomnia (EFO:0005246) added as subclass of 'Sleep Disorder' (EFO:0008568)

- [ ] sleep apnea (EFO:0003877) added as subclass of 'Sleep Disorder' (EFO:0008568)

- [ ] narcolepsy with cataplexy (EFO:0000614) added as subclass of 'Sleep Disorder' (EFO:0008568)

- [ ] narcolepsy without cataplexy (EFO:0005855) added as subclass of 'Sleep Disorder' (EFO:0008568)
