### ISSUE TITLE
HPOA not getting fetched

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#1051]
When running ./get_mirrors.sh, the output includes:

Fetching HPOA from Monarch...
 % Total  % Received % Xferd Average Speed  Time  Time   Time Current
                 Dload Upload  Total  Spent  Left Speed
 0   0  0   0  0   0   0   0 --:--:-- --:--:-- --:--:--   0curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

If this is true for others too, Nico suggests trying the following locally (possibly on VPN):

1. open get_mirrors.sh
2. rename https://data.monarchinitiative.org/ttl/hpoa.ttl to http://data.monarchinitiative.org/ttl/hpoa.ttl
3. run again

If that works, commit the change to repo. 
However, consider if EFO still needs to import HPOA, as OTAR decided to use it directly.

Update - I tried again while on EBI VPN and I still get the same fail message.

**Comment by paolaroncaglia** [comment]
Update 13/5/21, this is still occurring for HPOA when running ./get_mirrors.sh: 

Fetching HPOA from Monarch...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) SSL peer handshake failed, the server most likely requires a client certificate to connect

As noted earlier, we should consider if EFO really still needs to import HPOA, as OTAR decided to use it directly.
Anyway this is not breaking anything afaik.

**Comment by zoependlington** [comment]
I think we can comment this out as it is currently not being used by the EFO pipeline.
