### ISSUE TITLE
GWAS term requests (electrocardiography traits)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1055]
I'm requesting three new terms (in numbered list) below:

## Preferred term label

1. ST segment duration
2. T wave duration
3. TP segment duration

## Synonyms
...

## Textual definition

1. Electrocardiography measurement of the duration from the end of the S wave to the start of the T wave.
2. Electrocardiography measurement of the duration from the start of the T wave to the end of the T wave.
3. Electrocardiography measurement of the duration from the end of the T wave to the start of the P wave.

## Suggested parent term

all should be children of: 
http://www.ebi.ac.uk/efo/EFO_0004327  (electrocardiography)

**Comment by kallia-p** [comment]
@eks-ebi Hi Elliot, is there a PMID to annotate these terms with?

**Comment by eks-ebi** [comment]
@kallia-p Hi Kallia, yeah sorry it's for PMID 32602732

**Comment by kallia-p** [comment]
@eks-ebi 
Added the three electrocardiography terms with definitions as requested.
EFO:0011033 ‘ST segment duration’
EFO:0011034 ‘T wave duration’
EFO: 0011035 ‘TP segment duration’
All are Subclass of electrocardiography.

**Comment by eks-ebi** [comment]
Thanks Kallia!
