### ISSUE TITLE
Consistent capitalisation of 10X labels

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#1057]
Would it be possible to edit the labels of the 10X ontologies so they use a consistent capitalisation pattern?

Currently it alternates between upper and lower case depending on the term 
![Screenshot 2021-04-13 at 10 20 32](https://user-images.githubusercontent.com/13007987/114478574-e8f35300-9c41-11eb-81fa-2193cc2c3211.png)

Looking at their website, it seems the preferred case is lower case, i.e. `10x`

thanks!

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,

Thanks. I noticed the same issue a couple of weeks ago while working on https://github.com/EBISPOT/efo/issues/1037, and I addressed the capitalization then. The edits are listed [here](https://github.com/EBISPOT/efo/commit/500fc44fc9e3b4f3095a6a0a5303548acd8ddae0) - it's a bit long, the bottom line is that I covered all cases highlighted above already. The changes will be visible in the next EFO release, in a couple of days.

Thanks
Paola
