### ISSUE TITLE
New term request "STARmap"

### ISSUE THREAD

**Issue by jiahaoh** [EBISPOT/efo#1059]
## Preferred term label
STARmap

## Synonyms
Spatially-resolved Transcript Amplicon Readout Mapping

## Textual definition
STARmap is an image-based technology for 3D intact-tissue RNA sequencing, which integrates hydrogel-tissue chemistry, targeted signal amplification, and in situ sequencing.

PubMed ID: 29930089

## Suggested parent term
RNA assay
microscopy assay
In-situ hybridization

## Attribution
Xiao Wang (https://orcid.org/0000-0002-3090-9894)

**Comment by paolaroncaglia** [comment]
Hi @jiahaoh ,
The term you requested has been created as EFO_0030000 (STARmap).
It will be available in the next EFO release, scheduled for Monday May 17th. 
Thanks,
Paola
