### ISSUE TITLE
Import MONDO terms used by ClinGen

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1061]
Hello,

could you please import the 20 MONDO ids in [unmapped_diseases_clingen.txt](https://github.com/EBISPOT/efo/files/6316279/unmapped_diseases_clingen.txt) to EFO? They are MONDO disease ids used by ClinGen that I could not find in EFO neither directly nor as xrefs of current terms.

Thank you very much!

**Comment by zoependlington** [comment]
These terms have now been imported into EFO.
