### ISSUE TITLE
viral conjunctivitis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#107]
For new term requests, please provide the following information:

## Preferred term label

viral conjunctivitis

## Synonyms

(e.g., Absent spleen)

## X-refs
MESH D003236
ICD10 B30

## Textual definition

nflammation, often mild, of the conjunctiva caused by a variety of viral agents. Conjunctival involvement may be part of a systemic infection [MeSH]

## Suggested parent term

Conjunctival Disorder

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]  Create new term:
EFO:NEW1 viral conjunctivitis
Subclass of Conjunctival Disorder (EFO:1000203)
Def: Inflammation, often mild, of the conjunctiva caused by a variety of viral agents. Conjunctival involvement may be part of a systemic infection [MeSH]
X-refs: MESH D003236
ICD10 B30

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008571 | viral conjunctivitis
