### ISSUE TITLE
single nucleus (RNA) sequencing terms need update (remove redundancy or change term definition and relation)

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#1078]
I found 2 terms in EFO referencing "snRNA-seq" (single nucleus RNA sequencing).

snRNA-seq http://www.ebi.ac.uk/efo/EFO_0008940
single nucleus sequencing  http://www.ebi.ac.uk/efo/EFO_0009809

EFO_0009809 has child terms referencing RNA sequencing and has the synonym "snRNA-seq" which points to the meaning of this term being also "single nucleus RNA-sequencing" and thus redundant with EFO_0008940

I see two possible solutions:
1) One of the terms should be deprecated (probably EFO_0008940) and the main label of EFO_0009809 renamed to single nucleus RNA sequencing. 

2) We keep EFO_0009809 as general "single nucleus sequencing" term (including RNA and DNA sequencing), remove the synonym and definition, and make snRNA-seq a child term, moving the children of EFO_0009809 to children of EFO_0008940. 
That would also mean to detach EFO_0009809 from parent transcription profiling (move it one level up) and make EFO_0008940 a child of assay by high throughput sequencer (EFO_0002697) instead. But we then need again "snRNA-seq" as a child of transcription profiling by sequencing (EFO_0002770). 
This is the more complicated option but it may give us more flexibility in future when other types of single nucleus techniques may arise.

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
A quick note to say that, based on the terms' axioms, definitions, synonyms and supporting publications, they both indeed refer to single nucleus _RNA_ sequencing. Hence, the correct approach would be your option 1 (merge the 2 terms i.e. obsolete one in favor of the other), and then, if and when the need for a generic or DNA-specific term arises, create it. I will look more closely into which of the 2 terms we should keep.
Thanks for spotting this.
Paola

**Comment by anjaf** [comment]
Thank you @paolaroncaglia, that makes sense.

**Comment by paolaroncaglia** [comment]
@anjaf @sfexova @ngeorgeebi

This ties in with a discussion we just had on the HCA/SCA curators call. The 2 terms we plan to merge sit in 2 slightly different places in EFO. One is a subclass of 'RNA assay', while the other is a subclass of 'transcription profiling by high throughput sequencing', hence a descendant of 'experimental process' but not of 'assay'. Where should 'single nucleus RNA sequencing' be positioned ideally in the ontology, for it to be fully accessible to AE/SCA? This may lead to a broader discussion (should 'transcription profiling' be a subclass of 'assay', considering it's defined as "An assay in which the transcriptome of a biological sample is analysed."...).

Thanks,
Paola

**Comment by dosumis** [comment]
Suggested change (from call)

merge snRNAseq with single nucleus sequencing.  snRNAseq wins as term name.  But classification remains as for 'single nucleus sequencing'.  

@anjaf - please correct if wrong.

**Comment by sfexova** [comment]
@paolaroncaglia I think the agreement is that the best solution would be to deprecate snRNA-seq entirely and keep the single nucleus sequencing http://www.ebi.ac.uk/efo/EFO_0009809 and all its current parentage but change its label to 'single nucleus RNA sequencing'

**Comment by anjaf** [comment]
> @paolaroncaglia yes, I think that is the agreement: to deprecate snRNA-seq entirely and keep the single nucleus sequencing http://www.ebi.ac.uk/efo/EFO_0009809 and all its current parentage but change its label to 'single nucleus RNA sequencing'

I second this. 👍

**Comment by paolaroncaglia** [comment]
Hi @anjaf (cc @sfexova and @ngeorgeebi),
snRNA-seq http://www.ebi.ac.uk/efo/EFO_0008940
is now deprecated in favor of 
single nucleus sequencing http://www.ebi.ac.uk/efo/EFO_0009809
which is now renamed 'single nucleus RNA sequencing'. Annotations and parentage have been kept.
The changes will be visible after tomorrow's EFO release. Thanks.
