### ISSUE TITLE
NTR(s): sci-CAR ATAC-seq and sci-CAR RNA-seq

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#1079]
See https://github.com/HumanCellAtlas/ontology/issues/82.
- [x] Add in_subset "added_for_HCA"
- [x] Add @pnejad's ORCID
- [x] Add PMID:30166440

**Comment by paolaroncaglia** [comment]
Hi @pnejad,

In your original request https://github.com/HumanCellAtlas/ontology/issues/82 you asked for 2 new terms, 'sci-CAR ATAC-seq' and 'sci-CAR RNA-seq'. However, based on these bits from the [supporting publication](https://pubmed.ncbi.nlm.nih.gov/30166440/)  
"Here we describe sci-CAR, a combinatorial indexing-based coassay that jointly profiles chromatin accessibility and mRNA (CAR) in each of thousands of single cells."
and
"Here we describe sci-CAR, which jointly profiles single-cell chromatin accessibility and mRNA (CAR) in a scalable fashion. sci-CAR effectively combines sci–ATAC sequencing (sci-ATAC-seq) and sci-RNA-seq into a single protocol (Fig. 1) by the following steps (...)"
I'd suggest to create one single new term, 'sci-CAR', as follows:

EFO:NEW sci-CAR
exact synonym: single-cell combinatorial indexing chromatin accessibility and mRNA profiling
def: A combinatorial indexing-based coassay that jointly profiles chromatin accessibility and mRNA (CAR) in each of thousands of single cells, combining sci–ATAC sequencing (sci-ATAC-seq) and sci-RNA-seq into a single protocol.
def dbxrefs: PMID:30166440, your ORCID
subclass of single cell library construction EFO:0010183
has_parts: EFO:0008925 'scATAC-seq (cell index)' (synonym sci-ATAC-seq), EFO:0010550 sci-RNA-seq

Please let me know if you have any concern with this plan. Thanks.
Paola

**Comment by pnejad** [comment]
Hi @paolaroncaglia! Great catch, I think what you are suggesting makes sense.

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,
The new term EFO_0030001 (sci-CAR) will be available in the next EFO release, scheduled for Monday.
It will then be imported in the following HCAO release, tentatively scheduled for Tuesday, May 18th. We'll tag you in the release ticket, as agreed.
Thanks,
Paola
