### ISSUE TITLE
malnutrition

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#108]
For new term requests, please provide the following information:

## Preferred term label

malnutrition

## Synonyms

Lack of food

## X-ref

HP_0004395
NCIT_C3669
MESH_D044342

## Textual definition

Inadequate nutrition resulting from poor diet, malabsorption, or abnormal nutrient distribution. [ NCI ]
## Suggested parent term

nutritional disorder

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 malnutrition
Subclass of nutritional disorder (EFO:0001069)
Def: Inadequate nutrition resulting from poor diet, malabsorption, or abnormal nutrient distribution. [ NCI ]
X-refs: HP_0004395
NCIT_C3669
MESH_D044342
Synonyms: Lack of food

**Comment by paolaroncaglia** [comment]
@zoependlington 
This one looks good to me too.
