### ISSUE TITLE
Request to import a human phenotype term (HP:0001667)

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#1081]
Hi, we noticed that EFO sometimes imports human phenotype terms. I'm not sure what the process is for accepting new HP terms to import? We would like to have the term for right ventricular hypertrophy (HP:0001667) available through EFO. https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0001667 Would that be possible? 

I did notice that there is an existing EFO term for left ventricular hypertrophy, so perhaps for consistency sake another EFO term could be made for right ventricular hypertrophy instead of importing the HP term? https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003896

Thank you again for your help!

**Comment by zoependlington** [comment]
Thanks @bonitalam, I've imported the HP term. It will be available in EFO after our September release.
