### ISSUE TITLE
New term request for Zheng PMID 33888516

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1084]
For new term requests, please provide the following information:

## Preferred term label
haemorrhoidal disease

## Synonyms
HEM

## Textual definition
A prevalent anorectal pathology characterised by the symptomatic enlargement and distal displacement of anal cushions

## Suggested parent term
http://www.ebi.ac.uk/efo/EFO_0009685

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by kallia-p** [comment]
@buniello @zoependlington Hi Annalisa, we already have hemorrhoid in EFO_0009552 (which is defined as a disorder therein) under parent term vascular disease EFO_0004264. The term hemorrhoid is used in other disease ontologies such as Mondo and NCIT and is interchangeably used with 'haemorrhoidal disease' in the literature space. After looking at the cases ascertainment in the supplement the ICD codes are for hemorrhoids http://www0.sun.ac.za/aotc/icd10/mf_icd10_codelist.php?showmaster=mf_icd10_node3&icd10_block=I00-I99&icd10_subblock=I80-I89&icd10_n3=I84 
http://www.icd9data.com/2015/Volume1/390-459/451-459/455/455.htm
Are you happy to use the existing term instead for your annotation purposes?

**Comment by buniello** [comment]
Yes I am happy to use the existing term.
Thank you @kallia-p

**Comment by kallia-p** [comment]
@buniello @zoependlington Great, Zoe there is no PR for this ticket and I am moving this to done.
