### ISSUE TITLE
Update EFO download link on BioPortal

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#109]
Please edit the link to github (previously sourceforge). This should be the monthly release version of inferred EFO. Probably good to update the contact e-mail to EFO-users@ebi.ac.uk too.

Cheers :)
Sira

======================================================

BioPortal failed to load Experimental Factor Ontology (EFO) from URL: http://sourceforge.net/p/efo/code/HEAD/tree/trunk/src/efoinowl/InferredEFOOWLview/EFO_inferred.owl?format=raw. 

Please verify the URL you provided for daily loading of your ontology:
Make sure you are signed in to BioPortal.
Navigate to your ontology summary page: http://bioportal.bioontology.org/ontologies/EFO.
Click the "Edit submission information" link.
In the Location row, verify that you entered a valid URL for daily loading of your ontology in the URL text area.
If you need further assistance, please contact us via the BioPortal support mailing list. 

Thank you,
The BioPortal Team

**Comment by paolaroncaglia** [comment]
@siiraa thanks for pointing this out.
@simonjupp I signed in to BioPortal and navigated to the EFO summary page, but I can't see any "Edit submission information" link. Presumably you and Sira have an admin-type special account. I'm happy to contact the BioPortal support mailing list (cc-ing you), unless you have different advice. Thanks.

**Comment by twhetzel** [comment]
Yes, you'll need to contact BioPortal and ask to be added as the admin of EFO.

**Comment by paolaroncaglia** [comment]
I emailed BioPortal (and cc'd Sira as the previous admin and Simon as team lead).

**Comment by paolaroncaglia** [comment]
@simonjupp and I are now administrators of EFO in BioPortal.
I updated the Location (Load from URL) from
http://sourceforge.net/p/efo/code/HEAD/tree/trunk/src/efoinowl/InferredEFOOWLview/EFO_inferred.owl?format=raw
to
https://github.com/EBISPOT/efo/blob/master/efo.owl
- [ ] @simonjupp, could you please confirm that the above is the correct link.
I also updated the version number, and the contact info (EFO mailing list) in the Description and Contact fields.
- [ ] Note for self: before closing this ticket, I’ll double-check that the correct version of EFO is now uploaded in BioPortal (as the daily loading doesn’t take place immediately upon location update).

**Comment by simonjupp** [comment]
The download link should be to the raw  and inferred file https://raw.githubusercontent.com/EBISPOT/efo/master/efo_inferred.owl

**Comment by paolaroncaglia** [comment]
@simonjupp thanks, I updated the link in BioPortal.
