### ISSUE TITLE
Move "Cel-seq2" assay term

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#1094]
"Cel-seq2"  http://www.ebi.ac.uk/efo/EFO_0010010 is currently listed under the broad category "assay". It should be moved  from "assay" to "RNA assay" http://www.ebi.ac.uk/efo/EFO_0001457

Also can add "measures some RNA".

**Comment by paolaroncaglia** [comment]
@anjaf 
I agree. I'll add the axiom
realizes some ('analyte role' and (role_of some RNA))
which will infer Cel-seq2 as a subclass of 'RNA assay'.

**Comment by rays22** [comment]
The proposed changes make sense to me.
The `assay` --> `RNA assay` change should not affect HCA ontology validation as long the term EFO:0010010 `CEL-seq2` remains a child term of EFO:0010183 `single cell library construction` too.

**Comment by paolaroncaglia** [comment]
@rays22 

> The proposed changes make sense to me.
> The `assay` --> `RNA assay` change should not affect HCA ontology validation as long the term EFO:0010010 `CEL-seq2` remains a child term of EFO:0010183 `single cell library construction` too.

Thanks for your feedback. Yes, that parentage won't change.
Best,
Paola

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
As requested, Cel-seq2 is now a child of RNA assay (as well as of 'single cell library construction'). 
The change will be public after tomorrow's EFO release.

**Comment by paolaroncaglia** [comment]
cc @rays22 for his information.
