### ISSUE TITLE
Response to antineoplastic agent branch

### ISSUE THREAD

**Issue by kallia-p** [EBISPOT/efo#1099]
Suggestion to improve 'response to antineoplastic agent' branch structure  by the addition of a few general grouping terms as children with the most obvious being 'response to immunotherapy (agent?)' and 'response to chemotherapy (agent?)'. Currently there are 2 other subclasses representing general grouping terms 'response to immunochemotherapy' and 'response to combination chemotherapy' and several more specific terms which include responses to a particular chemotherapy agent which could be grouped under the more general term 'response to chemotherapy'. Some of these are GO terms and some are GWAS traits. See also issue#1085 'response to mycobacterium Bovis BCG' currently grouped under the more general class 'response to antineoplastic agent' which would fit well under a parent term 'response to immunotherapy' or  'response to immunotherapy agent'. https://github.com/EBISPOT/efo/issues/1085

**Comment by dosumis** [comment]
This will be superseded by general work on 'response to' term
