### ISSUE TITLE
Review suitability of CMO for use in EFO3 for measurements

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#11]
CMO (Clinical Measurement Ontology) covers a lot of the measurements in EFO. We should review whether it meets our requirements and import from it directly if possible.

**Comment by simonjupp** [comment]
@twhetzel please comment on if CMO would be useful for GWAS

**Comment by paolaroncaglia** [comment]
Hi @twhetzel ,
Zoe and I are reviewing the EFO tickets backlog. Could you please take a look at this one and let us know if it's still relevant? If yes, could you please bring it up at a GWAS meeting? If not, please move to Done. Thank you!

**Comment by paolaroncaglia** [comment]
Update: @twhetzel doesn't think this would be needed by GWAS, and that if terms existed in CMO that are needed by GWAS, curators would be suggesting those; @zoependlington and I think that this ticket may now be out of date / not relevant to GWAS, so I'll move to Done.
