### ISSUE TITLE
New term request for Currant et al,  PMID 33979322

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1107]
For new term requests, please provide the following information:

## Preferred term label

Inner corneal thickness

## Synonyms
NA

## Textual definition
A measure of the inner corneal thickness. This can be measured by contact e.g. ultrasound, confocal microscpy or non contact methods e.g. biometry. Reduced inner corneal thickness is used as an indicator for glaucoma.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0004731

**Comment by kallia-p** [comment]
@buniello
Do you think we can  add the exact phenotypes and if so which of these see PMID text below? Are the associated variants with the Ganglion Cell complex thickness or with either RNFL or GCIPL?
.....The thickness of the Ganglion Cell Complex (GCC), the collective name for the RNFL and GCIPL...in this study we have focused on the morphology of the inner retina, comprising the RNFL and GCIPL...
Ganglion Cell complex thickness is already in an ontology called DICOM
http://dicom.nema.org/resources/ontology/DCM/111926. Perhaps we could add inner corneal thickness as a parent term, though not necessary.

**Comment by buniello** [comment]
Hi @kallia-p thank you for the detailed analysis! It would be good to have inner corneal thickness as parent term with RNFL and GCIPL thickness as child terms; however, the trait granularity here is also captured by the reported traits and the users don't usually search for very granular phenotypes. Therefore, I believe that mapping with parent term both phenotypes would be good enough for our user case. I leave the choice to you (more granular vs less granular). Please let me know what you decide.

**Comment by kallia-p** [comment]
@buniello I have discussed some of the more tricky term additions with Laura and they said that they would generally prefer to add new terms that are more specific. I also need to make sure that we align with other ontologies when we make new terms such as anatomical terms from UBERON. Today I have the EFO-GWAS meeting and I will bring this as an example and I will let you know what's been decided. Proposed structure looks something like this but we may change the wording a bit:
eye measurement or (less likely) eye morphology measurement
-inner corneal thickness (measurement)
--ganglion cell complex thickness (measurement)
---retinal nerve fibre layer (RNFL) thickness (measurement)
---ganglion cell inner plexiform layer (GCIPL) thickness (measurement)

**Comment by kallia-p** [comment]
@buniello We decided that under eye measurement I will add 
-'retinal layer thickness measurement' EFO:0600002
definition "A measure of the thickness of one or more layers of the retina. It is measured with various imaging tools including ultrasound, optical coherence tomography (OCT), confocal microscopy, and biometry. Reduced retinal layer thickness is one of the biomarkers used for the diagnosis of glaucoma."

children are
--'retinal nerve fibre layer thickness measurement' EFO:0600004
definition "A measure of the thickness of the retinal nerve fiber layer (RNFL). It is typically measured using optical imaging methods such as optical coherence tomography (OCT). The thickness of the ganglion cell complex (GCC), the collective name for the retinal nerve fibre layer and the ganglion cell inner plexiform layer, is one of the biomarkers used in the diagnosis of primary open angle glaucoma (POAG)."

-- 'ganglion cell inner plexiform layer thickness measurement' EFO:0600005
definition "A measure of the thickness of the ganglion cell inner plexiform layer (GCIPL). It is typically measured using optical imaging methods such as optical coherence tomography (OCT). The thickness of the ganglion cell complex (GCC), the collective name for the retinal nerve fibre layer and the ganglion cell inner plexiform layer, is one of the biomarkers used in the diagnosis of primary open angle glaucoma (POAG)."

**Comment by buniello** [comment]
Thanks for letting me know @kallia-p. It sounds like an excellent plan
