### ISSUE TITLE
OTAR profile update

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#1108]
The OTAR profile needs to be cleaned up as a few non-TA terms are currently sitting directly under disease.

**Comment by d0choa** [comment]
Thanks @zoependlington. We would like to use 3.30 for our next release. A cleaned-up version is not a requirement on our side until early June. Please let us know if we can help with the task

**Comment by zoependlington** [comment]
Thanks for the information @d0choa! I will be able to make a patch of today's 3.30.0 release in early June should there be any issues. I believe that the clean up shouldn't be too difficult, but may require some fine tuning of the slim pipeline.

**Comment by d0choa** [comment]
Any update on this issue? We might need an EFO version in about a week time

**Comment by zoependlington** [comment]
Hi @d0choa, this is still a work in progress that I'm hoping to complete next week before the EFO release on the 15th. Would you require an updated version of the slim file before the EFO release day?

**Comment by d0choa** [comment]
If you happen to have something earlier, we could use it internally for our internal dev instance. That would minimise risk on our side. If it comes easy to you let us know.  For production, we will wait for the next release on the 15th.

**Comment by zoependlington** [comment]
The issues with 'pancreas disease' and 'viral disease or post-viral disorder' should now be fixed in the version we will release tomorrow. Apologies this fix took so long and I was unable to send you an earlier version.

**Comment by d0choa** [comment]
No problem @zoependlington. Looking forward to the release tomorrow
