### ISSUE TITLE
New term request for 33731350

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1114]
For new term requests, please provide the following information:

## Preferred term label

mitochondrial heteroplasmy measurement

## Textual definition

A quantification of the degree of mitochondrial heteroplasmy, i.e. the presence of different mitochondrial DNA variants in different mitochondria within the same individual organism or cell. Heteroplasmy can be inherited through the maternal germ line, or arise through somatic mitochondrial mutations within an individual.

## Suggested parent term

mitochondrial DNA measurement EFO:0006312 - this sounds like a good parent, but the definition makes it sounds like it only applies to measuring the total amount of mtDNA in a sample, so might be too restrictive
and/or
genomic measurement EFO:0004554

## Additional suggested annotations

anatomical part: mitochondrion (GO:0005739), mitochondrial DNA (EFO:0008480)
about disease: mitochondrial disease (Orphanet:68380)

**Comment by kallia-p** [comment]
@eks-ebi That's a good point I can see that the definition for mitochondrial DNA measurement is restrictive and I think the genomic measurement would also be a good candidate for both of these terms to be moved under. For now I have added mitochondrial heteroplasmy measurement EFO:0600008 under mitochondrial DNA measurement EFO:0006312  and I will follow on with a separate ticket to address the structure of the genomic and mitochondrial measurements.

**Comment by eks-ebi** [comment]
@kallia-p Thanks, sounds like a good plan!
