### ISSUE TITLE
Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/efo#1116]
Hi Guys,

One of the tests for our ontology mapping tool ([OnToma](https://github.com/opentargets/OnToma/tree/master/ontoma)) fails recently because of `Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome`. The failing test looks like this:

```
>       assert ontclient.find_term('Camptodactyly-arthropathy-coxa-vara-pericarditis syndrome') == 'http://www.ebi.ac.uk/efo/EFO_0009028'
E       AssertionError: assert 'http://purl....MONDO_0008828' == 'http://www.e...o/EFO_0009028'
E         - http://www.ebi.ac.uk/efo/EFO_0009028
E         + http://purl.obolibrary.org/obo/MONDO_0008828
```

When taking a closer look, both terms `http://www.ebi.ac.uk/efo/EFO_0009028` and `http://purl.obolibrary.org/obo/MONDO_0008828` are valid terms in EFO. However the only difference is the capitalisation of the disease label and a dash (`coxa-vara` *vs* `coxa vara`). 

I have two questions:
* Are these indeed two conceptually different terms? (I guess no, but I want to double check)
* If no, is there a way to find cases systematically, because intercepting one with our handful of tests suggests there might be a larger number of such events in the full database.

Thank for looking into this issue for us!

**Comment by zoependlington** [comment]
Thanks for finding this @DSuveges, I suspect we just need to add the mapping into the mapping file but I'll investigate.

**Comment by zoependlington** [comment]
I've added the mapping for this term, however catching these in the future is something we should look into. Will make a note to discuss.

Moving to Done.
