### ISSUE TITLE
Loading term history fails

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/efo#1117]
Hi Guys,

I was looking up some tems on OLS and when I tried to check out the term history the I got server error. I got the same message when checking out the page on Chrome, Firefox and Safari.

The page I was looking at: [link](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1020)

The js console gave me this:

```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
changes.js:70 Failed to do webservice call!
changes.js:70 https://www.ebi.ac.uk/spot/dino/changes-api/changes/search/findByOntologyNameAndChangeSubjectUri?ontologyName=efo&subject=http://www.ebi.ac.uk/efo/EFO_0009028
```

Sorry if this issue has been already on your radar.

**Comment by zoependlington** [comment]
Tagging: @henrietteharmse @udp for OLS

**Comment by henrietteharmse** [comment]
@DSuveges Yes is a known issue with OLS. In fact this has not been working for some time as far as I am aware. Have you been using it frequent in past? Or is it more a case that you were curious about the functionality?

The reason why we have made no to attempt to fix it is that it was not deemed useful by any of our users. Or at least as far as I know.

**Comment by DSuveges** [comment]
@henrietteharmse, thanks for the quick reply! So checking out term history is not something I usually do (although it was not the first time for sure). In this particular case, I wanted to compare histories for the terms mentioned under #1116 as I was hoping I would get some extra insight what was going on. For me it would be a nice to have feature, but I'm like users in general: want all the features and want them now. :) 

But I fully understand it's not a priority to fix. I have actually checked if this is already reported but I haven't noticed this was EFO's and not OLS's issue tracker. My bad.
