### ISSUE TITLE
Gangrene

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#112]
For new term requests, please provide the following information:

## Preferred term label

gangrene

## X-refs

NCIT_C50573
UMLS_CUI C0017086
MeSH D005734
ICD10 R02
HP_0100758

## Textual definition

Death of tissue, usually in considerable mass and generally associated with loss of vascular (nutritive) supply and followed by bacterial invasion and putrefaction. [ NCI ]

## Suggested parent term

abnormality of metabolism/homeostasis

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 gangrene
Subclass of abnormality of metabolism/homeostasis (HP:0001939)
Def: Death of tissue, usually in considerable mass and generally associated with loss of vascular (nutritive) supply and followed by bacterial invasion and putrefaction. [ NCI ]
X-refs: NCIT_C50573
UMLS_CUI C0017086
MeSH D005734
ICD10 R02
HP_0100758

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008574 | gangrene
