### ISSUE TITLE
New term request for Zheng JS PMID 33203707

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1122]
## Preferred term label

vitamin C measurement

## Textual definition

The quantification of vitamin C levels. 

## Suggested parent term

vitamin measurement

**Comment by earlEBI** [comment]
@kallia-p

**Comment by earlEBI** [comment]
@kallia-p

**Comment by kallia-p** [comment]
@earlEBI added term 'vitamin c measurement' EFO_0600003
