### ISSUE TITLE
New term request for Alfradique-Dunham PMID 33987465

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1123]
## Preferred term label

Parkinson's disease symptom measurement

## Textual definition

Quantification of some aspect of Parkinson's disease symptoms such as their frequency, severity or ratio.

## Suggested parent term

measurement (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001444&viewMode=All&siblings=true)

##additional info
p2: 
"PD motor subtypes, TD (tremor dominant) and PIGD (postural instability/gait difficulty), were determined using previously published algorithms.1,2 Subjects are classified as either TD, PIGD, or indeterminate using scale-specific cutoffs based on the ratio of tremor score to PIGD score from the UPDRS or MDS-UPDRS parts II and III. Applying these algorithms to our pooled cohort, 383 subjects with a tremor/ PIGD score ratio in the indeterminate range could not be assigned to either the TD or PIGD dichotomous trait. As a complementary approach [to the dichotomous GWAS], we therefore used the tremor/ PIGD score ratio as a continuous outcome, permitting inclusion of all subjects (including those classified as indeterminate)."

**Comment by earlEBI** [comment]
@kallia-p

**Comment by kallia-p** [comment]
@earlEBI Added new term 'Parkinson's disease symptom measurement' EFO:0600011
