### ISSUE TITLE
New term request for Khan PMID 33941608

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1124]
## Preferred term label

complement C3 measurement

## Synonyms

complement component 3

## Textual definition

Quantification of the amount of complement C3 in a sample.

## Suggested parent term

blood protein measurement 

##similar existing terms:

complement component C8 measurement - https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008094&viewMode=All&siblings=true

complement C4 measurement - https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004984

@kallia-p

**Comment by kallia-p** [comment]
@earlEBI This is already in EFO see http://www.ebi.ac.uk/efo/EFO_0004983

**Comment by earlEBI** [comment]
@kallia-p ah, sorry, not sure how I missed that - thank you!
