### ISSUE TITLE
New term request for Lahm PMID 33201861

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1126]
## Preferred term label

congenital right-sided heart lesions

## Textual definition

Serious heritable structural anomalies of the right side of the heart, including pulmonary atresia, tricuspid valve disease and Ebstein's anomaly, and right ventricular outflow tract obstruction and/or pulmonary stenosis, that are present from birth.

## Suggested parent term

congenital heart malformation

## Similar existing term: 
congenital left-sided heart lesions
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005938

@kallia-p

**Comment by kallia-p** [comment]
@zoependlington Is this a term that we should request from Mondo, then import to EFO?

**Comment by zoependlington** [comment]
Absolutely @kallia-p, new Mondo term should be requested as a sibling term to [this](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005584&viewMode=PreferredRoots&siblings=false) term.

**Comment by kallia-p** [comment]
@earlEBI. For this term we are going to raise a ticket to Mondo and we will let you know when it is imported to EFO.

**Comment by kallia-p** [comment]
@earlEBI Added congenital left-sided heart lesions EFO_0600032
