### ISSUE TITLE
Osteochondrosis (and subtypes)

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#113]
For new term requests, please provide the following information:

## Preferred term label

Osteochondrosis
Spinal Osteochondrosis
Juvenile Osteochondrosis

### Spinal Osteochondrosis
Osteochondrosis of Spine

### Osteochondrosis
MESH D055034
NCIT_C34879
UMLS CUI C0029429 

### Spinal Osteochondrosis
MESH D055035
ICD10 M42

### Juvenile Osteochondrosis
NCIT_C35313
UMLS CUI C0729346

### Osteochondrosis
A condition that is characterized by defective bone growth that affects the growth centers of bone. [ NCI ]

### Spinal Osteochondrosis
A bone disorder involving ossification centers (EPIPHYSES) of the VERTEBRAL COLUMN. [ MeSH ]

### Juvenile Osteochondrosis
Defective bone growth that affects the growth centers of bone in children. [ NCI ]

## Suggested parent term

Osteochondrosis => bone disease
Spinal Osteochondrosis => Osteochondrosis
Juvenile Osteochondrosis => Osteochondrosis
Familial Scheuermann disease => Spinal Osteochondrosis

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 Osteochondrosis
Subclass of bone disease (EFO:0004260)
Def: A condition that is characterized by defective bone growth that affects the growth centers of bone. [ NCI ]
X-refs: MESH D055034
NCIT_C34879
UMLS CUI C0029429

- [ ] Create new term:
EFO:NEW2 Spinal Osteochondrosis
Subclass of Osteochondrosis (EFO:NEW1)
Def: A bone disorder involving ossification centers (EPIPHYSES) of the VERTEBRAL COLUMN. [ MeSH ]
X-refs: MESH D055035
ICD10 M42

- [ ] Create new term:
EFO:NEW3 Juvenile Osteochondrosis
Subclass of Osteochondrosis (EFO:NEW1)
Def: Defective bone growth that affects the growth centers of bone in children. [ NCI ]
X-refs: NCIT_C35313
UMLS CUI C0729346

- [ ] Familial Scheuermann disease (Orphanet:3135) as subclass of Spinal Osteochondrosis (EFO:NEW2)

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008575 | Osteochondrosis
EFO:0008576 | Spinal Osteochondrosis
EFO:0008577 | Juvenile Osteochondrosis
