### ISSUE TITLE
Consider relocation of `foreign body` and descendants as an `injury`

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#1132]
Throughout curation of finngen GWAS traits we observed that, whereas `foreign bodies` and `foreign body in gastrointestinal tract` are part of `test results`,  `eye foreign bodies` falls within `eye disease`.

From the OT perspective, it would make sense if all `foreign bodies` fall under `injuries` as they are usually considered together with other injuries, poisonings and complications ([ICD10 as example](https://icd.who.int/browse10/2016/en#/XIX)).

**Comment by zoependlington** [comment]
I have updated the existing foreign body terms in EFO to be children of injuries. This will be available with our July release.
