### ISSUE TITLE
New term request for Wang PMID 33227023

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1133]
For new term requests, please provide the following information:

## Preferred term label

IgA measurement

## Synonyms

immunoglobulin A

## Textual definition

Quantification of immunoglobulin A, an antibody with a role in mucosal immunity. 

## Suggested parent term

antibody measurement

## further info
paper conducts GWAS on 'blood concentration of ten cytokines' using neonatal blood spots

**Comment by kallia-p** [comment]
@earlEBI EFO already has 'serum IgA measurement' EFO:0004912. I will add serum immunoglobulin A measurement as a synonym.
