### ISSUE TITLE
New term request for Wang PMID 33227023

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1134]
For new term requests, please provide the following information:

## Preferred term label

S100 calcium-binding protein measurement

## Synonyms

S100B

## Textual definition

The quantification of S100 calcium-bnding protein in a sample. 

## Suggested parent term

cytokine measurement
blood protein measurement

## further info
paper conducts GWAS on 'blood concentration of ten cytokines' using neonatal blood spots.

**Comment by kallia-p** [comment]
@earlEBI S100 calcium-binding protein B measurement
EFO:0600012
