### ISSUE TITLE
salivary gland disease

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#114]
## Preferred term label

salivary gland disease
sialadenitis (already in EFO but need reclassification)
sialolithiasis (already in EFO but need reclassification)

There are probably more salivary gland disorders missing (check http://purl.obolibrary.org/obo/NCIT_C26879 in OLS for instance).

### salivary gland disease
Salivary Gland Disorder

### sialadenitis
Adenitis, Salivary Gland
Chronic Sialadenitis
Irradiation-Induced Sialadenitis
Salivary Gland Inflammation
Sialitis
Sialoadenitis

### salivary gland disease
MESH D012466
ICD10 K11
DOID 10854
NCIT C26879
UMLS_CUI C0036093

### salivary gland disease
A non-neoplastic or neoplastic (benign or malignant) disorder involving a salivary gland. [ NCI ]

## Suggested parent term

salivary gland neoplasm => salivary gland disease => mouth disease => digestive system disease
sialadenitis => salivary gland disease => mouth disease => digestive system disease
sialolithiasis => salivary gland disease => mouth disease => digestive system disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW 1 salivary gland disease
Subclass of mouth disease (EFO:1001047)
Synonyms: Salivary Glad Disorder
X-refs: MESH:D012466 || ICD10:K11 || DOID:10854 || NCIT:C26879 || UMLS_CUI:C0036093
Def: A non-neoplastic or neoplastic (benign or malignant) disorder involving a salivary gland. [ NCI ]

- [ ] EFO:RECLASSIFY1 sialadenitis (EFO:1001179)
Subclass of salivary gland disease (EFO:NEW1)
Remove as subclass of digestive system disease (EFO:0000405)
Synonyms: Adenitis, Salivary Gland
Chronic Sialadenitis
Irradiation-Induced Sialadenitis
Salivary Gland Inflammation
Sialitis
Sialoadenitis

- [ ] EFO:RECLASSIFY2 sialothiasis (EFO:1001180)
Subclass of salivary gland disease (EFO:NEW1)
Remove as subclass of mouth disease (EFO:1001047)

- [ ] EFO:RECLASSIFY3 salivary gland neoplasm (EFO:0003826)
subclass of salivary gland disease (EFO:NEW1)

- [ ] EFO:RECLASSIFY4 parotitis (EFO:0007423)
subclass of salivary gland disease (EFO:NEW1)

**Comment by zoependlington** [comment]
Here is the ID for the the new term:
EFO:0008581 || salivary gland disease
