### ISSUE TITLE
acute myocardial infarction

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#115]
## Preferred term label

acute myocardial infarction
Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction
ST Elevation Myocardial Infarction
Non-ST Elevation Myocardial Infarction

### ST Elevation Myocardial Infarction
ST Elevation Myocardial Infarction by ECG Finding, STEMI, ST Elevation Myocardial Infarction by EKG Finding

### Non-ST Elevation Myocardial Infarction
Non-ST Elevation Myocardial Infarction by ECG Finding, NSTEMI, Non-ST Elevation Myocardial Infarction by EKG Finding, NON-STEMI

### acute myocardial infarction
NCIT_C35204
UMLS CUI C0155626
DOID_9408
ICD10 I21

### Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction
ICD10 I22

### ST Elevation Myocardial Infarction
NCIT_C101888

### Non-ST Elevation Myocardial Infarction
NCIT_C80383

### acute myocardial infarction
Necrosis of the myocardium, as a result of interruption of the blood supply to the area. It is characterized by a severe and rapid onset of symptoms that may include chest pain, often radiating to the left arm and left side of the neck, dyspnea, sweating, and palpitations. [ NCI ]

### ST Elevation Myocardial Infarction
A myocardial infarction that produces elevation in the ST segments of the ECG. [ NCI ]

### Non-ST Elevation Myocardial Infarction
An electrocardiographic finding of a myocardial infarction that does not produce elevations in the ST segment of the EKG. [ NCI ]

## Suggested parent term

acute myocardial infarction => myocardial infarction
Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction => myocardial infarction
Non-ST Elevation Myocardial Infarction => Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction
ST Elevation Myocardial Infarction => Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW1 acute myocardial infarction
subclass of myocardial infarction (EFO:0000612)
X-refs: NCIT:C35204 || UMLS_CUI:C0155626 || DOID:9408 || ICD10:I21
Def: Necrosis of the myocardium, as a result of interruption of the blood supply to the area. It is characterized by a severe and rapid onset of symptoms that may include chest pain, often radiating to the left arm and left side of the neck, dyspnea, sweating, and palpitations. [ NCI ]

- [ ] EFO:NEW2 Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction
subclass of myocardial infarction (EFO:0000612)
X-ref: ICD10:I22
Def:

- [ ] EFO:NEW2 ST Elevation Myocardial Infarction
subclass of Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction (EFO:NEW2)
synonyms: ST Elevation Myocardial Infarction by ECG Finding, STEMI, ST Elevation Myocardial Infarction by EKG Finding
X-ref: NCIT:C101888
Def: A myocardial infarction that produces elevation in the ST segments of the ECG. [ NCI ]

- [ ] EFO:NEW4 Non-ST Elevation Myocardial Infarction
subclass of Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction (EFO:NEW2)
synonyms: Non-ST Elevation Myocardial Infarction by ECG Finding, NSTEMI, Non-ST Elevation Myocardial Infarction by EKG Finding, NON-STEMI
X-ref: NCIT:C80383
Def: An electrocardiographic finding of a myocardial infarction that does not produce elevations in the ST segment of the EKG. [ NCI ]

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008583 || acute myocardial infarction
EFO:0008584 ||  Subsequent ST elevation (STEMI) and non-ST elevation (NSTEMI) myocardial infarction
EFO:0008585 || ST Elevation Myocardial Infarction
EFO:0008586 || Non-ST Elevation Myocardial Infarction
