### ISSUE TITLE
Import MONDO terms

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1150]
Hello,

could you please import this list of 34 MONDO ids to EFO? 
[mondos_to_include.tsv.zip](https://github.com/EBISPOT/efo/files/6677230/mondos_to_include.tsv.zip)
.
They are MONDO disease ids used by various data sources that I could not find in EFO neither directly nor as xrefs of current terms, leading to invalid evidence.

Thank you very much!

**Comment by zoependlington** [comment]
All terms have been imported and will be available in our July release.
