### ISSUE TITLE
New term request for Damotte PMID 34002480

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1152]
For new term requests, please provide the following information:

## Preferred term label

plasma beta-amyloid 1-40:1-42 ratio measurement

## Textual definition

quantification of the ratio of beta-amyloid 1-40 to 1-42 proteins in a sample of blood plasma

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0006514

**Comment by kallia-p** [comment]
@buniello Added new term plasma beta-amyloid 1-40:1-42 ratio measurement.

**Comment by buniello** [comment]
thank you @kallia-p! Which EFO ID is assigned to this term?

**Comment by kallia-p** [comment]
@buniello EFO_0600016

**Comment by buniello** [comment]
thank you @kallia-p
