### ISSUE TITLE
New term request for Cindi 33625064

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1154]
For new term requests, please provide the following information:

## Preferred term label

response to dolutegravir

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) in response to the anti-retroviral drug dolutegravir, typically used in the treatment of HIV infection.

## Suggested parent term

http://purl.obolibrary.org/obo/GO_0061479

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by kallia-p** [comment]
@buniello Added new term 'response to dolutegravir' EFO_0600017
