### ISSUE TITLE
Request for adding Mondo mappings

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#1155]
Hey @zoependlington can you add Mondo mappings for the following 5 terms to

https://github.com/EBISPOT/efo/blob/master/src/ontology/components/mondo_efo_mappings.tsv

cls | label | subject_id | object_id
-- | -- | -- | --
http://www.ebi.ac.uk/efo/EFO_0009068 | dicer1 syndrome | http://purl.obolibrary.org/obo/MONDO_0017288 | http://www.ebi.ac.uk/efo/EFO_0009068
http://www.ebi.ac.uk/efo/EFO_0009118 | female reproductive endometrioid cancer | http://purl.obolibrary.org/obo/MONDO_0002480 | http://www.ebi.ac.uk/efo/EFO_0009118
http://www.ebi.ac.uk/efo/EFO_0009383 | tumoral calcinosis, hyperphosphatemic, familia... | NaN | NaN
http://www.ebi.ac.uk/efo/EFO_0009384 | tumoral calcinosis, hyperphosphatemic, familia... | NaN | NaN
http://www.ebi.ac.uk/efo/EFO_0009441 | Waldenstrom macroglobulinemia | NaN | NaN

That will be all we need for the Cancer work we discussed. Thanks.

**Comment by zoependlington** [comment]
All mappings have been added. Thanks, Nico!

**Comment by matentzn** [comment]
Thank you!
