### ISSUE TITLE
gender identity disorder

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#116]
For new term requests, please provide the following information:

## Preferred term label

gender identity disorder

## X-ref
NCIT_C94362
ICD10 F64
ULMS CUI C0017250
DOID_1234

## Textual definition

A disorder characterized by a strong and persistent cross-gender identification (such as stating a desire to be the other sex or frequently passing as the other sex) coupled with persistent discomfort with his or her sex (manifested in adults, for example, as a preoccupation with altering primary and secondary sex characteristics through hormonal manipulation or surgery). [ NCI ]

## Suggested parent term

gender identity disorder => mental or behavioural disorder

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW1 gender identity disorder
Subclass of mental of behavioural disorder (EFO:0000677)
X-refs: NCIT:C94362 || ICD10:F64 || ULMS_CUI:C0017250 || DOID:1234
Def: A disorder characterized by a strong and persistent cross-gender identification (such as stating a desire to be the other sex or frequently passing as the other sex) coupled with persistent discomfort with his or her sex (manifested in adults, for example, as a preoccupation with altering primary and secondary sex characteristics through hormonal manipulation or surgery). [ NCI ]

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008587 || gender identity disorder
