### ISSUE TITLE
New term request for Dubé PMID 34035401

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1161]
For new term requests, please provide the following information:

## Preferred term label

COVID-19 symptoms remission measurement
or
COVID-19 symptoms remission measurement (time to event)
or 
COVID-19 symptoms measurement

## Textual definition

A measurement of some aspect of COVID-19 symptoms, such as severity or time to remission. 

## Suggested parent term

COVID-19 http://purl.obolibrary.org/obo/MONDO_0100096
or
disease progression measurement https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008336#
or
measurement https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0001444&viewMode=All&siblings=false#

**## further info**
Discussed partly on EFO-trait Slack channel. 

The paper measures time to symptom remission in COVID-19 outpatients at risk of severe disease ("at least one risk factor for disease severity").

**GWAS Catalog reported trait considered (i.e. more specific, using author language):** 
COVID-19 symptoms remission in non-hospitalised, high-risk patients (time to event)

**Comment by kallia-p** [comment]
@earlEBI Added new term 'time to remission of COVID-19 symptoms' EFO_0600020
New parent term created 'COVID-19 symptoms measurement' EFO_0600019
