### ISSUE TITLE
New term request for Batai K PMID 33382417

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1164]
## Preferred term label

response to dietary selenium supplementation

## Textual definition

Physiological response of an organism to being given selenium as a dietary supplement.

## Suggested parent term

response to diet -  https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010757&viewMode=All&siblings=false

**Comment by kallia-p** [comment]
@earlEBI Added new term EFO:0600021
