### ISSUE TITLE
New term request for Nishizawa D PMID 33685280

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1165]
For new term requests, please provide the following information:

## Preferred term label

response to gamma-aminobutyric acid receptor agonists

## Synonyms

response to GABA receptor agonists

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a gamma-aminobutyric acid receptor agonist. 

## Suggested parent term

response to drug

**Comment by kallia-p** [comment]
@earlEBI New term added EFO:0600022

**Comment by kallia-p** [comment]
@earlEBI Added new term EFO:0600022
