### ISSUE TITLE
branch_class annotation property

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#1167]
Stemming from today's EFO docathon.

EFO has an annotation property called branch_class (http://www.ebi.ac.uk/efo/branch_class).
It's applied to some high-level classes (see screenshot below). 
I suspect it was created for ArrayExpress, but it’s undefined.
Is it (still) used in pipelines? I’d suggest to define it if it’s still used (so editors and developers know how to use it), or drop it if it isn’t. Do we need to consult with others in addition to ArrayExpress? I'll add to the agenda for our next curators' meeting.
cc @anjaf (please feel free to tag others).

![Screen Shot 2021-07-08 at 14 44 21](https://user-images.githubusercontent.com/4982516/124923815-1a8a7900-dffb-11eb-944d-6c0b957755d9.png)

**Comment by helenp** [comment]
@paolaroncaglia I think you are right about the usage. As I recall this was used to identify classes to integrate with a very old ArrayExpress data acquisition tool. I  think this could be killed now as long as Irene's team are no longer using this.

**Comment by paolaroncaglia** [comment]
Thanks for confirming @helenp ! We'll discuss with Anja and others next week.

**Comment by anjaf** [comment]
I'll check with our developers if this is still in use. At latest, after the move of ArrayExpress to BioStudies, this can probably be removed.

**Comment by paolaroncaglia** [comment]
Thanks @anjaf .

**Comment by paolaroncaglia** [comment]
Nancy has never seen it used. We could reach out to BioStudies to double-check that branch_class would be safe to remove.

**Comment by anjaf** [comment]
Hi @paolaroncaglia, it turns out that ArrayExpress interface is still using this. Please do not remove.

**Comment by paolaroncaglia** [comment]
> Hi @paolaroncaglia, it turns out that ArrayExpress interface is still using this. Please do not remove.

Thanks @anjaf for following up. Then we'll keep the annotation property 'branch_class' and
- [ ] I'll add a quick definition to it "For use in the EMBL-EBI ArrayExpress interface."
