### ISSUE TITLE
New term request for Abdel-Wahab PMID 33409738

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1173]
For new term requests, please provide the following information:

## Preferred term label

response to immune checkpoint inhibitor

## Synonyms

response to ICI

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of immune checkpoint inhibitor stimulus such as Ipilimumab and Anti-PD-1/PD-L1 agents.

## Suggested parent term

response to drug

## further info
Paper looks at immune-related adverse response to ICI's in treating melanoma

**Comment by kallia-p** [comment]
@earlEBI @ljwh2 @eks-ebi New term added 'response to immune checkpoint inhibitor' EFO:0600023.
This is a nice example of a response term to an antineoplastic agent (immune checkpoint inhibitor) that refers to immune-related adverse events. The parent class is 'response to antineoplastic agent' and for now I have added (is_about some adverse effect).
