### ISSUE TITLE
New term request for Bing PMID 33455090

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1176]
For new term requests, please provide the following information:

## Preferred term label

response to tofacitinib

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulus with tofacitinib.

## Suggested parent term

response to drug

## further info
Tofacitinib is an oral JAK inhibitor for the treatment of rheumatoid arthritis (RA), psoriatic arthritis, and ulcerative colitis, and has been previously investigated for psoriasis (PsO).

The paper looks at herpes zoster incidence/time to event in psoriasis/rheumatoid arthritis after being treated with tofacitinib.

**Comment by kallia-p** [comment]
@earlEBI Added response to tofacitinib EFO_0600024
Parent term: response to drug
is_about some 'Herpes Zoster'
is_about some 'psoriatic arthritis'
is_about some 'rheumatoid arthritis'
is_about some 'ulcerative colitis'

Thanks for including additional info. We will look at possible improvement to the term based on the text you provided (herpes zoster incidence/time to event in psoriasis/rheumatoid arthritis after being treated with tofacitinib) along with all other GWAS measurements that are 'response to'.
