### ISSUE TITLE
New terms request for Aherrahrou PMID 33040646 (WC_20210716)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1179]
2 terms
aortic calcification measurement
aortic proliferation measurement

https://docs.google.com/spreadsheets/d/1GZimquDOPilpVVXFN0TiSrSFPaZMETIBTyil4b5UdHU/edit#gid=1909577919

**Comment by kallia-p** [comment]
@Santhi1901. I suggest to use the term aortic smooth muscle cell proliferation or vascular associated smooth muscle cell proliferation which is also a GO process GO:1990874). 
Happy with this? Not sure if it is an established biomarker for cardiovascular disease but I will look into it

**Comment by Santhi1901** [comment]
@kallia-p  In the paper mentioned traits are mentioned as atherosclerosis-relevant traits, proliferation, and calcification, in vascular smooth muscle cells (VSMCs), so I feel vascular associated smooth muscle cell proliferation will be fine for proliferation

**Comment by kallia-p** [comment]
@Santhi1901 Yes, the two measurements above are cellular phenotypes relevant to atherogenesis and atherosclerosis. Vascular smooth muscle cells (VSMCs) are currently considered to be responsible for the formation of vascular calcifications and atherosclerotic plaques PMID:15131535. But 'aortic calcification' sounds very similar to 'abdominal aortic calcification' which we have in EFO and is a non-cellular phenotype measured with imaging methods (see https://www.ejves.com/article/S1078-5884(05)00247-9/pdf). The role of vascular smooth muscle cell proliferation in the formation of atherosclerotic plaques is not very clear. VSMC proliferation in atherosclerosis appears to be predominantly reparative, even in atherogenesis, and not the primary driver of plaque formation. PMID:26892967
Therefore my suggestion for the terms is as follows:
aortic smooth muscle cell calcification measurement 
Quantification of the calcification of vascular smooth muscle cells derived from the aorta. A vascular smooth muscle cell is a non-striated, elongated, spindle-shaped cell found lining the blood vessels. 
aortic smooth muscle cell proliferation measurement.
Quantification of the multiplication or reproduction of vascular smooth muscle cells derived from the aorta. A vascular smooth muscle cell is a non-striated, elongated, spindle-shaped cell found lining the blood vessels.
There is still a bit of digging up for me to do for the parental class but are you happy with the terms and their definitions thus far?

**Comment by Santhi1901** [comment]
@kallia-p yes it sounds good

**Comment by kallia-p** [comment]
@Santhi1901 
aortic vascular smooth muscle cell calcification measurement EFO_0600025
aortic vascular smooth muscle cell proliferation measurement EFO_0600026
Parent class 'cardiovascular measurement' EFO_0004298
