### ISSUE TITLE
Status Asthmaticus

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#118]
For new term requests, please provide the following information:

## Preferred term label

Status Asthmaticus

## Synonyms

Asthma with status asthmaticus
Severe asthma attack

## X-refs
NCIT_C122577
UMLS CUI C0038218
HP_0012653
DOID_9362
ICD10 J46

## Textual definition

An acute exacerbation of asthma, characterized by inadequate response to initial bronchodilators. [ NCI ]

## Suggested parent term

Asthma

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Here's the ID for the new term:
EFO:0008590 || Status Asthmaticus
