### ISSUE TITLE
New term request for Lee SHR PMID 32882024 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1181]
For new term requests, please provide the following information:

## Preferred term label

TCF3-PBX1 fusion

## Textual definition

TCF3-PBX1 fusion is a common molecular subtype of acute lymphoblastic leukemia, arising from the translocation t(1; 19)(q23; p13.3) and occurring in approximately 5% of children with B-cell ALL

## Suggested parent term

childhood acute lymphoblastic leukemia

#can it also be under 'acute lymphoblastic leukemia'?

**Comment by kallia-p** [comment]
@earlEBI Apologies for the delay for this term. There is a term in NCIT http://purl.obolibrary.org/obo/NCIT_C80347
B Acute Lymphoblastic Leukemia with t(1;19)(q23;p13.3); E2A-PBX1 (TCF3-PBX1)
which I think can go under acute lymphoblastic leukemia. 
For some reason I cannot get to the full text of the GWAS but it seems to me from the abstract that this is the disease and we can use the NCIT term.

**Comment by earlEBI** [comment]
@kallia-p yes that looks right, yes please

**Comment by kallia-p** [comment]
@earlEBI Hi Liz,
Does the paper examines this phenotype in adult B acute lymphoblastic leukemia or in children? Do you have a pdf pf the paper, cause I can't access the full text? I need to see the parental structure at Mondo and whether this could fit under children, adult, or other parent.

**Comment by earlEBI** [comment]
@kallia-p hi Kallia, the paper looks at children only. I'll send you the PDF via Slack. Thank you

**Comment by kallia-p** [comment]
@earlEBI Hi Liz, I have added this term in MONDO B-cell acute lymphoblastic leukemia with t(1;19)(q23;p13.3); E2A-PBX1 (TCF3-PBX1). They will have their monthly release soon so once this is in Mondo I will import it in EFO. I will send you the EFO id in due course.

**Comment by earlEBI** [comment]
@kallia-p thank you!

**Comment by earlEBI** [comment]
@kallia-p hi, is this imported now? thank you

**Comment by zoependlington** [comment]
NOTE TO EDITOR: Add MONDO:0600030 to the mondo_terms.txt in the iri_dependencies to import the term.

**Comment by zoependlington** [comment]
I've imported this term now and it'll be available after our 17th January release.

**Comment by earlEBI** [comment]
thank you, then I will publish with http://purl.obolibrary.org/obo/MONDO_0600030
