### ISSUE TITLE
New term request for "Sample Splitting"

### ISSUE THREAD

**Issue by JoshuaFortriede** [EBISPOT/efo#1183]
For new term requests, please provide the following information:

## Preferred term label

Sample Splitting

## Synonyms

Aliquotting, sub-sampling

## Textual definition

Physical separation of a material, eg tissue obtained from a biopsy, into discrete instances

## Suggested parent term

experimental process - http://www.ebi.ac.uk/efo/EFO_0002694

## Attribution

https://orcid.org/0000-0002-3293-5463

**Comment by paolaroncaglia** [comment]
Hi @JoshuaFortriede ,

We'll add your term as suggested, in time for the next EFO release (mid-August).

Thank you,
Paola

**Comment by paolaroncaglia** [comment]
Hi @JoshuaFortriede ,

The new term you requested is EFO_0030016 (sample splitting).
It will be available with the new EFO release, scheduled for August 16th.

Thank you,
Paola Roncaglia
