### ISSUE TITLE
New term requests for RCH-ACV and BLaER1 cell lines

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#1187]
Hello, ENCODE has two requests for terms to be made for the following cell lines. Thank you and please let me know if you have any questions.

## Preferred term label
RCH-ACV

## Synonyms
RCHACV, RCH

## Textual definition
RCH-ACV cell line is a human B cell precursor leukemia cell line established from a bone marrow sample of a child with acute lymphoblastic leukemia. (https://doi.org/10.1016/0165-4608(86)90055-5)

## Suggested parent term
lymphoma or leukemia cell line (EFO:0002937)

## Organism part
bone marrow

## Organism
Homo sapiens

## Sex
female

## Disease
acute lymphoblastic leukemia 

---

## Preferred term label
BLaER1

## Synonyms
B cell Leukemia C/EBPalphaER clone 1

## Textual definition
BLaER1 cell line is a tamoxifen-inducible subclone of the RCH-ACV B-cell leukemia cell line genetically modified using a retrovirus vector to express C/EBPα fused with the estrogen receptor hormone binding domain (ER) and GFP. (https://doi.org/10.1016/j.celrep.2013.03.003)

## Suggested parent term
See NTR request above (RCH-ACV)

## Organism part
bone marrow

## Organism
Homo sapiens

## Sex
female

## Disease
acute lymphoblastic leukemia

**Comment by paolaroncaglia** [comment]
Hello @bonitalam ,
We'll try to add the two terms you requested in time for the mid-August EFO release. We'll comment here when done.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Notes for self/EFO editor:
For RCH-ACV, 
- [ ] xref BTO:0003376; 
- [ ] pub provided is PMID: 3455845; 
- [ ] the "organism part" should not be a strict part_of rel, see if it's already linked to the parent term; 
- [ ] check best rel to use for disease.

**Comment by bonitalam** [comment]
Thanks so much @paolaroncaglia!
