### ISSUE TITLE
Information on versions of ontologies that the EFO stitches together

### ISSUE THREAD

**Issue by dorkosaurus** [EBISPOT/efo#1188]
Hi EFO authors,

How do I figure out which versions of the cell line ontology, uberon, and disease ontology get used for a new EFO release?   I'm trying to enable forensics on my data and this lack of information acts as a barrier for some use cases I am trying to enable.

Many thanks!

Vivek

**Comment by paolaroncaglia** [comment]
Dear Vivek (@dorkosaurus ),

Thank you for contacting us. 

> How do I figure out which versions of the cell line ontology, uberon, and disease ontology get used for a new EFO release? I'm trying to enable forensics on my data and this lack of information acts as a barrier for some use cases I am trying to enable.

EFO does not import the Cell Line Ontology (CLO) at present; it cross-references some of their terms. If you meant the Cell Type Ontology instead (CL), EFO imports it dynamically, so every EFO release (scheduled around the 15th of every month) will contain the latest version of CL available at the time. Same for Uberon. As for the Human disease ontology DOID, EFO no longer imports from it, so any DOID class in EFO dates back to ver1.88, as listed in the EFO release notes (https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt). However, EFO imports the Mondo disease ontology dynamically, and Mondo integrates DOID. You may find a summary of the EFO-Mondo integration process under "Changes to EFO in version 3" in https://github.com/EBISPOT/efo#readme. 

Please let us know if you'd like further details on any of the above.

With best wishes,
Paola Roncaglia, for the EFO team.

**Comment by paolaroncaglia** [comment]
Addendum/example:
The latest EFO release (July 15th) contains 
CL version dated June 29th 
Uberon version dated July 6th
Mondo version dated July 12th.
EFO is released every month.
