### ISSUE TITLE
New term request for Timmer PMID 33491795

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1189]
For new term requests, please provide the following information:

## Preferred term label

hemoglobin change measurement

## Textual definition

quantification of the change in hemoglobin levels in an individual over time, eg over the course of several years after regular blood donation

## Suggested parent term

hemoglobin measurement

## more info

GWAS looks at declining hemoglobin trajectory in blood donors - using growth mixture models on repeated pre-donation capillary hemoglobin measurements

**Comment by kallia-p** [comment]
@earlEBI Added hemoglobin change measurement EFO_0600027
