### ISSUE TITLE
Duplicated classes for Erysipeloid

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#119]
https://www.ebi.ac.uk/ols/search?q=Erysipeloid&ontology=efo

Please keep 'Erysipelothrix rhusiopathiae infectious disease' (EFO_1000928)
and remove the other class (EFO_1000927)

## Synonyms from the other class

Erysipelothrix infectious disease
Erysipeloid (disorder)
Erysipelothrix disease (disorder)Erysipelothrix Infections
Seal finger (disorder)

## X-ref
ICD10 A26

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Obsolete Erysipelothrix infectious disease (EFO:1000927)
make obsolete (editing label, subclass of obsolete class, remove axioms), 
term replaced by 'Erysipelothrix rhusiopathiae infectious disease' (EFO:1000928) (http://www.ebi.ac.uk/efo/EFO_1000928)
obsolete_in_version 2.95
reason_for_obsolescence Use: EFO:1000928 label: Erysipelothrix rhusiopathiae infectious disease
organizational_class true

- [ ] EFO:EDIT 'Erysipelothrix rhusiopathiae infectious disease' (EFO:1000928)
Synonyms: Erysipelothrix infectious disease
Erysipeloid (disorder)
Erysipelothrix disease (disorder)
Erysipelothrix Infections
Seal finger (disorder)
X-refs: ICD10:A26
