### ISSUE TITLE
Remove several children from Alzheimer biomarker class

### ISSUE THREAD

**Issue by kallia-p** [EBISPOT/efo#1190]
Remove terms with little or no evidence of being biomarkers for Alzheimers disease
http://www.ebi.ac.uk/efo/EFO_0004744
http://www.ebi.ac.uk/efo/EFO_0010588
http://www.ebi.ac.uk/efo/EFO_0010589
http://www.ebi.ac.uk/efo/EFO_0010590
http://www.ebi.ac.uk/efo/EFO_0010591
http://www.ebi.ac.uk/efo/EFO_0008466
http://www.ebi.ac.uk/efo/EFO_0007656
http://www.ebi.ac.uk/efo/EFO_0007657
http://www.ebi.ac.uk/efo/EFO_0004751
http://www.ebi.ac.uk/efo/EFO_0004814
http://www.ebi.ac.uk/efo/EFO_0004814
http://www.ebi.ac.uk/efo/EFO_0004814

http://www.ebi.ac.uk/efo/EFO_0007739 (not relevant to AD but relevant to schizophrenia)

**Comment by zoependlington** [comment]
**Note to self:** Remove the connection to Alzheimers biomarker for the above terms.
