### ISSUE TITLE
New term request for McGurk PMID 33437986

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1191]
For new term requests, please provide the following information:

## Preferred term label

N-acylethanolamine measurement

## Synonyms

(e.g., Absent spleen)

## Textual definition

A quantification of N-acylethanolamine in a sample. 

## Suggested parent term

lipid measurement

## further info

2 GWAS described, on ceramide (CER) levels and N-acyl ethanolamine (NAE) levels. 

"Bioactive lipids of the NAE and CER classes have potent roles in inflammation and immunity. NAEs are fatty acid deriva- tives, derived from membrane phospholipids and degraded by the enzyme fatty acid amide hydrolase (FAAH; Fig. 1). This class of bioactive lipids includes the endocannabinoid anandamide (AEA), the nuclear factor agonist palmitoyl ethanolamide (PEA) and a number of other species with intracellular roles in neu- ronal signalling and pain. Plasma levels of some NAEs are posi- tively correlated with obesity (10–13).

CHEBI term: N-acylethanolamine - https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCHEBI_52640

**Comment by kallia-p** [comment]
@earlEBI Added N-acylethanolamine EFO_0600028
