### ISSUE TITLE
New term request: Seq-Well S^3

### ISSUE THREAD

**Issue by snyquist2** [EBISPOT/efo#1194]
For new term requests, please provide the following information:

## Preferred term label

Seq-Well S^3

## Synonyms

(e.g., Absent spleen)

## Textual definition

Seq-Well with second strand synthesis (PMID: 33053333)

## Suggested parent term

Seq-Well http://www.ebi.ac.uk/efo/EFO_0008919

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hello @snyquist2 ,
We'll add Seq-Well S^3 hopefully in time for the next EFO release, and will comment here with the new EFO ID when done. If you wish, please indicate your ORCID so we can link it to the new term for micro-attribution.
@zoependlington is there a way to render the term label as per publication [here](https://pubmed.ncbi.nlm.nih.gov/33053333/) please?

**Comment by zoependlington** [comment]
@paolaroncaglia I don't think there is a way to render this in EFO but I can look into it.

**Comment by paolaroncaglia** [comment]
> @paolaroncaglia I don't think there is a way to render this in EFO but I can look into it.

Thanks @zoependlington ! If not, I'll add without the superscript.

**Comment by paolaroncaglia** [comment]
Hi @snyquist2 ,
The new term you requested is 
EFO_0030019 (Seq-Well S3) 
with exact synonym "Seq-Well S^3".
It will be available with the next EFO release scheduled for August 16th.
Best wishes,
Paola Roncaglia
