### ISSUE TITLE
New term request for Dube MP PMID 33560138

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1196]
For new term requests, please provide the following information:

## Preferred term label

response to colchicine

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a colchicine stimulus.

## Suggested parent term

response to drug

## further information
"The COLCOT (Colchicine Cardiovascular Outcomes Trial) has recently shown the benefits of the anti-inflammatory medication colchicine in reducing the rate of ischemic cardiovascular events"

Paper looks at 2 GWAS: 
1. Cardiovascular event in colchicine-treated recent myocardial infarction
2. Gastrointestinal event in colchicine-treated recent myocardial infarction

**Comment by kallia-p** [comment]
@earlEBI Added response to colchicine EFO_0600029
Flagging this for future improvement. For future reference with which of the 2 end points are you annotating the associations in the GWAS catalog? There are two end points: The primary end point of the trial is 'time to occurrence of cardiovascular event in colchicine-treated recent myocardial infarction'. The safety end point is 'time to occurrence (i.the first report) of gastrointestinal event in colchicine-treated recent myocardial infarction'. This is the adverse event of the trial. 
Relevant text from paper:
"The pharmacogenomic study's primary cardiovascular end point was defined as for the main trial, as time to first occurrence of cardiovascular death, resuscitated cardiac arrest, myocardial infarction, stroke, or urgent hospitalization for angina requiring coronary revascularization. The safety end point was time to the first report of gastrointestinal events."

**Comment by earlEBI** [comment]
@kallia-p Thanks for this - I'd missed that the gastrointestinal GWAS was also time to event. 
At the moment I have created 2 separate entries to the Catalog, one annotated with 'response to colchicine' and 'cardiovascular event measurement'. The other with 'response to colchicine' and 'abdominal symptom'.  (Both have 'myocardial infarction' as background EFO.)
