### ISSUE TITLE
New term request for Franco LAM PMID 33669428

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1202]
For new term requests, please provide the following information:

## Preferred term label

response to antiparasitic agent

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an antiparasitic agent. 

## Suggested parent term

response to drug

## further info:

This paper conducts a GWAS on 'Adverse response to benznidazole in Chagas disease'
From Wikipedia: Benznidazole is a nitroimidazole antiparasitic with good activity against acute infection with Trypanosoma cruzi, commonly referred to as Chagas disease.

Happy to use 'response to antiparasitic agent' or 'response to benznidazole', however specific EFO feels is necessary.

**Comment by kallia-p** [comment]
@earlEBI Thanks for the info and the options. I added both terms 'response to benznidazole' EFO_0600031 which is is the child of 'response to antiparasitic agent' EFO_0600030. So you can use the former for the GWAS annotation for specificity and the parent term indicates what it is for.  I have also added SubClass Of axiom is_about some 'Chagas disease' and is_about some 'parasitic infection'.

**Comment by earlEBI** [comment]
@kallia-p brilliant, thank you!
