### ISSUE TITLE
New terms request to indicate drug responses

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1209]
At Open Targets we are curating the cancer biomarkers dataset from the Cancer Genome Interpreter. We want to standardise how the responses to a treatment are reported in this datasource by including the respective term to EFO, following the same parentage as response to drug ([GO_0042493](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0042493)). That is, we want the different effects to be inherited from the parent `biological process`.

## Preferred term label
1. drug resistance
2. lack of efficacy
3. drug toxicity

## Synonyms
2. refractory drug response / lack of drug effect

## Cross-references
1. NCIT:C16523
2. HP_0020174
3. NCIT:C27955, TXPO:0004320, NPO:1341, OAE:0001804

## Textual definition
1. The state of primary insensitivity or greatly reduced sensitivity of a given organism to the action of one or more drugs.
2. Absent or significantly reduced efficacy of drug intervention characterized by lack of measurable benefit or deterioration of disease course.
3. An adverse effect of a drug used therapeutically or diagnostically.

## Suggested parent term

To describe responses to a drug, we want the parent term to always fall under `biological_process`
https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0008150&viewMode=All&siblings=false

## Attribution

ORCID id: https://orcid.org/0000-0002-2417-7324

Many thanks!

**Comment by ireneisdoomed** [comment]
Hi @zoependlington, could you please let me know if this ticket is in scope for your upcoming release?

Many thanks!

**Comment by paolaroncaglia** [comment]
Hi @ireneisdoomed ,

> Hi @zoependlington, could you please let me know if this ticket is in scope for your upcoming release? We are releasing late September and we are including this new data source in it. It would be great to know if we could count with these mappings.
> 
> Many thanks!

Thanks for your message. Zoë is away this week, but she's already assigned this ticket to herself, and I trust that it'll be in scope for the next EFO release (mid-September). Best wishes,

Paola

**Comment by zoependlington** [comment]
The following terms have been added and will be available after the September release:

drug resistance - EFO_0020001
lack of efficacy - EFO_0020002
drug toxicity - EFO_0020003

**Comment by ireneisdoomed** [comment]
Many thanks! I will provide feedback as soon as the release comes out.
