### ISSUE TITLE
thyroid disease (Thyroiditis) classification

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#121]
'autoimmune thyroid disease' should be a subtype of 'thyroid disease'.
'Thyroiditis' should be a synonym of 'thyroid disease'.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:EDIT autoimmune thyroid disease (EFO:00006812)
Subclass of thyroid disease (EFO:1000627)

- [ ] EFO:EDIT thyroid disease (EFO:1000627)
Synonym: Thyroiditis
