### ISSUE TITLE
New term request for Kim SK PMID 33606446

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1211]
For new term requests, please provide the following information:

## Preferred term label

Achilles tendon injury

## Textual definition

Any injury to the Achilles tendon, including bursitis, tendinitis, rupture or degeneration. 

## Suggested parent term

tendinopathy https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1001434&viewMode=All&siblings=false

##existing terms:
Abnormality of the Achilles tendon - https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0005109&viewMode=PreferredRoots&siblings=false

Achilles tendonitis: https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0025273 (I think this should be tendinitis?) - not in EFO

#further info
see Table 1 in paper for a list of included case phenotypes.

**Comment by earlEBI** [comment]
@kallia-p hi, just nudging this one, thank you

**Comment by kallia-p** [comment]
@earlEBI 'Achilles tendon injury' EFO_0600078
Parent term is 'leg injury' EFO_0009508
