### ISSUE TITLE
New term request for Gao PMID 33610756

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1212]
For new term requests, please provide the following information:

## Preferred term label

response to mitochondrial complex I inhibitor

## Synonyms

NA

## Textual definition

mitochondrial complex I inhibitor blocks neurodegeneration and cognitive decline in Alzheimer’s disease

## Suggested parent term
response to drug
## Attribution

##Other info
MCI is defined as a small molecule druggable target with downstream signalling that engages multiple neuroprotective mechanisms alleviating cognitive decline and neurodegeneration

If you would like a nanoattribution, please indicate your ORCID id

**Comment by kallia-p** [comment]
@Santhi1901 
Added new term - EFO:0600033 response to mitochondrial complex I inhibitor
Parent -  response to drug
Definition - Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a mitochondrial complex I inhibitor stimulus. MCI is a small molecule druggable target with downstream signalling that engages multiple neuroprotective mechanisms alleviating cognitive decline and neurodegeneration.
