### ISSUE TITLE
Iodine Deficiency Hypothyroidism

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#122]
For new term requests, please provide the following information:

## Preferred term label

Iodine Deficiency Hypothyroidism

## Synonyms

Hypothyroidism due to Iodine Deficiency
Subclinical iodine deficiency hypothyroidism

## X-refs

NCIT_C132053
UMLS CUI CL520437
ICD10 E02

## Textual definition

Hypothyroidism due to insufficient intake of iodine. [ NCI ]

## Suggested parent term

hypothyroidism

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW Iodine Deficiency Hypothyroidism
    -  Subclass of hypothyroidism (EFO:0004705)
    -  Synonyms: Hypothyroidism due to Iodine Deficiency || Subclinical iodine deficiency hypothyroidism
    -  X-refs: NCIT:C132053 || UMLS_CUI:CL520437 || ICD10:E02
    - Definition: Hypothyroidism due to insufficient intake of iodine. [ NCI ]

**Comment by zoependlington** [comment]
Here's the ID for the new term:
EFO:0008614 || Iodine Deficiency Hypothyroidism
