### ISSUE TITLE
Cystic Kidney Disease

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#123]
For new term requests, please provide the following information:

## Preferred term label

Cystic Kidney Disease
Please include all subtypes of [http://purl.obolibrary.org/obo/NCIT_C34750](http://purl.obolibrary.org/obo/NCIT_C34750)

## Synonyms

Cystic Kidney Diseases
Cystic Renal Diseases
Kidney, Cystic

## X-refs
NCIT_C34750
MESH D052177
DOID 
ICD10 Q61
UMLS CUI C1691228

## Textual definition

A congenital or acquired kidney disorder characterized by the presence of renal cysts. [ NCI ]

## Suggested parent term

kidney disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008621 || Microcystic Renal Disease
EFO:0008620 || Polycystic Kidney Disease
EFO:0008619 || Simple Cyst of Kidney
EFO:0008618 || Medullary Cystic Kidney Disease Type II 
EFO:0008617 || Medullary Cystic Kidney Disease Type I 
EFO:0008616 || Complex Cyst of Kidney 
EFO:0008615 || Cystic Kidney Disease
