### ISSUE TITLE
Requests for new terms for HCA 

### ISSUE THREAD

**Issue by Wkt8** [EBISPOT/efo#1232]
We would like to add the 'Analysis' term as a subclass under 'Experimental process', and add three terms as subclasses under 'Analysis'. These three terms will be used to describe different types of analysis processes. I have included all the information here but am happy to split them into separate tickets if that is better for you @paolaroncaglia 

## Preferred term label
Analysis

## Synonyms
Data Analysis

## Textual definition
A process which involves analysing or interpreting data (sequence files, images, etc.) to generate analysis files (count matrices, barcode lists, spatial transcriptomics, etc.) 

## Suggested parent term
Experimental process: EFO:0002694

----------------
As stated above, we would like to add terms that would be subclasses of the parent term 'Analysis'. These terms are:
- raw matrix generation
Definition: Processes involved in generating a raw matrix from raw data

- processed matrix generation
Definition: Processes involved in generating a processed matrix from sequence data and/or count matrices, including demultiplexing samples, quality control, normalization, data correction, and feature selection

- analysis of matrices
Definition: Processes involved in analysing expression matrices, including visualisation, comparison or integration with other datasets, clustering, differential expression analysis 

- spatial analysis 
Definition: Processes involved in analysing spatial images or data

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,
Thanks. It's ok to keep these term requests in one ticket as they are related, no need to open other tickets. I'm just back from summer leave and will address this over the next few days. Meanwhile, quick notes for self:
- [ ] The EDAM ontology likely has some useful terms that we could import into HCAO, I'll need to check that, as well as how/where those EDAM terms would fit in HCAO (I don't anticipate major issues, but I've not imported EDAM classes before).

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,

- [ ] With regard to your request for a new term labelled 'analysis' (with synonym "data analysis"), EFO already has OBI:0200000 'data transformation' (subclass of 'experimental process') with exact synonyms "data analysis" and "data processing"; the OBI/EFO definitions fit well with the one you proposed above. Therefore, I suggest to use OBI:0200000 'data transformation', which is already in HCAO (see [here](https://ontology.archive.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0200000)), instead of the requested new term 'analysis'. Please let me know if this won't work for you.
- [ ] With regard to the 4 terms you requested as children of 'analysis', I'll create them as subclasses of EFO OBI 'data transformation'.
- [ ] Could you please provide your ORCID and, if possible, references for the 4 new terms. If general references are not straightforward to find, PMIDs of articles that use those kinds of data transformation would also be acceptable.

Thanks,
Paola

**Comment by Wkt8** [comment]
Hey Paola,

Thank you - that works perfectly! As long as it is a subclass of ‘experimental process’ we are happy with ‘data transformation’. Great to hear about the 4 terms as children of ‘data transformation’.

My ORCID is https://orcid.org/my-orcid?orcid=0000-0002-6583-8504 

I have added 4 general references here: 

raw matrix generation (https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/rna-seq-reads-to-counts/tutorial.html) (https://www.embopress.org/doi/full/10.15252/msb.20188746) “Raw data generated by sequencing machines are processed to obtain matrices of molecular counts (count matrices) or, alternatively, read counts (read matrices),” 
I have added two references here to generating raw matrices. 


processed matrix generation (https://scrnaseq-course.cog.sanger.ac.uk/website/construction-of-expression-matrix.html)  
This is a reference to generating processed matrices. 
Definition: Processes involved in generating a processed matrix from sequence data and/or count matrices, including demultiplexing samples, quality control, normalization, data correction, and feature selection 


analysis of matrices (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6700744/) (PMID: 29608179) 
This is a PMID of an article discussing this data transformation. 
Definition: Processes involved in analysing expression matrices, including visualisation, comparison or integration with other datasets, clustering, differential expression analysis 


spatial analysis (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7864098/ PMID: 33406409) 
This is a PMID of an article which uses this data transformation. 
 Definition: Processes involved in analysing spatial images or data 

Please let me know if any of these need more detail!

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,

Thanks for your reply and for all the info:

> As long as it is a subclass of ‘experimental process’ we are happy with ‘data transformation’.

It is, so all's good.

> I have added 4 general references here:

That's great, thanks. I'll include the PMIDs (note for self: the embopress one is PMID:31217225), but the links to the training courses, however helpful, might become stale after some time, so we'd rather not add them. 
I now have all the details I need, so I'll add the 4 new EFO terms in time for the next EFO release (scheduled for Sept 15th). I'll comment here with the new IDs when ready. They should then be available in the HCAO release scheduled for Sept 16th. The OLS instance will probably be deployed within a couple of working days after the HCAO release.

Best, 
Paola

**Comment by paolaroncaglia** [comment]
Hi @Wkt8 ,
The new terms are

EFO_0030022 (raw matrix generation)
EFO_0030023 (processed matrix generation)
EFO_0030024 (analysis of matrices)
EFO_0030025 (spatial analysis)

Best wishes,
Paola
