### ISSUE TITLE
NTR: sci-Plex

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1234]
For new term requests, please provide the following information:

## Preferred term label

sci-Plex

## Textual definition

The combination of nuclear hashing and sci-RNA-seq into a single workflow for multiplex transcriptomics, enabling the capture of gene expression profiles from thousands of experimental conditions in a single experiment. PMID:31806696

## Suggested parent term

EFO:0010550 [sci-RNA-seq]

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,
I'll address this request in time for the next EFO and HCA ontology releases, and will comment here when done.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,

The new term is EFO_0030026 (sci-Plex).
It will be available with the next EFO release (scheduled for tomorrow) and then in the HCAO release currently scheduled for the day after tomorrow (the OLS instance may take a couple of extra days to be deployed).

Best wishes,

Paola
