### ISSUE TITLE
New term request for Ahlstrom PMID 33676726

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1235]
For new term requests, please provide the following information:

## Preferred term label

response to neuromuscular blocker

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a neuromuscular blocker.

## Suggested parent term

response to drug

## further info

GWAS on: rocuronium dose requirement in breast cancer surgery. 
"Rocuronium, a common neuromuscular blocking agent"

**Comment by kallia-p** [comment]
@earlEBI Added new term EFO_0600034
