### ISSUE TITLE
NTR: snmC-Seq2

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1236]
For new term requests, please provide the following information:

## Preferred term label

snmC-Seq2

## Synonyms

single nucleus methylcytosine sequencing v2

## Textual definition

A protocol for single nucleus methylcytosine sequencing. snmC-seq2 provides improved read mapping, reduced artifactual reads, enhanced throughput, as well as increased library complexity and coverage uniformity compared to snmC-seq.
PMID:30237449

## Suggested parent term

EFO:0002761 [methylation profiling by high throughput sequencing]
EFO:0010183 [single cell library construction]

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,
I'll address this request in time for the next EFO and HCA ontology releases, and will comment here when done.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,
The new term is EFO_0030027 (snmC-Seq2).
Best,
Paola
