### ISSUE TITLE
NTR: sci-RNA-seq3

### ISSUE THREAD

**Issue by ESapenaVentura** [EBISPOT/efo#1239]
For new term requests, please provide the following information:

## Preferred term label

sci-RNA-seq3

## Synonyms

Sci-RNA-Seq3, sci-RNA-Seq3

## Textual definition

Single-cell combinatorial indexing (‘sci-’) is a methodological framework that employs split-pool barcoding to uniquely label the nucleic acid contents of large numbers of single cells or nuclei. The sci-RNA-seq3 is an updated version of sci-RNA-seq. The major improvements are:

(1) nuclei are extracted directly from fresh tissues without enzymatic treatment;

(2) hairpin ligation for the third level indexing (barcoded Tn5 tagmentation was used in the previous version);

(3) individually optimised enzymatic reactions;

(4) FACS was replaced by dilution, and sonication and filtration steps were added to minimize aggregation.

Protocols.io DOI: 10.17504/protocols.io.9yih7ue

## Suggested parent term

[sci-RNA-seq](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010550)

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
I'll address this request in time for the next EFO release (mid September). Thanks.
Paola

**Comment by ESapenaVentura** [comment]
Many thanks @paolaroncaglia !

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
The new term is EFO_0030028 (sci-RNA-seq3).
It will be available with tomorrow's EFO release, and then in the HCAO release scheduled for the day after tomorrow (plus possibly a couple of days for the OLS instance to be deployed).
Best,
Paola
