### ISSUE TITLE
female genital tract polyp

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#124]
Intermediate class

## Preferred term label

female genital tract polyp

## Synonyms

Polyp of female genital tract
polyp in the female reproductive tract
polyps in female reproductive organs

## X-refs
ICD10 N84

## Suggested parent term

vulva fibroepithelial polyp => female genital tract polyp => polyp

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW female genital tract polyp
    - Subclass of polyp (EFO:0000662)
    - has_disease_location some 
    ('female reproductive system' or (part_of some 'female reproductive system'))
    - Synonyms: Polyp of female genital tract || polyp in the female reproductive tract || polyps in female reproductive organs
    - X-refs: ICD10:N84
    - Definition: A soft and painless polypoid mass that arises from the female genital tract.

- [ ] EFO:EDIT vulva fibroepithelial polyp (EFO:1000777)
    - subclass of female genital tract polyp (EFO:NEW)
    - remove as subclass of polyp (EFO:0000662)

**Comment by zoependlington** [comment]
Here's the ID for the new term:
EFO:0008622 || female genital tract polyp
