### ISSUE TITLE
New term request for Quant-seq

### ISSUE THREAD

**Issue by xiaosaiyao** [EBISPOT/efo#1242]
For new term requests, please provide the following information:

## Preferred term label
Quant-seq

## Synonyms

quantseq, quant-seq, QuantSeq

## Textual definition

QuantSeq provides an easy protocol to generate highly strand-specific next-generation sequencing (NGS) libraries close to the 3′ end of polyadenylated RNAs within 4.5 h (https://doi.org/10.1038/nmeth.f.376)

## Suggested parent term

EFO:0002770 (transcription profiling by high throughput sequencing)
EFO:0001457 (RNA assay)

**Comment by paolaroncaglia** [comment]
Hi @xiaosaiyao ,
I'll add your requested term in time for the next EFO release (mid-September).
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Hi @xiaosaiyao ,
The new term is EFO_0030030 (Quant-seq).
It will be visible in the next EFO release, scheduled for tomorrow.
Best wishes,
Paola Roncaglia
