### ISSUE TITLE
Provide a simple list of Mondo ids 

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#1244]
Provide a list of Mondo is as a txt file that are use in EFO - in their original or their translated form. This list should be kept up to date with each release, and will be used by the Mondo team to protect certain terms against deprecation.

- should be added to makefile
- should be added to "how to run a release" workflow

**Comment by zoependlington** [comment]
All EFO curated mappings can be found here: https://github.com/EBISPOT/efo/blob/master/src/ontology/components/mondo_efo_mappings.tsv
And all Mondo terms that are purposefully imported (for one reason or another, e.g. they are part of the mappings or have been requested to be imported) are here: https://github.com/EBISPOT/efo/blob/master/src/ontology/iri_dependencies/mondo_terms.txt

Both are kept up to date for each EFO release.

**Comment by matentzn** [comment]
Thank you Zoë; our goal to make it somehow easier to protect the Mondo terms used by collaborators a bit more, and it would be convenient if we could simply get a single file with all of the IDs rather than having to look at two files, extract columns etc. So from the Mondo perspective we want to encourage users to produce a list of Mondo IDs in a text file that contains just that; would it be an option to provide and maintain one like that?

**Comment by zoependlington** [comment]
In that case, you will only need the second file as that has all of the Mondo terms that are important to EFO in it in a simple text file list :-)

**Comment by matentzn** [comment]
So the second list has all terms that are imported from Mondo and the once that are mapped as well? That's great!

**Comment by zoependlington** [comment]
Yeah, it contains all Mondo terms, including mapped terms and imported terms.

**Comment by matentzn** [comment]
Perfect! thank you @zoependlington :) The issue is now moved to Mondo, thanks for the help: https://github.com/monarch-initiative/mondo/issues/3586
