### ISSUE TITLE
Please add new term (SCOPE-chip) and add to HCAO

### ISSUE THREAD

**Issue by pnejad** [EBISPOT/efo#1245]
## Preferred term label

SCOPE-chip 

## Synonyms
GEXSCOPE

## Textual definition

The SCOPE-chip™ captures single cells by partitioning single cells into hundreds of thousands of microwells on the chip following the Poisson distribution. Afterwards, an excess of Barcoding Beads is added to the microwells of the chip; the diameter of the beads versus that of the microwells ensuring that only one Barcoding Bead falls into each microwell. After cell lysis, Barcoding Beads, each with an unique cell label (Barcode), capture mRNA by binding to the poly (A) tail on the mRNA. Barcoding Beads are subsequently collected from the microwell chip, followed by reverse transcription of the mRNA captured by the Barcoding Beads into cDNA, and subsequent PCR amplification. The amplified cDNA is then fragmented and ligated with sequencing adapters. The end result is an NGS library that is compatible with Illumina sequencing instruments, that can also be run on Pacbio and MGI sequencing platforms with minor modifications.

By increasing the ratio of the number of microwells on chip to the number of cells loaded, the SCOPE-chip™ can maintain a low doublet rate. Meanwhile, by selecting different chip throughput and microwell sizes, the SCOPE-chip™ can analyze 500 – 30,000 single cells simultaneously and accommodate different cell morphologies and sizes.

Taken from: https://www.singleronbio.com/product/detail-18.html

## Suggested parent term

single cell library construction (EFO:0010183)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @pnejad ,

Thanks for the info and for opening the ticket directly in the EFO tracker, I confirm that this is the right place for terms related to single-cell technologies. I'll add the new EFO term in time for the next EFO release (~Sept 15th) and we'll then import it into the following HCAO release (~Sept 16th). As usual, we'll tag you in the HCAO release ticket.
- [ ] I might shorten the proposed definition and leave out the second paragraph which contains detailed "gloss" that's not strictly necessary. 
- [ ] Could you please provide PMID or other reference of the study you're wrangling where the technology is used, if applicable?
- [ ] I'll also add your ORCID ( https://orcid.org/0000-0002-3163-0115)

Thanks,
Paola

**Comment by pnejad** [comment]
Thank you @paolaroncaglia! 

This method was mentioned in GSE165399, which is associated with this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8315026/

**Comment by paolaroncaglia** [comment]
Thanks @pnejad .

**Comment by paolaroncaglia** [comment]
@pnejad
The new term is EFO_0030031 (SCOPE-chip).
