### ISSUE TITLE
Candidates for obsoletion in Mondo - Mondo grouping classes

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#1249]
Hi, The following terms below are proposed obsoletion candidates in Mondo. These are meta grouping classes that are under the top-level 'disease or disorder' term, and upon discussions on the Mondo curation calls, it seems these are not clinically relevant and are difficult to maintain, so we propose obsoleting these terms in a future release (on or after December 2021).

We can see these are being used by EFO, so we wanted to check with you all before proceeding. Please let us know your thoughts or we'd be happy to have a call as well, thanks! 

| Mondo ID             |        Label                                              |        proposed obsoletion   date |
|----------------------|-----------------------------------------------------------|--------------------------|
|        MONDO:0021194 |              disease by subcellular system affected       |        12/1/21           |
| MONDO:0021195        |         disease by cellular process disrupted             |         12/2/21          |
| MONDO:0021196        |         disease by molecular activity disrupted           |         12/3/21          |
| MONDO:0021197        |         disease by cellular component affected            |         12/4/21          |
| MONDO:0021199        |         disease by anatomical system                      |         12/5/21          |
| MONDO:0024505        |         disorder by anatomical region                     |         12/6/21          |
| MONDO:0044969        |         disease of membrane bound organelle               |         12/7/21          |
| MONDO:0044971        |         disease of macromolecular complex                 |         12/8/21          |
| MONDO:0044974        |         disease of supramolecular complex                 |         12/9/21          |
| MONDO:0044975        |         disease of transporter activity                   |         12/10/21         |
| MONDO:0044976        | disease   of catalytic activity                           | 12/11/21                 |
| MONDO:0044977        | disease   of receptor activity                            | 12/12/21                 |
| MONDO:0044979        | disease   by cell type                                    | 12/13/21                 |
| MONDO:0044980        |         disease of signal transduction                    |         12/14/21         |

related to https://github.com/monarch-initiative/mondo/issues/3661
cc @sabrinatoro

**Comment by zoependlington** [comment]
Thanks @nicolevasilevsky! I will need to check some of these against our Open Targets version of EFO, but all should be well!
