### ISSUE TITLE
dysthymic disorder

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#125]
For new term requests, please provide the following information:

## Preferred term label

dysthymic disorder

## Synonyms

Persistent depressive disorder
dysthymia
persistent mood

## X-refs
ICD10 F34
DOID_12139
NCIT_C34562
UMLS CUI C0013415
MESH D019263

## Textual definition

A chronic mood disorder in which the symptoms are similar to, though milder than, those diagnosed in depression. [ NCI ]

## Suggested parent term

mood disorder

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Here's the ID for the new term:
EFO:0008623 || dysthymic disorder
