### ISSUE TITLE
New term request for Gurung PMID 33889958

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1252]
For new term requests, please provide the following information:

## Preferred term label

leucine rich alpha-2-glycoprotein 1 measurement

## Synonyms

LRG1

## Textual definition

Quantification of leucine rich alpha-2-glycoprotein 1 present in a sample.

## Suggested parent term

inflammation biomarker measurement - http://www.ebi.ac.uk/efo/EFO_0004872

blood protein measurement - http://www.ebi.ac.uk/efo/EFO_0007937

## further info

Already existing in NCIT - http://purl.obolibrary.org/obo/NCIT_C165973

"Elevated levels of plasma leucine-rich α-2-glycoprotein 1 (LRG1), a component of transforming growth factor beta signaling, are associated with development and progression of chronic kidney disease in patients with type 2 diabetes (T2D)."

**Comment by kallia-p** [comment]
@earlEBI New term added 'plasma leucine rich alpha-2-glycoprotein 1 measurement' EFO_0600050 with parent terms as suggested
