### ISSUE TITLE
vitreous body disorders

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#126]
For new term requests, please provide the following information:

## Preferred term label

vitreous body disease
vitreous prolapse
vitreous hemorrhage
Hyalitis
eye hemorrhage

### vitreous body disease
vitreous body disorder

### vitreous prolapse
prolapse of vitreous body
intraocular content prolapse
prolapse of the intraocular contents

### vitreous hemorrhage
Vitreous Hemorrhage Fluid
Blood In Vitreous
Blood In Vitreous Fluid, 
Vitreous Fluid, Blood In
vitreous body hemorrhage

### eye hemorrhage
Bleeding from the eye
Hemorrhage of the eye

### Hyalitis
Hyaloiditis
Vitritis
Vitreitis

### vitreous body disease
NCIT_C45256
UMLS CUI C0155365
ICD10 H43

### vitreous prolapse
ICD10 H43.0

### vitreous hemorrhage
ICD10 H43.1
HP_0007902
NCIT_C50469
MESH D014823
MP_0006202

### eye hemorrhage
MSH:D005130
UMLS:C0015402
SNOMEDCT_US:417244000
SNOMEDCT_US:93478000
MP_0006203
HP_0011885

### Hyalitis
NCIT_C50587
UMLS CUI C0235812

### vitreous body disease
Any disease affecting the vitreous body of the eye. [ NCI ]

### vitreous prolapse
Prolapse of the vitreous material through the defect in the zonule around the lens and into the anterior chamber.

### vitreous hemorrhage
Blood extravasation in the vitreous humor. Causes include neovascularization, retinal tear, retinal detachment, and rupture of a blood vessel aneurysm in the eye. [ NCI ]

### eye hemorrhage
Bleeding from vessels of the various tissues of the eye. [ DDD:akelly ]

### Hyalitis
Inflammatory intraocular reaction with clouding and cells in vitreous; often accompanies inflammation of ciliary body, iris, choroid, or retina. [ NCI ]

## Suggested parent term

vitreous body disease => eye disease
eye hemorrhage => eye disease
vitreous prolapse => vitreous body disease
Hyalitis => vitreous body disease
vitreous hemorrhage => vitreous body disease
vitreous hemorrhage => eye hemorrhage

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW1 vitreous body disease
    - Subclass of eye disease (EFO:0003966)
    - Synonyms: vitreous body disorder
    - X-refs: NCIT:C45256 || UMLS_CUI:C0155365 || ICD10:H43
    - Definition: Any disease affecting the vitreous body of the eye. [ NCI ]
    
- [ ] EFO:NEW2 vitreous prolapse
    - Subclass of vitreous body disease (EFO:NEW1)
    - Synonyms: prolapse of vitreous body || intraocular content prolapse || prolapse of the intraocular contents
    - X-refs: ICD10:H43.0
    - Definition: Prolapse of the vitreous material through the defect in the zonule around the lens and into the anterior chamber.
    
- [ ] EFO:NEW3 vitreous hemorrhage
    - Subclass of vitreous body disease (EFO:NEW1)
    - Subclass of eye hemorrhage (EFO:NEW5)
    - Synonyms: Vitreous Hemorrhage Fluid || Blood In Vitreous || Blood In Vitreous Fluid, || Vitreous Fluid, Blood In || vitreous body hemorrhage
    - X-refs: ICD10:H43.1 || HP:0007902 || NCIT:C50469 || MESH:D014823 || MP:0006202
    - Definition: Blood extravasation in the vitreous humor. Causes include neovascularization, retinal tear, retinal detachment, and rupture of a blood vessel aneurysm in the eye. [ NCI ]
    
- [ ] EFO:NEW4 Hyalitis
    - Subclass of vitreous body disease (EFO:NEW1)
    - Synonyms: Hyaloiditis || Vitritis || Vitreitis
    - X-refs: NCIT:C50587 || UMLS_CUI:C0235812
    - Definition: Inflammatory intraocular reaction with clouding and cells in vitreous; often accompanies inflammation of ciliary body, iris, choroid, or retina. [ NCI ]
    
- [ ] EFO:NEW5 eye hemorrhage
    - Subclass of eye disease (EFO:0003966)
    - Synonyms: Bleeding from the eye || Hemorrhage of the eye
    - X-refs: MSH:D005130 || UMLS:C0015402 || SNOMEDCT_US:417244000 || SNOMEDCT_US:93478000 || MP_0006203 || HP_0011885
    - Definition: Bleeding from vessels of the various tissues of the eye. [ DDD:akelly ]

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008628 || Hyalitis
EFO:0008627 || eye hemorrhage
EFO:0008626 || vitreous hemorrhage
EFO:0008625 || vitreous prolapse 
EFO:0008624 || vitreous body disease
