### ISSUE TITLE
Potential Mondo terms to be merged (in use by EFO)

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#1264]
Hi, Reporting additional Mondo terms that are proposed for obsoletion and merge in Mondo. We propose obsoleting/merging these terms in a future release (on or after December 2021).

We can see these are being used by EFO, so we wanted to check with you all before proceeding. Please let us know your thoughts or we'd be happy to have a call as well, thanks! 

| Mondo   ID (this ID will be obsoleted) | Label                                | Mondo   ID (this will be the. new ID) | Label   (this will be the new label)                  | GitHub   ticket                                         | Comment                                                                                                                 |
|----------------------------------------|--------------------------------------|---------------------------------------|-------------------------------------------------------|---------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------|
| MONDO:0006819                          | kernicterus                          | MONDO:0018477                         | bilirubin   encephalopathy                            | https://github.com/monarch-initiative/mondo/issues/3604 | This   will be merged in the December release with MONDO:0018477 bilirubin   encephalopathy.                            |
| MONDO:0010302                          | Ito   hypomelanosis                  | MONDO:0016985                         | Nevus   of Ito                                        | https://github.com/monarch-initiative/mondo/issues/3598 | This   will be merged in the December release with MONDO:0016985 Nevus of Ito.                                          |
| MONDO:0011379                          | medullary   cystic kidney disease 2' | MONDO_0008073                         | familial   juvenile hyperuricemic nephropathy type 1' | https://github.com/monarch-initiative/mondo/issues/1880 | This   will be merged in the December release with MONDO_0008073 familial juvenile   hyperuricemic nephropathy type 1'. |
  
Related to https://github.com/EBISPOT/efo/issues/1249
cc @sabrinatoro

**Comment by zoependlington** [comment]
Thanks for letting us know @nicolevasilevsky! We will remove the mappings after the Mondo release.
