### ISSUE TITLE
New term request for shRNA-seq

### ISSUE THREAD

**Issue by Jfortin1** [EBISPOT/efo#1268]
For new term requests, please provide the following information:

## Preferred term label

shRNA-seq

## Synonyms

shRNA-Seq, shrna-seq, shrna-Seq

## Textual definition

Amplicon sequencing of shRNAs from RNAi pooled genetic screens.
PMID:23394947

## Suggested parent term

EFO:0003747 (Amplicon sequencing)
EFO:0001456 (DNA assay)

## Attribution

ORCID id: 0000-0001-9328-3852

**Comment by paolaroncaglia** [comment]
Dear @Jfortin1 ,

Similarly to https://github.com/EBISPOT/efo/issues/1267#issuecomment-924911169, could you please provide your ORCID iD and/or references for shRNA-seq?

Thanks,

Paola

**Comment by Jfortin1** [comment]
Updated, thanks!

**Comment by paolaroncaglia** [comment]
@Jfortin1 thanks again.
