### ISSUE TITLE
New term request for Chenoweth PMID 33713409

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1269]
For new term requests, please provide the following information:

## Preferred term label

response to varenicline

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of varenicline, a smoking cessation treatment.

## Suggested parent term

response to drug

- suggest create parent term under 'response to drug' - 'response to smoking cessation treatment'?

**Comment by kallia-p** [comment]
Parent term 'response to smoking cessation agent' EFO_0600051
Definition: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a smoking cessation agent. These include nicotine replacement therapy (NRT) agents that are available as nicotine patches, gums, lozenges or inhalers and nicotinic receptor antagonists such as varenicline and buproprion.

response to varenicline EFO_0600052
Definition: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of varenicline, a nicotinic acetylcholine receptor agonist used as a smoking cessation agent. Varenicline is also used for the treatment of dry eye disease.

**Comment by kallia-p** [comment]
@earlEBI please see new terms added above
