### ISSUE TITLE
Synovitis and Acute Synovitis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#127]
For new term requests, please provide the following information:

## Preferred term label

synovitis
acute synovitis

### synovitis
Synovial Hypertrophy
Synovial Thickening

### synovitis
NCIT_C50766
UMLS CUI C0039103
DOID_2703
MESH D013585
HP_0100769

### acute synovitis
NCIT_C97140
UMLS CUI C1739148

### synovitis
Inflammation of the SYNOVIAL MEMBRANE [ MeSH ]

### acute synovitis
An acute inflammation of a synovial membrane. It is associated with swelling and pain in the affected area. [ NCI ]

## Suggested parent term

acute synovitis => synovitis => rheumatic disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] EFO:NEW1 synovitis
     - subclass of rheumatic disease (EFO:0005755)
     - has_disease_location some ('synovial membrane' or (part of 'synovial membrane'))
     - **synonyms:** Synovial Hypertrophy || Synovial Thickening 
     - **X-refs:** NCIT:C50766 || UMLS_CUI:C0039103 || DOID:2703 || MESH:D013585 || HP:0100769
     - **Description:** Inflammation of the SYNOVIAL MEMBRANE [ MeSH ]

- [ ] EFO:NEW2 acute synovitis
     - subclass of synovitis (EFO:NEW1)
     - **X-refs:** NCIT:C97140 || UMLS_CUI:C1739148
     - **Description:** An acute inflammation of a synovial membrane. It is associated with swelling and pain in the affected area. [ NCI ]

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO:0008997 || synovitis 
EFO:0008998 || acute synovitis
