### ISSUE TITLE
New term request for Carrera PMID 33723576

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1270]
For new term requests, please provide the following information:

## Preferred term label

Parenchymal hematoma

## Textual definition

A severe presentation of intracerebral bleeding.

## Suggested parent term

intracerebral hemorrhage

## info from text:

"Haemorrhagic transformation is a complication of recombinant tissue-plasminogen activator treatment. The most severe form, parenchymal haematoma, can result in neurological deterioration, disability, and death."

**Comment by zoependlington** [comment]
Added as EFO_0020101, which will be available on 17th January after the release.
