### ISSUE TITLE
New term request for Carrera PMID 33723576

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1271]
For new term requests, please provide the following information:

## Preferred term label

response to thrombolytic therapy

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a thrombolysis stimulus.

## Suggested parent term

response to drug

**Comment by kallia-p** [comment]
@earlEBI Suggestion to make this term more specific 'response to recombinant tissue-plasminogen activator' would this be OK down the GWAS catalog end?

**Comment by earlEBI** [comment]
@kallia-p that would be great, thank you

**Comment by kallia-p** [comment]
@earlEBI response to recombinant tissue-plasminogen activator EFO_0600080

Definition: Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a recombinant tissue-plasminogen activator stimulus, a type of systemic thrombolytic agent.
