### ISSUE TITLE
NTR: MONDO:0054701 Kleefstra syndrome 2

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/efo#1273]
For new term requests, please provide the following information:

## Preferred term label

Kleefstra syndrome 2

## Synonyms

n/a

## Textual definition

A Kleefstra syndrome that is characterized by delayed psychomotor development, variable intellectual disability, and mild dysmorphic features and has_material_basis_in heterozygous mutation in the KMT2C gene on chromosome 7q36.

## Suggested parent term

Same as:

MONDO:0054701 and DOID:0080598

## Attribution

If you would like a nanoattribution, please indicate your ORCID id: ORCID iD: 0000-0003-4062-6158

**Comment by zoependlington** [comment]
I have imported the Mondo term into EFO and it will be available in our October (18th) release.
