### ISSUE TITLE
New term request for Lores-Motta L PMID 34260947 (parent term)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1274]
For new term requests, please provide the following information:

## Preferred term label

Complement factor H-related proteins measurement 

## Synonyms

FHR proteins measurement

## Textual definition
quantification of the amount of complement factor H-related proteins in a sample

## Suggested parent term

https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0007937

## Attribution

NA

**Comment by kallia-p** [comment]
@buniello 
parent term complement factor H-related proteins measurement EFO_0600053
