### ISSUE TITLE
ovarian dysfunction classes

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#128]
For new term requests, please provide the following information:

## Preferred term label

ovarian dysfunction
hyperestrogenism
premature menopause
hyperandrogenism
Adrenal Hyperandrogenism
Ovarian Hyperandrogenism
primary ovarian insufficiency (already in EFO)

### hyperestrogenism
Estrogen excess

### hyperandrogenism
Androgen Excess

### Adrenal Hyperandrogenism
Adrenal Androgen Excess

### premature menopause
Menopause - premature
Menopause praecox

### primary ovarian insufficiency
POF

### ovarian dysfunction
DOID_1414

### hyperestrogenism
DOID_14336

### hyperandrogenism
NCIT_C113215
UMLS CUI C0206081

### Adrenal Hyperandrogenism
NCIT_C113209
UMLS CUI C3831597

### Ovarian Hyperandrogenism
NCIT_C120146
UMLS CUI C3897086

### premature menopause
DOID_10787

### hyperestrogenism
Abnormally high level of estrogen. [ NICHD NCI ]

### hyperandrogenism
Excessive secretion of androgens from the adrenal glands or gonads. Clinical manifestations may include virilization. [ NICHD NCI ]

### Adrenal Hyperandrogenism
Excessive secretion of the androgen hormones dehydroepiandrosterone (DHEA), DHEA sulfate, and androstenedione, from the adrenal gland. Clinical manifestations may include virilization. [ NICHD NCI ]

### Ovarian Hyperandrogenism
Increased production of androgens by the ovaries. [ NCI ]

## Suggested parent term

ovarian dysfunction => ovarian disease
hyperestrogenism => ovarian dysfunction
premature menopause => ovarian dysfunction
hyperandrogenism => ovarian dysfunction
Adrenal Hyperandrogenism => hyperandrogenism
Ovarian Hyperandrogenism => hyperandrogenism
primary ovarian insufficiency => ovarian dysfunction (this is in addition to the other classification)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW1** ovarian dysfunction
     - subclass of ovarian disease (EFO:0005771)
     - **X-refs:** DOID:1414
     - **Definition:** The inability of the ovaries to function. [ NCI ]

- [ ] **EFO:NEW2** hyperestrogenism
     - subclass of ovarian dysfunction (EFO:NEW1)
     - **Synonyms:** Estrogen excess
     - **X-refs:** DOID:14336
     - **Definition:** Abnormally high level of estrogen. [ NICHD NCI ]

- [ ] **EFO:NEW3** premature menopause
     - subclass of ovarian dysfunction (EFO:NEW1)
     - **Synonyms:** Menopause - premature || Menopause praecox
     - **X-refs:** DOID:10787 || wiki/Premature_ovarian_failure
     - **Definition:** The loss of normal function of the ovaries before age 40.

- [ ] **EFO:NEW4** hyperandrogenism
     - subclass of ovarian dysfunction (EFO:NEW1)
     - **Synonyms:** Androgen Excess
     - **X-refs:** NCIT:C113215 || UMLS_CUI:C0206081
     - **Description:** Excessive secretion of androgens from the adrenal glands or gonads. Clinical manifestations may include virilization. [ NICHD NCI ]

- [ ] **EFO:NEW5** Adrenal Hyperandrogenism
     - subclass of hyperandrogenism (EFO:NEW4)
     - **Synonyms:** Adrenal Androgen Excess
     - **X-refs:** NCIT:C113209 || UMLS_CUI:C3831597
     - **Definition:** Excessive secretion of the androgen hormones dehydroepiandrosterone (DHEA), DHEA sulfate, and androstenedione, from the adrenal gland. Clinical manifestations may include virilization. [ NICHD NCI ]

- [ ] **EFO:NEW6** Ovarian Hyperandrogenism
     - subclass of hyperandrogenism (EFO:NEW4)
     - **X-refs:** NCIT:C120146 || UMLS_CUI:C3897086
     - **Definition:** Increased production of androgens by the ovaries. [ NCI ]

- [ ] **EFO:EDIT** primary ovarian insufficiency (already in EFO)
     - Add as subclass of ovarian dysfunction (EFO:NEW1) without removing other classification

**Comment by zoependlington** [comment]
Here are the Ids for the new terms:
EFO_0009008 || Ovarian Hyperandrogenism
EFO_0009007 || Adrenal Hyperandrogenism
EFO_0009006 || hyperandrogenism
EFO_0009005 || premature menopause
EFO_0009004 || hyperestrogenism
EFO_0009003 || ovarian dysfunction

**Comment by gkos-bio** [comment]
Will they be added to the May release?

**Comment by zoependlington** [comment]
@gkos-bio Yes
