### ISSUE TITLE
updated list of candidates for obsoletion in Mondo

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#1280]
Hi @zoependlington 
Mondo is considering obsoleting the following terms for either the November or December release (it is marked in the file:
https://github.com/monarch-initiative/mondo/blob/master/reports/obsoletion-candidates/2021-10-01-report-obsoletioncandidates-withcomment.tsv

This is an updated list of Mondo terms that are being used by EFO:
https://github.com/monarch-initiative/mondo/blob/master/reports/obsoletion-candidates/2021-10-01-ObsoletionCandidatesInUseByEFO.tsv

This overlaps with tickets https://github.com/EBISPOT/efo/issues/1264 and https://github.com/EBISPOT/efo/issues/1249

We plan to generate reports in this format at the end of every month going forward and share them with you.

Thanks!

cc @sabrinatoro

**Comment by zoependlington** [comment]
Thanks @nicolevasilevsky! I shall double check if we anticipate any issues here and get in touch if we have any objections/issues.

**Comment by nicolevasilevsky** [comment]
perfect, thanks!
