### ISSUE TITLE
Import MONDO terms

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1282]
Hello,

could you please import this list of 28 MONDO, 4 HP and 1 DOID ids to EFO?
[import2EFO.csv.zip](https://github.com/EBISPOT/efo/files/7284005/import2EFO.csv.zip)

These are disease ids used by various data sources that I could not find in EFO either directly or as xrefs of current terms, leading to invalid evidence.

Thank you very much!

**Comment by zoependlington** [comment]
I have imported the Mondo and HP terms and created an EFO term (EFO_0020006) x-refing the DOID term.
