### ISSUE TITLE
Request terms for UK Biobank Fields

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#1285]
## Preferred term label
time spent outdoors
## Synonyms
NA
## Textual definition

Measurement of time an an individual spends outside

## Suggested parent term

environmental exposure measurement [EFO_0008360](http://www.ebi.ac.uk/efo/EFO_0008360)

## Suggested child term

sunlight exposure measurement [EFO_0010729](http://www.ebi.ac.uk/efo/EFO_0010729)

## Source
Appears in UK Biobank questionnaire:
- Time spend outdoors in summer  https://biobank.ndph.ox.ac.uk/crystal/field.cgi?id=1050
- Time spent outdoors in winter https://biobank.ndph.ox.ac.uk/crystal/field.cgi?id=1050

## Attribution

0000-0001-8222-008X

**Comment by smlmbrt** [comment]
Appears in UK Biobank questionnaire:
- Time spend outdoors in summer  https://biobank.ndph.ox.ac.uk/crystal/field.cgi?id=1050
- Time spent outdoors in winter https://biobank.ndph.ox.ac.uk/crystal/field.cgi?id=1050

**Comment by smlmbrt** [comment]
## Preferred term label
bowel opening frequency

## Synonyms
From [Frequency of bowel action (SNOMED:249521002)](https://www.ebi.ac.uk/ols/ontologies/snomed/terms?iri=http%3A%2F%2Fsnomed.info%2Fid%2F249521002):

- Frequency of bowel movement
- Frequency of stool
- Number of times bowel opened

## Textual definition
Number of times bowels opened per day
## Suggested parent term

measurement 
## Suggested links

_is_about_ digestive health (perhaps https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008460)

## Source 

UKB Field 21044 "Average number of times bowels opened per day" https://biobank.ndph.ox.ac.uk/ukb/field.cgi?id=21044

## Attribution

0000-0001-8222-008X

**Comment by smlmbrt** [comment]
## Request import of PP Interval ([CMO_0000278](http://purl.obolibrary.org/obo/CMO_0000278))
Details can be extracted from the CMO

## Suggested parent term 
electrocardiography ([EFO_0004327](http://www.ebi.ac.uk/efo/EFO_0004327))

## Source
UKB Field 22334 "PP interval" https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=22334

**Comment by smlmbrt** [comment]
## Request PQ interval as a synonym for PR Interval

## Synonym to be added 
PQ interval

## Sources for the synonym
https://en.ecgpedia.org/wiki/Conduction
https://en.wikipedia.org/wiki/PR_interval

## Related Source Data  
PQ Interval in UKB https://biobank.ndph.ox.ac.uk/showcase/field.cgi?id=22330

**Comment by kallia-p** [comment]
@smlmbrt 
EFO_0600081 time spent outdoors measurement
EFO_0600082 insulin use measurement. Another parent term has been inferred by the reasoner which is insulin measurement EFO_0004467 (according to the definition this refers to the insulin measurement typically done for the diagnosis of patients so it is slightly distinct term from the insulin use measurement). 
EFO_0600083 family history of prostate cancer
EFO_0600084 bowel opening frequency  
EFO_0600085 PP interval
PQ interval added as a synonym for PR Interval

Source added https://doi.org/10.1101/2021.09.02.21262942

**Comment by smlmbrt** [comment]
Sounds good, but don't think EFO_0004467 (insulin measurement) is a good parent for insulin use measurement (EFO_0600082), because this measures how long after diagnosis insulin was used as a drug/treatment.

**Comment by kallia-p** [comment]
@smlmbrt You are right about this but the reasoner has made the inference which I cannot easily change. It's not entirely off as they both refer to an insulin measurement; drug use measurement is an asserted parent of insulin use measurement.
