### ISSUE TITLE
New terms request for Wang PMID 34202464 (WC_20211008)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1289]
5 terms
ABO blood group
Blood group A
Blood group B
Blood group O
Blood group AB

https://docs.google.com/spreadsheets/d/1szDDFCbo90nEZabE0zonboUOCK03j_Z39YcEe8SszlA/edit#gid=1909577919

for all of these HP terms are available http://purl.obolibrary.org/obo/HP_0032224

**Comment by kallia-p** [comment]
@Santhi1901 Added a 'blood group' superclass with 'ABO blood group' as a child and the rest as per our request. 
EFO_0600058 (blood group)
EFO_0600059 (ABO blood group)
EFO_0600060 (blood group A)
EFO_0600061 (blood group B)
EFO_0600062 (blood group AB)
EFO_0600063 (blood group O)
