### ISSUE TITLE
New term request: "4C-seq"

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#1297]
For new term requests, please provide the following information:

## Preferred term label

4C-seq

## Textual definition

Circular chromosome conformation capture combined with high-throughput sequencing
PMID: 22961246 (https://doi.org/10.1038/nmeth.2173)

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0003740
http://www.ebi.ac.uk/efo/EFO_0009967

**Comment by anjaf** [comment]
Sorry to be opening this back up. I can't find the term "4C-seq" in EFO and the quoted accession doesn't seem to be the right one. (EFO_0030037 leads to "[T cell activation assay](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030037)"). Maybe something got mixed up?

**Comment by paolaroncaglia** [comment]
@anjaf 

> Sorry to be opening this back up. I can't find the term "4C-seq" in EFO and the quoted accession doesn't seem to be the right one. (EFO_0030037 leads to "[T cell activation assay](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030037)"). Maybe something got mixed up?

Thank you for pointing this out. [This pull request](https://github.com/EBISPOT/efo/commit/0343b744f078c1e46c3919baa95ecb974c15e4ce) shows that in mid-October I added and committed EFO_0030037 as '4C-seq'. However, as you noticed, [EFO:0030037 now points to 'T cell activation assay'](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030037), and there is no '4C-seq' in EFO. Let me dig a bit deeper to figure out what went wrong and suggest a course of action.

**Comment by paolaroncaglia** [comment]
@anjaf 
In mid-November I indeed added EFO_0030037 as 'T cell activation assay', as shown in [this pull request](https://github.com/EBISPOT/efo/commit/bc6b61039131c96e411e71a55f965efbfb2bea1d). My Protege is set up so as to remember the last ID used, but apparently EFO_0030037 was still available. I could have somehow unconsciously scrambled the Protege set-up to allow that, or my mid-October commit might have been reverted for some reason - let me check the full commit log. Then I'll see what's best to do, possibly add 4C-seq again... I might need to ask for assistance as I no longer work at EBI, but I'll see that this is addressed soon. Not sure what went wrong but apologies for whatever that was!

**Comment by paolaroncaglia** [comment]
@anjaf 
It looks like [this commit](https://github.com/EBISPOT/efo/pull/1299) never went through. To fix:
- [ ] A new term should be created for 4C-seq as detailed [here](https://github.com/EBISPOT/efo/commit/0343b744f078c1e46c3919baa95ecb974c15e4ce);
- [ ] "RIP-Chip by array" should be made a subclass of the additional parent "assay by array".
I'll see that this is all done in time for the mid-July EFO release.

**Comment by zoependlington** [comment]
@paolaroncaglia No changes! Please feel free. If you run into any issues, let me know!

**Comment by zoependlington** [comment]
@anjaf I have added 4C-seq as EFO_0021526 and completed Paola's other changes that were missing. These will be available after the July release (18th).
