### ISSUE TITLE
New term request for Hodel PMID 34532061

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1306]
For new term requests, please provide the following information:

## Preferred term label

**requesting 3 terms - see webulous form:** 

[webulous.-.WC_20210811_measurement.xlsx](https://github.com/EBISPOT/efo/files/7388269/webulous.-.WC_20210811_measurement.xlsx)

1. anti-WU polyomavirus antibody measurement

2. anti-human polyomavirus 6 antibody measurement

3. human polyomavirus 6 seropositivity

**Comment by kallia-p** [comment]
@earlEBI The webulous attachment contains the organ volume measurements from another ticket, could you please re-send?

**Comment by earlEBI** [comment]
@kallia-p sorry about that!
[webulous.-.WC_20211111_measurement.xlsx](https://github.com/EBISPOT/efo/files/7520897/webulous.-.WC_20211111_measurement.xlsx)

**Comment by kallia-p** [comment]
@earlEBI 
human polyomavirus 6 seropositivity EFO_0600072 
anti-WU polyomavirus antibody measurement EFO_0600073
anti-human polyomavirus 6 antibody measurement EFO_0600074
