### ISSUE TITLE
New term request for Kawaratani PMID 34309184

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1307]
For new term requests, please provide the following information:

## Preferred term label

response to tolvaptan

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of treatment with tolvaptan, an aquaretic drug that functions as a selective, competitive vasopressin receptor 2 (V2) antagonist.

## Suggested parent term

response to drug http://purl.obolibrary.org/obo/GO_0042493

## Attribution

NA

**Comment by kallia-p** [comment]
@Santhi1901 EFO_0600065
