### ISSUE TITLE
New term request: bronchoscopic microsampling

### ISSUE THREAD

**Issue by ESapenaVentura** [EBISPOT/efo#1308]
## Preferred term label

bronchoscopic microsampling

## Synonyms

BMS

## Textual definition

Method in which a device consisting of a wire with a polyester probe at the tip is used to collect bronchial epithelial lining fluid with bronchoscopy.

## Suggested parent term

[biopsy](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009120)

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
The new term is EFO_0030036 (bronchoscopic microsampling).
It will be in HCAO following the release scheduled for Tue 16th.
