### ISSUE TITLE
New term request for Brikell PMID 34154395

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1309]
For new term requests, please provide the following information:

## Preferred term label

response to stimulant therapy

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a stimulant such as used in the treatment of ADHD. 

## Suggested parent term

response to drug

## more info:

The paper describes 3 GWAS:
1. Cases (ADHD patients who have switched from stimulant treatment to non-stimulant treatment) vs. healthy controls. 
2. Cases (ADHD patients who have initiated stimulant treatment) vs. healthy controls
3. Cases (ADHD patients who have discontinued stimulant treatment) vs. healthy controls

#note: a relevant purl term: https://www.ebi.ac.uk/ols/ontologies/maxo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMAXO_0000438

**Comment by kallia-p** [comment]
response to stimulant therapy EFO_0600075

**Comment by kallia-p** [comment]
@earlEBI response to stimulant therapy EFO_0600075
