### ISSUE TITLE
New term request for Leskela PMID 34668383

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1316]
For new term requests, please provide the following information:

## Preferred term label

serum lipopolysaccharide activity

## Synonyms

endotoxemia

## Textual definition

Quantification of lipopolysaccharide activity in serum. 

## Suggested parent term 

gram-negative bacterial infections - http://purl.obolibrary.org/obo/MONDO_0021678 ? 

## further info: 

“Translocation of lipopolysaccharide from gram-negative bacteria into the systemic circulation results in endotoxemia.”

**Comment by earlEBI** [comment]
Hi @kallia-p please could you prioritise this request as much as possible? Thank you

**Comment by kallia-p** [comment]
@earlEBI EFO_0600064
