### ISSUE TITLE
New term request for Brikell PMID 34154395

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1322]
For new term requests, please provide the following information:

## Preferred term label

stimulant use measurement

## Synonyms

(e.g., Absent spleen)

## Textual definition

Quantification of some aspect of stimulant use, for instance in the treatment of ADHD. 

## Suggested parent term

drug use measurement

## related to:
ticket #1309

For use in the following study:
Cases (ADHD patients who have initiated stimulant treatment) vs. healthy controls

**Comment by kallia-p** [comment]
stimulant use measurement EFO_0600076

**Comment by kallia-p** [comment]
@earlEBI stimulant use measurement EFO_0600076
