### ISSUE TITLE
New term request: T cell activation

### ISSUE THREAD

**Issue by ipediez** [EBISPOT/efo#1324]
## Preferred term label

T cell activation

## Synonyms

T-cell activation, T lymphocyte activation

## Textual definition

A method in which T cells are incubated with a culture media containing an activator agent (such as Dynabeads Human T-Activator CD3/CD28), mimicking the natural activation and expansion process.

## Suggested parent term

cellular modification (EFO:0000325)

**Comment by paolaroncaglia** [comment]
Hi @ipediez ,

Nice to e-meet you. The term you're looking for is already in the HCA OLS production instance as GO:0042110, see [here](https://ontology.archive.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0042110). The GO term refers to the physiological process, while your definition refers to an assay. Would it be appropriate to annotate to the GO term? If not, I'll look for, or create, an assay term in time for the next EFO and HCAO releases (Nov 15th and 16th respectively). Thanks.

Paola Roncaglia

**Comment by ipediez** [comment]
Hi @paolaroncaglia,

Annotating to the GO term would not be possible, as the metadata schema we are using restricts the acceptance of terms to those under the EFO category experimental process (EFO:0002694). If you could look for, or create, a term for this, it would be great.

**Comment by paolaroncaglia** [comment]
Hi @ipediez ,

Thanks for clarifying. Sure, I'll create (or import) an appropriate term in the 'experimental process' branch. It can't have the same label as the GO term, but I might add 'T cell activation' as a broad or related synonym, I'll see. I'll update this ticket in time for the release.

**Comment by paolaroncaglia** [comment]
Note for self: [BAO has a term for T-cell activation assay](https://www.ebi.ac.uk/ols/ontologies/bao/terms?iri=http%3A%2F%2Fwww.bioassayontology.org%2Fbao%23BAO_0010253), but it's undefined. It has 
"Synonyms: T cell proliferation assay tumor cell - T cell co-culture assay T-cell proliferation T-cell functional activity T cell activation T cell - tumor cell co-culture assay". I don't think it would fit the HCA need. I'll create a new EFO term.

**Comment by paolaroncaglia** [comment]
Hi @ipediez ,
Could you please provide your ORCID ID if you have one? Not mandatory, but nice to have. Thanks.

**Comment by ipediez** [comment]
Sure @paolaroncaglia, it's 0000-0002-2658-1136. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @ipediez ,
The new term is EFO_0030037 (T cell activation assay).
It will be in HCAO following the release scheduled for Tue 16th.
I added related synonyms "T cell activation", "T-cell activation" and "T lymphocyte activation".
