### ISSUE TITLE
New term request for Sanders PMID 34518958

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1325]
For new term requests, please provide the following information:

## Preferred term label

Childhood gender nonconformity

## Synonyms

CGN

## Textual definition

Childhood gender nonconformity (CGN) is a phenomenon in which prepubescent children do not conform to expected gender-related sociological or psychological patterns, or identify with the opposite sex/gender.

## Suggested parent term

gender identity disorder http://www.ebi.ac.uk/efo/EFO_0008587

## Attribution

NA

##Other info
 A similar term in SNOMED: Gender identity disorder of childhood (disorder) (http://snomed.info/id/5095008)

**Comment by zoependlington** [comment]
Added as EFO_0020103, which will be available after our 17th January release.
