### ISSUE TITLE
New terms request from Harshfield EL, PMID 34503513 (bulk request)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1327]
For new term requests, please provide the following information:

https://docs.google.com/spreadsheets/d/1jdLwHJkYeiwdybJhh-2EYgxqNwXPbT-9dVKdVy9TSlQ/edit#gid=0

**Comment by zoependlington** [comment]
@buniello I have added these terms into EFO and they will be available after out 17th January release. The IDs are on the Google sheet if you require them.

Please let me know if you spot any issues after the 17th.
