### ISSUE TITLE
New term request for Moksnes PMID 33961016

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1328]
For new term requests, please provide the following information:

## Preferred term label

cardiac troponin I change measurement

## Synonyms

cTnI change measurement

## Textual definition

Quantification of the change in cardiac troponin I in an individual over time, typically measured in blood. 

## Suggested parent term

cardiac troponin I measurement

## From the paper: 
"Additionally, we assessed changes in cTnI with time in 5178 HUNT participants with repeated measures."

**Comment by kallia-p** [comment]
@earlEBI EFO_0600077
