### ISSUE TITLE
New term request for pseudo-bulk aggregation of sc(RNA)-seq data

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1329]
For new term requests, please provide the following information:

## Preferred term label

Pseudo-bulk aggregation of single-cell expression data

## Synonyms

pseudo-bulk RNA-seq

## Textual definition

This involves combining single-cell expression values from multiple cells in the same biological sample. Aggregation is typically performed by summation of count data for cells of the same (inferred) type. The aggregated expression profiles can then be used in the same manner as bulk RNA-seq data, especially in differential expression analyses.

PMID:  [28045081](https://www.nature.com/articles/srep39921), which introduces the term in passing.

## Suggested parent term

EFO:0030023

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
I'll look into this request (and the other 5 that you submitted along with this one) aiming for the mid-November EFO release, if possible. I'll post the IDs here when ready. Thanks.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
The new term is EFO_0030053 (pseudo-bulk aggregation of single-cell expression data).
It will be in the next EFO release, scheduled for Monday 15th.
