### ISSUE TITLE
New term request for label-free quantification

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1330]
For new term requests, please provide the following information:

## Preferred term label

Label-free quantification

## Synonyms

LFQ

## Textual definition

This uses mass spectrometry to quantify the relative amount of each protein across multiple biological samples without the need for any prior sample labelling. The assay is run separately on each sample and involves digestion of the proteome into peptides, liquid chromatography with mass spectrometry, and then quantification via spectral counting (i.e., the number of matching spectra from MS/MS) or integration of the intensities of each peptide's peaks. 

PMID: [17668192](https://link.springer.com/article/10.1007%2Fs00216-007-1486-6#Sec6) (see Section 6, "Label-free quantification")

## Suggested parent term

EFO:0002766

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
@LTLA 
EFO_0030054 (label-free quantification)
