### ISSUE TITLE
New term request for 16S metagenomic sequencing

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1331]
For new term requests, please provide the following information:

## Preferred term label

16S metagenomic sequencing

## Synonyms

16S-seq

## Textual definition

Amplicon sequencing approach targeting the variable regions of the 16S ribosomal RNA gene. This is commonly used to quantify the abundance of different microbial taxa in an environmental sample, based on how frequently a taxa's specific rRNA sequence is observed in the sequencing data.

PMID: [15489351](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC523561/)

## Suggested parent term

EFO:0003747

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
@LTLA 
EFO_0030055 (16S metagenomic sequencing)
