### ISSUE TITLE
New term request for NanoString sequencing

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1332]
For new term requests, please provide the following information:

## Preferred term label

Transcriptional profiling by NanoString 

## Synonyms

NanoString

## Textual definition

The NanoString nCounter gene expression system uses multiplexed probe hybridization to capture and count individual mRNA transcripts. Transcripts for each gene are targeted by a pair of gene-specific probes - a biotinylated capture probe to capture the transcript on a streptavidin-coated slide, and a reporter probe containing a color-coded pattern of fluorescent segments. Imaging of the slide can then identify each captured transcript.

PMID: [18278033](https://pubmed.ncbi.nlm.nih.gov/18278033/)

## Suggested parent term

EFO:0002773 or EFO:0001032, depending on how you want to interpret it. Perhaps this is really two separate terms - "assay by NanoString" for the general use case involving this technology, and then the specific application of "transcriptional profiling by NanoString".

Note that the assay technology is closely related to EFO:0030029, but the application is different; this request does not have any spatial aspect, it just refers to the expression profiling.  

## Attribution

0000-0002-2443-7325

**Comment by paolaroncaglia** [comment]
@LTLA 
EFO_0030058 (transcription profiling by NanoString)
Thank you for adding details, it's helpful and makes term addition quicker. I opted to add the transcription profiling term alone - we can always add a broader one if needed. Also please note that for consistency with existing EFO terms, I labelled the term 'transcription profiling ...' and gave it an exact synonym 'transcriptional...'.
Thanks,
Paola
