### ISSUE TITLE
New term request for tandem mass spectrometry

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1333]
For new term requests, please provide the following information:

## Preferred term label

Tandem mass spectrometry

## Synonyms

MS/MS
MS2
Tandem MS

## Textual definition

This assay combines two mass spectrometers together to analyze complex biomolecules such as peptides. The first instrument separates ionized molecules by their mass-to-charge ratio and filters for ions at a particular ratio. Once isolated, these ions are fragmented into smaller ions that are analyzed with the second instrument. The mass-charge filter and fragment spectra are then compared to a reference database to identify the original molecule.

PMID: [3462691](https://pubmed.ncbi.nlm.nih.gov/3462691/)

## Suggested parent term

EFO:0002774

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
@LTLA 
EFO_0030056 (tandem mass spectrometry)
