### ISSUE TITLE
New term request for Luminex assays

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1334]
For new term requests, please provide the following information:

## Preferred term label

Luminex multi-analyte profiling

## Synonyms

Luminex

## Textual definition

The Luminex technology is a bead-based assay for quantification of multiple analytes in a single sample. Beads are color-coded and coated with antibodies or oligonucleotide primers specific to different analytes. After incubation with the sample of interest, secondary antibodies/primers are added, and imaging of the beads can be used to quantify the abundance of each analyte.

PMID: [12360572](https://pubmed.ncbi.nlm.nih.gov/12360572/)

## Suggested parent term

EFO:0002773

This can be used for both nucleic acid and protein, so I'm not sure whether it is worth listing it under "assay by molecule".

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
@LTLA 
EFO_0030057 (Luminex multi-analyte profiling)
