### ISSUE TITLE
Organ volume measurement term

### ISSUE THREAD

**Issue by kallia-p** [EBISPOT/efo#1336]
Secondary ticket stemming from https://github.com/EBISPOT/efo/issues/1218

Organ volume measurement was requested by the GWAs catalog as a parent term for kidney volume, liver volume etc. measurements. We may want to add a suitable term in EFO (for example Volume PATO:0000918 or Body size trait OBA:VT0100005).

**Comment by zoependlington** [comment]
This will be covered by other planned work with measurement patterns.
