### ISSUE TITLE
New term request for Chakraborty PMID 34608871

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1338]
For new term requests, please provide the following information:

## Preferred term label

Narrow occludable anterior chamber angle
or 
Narrow occludable anterior chamber angle of eye

## Synonyms

NA

## Textual definition

The narrow or occludable angle is when the angle of the eye is narrow or closed by the iris.

## Suggested parent term

eye measurement

## Attribution

NA

## Other info

occludable anterior chamber angle is considered as a primary risk factor for Primary angle closure glaucoma, which in turn could be responsible for high intraocular pressure (IOP) and subsequent neurodegeneration of retinal ganglion cells.

**Comment by kallia-p** [comment]
@Santhi1901 
New term added Narrow occludable anterior chamber angle EFO_0600087.
Parent term is a child of eye measurement 'anterior chamber depth measurement' based on SNOMED hierarchy. 

![image](https://user-images.githubusercontent.com/77484553/145809282-e3dcadde-0762-411e-b6c1-eeae6a538f3c.png)
