### ISSUE TITLE
Add diseases (stemming from ChEMBL additions)

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#135]
From email correspondence with @gkos-bio:

"I was looking at what diseases were rejected during our validation process during the last February release and noticed that ChEMBL submitted evidence for drugs with HP terms that are actually diseases. So, I'll create a Webulous template to populate the all the information properly and will send the shareable link."

and

"As promised:
https://docs.google.com/spreadsheets/d/1IF677P3qLwkUM5d6zmo6i7iIoMovOyJw75ryclxc9XQ/edit?usp=sharing
I've added the few diseases from ChEMBL and looked closely at the classification in different ontologies/thesauri.
Most of the diseases exist in EFO. However, the classification can be improved and none of them had an organ location.
I've added the relevant cell type for one of them.
Please note that some diseases have a preferred label:
### Wegener's Granulomatosis
The name of this vasculitic disease was officially changed from Wegener's Granulomatosis (WG) to Granulomatosis with Polyangiitis (GPA) in 2011.
### Churg-Strauss Syndrome
Eosinophilic granulomatosis with polyangiitis (EGPA) was traditionally termed, Churg-Strauss syndrome."

**Comment by paolaroncaglia** [comment]
- [ ] Do a quick check of all info in template, including
- [ ] Are (any of) those disease terms in MONDO? If yes, add MONDO def cit.
- [ ] Address questions on checking names of two diseases above.

**Comment by paolaroncaglia** [comment]
The template contains 13 entries. 8 are existing terms and the corresponding rows are highlighted in yellow.
I noted down in the Webulous template MONDO definition citations for 10 of the 13 entries.
The 2 labels highlighted by Gautier need to be moved to synonyms and updated as indicated in the 'comments' column. 
- [ ] Once the issue of renaming multiple URIs with Urigen (due to missing menu item in Protege) is fixed, see what's more convenient - splitting the Webulous template to keep only new terms and edit the existing ones by hand, or submitting the entire template and then hand-editing the existing terms. Either way,
- [ ] Remember to make a copy of the full template, and clear the content in the 'comments' column in the 'working' copy.

**Comment by paolaroncaglia** [comment]
In the absence of a short-term fix, given the size of the task, I'll do it manually. I'll refer to the info in the spreadsheet: https://docs.google.com/spreadsheets/d/1IF677P3qLwkUM5d6zmo6i7iIoMovOyJw75ryclxc9XQ/edit#gid=912265354

**Comment by paolaroncaglia** [comment]
Added EFO:0009011 Arteritis
Added EFO:0009012 Polyarteritis nodosa
(more soon)

**Comment by paolaroncaglia** [comment]
Note for self: before importing UBERON terms, if via Webulous, I'd need to install and test the updated URIGEN plugin.

**Comment by zoependlington** [comment]
Completed the import of terms:

>  - [ ] Import the following terms from UBERON:
>'lung blood vessel', 'trachea blood vessel’, 'nasal vein’, 'iliac artery', 'femoral artery', 'popliteal artery', 'peroneal artery’

Just the disease location axioms to be done!

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT1** Granulomatosis with Polyangiitis (EFO:0005297)
     - [ ] Edit has_disease_location some (lung or (part_of some lung)) -> has_disease_location some 
    ('lung blood vessel' or (part_of some 'lung blood vessel'))
     - [ ] Edit has_disease_location some (trachea or (part_of some trachea)) -> has_disease_location some ('trachea blood vessel' or (part_of some 'trachea blood vessel'))
     - [ ] Edit has_disease_location some (vein or (part_of some vein)) -> has_disease_location some ('nasal vein' or (part_of some 'nasal vein'))

- [ ] **EFO:EDIT2** peripheral arterial disease (EFO:0004265)
     - [ ] has_disease_location some ('iliac artery' or (part_of some 'iliac artery'))
     - [ ] has_disease_location some ('femoral artery' or (part_of some 'femoral artery'))
     - [ ] has_disease_location some ('popliteal artery' or (part_of some 'popliteal artery'))
     - [ ] has_disease_location some ('peroneal artery' or (part_of some 'peroneal artery'))
