### ISSUE TITLE
New term request for Kachuri PMID 34469753

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1363]
For new term requests, please provide the following information:

## Preferred term label

Lymphocyte-to-monocyte ratio
OR
lymphocyte:monocyte ratio

## Synonyms

NA

## Textual definition

quantification of the ratio between absolute lymphocyte count and absolute monocyte count

## Suggested parent term

hematological measurement (http://www.ebi.ac.uk/efo/EFO_0004503)

## Attribution

NA

**Comment by kallia-p** [comment]
@Santhi1901 New term added EFO_0600088
