### ISSUE TITLE
New terms request for Mehrotra PMID 34197840 (WC_20211116)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1364]
2 terms
peritoneal solute transfer rates
response to peritoneal dialysis

https://docs.google.com/spreadsheets/d/16kU5uk7acAo4NYVK4DRwZAquYH1ahvUHkr2JQD0L0Vk/edit#gid=1909577919

**Comment by kallia-p** [comment]
@Santhi1901 
peritoneal solute transfer rate EFO_0600089 
response to peritoneal dialysis EFO_0600090
