### ISSUE TITLE
NTRs - single-cell assays

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1366]
## Preferred term label

10x multiome

## Synonyms

Chromium Single Cell Multiome ATAC + Gene Expression

## Textual definition

Simultaneous profiling of gene expression and open chromatin from the same cell.
citation: https://assets.ctfassets.net/an68im79xiti/7x5E4P6xefQruTbFg0yr3a/1381fdcd2d2e7d667ef5b415119dab15/CG000338_ChromiumNextGEM_Multiome_ATAC_GEX_User_Guide_RevE.pdf

## Suggested parent term

EFO:0010183 (single cell library construction), EFO:0010891 (scATAC-seq), EFO:0008913 (scRNA-seq), EFO:0008995 (10x technology)

## Preferred term label

mCT-seq

## Synonyms

methylcytosine and transcriptome sequencing

## Textual definition

A method that can jointly capture cytosine DNA methylome (5mC) and transcriptome profiles from single cells/nuclei by partitioning RNA and DNA molecules through the incorporation of 5’-methyl-dCTP instead of dCTP during reverse transcription of RNA.
citation: https://www.biorxiv.org/content/10.1101/434845v1

## Suggested parent term

EFO:0010183 (single cell library construction), EFO:0001456 (DNA assay), EFO:0008913 (scRNA-seq)

## Preferred term label

mcSCRB-seq

## Synonyms

molecular crowding single-cell RNA barcoding and sequencing

## Textual definition

A single-cell RNA barcoding and sequencing protocol with increased sensitivity through the addition of polyethylene glycol (PEG 8000). PEG 8000 increases the cDNA yield by reducing the effective reaction volume.
citation: PMID:30050112

## Suggested parent term

EFO:0010004 (SCRB-seq)

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,
I'll look into these term requests in time for the next EFO release, scheduled for Dec 15th.
Meanwhile, could you please provide your ORCID for term attribution? Not mandatory but nice to have.
Thanks,
Paola

**Comment by jahilton** [comment]
0000-0002-1196-4871
Thanks @paolaroncaglia

**Comment by paolaroncaglia** [comment]
Hi @jahilton ,
The new terms are:
EFO_0030059 (10x multiome)
EFO_0030060 (mCT-seq)
EFO_0030061 (mcSCRB-seq)
They'll be in the EFO release very soon (scheduled for Dec 15th). Thanks.
