### ISSUE TITLE
Terms with missing OMIM cross references

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1368]
Hello!

There are 82 terms in EFO that at least in June used to have an xref with OMIM and which now such xref is not present. 
[missing_omim_xrefs.json.zip](https://github.com/EBISPOT/efo/files/7626906/missing_omim_xrefs.json.zip)

The terms seem to be correctly paired, I'd like to know how we can gain this annotation back.

Here are some examples:
```
+---------------+------------------------------------------------------+
|disease        |lost_omim_xrefs                                       |
+---------------+------------------------------------------------------+
|EFO_0000292    |[OMIM:109800]                                         |
|EFO_0000571    |[OMIM:211980]                                         |
|EFO_0005561    |[OMIM:612160]                                         |
|EFO_0000632    |[OMIM:137800]                                         |
|MONDO_0019587  |[OMIM:618533, OMIMPS:124900]                          |
|EFO_1001229    |[OMIM:154800]                                         |
|EFO_0005543    |[OMIM:613028, OMIM:613029]                            |
```

**Expected behaviour**
These xrefs are used to establish a relationship between diseases and phenotypes in our [Clinical signs and symptoms widget](https://platform.opentargets.org/disease/EFO_0003767).
```
EFO ID ----> OMIM ID ----> HP ID
```
If we lose OMIM xrefs, we lose the ability to connect diseases with phenotypes.

**Notes**
[efo_otar_slim.json v. 3.36.0](https://github.com/EBISPOT/efo/releases/download/v3.36.0/efo_otar_slim.owl) has been used for the analysis.
OLS might show the missing xref in the offending terms (see [EFO_0000571](http://www.ebi.ac.uk/efo/EFO_0000571)). This is a bug where an outdated version of EFO is displayed. The dump file lacks such reference.

**Comment by zoependlington** [comment]
Hi @ireneisdoomed!

I've looked into this a little and it looks like these may have been dropped during a few big edits to EFO (e.g. reworking the cancer branch) - I'll add these in for the EFO and the Orphanet terms for our January (17th) release however Mondo term x-ref additions will have to be requested directly to Mondo (https://github.com/monarch-initiative/mondo/issues).

Additionally EFO_0000292 is actually obsolete and has been replaced by MONDO_0004986 which does have the OMIM x-ref.
