### ISSUE TITLE
New terms request for Suhre PMID 28240269 (bulk request)

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1369]
Robot form below:

https://docs.google.com/spreadsheets/d/1rUS5SSWVHUOLn6HPtxoUkuNm4PRiYYiZaREn7kUo4v4/edit#gid=0

**Comment by zoependlington** [comment]
All terms have been added and IDs are on the template. They'll be available after our January release (17th).

**Comment by buniello** [comment]
thanks so much for this @zoependlington
