### ISSUE TITLE
Coordinate with MONDO on Orphanet prefix

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#137]
Stemming from https://github.com/monarch-initiative/mondo/issues/118
“MONDO uses "Orphanet" as a prefix for orphanet items, but Orphanet uses "ORPHA". Should we also switch to "ORPHA" for consistency's sake?”
@cmungall’s reply:
“See monarch-initiative/dipper#469 (comment)
The official ORDO purls have a URI fragment Orphanet_NNNN, so following OBO conventions the CURIE would be Orphanet:NNN, but this is convention rather than rule, so we could in theory use anything
coordinate with @simonjupp”

**Comment by simonjupp** [comment]
Replied with comment

**Comment by TomConlin** [comment]
has been changed in monarch-initiative/dipper
