### ISSUE TITLE
New term request for Cipriani PMID 34260948

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1371]
## Preferred term label

Complement factor H-like 1 protein measurement

## Synonyms

FHL-1

## Textual definition

Quantification of complement factor H-like 1 protein in a sample. 

## Suggested parent term

blood protein measurement

## info from text: 

CFH encodes full-length factor H (FH) and a truncated splice variant, factor-H-like protein 1 (FHL-1), whereas the CFHR genes encode five FHR proteins, from FHR-1 to FHR-5.
FH and FHL-1 are cofactors for factor I, which cleaves and inactivates the central C3b protein in the complement pathway and ensures that activation is kept in check.

**Comment by kallia-p** [comment]
@earlEBI New term added EFO_0600092
