### ISSUE TITLE
New term request for Inoue PMID 34265127

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1372]
For new term requests, please provide the following information:

## Preferred term label

Skin roughness measurement

## Textual definition

Quantification of some aspect of skin roughness such as frequency or severity. 

## Suggested parent term

measurement ?

## phenotype info from text: 

2.3.6  |  Frequency of rough skin
To a question: “Does your skin often become rough in the presence of stress, shortage of sleep, or a change in the season?”, each subject was instructed to select the frequency of rough skin from four options: 1. not at all, 2. rarely, 3. sometimes and 4. often. The response was regarded as a phenotype.

**Comment by kallia-p** [comment]
@earlEBI Added skin roughness measurement EFO_0600094
