### ISSUE TITLE
New term request for Inoue PMID 34265127

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1373]
For new term requests, please provide the following information:

## Preferred term label

Response to cosmetics

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a cosmetic product stimulus. 

## Suggested parent term

response to drug

## phenotype info from text: 

2.3.7  |  Responsiveness to cosmetics
To the question: “Have you felt a cosmetic uncomfortable during the past year?”, each subject was instructed to select the frequency of such cases from three options: 1. not at all, 2. sometimes and 3. often. The response was regarded as a phenotype.

**Comment by kallia-p** [comment]
Added response to cosmetics EFO_0600093

**Comment by kallia-p** [comment]
@earlEBI Added response to cosmetics EFO_0600093
