### ISSUE TITLE
Appendectomy term for GBMI endpoint doi:10.1101/2021.11.19.21266436

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#1376]
## Preferred term label

Appendectomy

## Synonyms

Excision of appendix

## Textual definition

Procedure to remove the appendix 

## Linked Terms
snomed:[80146002](http://snomed.info/id/80146002)
NCIT:[C51687](http://purl.obolibrary.org/obo/NCIT_C51687)
OPCS-4:H01 (Emergency excision of appendix)
OPCS-4:H01.1(emergency excision of abnormal appendix and drainage)
OPCS-4:H01.2 (emergency excision of a normal appendix)

## Suggested parent term

medical procedure ([EFO_0002571](http://www.ebi.ac.uk/efo/EFO_0002571))

## Source Publication

doi:[10.1101/2021.11.19.21266436](https://doi.org/10.1101/2021.11.19.21266436)

## Attribution

0000-0001-8222-008X

**Comment by kallia-p** [comment]
@smlmbrt 
New term added EFO_0600086
