### ISSUE TITLE
New term request for Alotaibi PMID 34311721

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1377]
For new term requests, please provide the following information:

## Preferred term label

Primary dental caries

## Textual definition

The decay of any primary tooth, in which it becomes softened, discolored, and/or porous.

## Suggested parent term

Dental caries

## further info: 
I am requesting 2 specific terms, primary and permanent dental caries, due to the following text: 

"Importantly, none of the top associated SNPs in either of the analyses (dft and DFT) were replicated in the other one, full results are presented in the Additional file 1: Tables S3 and S4. This confirms that genetic loci that influence the susceptibility to dental caries differ between primary and permanent dentitions [54]."

**Comment by kallia-p** [comment]
@earlEBI EFO_0600095
