### ISSUE TITLE
Tool advice

### ISSUE THREAD

**Issue by psaffrey** [EBISPOT/efo#1379]
I would like to use the downloads [you provide](https://github.com/EBISPOT/efo/releases) to integrate EFO ontology features into my locally-hosted applications. I was hoping for some recommended tools that will help me do this and I can't seem to find much guidance in the documentation in this repo or on the OLS pages.

Specifically, I'm trying to use Python to parse the efo.obo file. I've tried [fastobo](https://pypi.org/project/fastobo/), which does this:

    >>> import fastobo
    >>> obodoc = fastobo.load("/home/psaffrey/incoming/efo.obo")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<stdin>", line 967
        xref: KEGG COMPOUND:70458-96-7 "CAS Registry Number"␊
                   ^
    SyntaxError: expected EOL or QuotedString

and [Pronto](https://pypi.org/project/pronto/), which does this:

    >>> from pronto import Ontology
    >>> efo = Ontology("/path/to/efo.obo")
    thread '<unnamed>' panicked at 'assertion failed: `(left != right)`
      left: `0`,
     right: `0`: Python threading is not initalized and the `auto-initialize` feature is not enabled.

    Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.', /tmp/pip-req-build-pz6epnph/build/temp.linux-x86_64-3.6/cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.1/src/gil.rs:231:21
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/psaffrey/.venv-sandbox/lib64/python3.6/site-packages/pronto/ontology.py", line 283, in __init__
        cls(self).parse_from(_handle)  # type: ignore
      File "/home/psaffrey/.venv-sandbox/lib64/python3.6/site-packages/pronto/parsers/obo.py", line 18, in parse_from
        doc = fastobo.iter(handle, ordered=True)
     pyo3_runtime.PanicException: assertion failed: `(left != right)`
      left: `0`,
     right: `0`: Python threading is not initalized and the `auto-initialize` feature is not enabled.

    Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.

Of course, I'm probably using these tools incorrectly in some way, but I've tried to follow the documentation supplied. Would it be possible to link some guidelines to help me (and the next person) to know what I should use and how I should use it?

PS. Sorry about the multiple edits. Struggling to get Github markdown to work properly...

**Comment by zoependlington** [comment]
Hi @psaffrey!

We do have a release of EFO in the json format (https://github.com/EBISPOT/efo/releases/download/current/efo.json) which is still in the experimental stage but can be parsed using normal JSON parsers.

Hopefully this will suit your requirements, but please do get in touch if this isn't the case. I will leave this ticket open for now, so feel free to reply here if you have any further trouble or questions.

Thanks,
Zoë

**Comment by psaffrey** [comment]
Thanks Zoë,

Yes, I've looked at the JSON, which would work but is a bit fiddly. I'll have to disentangle all the various edge labels to ensure that I'm properly mapping the ontology. I guess I was hoping that by using a proper ontology format like OBO or OWL I would get some of this functionality "for free", or at least directly supported by a library.

What I want to do is to be able to map descendants/ancestors. I suspect the easiest way is just to reproduce the OLS API as documented [here](https://github.com/EBISPOT/OLS#deploying-with-docker), so perhaps I'll try there. I was just a bit surprised that you supply an OBO to download but no real way to work with it.

Thanks,

Peter

**Comment by matentzn** [comment]
Hey @psaffrey 

You have a few options, you could read this notebook by @jannahastings which I found useful:

https://github.com/jannahastings/py-horned-owl/blob/main/docs/TestOntoPyLibs.ipynb

https://github.com/biolink/ontobio should read the efo.json and give you access to the info you need:
https://nbviewer.org/github/biolink/ontobio/tree/master/notebooks/

As long as your use case is fairly simple all these will do. I am not 100% sure about any of these traversing `part of` and other properties - but if you mean subClassOf (is a) by "descendants" you will be fine.

**Comment by krassowski** [comment]
`pronto` does parse the OWL version (see https://github.com/althonos/pronto/issues/101 and https://github.com/althonos/pronto/issues/65) but it emits lots of syntax warnings, please see in the details below.

<details>

```
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb787c0> contains text but no `xsd:datatype`
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb78770> contains text but no `xsd:datatype`
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb786d0> contains text but no `xsd:datatype`
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb78630> contains text but no `xsd:datatype`
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb785e0> contains text but no `xsd:datatype`
<Element '{http://purl.org/dc/elements/1.1/}creator' at 0x2b6a6cb78590> contains text but no `xsd:datatype`
<Element '{http://www.ebi.ac.uk/efo/}creator' at 0x2b6a6cb782c0> contains text but no `xsd:datatype`
<Element '{http://www.ebi.ac.uk/efo/}creator' at 0x2b6a6cb82810> contains text but no `xsd:datatype`
<Element '{http://www.ebi.ac.uk/efo/}creator' at 0x2b6a6cb82630> contains text but no `xsd:datatype`
<Element '{http://www.ebi.ac.uk/efo/}creator' at 0x2b6a6cb82860> contains text but no `xsd:datatype`
<Element '{http://www.ebi.ac.uk/efo/}creator' at 0x2b6a6cb822c0> contains text but no `xsd:datatype`
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dc89810>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dc89900>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc89860>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc89630>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc897c0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc89770>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc89720>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc896d0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc892c0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc89400>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc89450>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc893b0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc89360>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc89310>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc89220>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000116' at 0x2b6a6dc891d0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000118' at 0x2b6a6dc890e0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000118' at 0x2b6a6dc89090>
unknown element in `owl:ObjectProperty`: <Element '{http://www.w3.org/2000/01/rdf-schema#}seeAlso' at 0x2b6a6dcaf540>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dcaf220>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcaf1d0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcaf180>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcaf130>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000118' at 0x2b6a6dcaf0e0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000118' at 0x2b6a6dcaf090>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000600' at 0x2b6a6dcc4f90>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dcc4d10>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcc4cc0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcc4a90>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcc4c20>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000600' at 0x2b6a6dcc4bd0>
unknown element in `owl:ObjectProperty`: <Element '{http://www.w3.org/2002/07/owl#}equivalentProperty' at 0x2b6a6dcc4590>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dcc42c0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dcc4180>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000117' at 0x2b6a6dc88db0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000112' at 0x2b6a6dc889a0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000117' at 0x2b6a6dc888b0>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000111' at 0x2b6a6dc88590>
unknown element in `owl:ObjectProperty`: <Element '{http://purl.obolibrary.org/obo/}IAO_0000117' at 0x2b6a6dc88360>
unknown element in `owl:ObjectProperty`: <Element '{http://www.w3.org/2002/07/owl#}propertyChainAxiom' at 0x2b6a6dd0ecc0>
unknown element in `owl:ObjectProperty`: <Element '{http://www.w3.org/2002/07/owl#}propertyChainAxiom' at 0x2b6a6dd0ebd0>
unknown element in `owl:ObjectProperty`: <Element '{http://www.w3.org/2002/07/owl#}propertyChainAxiom' at 0x2b6a6dd0e5e0>
```

</details>

and crucially the relationships are basically missing which makes it completely useless.

Also, there was a previous discussion on OBO standards conformance in this repo: https://github.com/EBISPOT/efo/issues/732.

Indeed it would be the most useful to validate the OWL/OBO with some strict tools to ensure that end users:
a) can open the ontology
b) are not getting misleading results from parsing the files due to lack of compliance with the specifications

That said I will just fall back to JSON for now. Thanks for keeping this issue open, I find it useful to be able to see what are the options and provide feedback. And thanks for EFO!
