### ISSUE TITLE
Odd entity IRI trips up parsers

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#1380]
This IRI is used somewhere in EFO..

```
http://www.geneontology.org/formats/oboInOwl#http://www.co-ode.org/patterns#createdBy
```

Is it in an import? Which one?

**Comment by zoependlington** [comment]
It looks like this might come from HP as it seems to be an annotation on mostly HP terms

**Comment by matentzn** [comment]
Hm, I cant confirm this for Mondo or HPO.. Can you do a text search on efo-edit.owl?

**Comment by zoependlington** [comment]
Weirdly I can't seem to see it in efo-edit.owl, only on Protege.

**Comment by matentzn** [comment]
I fixed it for EFO and HANCESTRO: https://github.com/EBISPOT/ancestro/pull/19

**Comment by paolaroncaglia** [comment]
@matentzn can this be closed, please?

**Comment by matentzn** [comment]
@zoependlington can check if its fixed in protege and then close it!

**Comment by zoependlington** [comment]
Doesn't seem to be in EFO anymore so I'll close it. Thanks!
