### ISSUE TITLE
Update EFO IDs to Mondo?

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#1381]
We noticed that there are cases where EFO uses an EFO disease term where a MONDO term is available:

disease | disease label | EFO
-- | -- | --
MONDO:0004975 | Alzheimer's disease | EFO:0000249
MONDO:0004979 | asthma | EFO:0000270
MONDO:0004986 | bladder carcinoma | EFO:0000292
MONDO:0005129 | cataract | EFO:0001059
MONDO:0021187 | hyperlipidemia | EFO:0003774
MONDO:0005178 | osteoarthritis | EFO:0002506
MONDO:0005180 | Parkinson's disease | EFO:0002508
MONDO:0001134 | primary hypertension | EFO:1002032
MONDO:0005090 | schizophrenia | EFO:0000692
MONDO:0005147 | type I diabetes mellitus | EFO:0001359
MONDO:0005148 | type II diabetes mellitus | EFO:0001360
MONDO:0005405 | childhood onset asthma | EFO:0004591
MONDO:0007079 | alcohol dependence | EFO:0003829
MONDO:0005271 | allergy | EFO:0003785
MONDO:0004976 | amyotrophic lateral sclerosis | EFO:0000253
MONDO:0000327 | Buruli Ulcer | EFO:1001281
MONDO:0005277 | migraine disorder | EFO:0003821
MONDO:0005475 | migraine with aura | EFO:0005295
MONDO:0011847 | migraine without aura | EFO:0005296
MONDO:0005301 | multiple sclerosis | EFO:0003885
MONDO:0004892 | refractive error measurement |  EFO:0007814
MONDO:0016158 | narcolepsy with cataplexy | EFO:0000614

Can these be moved to dynamic import? 
If they are, what should we do to ensure that users (e.g. GWAS) can automatically update.  Can we just use the OBO standard obsoletion mechanism and add a replace_by?

**Comment by dosumis** [comment]
CC @kallia-p

**Comment by zoependlington** [comment]
@dosumis These should be in our [mondo_efo_mappings](https://github.com/EBISPOT/efo/blob/master/src/ontology/components/mondo_efo_mappings.tsv) (I checked a handful and they're in there) and are EFO terms that merge in the Mondo import, they simply use the EFO ID as this was part of the EFO2->EFO3 update to the disease branch. If they aren't, they should be added to the mapping file and the [Mondo terms file](https://github.com/EBISPOT/efo/blob/master/src/ontology/iri_dependencies/mondo_terms.txt).

**Comment by dosumis** [comment]
This is related to addition of 'age of onset' terms defined using these diseases.  

Disadvantages of not updating:
 * Potential for duplicate terms (EFO/Mondo) from import 
 * Lack of link in EFO between (OBA) 'age of onset' and (EFO) disease terms.
- related ticket https://github.com/EBISPOT/efo/issues/1382

**Comment by d0choa** [comment]
From an OTAR perspective, we would be ok for (most) of our applications as long as you keep track of the obsoleted terms.
Let us know if you commit to these changes so we can bulletproof our systems.

**Comment by zoependlington** [comment]
I have obsoleted the following EFO terms in favour of their Mondo counterparts:

Mondo replacement | EFO term label | EFO term obsoleted
-- | -- | --
http://purl.obolibrary.org/obo/MONDO_0004975 | Alzheimer's   disease | http://www.ebi.ac.uk/efo/EFO_0000249
http://purl.obolibrary.org/obo/MONDO_0004979 | asthma | http://www.ebi.ac.uk/efo/EFO_0000270
http://purl.obolibrary.org/obo/MONDO_0004986 | bladder carcinoma | http://www.ebi.ac.uk/efo/EFO_0000292
http://purl.obolibrary.org/obo/MONDO_0005129 | cataract | http://www.ebi.ac.uk/efo/EFO_0001059
http://purl.obolibrary.org/obo/MONDO_0021187 | hyperlipidemia | http://www.ebi.ac.uk/efo/EFO_0003774
http://purl.obolibrary.org/obo/MONDO_0005178 | osteoarthritis | http://www.ebi.ac.uk/efo/EFO_0002506
http://purl.obolibrary.org/obo/MONDO_0005180 | Parkinson's disease | http://www.ebi.ac.uk/efo/EFO_0002508
http://purl.obolibrary.org/obo/MONDO_0001134 | primary hypertension | http://www.ebi.ac.uk/efo/EFO_1002032
http://purl.obolibrary.org/obo/MONDO_0005090 | schizophrenia | http://www.ebi.ac.uk/efo/EFO_0000692
http://purl.obolibrary.org/obo/MONDO_0005147 | type I diabetes mellitus | http://www.ebi.ac.uk/efo/EFO_0001359
http://purl.obolibrary.org/obo/MONDO_0005148 | type II diabetes mellitus | http://www.ebi.ac.uk/efo/EFO_0001360
http://purl.obolibrary.org/obo/MONDO_0005405 | childhood onset asthma | http://www.ebi.ac.uk/efo/EFO_0004591
http://purl.obolibrary.org/obo/MONDO_0007079 | alcohol dependence | http://www.ebi.ac.uk/efo/EFO_0003829
http://purl.obolibrary.org/obo/MONDO_0005271 | allergy | http://www.ebi.ac.uk/efo/EFO_0003785
http://purl.obolibrary.org/obo/MONDO_0004976 | amyotrophic lateral sclerosis | http://www.ebi.ac.uk/efo/EFO_0000253
http://purl.obolibrary.org/obo/MONDO_0000327 | Buruli Ulcer | http://www.ebi.ac.uk/efo/EFO_1001281
http://purl.obolibrary.org/obo/MONDO_0005277 | migraine disorder | http://www.ebi.ac.uk/efo/EFO_0003821
http://purl.obolibrary.org/obo/MONDO_0005475 | migraine with aura | http://www.ebi.ac.uk/efo/EFO_0005295
http://purl.obolibrary.org/obo/MONDO_0100431 | migraine without aura | http://www.ebi.ac.uk/efo/EFO_0005296
http://purl.obolibrary.org/obo/MONDO_0005301 | multiple sclerosis | http://www.ebi.ac.uk/efo/EFO_0003885
http://purl.obolibrary.org/obo/MONDO_0016158 | narcolepsy with cataplexy | http://www.ebi.ac.uk/efo/EFO_0000614


The only one I did not obsolete as it was not an exact match is MONDO:0004892 | refractive error measurement | EFO:0007814. Instead I added an equivalence axiom to the measurement term referencing the Mondo term.

**Comment by kallia-p** [comment]
@zoependlington. Thanks Zoe!

**Comment by psaffrey** [comment]
Hi there, sorry to comment on a closed ticket. I'm just wondering what your recommendations are for using data sources that reference now-obsolete terms, like OpenTargets? The references still work and point to a valid ontology entry, but since the entry has been detached from the overall tree (the API returns that it no longer has any descendants) the term is in something of a limbo state.

**Comment by zoependlington** [comment]
@psaffrey All obsolete terms in EFO should have a replaced by link to their replacement (except for very rare circumstances, in which case the reason for obsoletion will clearly state why), which I believe should then be picked up and updated on the Open Targets side to the replaced by term in an automated way.

@d0choa, can you confirm this please?

**Comment by d0choa** [comment]
@psaffrey In the Open Targets Platform evidence annotated with obsoleted terms will automatically be propagated to the new term. We aim to work with data providers when they start accumulating obsoleted terms and invite them to migrate their mappings. In Open Targets Genetics Portal this process is not fully automated and we usually remap obsoleted EFO terms from time to time.

**Comment by mkanai** [comment]
Hi all, following up on the previous comment, I wonder whether you have a full table of obsolete terms and their replacements. I'm using multiple resources with EFO annotations at different time points, and would like to update them altogether. A table like the one in [this comment](https://github.com/EBISPOT/efo/issues/1381#issuecomment-1005603546) would be extremely helpful.

Many thanks!

**Comment by zoependlington** [comment]
@mkanai If you are interested in all obsolete terms in EFO (including from imports), you can use this SPARQL query to get a full list of obsolete terms: https://github.com/EBISPOT/efo/blob/master/src/sparql/obsoletes.sparql. This changes regularly so a full list of obsoleted terms I can provide now will be different based on imports and edits to EFO another day, so it may be best to run this when you need to.

Alternatively all EFO terms will have a replaced by (IAO_0100001) value unless stated otherwise in comments or reason for obsolescence, which can be used programatically to replace previous annotations if that annotation is classed as obsolete (owl:deprecated true).

Please let me know if I can assist any further.
