### ISSUE TITLE
HP and MONDO terms for myopia both in EFO

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/efo#1387]
There are both an HP and a MONDO term for myopia in EFO:

http://purl.obolibrary.org/obo/MONDO_0001384
http://purl.obolibrary.org/obo/HP_0000545

I think the MONDO term might have been requested by GWAS recently, but we should have used the HP term instead. We will change our annotation, but I guess these two terms also need dealing with in EFO.

**Comment by zoependlington** [comment]
The Mondo term has been removed and will no longer be available in the 17th January release.
