### ISSUE TITLE
NTF - Slide-seqV2

### ISSUE THREAD

**Issue by EMRutherford** [EBISPOT/efo#1393]
## Preferred term label

Slide-seqV2

## Synonyms

none

## Textual definition

More sensitive version of the Slide-seq method for transferring RNA from tissue sections onto a surface covered in DNA-barcoded beads with known positions, which differs from Slide-seq in the use of a monobase encoding scheme with sequencing by ligation using sequential interrogation by offset primer, and improved parameters for split-pool synthesis of barcoded beads.

https://www.biorxiv.org/content/10.1101/2020.03.12.989806v1

## Suggested parent term

EFO:0030005 (spatial transcriptomics by high-throughput sequencing), EFO:0010183 (single cell library construction)

## Additional change

Ideally, the existing term "Slide-seq" (EFO:0009920) would have the parent terms EFO:0030005 (spatial transcriptomics by high-throughput sequencing) and EFO:0010183 (single cell library construction) to match.  The existing parent term for "Slide-seq" is "RNA assay" (EFO:0001457).  We think that these proposed parent terms are more specific, and it would be better for "Slide-seq" and "Slide-seqV2" to be sister terms.

**Comment by paolaroncaglia** [comment]
Dear @EMRutherford ,

Thank you for your request. We'll address it in time for the next EFO release, scheduled for mid-January, and we'll post an update here.

Best wishes,
Paola Roncaglia, for the EFO team.

**Comment by paolaroncaglia** [comment]
P.S. @EMRutherford could you please provide your ORCID, so it can be used for term attribution?
Not mandatory, but nice to have. Thanks.

**Comment by EMRutherford** [comment]
@paolaroncaglia , my ORCID is 0000-0001-8134-3037.  Thank you.

**Comment by paolaroncaglia** [comment]
Dear @EMRutherford ,
All edits above are done, but they won't be publicly available until the next EFO release, scheduled for Jan 17th.
The new term will be EFO_0030062 (Slide-seqV2).
Best wishes,
Paola
