### ISSUE TITLE
`cholangiocyte` wrongly classified as part of some `intralobular bile duct`

### ISSUE THREAD

**Issue by gouttegd** [EBISPOT/efo#1397]
This is a similar issue to #1375.

CL has the following terms:

* `cholangiocyte` (CL:1000488), defined as part of some `bile duct` (UBERON:0002394)
  * `intrahepatic cholangiocyte` (CL:0002538), defined as part of some `intrahepatic bile duct` (UBERON:0003704)
  * `extrahepatic cholangiocyte` (CL:0019020), defined as part of some `extrahepatic bile duct` (UBERON:0003703)

EFO modifies CL’s `cholangiocyte` (in the `anatomagram_liver.tsv` template) to make it part of some `intralobular bile duct` (UBERON:0001282) (which is itself a subclass of `intrahepatic bile duct`).

This makes all `cholangiocyte`s part of some `liver`, even the `extrahepatic cholangiocyte`s. This is problematic because Uberon considers `extrahepatic bile duct` to be spatially disjoint with `liver`, resulting in `extrahepatic cholangiocyte` being unsatisfiable when merging Uberon/CL and EFO, because it is both “part of the liver” and “extra hepatic”.

**Comment by zoependlington** [comment]
See https://github.com/EBISPOT/efo/issues/1375 for comment.
