### ISSUE TITLE
EFO cancer alignment with DO - Review and add new terms

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#14]
Per Natalie's discussion on improving EFO-Cancer (for PDX integrator)
- New terms may be needed
- Classification/axiomatisation might need a fix.

See https://docs.google.com/spreadsheets/d/1rKUYGBETdx2hHkgHtZBFAmjpIHKP2PD5C9gsc1BHtBY/edit#gid=0 and the doc file

align DO-cancer terms with EFO. Identify what DO is missing and what EFO has by:
- DO xRef in EFO (OxO)
- for EFO terms not having DO def_cite, use Zooma/OxO to see if there is an equivalent DO terms for each of those EFO terms.

[review ontology letter.docx](https://github.com/EBISPOT/efo/files/1428189/review.ontology.letter.docx)

**Comment by simonjupp** [comment]
won't fix in EFO. PDX will use NCIt and we will integrate with EFO when we import MONDO
