### ISSUE TITLE
Removal of anatomical regions from OTAR slim/profile

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#1401]
Currently, the OTAR slim/profile mostly contains disease therapeutic areas at the root level. However, there is an exception which is the `anatomical structure` term. 

![Screenshot 2022-01-04 at 10 49 00](https://user-images.githubusercontent.com/5097586/148049005-86dd326a-62e0-4de3-a070-eed5d3c11cb2.png)

Since the Open targets informatics services are not currently using this part of the ontology for the Target-Disease association problem, we were wondering if it would be better to streamline the profile and remove the `anatomical structure` term from it.

A description of the actions on our side as well as some associated problems can be found here https://github.com/opentargets/platform/issues/1784

**Comment by zoependlington** [comment]
Absolutely, I'll remove this for the 17th January release.

**Comment by zoependlington** [comment]
The pipeline has now been [edited and 'anatomical structure' removed from the slim](https://github.com/EBISPOT/otar_profiler/commit/6e7111b63db14a7accc67dc73395350ea1897e0d).
