### ISSUE TITLE
New term request for Gergei PMID 34542150

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1406]
For new term requests, please provide the following information:

## Preferred term label

Circulating alpha-Klotho measurement

## Textual definition

Quantification of circulating alpha-Klotho in a sample.

## Suggested parent term

blood protein measurement

## further info:

study measures circulating plasma alpha-Klotho - 
"α-Klotho is a transmembrane protein that serves with fibroblast growth factor receptors as a co-receptor for fibroblast growth factor 23 (FGF23) (1)...
A soluble form of α-Klotho is generated by cleavage of transmembrane α-Klotho, which is readily detected in the circulation, and henceforth referred to as circulating α-Klotho (4). Though the role of circulating α- Klotho remains incompletely understood, it is thought to share functional similarities with the membrane-bound form and to contribute to the actions of its ligand, FGF23 (5)."

**Comment by zoependlington** [comment]
Added as EFO_0020102, which will be available after the 17th January release
