### ISSUE TITLE
Run global search + replace for NCIT vs NCIt in definition citations

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#141]
Where NCIt is the correct format. 
As discussed with @simonjupp , the task could be run when EFO3 is ready.

**Comment by zoependlington** [comment]
I've also noticed that MeSH definition citations are also not all formatted in the correct format (I've seen MESH and MSH used).

**Comment by paolaroncaglia** [comment]
@simonjupp notes that we should not change formatting of xrefs when they are 'embedded' in external terms that we import. Ideally we could keep all xrefs separate. We'll need to discuss this.

**Comment by dhimmel** [comment]
Thanks @paolaroncaglia for pointing me here from https://github.com/EBISPOT/efo/issues/878.

> @simonjupp notes that we should not change formatting of xrefs when they are 'embedded' in external terms that we import.

I see why it makes sense to preserve the original dirty xrefs, although I imagine users would much prefer clean xrefs that use standard prefixes (for example those defined at https://registry.identifiers.org/).

I could imagine the following approach:

1. correcting non-standard prefixes in xrefs. If there is concern about removing incorrect data from embedded terms, we could add the clean xref while keeping the dirty xref.
2. report dirty embedded xrefs to the upstream resources.

**Comment by simonjupp** [comment]
@dhimmel  all the xrefs are cleaned using the approach you mentioned in OXO https://www.ebi.ac.uk/spot/oxo, so EFO could pull back in the cleaned version from there.

**Comment by paolaroncaglia** [comment]
@dhimmel also, if xrefs are incorrect "at source" in external ontologies that we import _dynamically_ (atm these are Mondo, CL, Fbbt, Hancestro, HP and Uberon), they should be reported to the originating resources. If we edited them in EFO, they'd be overwritten with incorrect ones at the following release-import cycle.

**Comment by dhimmel** [comment]
Thanks @simonjupp for pointing me to OXO, which I didn't know about and seems incredibly useful. Some more links:

- https://github.com/EBISPOT/OXO
- https://www.ebi.ac.uk/spot/oxo/docs/api

> If we edited them in EFO, they'd be overwritten with incorrect ones at the following release-import cycle.

I completely agree that in an ideal world xref prefixes would be standardized upsteam, and that upstream ontologies are the source of the problem in many cases here. Invalid xref prefixes should be reported upstream (happy to help here) and hopefully over time they will be fixed. But realistically there will always be upstream irregularities, and EFO users would benefit greatly from standard xrefs now.

So would it be possible to apply patches for common xref issues while doing the dynamic imports of ontologies? I am imagining this would be coded, so it would happen automatically every release-import cycle. Even just the small number of tweaks mentioned at https://github.com/EBISPOT/efo/issues/878#issuecomment-714635301 would go a long way in making EFO more useful for downstream applications.
