### ISSUE TITLE
New term request for Casto PMID 34269803

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1412]
For new term requests, please provide the following information:

## Preferred term label

Cytomegalovirus Virus Reactivation

## Synonyms

NA

## Textual definition

The switching of latent cytomegalovirus to a lytic infection. [ NCI ]

## Suggested parent term

There is an NCIT term which is under parent term 'Virus Reactivation'
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C160246

## Attribution

NA

**Comment by zoependlington** [comment]
This term has been added as EFO:0020106 and will be available after the January EFO release.
