### ISSUE TITLE
Review EFO_0008864

### ISSUE THREAD

**Issue by pavelVPo** [EBISPOT/efo#1417]
Hello,

Term [EFO_0008864](http://www.ebi.ac.uk/efo/EFO_0008864), Phi29 DNA polymerase multiple amplification (PMA), is given as the subclass of [EFO_0001457](http://www.ebi.ac.uk/efo/EFO_0001457), RNA assay, which is an assay to measure/analyze some RNA.
However, Phi29 DNA polymerase multiple amplification (PMA) is more about measuring/analyzing DNA.
See:
https://en.wikipedia.org/wiki/Multiple_displacement_amplification#Phi_29_DNA_polymerase
Kumar, Gyanendra et al. “Improved multiple displacement amplification with phi29 DNA polymerase for genotyping of single human cells.” BioTechniques 44 7 (2008): 879-90.
Thus, Term [EFO_0008864](http://www.ebi.ac.uk/efo/EFO_0008864), Phi29 DNA polymerase multiple amplification (PMA), is rather should be included in [EFO_0001456](http://www.ebi.ac.uk/efo/EFO_0001456), DNA assay, along with the [EFO_0008800](http://www.ebi.ac.uk/efo/EFO_0008800), Multiple displacement amplification (MDA).

Thanks, regards.

**Comment by paolaroncaglia** [comment]
Dear @pavelVPo ,
Thank you for reporting this. We'll address your suggestion and will comment back here when done.
Best wishes,
Paola Roncaglia, for the EFO team.

**Comment by paolaroncaglia** [comment]
@pavelVPo 
Your suggestions have been implemented and will be visible in the next EFO release, scheduled for Jan. 17th.
Thanks,
Paola

**Comment by pavelVPo** [comment]
Paola, thank you for the response.

Regards, Pavel Pogodin
IBMC
dep. of Bioinformatics
LSFBDD.


-------- Оригинальное Сообщение --------
От: paolaroncaglia ***@***.***>
Отправлено: Fri Jan 14 18:58:02 GMT+03:00 2022
Кому: EBISPOT/efo ***@***.***>
Копия: pavelVPo ***@***.***>, Mention ***@***.***>
Тема: Re: [EBISPOT/efo] Review EFO_0008864 (Issue #1417)

@pavelVPo 
Your suggestions have been implemented and will be visible in the next EFO release, scheduled for Jan. 17th.
Thanks,
Paola
