### ISSUE TITLE
New term request for Oh PMID 34680357

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1418]
For new term requests, please provide the following information:

## Preferred term label

radical prostatectomy

## Textual definition

The surgical removal of all of the prostate as well as some surrounding tissue, including lymph nodes.

## Suggested parent term

medical procedure

## further info

existing in NCIT: http://purl.obolibrary.org/obo/NCIT_C15399

**Comment by zoependlington** [comment]
Term added as EFO_0020684 which will be available after our January release (17th).
