### ISSUE TITLE
Requested new term: Sort-seq

### ISSUE THREAD

**Issue by ESapenaVentura** [EBISPOT/efo#1426]
For new term requests, please provide the following information:

## Preferred term label

Sort-seq

## Synonyms

No synonyms

## Textual definition

SORT-seq uses FACS to sort single-cells into the wells of a 384-well cell-capture plate. Each well in the plate contains barcoded primers and other reagents.

This sorting step makes it possible to analyze live single-cells, or any other particular population of interest. SORT-seq is a partially robotized version of the CEL-seq2 protocol.

(Taken from [here](https://www.scdiscoveries.com/technology/sort-seq/)
(First described [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5092539/)

## Suggested parent term

[CEL-seq2](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010010&viewMode=All&siblings=false)

## Attribution

0000-0003-4554-9040

**Comment by ESapenaVentura** [comment]
Tagging @paolaroncaglia ^

**Comment by paolaroncaglia** [comment]
@ESapenaVentura thank you, I'll add the new term in time for the next EFO + HCAO monthly releases. Unfortunately the January releases have just been done, so the next ones will be on Feb. 15th and 16th respectively. I'll update this ticket when the new term ID is available.
Best wishes,
Paola

**Comment by paolaroncaglia** [comment]
Note to self:
- [ ] Edit label to SORT-seq, as per references provided (the one we'll include has PMID:27693023);
- [ ] Add sort-seq as an exact synonym;
- [ ] Add "sorting and robot-assisted transcriptome sequencing" as an exact synonym, as per reference provided;
- [ ] Edit definition slightly to conform to "differentia" style "An x that y": "A partially robotized version of the CEL-seq2 protocol that uses FACS to sort single cells into the wells of a 384-well cell-capture plate. Each well in the plate contains barcoded primers and other reagents. This sorting step makes it possible to analyze live single cells, or any other particular population of interest.";
- [ ] Remember to include Enrique's ORCID.

**Comment by paolaroncaglia** [comment]
Hi @ESapenaVentura ,
The new term is EFO_0030074 (SORT-seq).
It will be available with the next EFO release (Feb 15), and will be imported in the HCAO release scheduled for Feb 16.
