### ISSUE TITLE
Term request "ANGPTL8 measurement" for GWAS PMID 33619548

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1428]
For new term requests, please provide the following information:

## Preferred term label

ANGPTL8 measurement

## Textual definition

Quantification of the levels of ANGPTL8 protein in a sample, typically blood plasma.

## Suggested parent term

protein measurement

**Comment by zoependlington** [comment]
This term will be available after out February (15th) release: EFO_0020861
