### ISSUE TITLE
New term "cDNA microarray" as child of instrument ... DNA array

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#1429]
## Preferred term label

cDNA microarray

## Synonyms

spotted cDNA array, complementary DNA microarray

## Textual definition

cDNA microarrays usually contain many thousands of spots of DNA, generated from the reverse transcription of messenger RNA and propagated in bacterial vectors. While their main application is in the generation of transcriptomic profiles, they also can be used for genomic analyses such as copy number profiling experiments.

## Suggested parent term

[DNA array](http://www.ebi.ac.uk/efo/EFO_0002701)

## Attribution

[0000-0002-9903-4248](https://orcid.org/0000-0002-9903-4248)

**Comment by mbaudis** [comment]
This is in line w/ previous submissions & fills the need we see when documenting technical provenance of CNV data in [Progenetix](http://progenetix.org).

**Comment by paolaroncaglia** [comment]
@mbaudis I'll address this in time for the next EFO release (Feb 15th), and will update with new term ID when ready.

**Comment by mbaudis** [comment]
Brilliant - thanks a lot for the extremely fast response :-)

**Comment by paolaroncaglia** [comment]
@mbaudis 
The new term is EFO_0030075 (cDNA microarray).
It will be available with the EFO release scheduled for Feb 15th.
