### ISSUE TITLE
New terms request for Li-Gao PMID 34610981 (WC_20220124)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1430]
40 terms related to change in concentration of a metabolite between the fasting and postprandial state,

https://docs.google.com/spreadsheets/d/1jDfESgRbjCbn7AceoOIkYntIUt9Qok7W6zH6alzHCYY/edit#gid=1909577919

**Comment by zoependlington** [comment]
Hi @Santhi1901, I have transferred this request to the new template that we are trialling to replace the Webulous forms (see the same Google Sheet but under the "NEW TEMPLATE" tab). I have highlighted the cells in bright yellow that still require information based on optional, not needed and needed columns. If you're able, it would be a big help if you could complete those cells so I can add these in for our February release.

**Comment by Santhi1901** [comment]
@zoependlington I will fill those cells

**Comment by zoependlington** [comment]
Thank you @Santhi1901!

**Comment by zoependlington** [comment]
All terms are now in EFO and the IDs are on the new template spreadsheet. They'll be available after our February release.
