### ISSUE TITLE
New term request for Cutrer PMID 33829662

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1431]
For new term requests, please provide the following information:

## Preferred term label

response to verapamil

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of verapamil stimulus

## Suggested parent term

response to calcium channel blocker

## Attribution

NA

**Comment by zoependlington** [comment]
This term will be available after out February (15th) release: EFO_0020862
