### ISSUE TITLE
New term request for Stanislawski PMID 33910371

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1432]
For new term requests, please provide the following information:

## Preferred term label

Soluble CD14 measurement

## Synonyms

cluster of differentiation 14, sCD14

## Textual definition

Quantification of the circulating pattern recognition receptor CD14 in a sample such as blood plasma. 

## Suggested parent term

blood protein measurement

**Comment by zoependlington** [comment]
This term will be available after out February (15th) release: EFO_0020860
