### ISSUE TITLE
New term request for Liu X, PMID 34158603

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1435]
For new term requests, please provide the following information:

## Preferred term label

major adverse cardiovascular event measurement 

## Synonyms

MACE

## Textual definition

quantification of some major cardiovascular event such as cardiovascular death, myocardial infarction, atherothrombotic stroke and repeated revascularization

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0006919

## Attribution

NA

**Comment by zoependlington** [comment]
This term will be available after out February (15th) release: EFO_0020863
