### ISSUE TITLE
New term "methylation-specific microarray" as child of instrument ... oligonucleotide DNA microarray

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#1441]
For new term requests, please provide the following information:

## Preferred term label

methylation-specific microarray

## Synonyms

methylation array

## Textual definition

Methylation arrays employ specifically designed oligonucleotides to probe the methylation status of e.g. CpG and CpHpG sites. They may also be applied to derive additional information such as genomic copy number variations.

## Suggested parent term

[oligonucleotide DNA microarray](http://www.ebi.ac.uk/efo/EFO_0010939)

## Attribution

[0000-0002-9903-4248](https://orcid.org/0000-0002-9903-4248)

**Comment by mbaudis** [comment]
@paolaroncaglia Filling more gaps - apologies for doing this piecemeal and not with https://github.com/EBISPOT/efo/issues/1429 ...

**Comment by paolaroncaglia** [comment]
Hi @mbaudis , no problem, I'll address this in time for the next EFO release.

**Comment by paolaroncaglia** [comment]
Note to self: def should read "An oligonucleotide DNA microarray that employs..."

**Comment by paolaroncaglia** [comment]
@mbaudis 
The new term is EFO_0030076 (methylation-specific microarray). 
It'll be in the Feb 15th EFO release.
