### ISSUE TITLE
New term request for Cell hashing

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1451]
For new term requests, please provide the following information:

## Preferred term label

Cell hashing

## Synonyms

CellPlex (not 100% sure about this, as this is 10X Genomics's specific implementation of the general cell hashing concept; maybe it deserves its own term).

## Textual definition

Cell hashing involves labelling cells with sample-specific oligonucleotides, typically through antibody- or lipid-based reagents, such that cells from distinct samples can be pooled together for single-cell sequencing. This multiplexed approach increases throughput, eliminates batch effects, and enables detection of multiplets.

PMID: 30567574

## Suggested parent term

EFO:0010183

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
I'll look into this in time for the next EFO release, scheduled for March 15th. Thank you.

**Comment by LTLA** [comment]
FYI it seems that EFO:0030009 would have some relation to the "cell hashing" term. They are not entirely synonymous, because you can perform cell hashing without CITE-seq antibodies (e.g., with lipid-based reagents), but CITE-seq-based sample multiplexing could certainly be considered a concrete realization of the general cell hashing procedure.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
Thanks for your helpful input. I will
- [ ] Add EFO:NEW 'cell hashing'
subclass of EFO:0010183 'single cell library construction'
narrow synonym: CellPlex 
definition: "A single cell library construction process that involves labelling cells with sample-specific oligonucleotides, typically through antibody- or lipid-based reagents, such that cells from distinct samples can be pooled together for single-cell sequencing. This multiplexed approach increases throughput, eliminates batch effects, and enables detection of multiplets."
def dbxrefs: PMID:30567574, https://orcid.org/0000-0002-3564-4813
- [ ] Make EFO:0030009 'CITE-seq (sample multiplexing)' a subclass of (also) EFO:NEW 'cell hashing', and add PMID:30567574 and https://orcid.org/0000-0002-3564-4813 as def dbxrefs to it also.

**Comment by paolaroncaglia** [comment]
@LTLA the new term is EFO_0030077 (cell hashing). It'll be public after the EFO release scheduled for March 15th. Thanks.
