### ISSUE TITLE
Wrong CURIE linked to "dye role" 

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/efo#1453]
The dye role term, currently [``CHEBI:37960``](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37960), corresponds to cyanine dye in the Chemical Entities of Biological Interest (ChEBI) ontology. I think this corresponds to a specific dye using the dye role, which in ChEBI corresponds to [``CHEBI:37958``](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:37958) (the correct CURIE).
![image](https://user-images.githubusercontent.com/77288380/154989273-720eede8-0829-4fd1-aa60-fffa52c58527.png)

Clones https://github.com/EBISPOT/OLS/issues/559.

**Comment by zoependlington** [comment]
Hi @M-casado, the CHEBI import in EFO is very old and, unfortunately, static meaning that it has not received any updates for some time. We are working through our imported ontologies to shift them to be dynamically imported (meaning any changes in the original ontology will appear in EFO)- see our epic ticket here: https://github.com/EBISPOT/efo/issues/623.

I believe this is a case of a static import which will hopefully be rectified soon once our CHEBI dynamic import is in place.

**Comment by M-casado** [comment]
Thanks for your quick response, @zoependlington. I see, the source changed but it did not propagate to EFO. 
I'm okay with it being fixed in a future upgrade as long as the issue is noticed 👍

**Comment by zoependlington** [comment]
I will move this ticket to the backlog so I can double check this is resolved after the CHEBI import has been updated. It's one of the next on the list to switch in EFO so should not be too far off 😄

**Comment by zoependlington** [comment]
This has been resolved by the updated CHEBI import and I have also imported CHEBI:37958 (dye) into EFO, which will be available after the November release.
