### ISSUE TITLE
New term request for Grgic O, PMID 34754074

### ISSUE THREAD

**Issue by ar-ibrahim** [EBISPOT/efo#1461]
## Preferred term label

Skeletal age

## Synonyms

Bone age, Skeletal maturity

## Textual definition

An indication of skeletal growth potential based on skeletal maturity indicators, such as radiologic imaging of growth plates.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0006887

## Attribution

NA

## Notes

- There's an NCIT term (NCIT:C156787) but it does not map after importing.
- Discussed with @buniello

**Comment by earlEBI** [comment]
Hi @zoependlington I'm trying to trace an error. It looks like both this term and fillagrin gene expression measurement have been given the same EFO ID? https://github.com/EBISPOT/efo/issues/1460#issuecomment-1056663578

**Comment by zoependlington** [comment]
Apologies, the above is a typo and should be EFO_0020898 for skeletal age!

**Comment by earlEBI** [comment]
@zoependlington thanks!
