### ISSUE TITLE
Unresolved missing EFO/GWAS terms

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#1465]
Tagging @eks-ebi @ljwh2 to keep you both updated.

The following terms are used by GWAS but seem to not be in EFO currently. Needs investigating.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/zmp/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/zmp/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

GWAS_EFO_URI | GWAS_EFO_ID | GWAS_EFO_label | Issue | Proposed_solution
-- | -- | -- | -- | --
http://purl.obolibrary.org/obo/HP_0010447 | HP_0010447 | anal fistula | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0021451 | MONDO_0021451 | benign neoplasm of brain | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0007197 | MONDO_0007197 | bladder diverticulum | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0024505 | MONDO_0024505 | disorder by anatomical region | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0000466 | MONDO_0000466 | first-degree atrioventricular block | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0014897 | MONDO_0014897 | portal hypertension | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0010837 | MONDO_0010837 | primary hyperparathyroidism | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0004754 | MONDO_0004754 | rectal prolapse | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/GO_0072710 | GO_0072710 | response to hydroxyurea | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0008420 | MONDO_0008420 | seborrheic keratosis | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/HP_0025236 | HP_0025236 | Somnambulism | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/HP_0025268 | HP_0025268 | Stuttering | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/DOID_0080180 | DOID_0080180 | Zika virus congenital syndrome | Term not in EFO | ask for import into EFO or creation of new term
http://purl.obolibrary.org/obo/MONDO_0000745 | MONDO_0000745 | cardiac arrest | Term not in EFO | ask for import into EFO?
http://purl.obolibrary.org/obo/HP_0000389 | HP_0000389 | chronic otitis media | Term not in EFO | ask for import into EFO?
http://purl.obolibrary.org/obo/MONDO_0005009 | MONDO_0005009 | congestive heart failure | Term not in EFO | merge with existing term in EFO and GWAS Cat?   http://www.ebi.ac.uk/efo/EFO_0000373
http://purl.obolibrary.org/obo/MONDO_0005492 | MONDO_0005492 | urticaria | Term not in EFO | merge with existing term in EFO and GWAS Cat?   http://www.ebi.ac.uk/efo/EFO_0005531
http://www.ebi.ac.uk/efo/EFO_0000373 | EFO_0000373 | congestive heart failure | Term is in EFO; label is not unique in GWAS Cat | remove conflicting MONDO term from GWAS Cat?   http://purl.obolibrary.org/obo/MONDO_0004754
http://www.ebi.ac.uk/efo/EFO_0005531 | EFO_0005531 | urticaria | Term is in EFO; label is not unique in GWAS Cat | remove conflicting MONDO term from GWAS Cat?   http://purl.obolibrary.org/obo/MONDO_0005492
http://purl.obolibrary.org/obo/NCIT_C82004 | NCIT_C82004 | brain-derived neurotrophic factor measurement | Term not in EFO | replace in GWAS Cat with equivalent EFO term:   http://www.ebi.ac.uk/efo/EFO_0011018
http://purl.obolibrary.org/obo/MONDO_0002176 | MONDO_0002176 | connective tissue cancer | Term not in EFO | replace in GWAS Cat with equivalent EFO term:   http://www.ebi.ac.uk/efo/EFO_1001184
http://www.ebi.ac.uk/efo/EFO_0011021 | EFO_0011021 | BRCA1 mutation carrier status | Term not in EFO; mentioned here but maybe not added:   https://github.com/EBISPOT/efo/pull/1022 | check with EFO team if these terms should be in EFO
http://www.ebi.ac.uk/efo/EFO_0011022 | EFO_0011022 | BRCA2 mutation carrier status | Term not in EFO; mentioned here but maybe not added:   https://github.com/EBISPOT/efo/pull/1022 | check with EFO team if these terms should be in EFO
http://www.ebi.ac.uk/efo/EFO_0000727 | EFO_0000727 | treatment | Term is in EFO, no apparent problem | ?

</body>

</html>

**Comment by zoependlington** [comment]
**To import:**
HP_0010447
MONDO_0007197
GO_0072710
HP_0025236
HP_0025268
MONDO:0000890 (will replace DOID_0080180)

**Existing in EFO:** @eks-ebi The following can be switched in GWAS to the existing terms in EFO (after the ->)
MONDO_0021451 -> EFO_1000107
MONDO_0000466 -> HP_0011705
MONDO_0014897 -> EFO_0000666
MONDO_0010837 -> EFO_0008519
MONDO_0004754 -> HP_0002035
MONDO_0008420 -> EFO_0005584
MONDO_0000745 -> EFO_0009492
HP_0000389 -> MONDO_0021204
MONDO_0005009 -> EFO_0000373
MONDO_0005492 -> EFO_0005531
NCIT_C82004 -> EFO_0011018

**Obsoleted in Mondo due to switch from anatomical to clinical view (in line with Open Targets):**
MONDO_0024505 (see https://github.com/monarch-initiative/mondo/issues/3661)

**Obsolete:**
MONDO_0002176 (https://github.com/monarch-initiative/mondo/issues/3593)

**To be created due to not existing:**
BRCA1 mutation carrier status
BRCA2 mutation carrier status

**In EFO, no problems:**
EFO_0000727

**Comment by eks-ebi** [comment]
@zoependlington I've replaced all of the "Existing in EFO" terms in the GWAS Catalog and found new more appropriate annotations for the 2 remaining obsoleted MONDO terms as well. So those are all resolved.

Shall we keep an eye out for updates here on the 6 "to import" terms and the 2 BRCA mutation terms?

> **To import:** 
HP_0010447 
MONDO_0007197 
GO_0072710 
HP_0025236 
HP_0025268 
MONDO_0000890 (will replace DOID_0080180)
> 
> **To be created due to not existing:** 
BRCA1 mutation carrier status 
BRCA2 mutation carrier status

I'll also create a separate ticket at our end to investigate EFO_0000727, because that doesn't seem to be an issue on the EFO side.

**Comment by zoependlington** [comment]
Brilliant!

Yes, I'll keep this ticket open to finish the imports and the new terms. I unfortunately did not have time to complete this before yesterday's release due to being off for a few days but they'll be available in our April release for sure!

**Comment by zoependlington** [comment]
The "to import" terms are now in EFO and will be available after the April (19th) release.

I still need to investigate the BRCA terms more carefully as they seem to have been created and merged at one point but have disappeared entirely.

**Comment by eks-ebi** [comment]
Thanks Zoe, that's great! I'll keep an eye out for updates on the BRCA terms

**Comment by zoependlington** [comment]
I've added the BRCA terms as their previous IDs since they weren't re-used:
EFO_0011021 -> BRCA1 mutation carrier status
EFO_0011022 -> BRCA2 mutation carrier status

Again they'll be available after the April (19th) release.

**Comment by eks-ebi** [comment]
Thanks Zoe!
