### ISSUE TITLE
EFO classifies CERVICAL RIB as reproductive disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#147]
There are questions from the MONDO team if Cervical Rib is properly classified as a child of 'reproductive disease'.

Please also determine if you think it is the same as https://omim.org/entry/117900

For more details see: https://github.com/monarch-initiative/mondo/issues/160

**Comment by zoependlington** [comment]
We have discussed this ticket and agree this is improperly classified as a child of reproductive system disease and propose the following:

- [ ] **EFO:EDIT** cervical rib syndrome (EFO:1000861)
     - Remove as subclass of reproductive system disease (EFO:0000512)
     - Add as subclass of thoracic outlet syndrome (EFO:0007507)

- [ ] **EFO:EDIT** thoracic outlet syndrome (EFO:0007507)
     - Add as subclass of nervous system disease (EFO:0000618) in conjunction with being a child of vascular disease
