### ISSUE TITLE
Include "protein" under "biological macromolecule" [suggestion]

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/efo#1470]
I suggest including ``protein`` ([CHEBI:36080](http://purl.obolibrary.org/obo/CHEBI_36080)) under ``biological macromolecule`` ([EFO:0004446](http://www.ebi.ac.uk/efo/EFO_0004446)), given their definitions:

- ``biological macromolecule`` (suggested parent node): _Anatomical structure which has as its parts one or more ordered aggregates of nucleotide, **amino acid**, fatty acid or sugar molecules bonded to one another_.
- ``protein`` (suggested child node): _A **biological macromolecule** minimally consisting of one polypeptide chain synthesized at the ribosome_.

**Comment by paolaroncaglia** [comment]
@M-casado (cc @zoependlington )
Thank you for your suggestion:

> I suggest including `protein` ([CHEBI:36080](http://purl.obolibrary.org/obo/CHEBI_36080)) under `biological macromolecule` ([EFO:0004446](http://www.ebi.ac.uk/efo/EFO_0004446)), given their definitions:
> 
> * `biological macromolecule` (suggested parent node): _Anatomical structure which has as its parts one or more ordered aggregates of nucleotide, **amino acid**, fatty acid or sugar molecules bonded to one another_.
> * `protein` (suggested child node): _A **biological macromolecule** minimally consisting of one polypeptide chain synthesized at the ribosome_.

I support your suggestion; CHEBI 'protein' is in fact a descendant of CHEBI 'biomacromolecule'. At present, CHEBI is not imported dynamically into EFO (although we might in the future, as per #623 ), therefore that link is not captured in EFO. 
@zoependlington would you like me to make CHEBI 'protein' a subclass of EFO 'biological macromolecule', in the meantime? (While still leaving it as a subclass of CHEBI 'chemical entity' of course.)

**Comment by zoependlington** [comment]
@paolaroncaglia I agree, please go ahead with this fix and I will bump up priority of the CHEBI import. Thanks.

**Comment by paolaroncaglia** [comment]
@M-casado I'll do the edit in time for the next EFO release (scheduled for May 16th).

**Comment by M-casado** [comment]
Awesome, thank you very much, both @paolaroncaglia & @zoependlington!

**Comment by paolaroncaglia** [comment]
@M-casado CHEBI 'protein' is now a subclass of EFO 'biological macromolecule'. The change will be visible with the new EFO release scheduled for May 16th.
