### ISSUE TITLE
New term request for Drake PMID 34743218

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1478]
For new term requests, please provide the following information:

## Preferred term label

galactin-1 measurement

## Textual definition

quantification of the amount of galectin-1 in a sample

## Suggested parent term

blood protein measurement

**Comment by earlEBI** [comment]
@zoependlington thank you! (to note, sorry, i made a typo, should be "galectin-1 measurement" if poss - thank you!)

**Comment by zoependlington** [comment]
Typo updated! Thanks @earlEBI!

**Comment by earlEBI** [comment]
thank you!
