### ISSUE TITLE
Abnormality of the eye (HP_0000478) has wrong definition

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#148]
There seems to be an artefact: Abnormality of the eye is defined as "inheres_in some eye".  The correct definition is there as well, so I think it might have been simply overlooked). As it can cause some weird inferences, maybe it should be deleted.

**Comment by zoependlington** [comment]
- [ ] EFO:EDIT Abnormality of the eye (HP:0000478)
     - Remove equivalent to inheres_in some eye
     - X-refs:
          - MSH:D005124
          - MSH:D005128
          - SNOMEDCT_US:19416009
          - UMLS:C0015393
          - UMLS:C0015397
          - SNOMEDCT_US:371405004
          - SNOMEDCT_US:371409005
     - Synonym: abnormal eye
