### ISSUE TITLE
Fix parents for Hi-C - EFO:0007693

### ISSUE THREAD

**Issue by sbreiff** [EBISPOT/efo#1480]
We requested some new terms and term edits a couple years ago for the 4D Nucleome Network (https://github.com/EBISPOT/efo/issues/504) but it looks as though Hi-C was assigned the parent term "Ligation-free chromosome conformation capture assay" (EFO:0009968) rather than "Ligation-mediated chromosome conformation capture assay" (EFO:0009967), as Hi-C assays do involve a ligation step. Could this be corrected?

**Comment by paolaroncaglia** [comment]
Hi @sbreiff ,
I'll look into this in time for the next EFO release (scheduled for April 19th). I'll comment back here when done.

**Comment by paolaroncaglia** [comment]
@sbreiff 

> We requested some new terms and term edits a couple years ago for the 4D Nucleome Network (#504) but it looks as though Hi-C was assigned the parent term "Ligation-free chromosome conformation capture assay" (EFO:0009968) rather than "Ligation-mediated chromosome conformation capture assay" (EFO:0009967), as Hi-C assays do involve a ligation step. Could this be corrected?

This is done now and will be public with the next EFO release, scheduled for April 19th. Thank you.

Paola
