### ISSUE TITLE
New term request for Wu PMID 34801968

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1488]
For new term requests, please provide the following information:

## Preferred term label

lysophosphatidylcholine 15:0 measurement

## Synonyms

LysoPC(15:0)

## Textual definition

The quantification of lysophosphatidylcholine 15:0 levels in a sample.

## Suggested parent term

[lysophosphatidylcholine measurement](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010356&viewMode=All&siblings=false#)

**Comment by zoependlington** [comment]
Thanks @earlEBI! Term has been added as EFO_0020941 and will be available after the April (19th) release.
