### ISSUE TITLE
New term request for Wu PMID 34801968

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1489]
For new term requests, please provide the following information:

## Preferred term label

propionylcarnitine measurement

## Textual definition

Quantification of propionylcarnitine in a sample. 

## Suggested parent term

cardiovascular disease biomarker measurement

**Comment by zoependlington** [comment]
Thanks @earlEBI! Term has been added as EFO_0020942 and will be available after the April (19th) release.
