### ISSUE TITLE
New lipid ratio trait request x5 for Richardson PMID 35213538

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1490]
## See attached Webulous form:
[webulous.-.WC_20220323_measurement.xlsx](https://github.com/EBISPOT/efo/files/8339987/webulous.-.WC_20220323_measurement.xlsx)

## Preferred term label

Cholesterol:total lipids ratio
Cholesteryl esters:total lipids ratio
Free cholesterol:total lipids ratio
Phospholipids:total lipids ratio
Triglycerides:total lipids ratio

**Comment by zoependlington** [comment]
The following have been added and will be available after the April (19th) release:

Cholesterol:total lipids ratio (EFO_0020943)
Cholesteryl esters:total lipids ratio (EFO_0020944)
Free cholesterol:total lipids ratio (EFO_0020945)
Phospholipids:total lipids ratio (EFO_0020946)
Triglycerides:total lipids ratio (EFO_0020947)
