### ISSUE TITLE
New term request for Hong PMID 34815255 ? 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1495]
For new term requests, please provide the following information:

## Preferred term label

clonal hematopoiesis mutation measurement 

## Textual definition

Quantification of the number of known clonal hematopoiesis mutations in a sample. 

## Suggested parent term

- measurement 
- new term: mutation measurement ? 
- [clonal hematopoiesis](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010819)

## from text: 
"Potential CH mutations were identified by a set of hierarchical filtering criteria in different exonic regions"
"The following criteria were used to retain mutations: (i) sites with coverage > 1⁄4 20; (ii) variant allele fraction (VAF) <35%; (iii) binomial model FDR-adjusted P < 0.001; (iv) sites were reported in Catalogue of Somatic Mutations in Cancer (COSMIC) version 92 (19)."
"Association analysis of genome-wide genetic variants identified dozens of genetic loci associated with CH mutations"
"We applied a linear regression model, with the number of CH mutations in each sample as the dependent variable, genotype of each SNP as independent variables."

**Comment by zoependlington** [comment]
I've added as a child of measurement with an equivalence axiom to 'measurement is about some clonal hematopoiesis' for now. If we require the mutation measurement in the future due to more terms, then we can create it. The ID is EFO_0020949 and will be available after the April (19th) release.
