### ISSUE TITLE
New term / import request for Shaw PMID 34861174

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1496]
For new term requests, please provide the following information:

## Preferred term label

stuttering

## Textual definition

Disruptions in the production of speech sounds, with involuntary repetitions of words or parts of words, prolongations of speech sounds, or complete blockage of speech production for several seconds.

## Suggested parent term

[Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004730)

**Comment by zoependlington** [comment]
Hi @earlEBI HP_0025268 seems to already be in EFO due to recent import updates, so it will be available after our April (19th) release.

**Comment by earlEBI** [comment]
brilliant, thank you!
