### ISSUE TITLE
Unmapped CHEBI terms for OTAR metabolon data

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#150]
Continued from https://github.com/EBISPOT/efo/issues/20.

Terms that were not mapped are located here:
https://docs.google.com/spreadsheets/d/1CEEid-hAvkhpurE9KJDzZvQb9nt2v8m2qYfSQPd8cJI/edit?usp=sharing

**Comment by paolaroncaglia** [comment]
I think that the problem with (at least some) unmapped Metabolon terms is that chemical labels often have synonyms that are quite diverse from the primary labels, so a lexical search may not always work well, and it may catch the conjugate acid or base instead. That may depend on whether Zooma includes ChEBI synonyms or not, I'm thinking probably not, @simonjupp do you know? I'm looking manually at entries in the spreadsheet (https://docs.google.com/spreadsheets/d/1AQBVPRSNlBDBiaQbEXZ05RnnxGlLrWvxIFnTaf62Atk/edit?usp=sharing) and I’m finding that the specific base (or acid) term from Metabolon is often available in ChEBI. I’m adding those more precise ChEBI mappings to the spreadsheet.

Bit weird though as I've found 3 exact lexical matches out of the first 8 entries in the spreadsheet... and those 3 terms have been in ChEBI for a while...

Lines in green indicate mappings that had already been picked up by Zoe.

**Comment by paolaroncaglia** [comment]
Note for OntoTools scrum 1/11/18:
This ticket can't be completed before the next ChEBI release on 1/11/18 and OLS picking it up on 2/11/18. Therefore, I'm removing the 01/11/18 milestone, and moving to backlog. I'll pick this ticket up again wc 5/11.

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio,
FYI, we have completed review and addition of ChEBI terms requested previously for OTAR Metabolon data (see https://github.com/EBISPOT/efo/issues/20). The ChEBI terms needed are either already in EFO or have been added in recent commits; the newly added terms will be visible after the next EFO release on Nov. 15th. Thanks.
