### ISSUE TITLE
Import terms from MONDO/HP

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1506]
Hi!

Could you please import these 2 terms from MONDO/HP to EFO? These are traits used in the latest FINNGEN release for which we have not found an equivalent in EFO.

| disease_name | disease_id | 
| ------------- | ------------- |
| dental malocclusion | HP_0000689  |
| chronic gingivitis | MONDO_0020782  |

Thanks!

**Comment by zoependlington** [comment]
Thanks @ireneisdoomed! These terms have been added and will be available after our April release (19th).
