### ISSUE TITLE
New term request for PMID: 35013273

### ISSUE THREAD

**Issue by ar-ibrahim** [EBISPOT/efo#1512]
New terms for **phytosterol** subclasses.

From main text: _"Phytosterols are cholesterol homologues synthesized by plants only. Therefore, phytosterol concentrations in mammals can be completely attributed to nutrition, where it can mainly be found in plant oils, nuts and seeds."_

https://docs.google.com/spreadsheets/d/12K6Ns-TD8Qy12Qreg8kcnEetKeXXYtcL8uA4VcDICYY/edit#gid=0

**Comment by zoependlington** [comment]
I have added the IDs for these terms to the spreadsheet. These terms will be available after today's release.
