### ISSUE TITLE
New term request for PMID: 34563919

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1519]
For new term requests, please provide the following information:

## Preferred term label

Somnambulism

## Synonyms

NA

## Textual definition

Ambulation or other complex motor behaviors after getting out of bed in a sleep-like state. During sleepwalking episodes, the sonambulating individual appears confused or dazed, the eyes are usually open, and he or she might mumble or give inappropriate answers to questions, or occasionally appear agitated. [ http://www.ncbi.nlm.nih.gov/pubmed/27647645 ]

## Suggested parent term

Present in http://purl.obolibrary.org/obo/HP_0025236

## Attribution

NA

**Comment by zoependlington** [comment]
Sonambulism ([HP_0025236](http://purl.obolibrary.org/obo/HP_0025236)) is already in EFO, so I'll move this ticket to done. Please reply to the ticket if there are any problems.

**Comment by Santhi1901** [comment]
@zoependlington I am not able to find this ID in EFO. 
<img width="1611" alt="Screenshot 2022-04-28 at 2 47 54 pm" src="https://user-images.githubusercontent.com/57477790/165767179-32535dba-fa6f-4397-9fc3-44f1ee4595f1.png">
