### ISSUE TITLE
New term request for PMID:34125832

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1521]
For new term requests, please provide the following information:

## Preferred term label

Zika virus congenital syndrome

## Synonyms

NA

## Textual definition

A congenital birth syndrome that arises from materal Zika infection. [ https://www.cdc.gov/pregnancy/zika/testing-follow-up/zika-syndrome-birth-defects.html ]

## Suggested parent term

Present in http://purl.obolibrary.org/obo/MONDO_0000890

## Attribution

NA

**Comment by zoependlington** [comment]
This term is already in EFO (see screenshot below) so I will move this to done.

![image](https://user-images.githubusercontent.com/36990116/165909137-67874e29-8a49-478b-a7d6-c9e019ac652c.png)
