### ISSUE TITLE
EFO terms with URI having capital EFO

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1522]
Found some of the EFOs URI has capital EFO (http://www.ebi.ac.uk/EFO/). Some examples are
EFO_0020883
EFO_0020896
EFO_0020881
EFO_0020891
EFO_0020882
EFO_0020889
EFO_0020857
EFO_0020906
EFO_0020907
EFO_0020908
EFO_0020866
EFO_0020904
EFO_0020868
EFO_0020869
EFO_0020893
EFO_0020894
EFO_0020895
EFO_0020901
EFO_0020905
EFO_0020870
EFO_0020872
EFO_0020873
EFO_0020874
EFO_0020875
EFO_0020876
EFO_0020877
EFO_0020878
EFO_0020879
EFO_0020880
EFO_0020884
EFO_0020885
EFO_0020887
EFO_0020888
EFO_0020890
EFO_0020892
EFO_0020892
EFO_0020886

In the downloadable study file in GWAS Catalog these terms and URI were missing even though it is available in the UI. Not sure if this capitalization of EFO in the URI is linked to this problem

**Comment by zoependlington** [comment]
I've changed all of these so they should be correct. If there are still issues after the May release, please let me know!

**Comment by zoependlington** [comment]
@Santhi1901 When running tests I've found that EFO_0020867 is in the GWAS system (downloaded from https://www.ebi.ac.uk/gwas/api/search/downloads/trait_mappings) as http://www.ebi.ac.uk/EFO/EFO_0020867 twice, which is causing EFO to fail. Is there any chance that this can be updated to http://www.ebi.ac.uk/efo/EFO_0020867? Thanks!

**Comment by ireneisdoomed** [comment]
I think this issue is still present in the newest EFO release. I've checked the EFO Slim file and 7619/20931 have an URI as the term name, which causes us downstream problems.
Some examples:
```
 'http://www.ebi.ac.uk/efo/EFO_0005126',
 'http://www.ebi.ac.uk/efo/EFO_0008222',
 'http://www.orpha.net/ORDO/Orphanet_99945',
 'http://www.ebi.ac.uk/efo/EFO_0010259',
 'http://www.ebi.ac.uk/efo/EFO_1000433',
 'http://www.ebi.ac.uk/efo/EFO_0009159',
 'http://www.orpha.net/ORDO/Orphanet_98708',
 'http://www.ebi.ac.uk/efo/EFO_0007783',
 'http://www.ebi.ac.uk/efo/EFO_0020909',
 'http://www.orpha.net/ORDO/Orphanet_166081',
 'http://www.orpha.net/ORDO/Orphanet_98813',
 'http://www.orpha.net/ORDO/Orphanet_166305',
 'http://www.ebi.ac.uk/efo/EFO_0010375',
 'http://www.ebi.ac.uk/efo/EFO_0010800',
 'http://www.ebi.ac.uk/efo/EFO_0020599',
 'http://www.ebi.ac.uk/efo/EFO_0020589',
 'http://www.ebi.ac.uk/efo/EFO_0010137',
 'http://www.ebi.ac.uk/efo/EFO_0004999',
 'http://www.ebi.ac.uk/efo/EFO_0020715',
 'http://www.ebi.ac.uk/efo/EFO_0009113',
 'http://www.orpha.net/ORDO/Orphanet_183643',
 'http://www.ebi.ac.uk/efo/EFO_0009391',
 'http://www.ebi.ac.uk/efo/EFO_0021399',
 'http://www.ebi.ac.uk/efo/EFO_0010438',
 'http://www.ebi.ac.uk/efo/EFO_0021488',
```

Could you please check it?

**Comment by zoependlington** [comment]
@ireneisdoomed I do not see this in my local version of EFO, as all these terms seem to have proper URIs, so I believe this is a separate issue. Could you create a new ticket so I can look into this further? Thanks!
