### ISSUE TITLE
4 New term requests for Brüggemann PMID 34982741

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1527]
For new term requests, please provide the following information:

## Preferred term label

1. revision of total knee arthroplasty 
(Existing in NCIT: [Revision of Total Knee Arthroplasty](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C51567#))

2. revision of total hip arthroplasty

3. revision of total joint arthroplasty

4. total knee arthroplasty

## Textual definition
1.  A surgical procedure of the knee joint in which some or all of the parts of the original prosthesis are removed and replaced for the purpose of correcting any problems that have developed since the initial surgery, such as aseptic loosening.

2. A surgical procedure of the hip joint in which some or all of the parts of the original prosthesis are removed and replaced for the purpose of correcting any problems that have developed since the initial surgery, such as aseptic loosening.

3. A surgical procedure of a joint in which some or all of the parts of the original prosthesis are removed and replaced for the purpose of correcting any problems that have developed since the initial surgery, such as aseptic loosening.

4. A surgical procedure in which the knee joint is replaced by a prosthetic implant. 

## Suggested parent term

1-3. [total joint arthroplasty](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010726#)

4. [medical procedure](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002571&viewMode=All&siblings=false#)

**Comment by zoependlington** [comment]
The following terms have been added:
EFO_0020972 - revision of total knee arthroplasty
EFO_0020973 - revision of total hip arthroplasty
EFO_0020974 - revision of total joint arthroplasty
EFO_0020975 - total knee arthroplasty

They'll be available after the May release (16th).
