### ISSUE TITLE
New term request for Ko PMID 34613391

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1539]
For new term requests, please provide the following information:

## Preferred term label

occupational attainment

## Synonyms

(e.g., Absent spleen)

## Textual definition

A measure of occupational attainment through eg. hierarchical categorisation using the Standard Occupational Classification (SOC) system.

## Suggested parent term

measurement

or 

[cognitive function measurement](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008354) ? 

## from text: 

"Occupational attainment, which represents middle-age cognitive activities, is a known proxy marker of cognitive reserve for Alzheimer’s disease"

"...educational attainment, another marker of cognitive reserve."

"In this analysis, we defined occupational attainment using the classified job levels formulated in the UK Standard Occupational Classification system considering the individual professional skill and academic level."

"...occupational attainment as a cognitive proxy..."

"Occupational attainment was operationally defined as a job code based on a hierarchy, starting from the highest level of managers and senior officials to the lowest level of elementary occupations. It was derived from the Standard Occupational Classification (SOC) system, developed by the UK Office of National Statistics"

**Comment by zoependlington** [comment]
This term has been added as EFO_0020977, which will be available after the May release (16th).
