### ISSUE TITLE
New term request for 'HLA typing using NGS'

### ISSUE THREAD

**Issue by gladkia** [EBISPOT/efo#1549]
For new term requests, please provide the following information:

## Preferred term label
HLA typing using NGS

## Synonyms
HLA typing using Next Generation Sequencing

## Textual definition
A method for identification of HLA antigen polymorphisms using a high-throughput sequencing platform.

## Suggested parent term
EFO:0002771

## Attribution
0000-0002-7059-6378

**Comment by paolaroncaglia** [comment]
@gladkia 
The new term is EFO:0030081 'HLA typing by NGS' (with "HLA typing using NGS" as an exact synonym; the suggested label was modified slightly to be consistent with other, existing terms in the branch). The new term will be available with the next EFO release, scheduled for May 16th.
