### ISSUE TITLE
New term request for 'PRS'

### ISSUE THREAD

**Issue by gladkia** [EBISPOT/efo#1550]
For new term requests, please provide the following information:

## Preferred term label
PRS

## Synonyms
polygenic risk scores, polygenic scores, genetic risk scores

## Textual definition
Polygenic risk score (PRS) are estimates of an individual’s genetic risk for some traits, obtained by aggregating and quantifying the effect of many common variants (usually defined as minor allele frequency ≥1%) in the genome, each of which can have a small effect on a person’s genetic risk for a given disease or condition.

## Suggested parent term
EFO:0001444

## Attribution
0000-0002-7059-6378

**Comment by paolaroncaglia** [comment]
@gladkia
The new term is EFO:0030082 'polygenic risk score' (with "PRS" as a broad synonym). The new term will be available with the next EFO release, scheduled for May 16th.

**Comment by gladkia** [comment]
@paolaroncaglia many thanks!
