### ISSUE TITLE
Start OBA trait : EFO measurement SSSOM file

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#1554]
- Use initial mappings [here](https://docs.google.com/spreadsheets/d/13qh7dLE38vMyz91oRqj6GzKjFohNazNKAJxKG6Plw1o/edit#gid=1454298570) to seed. Make sure to credit reviewers using ORCID.
- Host on EFO repo or on some phenotype mapping commons (@matentzn to advise)

**Comment by matentzn** [comment]
The starting point has been done https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/mappings/oba-efo.sssom.tsv
