### ISSUE TITLE
New term request for Schack PMID:35039627

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1555]
For new term requests, please provide the following information:

## Preferred term label

Tube feeding

## Synonyms

NA

## Textual definition

Feeding problem necessitating food and nutrient delivery via a tube.

## Suggested parent term

available in HP: http://purl.obolibrary.org/obo/HP_0033454

**Comment by zoependlington** [comment]
Term added to imports. It will be available after the June release.
