### ISSUE TITLE
Cross-references to obsolete/non-existent MeSH terms

### ISSUE THREAD

**Issue by bgyori** [EBISPOT/efo#1557]
I found that EFO currently contains xrefs to a number of obsolete MeSH terms that don't exist in its current release. One example is this line
```
AnnotationAssertion(skos:exactMatch efo:EFO_0000181 <http://identifiers.org/mesh/C535575>)
```
which points here [https://id.nlm.nih.gov/mesh/C535575.html](https://id.nlm.nih.gov/mesh/C535575.html). Is there a preferred way to deal with this? Should xrefs that cannot be replaced with a current term but are known to be obsolete removed?
Should I try replacing the ones that can be replaced with new/valid MeSH terms and PR the changes?

**Comment by zoependlington** [comment]
@bgyori Please feel free to submit a PR with removed incorrect x-refs and any replacements that exist. If you could tag myself to review, that would be great. This is very welcome help to fix some old x-refs that we're very aware of in EFO. Thank you.

**Comment by dhimmel** [comment]
Looking at http://www.ebi.ac.uk/efo/EFO_0000181 (head and neck squamous cell carcinoma), it appears that the MeSH cross-references might be coming from Orphanet:

- MESH:C535575 (Orphanet:67037)
- MESH:C535575 (Orphanet:67037/e)

So one question is whether EFO is the right place to contribute the fix?

Also I'm kind of surprised that the cross-reference is to a MeSH concept rather than descriptor / supplemental concept record. Seems like might be best to map to the descriptor [`D000077195`](http://id.nlm.nih.gov/mesh/D000077195) for "Squamous Cell Carcinoma of Head and Neck".

**Comment by bgyori** [comment]
I am just now noticing that I seem to have forgotten to get back to this issue. @dhimmel's point is interesting that we'd actually be updating xrefs that were imported from Orphanet. In this particular case, it turns out that [Orphanet:67037](https://www.orpha.net/consor/cgi-bin/OC_Exp.php?Lng=EN&Expert=67037) is actually deprecated. I think if the goal is to improve EFO-MeSH mappings specifically (that was my goal) then going through Orphanet to apply fixes might not be worth it.

In terms of the cross-reference to a supplemental concept: I suspect the xref was added when the supplemental concept first appeared in MeSH but was later turned into a proper term and the supplemental concept was deleted. This is a fairly common reason for invalid xrefs to MeSH.

**Comment by dhimmel** [comment]
> In terms of the cross-reference to a supplemental concept: I suspect the xref was added when the supplemental concept first appeared in MeSH but was later turned into a proper term and the supplemental concept was deleted. This is a fairly common reason for invalid xrefs to MeSH.

That makes sense. You can disregard what I said about the concept. I had misread the MeSH browser and thought the Orphanet mapping was to a concept like [`M0530036`](https://id.nlm.nih.gov/mesh/M0530036.html) rather than a supplemental concept record.

**Comment by bgyori** [comment]
In the meantime, I found 348 unique xrefs from EFO to MeSH and out of these only 6 are to invalid terms (note: I'm not checking each xref in terms of actual correctness, just whether it's to a valid term), all supplemental terms, one of which is MESH:C535575. I will find appropriate replacements for these and PR a fix.

**Comment by zoependlington** [comment]
Thank you for investigating this @bgyori and @dhimmel! I believe some of these may come from our Mondo merged import (where we merge equivalent Mondo terms into the existing EFO ID) where Mondo has imported from other sources e.g. Orphanet. I'll review the PR and check to see if this is the case for the changes made there and review against the Mondo terms we import.
