### ISSUE TITLE
New term request for 10x transcription profiling (as a parent of the 5' and 3' terms)

### ISSUE THREAD

**Issue by LTLA** [EBISPOT/efo#1558]
For new term requests, please provide the following information:

## Preferred term label

10x transcription profiling

## Synonyms

N/A

## Textual definition

10x transcription profiling is the 10x-based single-cell technology that sequences mRNA molecules.

## Suggested parent term

EFO:0008995

It should also be the parent of the 5' and 3'-specific terms (EFO:0030003 and EFO:0030004). This is motivated by a scenario where we knew that a scRNA-seq dataset was generated using 10X but we did not know the specific protocol; having a parent term for "10X transcriptome profiling" would allow us to annotate these datasets as precisely as possible with our limited info.

## Attribution

0000-0002-3564-4813

**Comment by paolaroncaglia** [comment]
Note to self: add as suggested, including a definition gloss and a seeAlso AP.

**Comment by paolaroncaglia** [comment]
Hi @LTLA ,
I added the new term as EFO_0030080 (10x transcription profiling). 
It will be available with the new EFO release scheduled for May 16th.
