### ISSUE TITLE
New term request for Sharafeldin PMID:35379913

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1559]
For new term requests, please provide the following information:

## Preferred term label

bone marrow transplantation

## Synonyms

BMT

## Textual definition

A procedure to replace diseased bone marrow with transplanted healthy bone marrow cells. [ NCI ]

## Suggested parent term

medical procedure http://www.ebi.ac.uk/efo/EFO_0002571

## Attribution

NA

**Comment by zoependlington** [comment]
Added as EFO_0020989, which will be available after the May release.
