### ISSUE TITLE
New term request for Martin PMID 34996099

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1564]
For new term requests, please provide the following information:

## Preferred term label

chronic graft vs. host disease

## Textual definition

Complications among patients surviving >100 days post allogeneic transplantation.

## Suggested parent term

graft versus host disease
- also suggest updating this definition - remove the word "Acute". #

**Comment by zoependlington** [comment]
Unfortunately I'm unable to edit the parent definition as it comes from Mondo, but the requested term has been imported from Mondo (MONDO_0020547).
