### ISSUE TITLE
New term request for Connell PMID 35154085

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1566]
For new term requests, please provide the following information:

## Preferred term label

response to ustekinumab

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a ustekinumab stimulus. Ustekinumab is a human immunoglobulin monoclonal antibody, used in the treatment of eg. psoriasis. 

## Suggested parent term

response to drug

**Comment by dosumis** [comment]
I think best to add to EFO for now.  So far we've just been adding response to chemicals in CHEBI - but this seems to be a mAB drug https://en.wikipedia.org/wiki/Ustekinumab

**Comment by rays22** [comment]
Yes, this [monoclonal antibody-type drug](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C84237) is not in CHEBI.

**Comment by zoependlington** [comment]
Thanks @dosumis @rays22! Just wanted to double check before I confused any progress on the response to side 😄

**Comment by zoependlington** [comment]
Added as EFO_0020986, which will be available after the May (16th) release.
