### ISSUE TITLE
EPIC: fix all EquivalentClass definition lacking a genus

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#1584]
These are collected here: 
https://docs.google.com/spreadsheets/d/1Yyery5j0zDfVpm-C84QadHgVVcUvoPjgKdBAQvWu_qw/edit#gid=0

Examples of the problems caused by these axioms here  #1582

Generally fixing involves choosing a sensible genus term to add. If no obvious one is available,  then relax the equivalentClass to subClassof.

In a few cases there is some useful inference coming from the dodgy axioms, so best to check the results of changes on classification. This might help inform the choice of replacement genus.

Also watch out for hidden GCIs - subClassOf axioms on the same term as an EquivalentTo axiom that lead to unwanted inferences - some cracking examples on  #1582

**Comment by dosumis** [comment]
Did you check a reasoned diff?  I think some of these were doing useful work but needed to be tightened (by addition of a genus).

**Comment by zoependlington** [comment]
A lot of these were self references and any that weren't I added back as subclasses or updated the equivalence if it was appropriate so everything should be as it was.
