### ISSUE TITLE
EFO term requests for PMID 35144566

### ISSUE THREAD

**Issue by ar-ibrahim** [EBISPOT/efo#1587]
Request for **tumor markers** : _CA 50_ and _SCCA_

https://docs.google.com/spreadsheets/d/1TRIspemvg1x49HiKOKoODGVqf6iLjtVQ/edit#gid=1609159643

**Comment by zoependlington** [comment]
Added as EFO_0020994 and EFO_0020995 respectively. They'll be available after the June release.
