### ISSUE TITLE
New term request for Jiang PMID 35122707

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1588]
For new term requests, please provide the following information:

## Preferred term label

response to methazolamide

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of methazolamide, a systemic carbonic anhydrase inhibitor, commonly used to treat glaucoma.

## Suggested parent term

response to drug

**Comment by zoependlington** [comment]
Term added as EFO_0020996, which will be available after the June release.
