### ISSUE TITLE
New term request for Drögemöller PMID 35149390

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1591]
For new term requests, please provide the following information:

## Preferred term label

respnose to ondansetron

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of an ondansetron stimulus, an antiemetic used for the treatment of nausea and vomiting.

## Suggested parent term

response to drug

**Comment by zoependlington** [comment]
Term added as EFO_0020997, which will be available after the June release.
