### ISSUE TITLE
New metabolite measurement term requests for Shin PMID 24816252

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1593]
Requesting 422 metabolite levels / ratio terms

Robot form: 
[Shin EFO robot form.xlsx](https://github.com/EBISPOT/efo/files/8761548/Shin.EFO.robot.form.xlsx)

Please let me know if you want me to change anything in the form, thank you

**Comment by zoependlington** [comment]
Terms have been added and assigned EFO IDs between EFO:0020999 and EFO:0021420 (in order of the excel sheet). They will be available after the June release.
