### ISSUE TITLE
turn on define class definition import from HP

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#16]
Phenotypic abnormality subclasses in EFO2 uses the old definitions of the define classes from HP. HP has updated these axioms, the new axioms need to be cleanly imported in EFO3.

E.g. has component -> has modifier

Abnormality of metabolism/homeostasis in EFO2 uses
'has part' some
(quality and ('has component' some abnormal) and ('inheres in part of' some 'metabolic process'))

HP has updated this to be
has part some (
quality and
inheres in part of some metabolic process and
has modifier some abnormal)

**Comment by simonjupp** [comment]
Iceboxed until EFO 3

**Comment by matentzn** [comment]
+1
