### ISSUE TITLE
Improved xrefs for HER2 negative breast carcinoma (EFO:0009780)

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#1606]
Here's all the info for [HER2 negative breast carcinoma](http://www.ebi.ac.uk/efo/EFO_0009780) from [`efo-edit.owl`](https://github.com/EBISPOT/efo/blob/0343b744f078c1e46c3919baa95ecb974c15e4ce/src/ontology/efo-edit.owl):

```owl
# Class: efo:EFO_0009780 (HER2 negative breast carcinoma)

AnnotationAssertion(obo:IAO_0000115 efo:EFO_0009780 "A biologic subset of breast carcinoma defined by absence of HER2."^^xsd:string)
AnnotationAssertion(obo:IAO_0000117 efo:EFO_0009780 "Annalisa Buniello"^^xsd:string)
AnnotationAssertion(efo:definition_citation efo:EFO_0009780 "PMID:28864454"^^xsd:string)
AnnotationAssertion(oboInOwl:hasDbXref efo:EFO_0009780 "https://www.cancer.gov/publications/dictionaries/cancer-terms/def/her2-negative"^^xsd:string)
AnnotationAssertion(rdfs:label efo:EFO_0009780 "HER2 negative breast carcinoma"^^xsd:string)
SubClassOf(efo:EFO_0009780 efo:EFO_0000305)
SubClassOf(efo:EFO_0009780 ObjectSomeValuesFrom(efo:EFO_0000784 ObjectUnionOf(obo:UBERON_0000310 ObjectSomeValuesFrom(obo:BFO_0000050 obo:UBERON_0000310))))
```

Note that it's missing xrefs like:

- [`SNOMEDCT:431396003`](https://snomedbrowser.com/Codes/Details/431396003): Human epidermal growth factor 2 negative carcinoma of breast
- [`MONDO:0000618`](http://purl.obolibrary.org/obo/MONDO_0000618): Her2-receptor negative breast cancer
- And presumably more that I haven't searched for

Looking at [`EFO:1000294`](http://www.ebi.ac.uk/efo/EFO_1000294) for HER2 Positive Breast Carcinoma, there's many cross-references:

- NCIT:C53556 (exact-label-match)
- UMLS:C1960398 (NCIT:C53556)
- SCTID:427685000 (MONDO:equivalentTo)
- NCIT:C53556 (MONDO:exact-label-match)
- DOID:0060079 (MONDO:equivalentTo)
- EFO:1000294 (MONDO:equivalentTo)
- MONDO:0006244

How do we go about adding the missing xrefs for `EFO:0009780`? If we just add the MONDO xref, will the remaining xrefs be imported from MONDO... such that it's best to add as many xrefs to MONDO and just allow EFO to import them all from the single MONDO xref?

**Comment by zoependlington** [comment]
Hi @dhimmel, I will add the mapping for the Mondo term which will then bring int he Mondo x-refs. It is best in these cases to ensure that the Mondo term has x-refs as when mapped to EFO these will be brought in.

To do (for self): Add mapping as follows:

http://purl.obolibrary.org/obo/MONDO_0000618	http://www.ebi.ac.uk/efo/EFO_0009780	Her2-receptor negative breast cancer	HER2 negative breast carcinoma

**Comment by zoependlington** [comment]
They will be consistently updated as our Mondo import is dynamic - this means that any changes in Mondo will also be reflected in EFO.

**Comment by dhimmel** [comment]
> any changes in Mondo will also be reflected in EFO

Awesome. Went ahead and added more comprehensive xrefs to MONDO in https://github.com/monarch-initiative/mondo/pull/4992

**Comment by zoependlington** [comment]
I've added the mapping in EFO so after Mondo adds these x-refs and releases they will be available in the subsequent EFO release. Moving this ticket to Done.
