### ISSUE TITLE
intracranial hemorrhage NOS

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#161]
EFO Issue from @cmungall posted here EBISPOT/OLS#207

**Comment by zoependlington** [comment]
cmungall commented:
> https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000551
>
>this has two xrefs to NCIT in EFO. The first is to a finding not a disease. The second is a mistake as it is to NCIT:C34463 ! Chlamydial Infection
>
>Also: do you really need the NOS on the end?

Term looks like there was a mix up importing from bioportal, where intracranial hemorrhage and chlamydia trachomatis infectious disease are combined.

- [ ] **EFO:EDIT** intracranial hemorrhage NOS (EFO:0000551)
     - remove chlamydia related annotations
          - **Synonyms:** Chlamydia trachomatis infectious disease || chlamydial disease || chlamydial infection
          - **bioportal_provenance:** A commensal Chlamydiaceae infectious disease that is caused by a member of the genus Chlamydia, specifically C. trachomatis.[accessedResource: DOID:1126][accessDate: 05-04-2011] || Chlamydia trachomatis infectious disease[accessedResource: DOID:1126][accessDate: 05-04-2011] || Chlamydial Infection[accessedResource: DOID:1126][accessDate: 05-04-2011]
          - **X-refs:** NCIT:C34463 || SNOMEDCT:105629000
     - Edit label to intracranial hemorrhage

- [ ] **EFO:EDIT2** Chlamydia trachomatis infectious disease (EFO:0007205)
     - Add information from intracranial hemorrhage
          - **X-refs:** NCIT:C34463 || SNOMEDCT:105629000
