### ISSUE TITLE
Upon parsing the EFO OWL file, multiple syntax warnings are reported

### ISSUE THREAD

**Issue by tskir** [EBISPOT/efo#1626]
### Background
In Open Targets we're using the [pronto](https://github.com/althonos/pronto) library to work with the EFO OWL files. We noticed that upon ingesting the file, the library issues a few hundred various syntax warnings. I've looked into several of them, and it does look like those are genuine syntax issues, and not idiosyncrasies of the pronto library.

### The observed issues
The top 5 of the most common issues are:
* several names found (84)
* unknown element in `owl:ObjectProperty` (76)
* could not find axiom source (65)
* unknown element in `owl:Class` (34)
* unknown axiom property (28)

In total there are 310 syntax warnings. I attach the complete list to this issue: [efo_syntax_warnings.txt](https://github.com/EBISPOT/efo/files/8870045/efo_syntax_warnings.txt).

While not critical, it would be nice if some or all of those could be eventually fixed, so that the file fully conforms to the standards and there is complete chain of provenance for each and every term, class and attribute.

### Steps to reproduce
```bash
python3 -m pip install pronto==2.4.5
wget -q -O efo.owl https://github.com/EBISPOT/efo/releases/download/v3.42.0/efo.owl
python3 -c 'from pronto import Ontology; Ontology("efo.owl")' 2>&1 | grep SyntaxWarning | sort > efo_syntax_warnings.txt
```

**Comment by zoependlington** [comment]
Thanks for this information @tskir, I hope to look over this after I return from some annual leave and hopefully we can fix some of these issues over the summer!
