### ISSUE TITLE
New metabolite measurement term requests for Shin PMID 24816252 - part 2

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1628]
Sorry, I seem to have missed a few (14) terms I still need for this paper, provided in the below robot form. 
[Shin.EFO.robot.form - PART 2.xlsx](https://github.com/EBISPOT/efo/files/8892512/Shin.EFO.robot.form.-.PART.2.xlsx)
Thank you!

**Comment by zoependlington** [comment]
There were three terms that were already in EFO:

Term ID | Term label
-- | --
EFO_0020999 | 2-hydroxybutyrate measurement
EFO_0021397 | arachidonate 20:4n6-to-1-arachidonoylglycerophosphoinositol   ratio
EFO_0021419 | myristate 14:0-to-myristoleate 14:1n5 ratio

The rest have been created as follows:

Term ID | Term label
-- | --
EFO_0021506 | 2-hydroxyglutarate measurement
EFO_0021507 | 2-hydroxypalmitate measurement
EFO_0021508 | 4-hydroxyhippurate measurement
EFO_0021509 | cholate measurement
EFO_0021510 | linoleate 18:2n6 measurement
EFO_0021511 | phenyllactate measurement
EFO_0021512 | 1,7-dimethylurate measurement
EFO_0021513 | 3-4-hydroxyphenyl lactate-to-alpha-hydroxyisovalerate ratio
EFO_0021514 | acetylcarnitine-to-hexanoylcarnitine ratio
EFO_0021515 | androsterone sulfate-to-epiandrosterone sulfate ratio
EFO_0021517 | arachidonate 20:4n6-to-dihomo-linolenate 20:3n3 or n6 ratio
EFO_0021518 | linoleate 18:2n6-to-dihomo-linolenate 20:3n3 or n6 ratio
EFO_0021519 | linoleate 18:2n6-to-X-12442-5,8-tetradecadienoate ratio
EFO_0021521 | phenyllactate-to-phenylalanine ratio
