### ISSUE TITLE
Mispelled label for drug hypersensitivity syndrome

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#163]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_1002004

The label is mispelled (drug hypersensitivity sydrome).

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT** drug hypersensitivity sydrome (EFO:1002004)
    - Edit the label to correct to drug hypersensitivity syndrome
