### ISSUE TITLE
Missing new term for "4C-seq"

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#1635]
Dear EFO team, I had previously requested a [new term for 4C-seq](https://github.com/EBISPOT/efo/issues/1297). Unfortunately, the quoted new EFO accession doesn't lead to the right term. Could you look into this again for me please?

**Comment by paolaroncaglia** [comment]
@anjaf 

> Dear EFO team, I had previously requested a [new term for 4C-seq](https://github.com/EBISPOT/efo/issues/1297). Unfortunately, the quoted new EFO accession doesn't lead to the right term. Could you look into this again for me please?

I reopened and pinned #1297 to indicate high priority, so I'll close this ticket as a duplicate. Thank you.
