### ISSUE TITLE
New term requests for PMID 35501403: metal measurements

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1639]
7 terms requested with the same pattern.

## Preferred term label

blood arsenic measurement
blood barium measurement
blood rubidium measurement
blood tin measurement
blood strontium measurement
blood titanium measurement
blood vanadium measurement

## Synonyms

none

## Textual definition

Quantification of [name of metal] in a blood sample.

e.g. Quantification of **arsenic** in a blood sample.

## Suggested parent term

blood toxic metal measurement (http://www.ebi.ac.uk/efo/EFO_0007574)

I'm modelling these on existing blood metal measurement terms that are already under this parent. I'm not 100% sure if all are considered "toxic" metals. There could be some benefit in simplifying the parent term to be more neutral, i.e. blood metal measurement, in order to be able to include a wider range of child terms here. But for the current set of terms, I'm happy for it to be kept as is.

## Additional comment

The definitions of the existing child terms under "blood toxic metal measurement" seem to have carried over a bit of confusing wording from the parent definition. They all have the word "some" copied over, which doesn't really make sense when the specific metal is named. This could be a good opportunity to clean that up.

Parent definition:
quantification of **some toxic metal** in a blood sample

Child definitions (e.g. blood aluminium measurement http://www.ebi.ac.uk/efo/EFO_0007575): 
quantification of **some** aluminium in a blood sample

**Comment by zoependlington** [comment]
The following terms have been created:

Term label | Term ID
-- | --
blood arsenic measurement | EFO_0021527
blood barium measurement | EFO_0021528
blood rubidium measurement | EFO_0021529
blood tin measurement | EFO_0021530
blood strontium measurement | EFO_0021531
blood titanium measurement | EFO_0021532
blood vanadium measurement | EFO_0021533

I've also edited the definitions of the existing terms to make more sense, thanks for catching that!

These changes and new terms will be available after the July release (18th).

**Comment by eks-ebi** [comment]
Thanks @zoependlington!
