### ISSUE TITLE
shingles

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#164]
Please check the synonyms of 'Herpes Zoster'

There is a typo in 'singles' it should be 'shingles'
http://www.ebi.ac.uk/efo/EFO_0006510

'Zoster' can also be a synonym (http://purl.obolibrary.org/obo/NCIT_C71079)

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT** Herpes Zoster (EFO:0006510)
     - Edit alternative_term "singles" to correct type -> should be shingles

Herpes Zoster already has the synonym "zoster", therefore the synonym "Zoster" is not needed.
