### ISSUE TITLE
Adjustment to Reference and Abnormal samples/roles

### ISSUE THREAD

**Issue by M-casado** [EBISPOT/efo#1641]
Few comments to improve the information quality of **Reference and Abnormal samples/roles**:

- ``Reference sample`` [[EFO:0009654](http://www.ebi.ac.uk/efo/EFO_0009654)] **should be linked** (``has_quality``) to ``normal`` [[PATO:0000461](http://purl.obolibrary.org/obo/PATO_0000461)] property, just like ``abnormal sample`` [[EFO:0009655](http://www.ebi.ac.uk/efo/EFO_0009655)] is to ``abnormal`` [[PATO:0000460](http://purl.obolibrary.org/obo/PATO_0000460)]. 
- ``Abnormal sample`` [[EFO:0009655](http://www.ebi.ac.uk/efo/EFO_0009655)] **should have its counterpart role** ``abnormal`` under ``role`` [[BFO:0000023](http://purl.obolibrary.org/obo/BFO_0000023)] just like ``Reference sample`` [[EFO:0009654](http://www.ebi.ac.uk/efo/EFO_0009654)] does with ``control`` [[EFO:0001461](http://www.ebi.ac.uk/efo/EFO_0001461)].
- Both ``reference sample`` [[EFO:0009654](http://www.ebi.ac.uk/efo/EFO_0009654)] and ``abnormal sample`` [[EFO:0009655](http://www.ebi.ac.uk/efo/EFO_0009655)] **should be linked** to ``case control design`` [[EFO:0001427](http://www.ebi.ac.uk/efo/EFO_0001427)].

**Comment by zoependlington** [comment]
Thank you @M-casado, I will look into including these suggestions in our upcoming release.

**Comment by zoependlington** [comment]
I've updated most of these, minus adding role to abnormal (as in your second bullet) due to this term not being an EFO term. We're hoping to have a PATO dynamic import soon which will pull in up to date versions of PATO terms in EFO and may solve this. The changes I've made today will be available after our July (18th) release.

**Comment by M-casado** [comment]
Understood, thanks for adding my feedback!
