### ISSUE TITLE
New term request for Kulyte PMID: 35320353

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1642]
For new term requests, please provide the following information:

## Preferred term label

abdominal fat cell number

## Synonyms

fat cell number

## Suggested parent term

adipose tissue measurement (http://www.ebi.ac.uk/efo/EFO_0004764)

## Attribution

INA

**Comment by zoependlington** [comment]
Added as EFO_0021534, which will be available after the July (18th) release.
