### ISSUE TITLE
New term request for Zhu 35322040

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1643]
For new term requests, please provide the following information:

## Preferred term label

response to Par-4 dependent chemotherapy

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of Par-4 dependent chemotherapy stimulus.

## Suggested parent term

response to antineoplastic agent http://purl.obolibrary.org/obo/GO_0097327

## Attribution

NA

**Comment by zoependlington** [comment]
Added as EFO_0021535, which will be available after the July release.
