### ISSUE TITLE
New term request for Vollert PMID 35401282

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1644]
For new term requests, please provide the following information:

## Preferred term label

Irritable bowel syndrome symptom measurement

## Textual definition

Quantification of irritable bowel syndrome symptoms for instance using the IBS Symptom Severity Scale assessing pain frequency and intensity, bowel dysfunction or bloating.

## Suggested parent term

measurement

**Comment by zoependlington** [comment]
Added as EFO_0021536, which will be available after the July release.
