### ISSUE TITLE
New term request for Landini PMID 35332118

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1646]
For new term requests, please provide the following information:

## Preferred term label

transferrin glycosylation measurement

## Textual definition

Quantification of N-linked transferrin glycans in a sample

## Suggested parent term

transferrin measurement

## note
similar/related term: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005193

**Comment by zoependlington** [comment]
Added as EFO_0021537, which will be available after the July release.
