### ISSUE TITLE
text definition and axioms differ in technician role & experiment performer role 

### ISSUE THREAD

**Issue by StroemPhi** [EBISPOT/efo#1648]
When reading the text definitions of [EFO:technician](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009739) ("A person employed to look after technical equipment or do practical work in a laboratory.") and  [EFO:'experiment performer'](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000647) ("An individual who does some experimental process."), their asserted subclassOf axioms are contradictive:
```
# technician
'characteristic of' some Homo Sapiens (NCBITaxon_9606)
'characteristic of' some organization (OBI_0000245)

# experiment performer
'characteristic of' some 
    (NCBITaxon_9606
     and OBI_0000245)
```
Shouldn't these two roles only be `'role of' some NCBITaxon_9606`?

**Comment by zoependlington** [comment]
Thanks for this ticket @StroemPhi, I have made edits to these terms which will be available after the July (18th) release.
