### ISSUE TITLE
New term request for Cheng Y. PMID 35385482 

### ISSUE THREAD

**Issue by ar-ibrahim** [EBISPOT/efo#1650]
## Synonyms

SPP-1, Nephropontin, Bone Sialoprotein 1, Uropontin, Secreted Phosphoprotein 1, Urinary Stone Protein 

## Textual definition

Quantification of the amount of osteopontin protein in a sample

## Suggested parent term

EFO_0004555 (glycoprotein measurement)

** Term existing in NCIT ontology database NCIT_C46082

**Comment by zoependlington** [comment]
Term added as EFO_0021776, which will be available after the July (18th) release.
