### ISSUE TITLE
New term request for Brouwer PMID 35383335

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1657]
Robot EFO request form for brain morphology rate of change measurements:
[Brouwer EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/9048191/Brouwer.EFO.robot.form1.xlsx)

see Fig1 in paper for brain region diagram.

**Comment by zoependlington** [comment]
Terms have been added as the following:

Term ID | Term label
-- | --
EFO_0021490 | amygdala volume change   measurement
EFO_0021491 | caudate volume change measurement
EFO_0021492 | hippocampus volume change measurement
EFO_0021493 | nucleus accumbens volume change measurement
EFO_0021494 | pallidum volume change measurement
EFO_0021495 | putamen volume change measurement
EFO_0021496 | thalamus volume change measurement
EFO_0021497 | cerebellum cortex volume change measurement
EFO_0021498 | cerebellum white matter volume change measurement
EFO_0021499 | cerebral white matter volume change measurement
EFO_0021500 | cortex volume change measurement
EFO_0021501 | cortical thickness change measurement
EFO_0021502 | lateral ventricle volume change measurement
EFO_0021503 | cortical surface area change measurement
EFO_0021504 | total brain volume change measurement
