### ISSUE TITLE
New term requests (age of onset terms)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1658]
## Preferred term label

new term | suggested parent | existing term that should be child of new term|GWAS Catalog refs
--|--|--|--
age of onset of coronary stenosis | Onset (http://purl.obolibrary.org/obo/HP_0003674) | NA | 33766035
age of onset of glioblastoma multiforme | Onset | NA | 30152087
age of onset of systemic lupus erythematosus | Onset | NA | 29967481
age of onset of hypertension | Onset | age of onset of essential hypertension (http://purl.obolibrary.org/obo/OBA_2001010) | 34662886
age of onset of Machado-Joseph disease | Onset | NA | 32205469
age of onset of unipolar depression | Onset | NA | 22915352, 34662886, 35330412, 35347114

In addition, I suggest that one term be renamed and moved under a different parent term:

current label | suggested label | current parent | suggested parent
--|--|--|--
age of onset of migraine without aura, susceptibility to, 4 (http://purl.obolibrary.org/obo/OBA_2001028) | age of onset of migraine without aura | Onset | age of onset of migraine disorder (http://purl.obolibrary.org/obo/OBA_2001026)

This would better reflect the position of the corresponding disease term: http://purl.obolibrary.org/obo/MONDO_0100431

## Synonyms

All new terms should have the synonyms:
* age at onset of [disease name]
* age [disease name] symptoms begin

## Textual definition

All definitions should follow the pattern:
"The age at which [disease name] manifestations first appear."

## Suggested parent term

(see table above)

**Comment by rays22** [comment]
This issue depends on https://github.com/obophenotype/bio-attribute-ontology/issues/111
