### ISSUE TITLE
New term requests for age at initiation/occurrence of behaviours, treatments and procedures.

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1659]
The following terms are requested to represent 

## Preferred term label

1. age at initiation of treatment
_plus the following children:_
1a. age at initiation of hormone replacement therapy
1b. age at initiation of corrective lens use
1c. age of initiation of oral contraceptive pill use

2. age at medical procedure

3. age at initiation of smoking

4. age at initiation of cannabis use 

## Synonyms

Suggested synonyms for some of the above terms:

age at initiation of treatment:
* age at initiation of medical treatment

age at medical procedure:
* age at procedure
* age at intervention
* age at medical intervention

age at initiation of cannabis use:
* age at initiation of cannabis consumption

## Textual definition

age at initiation of treatment
* Age at initiation of a medical treatment, such as a drug, therapy or medical device.

age at initiation of hormone replacement therapy:
* Age at initiation of hormone replacement therapy, the therapeutic use of hormones to alleviate the effects of hormone deficiency.

age at initiation of corrective lens use:
* Age at initiation of the use of corrective lenses, such as glasses or contact lenses, to treat an abnormality of the eye.

age of initiation of oral contraceptive pill use
* Age at initiation of the use of an oral contraceptive pill.

age at medical procedure:
* Age at the time of a specific medical procedure or intervention intended to alter the course of a disease.

age at initiation of smoking:
* Age of initation of the habit of smoking, the inhaling and exhaling of tobacco smoke.

age at initiation of cannabis use 
* Age of initiation of the consumption of the drug cannabis.

## Suggested parent term

All requested terms should be children of:
* age - http://www.ebi.ac.uk/efo/EFO_0000246

(request that 'age at initiation of treatment' should have its own child terms, above)

**Comment by zoependlington** [comment]
Connected to #1693 (same big GWAS submission).

**Comment by rays22** [comment]
> Connected to #1693 (same big GWAS submission). Need to be in EFO for the August release (15th)
> 
> @rays22, are these candidates for OBA or should I add them on my side?

@zoependlington , I think it would be better if you add them on  your side.
Some of these terms may be tangentially related to biological traits that are covered by the 'age of onset' pattern in OBA (e.g. hormone replacement therapy), but most of the terms look like they would be a better fit for a clinical or health-care administration ontology (e.g. age at medical procedure).
In summary, I do not think these terms should be added to OBA.

**Comment by zoependlington** [comment]
Thanks @rays22, I'll add these before the EFO release. Will unassign you now.

**Comment by rays22** [comment]
> Thanks @rays22, I'll add these before the EFO release. Will unassign you now.

Thanks @zoependlington .

**Comment by rays22** [comment]
This branch of [NCIT](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25150&lang=en&viewMode=All&siblings=false) appears to cover many of these terms.

**Comment by zoependlington** [comment]
Unfortunately we don't import NCIT, but I'll make sure to x-ref these terms. Thanks Ray!

**Comment by zoependlington** [comment]
Terms have been added as follows and will be available after the August (15th) release:

age at initiation of treatment || EFO_0021779
age at initiation of hormone replacement therapy || EFO_0021780
age at initiation of corrective lens use || EFO_0021781
age at initiation of oral contraceptive pill use || EFO_0021782
age at medical procedure || EFO_0021783
age at initiation of smoking || EFO_0021784
age at initiation of cannabis use || EFO_0021785
