### ISSUE TITLE
Duplicate EFO terms

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1661]
diacylglycerol 36:1 measurement	http://www.ebi.ac.uk/efo/EFO_0010354
diacylglycerol 36:1 measurement	http://www.ebi.ac.uk/efo/EFO_0020060

diacylglycerol 36:2 measurement	http://www.ebi.ac.uk/efo/EFO_0010355
diacylglycerol 36:2 measurement	http://www.ebi.ac.uk/efo/EFO_0020061

**Comment by zoependlington** [comment]
I have obsoleted the following in favour of the other terms: diacylglycerol 36:1 measurement http://www.ebi.ac.uk/efo/EFO_0020060
diacylglycerol 36:2 measurement http://www.ebi.ac.uk/efo/EFO_0020061
