### ISSUE TITLE
New term request for PMID 35577822

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1663]
For new term requests, please provide the following information:

## Preferred term label

urinary 6‑hydroxymelatonin sulfate to creatinine ratio 

## Synonyms

NA

## Textual definition

Quantification of the ratio of 6‑hydroxymelatonin sulfate to creatinine in a urine sample

## Suggested parent term

urinary metabolite measurement (http://www.ebi.ac.uk/efo/EFO_0005116)

## Attribution

na

**Comment by zoependlington** [comment]
Added as EFO_0021437 which will be available after the July (18th) release.

**Comment by Santhi1901** [comment]
@zoependlington this same EFO is used for a different term: cholesteryl ester 17:1 measurement https://github.com/EBISPOT/efo/issues/1638
