### ISSUE TITLE
New term request for ExSeq

### ISSUE THREAD

**Issue by jychien** [EBISPOT/efo#1666]
## Preferred term label

ExSeq

## Synonyms

expansion sequencing

## Textual definition

A spatial transcriptomics assay that involves physically expanding specimens with polymer- and hydrogel-based systems followed by amplification of RNA and in situ sequencing using FISSEQ.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7900882/ (PMID: 33509999)

## Suggested parent term

For parent, it is not entirely clear as to where this best fits. According to https://wyss.harvard.edu/technology/fluorescent-in-situ-sequencing-fisseq/, FISSEQ is "allowing researchers to perform high throughput RNA sequencing". But, it is not clear what is meant by https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0030005. Currently, FISSEQ is only listed under "RNA assay": https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0008990. But, if FISSEQ is to be considered as "high-throughput", then the parents would be:
- spatial transcriptomics by high-throughput sequencing (EFO:0030005)

"ExSeq" would also has_part "FISSEQ"

## Attribution

https://orcid.org/0000-0003-4389-9821

**Comment by jychien** [comment]
Still unclear as to what the parent term should be. Will update the ticket in the near future.

**Comment by jychien** [comment]
## Preferred term label

ExSeq
targeted ExSeq
untargeted ExSeq

## Synonyms

**ExSeq**: expansion sequencing

## Textual definition

**ExSeq**: A spatial transcriptomics assay that involves physically expanding specimens with polymer- and hydrogel-based systems followed by in situ sequencing.
**targeted ExSeq**: A spatial transcriptomics assay that involves physically expanding specimens with polymer- and hydrogel-based systems followed by targeted padlock probe hybridization, amplification, and in situ sequencing of padlock barcode.
**untargeted ExSeq**: A spatial transcriptomics assay that involves physically expanding specimens with polymer- and hydrogel-based systems followed by reverse transcription, amplification, and in situ sequencing of untargeted RNA using FISSEQ.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7900882/ (PMID: 33509999)

## Suggested parent term

**ExSeq**: ISS http://www.ebi.ac.uk/efo/EFO_0008989.
**targeted ExSeq**: ExSeq
**untargeted ExSeq**: ExSeq

## Attribution

https://orcid.org/0000-0003-4389-9821

Additional suggested modifications:
- For [ISS](http://www.ebi.ac.uk/efo/EFO_0008989): To be consistent with '[in-situ hybridization assay](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001686)', the term name should be 'in-situ sequencing' and 'ISS' would then be a synonym. ISS has synonym 'in situ sequencing', but for some reason I am unable to find 'ISS' when searching for 'in situ sequencing'.
- Have [FISSEQ](http://www.ebi.ac.uk/efo/EFO_0008990) be a child of ISS. This would mirror the layout for 'in-situ hybridization assay'. However, it is not entirely clear if all FISSEQ assays involve a padlock probe, but rolling-circle amplification is applicable (https://www.nature.com/articles/nprot.2014.191)

**Comment by bvarner-ebi** [comment]
Hi, @jychien, thank for the new term requests.

Did you use other dbxrefs for the defintiions? I did not see "with polymer- and hydrogel-based systems" mentioned in the link, but maybe you were able to infer it?

**Comment by jychien** [comment]
Oh, interesting, it looks like the when the article is accessed from: https://www.science.org/doi/10.1126/science.aax2656, there is a paragraph titled "Identifying transcript location in cells" at the beginning. All hyphens do seem a little excessive, feel free to modify to make the wording flow a little better.

**Comment by bvarner-ebi** [comment]
Thanks, @jychien!
I will add that dbxref for this summary to the 'ExSeq' definition term.
I think the hyphens in this case make sense as "polymer-based" and "hydrogel-based" are compound modifiers.

**Comment by bvarner-ebi** [comment]
Hi @jychien, regarding [your comment ""ExSeq" would also has_part "FISSEQ""](https://github.com/EBISPOT/efo/issues/1666#issue-1299262183)...

I only added this to 'untargeted ExSeq', as it is noted in the text definition for that term only. Can you confirm is this is correct or if the other ExSeq terms should be revised?

**Comment by jychien** [comment]
Yes, only "untargeted ExSeq" would have has_part "FISSEQ".

**Comment by bvarner-ebi** [comment]
Hi, @jychien, I'm revisiting these terms since Human Cell Atlas has [a question related to spatial transcriptomics](https://github.com/HumanCellAtlas/ontology/issues/118).

For these three ExSeq terms, do you think they should also be classified under [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994)?

More specifically, do you think they should be classified under [EFO:0030005 'spatial transcriptomics by high-throughput sequencing](http://www.ebi.ac.uk/efo/EFO_0030005)'.

I will appreciate hearing your thoughts.

**Comment by jychien** [comment]
Hello @bvarner-ebi! I had initially thought of EFO:0030005 or EFO:0008994 as a parent term. After re-reading the article, I landed on ISS as a parent term because the unique features of ExSeq is the expansion gel and the fact that the sequencing is done in situ. In general, though, ISS is a type of spatial transcriptomics.

As for 'spatial transcriptomics' vs 'spatial transcriptomics by high-throughput sequencing', it really depends on how "high-throughput sequencing" is defined. If that is thought to be an assay that uses a sequencer like Illumina, then ExSeq is not high throughput. Or, if high-throughput is anything with >~200 genes being profiled, then ExSeq would be high-throughput.

**Comment by bvarner-ebi** [comment]
Thank you, @jychien.

@dosumis, @zoependlington, could I get your advice, please, or if you can point me to someone else with expertise...

I'm considering putting [EFO:0008989 'in situ sequencing'](http://www.ebi.ac.uk/efo/EFO_0008989) as a subclass of [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994). Does that seem reasonable?

[To also help HCA](https://github.com/HumanCellAtlas/ontology/issues/118), I'm considering to make [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994) either a subclass of (not sure about that) or a part of [OBI:0000711 'library preparation'](http://purl.obolibrary.org/obo/OBI_0000711).
Because I have some reservations about this, I would appreciate some additional input.

**Comment by dosumis** [comment]
> I'm considering putting [EFO:0008989 'in situ sequencing'](http://www.ebi.ac.uk/efo/EFO_0008989) as a subclass of [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994). Does that seem reasonable?

It does.

> https://github.com/HumanCellAtlas/ontology/issues/118, I'm considering to make [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994) either a subclass of (not sure about that) or a part of [OBI:0000711 'library preparation'](http://purl.obolibrary.org/obo/OBI_0000711).

That's a bit trickier.   It seems like we've been stuck on this general issue for a long time.  Library prep feels like a very odd general class here - required for many transctiptomics assays, but perhaps not all?  Does it apply to multiplexed FISH (e.g. MerFish?)

  It might be best to discuss with HCA and see if it makes more sense for them to adjust their schema.

**Comment by bvarner-ebi** [comment]
Thank you for the feedback, @dosumis. 

There is reference to a "MERFISH library" [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5047202/), but I do not have the background knowledge to know how widely applicable this is.
Upon further reading, it does seem that, if anything, [OBI:0000711 'library preparation'](http://purl.obolibrary.org/obo/OBI_0000711) would be part of [EFO:0008994 'spatial transcriptomics'](http://www.ebi.ac.uk/efo/EFO_0008994) (I initially had it the other way around).

HCA is advocating for 'spatial transcriptomics' to be a subclass of 'library preparation', but I don't think that is logically correct, and I agree it is a bit strange for it to be a general class term.

**Comment by bvarner-ebi** [comment]
@jychien, FYI, 'in situ sequencing' has been made a subclass of 'spatial transcriptomics'. See the merged PR link directly above this comment.
