### ISSUE TITLE
New term request for Blair PMID 35760791

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1668]
For new term requests, please provide the following information:

## Preferred term label

cryptic phenotype measurement

## Textual definition

Quantification of disease-related phenotypic variability using qualitative symptom data.

## Suggested parent term

measurement

**Comment by zoependlington** [comment]
Added as EFO_0021436, which will be available after the July (18th) EFO release.

**Comment by earlEBI** [comment]
@zoependlington thank you Zoe - but I see that EFO ID has already been used by us for cholesteryl ester 17:0 measurement? https://github.com/EBISPOT/efo/issues/1638

**Comment by zoependlington** [comment]
Apologies for that, I double checked but strangely this terms didn't appear in Protege - turned out to be a bigger problem that I've now fixed. The new term ID is EFO_0021487.

**Comment by earlEBI** [comment]
Thank you!
