### ISSUE TITLE
efo incompatible with uberon

### ISSUE THREAD

**Issue by tgbugs** [EBISPOT/efo#167]
Importing the latest versions of efo and uberon together leads to many reasoning errors, they mostly seem to be related to misuse of the 'part of' relationship violating disjointness axioms between body systems. Not sure if this is due to an old import of uberon terms or due to drift from upstream modelling.

**Comment by simonjupp** [comment]
Thanks. We have a stale uberon import and are working on a fresh import that will resolve these issues.

**Comment by S2Ola** [comment]
@paolaroncaglia I can confirm that CL:0000446 'parathyroid' has been fixed with the imported UBERON update terms imports pipeline.
Thanks
