### ISSUE TITLE
New term request for Thomeas-McEwing PMID: 35383711

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1670]
For new term requests, please provide the following information:

## Preferred term label

treprostinil dose measurement

## Synonyms

na

## Textual definition

quantification of some aspect of treprostinil dosage

## Suggested parent term

drug use measurement (http://www.ebi.ac.uk/efo/EFO_0007010)

## Attribution

na

**Comment by zoependlington** [comment]
Term added as EFO_0021489, which will be available after the July release.
