### ISSUE TITLE
Request for new EFO terms for OpenTargets project

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#169]
From an email from Thawfeek Mohamed Varusai:

"Hi,

I'm a curator in Reactome and am collaborating with OpenTargets on a 
project. We are trying to map some diseases to EFO IDs and find that 
there are a few missing terms in the ontology (listed below). Could you 
please add these terms to the ontology and forward me the IDs once they 
are there.

1. female reproductive endometrioid cancer

2. precursor lymphoblastic lymphoma/leukemia

3. myeloid neoplasm

Many thanks,

Thawfeek

Scientific Database Curator

Reactome, EMBL-EBI"

**Comment by paolaroncaglia** [comment]
At a very quick glance,
'female reproductive endometrioid cancer' is in MONDO (http://purl.obolibrary.org/obo/MONDO_0002480);
'precursor lymphoblastic lymphoma/leukemia' is also in MONDO (http://purl.obolibrary.org/obo/MONDO_0003538);
'myeloid neoplasm' is already in EFO (http://www.ebi.ac.uk/efo/EFO_0002427).

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW1** female reproductive endometrioid cancer
     - Subclass of cancer (EFO:0000311)
     - has_disease_location some ('female reproductive system' or (part_of some 'female reproductive system'))
     - **Definition:** A benign, borderline, or malignant epithelial tumor of the female reproductive system characterized by the presence of glands and/or cysts lined by neoplastic cells that resemble endometrial cells.
     - **Synonyms:** endometrioid tumor (morphologic abnormality)||endometrioid neoplasm
     - **X-refs:** MONDO:0002480||DOID:3001||UMLS:C0474809

- [ ] **EFO:NEW2** precursor lymphoblastic lymphoma/leukemia
     - Subclass of leukemia (EFO:0000565)
     -  **Definition:** A neoplasm of immature malignant lymphocytes (lymphoblasts) committed to the B-cell or T-cell lineage. Neoplasms involving the bone marrow and the peripheral blood are called precursor lymphoblastic leukemias or acute lymphoblastic leukemias. Neoplasms involving primarily lymph nodes or extranodal sites are called lymphoblastic lymphomas.
     - **Synonyms:** Precursor Lymphoblastic Leukemia/Lymphoma || Precursor Lymphoblastic Lymphoma/Leukemia || Precursor Lymphoid Neoplasm
     - **X-refs:** MONDO:0003538 || DOID:5600 || UMLS:C1335469 || NCIT:C7055 || MESH:D054198

- [ ] **EFO:EDIT** acute lymphoblastic leukemia (EFO:0000220)
     - Subclass of precursor lymphoblastic lymphoma/leukemia (EFO:NEW2)
     - Subclass of acute leukemia (EFO:1000068)

- [ ] **EFO:EDIT** precursor T-cell lymphoblastic leukemia-lymphoma (EFO:1001830)
     - Subclass of precursor lymphoblastic lymphoma/leukemia (EFO:NEW2)

**Comment by vthawfeek** [comment]
Thanks!

**Comment by vthawfeek** [comment]
Are the new terms available now? Can I please have the EFO IDs.

Thanks!

**Comment by zoependlington** [comment]
@vthawfeek 

Here are the IDs for the new terms:
EFO:0009118 || female reproductive endometrioid cancer
EFO:0009119 || precursor lymphoblastic lymphoma/leukemia

They will be released with the June EFO release (18th June).

**Comment by vthawfeek** [comment]
Thanks a lot!
