### ISSUE TITLE
New age of onset terms request

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1693]
- [x] This issue depends on https://github.com/obophenotype/bio-attribute-ontology/issues/111
- [x] This issues depends on https://github.com/obophenotype/bio-attribute-ontology/issues/118

For new term requests, please provide the following information:

## Preferred term label

1. age of onset of cancer
2. age of onset of glaucoma
3. age of onset of stroke

## Synonyms

na

## Textual definition

1. The age at which cancer manifestations first appear.
2. The age at which glaucoma manifestations first appear.
3. The age at which stroke manifestations first appear.

## Suggested parent term

Onset (http://purl.obolibrary.org/obo/HP_0003674)

## Attribution

na

**Comment by rays22** [comment]
This issue depends on https://github.com/obophenotype/bio-attribute-ontology/issues/111

**Comment by zoependlington** [comment]
@rays22 Can this be prioritised so these terms are in EFO for the August (15th) release, please? It's blocking a big submission on the GWAS side. Ping me if there are any issues importing them into EFO 😄

**Comment by rays22** [comment]
> @rays22 Can this be prioritised so these terms are in EFO for the August (15th) release, please? It's blocking a big submission on the GWAS side. Ping me if there are any issues importing them into EFO 😄

This issue will be fixed in https://github.com/EBISPOT/efo/pull/1697, but that PR, in turn, depends on a new OBA release, which I will do ASAP.
