### ISSUE TITLE
erythrocyte measurement

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#170]
There is a typo in the definition ('quantity')

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT** erythrocyte measurement (EFO_0005047)
     - Edit typo in description (quanity -> quantity)

There are also a few others with the same typo:

- [ ] **EFO:EDIT** hemoglobin measurement (EFO_0004509)
     - Edit typo in description (quanity -> quantity)

- [ ] **EFO:EDIT** hemoglobin A1 measurement (EFO_0007629)
     - Edit typo in description (quanity -> quantity)

- [ ] **EFO:EDIT** hemoglobin A2 measurement (EFO_0005845)
     - Edit typo in description (quanity -> quantity)
