### ISSUE TITLE
New term request for Krupenko PMID 35460232

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1702]
For new term requests, please provide the following information:

## Preferred term label

serine:glycine ratio

## Synonyms

NA

## Textual definition

Quantification of the ratio of serine to glycine in plasma

## Suggested parent term

serine measurement http://www.ebi.ac.uk/efo/EFO_0009774

## Attribution

NA

**Comment by zoependlington** [comment]
Added as EFO_0021777, which will be available after the August 15th release.
