### ISSUE TITLE
New term requests (cerebral and subcortical volume measurements) / PMID 35842455, Tissink et. al 

### ISSUE THREAD

**Issue by ar-ibrahim** [EBISPOT/efo#1705]
Total cerebral and subcortical volume measurements are brain volume measurements.

Total subcortical volume includes the volumes of the thalamus, caudate, putamen, pallidum, hippocampus, amygdala, accumbens, ventral diencephalon, and substancia nigra _(main text of PMID 35842455 pg 9)._

https://docs.google.com/spreadsheets/d/1j_AmOcRLvOJCHNRVnnYVgGK4gR1MBtAr/edit#gid=1609159643

**Comment by zoependlington** [comment]
I've added these terms as the following, which will be available after the August (15th) release:
cerebral volume measurement || EFO_0021789
subcortical volume measurement || EFO_0021790
