### ISSUE TITLE
New term requests for PMID 34837083

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1706]
## Requested terms labels

1. ascending aortic diameter
2. descending aortic diameter
3. aortic diameter

## Synonyms

1. ascending aorta diameter
2. descending aorta diameter
3. aorta diameter

## Textual definition

1. Measurement of the diameter of the ascending aorta.
2. Measurement of the diameter of the descending aorta.
3. Measurement of the diameter of some part of the aorta.

## Suggested parent term

1. ascending aortic diameter < _child of_ aortic diameter [new]
2. descending aortic diameter < _child of_ aortic diameter [new]
3. aortic diameter < _child of_ aortic measurement [http://www.ebi.ac.uk/efo/EFO_0020865]

**Comment by zoependlington** [comment]
Terms have been added as the following and will be available after the EFO August (15th) release:
ascending aortic diameter || EFO_0021787
descending aortic diameter || EFO_0021788
aortic diameter || EFO_0021786

**Comment by eks-ebi** [comment]
thanks!
