### ISSUE TITLE
New term request for Kingston PMID:35647563

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1710]
For new term requests, please provide the following information:

## Preferred term label

CFTR mutation carrier status

## Synonyms

na

## Textual definition

Quantification of the presence or absence of the CFTR mutation in an individual

## Suggested parent term

carrier status http://www.ebi.ac.uk/efo/EFO_0007658

## Attribution

na

**Comment by zoependlington** [comment]
Added as EFO_0021794, which will be available after the September release.
