### ISSUE TITLE
New term request for Nieves-Colon PMID:35588731

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1711]
For new term requests, please provide the following information:

## Preferred term label

preeclampsia severity measurement

## Synonyms

NA

## Textual definition

Quantification of the severity of the symptoms of preeclampsia

## Suggested parent term

measurement http://www.ebi.ac.uk/efo/EFO_0001444

## Attribution

na

**Comment by zoependlington** [comment]
Added as EFO_0021792, which will be available after the 15th September release.
