### ISSUE TITLE
NTRs: BD Rhapsody WTA & targeted

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1712]
## Preferred term label

BD Rhapsody Whole Transcriptome Analysis

## Synonyms

BD Rhapsody WTA

## Textual definition

BD Biosciences-based technology that sequences mRNA from the 3' end in an unbiased manner.
citation: https://www.bdbiosciences.com/content/dam/bdb/marketing-documents/BD-Rhapsody-WTA-Amplification-Kit.pdf

## Suggested parent term

EFO:0010183 (single cell library construction), EFO:0008913 (single-cell RNA sequencing)

-----
## Preferred term label

BD Rhapsody Targeted mRNA

## Textual definition

BD Biosciences-based technology that utilizes multiplex PCR to sequence mRNA from the 3' end of specific genes from a predetermined panel.
citation: https://www.bdbiosciences.com/content/dam/bdb/products/reagents/single-cell-multiomics-reagents/targeted-mrna-kits/BD-Rhapsody-Immune-Response-Human-Panel-Brochure.pdf

## Suggested parent term

EFO:0010183 (single cell library construction), EFO:0008913 (single-cell RNA sequencing)

-----
## Attribution

ORCID id: 0000-0002-1196-4871

**Comment by bvarner-ebi** [comment]
@zoependlington, do you have thoughts about adding these terms under EFO:0010183 'single cell library construction' versus EFO:0008913 'single-cell RNA sequencing'?

My inclination is to add them under EFO:0008913 'single-cell RNA sequencing', which is it itself a "grandchild" of EFO:0010183 'single cell library construction'.

**Comment by bvarner-ebi** [comment]
@jahilton, thank you for the new term requests.
Regarding your request for 'BD Rhapsody Targeted mRNA', I do not see that term used in the reference provided. 
I see 'BD RhapsodyTM Immune Response Panel (Human)' described at that link. Do you have a citation for your preferred term?

**Comment by jahilton** [comment]
Yes, sorry. I see now that was to one of the targeted mRNA kits.
These pages refer to the general assay
https://www.bdbiosciences.com/en-us/products/reagents/single-cell-multiomics/targeted-kits
https://scomix.bd.com/hc/en-us/articles/360023293851-Targeted-mRNA-Protocols

**Comment by zoependlington** [comment]
@bvarner-ebi I'd also be inclined to add this under EFO:0008913 'single-cell RNA sequencing', although I'm no sequencing expert.

**Comment by jahilton** [comment]
The BD kits should be treated similarly to 10x kits that accomplish similar things, so I tried to mirror those terms.
Example: EFO:0009899 (10x 3' v2) is considered a  'single cell library construction' through subClass relationships.
Though I'm not sure why the 10x terms are not related to any RNA sequencing term.

**Comment by bvarner-ebi** [comment]
@jahilton, thanks for the feedback.

Currently these new terms are subclasses of 'single-cell RNA sequencing' as requested.

`'single-cell RNA sequencing'` is a subclass of `'single-cell sequencing'` 
and 
`'single-cell sequencing' 'has part' some 'single cell library construction'`.

Does that seem reasonable?

**Comment by jahilton** [comment]
Yes, that'll work. Thanks!

**Comment by bvarner-ebi** [comment]
Thank you, @jahilton.

The terms have been added to EFO and will be part of the next release.

EFO:0700003 'BD Rhapsody Whole Transcriptome Analysis'
EFO:0700004 'BD Rhapsody Targeted mRNA'
