### ISSUE TITLE
NTR: Abseq

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1713]
## Preferred term label

Abseq

## Textual definition

The use of DNA-tagged antibodies to quantify proteins in single cells.
citation: https://pubmed.ncbi.nlm.nih.gov/28290550/

## Suggested parent term

EFO:0001458 (protein assay), EFO:0010183 (single cell library construction)

## Attribution

ORCID id: 0000-0002-1196-4871

**Comment by bvarner-ebi** [comment]
Hi @jahilton,
Thanks for the new term request.

Would this slight edit to the definition be appropriate:
"A method that uses DNA-tagged antibodies to quantify proteins in single cells."

'protein assay' seems reasonable as a superclass. 
I'm not as confident with 'single cell library construction' as a superclass. Is this method always a single cell library construction or is it also employed to only investigate particular proteins of interest?

**Comment by jahilton** [comment]
Hi @bvarner-ebi !
Yes, this method is specifically designed to quantitate proteins _in single cells_ at ultrahigh throughput.

**Comment by bvarner-ebi** [comment]
Thank you, @jahilton.

The terms have been added to EFO and will be part of the next release.

EFO:0700005 Abseq
