### ISSUE TITLE
New term request for Huang PMID 35613103

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1715]
For new term requests, please provide the following information:

## Preferred term label

behavioural ideal cardiovascular health

## Textual definition

The characteristics of a person's cardiovascular health based on a number of factors including smoking status, physical activity and BMI

## Suggested parent term

health trait

##info
requesting because there are already terms for clinical and 'clinical and behavioural', and this paper contains GWAS on just behavioural as well.

**Comment by zoependlington** [comment]
Term added as EFO_0021791, which will be available after our 15th September release.
