### ISSUE TITLE
New term request for Ramos PMID: 35490390

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1718]
For new term requests, please provide the following information:

## Preferred term label

age of onset of cognitive impairment

## Synonyms

NA

## Textual definition

The age at which cognitive impairment manifestations first appear.

## Suggested parent term

Onset http://purl.obolibrary.org/obo/HP_0003674

## Attribution

NA

**Comment by zoependlington** [comment]
@rays22 Is this one that should be in OBA or should I add this as an EFO term?

**Comment by rays22** [comment]
> @rays22 Is this one that should be in OBA or should I add this as an EFO term?

It looks like a genuine trait that fits OBA.
It can go into OBA using the [disease age of onse](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/disease_onset.yaml) pattern with the class [MONDO:0002039 cognitive disorder](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002039)

**Comment by zoependlington** [comment]
Thanks @rays22, I'll remove myself from the assignment.
