### ISSUE TITLE
New term request for Bencheck PMID 34315907

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1719]
For new term requests, please provide the following information:

## Preferred term label

oral motor function measurement

## Textual definition

Quantification of oral motor skills, generally through the administration of standardised tests such as syllable repetition on single, double and multi-syllable sequences

## Suggested parent term

language measurement

## from text: 
Oral Motor Skills Test
The Robbins and Klee Oral Speech Motor Control Protocol 1 (DDK-OSMCP) assessed oral motor skills in children 4 to 6 years. Diadochokinetic rates on single, double and multi-syllables were timed and scored. The Fletcher Time-by-Count Test of Diadochokinetic Syllable Rate 2 (DDK-FL) was administered to children 7 years or older. This test also assesses rates of syllable repetition on single, double and multi-syllable sequences. Z-scores were generated, and the scores for single and multi-syllables were combined for analysis. A shorter time for syllable sequence repetition indicates better oral motor skills. Because the DDK-OSMCP is scored in the opposite direction, these values were negated prior to merging with the DDK-FL; for this merged score, lower scores imply worse performance. We shall refer to this merged variable as DDK.

**Comment by zoependlington** [comment]
Added as EFO_0021793, which will be available after the 15th September release.
