### ISSUE TITLE
New term request for Chen PMID:35879288

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1726]
For new term requests, please provide the following information:

## Preferred term label

age of onset of depression

## Synonyms

NA

## Textual definition

The age at which depression manifestations first appear.

## Suggested parent term

Onset http://purl.obolibrary.org/obo/HP_0003674

## Attribution

NA

**Comment by zoependlington** [comment]
@rays22 Is this a candidate for OBA? If not I will add as EFO term.

**Comment by rays22** [comment]
> @rays22 Is this a candidate for OBA? If not I will add as EFO term.

It can go into OBA using the [disease age of onse](https://github.com/obophenotype/bio-attribute-ontology/blob/master/src/patterns/dosdp-patterns/disease_onset.yaml) pattern with the class [MONDO:0002050 depressive disorder](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002050).

**Comment by zoependlington** [comment]
Thanks @rays22, I'll remove myself from the assignment.
