### ISSUE TITLE
New term request for Klumpers PMID: 35743677

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1727]
For new term requests, please provide the following information:

## Preferred term label

Hypomagnesemia

## Synonyms

NA

## Textual definition

Lower than normal levels of magnesium in the circulating blood. [ NCI ]

## Suggested parent term

Abnormality of metabolism/homeostasis (http://purl.obolibrary.org/obo/HP_0001939)

## Attribution

NA

**Comment by zoependlington** [comment]
Imported http://purl.obolibrary.org/obo/HP_0002917 (Hypomagnesemia) into EFO.
