### ISSUE TITLE
ERROR in LPA curation

### ISSUE THREAD

**Issue by fauman** [EBISPOT/efo#1729]
Hi curators,
I notice that some GWAS of Lipoprotein(a) levels (gene is LPA) are tagged with 
https://www.ebi.ac.uk/gwas/efotraits/EFO_0004614
That is: apolipoprotein A 1 measurement
apolipoprotein A 1 is encoded by APOA1, not LPA.

In general, hits near 6:160539327 should be tagged as https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0006925
lipoprotein A measurement

**Comment by zoependlington** [comment]
@ljwh2 is this an issue on the GWAS side or the EFO side?

**Comment by ljwh2** [comment]
@zoependlington It's on the GWAS side, thanks, we will follow up

**Comment by ljwh2** [comment]
@zoependlington Actually it might be partly on the EFO side. The definition is: 

> Is a quantification of serum lipoprotein A. Apolipoprotein A-I, encoded in humans by the APOA1 gene and is the major protein component of high density lipoprotein (HDL) in plasma

I think the first sentence is wrong and might account for some of the incorrect annotations in the GWAS Catalog

**Comment by zoependlington** [comment]
Thanks @ljwh2, I'll take a look at this ASAP.
