### ISSUE TITLE
NTR: GEXSCOPE

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#1734]
## Preferred term label

GEXSCOPE

## Textual definition

A microwell-based technology developed by Singleron to prepare mRNA from single cells or single nuclei and generate an NGS library for high-throughput sequencing.
https://singleron.bio/product/detail-18.html
https://singleron.bio/product/detail-3.html
https://singleron.bio/product/detail-4.html

## Suggested parent term

EFO:0010183 (single cell library construction)

## Attribution

ORCID id: 0000-0002-1196-4871

**Comment by bvarner-ebi** [comment]
Hi @jahilton, thank you for the new term request.

Given your text definition and the links provided, should the label be SCOPE-chip? After a cursory review, it seems like your text definition refers to SCOPE-chip, which is a component of a "GEXSCOPE Single Cell RNA Library Kit". 
"GEXSCOPE" seems to be a broader suite of products.

I will appreciate your advice.

**Comment by jahilton** [comment]
I would think that "GEXSCOPE Single Cell RNA Library Kit" is analogous to "10x 3' v3" (EFO:0009922) in that each represents the process to construct the library prior to high-throughput sequencing.
I see "SCOPE-chip" is analogous to the 10x "Next GEM chip" in that each is a part of the process that facilitates the library construction.

Do you have suggestions for what could make the definition more applicable given that context?

**Comment by bvarner-ebi** [comment]
>Do you have suggestions for what could make the definition more applicable given that context?

Is your intention with this new term to represent the **library preparation** step of SCOPE-chip? Please see related comment [here](https://github.com/HumanCellAtlas/ontology/issues/118#issuecomment-1246669903).
If not, could you clarify what you mean by "technology" in your text definition?

**Comment by jahilton** [comment]
Thank you for pointing me to the comment.
My intention is to create a term analogous to 10x 3' v3. I interpret that term to represent a process with biomaterial input and an output of nucleic acids ready to be input to a sequencer.
For GEXSCOPE, it is what is included in the "GEXSCOPE kit" bracket (from https://singleron.bio/product/detail-3.html)
<img width="942" alt="Screen Shot 2022-09-15 at 3 09 14 PM" src="https://user-images.githubusercontent.com/15098808/190517430-96c8e83f-8818-4daf-9348-e23d8807c1c2.png">
The "technology", in this case, would include the SCOPE-chip but it is not limited to just that. I modeled that phrasing off of the 10x terms.

Am I misinterpreting the 10x terms?

**Comment by bvarner-ebi** [comment]
Thank you for the details, @jahilton.

My interpretation of [10x 3' v3](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009922&lang=en&viewMode=All&siblings=false) is that it encompasses the sequencing step. 
Text def: 10X 3' v3 is the third version of the 10x sequencing technology that sequences from the 3' end of nucleic acid molecules.
"10x 3' v3 sequencing" is listed as a related synonym to that term.

If your new term is meant to represent all of the following, then "GEXSCOPE" as a preferred label seems reasonable:
[GEXSCOPE® Single Cell RNA Library Kit](https://singleron.bio/product/detail-3.html)
[GEXSCOPE® Single Nucleus RNA Library Kit](https://singleron.bio/product/detail-4.html)
NEW! - GEXSCOPE® Microbial Single Cell RNA Library Kit HD (Yeast)
[GEXSCOPE® Single Cell V(D)J Kit](https://singleron.bio/product/detail-5.html)

If your new term is meant to be more specific, I recommend refining the preferred label and providing synonyms.

**Comment by jahilton** [comment]
The sequencing component of the 10x terms is not supported by the discussion & actions in #1091 nor as descendants of [library preparation](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0000711) which "...results in the creation of a library" as opposed to the creation of sequence reads.

Thank you for pointing out the variety of kits offered for GEXSCOPE. For completeness, I would be happy to submit new terms in order to construct a new branch, something like...
- GEXSCOPE technology
  - GEXSCOPE V(D)J Kit
  - GEXSCOPE transcription profiling
    - GEXSCOPE Single Cell RNA Library Kit
    - GEXSCOPE Single Nucleus RNA Library Kit

But would like to get on the same page first as to where in EFO to capture these terms.

**Comment by bvarner-ebi** [comment]
@jahilton, thank you for referring to #1091.

With that background, does it makes sense to you to use the label 'GEXSCOPE technology' with the text definition you submitted in this ticket?
You could then submit other new term requests to construct the hierarchy you illustrated above.

**Comment by jahilton** [comment]
Yes, that sounds like a great plan!

**Comment by bvarner-ebi** [comment]
@jahilton,

Thanks for your contribution. 
Your new term has been added to EFO and will be available in the next release.
EFO:0700011 'GEXSCOPE technology'

Details can be viewed in the PR: #1763
