### ISSUE TITLE
Potential duplicates

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#1735]
From Paula Magarinos:

EFO:0006926 and MONDO:0012197
MONDO:0018338 and Orphanet:397596
EFO:0007483 and EFO:1000052
MONDO:0019781 and EFO:0000272
MONDO:0015909 and HP:0001915
MONDO:0001627 and HP:0000726
EFO:1000391 and HP:0100582
EFO:1001176 and HP:0000407
HP:0011950 and MONDO:0002465
HP:0011974 and MONDO:0044903
Orphanet:166096 and MONDO:0010191
EFO:0004272 and MONDO:0002280
HP:0007716 and EFO:1000616

EFO:0001075 (ovarian carcinoma) and MONDO:0008170 (ovarian cancer): I’m not sure about this one, but ovarian cancer appears as synonym for EFO:0001075

Additionally, I’ve noticed that the EFO ID MONDO:0100245 is obsolete and it says it has been replaced by MONDO:0100244 but this ID is also obsolete.

**Comment by HelenaCornu** [comment]
Hello! I have an additional duplication, [as reported by a Open Targets Platform user](https://community.opentargets.org/t/why-are-there-near-identical-disease-terms-in-the-platform-adhd-and-how-to-collate-the-evidence/746):

EFO_0003888 and MONDO_0007743 (ADHD)

**Comment by zoependlington** [comment]
Planned work/explanation as to why they are or are not duplicates:

EFO:0006926 and MONDO:0012197 - phenotype vs disease, therefore not duplicates but something to consider in the future.
MONDO:0018338 and Orphanet:397596 - obsolete Orphanet term and replace with Mondo
EFO:0007483 and EFO:1000052 - merge EFO:0007483 into EFO:1000052 and obsolete EFO:0007483
MONDO:0019781 and EFO:0000272 - Remove current mapping for EFO term and replace with this one.
MONDO:0015909 and HP:0001915 - phenotype vs disease, therefore not duplicates but something to consider in the future.
MONDO:0001627 and HP:0000726 - phenotype vs disease, therefore not duplicates but something to consider in the future.
EFO:1000391 and HP:0100582 - phenotype vs disease, therefore not duplicates but something to consider in the future.
EFO:1001176 and HP:0000407 - phenotype vs disease, therefore not duplicates but something to consider in the future.
HP:0011950 and MONDO:0002465 - phenotype vs disease, therefore not duplicates but something to consider in the future.
HP:0011974 and MONDO:0044903 - phenotype vs disease, therefore not duplicates but something to consider in the future.
Orphanet:166096 and MONDO:0010191 - obsolete Orphanet term and replace with Mondo
EFO:0004272 and MONDO:0002280 - phenotype vs disease, therefore not duplicates but something to consider in the future.
HP:0007716 and EFO:1000616 - phenotype vs disease, therefore not duplicates but something to consider in the future.

EFO:0001075 (ovarian carcinoma) and MONDO:0008170 (ovarian cancer) - remove incorrect synonym from EFO term, they should remain as separate terms.

Additionally, I’ve noticed that the EFO ID MONDO:0100245 is obsolete and it says it has been replaced by MONDO:0100244 but this ID is also obsolete. - This comes directly from Mondo, so is out of our control but I will look into this further and import the replaced by term where appropriate.

EFO_0003888 and MONDO_0007743 (ADHD) - mapping should be added to merge these terms

**Comment by zoependlington** [comment]
These duplicates should now be solved for the upcoming September (15th) release.
