### ISSUE TITLE
New term request for Eising et al (35998220)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#1742]
For new term requests, please provide the following information:

## Preferred term label

phoneme awareness

## Textual definition

The ability to identify and manipulate individual sounds of spoken words.

(see PMID 35998220)

## Suggested parent term

speech perception (http://www.ebi.ac.uk/efo/EFO_0004336)

## Attribution

**Comment by zoependlington** [comment]
Added as EFO_0021812, which will be available after the September (15th) release.
