### ISSUE TITLE
New term request for Konig PMID:35888728 (WC_20220902)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1743]
10 terms:
https://docs.google.com/spreadsheets/d/19HgRQXqKxfP59nrtkkDSC2iwXaUT_D2zXNPIKXrn1e4/edit#gid=1909577919

**Comment by zoependlington** [comment]
The following terms have been added and will be available after the September (15th) release:

ID | Label
-- | --
EFO_0021802 | spermidine measurement
EFO_0021803 | decenoylcarnitine measurement
EFO_0021804 | dodecanoylcarnitine measurement
EFO_0021805 | hydroxyvalerylcarnitine measurement
EFO_0021806 | hexadecenoylcarnitine measurement
EFO_0021810 | putrescine measurement
EFO_0021807 | hydroxyhexadecanoylcarnitine measurement
EFO_0021811 | lysophosphatidylcholine 26:1 measurement
EFO_0021808 | dodecenoylcarnitine measurement
EFO_0021809 | tetradecenoylcarnitine measurement
