### ISSUE TITLE
New term request for Liu PMID: 35888748 (WC_20220906)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1748]
13 new metabolite terms:
https://docs.google.com/spreadsheets/d/1-EX9EdHCMXrq_zck1v0tO9kCXLkDgEXiA7EhzJyMK0w/edit#gid=1909577919

**Comment by zoependlington** [comment]
Terms have been added (IDs are in the spreadsheet) and will be available after the September release (15th).
