### ISSUE TITLE
New term request for Sonehara PMID: 35918310

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1758]
For new term requests, please provide the following information:

## Preferred term label

Intracranial germ cell tumor

## Synonyms
NA

## Textual definition

A germ cell tumor that arises within the cranium and occurs during adulthood. [ NCI ]

## Suggested parent term

central nervous system germ cell tumor http://purl.obolibrary.org/obo/MONDO_0003000 ?

## 
The term is available in NCIT Adult Intracranial Germ Cell Tumor http://purl.obolibrary.org/obo/NCIT_C114778

**Comment by ar-ibrahim** [comment]
Isn't the requested term **intracranial germ cell tumor** synonymous with **central nervous system germ cell tumor** _MONDO:0003000_ which already exists? Can we double check with Shawn or Bradley? @zoependlington

**Comment by zoependlington** [comment]
MONDO:0003000 is mapped as an exact term to NCIT:C5461 (Central Nervous System Germ Cell Tumor), which is an ancestor of the requested term in NCIT that we will x-ref the new term to. So I would say that they're different terms based on this and the more specific anatomical phrasing of "intercranial".

**Comment by ar-ibrahim** [comment]
Added as EFO:0800001. Available on October 17th release.
