### ISSUE TITLE
New term request for TruDrop

### ISSUE THREAD

**Issue by jychien** [EBISPOT/efo#1759]
## Preferred term label

TruDrop

## Synonyms

TruSeq-inDrop

## Textual definition

A droplet-based microfluidic library construction platform based on inDrop that incorporates dual-indexing to detect index hoping and standard Illumina sequencing primers for high-throughput sequencing.

https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-06843-0

## Suggested parent term

Parent terms should be comparable to what inDrop has as parents:

- "RNA assay" (EFO:0001457)
-  "single cell library construction" (EFO:0010183)

"TruDrop" has_part "inDrop" (EFO:0008780)

**Comment by bvarner-ebi** [comment]
Thanks for the new term request, @jychien.
Can you confirm "index hoping" should be "index-hopping" in the text definition?

Could you have a look at the conversation at https://github.com/HumanCellAtlas/ontology/issues/118 and advise if this new term really should be a subclass of 'RNA assay'?

**Comment by jychien** [comment]
@bvarner-ebi Oops! Yes, I meant "index-hopping". Thanks for catching that.

As for parent terms, I was mirroring where inDrop is currently in the ontology tree. Thank you for linking to the updated discussion. For our needs at [CELLxGENE](https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/3.0.0/schema.md#assay_ontology_term_id), the assay can be either a child of "assay by molecule" (EFO:0002772) or "single cell library construction" (EFO:0010183). So, we would be fine if you want to drop "RNA assay" as parent.

**Comment by bvarner-ebi** [comment]
Hi @jychien, your new term has been added to EFO and will appear in the next release.
You can refer to [the linked PR](https://github.com/EBISPOT/efo/pull/1760) to view the specific edits.

EFO:0700010 'TruDrop'
