### ISSUE TITLE
New term request for Lehtisalo PMID:35942816

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1765]
For new term requests, please provide the following information:

## Preferred term label

response to rosuvastatin

## Synonyms

NA

## Textual definition

Any process that results in a change in the state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a rosuvastatin stimulus. Rosuvastatin is a statin used as a cholesterol-lowering and anti-cardiovascular disease drug.

## Suggested parent term

response to statin (http://purl.obolibrary.org/obo/GO_0036273)

## Attribution

NA

**Comment by zoependlington** [comment]
Term added as EFO_0021896, which will be available after the October (17th) release.
