### ISSUE TITLE
New term request for Wang PMID: 36035146 (WC_20220929)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1766]
2 new terms: 
https://docs.google.com/spreadsheets/d/1A8iwwNE3juqlpLjN9tjc3z-wK2RP5AuzCHkaXeteSVQ/edit#gid=1909577919

the terms are available in HP

Widow's peak: http://purl.obolibrary.org/obo/HP_0000349
Accessory eyelid: http://purl.obolibrary.org/obo/HP_0430008

**Comment by zoependlington** [comment]
The two HP terms have been imported into EFO and will be available after the October (17th) release.
