### ISSUE TITLE
New term request for Yin PMID: 35347128 (WC_20221004)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1771]
new metabolite terms: 
https://docs.google.com/spreadsheets/d/1QxSTWRGrCLDLK_LnThtqNJ158MJm_ZoskKnqh11onrQ/edit#gid=1909577919

**Comment by zoependlington** [comment]
@ar-ibrahim We can take a look at this one together on Thursday so you can have a go with a bulk term request ticket.

**Comment by ar-ibrahim** [comment]
| Requested term  | Notes |
| ------------- | ------------- |
| 3-indoxyl sulfate measurement   | Existing (EFO:0010985) |
| N-acetylcarnosine  measurement  | Existing as X-12244--N-acetylcarnosine measurement (EFO:0021299)  |
| hypotaurine measurement  | Existing (EFO:0021833) |
| spermidine  measurement  | Existing (EFO:0021802) |
| betaine measurement  | Existing as plasma betaine measurement (EFO:0007787)  |
| 1-methylnicotinamide measurement  | Existing as EFO:0021829  |
| trimethylamine N-oxide measurement  | Existing EFO:0010541  |
| 1-(1-enyl-stearoyl)-2-linoleoyl-GPE (P-18:0/18:2) measurement  | Existing (EFO:0020014) |
| cholesterol  measurement  | Existing as total cholesterol measurement (EFO:0004574)  |
| hydrochlorothiazide measurement  | Existing as reponse to hydrochlorothiazide (EFO:000502)  |
| O-sulfo-L-tyrosine measurement  | Existing as X-11423--O-sulfo-L-tyrosine measurement (EFO:0021231)  |

Hi @Santhi1901. I created 1073 of 1084 metabolite terms you requested. Please let me know if you have any comments :)

**Comment by ar-ibrahim** [comment]
Ok I'll fix the spaces for those terms

response to hydrochlorothiazide (EFO:000502) is correct in EFO, it's just a typo in the ticket here

**Comment by ar-ibrahim** [comment]
@Santhi1901 

- Upon review, I also corrected the following:

    N-acetylglucosaminemeasurement
    indolepropionylglycinemeasurement
    isoleucylglycinemeasurement
    leucylglycinemeasurement

**Comment by ar-ibrahim** [comment]
Available on October 17th release.
