### ISSUE TITLE
46 duplicated labels in multiple terms

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1772]
Hi!

We have identified that there are cases where different IDs share the same label. One example is ([MONDO_0700092](https://platform.opentargets.org/disease/MONDO_0700092/associations)/[EFO_0010642](https://platform.opentargets.org/disease/EFO_0010642/associations)).

As you can see, the only differentiating part is that the EFO term is capitalised. Usually these terms come from different ontologies. Could you please take a look at the 46 diseases where this is happening?
[duplicated_terms.csv](https://github.com/EBISPOT/efo/files/9722931/duplicated_terms.csv)

Thanks!

**Comment by zoependlington** [comment]
Thanks @ireneisdoomed! I'll take a look at these ASAP!

**Comment by zoependlington** [comment]
From this list, the majority seem to be the issue of disease vs phenotype. This is an ongoing issue.

For the remaining terms (listed below) I will add mappings where appropriate to remove the duplications in EFO:

- aminoacylase 1 deficiency
- central precocious puberty
- pleuropulmonary blastoma
- polycystic kidney disease
- spinocerebellar ataxia type 42
- deltaretrovirus infections
- hyperpigmentation of the skin
- intellectual disability
- neurodevelopmental disorder

**Comment by ireneisdoomed** [comment]
Thank you so much!
