### ISSUE TITLE
New EFO term request Robot form for Thareja PMID 36168886

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1777]
Robot EFO request form for 196 new protein measurement EFO terms:
[Thareja EFO robot form.xlsx](https://github.com/EBISPOT/efo/files/9754773/Thareja.EFO.robot.form.xlsx)

**Comment by zoependlington** [comment]
The following already exist in EFO:
ID | label
-- | --
EFO_0021845 | gamma-enolase measurement
EFO_0021890 | interleukin-10 receptor subunit alpha measurement
EFO_0021844 | platelet-derived growth factor receptor alpha measurement
EFO_0021876 | leucine-rich repeat serine/threonine-protein kinase 2 measurement
EFO_0021891 | HemK methyltransferase family member 2 measurement
EFO_0004869 | chitinase-3-like protein 1 measurement
EFO_0021854 | apolipoprotein L1 measurement
EFO_0021883 | betacellulin measurement
EFO_0021852 | secreted and transmembrane protein 1 measurement
EFO_0021878 | R-spondin-3 measurement
EFO_0021869 | protein FAM3D measurement
EFO_0021858 | synaptosomal-associated protein 25 measurement
EFO_0021889 | lumican measurement
EFO_0021866 | CD177 antigen measurement
EFO_0021868 | SPARC-related modular calcium-binding protein 1 measurement
EFO_0021849 | protein Z-dependent protease inhibitor measurement
EFO_0021860 | leucine-rich repeat transmembrane protein FLRT2 measurement
EFO_0021861 | leucine-rich repeat transmembrane protein FLRT3 measurement
EFO_0021879 | immunoglobulin superfamily containing leucine-rich repeat protein 2 measurement
EFO_0021843 | vitronectin measurement
EFO_0021864 | semaphorin-5A measurement
EFO_0021893 | protein S100-A4 measurement
EFO_0021886 | E3 ubiquitin-protein ligase RNF43 measurement
EFO_0021877 | platelet receptor Gi24 measurement
EFO_0021851 | interleukin-36 alpha measurement
EFO_0021875 | ubiquitin-like protein ISG15 measurement
EFO_0004694 | coagulation Factor XI measurement
EFO_0020809 | tumor necrosis factor receptor superfamily member 1A measurement
EFO_0021848 | C-C motif chemokine 4-like measurement
EFO_0020758 | superoxide dismutase [Cu-Zn] measurement
EFO_0021894 | lipopolysaccharide-binding protein measurement
EFO_0004619 | coagulation factor VII measurement
EFO_0020203 | C-type lectin domain family 7 member A measurement
EFO_0020385 | fibroblast growth factor 8 isoform A measurement
EFO_0020649 | platelet-derived growth factor subunit A measurement
EFO_0021892 | adhesion G protein-coupled receptor E2 measurement
EFO_0021853 | galactoside 3(4)-L-fucosyltransferase measurement
EFO_0020666 | protein 4.1 measurement
EFO_0020111 | 15-hydroxyprostaglandin dehydrogenase [NAD(+)] measurement
EFO_0021856 | prolyl endopeptidase FAP measurement
EFO_0021882 | natural killer cell receptor 2B4 measurement
EFO_0021885 | semaphorin-6B measurement
EFO_0021871 | glypican-6 measurement
EFO_0021887 | glial cell line-derived neurotrophic factor measurement
EFO_0021874 | ankyrin-2 measurement
EFO_0021870 | cysteine-rich with EGF-like domain protein 1 measurement
EFO_0021873 | low-density lipoprotein receptor-related protein 1B measurement
EFO_0021859 | phosphoglucomutase-1 measurement
EFO_0021841 | mucin-1 measurement
EFO_0021857 | protein FAM3B measurement
EFO_0021850 | interferon alpha/beta receptor 1 measurement
EFO_0021865 | trefoil factor 1 measurement
EFO_0021872 | non-histone chromosomal protein HMG-14 measurement
EFO_0021846 | trefoil factor 2 measurement
EFO_0021863 | galectin-9 measurement
EFO_0021884 | transgelin-2 measurement
EFO_0021880 | quinone oxidoreductase-like protein 1 measurement
EFO_0021847 | pigment epithelium-derived factor measurement
EFO_0021895 | formimidoyltransferase-cyclodeaminase measurement
EFO_0021881 | ubiquitin carboxyl-terminal hydrolase 25 measurement
EFO_0021867 | plexin-B2 measurement

I will double check these terms against another ROBOT template we're working on to ensure there are no duplicates and then I'll add them before the end of the week.
