### ISSUE TITLE
New term request for Ford PMID:36006120 (WC_20221012)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1783]
21 terms: 

https://docs.google.com/spreadsheets/d/1AhEM6Jc7u-X6hrTEgXqV5iZ1qWXbA-jrixyCYjOVRv4/edit#gid=1909577919

**Comment by zoependlington** [comment]
@Santhi1901 Please could you add definitions for these terms to the spreadsheet? Every term requires a definition to meet our minimum standards for term addition into EFO. As soon as the definitions are added I can add these into EFO in time for the December release. Thanks!

**Comment by Santhi1901** [comment]
@zoependlington I've added the definitions for the terms

**Comment by zoependlington** [comment]
Thanks @Santhi1901!

**Comment by zoependlington** [comment]
Terms have been added (IDs in spreadsheet) and will be available after the January (16th) release.
