### ISSUE TITLE
New term request for Yang PMID 34565479

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1786]
For new term requests, please provide the following information:

## Preferred term label

platelet-activating factor measurement

## Synonyms

PAF, PAF-acether, AGEPC, acetyl-glyceryl-ether-phosphorylcholine

## Textual definition

Quantification of platelet-activating factor in a sample. 

## Suggested parent term

metabolite measurement

**Comment by ar-ibrahim** [comment]
Added as

**Comment by ar-ibrahim** [comment]
Added as EFO:0801075. Available on October 17th release.
