### ISSUE TITLE
New term request for Tietz PMID 34584012

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1790]
For new term requests, please provide the following information:

## Preferred term label

anti-NMDA receptor encephalitis

## note
in MONDO: http://purl.obolibrary.org/obo/MONDO_0021081

## Synonyms

Anti-N-methyl-D-aspartate receptor encephalitis

## Textual definition

An autoimmune acute encephalitis caused by antibodies against the glutamate NMDA receptor. 

## Suggested parent term

encephalitis

**Comment by ar-ibrahim** [comment]
The term MONDO:0021081 was imported into EFO and will be available after the November (15th) release.
