### ISSUE TITLE
New term request for Aksit PMID:36206743

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1798]
For new term requests, please provide the following information:

## Preferred term label

Cystic fibrosis-related diabetes

## Synonyms

CFRD

## Textual definition

A type of diabetes specifically caused by cystic fibrosis, a genetic condition.

## Suggested parent term

diabetes mellitus (http://www.ebi.ac.uk/efo/EFO_0000400)

## Attribution

NA

**Comment by d0choa** [comment]
Shouldn't this be captured as a foreground trait (Diabetes) and a background trait (Cystic fibrosis) by GWAS Catalog?

**Comment by Santhi1901** [comment]
Cystic fibrosis-related diabetes is a unique kind of diabetes as mentioned in: https://www.cff.org/managing-cf/cystic-fibrosis-related-diabetes, and it is also present in another ontology https://ontobee.org/ontology/OAE?iri=http://purl.obolibrary.org/obo/OAE_0009341
There is a similar term available in the EFO: cystic fibrosis associated meconium ileus EFO:0004608
We are happy to take any advice from the EFO team about this

**Comment by ar-ibrahim** [comment]
Added as EFO:0801077 and will be available after the November (15th) release.
