### ISSUE TITLE
New term request for Saita PMID:36123890

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1808]
For new term requests, please provide the following information:

## Preferred term label

Cancer-associated pain

## Synonyms

Cancer pain

## Textual definition

Pain associated with cancer or its diagnosis or treatment. [ NCI ]

## Suggested parent term

pain (http://www.ebi.ac.uk/efo/EFO_0003843)

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as 'cancer pain' with 'cancer-associated pain' as a synonym.

Added as EFO:0801084 which will be made available after the November (15th) release.
