### ISSUE TITLE
New term request for Thareja PMID: 36168886

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1815]
For new term requests, please provide the following information:

## Preferred term label

lithostathine-1-alpha measurement

## Synonyms

Islet cells regeneration factor (ICRF)
Islet of Langerhans regenerating protein (REG)
Pancreatic stone protein (PSP)
Pancreatic thread protein (PTP)
Regenerating islet-derived protein 1-alpha (REG-1-alpha)
Regenerating protein I alpha

## Textual definition

Quantification of the amount of lithostathine-1-alpha measurement in a sample. 

## Suggested parent term

protein measurement

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0801083** and will be available after the **November (15th) release**.
