### ISSUE TITLE
New term request for Nakabuye PMID 35461751

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1826]
For new term requests, please provide the following information:

## Preferred term label

body shape measurement

## Textual definition

Quantification of body shape, which may be derived from principal component analysis (PCA) of anthropometric traits such as BMI, weight, hip circumference and waist circumference. 

## Suggested parent term

anthropometric measurement

## from text: 
"Variants associated with body shape, as a composite variable might be different for those of individual anthropometric traits"

**Comment by ar-ibrahim** [comment]
Term added as EFO_0801227 and will be available after the December (15th) release.
