### ISSUE TITLE
New term request for Moitinho-Silva PMID:36261456

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1827]
For new term requests, please provide the following information:

## Preferred term label

skin microbiome measurement

## Synonyms

NA

## Textual definition

quantification of some aspect of an individual's micrbiome of the skin

## Suggested parent term

microbiome measurement http://www.ebi.ac.uk/efo/EFO_0007882

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as EFO_0801228 and will be available after the December (15th) release.
