### ISSUE TITLE
New term request - synthetic data

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#1829]
## Preferred term label

Synthetic data

## Synonyms

Artificial data

## Textual definition

Data that are artificially created rather than being generated by actual events.

## Suggested parent term

Child of data set http://purl.obolibrary.org/obo/IAO_0000100

Cross map to NCIT term http://purl.obolibrary.org/obo/NCIT_C176263

Note
I’m aware there is an existing 'synthetic DNA data' term, but this is not appropriate for 2 reasons, 1) we want a more generic term (covering not just DNA-related data), and 2) this term implies the synthetic DNA data has been synthesised in the real world (ie sitting in a test tube, rather than just a computational representation).
This request and definition has been discussed with the ELIXIR Machine learning working group, Synthetic data task sub-group. It will facilitate the tagging of synthetic datasets in Biostudies and more broadly.
 
## Attribution
https://orcid.org/0000-0003-0978-0309

**Comment by zoependlington** [comment]
Added as EFO_0022043, which will be available after the December release (15th).
