### ISSUE TITLE
Suggested additional ICD-10 xref for Hypertension (EFO_0000537))

### ISSUE THREAD

**Issue by spiros** [EBISPOT/efo#1832]
The ICD-10 code mapped to [hypertension (EFO_0000537)](http://www.ebi.ac.uk/efo/EFO_0000537) is "O11 Pre-existing hypertension with pre-eclampsia" which refers to essential hypertension combined with hypertension during pregnancy (pre-eclampsia). 

A more appropriate map would be "I10 Essential hypertension" so I propose this is added, either replacing the current one or in addition.

**Comment by zoependlington** [comment]
Thank you for spotting this @spiros, we'll make sure this is looked into ASAP!

**Comment by zoependlington** [comment]
ICD10:O11 has been removed as a x-ref and will be seen after the January (15th) release.

**Comment by spiros** [comment]
sounds good, thank you!
