### ISSUE TITLE
New term request for Agarwal PMID:35773277 (WC_20221104)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1834]
5 terms
https://docs.google.com/spreadsheets/d/14ThDPjfsoqbrkSMGyUL1gupJPg67Wahg7GqUcMKs0m0/edit#gid=1909577919

**Comment by ar-ibrahim** [comment]
Hi Santhi. The terms will be made available after the January (the 16th) release. https://docs.google.com/spreadsheets/d/14ThDPjfsoqbrkSMGyUL1gupJPg67Wahg7GqUcMKs0m0/edit#gid=1696971126
