### ISSUE TITLE
New term requests (Robot form) for Draisma PMID 26068415

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1835]
Robot form for metabolites. 
[Draisma EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/9939479/Draisma.EFO.robot.form1.xlsx)

**Comment by ljwh2** [comment]
@ar-ibrahim if possible could you please prioritise this one, we would like to publish it before the end of the year

**Comment by ar-ibrahim** [comment]
Terms added https://docs.google.com/spreadsheets/d/1th033XHPeKi9IISSy1qbQ3USlCPKUPvpQEW272eG_bE/edit#gid=325609555
and will be made available after the December (15th) release.

**Comment by earlEBI** [comment]
@ar-ibrahim brill, thank you!

**Comment by ar-ibrahim** [comment]
@earlEBI :blush::+1:
