### ISSUE TITLE
New Robot form terms requests for Sun BB PMID 29875488

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1836]
Robot form for 906 protein measurement terms:

[Sun EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/9951290/Sun.EFO.robot.form1.xlsx)

Checked against existing terms using Zooma. 
Please let me know if any problems.

**Comment by ljwh2** [comment]
@ar-ibrahim if possible could you please prioritise this one, we would like to publish it before the end of the year

**Comment by earlEBI** [comment]
@ar-ibrahim Hi Arwa, there's actually another 1,000-odd EFOs needed for this publication, I'm afraid. Here is the EFO form. Would it be better to create a separate ticket? 
(The full list is in SupTable 18 in the paper, if that helps, although there's some I don't seem to need.)
[Sun EFO robot form - part 2.xlsx](https://github.com/EBISPOT/efo/files/10154202/Sun.EFO.robot.form.-.part.2.xlsx)

**Comment by zoependlington** [comment]
@ljwh2 @earlEBI Arwa and I will try to get through these and get them into EFO as soon as possible, however since this is almost 2000 terms I can not promise these will be in for the December release (15th December).

If that is the case, would there be a potential possibility of tagging this study with "protein measurement" (EFO:0004747) temporarily upon initial publish and once we have managed to curate these spreadsheet templates and get them into EFO (hopefully January at the latest) then include the full specified list after we have the full list of EFO IDs?

Of course we'll do everything we can to try and get them in for December, but I don't want to promise it will happen and not deliver.

**Comment by ar-ibrahim** [comment]
[Sun EFO robot form_COMBINED.xlsx](https://github.com/EBISPOT/efo/files/10154737/Sun.EFO.robot.form_COMBINED.xlsx)

**Comment by zoependlington** [comment]
Created Google sheet so we can work on this at the same time: https://docs.google.com/spreadsheets/d/1tmlAW7oeiNerDzDHVlwLkq115laCp0kc2ZKd1M86fvY/edit?usp=sharing

The IDs will also be on the above sheet when they have been added/created.

**Comment by ar-ibrahim** [comment]
Hi @earlEBI :blush: The terms will be made available after the December (15th) release. https://docs.google.com/spreadsheets/d/1tmlAW7oeiNerDzDHVlwLkq115laCp0kc2ZKd1M86fvY/edit#gid=1119460519

The following terms already exist _(if you have any comments please let me know):_

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/aibrahim/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/aibrahim/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#1155CC" vlink="#1155CC">



Term Request | Existing ID | Notes
-- | -- | --
a disintegrin and metalloproteinase with   thrombospondin motifs 13 measurement | EFO:0008011 | Term reviewed (added 'measurement' to label)
alpha-synuclein measurement | EFO:0009323
apolipoprotein E (isoform E2) measurement | EFO:0008028
coagulation   Factor VIII measurement | EFO:0004630
dickkopf-related protein 1 measurement | EFO:0010620
fibroblast   growth factor 8 isoform A measurement | EFO:0020385 | Term reviewed   (corrected typo in label 'isoformAmeasurement')
growth/differentiation factor 15   measurement | EFO:0009181



</body>

</html>

**Comment by earlEBI** [comment]
@ar-ibrahim @zoependlington thank you so much!!
