### ISSUE TITLE
New term request for Wang PMID:35021295

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1837]
For new term requests, please provide the following information:

## Preferred term label

Premature ejaculation

## Synonyms

NA

## Textual definition

The emission of semen and seminal fluid during the act of preparation for sexual intercourse, i.e. before there is penetration or shortly after penetration. [ HPO : probinson ]

## Suggested parent term

Present in HP: Premature ejaculation http://purl.obolibrary.org/obo/HP_0012876

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term created as **EFO:0803321** and will be made available after the January (16th) release.
