### ISSUE TITLE
New Robot form term requests for Tahir PMID 35995766

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1839]
Robot form for metabolites. 
[Tahir EFO robot form2.xlsx](https://github.com/EBISPOT/efo/files/9969064/Tahir.EFO.robot.form2.xlsx)

Would it be possible for these to be created this week, at all? If not, no worries.

(I added a synonym column, if that's okay.)

**Comment by ar-ibrahim** [comment]
[Tahir.robot.form.added_EFOs.xlsx](https://github.com/EBISPOT/efo/files/9981102/Tahir.robot.form.added_EFOs.xlsx)

Terms will be available after the November (15th) release.

**Comment by earlEBI** [comment]
@ar-ibrahim Thank you!
