### ISSUE TITLE
New term request for Dennis PMID: 33441150 (WC_20221109)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1840]
15 terms:
https://docs.google.com/spreadsheets/d/1u81d_cuRTtHKqXBRR0FBfyp36kK4yNGxjsrgAXyBpEM/edit#gid=1909577919
Anti-topoisomerase I antibody positivity available in HP
all other terms available in NCIT

**Comment by ar-ibrahim** [comment]
Terms added https://docs.google.com/spreadsheets/d/1u81d_cuRTtHKqXBRR0FBfyp36kK4yNGxjsrgAXyBpEM/edit#gid=535809307
and will be made available after the February (15th) release.
