### ISSUE TITLE
New Robot form for Asimwe PMID 36210801

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1841]
Robot form for warfarin measurement terms:
[Asimwe EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/9973599/Asimwe.EFO.robot.form1.xlsx)

**Comment by ar-ibrahim** [comment]
The terms will be made available after the January (16th) release.

https://docs.google.com/spreadsheets/d/1esreMcOs6_yWUSIx24S13wOoijJa3Oc_L_bNxER4nUM/edit#gid=464663137
