### ISSUE TITLE
New term request for Hysi PMID:35050183 (WC_20221118)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1849]
71 metabolites terms:
https://docs.google.com/spreadsheets/d/1UCl4YUnaHRPu8QE5r6G9pF58uHuPSrkD/edit#gid=1253557834

**Comment by zoependlington** [comment]
Terms have been created and the IDs are on the spreadsheet (Sheet 1). They will be available after the January (16th) release.

**Comment by Santhi1901** [comment]
@zoependlington Diacylglycerol (16:1/18:2 [2], 16:0/18:3 [1]) measurement term in the sheet has given ID: EFO_0022093, but I can see that it is already available in the EFO under another ID http://www.ebi.ac.uk/efo/EFO_0800509

**Comment by zoependlington** [comment]
Thanks for catching that @Santhi1901! I'll remove the EFO_0022093 term.
