### ISSUE TITLE
merge cannabis and marijuana dependence

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#185]
http://www.ebi.ac.uk/efo/EFO_0004218
http://www.ebi.ac.uk/efo/EFO_0007191

**Comment by paolaroncaglia** [comment]
The merge in EFO is legitimate as ‘marijuana’ is a synonym of ‘cannabis’ (see e.g. https://en.wikipedia.org/wiki/Cannabis_(drug)). MONDO has already done the merge. I presume that the planned integration of EFO and MONDO would not automatically fix this issue, but just highlight it? If so, we should merge manually beforehand (note for editor: add MONDO xref; ensure that current xrefs of EFO:0004218 ‘marijuana dependence’ don’t go lost).

**Comment by zoependlington** [comment]
Merge marijuana dependence (EFO_0004218) into cannabis dependence (EFO_0007191).

- [ ] **EFO:EDIT** cannabis dependence (EFO_0007191) - ensure the following are present:
     - **Synonyms:** marijuana dependence || Marihuana Abuse || Marijuana Dependence
     - **X-refs:** DOID:1849 || DOID:9505 || ICD9:304.3 || ICD9:305.2 || NCIt:C34445 || SNOMEDCT:37344009 || SNOMEDCT:85005007 || MONDO_0005689
     - gwas_trait marijuana abuse || true

- [ ] **obsolete** EFO_0004218 marijuana dependence
