### ISSUE TITLE
New Robot form for Png PMID 36349687

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1851]
Robot EFO request form for 108 protein EFO terms: 
[Png EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/10066293/Png.EFO.robot.form1.xlsx)

**Comment by rays22** [comment]
Based on exact lexical match I have found 74% of the protein names in [Png EFO robot form1.xlsx](https://github.com/EBISPOT/efo/files/10066293/Png.EFO.robot.form1.xlsx):

Original sorting order | Protein names | PRO IDs
-- | -- | --
84 | secretoglobin family 3A member 2 | PR:000031676
93 | scavenger receptor cysteine-rich domain-containing group B protein | PR:000031066
39 | protein FAM3C | PR:000029492
106 | versican core protein | PR:000017271
105 | thymidine phosphorylase | PR:000016875
104 | thioredoxin domain-containing protein 5 | PR:000016863
103 | thyrotropin subunit beta | PR:000016724
100 | trem-like transcript 2 protein | PR:000016628
99 | tubulointerstitial nephritis antigen-like | PR:000016357
98 | metalloproteinase inhibitor 4 | PR:000016355
97 | thimet oligopeptidase | PR:000016317
96 | protein-glutamine gamma-glutamyltransferase 2 | PR:000016293
94 | serine/threonine-protein kinase 4 | PR:000015757
92 | spondin-2 | PR:000015558
89 | serpin B8 | PR:000014699
88 | serpin B6 | PR:000014697
87 | serpin A12 | PR:000014681
86 | semaphorin-3F | PR:000014620
85 | syndecan-4 | PR:000014553
82 | dihydropteridine reductase | PR:000013562
81 | prostasin | PR:000013330
80 | prolargin | PR:000013199
79 | protein phosphatase inhibitor 2 | PR:000013123
76 | paired immunoglobulin-like type 2 receptor beta | PR:000012731
75 | platelet-derived growth factor subunit A | PR:000012490
74 | poly [ADP-ribose] polymerase 1 | PR:000012289
73 | phosphoprotein associated with glycosphingolipid-enriched microdomains 1 | PR:000012231
48 | osteoclast-associated immunoglobulin-like receptor | PR:000012055
72 | neuronal pentraxin receptor | PR:000011384
71 | neural proliferation differentiation and control protein 1 | PR:000011359
70 | nodal modulator 1 | PR:000011317
68 | NAD kinase | PR:000010955
20 | cadherin-related family member 5 | PR:000010777
65 | meteorin-like protein | PR:000010339
64 | tyrosine-protein kinase Mer | PR:000010329
63 | meprin A subunit beta | PR:000010325
61 | multiple coagulation factor deficiency protein 2 | PR:000010239
58 | low-density lipoprotein receptor-related protein 11 | PR:000009918
57 | leucine-rich repeats and immunoglobulin-like domains protein 1 | PR:000009914
56 | lipoprotein lipase | PR:000009897
55 | leukocyte immunoglobulin-like receptor subfamily A member 5 | PR:000009806
53 | kallikrein-10 | PR:000009407
51 | integrin beta-7 | PR:000009143
49 | insulin-like growth factor-binding protein-like 1 | PR:000008954
47 | heme oxygenase 1 | PR:000008644
2 | adhesion G-protein coupled receptor G2 | PR:000008190
44 | lactoylglutathione lyase | PR:000008038
42 | peptidyl-prolyl cis-trans isomerase FKBP4 | PR:000007540
41 | Fc receptor-like protein 1 | PR:000007440
40 | fructose-1,6-bisphosphatase 1 | PR:000007365
45 | gastrotropin | PR:000007314
37 | protein delta homolog 1 | PR:000006521
34 | cathepsin O | PR:000006032
30 | carboxypeptidase B | PR:000005801
29 | carboxypeptidase A1 | PR:000005795
27 | clusterin-like protein 1 | PR:000005617
26 | calsyntenin-2 | PR:000005610
24 | C-type lectin domain family 5 member A | PR:000005572
23 | chordin-like protein 2 | PR:000005452
22 | chitinase-3-like protein 1 | PR:000005423
17 | CD2-associated protein | PR:000005163
14 | soluble calcium-activated nucleotidase 1 | PR:000005004
12 | bleomycin hydrolase | PR:000004760
10 | tyrosine-protein kinase receptor UFO | PR:000004528
6 | angiopoietin-related protein 7 | PR:000004032
5 | angiopoietin-related protein 1 | PR:000004026
4 | protein AMBP | PR:000003986
1 | lysophosphatidic acid phosphatase type 6 | PR:000003648
69 | nectin-2 | PR:000002069
50 | integrin beta-2 | PR:000002041
19 | complement component C1q receptor | PR:000002037
9 | aminopeptidase N | PR:000002031
16 | T-cell surface glycoprotein CD1c | PR:000002027
90 | tyrosine-protein phosphatase non-receptor type substrate 1 | PR:000001968
101 | tumor necrosis factor receptor superfamily member 10C | PR:000001952
102 | transferrin receptor protein 1 | PR:000001945
15 | sialomucin core protein 24 | PR:000001922
60 | macrophage receptor MARCO | PR:000001884
52 | junctional adhesion molecule A | PR:000001871
18 | B-cell antigen receptor complex-associated protein beta chain | PR:000001286
3 | retinal dehydrogenase 1 | Not found.
7 | DNA-(apurinic or apyrimidinic site) lyase | Not found.
8 | amyloid-like protein 1 | Not found.
11 | large proline-rich protein BAG6 | Not found.
13 | carbonic anhydrase 5A,mitochondrial | Not found.
21 | carcinoembryonic antigenrelated cell adhesion molecule 8 | Not found.
25 | CXADR-like membrane protein | Not found.
28 | collagen alpha-1 (I) chain | Not found.
31 | crk-like protein | Not found.
32 | chymotrypsin C | Not found.
33 | pro-cathepsin H | Not found.
35 | C-X-C motif chemokine 1 | Not found.
36 | 2,4-dienoyl-CoA reductase,mitochondrial | Not found.
38 | fatty acid-binding protein,intestinal | Not found.
43 | gastric intrinsic factor | Not found.
46 | hydroxyacid oxidase 1 | Not found.
54 | kynurenine-oxoglutarate transaminase 1 | Not found.
59 | lymphotoxin-beta receptor | Not found.
62 | monocyte chemoattractant protein-1 | Not found.
66 | matrix metalloproteinase-2 | Not found.
67 | matrix metalloproteinase-3 | Not found.
77 | perlecan | Not found.
78 | paraoxonase | Not found.
83 | receptor for advanced glycosylation end products | Not found.
91 | superoxide dismutase [Mn],mitochondrial | Not found.
95 | sulfatase-modifying factor 2 | Not found.
107 | v-set and immunoglobulin domain-containing protein 2 | Not found.
108 | X-C motif chemokine ligand 1 | Not found.

**Comment by rays22** [comment]
After checking the paper, it appears that these "*protein measurements*" presumably assess serum protein level traits.
For the new OBA trait categories, use component terms:
* PATO:0000070	amount
* UBERON:0001977	blood serum

**Comment by rays22** [comment]
I have mapped the the entire table to PRO terms:

Provided potein name | PRO IDs | PRO label
-- | -- | --
lysophosphatidic acid phosphatase type 6 | PR:000003648 | lysophosphatidic acid phosphatase type 6
adhesion G-protein coupled receptor G2 | PR:000008190 | adhesion G-protein coupled receptor G2
retinal dehydrogenase 1 | PR:000003920 | aldehyde dehydrogenase 1A1
protein AMBP | PR:000003986 | protein AMBP
angiopoietin-related protein 1 | PR:000004026 | angiopoietin-related protein 1
angiopoietin-related protein 7 | PR:000004032 | angiopoietin-related protein 7
DNA-(apurinic or apyrimidinic site) lyase | PR:000004127 | DNA-(apurinic or apyrimidinic site) endonuclease
amyloid-like protein 1 | PR:000004136 | amyloid beta precursor like protein 1
aminopeptidase N | PR:000002031 | aminopeptidase N
tyrosine-protein kinase receptor UFO | PR:000004528 | tyrosine-protein kinase receptor UFO
large proline-rich protein BAG6 | PR:000004651 | large proline-rich protein BAT3
bleomycin hydrolase | PR:000004760 | bleomycin hydrolase
carbonic anhydrase 5A,mitochondrial | PR:000004921 | carbonic anhydrase 5A, mitochondrial
soluble calcium-activated nucleotidase 1 | PR:000005004 | soluble calcium-activated nucleotidase 1
sialomucin core protein 24 | PR:000001922 | sialomucin core protein 24
T-cell surface glycoprotein CD1c | PR:000002027 | T-cell surface glycoprotein CD1c
CD2-associated protein | PR:000005163 | CD2-associated protein
B-cell antigen receptor complex-associated protein beta chain | PR:000001286 | B-cell antigen receptor complex-associated protein beta chain
complement component C1q receptor | PR:000002037 | complement component C1q receptor
cadherin-related family member 5 | PR:000010777 | cadherin-related family member 5
carcinoembryonic antigenrelated cell adhesion molecule 8 | PR:000001332 | carcinoembryonic antigen-related cell adhesion molecule 8
chitinase-3-like protein 1 | PR:000005423 | chitinase-3-like protein 1
chordin-like protein 2 | PR:000005452 | chordin-like protein 2
C-type lectin domain family 5 member A | PR:000005572 | C-type lectin domain family 5 member A
CXADR-like membrane protein | PR:000003605 | adipocyte adhesion molecule
calsyntenin-2 | PR:000005610 | calsyntenin-2
clusterin-like protein 1 | PR:000005617 | clusterin-like protein 1
collagen alpha-1 (I) chain | PR:000003264 | collagen alpha-1(I) chain
carboxypeptidase A1 | PR:000005795 | carboxypeptidase A1
carboxypeptidase B | PR:000005801 | carboxypeptidase B
crk-like protein | PR:000005883 | Crk-like protein
chymotrypsin C | PR:000006020 | chymotrypsin-C
pro-cathepsin H | PR:000006029 | cathepsin H
cathepsin O | PR:000006032 | cathepsin O
C-X-C motif chemokine 1 | PR:000006063 | growth-regulated alpha protein
2,4-dienoyl-CoA reductase,mitochondrial | PR:000006373 | 2,4-dienoyl-CoA reductase [(3E)-enoyl-CoA-producing], mitochondrial
protein delta homolog 1 | PR:000006521 | protein delta homolog 1
fatty acid-binding protein,intestinal | PR:000007310 | fatty acid-binding protein, intestinal
protein FAM3C | PR:000029492 | protein FAM3C
fructose-1,6-bisphosphatase 1 | PR:000007365 | fructose-1,6-bisphosphatase 1
Fc receptor-like protein 1 | PR:000007440 | Fc receptor-like protein 1
peptidyl-prolyl cis-trans isomerase FKBP4 | PR:000007540 | peptidyl-prolyl cis-trans isomerase FKBP4
gastric intrinsic factor | PR:000007975 | cobalamin binding intrinsic factor
lactoylglutathione lyase | PR:000008038 | lactoylglutathione lyase
gastrotropin | PR:000007314 | gastrotropin
hydroxyacid oxidase 1 | PR:000008441 | 2-hydroxyacid oxidase 1
heme oxygenase 1 | PR:000008644 | heme oxygenase 1
osteoclast-associated immunoglobulin-like receptor | PR:000012055 | osteoclast-associated immunoglobulin-like receptor
insulin-like growth factor-binding protein-like 1 | PR:000008954 | insulin-like growth factor-binding protein-like 1
integrin beta-2 | PR:000002041 | integrin beta-2
integrin beta-7 | PR:000009143 | integrin beta-7
junctional adhesion molecule A | PR:000001871 | junctional adhesion molecule A
kallikrein-10 | PR:000009407 | kallikrein-10
kynurenine-oxoglutarate transaminase 1 | PR:000005097 | kynurenine--oxoglutarate transaminase 1
leukocyte immunoglobulin-like receptor subfamily A member 5 | PR:000009806 | leukocyte immunoglobulin-like receptor subfamily A member 5
lipoprotein lipase | PR:000009897 | lipoprotein lipase
leucine-rich repeats and immunoglobulin-like domains protein 1 | PR:000009914 | leucine-rich repeats and immunoglobulin-like domains protein 1
low-density lipoprotein receptor-related protein 11 | PR:000009918 | low-density lipoprotein receptor-related protein 11
lymphotoxin-beta receptor | PR:000009976 | tumor necrosis factor receptor superfamily member 3
macrophage receptor MARCO | PR:000001884 | macrophage receptor MARCO
multiple coagulation factor deficiency protein 2 | PR:000010239 | multiple coagulation factor deficiency protein 2
monocyte chemoattractant protein-1 | PR:000002122 | C-C motif chemokine 2
meprin A subunit beta | PR:000010325 | meprin A subunit beta
tyrosine-protein kinase Mer | PR:000010329 | tyrosine-protein kinase Mer
meteorin-like protein | PR:000010339 | meteorin-like protein
matrix metalloproteinase-2 | PR:000010479 | 72 kDa type IV collagenase
matrix metalloproteinase-3 | PR:000010488 | stromelysin-1
NAD kinase | PR:000010955 | NAD kinase
nectin-2 | PR:000002069 | nectin-2
nodal modulator 1 | PR:000011317 | nodal modulator 1
neural proliferation differentiation and control protein 1 | PR:000011359 | neural proliferation differentiation and control protein 1
neuronal pentraxin receptor | PR:000011384 | neuronal pentraxin receptor
phosphoprotein associated with glycosphingolipid-enriched microdomains 1 | PR:000012231 | phosphoprotein associated with glycosphingolipid-enriched microdomains 1
poly [ADP-ribose] polymerase 1 | PR:000012289 | poly [ADP-ribose] polymerase 1
platelet-derived growth factor subunit A | PR:000012490 | platelet-derived growth factor subunit A
paired immunoglobulin-like type 2 receptor beta | PR:000012731 | paired immunoglobulin-like type 2 receptor beta
perlecan | PR:000008826 | basement membrane-specific heparan sulfate proteoglycan core protein
paraoxonase | PR:000013021 | serum paraoxonase/arylesterase 1
protein phosphatase inhibitor 2 | PR:000013123 | protein phosphatase inhibitor 2
prolargin | PR:000013199 | prolargin
prostasin | PR:000013330 | prostasin
dihydropteridine reductase | PR:000013562 | dihydropteridine reductase
receptor for advanced glycosylation end products | PR:000003828 | advanced glycosylation end product-specific receptor
secretoglobin family 3A member 2 | PR:000031676 | secretoglobin family 3A member 2
syndecan-4 | PR:000014553 | syndecan-4
semaphorin-3F | PR:000014620 | semaphorin-3F
serpin A12 | PR:000014681 | serpin A12
serpin B6 | PR:000014697 | serpin B6
serpin B8 | PR:000014699 | serpin B8
tyrosine-protein phosphatase non-receptor type substrate 1 | PR:000001968 | tyrosine-protein phosphatase non-receptor type substrate 1
superoxide dismutase [Mn],mitochondrial | PR:000015400 | superoxide dismutase [Mn], mitochondrial
spondin-2 | PR:000015558 | spondin-2
scavenger receptor cysteine-rich domain-containing group B protein | PR:000031066 | scavenger receptor cysteine-rich domain-containing group B protein
serine/threonine-protein kinase 4 | PR:000015757 | serine/threonine-protein kinase 4
sulfatase-modifying factor 2 | PR:000015828 | inactive C-alpha-formylglycine-generating enzyme 2
protein-glutamine gamma-glutamyltransferase 2 | PR:000016293 | protein-glutamine gamma-glutamyltransferase 2
thimet oligopeptidase | PR:000016317 | thimet oligopeptidase
metalloproteinase inhibitor 4 | PR:000016355 | metalloproteinase inhibitor 4
tubulointerstitial nephritis antigen-like | PR:000016357 | tubulointerstitial nephritis antigen-like
trem-like transcript 2 protein | PR:000016628 | trem-like transcript 2 protein
tumor necrosis factor receptor superfamily member 10C | PR:000001952 | tumor necrosis factor receptor superfamily member 10C
transferrin receptor protein 1 | PR:000001945 | transferrin receptor protein 1
thyrotropin subunit beta | PR:000016724 | thyrotropin subunit beta
thioredoxin domain-containing protein 5 | PR:000016863 | thioredoxin domain-containing protein 5
thymidine phosphorylase | PR:000016875 | thymidine phosphorylase
versican core protein | PR:000017271 | versican core protein
v-set and immunoglobulin domain-containing protein 2 | PR:000032670 | V-set and immunoglobulin domain-containing protein 2
X-C motif chemokine ligand 1 | PR:000002140 | lymphotactin

**Comment by earlEBI** [comment]
Thank you for these - could I just confirm I should be using OBA URIs in the form http://purl.obolibrary.org/obo/... which will be included in EFO? or will there be separate EFO URIs created?

**Comment by rays22** [comment]
> 

Yes, please use the format `http://purl.obolibrary.org/obo/OBA_XXXXXXX` which will be imported into EFO, like for example [this 'age of onset' term.](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_2001000)
