### ISSUE TITLE
New term request for sci-ATAC-seq3

### ISSUE THREAD

**Issue by jychien** [EBISPOT/efo#1859]
For new term requests, please provide the following information:

## Preferred term label

sci-ATAC-seq3

## Synonyms

none _(although, possibly Sci-ATAC-seq3 if we want to correspond with sci-RNA-seq3)_

## Textual definition
A single cell plate-based three-level combinatorial indexing assay that measures chromatin accessibility. The first two rounds of split-pool indexing are achieved by successive ligations to each end of the Tn5 transposase complex, and the third round remains through PCR. The protocol no longer requires cell sorting and has been optimized to maximize recovery of fragments per cell.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7785298/ (PMID: 33184180)
## Suggested parent term

scATAC-seq (EFO:0010891)

## Attribution

https://orcid.org/0000-0003-4389-9821

**Comment by zoependlington** [comment]
Added as EFO_0022045 which will be available after our January release (16th January).
