### ISSUE TITLE
Pulmonary Hypertension classification in EFO

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#186]
## Preamble

The consequence of having an ORDO "genetics disorder" branch in EFO is that it splits related diseases between the main anatomical system branches and the familial/rare/heritable/etc. forms of the diseases. In principle, the categorization make sense but this is causing issues when trying to group diseases in a meaningful ways in Open Targets.

A representative example is "pulmonary arterial hypertension" and related disorders  which needs to be better connected in EFO.

A good resource to understand the official classification for Pulmonary Hypertension is:
https://www.nhlbi.nih.gov/health-topics/pulmonary-hypertension
The World Health Organization divides pulmonary hypertension (PH) into five groups. These groups are organized based on the cause of the condition.

We will focus here on diseases represented in EFO and ORDO.

## Pulmonary arterial hypertension (PAH)
http://www.ebi.ac.uk/efo/EFO_0001361

PAH is classified under vascular and cardiovascular diseases.
It should also be classified under respiratory system disease (PH is increased pressure in the pulmonary arteries).

## Idiopathic and/or familial pulmonary arterial hypertension
http://www.orpha.net/ORDO/Orphanet_422

Idiopathic and/or familial pulmonary arterial hypertension (IFPAH) is a form or pulmonary arterial hypertension (PAH, see his term) characterized by elevated pulmonary arterial resistance leading to right heart failure; it is progressive and potentially fatal. 

Since it's a form of PAH, it should be classified as such, which I think it is in Orphanet but not in EFO.

There is an issue with the definition in EFO. Half of the text is missing.

## Drug- or toxin-induced pulmonary arterial hypertension
http://www.orpha.net/ORDO/Orphanet_275786

is missing in EFO.

## Pulmonary arterial hypertension associated with another disease
http://www.orpha.net/ORDO/Orphanet_275791

is missing in EFO.

We may need additional synonyms for each subtype, for instance:
"PAH occurring in association with scleroderma," will have "scleroderma-associated PAH." as a synonym.

## Pulmonary arterial hypertension associated with congenital heart disease
http://www.ebi.ac.uk/efo/EFO_0009054

is in EFO but should be under "Pulmonary arterial hypertension associated with another disease"
Besides, there is no synonyms defined.

## Pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis
http://www.orpha.net/ORDO/Orphanet_431353

Is missing in EFO.

Pulmonary capillary hemangiomatosis and Pulmonary venoocclusive disease are classified under this class.
Pulmonary capillary hemangiomatosis (PCH) is a rare form of pulmonary arterial hypertension is a are form of PH but is not classified as such in EFO.

Pulmonary venoocclusive disease is classified under PAH in EFO but not under the Orphanet parent term.

Please can you follow the Orphanet classification, please?

## Eisenmenger syndrome
Eisenmenger syndrome, a type of congenital heart disease, causes pulmonary hypertension and is defined in Orphanet as a type of PAH.

I could not find it in EFO.

http://purl.obolibrary.org/obo/NCIT_C84390
http://www.orpha.net/ORDO/Orphanet_97214

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0001361 subClassOf http://www.ebi.ac.uk/efo/EFO_0000684
http://www.orpha.net/ORDO/Orphanet_422 subClassOf http://www.ebi.ac.uk/efo/EFO_0001361 

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@gkos-bio 
It looks like most (if not all) of these issues would be dealt with by the integration with MONDO (see http://purl.obolibrary.org/obo/MONDO_0015924) and the release of EFO 3 (scheduled for mid-September). Please let us know if you’d be willing to wait until then, or if there are priorities/blockers in this ticket that are more urgent. Thanks!

**Comment by zoependlington** [comment]
In accordance with what was agreed in our scrum, these edits and new terms will be added.

**Work in progress:**

- [ ] **EFO:EDIT1** Pulmonary hypertension
     - Add as subclass of respiratory system disease
     - Change label to Pulmonary arterial hypertension (PAH)
     - **Synonyms:** Pulmonary hypertension || PAH

- [ ] **EFO:EDIT2** Idiopathic and/or familial pulmonary arterial hypertension
     - Subclass of pulmonary hypertension
     - needs to be aligned with Orphanet ie. should be classified at a pulmonary arterial hypertension.
     - definition needs to be edited to contain full definition:
          - Idiopathic and/or familial pulmonary arterial hypertension (IFPAH) is a form or pulmonary arterial hypertension (PAH, see his term) characterized by elevated pulmonary arterial resistance leading to right heart failure; it is progressive and potentially fatal. About 75% of heritable pulmonary arterial hypertension (HPAH, see this term) have an identified mutation. HPAH has been linked to mutations in BMPR2 in 75% of cases; other genes implicated in HPAH include ACVR1, BMPR1, CAV1, ENG and SMAD9 and CBLN2. (However, the majority of patients carrying an HPAH mutation do not develop PAH). Idiopathic pulmonary arterial hypertension (IFPAH; see this term) refers to those cases of pulmonary arterial hypertension in which etiology remains unknown.
     - check other aspects still align such as x-refs and subclass information

- [ ] **EFO:NEW1** Drug- or toxin-induced pulmonary arterial hypertension
     - Subclass of pulmonary arterial hypertension
     - **Definition:** Drug- or toxin-induced pulmonary arterial hypertension (PAH) is a form of pulmonary arterial hypertension (PAH, see this term) secondary to the exposition to drugs. Drug- or toxin-induced PAH is characterized by elevated pulmonary arterial resistance leading to right heart failure. Drug or toxin induced PAH is progressive and potentially fatal.
     - **Synonyms:** Drug- or toxin-induced PAH
     - **X-refs:** Orphanet:275786 || UMLS:C0340544 

- [ ] **EFO:NEW2** Pulmonary arterial hypertension associated with another disease
     - Subclass of pulmonary arterial hypertension
     - **Definition:** Pulmonary arterial hypertension associated with another disease is a group of conditions that lead to PAH (see this term); connective tissue diseases (lupus erythematosus, systemic sclerosis and mixed connective tissues disease), congenital heart disease (Eisenmenger syndrome), HIV infection, portal hypertension, schistosomiasis and chronic hemolytic anemia (see these terms),which is characterized by elevated pulmonary arterial resistance leading to right heart failure that is progressive and potentially fatal.
     - **Synonyms:** PAH associated with another disease || Secondary PAH
     - Do we want to add all the child terms, too? I would say yes.
          - Pulmonary arterial hypertension associated with HIV infection
          - Pulmonary arterial hypertension associated with chronic hemolytic anemia
          - Pulmonary arterial hypertension associated with connective tissue disease
          - Pulmonary arterial hypertension associated with portal hypertension
          - Pulmonary arterial hypertension associated with schistosomiasis

- [ ] **EFO:EDIT3** Pulmonary arterial hypertension associated with congenital heart disease
     - Change subclass to Pulmonary arterial hypertension associated with another disease
     - **Synonyms:** PAH associated with congenital heart disease || congenital heart disease-associated PAH

- [ ] **EFO:NEW3** Pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis
     - Subclass of pulmonary arterial hypertension
     - Need info. look at this part in more detail!

- [ ] **EFO:EDIT4** pulmonary capillary hemangiomatosis
     - Change to subclass of Pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis
     - 

- [ ] **EFO:EDIT5** pulmonary venoocclusive disease
    - Change to subclass of Pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis

- [ ] **EFO:NEW4** Eisenmenger syndrome
    - Subclass of Pulmonary arterial hypertension associated with congenital heart disease
    - **Description:** Eisenmenger syndrome (ES) is an form of pulmonary arterial hypertension (PAH) associated with unoperated congenital heart disease and is characterized by congenital heart malformations (see these terms) with reversed or bi-directional shunting through an intra-cardiac or intervascular (usually aorto-pulmonary) communication with the development of PAH.
    - **X-refs:** MedDRA:10058554 || UMLS:C0013743

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO_0009200 || Eisenmenger syndrome
EFO_0009199 || Pulmonary veno-occlusive disease and/or pulmonary capillary haemangiomatosis
EFO_0009198 || Pulmonary arterial hypertension associated with schistosomiasis
EFO_0009197 || Pulmonary arterial hypertension associated with portal hypertension 
EFO_0009196 || Pulmonary arterial hypertension associated with connective tissue disease 
EFO_0009195 || Pulmonary arterial hypertension associated with chronic hemolytic anemia 
EFO_0009194 || Pulmonary arterial hypertension associated with HIV infection
EFO_0009193 || Pulmonary arterial hypertension associated with another disease
EFO_0009192 || Drug- or toxin-induced pulmonary arterial hypertension
