### ISSUE TITLE
New terms request for Kim PMID: 36065883 (WC_20221207)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1864]
3 new terms:
1 parent term and 2 child terms
https://docs.google.com/spreadsheets/d/1gd7y1bHCY8toBr8d2vEZYZrRl-va0Ktd/edit#gid=1567901215

**Comment by zoependlington** [comment]
The IDs have been added to the template spreadsheet and these terms will be available after the January (16th) release.
