### ISSUE TITLE
New term request for Lemaitre PMID:36442731

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1865]
2 terms:
https://docs.google.com/spreadsheets/d/18AwVAtAkyltfrUCwPog1RpBAGsUcyK1b/edit#gid=2056587859

**Comment by zoependlington** [comment]
These terms have been added as the following and will be available after our January (16th) release:

EFO_0022046 || sulcal opening distance
EFO_0022047 || sulcal depth
