### ISSUE TITLE
New term request for Vernet PMID:35671886

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1868]
For new term requests, please provide the following information:

## Preferred term label

Eosinophil-derived neurotoxin measurement

## Synonyms

NA

## Textual definition

The determination of the amount of the eosinophil-derived neurotoxin in a sample. [ NCI ]

## Suggested parent term
 
blood protein measurement (http://www.ebi.ac.uk/efo/EFO_0007937)

## Attribution

NA

##
term available in NCIT http://purl.obolibrary.org/obo/NCIT_C184644

**Comment by zoependlington** [comment]
Added as EFO_0022048, which will be available after the January (16th) release.
