### ISSUE TITLE
Red cell distribution width

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#188]
## Preferred term label

Red cell distribution width

## Synonyms

Red blood cell erythrocyte distribution width
Red cell distribution width (RDW) blood test
RDW
RDW-CV
RCDW
RDW-SD

## Textual definition

https://en.wikipedia.org/wiki/Red_blood_cell_distribution_width

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for editor: the requested new term seems to be the same as NCIT:C64800 ‘Erythrocyte Distribution Width Measurement’ (http://purl.obolibrary.org/obo/NCIT_C64800), so we should add that as a cross-reference.

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW** Red cell distribution width
     - Subclass of hemoglobin measurement (EFO_0004509)
     - **Synonyms:** Red blood cell erythrocyte distribution width || Red cell distribution width (RDW) blood test || RDW || RDW-CV || RCDW || RDW-SD || Erythrocyte Distribution Width Measurement
     - **Definition:** Red blood cell distribution width (RDW or RDW-CV or RCDW and RDW-SD) is a measure of the range of variation of red blood cell (RBC) volume that is reported as part of a standard complete blood count. Usually red blood cells are a standard size of about 6-8 μm in diameter. Certain disorders, however, cause a significant variation in cell size. Higher RDW values indicate greater variation in size. Normal reference range of RDW-CV in human red blood cells is 11.5-14.5%.[1] If anemia is observed, RDW test results are often used together with mean corpuscular volume (MCV) results to determine the possible causes of the anemia. It is mainly used to differentiate an anemia of mixed causes from an anemia of a single cause.
     - **X-refs:** Wikipedia:Red_blood_cell_distribution_width || NCIT:C64800

**Comment by zoependlington** [comment]
Here's the new EFO ID:
EFO_0009188 || Red cell distribution width
