### ISSUE TITLE
New term request for Sadler PMID:36546557

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1883]
For new term requests, please provide the following information:

## Preferred term label

Vestibular Schwannoma

## Synonyms

NA

## Textual definition

A vestibular Schwannoma (also known as acoustic neuroma, acoustic neurinoma, or acoustic neurilemoma) is a benign, usually slow-growing tumor that develops from the VIIIth cranial nerve supplying the inner ear. [ HPO : probinson ]

## Suggested parent term

inner ear neoplasm http://purl.obolibrary.org/obo/MONDO_0024320

## Attribution

NA

HP term available: http://purl.obolibrary.org/obo/HP_0009588

**Comment by zoependlington** [comment]
Imported [HP_0009588](http://purl.obolibrary.org/obo/HP_0009588), which will be available after the January (16th) release.
