### ISSUE TITLE
NTRs: metabolite measurements (PMID: 32150548)

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#1884]
Hi! We would like to ask you to create 47 new terms that capture diverse metabolites measurements, mainly coming from lipid metabolism. 

The terms are pretty granular, this is to capture with detail the effect of rare variants on biomarkers relevant in Cardiovascular Disease as reported in [32150548](https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008605#sec019). This curated paper will be included as one of our sources for the gene burden associations.

<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

Term Label | Definition | Parent
-- | -- | --
Triglycerides in very small VLDL | Desc: "Quantification of triglycerides in very small VLDL." | EFO_0004530
Triglycerides in small VLDL | Desc: "Quantification of triglycerides in small VLDL." | EFO_0004530
Phospholipids in small VLDL | Desc: "Quantification of phospholipids in small VLDL." | EFO_0004639
Concentration of small VLDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of small very-low-density lipoprotein in a specimen." | EFO_0004529
Total lipids in small VLDL | Desc: "Quantification of total lipids in small VLDL." | EFO_0004529
Triglycerides in IDL | Desc: "Quantification of triglycerides in IDL." | EFO_0004530
Phospholipids in very small VLDL | Desc: "Quantification of phospholipids in very small VLDL." | EFO_0004529
Concentration of very small VLDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of very small very-low-density lipoprotein in a specimen." | EFO_0004732
Concentration of medium VLDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of very-low-density lipoprotein in a specimen." | EFO_0004732
Total lipids in medium VLDL | Desc: "Quantification of total lipids in medium VLDL." | EFO_0004529
Phospholipids in medium VLDL | Desc: "Quantification of phospholipids in medium VLDL." | EFO_0004639
Triglycerides in medium VLDL | Desc: "Quantification of triglycerides in medium VLDL." | EFO_0004530
Total lipids in very small VLDL | Desc: "Quantification of total lipids in very small VLDL." | EFO_0004529
Free cholesterol in large HDL | Desc: "Quantification of free cholesterol contained in or bound to HDL." | CHEBI_47775
Triglycerides in small HDL | Desc: "Quantification of triglycerides in small HDL." | EFO_0004530
Cholesterol esters in large HDL | Desc: "Quantification of cholesterol esters contained in or bound to HDL." | CHEBI_47775
Concentration of large LDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of large low-density lipoprotein in a specimen." | EFO_0004732
Total lipids in IDL | Desc: "Quantification of total lipids in IDL." | EFO_0004529
Total cholesterol in medium VLDL | Desc: "Quantification of total cholesterol in medium VLDL." | EFO_0008317
Total lipids in large LDL | Desc: "Quantification of total lipids in large LDL." | EFO_0004529
Phospholipids in IDL | Desc: "Quantification of phospholipids in IDL." | EFO_0004639
Cholesterol esters in large LDL | Desc: "Quantification of cholesterol esters contained in or bound to large LDL." | EFO_0004195
Concentration of small LDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of small low-density lipoprotein in a specimen." | EFO_0004732
Total cholesterol in large LDL | Desc: "Quantification of total cholesterol in large LDL." | EFO_0004195
Total lipids in small LDL | Desc: "Quantification of total lipids in small LDL." | EFO_0004529
Phospholipids in large VLDL | Desc: "Quantification of phospholipids in large VLDL." | EFO_0004639
Cholesterol esters in large VLDL | Desc: "Quantification of cholesterol esters contained in or bound to large VLDL." | EFO_0008317
Total cholesterol in small VLDL | Desc: "Quantification of total cholesterol in small VLDL." | EFO_0008317
Concentration of medium LDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of medium low-density lipoprotein in a specimen." | EFO_0004732
Concentration of large VLDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of large very-low-density lipoprotein in a specimen." | EFO_0004732
Phospholipids in large LDL | Desc: "Quantification of phospholipids in large LDL." | EFO_0004639
Total lipids in large VLDL | Desc: "Quantification of total lipids in large VLDL." | EFO_0004529
Free cholesterol in large LDL | Desc: "Quantification of free cholesterol contained in or bound to LDL." | EFO_0008591
Total cholesterol in large VLDL | Desc: "Quantification of total cholesterol in large VLDL." | EFO_0008317
Parent | Desc: "Quantification of triglycerides in large VLDL." | EFO_0004530
Total cholesterol in small LDL | Desc: "Quantification of total cholesterol in small LDL." | EFO_0004195
Total lipids in medium LDL | Desc: "Quantification of total lipids in medium LDL." | EFO_0004529
Free cholesterol in IDL | Desc: "Quantification of free cholesterol contained in or bound to IDL." | EFO_0008591
Cholesterol esters in medium VLDL | Desc: "Quantification of cholesterol esters contained in or bound to medium VLDL." | EFO_0008317
Phospholipids in medium LDL | Desc: "Quantification of phospholipids in medium LDL." | EFO_0004639
Total cholesterol in IDL | Desc: "Quantification of total cholesterol in IDL." | CHEBI_16113
Total cholesterol in medium LDL | Desc: "Quantification of total cholesterol in medium LDL." | EFO_0004195
Cholesterol esters in medium LDL | Desc: "Quantification of cholesterol esters contained in or bound to medium LDL." | EFO_0004195
Monounsaturated fatty acids; 16:1, 18:1 | Desc: "The determination of the amount of polyunsaturated fatty acids present in a sample." | EFO_0005110
Concentration of large HDL particles | Desc: "A lipoprotein concentration assay that measures the concentration of large high-density lipoprotein in a specimen." | EFO_0004732
Total lipids in large HDL | Desc: "Quantification of total lipids in large HDL." | EFO_0004529
Phospholipids in large HDL | Desc: "Quantification of phospholipids in large HDL." | EFO_0004639

</google-sheets-html-origin>

ORCID id: https://orcid.org/0000-0002-2417-7324

Thank you very much.

**Comment by zoependlington** [comment]
Terms have been added as follows and will be available after the January (16th) release:

ID | LABEL
-- | --
EFO:0022144 | triglycerides in very small VLDL measurement
EFO:0022145 | triglycerides in small VLDL measurement
EFO:0022146 | phospholipids in small VLDL measurement
EFO:0022147 | concentration of small VLDL particles
EFO:0022148 | total lipids in small VLDL
EFO:0022149 | triglycerides in IDL measurement
EFO:0022150 | phospholipids in very small VLDL measurement
EFO:0022151 | concentration of very small VLDL particles
EFO:0022152 | concentration of medium VLDL particles
EFO:0022153 | total lipids in medium VLDL
EFO:0022154 | phospholipids in medium VLDL measurement
EFO:0022155 | triglycerides in medium VLDL measurement
EFO:0022156 | total lipids in very small VLDL measurement
EFO:0022157 | free cholesterol in large HDL measurement
EFO:0022158 | triglycerides in small HDL measurement
EFO:0022159 | cholesterol esters in large HDL measurement
EFO:0022160 | concentration of large LDL particles measurement
EFO:0022161 | total lipids in IDL
EFO:0022162 | total cholesterol in medium VLDL
EFO:0022163 | total lipids in large LDL
EFO:0022164 | phospholipids in IDL measurement
EFO:0022165 | cholesterol esters in large LDL measurement
EFO:0022166 | concentration of small LDL particles measurement
EFO:0022167 | total cholesterol in large LDL
EFO:0022168 | total lipids in small LDL
EFO:0022169 | phospholipids in large VLDL measurement
EFO:0022170 | cholesterol esters in large VLDL measurement
EFO:0022171 | total cholesterol in small VLDL
EFO:0022172 | concentration of medium LDL particles measurement
EFO:0022173 | concentration of large VLDL particles measurement
EFO:0022174 | phospholipids in large LDL measurement
EFO:0022175 | total lipids in large VLDL
EFO:0022176 | free cholesterol in large LDL measurement
EFO:0022177 | total cholesterol in large VLDL
EFO:0022178 | triglycerides in large VLDL measurement
EFO:0022179 | total cholesterol in small LDL
EFO:0022180 | total lipids in medium LDL
EFO:0022181 | free cholesterol in IDL measurement
EFO:0022182 | cholesterol esters in medium VLDL measurement
EFO:0022183 | phospholipids in medium LDL measurement
EFO:0022184 | total cholesterol in IDL
EFO:0022185 | total cholesterol in medium LDL
EFO:0022186 | cholesterol esters in medium LDL measurement
EFO:0022187 | monounsaturated fatty acids; 16:1, 18:1 measurement
EFO:0022188 | concentration of large HDL particles measurement
EFO:0022189 | total lipids in large HDL
EFO:0022190 | phospholipids in large HDL measurement
