### ISSUE TITLE
New term request for Baloni PMID:36209301 (WC_20230111)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1885]
4 terms
https://docs.google.com/spreadsheets/d/1Kna2-FgxkO-tlJoj5DCbZp7v_D2pKLhW/edit#gid=435625397

**Comment by ar-ibrahim** [comment]
The requested terms for [Baloni PMID:36209301 ](https://docs.google.com/spreadsheets/d/1Kna2-FgxkO-tlJoj5DCbZp7v_D2pKLhW/edit#gid=2106755343) will be made available after the January (16th) release.
