### ISSUE TITLE
New term request for Mompeo PMID:36297114

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1894]
For new term requests, please provide the following information:

## Preferred term label

Dietary Approaches to Stop Hypertension diet

## Synonyms

DASH

## Textual definition

The diet promotes the consumption of vegetables and fruits, lean meat and dairy products, the inclusion of micronutrients and the reduction of sodium in the diet to about 1500 mg/day.

## Suggested parent term

diet (http://www.ebi.ac.uk/efo/EFO_0002755)

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803365** and will be made available after the February (15th) release.
