### ISSUE TITLE
New term request for Durda PMID:36314488

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1896]
For new term requests, please provide the following information:

## Preferred term label

soluble CD163 measurement

## Synonyms

cluster of differentiation 163, sCD163

## Textual definition

Quantification of the circulating pattern recognition receptor CD163 in a sample such as blood plasma.

## Suggested parent term

blood protein measurement http://www.ebi.ac.uk/efo/EFO_0007937

## Attribution

NA

**Comment by dosumis** [comment]
Is it practice to reference uniprot for markers like this -  https://www.uniprot.org/uniprotkb/Q86VB7/entry

Would like to encourage.

**Comment by zoependlington** [comment]
Term added as EFO_0020072, which will be available after the March (15th) release.
