### ISSUE TITLE
New term request for Urso PMID:36320039

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1897]
For new term requests, please provide the following information:

## Preferred term label

ovulation

## Synonyms

NA

## Textual definition

The discharge of a secondary oocyte from a vesicular follicle of the ovary. [ NCI ]

## Suggested parent term

reproductive process http://purl.obolibrary.org/obo/GO_0000003

## Attribution

NA

**Comment by dosumis** [comment]
GO already has ovulation: http://amigo.geneontology.org/amigo/term/GO:0030728

**Comment by zoependlington** [comment]
I have imported ovulation (GO_0030728) into EFO, which will be available after the February (15th) release.
