### ISSUE TITLE
Additional terms for EFO_0002012 organization role

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#19]
The IMAGE project (http://www.imageh2020.eu/) wishes to use EFO_0002012 organization role to describe the different sources of the biomaterials being contributed to the project and request the following addition of terms to the ontology:

Gene bank
Breeding company
Breeding association

 

Contacts: peter@ebi.ac.uk and alessandra.stella@tecnoparco.org

**Comment by siiraa** [comment]
@simonjupp - you e-mailed the requester for clarification right? What did they say?

**Comment by paolaroncaglia** [comment]
@simonjupp 
Is this still current, please? Should we close or follow up? Thanks.

**Comment by daniwelter** [comment]
Closing as no response on this ticket in almost 2 years. If this is still required, please file a new ticket.
