### ISSUE TITLE
Measurement of reticulocyte haemoglobin

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#190]
It might wise to list all the missing hematology tests in EFO and available in NCIt

## Preferred term label

Reticulocyte Mean Corpuscular Hemoglobin Measurement

## Synonyms

reticulocyte hemoglobin content (CHr)
CHr
Measurement of reticulocyte haemoglobin
reticulocyte haemoglobin measurement
High light scatter reticulocyte percentage

## x-refs

http://purl.obolibrary.org/obo/NCIT_C117855

## Textual definition

The determination of the mean amount of hemoglobin per reticulocyte present in a sample. [ NCI ]

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW** Reticulocyte Mean Corpuscular Hemoglobin Measurement
     - Subclass of hemoglobin measurement (EFO_0004509)
     - **Definition:** The determination of the mean amount of hemoglobin per reticulocyte present in a sample. [ NCI ]
     - **Synonyms:** reticulocyte hemoglobin content (CHr) || CHr || Measurement of reticulocyte haemoglobin || reticulocyte haemoglobin measurement || High light scatter reticulocyte percentage
     - **X-refs:** NCIt:C117855 || UMLS_CUI:C3897698

### OTHER:
Look through other children of hemoglobin measurement and add those that aren't already in EFO.
This has been started [here](https://docs.google.com/spreadsheets/d/1QtH9eHUmzjp68sNf3KywCbyiEdrVmrgqjUwW5o0TVRY/edit?usp=sharing)

**Comment by zoependlington** [comment]
Here is the new IDs:
EFO_0009202 | Reticulocyte Mean Corpuscular Hemoglobin Measurement

Still to do:
Look through other children of hemoglobin measurement and add those that aren't already in EFO.

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:

EFO_0009212 | 'Hemoglobin A2 to Total Hemoglobin Ratio Measurement'
EFO_0009211 | 'Hemoglobin A2 Prime to Total Hemoglobin Ratio Measurement' 
EFO_0009210 | 'Hemoglobin A1 to Total Hemoglobin Ratio Measurement'
EFO_0009209 | 'Hemoglobin A to Total Hemoglobin Ratio Measurement'
EFO_0009208 | 'Hemoglobin A Measurement'
EFO_0009207 | 'Glycosylated Hemoglobin Measurement'
EFO_0009206 | 'Free Hemoglobin Measurement'
EFO_0009205 | 'Corpuscular Hemoglobin Content'
EFO_0009204 | 'Corpuscular Hemoglobin Concentration Distribution Width'
EFO_0009203 | 'Carboxyhemoglobin to Total Hemoglobin Ratio Measurement'
EFO_0009222 | 'Hemoglobin O-Arab to Total Hemoglobin Ratio Measurement'
EFO_0009221 | 'Hemoglobin Lepore to Total Hemoglobin Ratio Measurement'
EFO_0009220 | 'Hemoglobin G Coushatta to Total Hemoglobin Ratio Measurement'
EFO_0009219 | 'Hemoglobin F to Total Hemoglobin Ratio Measurement'
EFO_0009218 | 'Hemoglobin E to Total Hemoglobin Ratio Measurement'
EFO_0009217 | 'Hemoglobin D to Total Hemoglobin Ratio Measurement'
EFO_0009216 | 'Hemoglobin C to Total Hemoglobin Ratio Measurement'
EFO_0009215 | 'Hemoglobin C Measurement' 
EFO_0009214 | 'Hemoglobin Barts to Total Hemoglobin Ratio Measurement'
EFO_0009213 | 'Hemoglobin B Measurement'
EFO_0009231 | 'Reticulocyte Hemoglobin Distribution Width' 
EFO_0009230 | 'Reticulocyte Corpuscular Hemoglobin Distribution Width'
EFO_0009229 | 'Reticulocyte Corpuscular Hemoglobin Content'
EFO_0009228 | 'Reticulocyte Corpuscular Hemoglobin Concentration Mean'
EFO_0009227 | 'Oxyhemoglobin to Total Hemoglobin Ratio Measurement'
EFO_0009226 | 'Methemoglobin to Total Hemoglobin Ratio Measurement'
EFO_0009225 | 'Hemoglobin Tetramer Measurement'
EFO_0009224 | 'Hemoglobin S to Total Hemoglobin Ratio Measurement'
EFO_0009223 | 'Hemoglobin S Measurement'
