### ISSUE TITLE
New term request for Strom PMID:36379924

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1902]
For new term requests, please provide the following information:

## Preferred term label

Hoarding Disorder

## Synonyms

NA

## Textual definition

A mental disorder characterized by persistent difficulties discarding or parting with possessions, often resulting in cluttered living spaces, distress, and impairment.

## Suggested parent term

mental or behavioural disorder http://www.ebi.ac.uk/efo/EFO_0000677

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO_0803361** and will be made available after the February (15th) release.
