### ISSUE TITLE
Measurement of immature reticulocyte fraction

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#191]
Another blood cell count measurement missing in EFO.
Please could you look at the NCIt systematic classification of blood cell count measurements and how many are missing in EFO?

## Preferred term label

Immature Reticulocyte Fraction Measurement

## Synonyms

Measurement of Immature Reticulocyte Fraction
Immature Reticulocyte Fraction
IRF

## X-refs

The determination of the ratio of immature reticulocytes to total reticulocytes present in a sample. [ NCI ]

## Textual definition

The determination of the ratio of immature reticulocytes to total reticulocytes present in a sample. [ NCI ]
## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Still work in progress.

- [ ] **EFO:EDIT1** complete blood cell count (EFO_0004586)
     - **Synonyms:** blood cell count || FBC || Complete Blood Count || Full Blood Count || complete blood count
     - **X-refs:** NCIt:C28133 || UMLS_CUI:C0005771

- [ ] **EFO:EDIT2** erythrocyte count (EFO_0004305)
     - Add as subclass of complete blood cell count (EFO_0004586)

- [ ] **EFO:EDIT3** leukocyte count (EFO_0004308)
     - Change to subclass of complete blood cell count (EFO_0004586)
     - Correct strange characters in description

- [ ] **EFO:EDIT4** platelet count (EFO_0004309)
     - Change to subclass of complete blood cell count (EFO_0004586)
     - Correct strange characters in description

- [ ] Webulous template found [here](https://docs.google.com/spreadsheets/d/1-bAyIHPNpnpCAdQFur0cpX91wW1hV2wHp2EJX_GeFNE/edit?usp=sharing)

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:

EFO_0009232 | 'Blast Count'
EFO_0009242 | 'Myeloid Progenitor Cell Count' 
EFO_0009241 | 'Monocytoid Cells to Leukocytes Ratio Measurement'
EFO_0009240 | 'Metarubricyte Count' 
EFO_0009239 | 'Mature Plasma Cell Count'
EFO_0009238 | 'Immature Plasma Cell Count'
EFO_0009237 | 'Estimated Platelets Measurement'
EFO_0009236 | 'Eosinophilic Myelocyte Count'
EFO_0009235 | 'Eosinophilic Metamyelocyte Count'
EFO_0009234 | 'Blood Cell Count with Differential'
EFO_0009233 | 'Blood Cell Count Ratio Measurement'
EFO_0009252 | 'Segmented Neutrophils to Neutrophils Ratio Measurement' 
EFO_0009251 | 'Rubricyte Count' 
EFO_0009250 | 'Prorubricyte Count'
EFO_0009249 | 'Precursor Plasma Cell Count'
EFO_0009248 | 'Plasma Cell Count' 
EFO_0009247 | 'Ovalocyte Count' 
EFO_0009246 | 'Neutrophils Band Form to Neutrophils Ratio Measurement' 
EFO_0009245 | 'Neutrophilic Myelocyte Count' 
EFO_0009244 | 'Neutrophilic Metamyelocyte Count'
EFO_0009243 | 'Myeloid to Erythroid Ratio Measurement'

Other edits outlined in the previous comment are still to do.

**Comment by zoependlington** [comment]
Here's the ID for the new term:

EFO_0009253 || Immature Reticulocyte Fraction Measurement

All edits have now been made.
