### ISSUE TITLE
Import Hepatorenal syndrome from MONDO 

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#1914]
From my naive understanding of the disease, I couldn't find `Hepatorenal syndrome` (http://purl.obolibrary.org/obo/MONDO_0001382) or any equivalent term in EFO.

The drug terlipressin was approved in 2022 for patients with this indication. https://www.fda.gov/drugs/new-drugs-fda-cders-new-molecular-entities-and-new-therapeutic-biological-products/novel-drug-approvals-2022

**Comment by zoependlington** [comment]
MONDO:0001382 has been imported into EFO and will be available after the February (15th) release.
