### ISSUE TITLE
New term request for Tsepilov PMID:32587327

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1918]
For new term requests, please provide the following information:

## Preferred term label

chronic musculoskeletal pain

## Synonyms

NA

## Textual definition

A chronic pain phenotype that originates in the bones, muscles, tendons or ligaments

## Suggested parent term

Chronic pain http://purl.obolibrary.org/obo/HP_0012532

## Attribution

NA

**Comment by zoependlington** [comment]
Added as EFO_0022195 which will be available after our February release.
