### ISSUE TITLE
Import Cold Agglutinin Disease from MONDO 

### ISSUE THREAD

**Issue by polrus** [EBISPOT/efo#1919]
One more indication that is absent - "cold agglutinin disease" (MONDO:0018922), I didn't find the term in EFO.

[Sutimlimab](https://www.fda.gov/drugs/news-events-human-drugs/fda-approves-treatment-adults-rare-type-anemia) was approved for this indiction in 2022.

**Comment by zoependlington** [comment]
Term has been imported and will be available after our February (15th) release.
