### ISSUE TITLE
Platelet indices (measurements) preferred name and missing measurements

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#192]
Platelet (PLT) indices including PLT count, mean platelet volume (MPV), platelet distribution width (PDW), platelet large cell ratio (P-LCR) and plateletcrit (PCT).

### Platelet crit
http://www.ebi.ac.uk/efo/EFO_0007985

### Platelet larger cell ratio
Not in EFO

### Platelet component distribution width
http://www.ebi.ac.uk/efo/EFO_0007984
http://purl.obolibrary.org/obo/NCIT_C111294

### Immature platelet fraction
Not in EFO

### platelet crit 
PCT
platelet crit (PCT)
plateletcrit (PCT)
plateletcrit

### platelet larger cell ratio
Platelet larger cell ratio
platelet larger cell ratio (P-LCR) 
P-LCR

### Platelet component distribution width
Platelet Component Distribution Width Measurement
PCDW
Platelet distribution width

### Immature platelet fraction
IPF

### platelet crit
Volume occupied by platelets in the blood (percentage)

### platelet large cell ratio
Indicator of larger (> 12 fL) circulating platelets (percentage)

### Platelet component distribution width
The determination of the amount of platelet shape changes present in a sample. [ NCI ]

### Immature platelet fraction
Percentage of immature platelets

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0005036

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT 1** platelet crit (EFO:0007985)
     - Change label from plateletcrit to platelet crit
     - **Synonym:** PCT || platelet crit (PCT) || plateletcrit (PCT) || plateletcrit
     - **Definition:** Volume occupied by platelets in the blood (percentage)

- [ ] **EFO:NEW1** platelet larger cell ratio
     - Subclass of platelet measurement (EFO:0005036)
     - **Synonym:** Platelet larger cell ratio || platelet larger cell ratio (P-LCR) || P-LCR
     - **Definition:** Indicator of larger (> 12 fL) circulating platelets (percentage)

- [ ] **EFO:EDIT 2** platelet distribution width (EFO:0007984)
     - Change name to platelet component distribution width
     - Subclass of platelet measurement (EFO:0005036)
     - **Synonym:** Platelet Component Distribution Width Measurement || PCDW || Platelet distribution width
     - **Definition:** The determination of the amount of platelet shape changes present in a sample. [ NCI ]
     - **X-refs:** NCIT:C111294

- [ ] **EFO:NEW2** immature platelet fraction
     - Subclass of platelet measurement (EFO:0005036)
     - **Synonym:** IPF
     - **Definition:** Percentage of immature platelets

**Comment by zoependlington** [comment]
The new EFO IDs are:
EFO_0009186 || platelet larger cell ratio
EFO_0009187 || immature platelet fraction

**Comment by gkos-bio** [comment]
Thanks!
