### ISSUE TITLE
New term request for Faber, PMID 36662418

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1933]
For new term requests, please provide the following information:

## Preferred term label

alpha angle

## Textual definition

A measure of femoral head sphericity.

## Suggested parent term

[osteoarthritis biomarker measurement](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005890#)

## Further info

"a non-spherical femoral head and has been associated with hip osteoarthritis "
"higher AA was associated with hip pain "
"Further sensitivity analyses were performed defining cam morphology as an AA ≥60o"

**Comment by zoependlington** [comment]
Term added as EFO_0020071, which will be available after the March (15th) release.
