### ISSUE TITLE
New term request for Kiiskinen PMID: 36653479

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1935]
For new term requests, please provide the following information:

## Preferred term label

Antihyperlipidemic use measurement

## Synonyms

NA

## Textual definition

Quantification of some aspects of the use of antihyperlipidemic drugs

## Suggested parent term

drug use measurement http://www.ebi.ac.uk/efo/EFO_0007010

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term created as **EFO:0803367** and will be made available after the March (15th) release.
