### ISSUE TITLE
New term request for Haghighatfard PMID 36566681

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1939]
For new term requests, please provide the following information:

## Preferred term label

internet addiction disorder

## Textual definition

An online-related compulsive behaviour which interferes with healthy living, resulting in significant impairment to various life domains over a prolonged period of time.

## Suggested parent term

[mental or behavioural disorder](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000677&lang=en&viewMode=All&siblings=false#)

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803368** and will be made available after the March (15th) release.
