### ISSUE TITLE
high-level copy number loss

### ISSUE THREAD

**Issue by ahwagner** [EBISPOT/efo#1941]
Tagging @mbaudis for his comments on this request and the distinction between this and Complete Genomic Deletion ([EFO_0030069](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030069&lang=en&viewMode=All&siblings=false))

## Preferred term label
high-level copy number loss

## Synonyms
high-level loss, focal loss

## Textual definition
Assessment of high-level copy loss. High-level loss is associated with a large negative log ratio between the ploidy at an indicated position and regional base ploidy. High-level loss is typically indicative of focal deletions. This term should be preferred in contrast to Complete Genomic Deletion ([EFO_0030069](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030069&lang=en&viewMode=All&siblings=false)) when a complete loss of all alleles at an indicated position cannot be reasonably assessed.

## Suggested parent term
Copy Number Loss ([EFO_0030067](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030067&lang=en&viewMode=All&siblings=false))

## Attribution
https://orcid.org/my-orcid?orcid=0000-0002-2502-8961

**Comment by mbaudis** [comment]
@ahwagner @zoependlington Maybe a use case hint? Reformulate to your liking ...

"... High-level loss is typically indicative of focal deletions. The term should be preferred in contrast to Complete Genomic Deletion ([EFO_0030069](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030069&lang=en&viewMode=All&siblings=false)) when a complete loss of all alleles at an indicated position cannot be reasonably assessed."

**Comment by ahwagner** [comment]
@mbaudis I think that sounds good. Added to the definition.

**Comment by mbaudis** [comment]
Great! A thought: Shouldn't [EFO_0030069](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0030069&lang=en&viewMode=All&siblings=false) be then become a child term of this, to allow proper term expansion? Or is this restricted to "most of many" copies (e.g. repeats)?

**Comment by ahwagner** [comment]
I think it would make sense to make EFO_0030069 a child term.

**Comment by mbaudis** [comment]
👏

**Comment by mbaudis** [comment]
@zoependlington So the agreement here is to do an insertion:

```
EFO:0030067 (copy number loss)
  |
  |- EFO:0030068 (low-level copy number loss)
  \- EFO:nnnnnnn (high-level copy number loss)
       |
       \- EFO:0030069 (complete genomic deletion)
```

**Comment by zoependlington** [comment]
@mbaudis Thank you! I'll get this done for the April release (17th).

**Comment by zoependlington** [comment]
Term has now been added as EFO:0020073 and edits to the hierarchy made, all of which will be available after the April release.
