### ISSUE TITLE
New term request for Currant PMID:36848389 (WC_22030307)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1944]
4 terms:

https://docs.google.com/spreadsheets/d/1_A1nvVPGmocydGTgo6KiBICC51AaIJ47/edit#gid=1916273582

**Comment by ar-ibrahim** [comment]
* *added **4** new 'retinal thickness measurement' terms _(3 'photoreceptor thickness measurement' subclasses)_

**Comment by ar-ibrahim** [comment]
The terms [Robot template-issue 1944](https://docs.google.com/spreadsheets/d/1_A1nvVPGmocydGTgo6KiBICC51AaIJ47/edit#gid=1320404540) will be made available after the May (15th) release.
