### ISSUE TITLE
New term request for Libiseller-Egger PMID 36587059

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1949]
For new term requests, please provide the following information:

## Preferred term label

cardiovascular age measurement

## Textual definition

Quantification or estimate of cardiovascular age, e.g. as derived from electrocardiogram.

## Suggested parent term

cardiovascular measurement

## more info: 
The GWAS trait is: Delta age (difference between ECG-predicted and chronological age).
I am requesting this EFO because I see a similar trait "Brain age (difference between predicted and chronological age)" uses an EFO of 'brain age measurement'. 
But maybe there's a case to create a broad 'predicted age measurement' instead/as well?

**Comment by ar-ibrahim** [comment]
@zoependlington I'm creating the term 'cardiovascular age measurement' but what do you think about Lizzy's suggestion of also creating a superclass 'predicted age measurement'?

**Comment by zoependlington** [comment]
I think 'predicted age measurement' makes sense to include all 'x age measurement' terms as subclasses too. Happy to have it added.

**Comment by ar-ibrahim** [comment]
The term **cardiovascular age measurement** was created as **EFO:0803380** and will be available after the May (15th) release.
