### ISSUE TITLE
Toxic Nodular Goiter, Thyrotoxicosis, Hyperthyroidism and Hypothyroidism

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#195]
The classification of thyroid diseases, especially the overactivity of the thyroid gland can be improved.
Several subtypes are missing from the ontology.

### Thyrotoxicosis
Missing from EFO

### Hyperthyroidism
Missing from EFO (while hypothyroidism is defined)

### Rare Hyperthyroidism
in EFO but should be connected to Hyperthyroidism

### Plummer's disease / Toxic Nodular Goiter
is missing in EFO (while nodular goiter is defined)

### Toxic Nodular Goiter
Plummer's disease
Plummer disease

### Hyperthyroidism
http://purl.obolibrary.org/obo/NCIT_C3123
http://purl.obolibrary.org/obo/DOID_7998
http://purl.obolibrary.org/obo/MONDO_0004425

### Thyrotoxicosis
http://purl.obolibrary.org/obo/MONDO_0010138
http://purl.obolibrary.org/obo/DOID_7997
http://purl.obolibrary.org/obo/NCIT_C61469

### Toxic Nodular Goiter
http://purl.obolibrary.org/obo/DOID_11277

### Hyperthyroidism
Overactivity of the thyroid gland resulting in overproduction of thyroid hormone and increased metabolic rate. Causes include diffuse hyperplasia of the thyroid gland (Graves' disease), single nodule in the thyroid gland, and thyroiditis. The symptoms are related to the increased metabolic rate and include weight loss, fatigue, heat intolerance, excessive sweating, diarrhea, tachycardia, insomnia, muscle weakness, and tremor. [ NCI ]

### Thyrotoxicosis
A hypermetabolic syndrome caused by the elevation of thyroid hormone levels in the serum. Signs and symptoms include tachycardia, palpitations, tremor, weight loss, warm weather intolerance, and moist skin. Causes include Graves disease, toxic nodular goiter, toxic thyroid nodule, and lymphocytic thyroiditis. [ NCI ]

## Suggested parent term

Hyperthyroidism => thyroid disease
Rare Hyperthyroidism => Hyperthyroidism
Rare Hypothyroidism => hypothyroidism
Toxic Nodular Goiter => Hyperthyroidism
Toxic Nodular Goiter => nodular goiter

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Look like most of these terms would be taken care of by the MONDO-EFO integration and the release of EFO 3 planned for mid-September. Please let us know if that is too late, and if so, we'll try to fix before then. Thanks!

**Comment by gkos-bio** [comment]
This should be OK for September.
I wanted to provide examples where the MONDO-EFO integration can be tested.
Please check what is in MONDO first because this might not generate the 'best' classification.

**Comment by zoependlington** [comment]
Here are the IDs of the new terms:
EFO_0009191 || Toxic Nodular Goiter
EFO_0009190 || Thyrotoxicosis
EFO_0009189 || Hyperthyroidism
