### ISSUE TITLE
New term request for Shaqiri PMID 36585402

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1950]
For new term requests, please provide the following information:

## Preferred term label

visual masking measurement

## Textual definition
Quantification of visual masking - when the visibility of one image is reduced by the presence of another. Timing arrangements include forward masking, backward masking, and simultaneous masking. Spatial arrangements include pattern masking and metacontrast.
## Suggested parent term

visual perception measurement

## endophenotype:
schizophrenia

**Comment by ar-ibrahim** [comment]
The term was added as **EFO:0803378** and will be made available after the May (15th) release.
