### ISSUE TITLE
New Term Request for Open Targets

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#1951]
For new term requests, please provide the following information:

## Preferred term label

Neuroinflammatory Disorders

## Synonyms

Neuroinflammatory Diseases

## Textual definition

A group of immune-mediated disorders of the central nervous system (brain, spinal cord and optic nerves).  Multiple Sclerosis (MS) is the best-known neuroinflammatory disease. Alzheimer’s disease (AD), Parkinson’s disease (PD), and other neurodegenerative diseases are all related to neuroinflammation. 

## Suggested parent term

(http://www.ebi.ac.uk/efo/EFO_0009386)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Hi @buniello, would MONDO_0000568 (autoimmune disorder of central nervous system) be acceptable for this term? Currently multiple sclerosis listed in the definition is a child of this Mondo term:

<img width="476" alt="image" src="https://user-images.githubusercontent.com/36990116/225068651-43eb4588-b5f7-4f65-b112-5b558dff0b82.png">

**Comment by buniello** [comment]
Hi @zoependlington, could "neuroinflammatory disorders" be added to the synonyms at least? It would be important for our search to capture it, as ultimately the targets will need to be associated with neuroinflammatory disorders (capturing a cell-to-human phenotype from an experimental setting).

**Comment by buniello** [comment]
Hi @zoependlington, I discussed this term with the team and also with the CRISPR data experts/providers, and they all would like to use the "Neuroinflammatory Disorders" term to capture our cell type-disease-target associations in the platform.
Would it be a real problem to create a new EFO term for us, as requested? Thanks!

**Comment by buniello** [comment]
thank you @zoependlington!!
