### ISSUE TITLE
New term request for Strippel PMID 35348614

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1957]
For new term requests, please provide the following information:

## Preferred term label

anti-GAD65 autoimmune neurological syndromes

## Synonyms

autoimmune neurological syndromes with anti-65kDa isoform of the glutamic acid decarboxylase autoantibodies, 
AINS with anti-GAD65 autoantibodies 

## Textual definition

Autoimmune neurological syndromes (AINS) with autoantibodies against the 65kDa isoform of the glutamic acid decarboxylase (GAD65), eg. limbic encephalitis, cerebellitis with ataxia, and stiff-person-syndrome. 

## Suggested parent term

autoimmune disease

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803379** and will be available after the May (15th) release.
