### ISSUE TITLE
Import Lambert-Eaton myasthenic syndrome from Orphanet

### ISSUE THREAD

**Issue by polrus** [EBISPOT/efo#1959]
Hello!
I couldn't find any **[Lambert-Eaton myasthenic syndrome](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_43393&lang=en&viewMode=All&siblings=false)** or any equivalent term in EFO or MONDO.

AMIFAMPRIDINE was approved for this indication in 2018.

**Comment by zoependlington** [comment]
As we do not import from Orphanet (although historical Orphanet terms do exist in EFO), this term has been added as EFO:0020094, which will be available after the April release.
