### ISSUE TITLE
knee pain

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#196]
## Preferred term label

knee pain

## X-refs
http://purl.obolibrary.org/obo/HP_0030839

## Textual definition

An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) localized to the knee. [ UToronto:chum ]

## Suggested parent term

knee pain => pain

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] **EFO:IMPORT** knee pain (HP_0030839)
     - Subclass of pain (EFO_0003843)
     - **Definition:** An unpleasant sensation characterized by physical discomfort (such as pricking, throbbing, or aching) localized to the knee. [ UToronto:chum ]
     - **X-ref:** UMLS:C0231749 || SNOMEDCT_US:30989003

**Comment by zoependlington** [comment]
Here's the ID of the imported term:
HP_0030839 || knee pain
