### ISSUE TITLE
New term request for Young PMID:36918541

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#1964]
For new term requests, please provide the following information:

## Preferred term label

QRS-T angle

## Synonyms

NA
## Textual definition

An electrocardiogram‐derived measure of the difference in mean vectors of depolarization and repolarization

## Suggested parent term

electrocardiography http://www.ebi.ac.uk/efo/EFO_0004327

## Attribution

NA

**Comment by zoependlington** [comment]
Term added as EFO_0020097, which will be available after the April release (17th).
