### ISSUE TITLE
New term request for Klimentidis PMID 36385154

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1966]
For new term requests, please provide the following information:

## Preferred term label

lipidema

## Textual definition

Lipidema is a common disorder characterised by excessive build-up of fat in the lower body, mainly occurring in adult women. 

## Suggested parent term

chronic disease?

**Comment by zoependlington** [comment]
I have imported MONDO_0013577 (lipedema), which will be available after the May release.
