### ISSUE TITLE
New term request for Koel PMID 36929174

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#1968]
For new term requests, please provide the following information:

## Preferred term label

cervical ectropion

## Textual definition

Cervical ectropion occurs when eversion of the endocervix exposes columnar epithelium to the vaginal milieu

## Suggested parent term
cervix disorder:
http://purl.obolibrary.org/obo/MONDO_0002256

## existing in HP: 
https://www.ebi.ac.uk/ols4/ontologies/hpi/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0030158

**Comment by zoependlington** [comment]
I have imported the HP term into EFO. This will be available after out May release.
