### ISSUE TITLE
New term request: PacBio Sequel II System

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#1976]
## Preferred term label

PacBio Sequel II System

## Synonyms

Pacific BioSciences Sequel II

## Textual definition

The PacBio Sequel II System is a high-throughput long-read sequencing machine developed by PacBio.

## Suggested parent term

EFO:0002699

## Attribution
N/a

## Other notes
Vendor website available at: https://www.pacb.com/technology/hifi-sequencing/sequel-system/
Related to EFO:0008630 (earlier generation Sequel System.)
Term present in OBI as OBI:0002633.

**Comment by bvarner-ebi** [comment]
@jenjou, thank you for the new term.

EFO:0700015 'PacBio Sequel II system' has been added to EFO and will be available in the next release.
Details can be viewed in #1979.

**Comment by jenjou** [comment]
Thank you for the quick turnaround!
