### ISSUE TITLE
Parentage/redundancy of Unipolar Depression (EFO_0003761)

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#1978]
I noticed that [Unipolar depression (EFO_0003761)](http://www.ebi.ac.uk/efo/EFO_0003761) is not placed as a descendant of [depressive disorder (MONDO_0002050)](http://purl.obolibrary.org/obo/MONDO_0002050) and instead listed as a high-level mood disorder. I think the depressive parent would fit better.

On a related note, is EFO_0003761 now redundant with [major depressive disorder (MONDO_0002009)](http://purl.obolibrary.org/obo/MONDO_0002009) that's already in EFO? Seems like merging them and obsoleting EFO_0004247  would be appropriate as they have near-identical synonyms. 

## Suggested parent term

[depressive disorder (MONDO_0002050)](http://purl.obolibrary.org/obo/MONDO_0002050)
## Attribution

0000-0001-8222-008X

**Comment by zoependlington** [comment]
Thanks for catching this @smlmbrt! I've made changes to our imports and mappings files to make the two terms equivalent and merged into [Unipolar depression (EFO_0003761)](http://www.ebi.ac.uk/efo/EFO_0003761) so it now sits under depressive disorder and there should no longer be any duplications. These changes will appear after our April (17th) release. Please don't hesitate to get in touch if you spot any issues remaining here.
