### ISSUE TITLE
Missing descendant/ancestor information in efo.owl

### ISSUE THREAD

**Issue by Elysheba** [EBISPOT/efo#199]
When parsing the efo.owl file provided on github (version 2.97), I noticed that not all subClass information is available in this file compared to the efo.obo file.

For example, when identifying all descendants of the “disease” term (“EFO:0000408”), descendants EFO:1001221, EFO:1001866, and EFO:0009065 are missing compared to the efo.obo file. 

Additionally, the parent information of “EFO:0003769" and "EFO:0002916" (among others) seems to be  partly missing in the efo.owl file while they are correctly listed in the efo.obo and on https://www.ebi.ac.uk/ols/ontologies/efo/

**Comment by zoependlington** [comment]
Thanks for your ticket! The efo.owl file is non-inferred and so a reasoner must be run to observe the inferred view. We do release an inferred owl file (efo_inferred.owl), which should have all inferred subClass and parent information available. I have checked all of the examples you have given and all of the information is available in the inferred file, efo_inferred.owl, and when a reasoner has been run over the original efo.owl file.
