### ISSUE TITLE
NTR: Smart-seq4

### ISSUE THREAD

**Issue by liaanym** [EBISPOT/efo#1991]
## Preferred term label
SMART-Seq v4

## Synonyms

Smart-seq2
Smart-like
Smart-3Seq

## Textual definition

Library construction method using the SMART (Switching Mechanism at the 5' end of the RNA Template) to generate high-quality cDNA from ultra-low amounts of total RNA or directly from multiple intact cells (<1,000 cells). Improves upon the SMART-Seq2 method by incorporating both the novel use of locked nucleic acid (LNA) technology into an optimized template switching oligo.

## Suggested parent term

Smart-like, RNA assay

## Attribution

https://orcid.org/0000-0002-7423-6054

**Comment by bvarner-ebi** [comment]
Hi, @liaanym, thank you for the new term.

- Can you provide an external reference (PMID or doi) for this term?

- For the listed synonyms, those terms already exist in EFO as classes and one is the suggested parent class (Smart-like). If this new term is placed under Smart-like, Smart-seq2 and Smart-3Seq would be sibling classes.

**Comment by liaanym** [comment]
Hi @bvarner-ebi! Here is the information below. I apologize, I did not put the correct terms for synonyms.

- external reference: Here is a manual: https://www.takarabio.com/a/114896#:~:text=The%20SMART%2DSeq%20v4%20Ultra,volume%20of%201%E2%80%9310%20%C2%B5l. 
- synonyms: Smart-Seq v4

**Comment by bvarner-ebi** [comment]
Thank you for the clarifications, @liaanym.
Looking at similar terms in the ontology, they have parent class assay (not 'RNA assay') with the label using the lower case styling.

Unless you have concerns, I'll continue this pattern:

label: Smart-seq v4
exact synonym: 'SMART-Seq v4'
parent classes: assay, Smart-like.
