### ISSUE TITLE
import ChEBI terms to EFO for OTAR metabolon data

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#20]
some known metabolites that already exist in ChEBI but not in EFO need to be imported to EFO
[EFO_ChEBIimport.xlsx](https://github.com/EBISPOT/efo/files/1430938/EFO_ChEBIimport.xlsx)

**Comment by simonjupp** [comment]
terms in red are where there isn't an exact mapping to a chebi term. 

- [ ] import Chebi terms that have a good mapping
- [ ] add metabalon label to Zooma openTargets datasource 
- [ ] submit unmapped terms to Chebi

**Comment by zoependlington** [comment]
@simonjupp According to @siiraa Gautier is chasing this ticket. Sira is asking for it to be done in the next sprint.

**Comment by zoependlington** [comment]
The list of terms has been sorted in a Webulous template for importing and non-mapped terms are included in a separate sheet here:
https://docs.google.com/spreadsheets/d/1AQBVPRSNlBDBiaQbEXZ05RnnxGlLrWvxIFnTaf62Atk/edit?usp=sharing

**Comment by paolaroncaglia** [comment]
I think that the problem with (at least some) unmapped Metabolon terms is that chemical labels often have synonyms that are quite diverse from the primary labels, so a lexical search may not always work well, and it may catch the conjugate acid or base instead. That may depend on whether Zooma includes ChEBI synonyms or not, I'm thinking probably not, @simonjupp do you know? I'm looking manually at entries in the spreadsheet (https://docs.google.com/spreadsheets/d/1AQBVPRSNlBDBiaQbEXZ05RnnxGlLrWvxIFnTaf62Atk/edit?usp=sharing) and I’m finding that the specific base (or acid) term from Metabolon is often available in ChEBI. I’m adding those more precise ChEBI mappings to the spreadsheet.
