### ISSUE TITLE
New term request for Kim PMID 36707530

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2001]
For new term requests, please provide the following information:

## Preferred term label

fornix volume measurement

## UBERON
http://purl.obolibrary.org/obo/UBERON_0000052

## Textual definition

Quantification of the volume of the fornix. 

## Suggested parent term

brain volume measurement

**Comment by ar-ibrahim** [comment]
The term was created as **EFO:0803381** and will be available after the May (15th) release.
