### ISSUE TITLE
New term request for Schmidt PMID 37126556

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2005]
For new term requests, please provide the following information:

## Preferred term label

right ventricular function

## Synonyms

NA

## Textual definition

The hemodynamic and electrophysiological action of the right HEART VENTRICLE. Its measurement is an important aspect of the clinical evaluation of patients with heart disease to determine the effects of the disease on cardiac performance.

## Suggested parent term

function http://purl.obolibrary.org/obo/BFO_0000034

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803382** and will be available after the June (15th) release.

**Comment by zoependlington** [comment]
I've re-added this term as EFO_0020939, which will be available after today's release has completed.
