### ISSUE TITLE
New term request for Vukadinovic PMID:36996817

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2006]
For new term requests, please provide the following information:

## Preferred term label

Left ventricle sphericity index

## Synonyms

NA

## Textual definition

The sphericity index is defined as the ratio of LV short axis length divided by LV long axis length.

## Suggested parent term

cardiovascular measurement http://www.ebi.ac.uk/efo/EFO_0004298

## Attribution

**
The sphericity index (SI) is used to evaluate the shape of the right and left ventricles of the heart and is derived by calculating the ratio between the end-diastolic mid-basal–apical and transverse lengths.

**Comment by zoependlington** [comment]
Term added as EFO_0020938 which will be available after the June release.
