### ISSUE TITLE
New term request: ONT PromethION 2 Solo

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2008]
## Preferred term label

ONT PromethION 2 Solo

## Synonyms

ONT P2 Solo

## Textual definition

The ONT PromethION 2 Solo is a high-throughput, high-sample number benchtop sequencing machine developed by Oxford Nanopore Technologies.

## Suggested parent term

high throughput sequencer EFO:0002699

## Attribution

0000-0003-3065-9183

## Other info
Term is related to ONT PromethION EFO:0008634. 
Vendor page: https://store.nanoporetech.com/us/p2-solo.html

**Comment by bvarner-ebi** [comment]
@jenjou, thank you for the new term.
The text definition for this term is the same as EFO:0008634 'ONT PromethION'. Can you provide a distinguishing aspect/feature of 'ONT PromethION 2 Solo'?

**Comment by bvarner-ebi** [comment]
@jenjou, here is a description from https://community.nanoporetech.com/requirements_documents/promethion-2s-spec.pdf:

"The PromethION 2 Solo is a small benchtop device designed to run up to two PromethION flow cells. Each flow cell is independently addressable, meaning that experiments can be run concurrently or individually. The PromethION 2 Solo plugs into a GridION Mk1 or user compute for real-time data streaming and analysis."

and another description from
https://nanoporetech.com/products/promethion-2#tabs-0=p2Solo:

"A compact sequencer for two PromethION Flow Cells, utilising resource within the GridION or other suitable compute, including laptops, to quickly enable accurate, high-yield nanopore sequencing."

Would the following be accurate and acceptable:

**Text def:**
"The ONT PromethION 2 Solo is a compact modular sequencing unit developed by Oxford Nanopore Technologies that can run up to two PromethION flow cells and connect to ONT GridION Mk1 devices."

**Comment:**
"Each flow cell of the ONT PromethION 2 Solo is independently addressable, meaning that experiments can be run concurrently or individually. The PromethION 2 Solo plugs into a GridION Mk1 or user compute for real-time data streaming and analysis."

**Comment by jenjou** [comment]
Yes, I think that description is acceptable. Thank you for your help!

**Comment by bvarner-ebi** [comment]
@jenjou, thank you for the new term request.
The following has been added to EFO and will part of the next release:

EFO:0700017 'ONT PromethION 2 Solo'

Details can be found in [the linked PR](https://github.com/EBISPOT/efo/pull/2009).

**Comment by jenjou** [comment]
Thank you!
