### ISSUE TITLE
Robot form request for Davyson PMID 36764567

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2017]
Robot request form: https://docs.google.com/spreadsheets/d/1oW9DzzcB9_1llKpooqh2ONXrB8tw9Igl/edit?usp=sharing&ouid=115603389613071004022&rtpof=true&sd=true

I have requested these terms (eg. cholesterol in IDL measurement) because there are quite a few similar already existing, (eg. [triglycerides in IDL measurement](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0022149?lang=en))

The only codes I really have for them are UKB data fields (see https://biobank.ndph.ox.ac.uk/ukb/search.cgi) if these are useful. 

Please let me know any thoughts / problems.

**Comment by zoependlington** [comment]
All terms have been added and the IDs have been added to the Google sheet. They will be available after the August release (15th).
