### ISSUE TITLE
Two different concepts in glioblastoma multiforme EFO:0000519 

### ISSUE THREAD

**Issue by tjboller** [EBISPOT/efo#202]
The EFO term glioblastoma multiforme (EFO:0000519) has two concepts mixed in it - optic nerve glioblastoma and glioblastoma (multiforme)

## Preferred term label

**optic nerve glioblastoma**

**glioblastoma**

## Synonyms

**optic nerve glioblastoma**
- MeSH: https://meshb.nlm.nih.gov/record/ui?ui=D020339
- Synonyms

malignant optic nerve astrocytoma
optic glioma
optic nerve glioma

**Glioblastoma**
- MeSH: https://meshb.nlm.nih.gov/record/ui?name=GLIOBLASTOMA
- Synonyms: 

[m]glioblastoma nos (morphologic abnormality)
astrocytoma, grade iv
astrocytomas, grade iv
gbm
gbm (glioblastoma)
gbm - glioblastoma multiforme
giant cell glioblastoma
giant cell glioblastomas
glioblastoma
glioblastoma (morphologic abnormality)
glioblastoma nos (morphologic abnormality)
glioblastoma, giant cell
glioblastoma, no icd-o subtype
glioblastoma, no icd-o subtype (morphologic ab...
glioblastoma, nos
glioblastomas
glioblastomas, giant cell
glm - glioblastoma multiforme
grade iv astrocytic neoplasm
grade iv astrocytic tumor
grade iv astrocytoma
grade iv astrocytomas

**Comment by zoependlington** [comment]
Thanks @paolaroncaglia!

- [ ] **EFO:EDIT** glioblastoma multiforme (EFO:0000519)
     - **X-refs to add:** MONDO:0018177
     - **X-refs that need removing:** MSH:D020339 || NCIt:C4325 || NCIt:C4537 || OMIM:137800 || NIFSTD:birnlex_12621 
     - **X-refs that need editing:** NIFSTF:birnlex:12620 => ILX:0104645
     - **Synonyms:** [m]glioblastoma nos (morphologic abnormality) || astrocytoma, grade iv || astrocytomas, grade iv || gbm || gbm (glioblastoma) || gbm - glioblastoma multiforme || giant cell glioblastoma || giant cell glioblastomas || glioblastoma || glioblastoma (morphologic abnormality) || glioblastoma nos (morphologic abnormality) || glioblastoma, giant cell || glioblastoma, no icd-o subtype || glioblastoma, no icd-o subtype || glioblastoma, nos || glioblastomas || glioblastomas, giant cell || glm - glioblastoma multiforme || grade iv astrocytic neoplasm || grade iv astrocytic tumor || grade iv astrocytoma || grade iv astrocytomas

- [ ] **EFO:NEW** optic nerve glioblastoma
     - Subclass of optic nerve neoplasm (EFO:1001073)
     - Subclass of glioblastoma multiforme (EFO:0000519)
     - **X-refs:** MSH:D020339 || MONDO:0003235 || NIFSTD:birnlex_12621 **BUT CHANGED TO =>** ILX:0108071 || NCIt:C4537
     - **Definition:** Glial cell derived tumors arising from the optic nerve, usually presenting in childhood.
     - **Synonyms:** malignant optic nerve astrocytoma || optic glioma || optic nerve glioma

**Comment by zoependlington** [comment]
Here's the ID for the new term:

EFO_0009254 || optic nerve glioblastoma
