### ISSUE TITLE
New term request for Senkevich PMID 36370000

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2023]
For new term requests, please provide the following information:

## Preferred term label

blood galactosylceramidase activity measurement

## Textual definition

Quantification of the activity of galactosylceramidase, a lysosomal enzyme, in blood.

## Suggested parent term

blood protein measurement

## Other mappings:
GO: http://purl.obolibrary.org/obo/GO_0004336
KEGG: https://www.genome.jp/dbget-bin/www_bget?enzyme+3.2.1.46

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803535** and will be made available after the August (15th) release.
