### ISSUE TITLE
Add subclasses in cardiovascular measurement 

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/efo#2024]
I noticed that all the measurements relating to blood pressure and heart rate are not part of the "cardiovascular measurement" branch but a separate branch called "vital signs". Could all the terms under blood pressure EFO:0004325 and heart rate EFO:0004326 be added as subclasses in cardiovascular measurement EFO:0004298? This would help the way we classify measurements in the GWAS Catalog.

**Comment by zoependlington** [comment]
This will be available in our August (15th) release.
