### ISSUE TITLE
New term request for Xia PMID 37253732

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2028]
For new term requests, please provide the following information:

## Preferred term label

mitochondrial haplogroup carrier status

## Synonyms

NA

## Textual definition

Quantification of the presence or absence of mitochondrial haplogroup in an individual

## Suggested parent term

carrier status http://www.ebi.ac.uk/efo/EFO_0007658

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803532** and will be made available after the July (17th) release.
