### ISSUE TITLE
New term request for Vosberg PMID 37277458

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2035]
For new term requests, please provide the following information:

## Preferred term label

sexual dimorphism measurement

## Textual definition

Quantification of the phenotypic difference between males and females, eg within anthropometric or cardiometabolic traits. 

## Suggested parent term

measurement

## Further:
see discussion on Slack

**Comment by zoependlington** [comment]
Added as EFO_0021796, which will be available after the August release (15th)
