### ISSUE TITLE
New term request for Acharya PMID 37089073

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2036]
For new term requests, please provide the following information:

## Preferred term label

visuospatial function measurement

## Textual definition

Quantification of visuospatial function, one aspect of cognitive ability, tested by eg. block design or construction praxis.

## Suggested parent term

[mental or behavioural disorder biomarker](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0006848?lang=en)

[cognitive function measurement](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0008354?lang=en)

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803533** and will be made available after the July (17th) release.
