### ISSUE TITLE
Different creator annotation properties being used.

### ISSUE THREAD

**Issue by henrietteharmse** [EBISPOT/efo#2040]
EBISPOT/ols4#405 pointed out the issue with display of creator information in EFO. This is due to 2 different annotation properties being used in EFO, namely:

- `http://purl.org/dc/elements/1.1/creator` and
- `http://www.ebi.ac.uk/efo/creator`

Will it be possible to correct this?

**Comment by zoependlington** [comment]
Obsoleted the EFO minted term in favour of keeping http://purl.org/dc/elements/1.1/creator. This will be available after out December (18th) release.
