### ISSUE TITLE
New term request for Wang H PMID 36869385

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2041]
For new term requests, please provide the following information:

## Preferred term label

age of onset of colorectal cancer

## Textual definition

The age at which colorectal cancer manifestations first appear.

## Suggested parent term

http://purl.obolibrary.org/obo/OBA_2040153

## query

I also have a study for 'early onset colorectal cancer'. Do you think this term could be used for that as well, or another EFO should be made? Or use 'colorectal cancer'?

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050327 (age of onset of colorectal cancer)** and will be made available following the upcoming OBA release and EFO patch release 3.57.1.
