### ISSUE TITLE
[HCA] Request new term: BGI MGISEQ-2000

### ISSUE THREAD

**Issue by arschat** [EBISPOT/efo#2042]
For new term requests, please provide the following information:

## Preferred term label

BGI MGISEQ-2000

## Synonyms

No synonyms

## Textual definition

MGISEQ-2000 is a BGI's NGS sequencer based on the DNA nanoball technology.

Taken from [here](https://www.frontiersin.org/articles/10.3389/fgene.2021.730519/full)
First described [here](https://www.biorxiv.org/content/10.1101/754671v2.full)

## Suggested parent term

[EFO:0002699 - high throughput sequencer](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0002699)

## Attribution

0000-0002-0608-0553

**Comment by bvarner-ebi** [comment]
Hi, @arschat, thank you for the new term request.

Please see the proposed revised text definition below and please share feedback if any:

A next-generation sequencing (NGS) sequencer from Beijing Genomics Institute (BGI) based on DNA nanoball (DNB) and probe-anchor synthesis (cPAS) technology, which were also used in the previous version of the BGISEQ-500 device; however, the reagents for MGISEQ-2000 have been refined and the platform utilizes updated software."

doi:[10.1371/journal.pone.0230301](https://doi.org/10.1371/journal.pone.0230301)
doi:[10.3389/fgene.2021.730519](https://doi.org/10.3389/fgene.2021.730519)
doi:[10.1101/754671](https://doi.org/10.1101/754671)

**Comment by arschat** [comment]
Hi @bvarner-ebi, I agree, this definition is much more accurate. Thank you!

**Comment by bvarner-ebi** [comment]
@arschat, thank you again for the new term.
The following has been added to EFO and will be available in the next release:

EFO:0700018 'BGI MGISEQ-2000'
