### ISSUE TITLE
New term request for Mu PMID: 36867504

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2046]
For new term requests, please provide the following information:

## Preferred term label

response to apixaban

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of apixaban stimulus

## Suggested parent term

response to anticoagulant http://purl.obolibrary.org/obo/GO_0061476

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050328 (trait in response to apixaban)** and will be made available following the upcoming OBA release and EFO patch release 3.57.1.
