### ISSUE TITLE
New term request for Yasukochi PMID:36890596

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2050]
For new term requests, please provide the following information:

## Preferred term label

cold-induced vasodilation

## Synonyms
CIVD

## Textual definition

Cold-induced vasodilation (CIVD) is an acute increase in peripheral blood flow observed during cold exposures

## Suggested parent term

response to cold http://purl.obolibrary.org/obo/GO_0009409

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803534** and will be made available after the July (17th) release.
