### ISSUE TITLE
New term request for Alonso PMID: 36941031

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2053]
For new term requests, please provide the following information:

## Preferred term label

response to teriparatide

## Synonyms

NA

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of teriparatide. Teriparatide is a form of parathyroid hormone used in the treatment of some forms of osteoporosis.

## Suggested parent term

response to stimulus, GO_0050896

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050330 (trait in response to teriparatide)** and will be made available following the upcoming OBA release and EFO patch release 3.57.1.
