### ISSUE TITLE
Update EFO PURLs to point to OLS4 instead of OLS3

### ISSUE THREAD

**Issue by ghost** [EBISPOT/efo#2057]
EFO PURLs, e.g., http://www.ebi.ac.uk/efo/EFO_0009899, still point to OLS3. 

The PURLS for CL and Uberon have been updated to point to OLS4. Can this update be applied to EFO PURLs as well?

FYI @udp.

**Comment by zoependlington** [comment]
This is now resolved, all PURLs direct to OLS4
