### ISSUE TITLE
New term request for Jokubaitis PMID 36448302

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2058]
For new term requests, please provide the following information:

## Preferred term label

multiple sclerosis symptom measurement

## Textual definition

Quantification of some aspect of multiple sclerosis symptoms, e.g. using the Expanded Disability Status Scale.

## Suggested parent term

measurement

## disease
multiple sclerosis

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803536** and will be made available after the August (15th) release.
