### ISSUE TITLE
Review the definition of "MRE-seq" EFO:0003748

### ISSUE THREAD

**Issue by sherinpumc** [EBISPOT/efo#2060]
Hi!

In MRE-seq, the methylation sensitive restriction enzymes  digest genome DNA at unmethylated CpGs （Ref: [https://link.springer.com/protocol/10.1007/978-1-4939-7481-8_12](url) and [https://www.ebi.ac.uk/ols/ontologies/enm/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001861](url) )

Could you please review this definition?

Thank you very much!

**Comment by zoependlington** [comment]
Thank you. The definition has been revised and will be available after the 18th December release.
