### ISSUE TITLE
New term request for Gelemanovic PMID 37108169

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2069]
For new term requests, please provide the following information:

## Preferred term label

susceptibility to influenza measurement

## Textual definition

Quantification of an individual's susceptibility to influenza.

## Suggested parent term

(https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0006841?lang=en#:~:text=respiratory-,disease,-biomarker%20(29))

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803537** and will be made available after the August (15th) release.
