### ISSUE TITLE
New term requests and enrichment of existing EFO terms

### ISSUE THREAD

**Issue by kalpanaps** [EBISPOT/efo#2070]
https://docs.google.com/spreadsheets/d/1XRZn9uy9Jj0phBn0pyzvA_NxEqWnYcsJKOGUpMzUy5A/edit#gid=807097440

ORCID: 0000-0003-2534-198X

**Comment by zoependlington** [comment]
All terms have been added in the above spreadsheet, the IDs are available on each sheet also. Terms will be available after the September (18th) release.

**Comment by kalpanaps** [comment]
Thank you!
