### ISSUE TITLE
New Robot form request for Zhao PMID 37563310

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2079]
https://docs.google.com/spreadsheets/d/1PytAoNq9B4aov0EMTdArDHHs6lh_puj9TwbkjwWGhDM/edit?usp=sharing

- 4 terms
- measured in plasma
- circulating inflammatory proteins
- Codes and names from Supplementary Table 2.

**Comment by ar-ibrahim** [comment]
ID | Term 
-- | --
OBA:2050334 | level of neurturin in blood plasma
OBA:2050335 | level of interleukin-33 in blood plasma
OBA:2050336 | level of T-cell differentiation antigen CD6 in blood plasma
OBA:2050337 | level of eukaryotic translation initiation factor 4E-binding protein 1 in blood plasma



Terms will be made available following the upcoming OBA release and EFO patch release 3.57.1.
