### ISSUE TITLE
New term request and enrichment of existing terms

### ISSUE THREAD

**Issue by kalpanaps** [EBISPOT/efo#2084]
https://docs.google.com/spreadsheets/d/1Sq6TbZT4CoNlaFSS-u51R5L1xvkGJHqEMCwvz43gLRQ/edit#gid=0

**Comment by zoependlington** [comment]
All terms have been added and additional annotations added to existing terms. IDs are in the spreadsheet. All will be available after the February 15th release.

**Comment by kalpanaps** [comment]
Thank you, Zoë
___________________
Kalpana Panneerselvam

IntAct-Lead
European Bioinformatics Institute (EMBL-EBI)
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***

**Comment by kalpanaps** [comment]
Thank you:)
___________________
Kalpana Panneerselvam

IntAct-Lead
European Bioinformatics Institute (EMBL-EBI)
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***
