### ISSUE TITLE
Duplicated EFO terms

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2086]
3 terms with duplicated IDs:
Fms-related tyrosine kinase 3 ligand measurement: http://www.ebi.ac.uk/efo/EFO_0010594
fms related receptor tyrosine kinase-3 ligand measurement: http://www.ebi.ac.uk/efo/EFO_0010785

interleukin 1 alpha measurement: http://www.ebi.ac.uk/efo/EFO_0009412
interleukin-1 alpha measurement: http://www.ebi.ac.uk/efo/EFO_0802653

interleukin 12 receptor subunit beta-1 measurement: http://www.ebi.ac.uk/efo/EFO_0008170
interleukin-12 receptor subunit beta-1 measurement: http://www.ebi.ac.uk/efo/EFO_0801715

**Comment by Santhi1901** [comment]
Found some more terms where definitions are incorrect.It is present in this form marked green: https://docs.google.com/spreadsheets/d/11pomvATVM5ZZH64OMluNrYdlRVqYXClLcWucDQ1kt-M/edit#gid=1946907454

**Comment by ar-ibrahim** [comment]
Ok thank you for flagging those terms Santhi!
