### ISSUE TITLE
New term request for Boahen PMID: 36865558

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2087]
For new term requests, please provide the following information:

## Preferred term label

interleukin-12 subunit beta measurement

## Synonyms

IL-12B

## Textual definition

Quantification of interleukin-12 subunit beta in blood

## Suggested parent term

protein measurement http://www.ebi.ac.uk/efo/EFO_0004747

## Attribution

NA

**Uniprot id: P29460

**Comment by ar-ibrahim** [comment]
- Created term in OBA.
- Will obsolete existing EFO term [EFO:0010787 interleukin-12 subunit B measurement](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0010787)
