### ISSUE TITLE
New Robot form for Akbari - PMID 37596262

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2090]
Robot form for 10 haematological measurement terms:
https://docs.google.com/spreadsheets/d/1RkvOzibWiQ8BtPO4FsiEb-6M-c87VmxXxNvZq1YPbew/edit?usp=sharing

(second tab is curator mapping to reported trait.)
Open to any comments or suggestions! ty

From text:
Here, we report the first large-scale GWAS of flow-cytometry measured non-classical CBC (ncCBC) traits (Fig. 1a–e). We call these phenotypes ncCBC traits because they were acquired using a haema- tology analyser, the Sysmex XN-1000, but are not included in standard cCBC reports (Fig. 1f). The XN-1000 analyser contains a flow-cyt- ometer, which can detect variation in the intracellular organelle com- plexity of cells from the intensity of SSC diffracted light. It can also detect variation in the nucleic acid content and membrane perme- ability of cells from the fluorescence intensity (SFL) of light emitted by a cell staining dye and variation in the size of cells from the intensity of forward scattered (FSC) diffracted light (Fig. 1a–e). The analyser reports individual level summaries of the cell level distributions of SSC, SFL and FSC intensity measurements (as averages or distribution widths over a set of cells of a given type). These phenotypes can cap- ture variation in biological processes with functional or clinical relevance7,9,20.

**Comment by ar-ibrahim** [comment]
[Terms](https://docs.google.com/spreadsheets/d/1RkvOzibWiQ8BtPO4FsiEb-6M-c87VmxXxNvZq1YPbew/edit#gid=1890695633) were added to EFO and will be made available following the October (16th) release.
