### ISSUE TITLE
New Term for Zhu PMID: 33589836

### ISSUE THREAD

**Issue by JMAStough** [EBISPOT/efo#2101]
For new term requests, please provide the following information:

## Preferred term label

Paired-Tag

## Synonyms

N/A

## Textual definition

An ultra-high throughput method, Paired-Tag, for joint profiling of histone modifications and transcriptome in single cells to produce cell-type-resolved maps of chromatin state and transcriptome in complex tissues. [PMID: 33589836]

## Suggested parent term

ChIP-Seq http://www.ebi.ac.uk/efo/EFO_0002692

## Attribution

N/A

**Comment by zoependlington** [comment]
Added as EFO_0022491, which will be available after the January (15th) release.
