### ISSUE TITLE
NTR for snm3C-seq

### ISSUE THREAD

**Issue by jychien** [EBISPOT/efo#2102]
## Preferred term label

snm3C-seq

## Synonyms

sn-m3C-seq

## Textual definition

A method to jointly profile chromatin conformation and cytosine DNA methylation from the same cell.

## Suggested parent term

[methylation profiling by high throughput sequencing](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0002761&lang=en&viewMode=All&siblings=false)
[single cell library construction](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010183&lang=en&viewMode=All&siblings=false)

## Attribution

https://orcid.org/0000-0003-4389-9821

## Reference
https://www.nature.com/articles/s41592-019-0547-z

**Comment by zoependlington** [comment]
Added as EFO_0022492, which will be available after the January (15th) release.
