### ISSUE TITLE
NTR: DNA extraction protocol

### ISSUE THREAD

**Issue by kdumschott** [EBISPOT/efo#2103]
For new term requests, please provide the following information:

## Preferred term label

DNA extraction protocol

## Textual definition

Nucleic acid extraction protocol that describes how to remove and purify DNA from an input material. This requires physical and/or chemical methods in order to separate the DNA from cell membranes, proteins and other cellular components.

## Suggested parent term

Would fit under nucleic acid extraction protocol (EFO:0002944) alongside RNA extraction protocol.

**Comment by zoependlington** [comment]
Added as EFO_0022384, which will be available after the October release.
