### ISSUE TITLE
NTR: protein extraction protocol

### ISSUE THREAD

**Issue by kdumschott** [EBISPOT/efo#2104]
For new term requests, please provide the following information:

## Preferred term label

protein extraction protocol

## Synonyms

(e.g., Absent spleen)

## Textual definition

A protocol that describes how to isolate protein from a tissue, cell culture or other biological samples.

## Suggested parent term

extraction protocol (EFO:0000490)

**Comment by zoependlington** [comment]
Added as EFO_0022383, which will be available after the October release.
