### ISSUE TITLE
New term request for Zhang PMID: 37659414 (WC_20230926)

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2105]
5 terms for various disease activity scores and responses to treatment 
https://docs.google.com/spreadsheets/d/1wqcCJSFCBO_J6YZq697FcJNEUj55B07H/edit#gid=1958068672

3 disease activity scores are available on NCIT

American College of Rheumatology Improvement Criteria: http://purl.obolibrary.org/obo/NCIT_C97995
Health Assessment Questionnaire Disability Index: http://purl.obolibrary.org/obo/NCIT_C132288
Psoriasis Area and Severity Index Clinical Classification: http://purl.obolibrary.org/obo/NCIT_C135734

**Comment by zoependlington** [comment]
Terms have been added as below and will be available after the October release (16th).

ID | measurement
-- | --
EFO_0022377 | Ankylosing spondylitis disease activity score
EFO_0022378 | response to secukinumab
EFO_0022379 | American College of Rheumatology Improvement Criteria
EFO_0022381 | Health Assessment Questionnaire Disability Index
EFO_0022382 | Psoriasis area and severity index
