### ISSUE TITLE
New term request for Verma PMID: 37345113

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2107]
For new term requests, please provide the following information:

## Preferred term label

Breast density

## Synonyms

NA

## Textual definition

The amount of fibroglandular versus fatty tissue in the breast. It is one of the strongest breast cancer risk factors

## Suggested parent term

measurement http://www.ebi.ac.uk/efo/EFO_0001444

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050351** and will be made available after the upcoming OBA and EFO releases.
