### ISSUE TITLE
New term request: chitotriosidase deficiency

### ISSUE THREAD

**Issue by apriltuesday** [EBISPOT/efo#2109]
FYI @zoependlington - This is the term occurring in ClinVar that was [deprecated](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0013586) as out of scope by Mondo, as discussed here's a ticket so we can figure out where to place it!

## Preferred term label
chitotriosidase deficiency

## Synonyms
CHITD

## Textual definition

Possible reference: [PMID:9748235](https://pubmed.ncbi.nlm.nih.gov/9748235/)

Also see [OMIM:614122](https://omim.org/entry/614122)

## Suggested parent term

Perhaps could be placed alongside other enzyme deficiencies?

## Attribution
N/A

**Comment by zoependlington** [comment]
Added as EFO_0022489 (under genetic disorder since in my research it seems to be that way - please do let me know if you disagree) which will be available after the December (18th) release.

**Comment by apriltuesday** [comment]
Sounds good, thank you so much!
