### ISSUE TITLE
Fix typo in label for congenital fibrosis of the extraocular muscles

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#211]
- EFO:1001985 has the label "congenital fibrosis of the extraocular musclesCongenital fibrosis of extraocular muscles". Should be just congenital fibrosis of the extraocular muscles with synonym of "Congenital fibrosis of extraocular muscles".

**Comment by S2Ola** [comment]
**Actions:** 
1. Removing the duplicates in the label of EFO:1001985 
2. Add the  synonym of "Congenital fibrosis of extraocular muscles".
