### ISSUE TITLE
New term request for Strausz PMID 37140068

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2117]
For new term requests, please provide the following information:

## Preferred term label

bruxism

## Existing in MONDO:
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0002443

## Textual definition

Excessive clenching of the jaw and grinding of the teeth.

## Suggested parent term

sleep disorder

**Comment by zoependlington** [comment]
Imported the Mondo term, which will be available after the 18th December release.
