### ISSUE TITLE
Request import of MONDO term to EFO

### ISSUE THREAD

**Issue by ala-ebi** [EBISPOT/efo#2118]
MONDO_0022880 (corticobasal degeneration) was obsoleted and replaced by MONDO_0022308 (corticobasal degeneration disorder), however, I cant find the latter in EFO, could you please import it to EFO?

Requested term to be imported to EFO:
MONDO_0022308 (corticobasal degeneration disorder)

**Comment by zoependlington** [comment]
This should now be rectified in the upcoming release (15th November). Please let me know if you come across any I have missed.
