### ISSUE TITLE
New term request for Ozeki PMID 37156394

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2119]
For new term requests, please provide the following information:

## Preferred term label

response to antidiabetic

## Textual definition

Any process that results in a change in state or activity of a cell or an organism as a result of an antidiabetic stimulus, for example dipeptidyl peptidase-4 inhibitors.

## Suggested parent term

response to drug

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050352** and will be made available after the next OBA and EFO releases.
