### ISSUE TITLE
New term request for "fecal microbiota transplantation"

### ISSUE THREAD

**Issue by lwaldron** [EBISPOT/efo#2125]
This term is in several other ontologies (https://www.ebi.ac.uk/ols4/search?q=fecal+microbiota+transplantation) and could be imported e.g. from MAXO:0000748 or NCIT:C118643. Only NCIT also has a subclass [autologous fecal microbiota transplantation](http://purl.obolibrary.org/obo/NCIT_C118644), which could be useful, but it looks like it imports from CTRP, which if I understand correctly is not in OLS).

## Preferred term label

fecal microbiota transplantation

## Synonyms

Union of NCIT:C118643 and MAXO:0000748 (although either one would be fine)

fecal material transplantation
fecal microbiota transplantation
fecal transplantation
FMT
poo transplant
poop transplant
stool transplant
stool transplantation

## Textual definition

The transplantation of fecal bacteria, via enema, colonoscopy, or other method, from a healthy individual to a recipient. 

(copied from MAXO:748 or NCIT:C118643)

## Suggested parent term

[medical procedure](http://www.ebi.ac.uk/efo/EFO_0002571)

**Comment by zoependlington** [comment]
Added as EFO_0022844, which will be available after the October (15th) release.
