### ISSUE TITLE
New term request for "age of onset of pancreatic ductal adenocarcinoma"

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#2127]
## Preferred term label

age of onset of pancreatic ductal adenocarcinoma

## Synonyms

<use synonyms from the existing disease term, and age of onset pattern>

## Textual definition

<create definition using pattern>

## Suggested parent term

age of onset of cancer

## Additional notes

Please create term in OBA and import into EFO. Should be linked to existing disease term using the standard "age of onset" template. There is currently an EFO term for "pancreatic ductal adenocarcinoma" (http://www.ebi.ac.uk/efo/EFO_0002517) but maybe this should be replaced by the MONDO term? (http://purl.obolibrary.org/obo/MONDO_0005184)

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050353** and will be made available after the upcoming OBA and EFO releases. 

_(The existing EFO term [EFO:0002517 pancreatic ductal adenocarcinoma](https://www.ebi.ac.uk/ols4/ontologies/efo/classes?short_form=EFO_0002517) will be obsoleted and replaced with [MONDO:0005184 pancreatic ductal adenocarcinoma](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0005184))_

**Comment by eks-ebi** [comment]
Thanks @ar-ibrahim!
