### ISSUE TITLE
New term request for Smart-seq3; Update name and synonyms request for Smart-3seq

### ISSUE THREAD

**Issue by jggatter** [EBISPOT/efo#2134]
Hello,

I am looking to have Smart-seq3 added as a Smart-like scRNA-seq library preparation protocol.

This is an existing synonym that was mistakenly listed under [Smart-3seq](http://www.ebi.ac.uk/efo/EFO_0010022). In reality they are distinct protocols so the synonym should be removed.

[Paper for Smart-3SEQ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6836736/#:~:text=Smart%2D3SEQ%20is%20a%20streamlined,compares%20favorably%20with%20previous%20methods). I'm not sure how EFO handles case sensitivity, but if it does that ontology term should be stylized as "Smart-3SEQ" and have "Smart-3seq" as a synonym.

## Preferred term label

Smart-seq3

## Textual definition

Smart-seq3 is an advanced single-cell RNA sequencing technology that provides full-length transcriptome coverage. It incorporates a 5' unique molecular identifier (UMI) RNA counting strategy, allowing for the in silico reconstruction of thousands of RNA molecules per cell. This method enhances transcript quantification accuracy and enables the detailed study of allele- and isoform-resolution within single cells. Smart-seq3 is particularly noted for its high sensitivity and ability to reconstruct the full-length transcripts of single cells

Smart-seq3 is a continuation and improvement of the Smart-seq technology, specifically Smart-seq2.

https://pubmed.ncbi.nlm.nih.gov/32518404/
https://www.sciencedirect.com/science/article/pii/S0168952523002317

## Suggested parent term

[Smart-like (EFO_0010184)](http://www.ebi.ac.uk/efo/EFO_0010184)

Thank you!

**Comment by jggatter** [comment]
Apologies if I should have made separate issues for each term!

**Comment by zoependlington** [comment]
Thank you for your ticket @jggatter (it's fine to have this in one, no worries at all!). I've added the new term as EFO_0022488 and updated the incorrect synonyms and capitalisation. Both will be available after our December release on the 18th.
