### ISSUE TITLE
2 different EFO for prostate specific antigen measurement

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2147]
2 EFO terms exist for prostate specific antigen measurement
prostate-specific antigen measurement: http://www.ebi.ac.uk/efo/EFO_0020660
prostate specific antigen measurement: http://www.ebi.ac.uk/efo/EFO_0004624

**Comment by ar-ibrahim** [comment]
Obsolete both terms and replace with [OBA:2050200](https://www.ebi.ac.uk/ols4/ontologies/oba/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_2050200).
