### ISSUE TITLE
New term request for Wu PMID 37492107

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2149]
For new term requests, please provide the following information:

## Preferred term label

age of onset of diverticular disease

## Synonyms

NA

## Textual definition

The age at which diverticular disease manifestations first appear

## Suggested parent term

age of onset of disease http://purl.obolibrary.org/obo/OBA_2020000

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **OBA:2050355** and will be made available after the upcoming OBA and EFO releases.

_(The EFO term diverticulitis [EFO:1001460](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_1001460) will be replaced by the [MONDO:0004235](https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0004235?lang=en) term)_.
