### ISSUE TITLE
Webpage describing EFO 3

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#215]
New page outlining the changes and roadmap

**Comment by zoependlington** [comment]
Started to pull together docs on EFO 3 here: https://docs.google.com/document/d/10R30bKwHZErB53RFneRqJJqlL1kghBcXq9E4aYeSSZk/edit?usp=sharing

**Comment by zoependlington** [comment]
- [ ] Announce in the next release notes and link from the EFO website with a link for download.

**Comment by paolaroncaglia** [comment]
@simonjupp @zoependlington
The current release notes say
"EFO - Release Notes
ArrayExpress Experimental Factor Ontology version 2.100"
(https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt)
- [ ] I presume we may want to discard the "ArrayExpress" bit in the second line going forward, as it's no longer the only resource using (or funding) EFO.

Also, as Dani pointed out in https://github.com/EBISPOT/efo/issues/263,
- [ ] "write appropriate release notes (be more verbose than the normal EFO release tag to make it clear to users that this isn't a standard EFO release!)"

**Comment by paolaroncaglia** [comment]
Here’s a suggested draft for the next release email: 

- [ ] Send email to: efo-users@ebi.ac.uk, arrayexpress-atlas@ebi.ac.uk 
(Ditch efo-users@lists.sourceforge.net and any mention of SourceForge in the email body, as we announced the move to GitHub a year ago now.)

Subject: EFO release 2.101 and first release of EFO 3 (beta version) 
- [ ] (Add version number of EFO 3 in subject line)

Text:

Dear EFO users,

Our first release of EFO 3 is now ready as a beta version. Therefore, from this month onwards and for some time, we will be releasing EFO versions 2.xxx and 3.xxx side by side, on our usual release dates. Each version will come with its own, separate release notes, but for your convenience we’ll provide links to downloads and release notes in the same monthly email. Details for this month are below, but if you wish to ask for more info or find that anything is unclear, please feel free to email us at efo-users@ebi.ac.uk.
 
*****

EFO 2

EFO version 2.101 is now live and available on the EFO website:
https://www.ebi.ac.uk/efo/

Please see release notes for a summary and detailed report of changes and modifications at our repository:
https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt 

*****

EFO 3

EFO version 3.1 (beta) is available here:

- [ ] [insert link]

You’ll find detailed release notes at the link below, but in summary these are the main novelties of EFO 3 vs. EFO 2:

- [ ] [insert a few bullet points]

Release notes here: 
- [ ] [insert link]

*****

Thanks,

- [ ] [Insert signature. For this one release, as it’s a big one, we could all sign?]

@simonjupp @zoependlington
