### ISSUE TITLE
New robot form term requests for Feofanova PMID 37253714

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2150]
Link to a webulous form for 106 circulating metabolite terms.
https://docs.google.com/spreadsheets/d/1F0OU7hZO93r7r1XIAID29Cs0rKly0vVU/edit?usp=sharing&ouid=115603389613071004022&rtpof=true&sd=true
In the paper (SupData3), terms are mapped to HMDB IDs only, which I then used the HMDB tool to map to pubchem/chebi... but it didn't pick up matches for all. 
Also added a synonym column (includes other labels that were included in the 'metabolite names' column, separated by a ;). 
I've only requested those terms which I could not find already existing and which had significant GWAS associations reported, but if there are any terms EFO doesn't think should be created due to lack of information, I can use a higher term. 
If I should be requesting eg. definitions differently for OBA terms, please say. Thanks!

**Comment by ar-ibrahim** [comment]
Term requests with existing CHEBI IDs were [created](https://docs.google.com/spreadsheets/d/1F0OU7hZO93r7r1XIAID29Cs0rKly0vVU/edit#gid=1980353162) in OBA and have been made available after the January release. All remaining terms were created in EFO and will be available after the February release 3.63.0.
