### ISSUE TITLE
New term request for Huang PMID:36658263

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2157]
For new term requests, please provide the following information:

## Preferred term label

Hamilton Depression Rating Scale 21-Item Clinical Classification

## Synonyms

HAMD-21

## Textual definition

A standardized rating scale developed by M. Hamilton in 1960 which is used to evaluate the severity of an individual's depression. This version of the instrument contains all 21 questions or types of symptoms associated with depression such as anxiety, mood, insomnia, and somatic symptoms experienced within the past week and is completed during a semi-structured interview. Each symptom is rated on a scale of 0-2, 0-3, or 0-4 with 0 being absent and 2, 3, or 4 being the most severe.

## Suggested parent term

measurement  http://www.ebi.ac.uk/efo/EFO_0001444
## Attribution

NA

** NCIT term: http://purl.obolibrary.org/obo/NCIT_C102119

**Comment by zoependlington** [comment]
Note for self or other editor: EFO:0007006 (depressive symptom measurement) may be an adequate parent - this needs to be investigated. Definition: "quantification of the existence and severity of depressive symptoms, usually via a questionnaire such as the Center for Epidemiological Studies Depression Scale (CES-D) "

**Comment by Santhi1901** [comment]
decided to use the parent term: depressive symptom measurement
