### ISSUE TITLE
NTR for ScaleBio Single Cell RNA Sequencing

### ISSUE THREAD

**Issue by brian-mott** [EBISPOT/efo#2158]
## Preferred term label

ScaleBio Single Cell RNA Sequencing

## Synonyms

None

## Textual definition

ScaleBio technology that utilizes a plate-based approach with combinatorial indexing to generate single cell libraries.

## Suggested parent term

[single cell library construction](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0010183&lang=en&viewMode=All&siblings=false)

## Reference

https://scale.bio/wp-content/uploads/2023/06/ScaleBio_Poster_scRNA-scATAC.pdf

**Comment by zoependlington** [comment]
Added as EFO_0022490, which will be available after the January (15th) release.
