### ISSUE TITLE
Request for new terms and enrichment of existing terms

### ISSUE THREAD

**Issue by kalpanaps** [EBISPOT/efo#2159]
https://docs.google.com/spreadsheets/d/1Ga0aVxHPVFrYYgsjByOeB-zT-_vjefAk9Iywx9dspas/edit#gid=0

**Comment by zoependlington** [comment]
The following have been added to EFO and will be available after today's release:


ID | LABEL
-- | --
EFO:0022616 | BD-215
EFO:0022617 | MM200
EFO:0022618 | MGR3
EFO:0022619 | Rh-28
EFO:0022620 | CFBE41o-
EFO:0022621 | OECM-1
EFO:0022622 | LCL 721.221
EFO:0022623 | SOSP-9607
EFO:0022624 | HuT 102 cell
EFO:0022625 | ST-1
EFO:0022626 | C666
EFO:0022627 | U-178MG
EFO:0022628 | 90C
EFO:0022629 | TPC-1
EFO:0022630 | AC16
EFO:0022631 | RCB1903 cell
EFO:0022632 | 2BS
EFO:0022633 | IHCF
EFO:0022634 | H157
EFO:0022635 | PRIESS
EFO:0022636 | FET
EFO:0022637 | T47D:A18
EFO:0022638 | SK-UT-2
EFO:0022639 | MO3.13
EFO:0022640 | SAVC
EFO:0022641 | BM9
EFO:0022642 | PLH
EFO:0022643 | BON-1
EFO:0022644 | PH5CH8
EFO:0022645 | CWR-R1
EFO:0022646 | HER911
EFO:0022647 | C-28/I2
EFO:0022648 | 253J-BV
EFO:0022649 | KHYG-1
EFO:0022650 | UPCI-SCC-131
EFO:0022651 | IHKE-1
EFO:0022652 | C3ABR
EFO:0022653 | Hs-578Bst
EFO:0022654 | MLS 2645-94
EFO:0022655 | MLS 402-91
EFO:0022656 | J.CaM1.6
EFO:0022657 | HOM-2
EFO:0022658 | TE-1
EFO:0022659 | EoL-1
EFO:0022660 | PITOUT
EFO:0022661 | LCL1
EFO:0022662 | OSU-2
EFO:0022663 | HuH-7-Lunet
EFO:0022664 | Colo-320
EFO:0022665 | SF-188
EFO:0022666 | HeLa M
EFO:0022667 | RCB2099
EFO:0022668 | OVCAR-10
EFO:0022669 | 8505C
EFO:0022670 | UWR1
EFO:0022671 | UWR2
EFO:0022672 | GES-1
EFO:0022673 | BHP5-16
EFO:0022674 | K1
EFO:0022675 | NCI-H3122
EFO:0022676 | SW-1736
EFO:0022677 | 5-8F
EFO:0022678 | HCCLM-3
EFO:0022679 | SACC-83
EFO:0022680 | T2
EFO:0022681 | SO-Rb50
EFO:0022682 | Flp-In-T-REx
EFO:0022683 | T-REx-HeLa
EFO:0022684 | T/C-28a2
EFO:0022685 | PER.C6
EFO:0022686 | HEK293S GnTI-
EFO:0022687 | HuTu-80
EFO:0022688 | LAN-5
EFO:0022689 | FU-OV-1
EFO:0022690 | 697
EFO:0022691 | BPH-1
EFO:0022692 | IMR-5
EFO:0022693 | HET-1A
EFO:0022694 | MOLM-13
EFO:0022695 | U6A
EFO:0022696 | HVTs-SM1
EFO:0022697 | tsA-201
EFO:0022698 | XPCS2BA
EFO:0022699 | RAO-3
EFO:0022700 | EW-7
EFO:0022701 | MCF-7/C4-12
EFO:0022702 | OV-2008
EFO:0022703 | HSC-3
EFO:0022704 | NCM-460
EFO:0022705 | U3118MG
EFO:0022706 | U3082MG
EFO:0022707 | HKE-3
EFO:0022708 | PD20
EFO:0022709 | BEL-7402
EFO:0022710 | Mahlavu
EFO:0022711 | LX-2
EFO:0022712 | LN-428
EFO:0022713 | Nthy-ori 3-1
EFO:0022714 | LN-308
EFO:0022715 | SK-CO15
EFO:0022716 | WRL-68
EFO:0022717 | 8305C
EFO:0022718 | TCam-2
EFO:0022719 | RH-41
EFO:0022720 | MEL-JUSO
EFO:0022721 | Nucleosome
EFO:0022722 | fluid shear stress
EFO:0022723 | GC-2
EFO:0022724 | Tn5 B1-4
EFO:0022725 | COS-7
EFO:0022726 | L-M
EFO:0022727 | BL-3
EFO:0022728 | BRL 3A
EFO:0022729 | NIH-3T3-A14
EFO:0022730 | Rat-1
EFO:0022731 | HER 14
EFO:0022732 | NIH EGFR-T17
EFO:0022733 | CV-1
EFO:0022734 | Vero
EFO:0022735 | J-774A.1
EFO:0022736 | EL-4
EFO:0022737 | P-388D1
EFO:0022738 | HTC
EFO:0022739 | FDCP-1
EFO:0022740 | N1E-115
EFO:0022741 | DA-3
EFO:0022742 | COS-1
EFO:0022743 | QT6
EFO:0022744 | SF-21
EFO:0022745 | SF-9
EFO:0022746 | MDCK
EFO:0022747 | BHK-21
EFO:0022748 | PS120
EFO:0022749 | BA/F3
EFO:0022750 | FAO
EFO:0022751 | PCCL-3
EFO:0022752 | MLE-15
EFO:0022753 | Mv1Lu
EFO:0022754 | TBY-2
EFO:0022755 | 32D clone3
EFO:0022756 | Neuro-2a
EFO:0022757 | TRAMP-C1
EFO:0022758 | H2.35
EFO:0022759 | B16-F10
EFO:0022760 | CHO
EFO:0022761 | PC12h
EFO:0022762 | NRK-52E
EFO:0022763 | P6
EFO:0022764 | RIN-m
EFO:0022765 | RK-13
EFO:0022766 | B16
EFO:0022767 | L-6
EFO:0022768 | H-4-II-E
EFO:0022769 | 70Z/3
EFO:0022770 | REF-52
EFO:0022771 | BSC-40
EFO:0022772 | J2E
EFO:0022773 | ME17
EFO:0022774 | P-19
EFO:0022775 | Do11.10
EFO:0022776 | S-180
EFO:0022777 | AtT-20
EFO:0022778 | RT4-D6P2T
EFO:0022779 | C6 glioma cell
EFO:0022780 | Rat-2
EFO:0022781 | McA-RH7777
EFO:0022782 | CHO-K1
EFO:0022783 | BP8
EFO:0022784 | 3T6-Swiss albino cell
EFO:0022785 | RT4-67
EFO:0022786 | RT4 NF2.17
EFO:0022787 | L8057
EFO:0022788 | R9
EFO:0022789 | FL5.12
EFO:0022790 | MC-1
EFO:0022791 | N18
EFO:0022792 | BV-2
EFO:0022793 | SVEC4-10
EFO:0022794 | OKP
EFO:0022795 | MES-23.5
EFO:0022796 | 32D
EFO:0022797 | MES13
EFO:0022798 | CHO-AA8
EFO:0022799 | MTD-1A
EFO:0022800 | NMuMg
EFO:0022801 | B95-8
EFO:0022802 | BAC1.2F5
EFO:0022803 | GD25
EFO:0022804 | RN-46A
EFO:0022805 | T37i
EFO:0022806 | UMR-106
EFO:0022807 | MTLn3
EFO:0022808 | HIB-1B
EFO:0022809 | ROS-17/2.8
EFO:0022810 | B1-8
EFO:0022811 | MA-104
EFO:0022812 | SV40LT-SMC Clone HEP-SA
EFO:0022813 | V-79
EFO:0022814 | AR4-2J
EFO:0022815 | AKR-2B
EFO:0022816 | RN33B
EFO:0022817 | PFHR 9
EFO:0022818 | NS-0
EFO:0022819 | alphaT3-1
EFO:0022820 | B104
EFO:0022821 | B16-F1
EFO:0022822 | BAEC
EFO:0022823 | C-127
EFO:0022824 | Dede
EFO:0022825 | CF2Th
EFO:0022826 | CHO9
EFO:0022827 | CHO-IR
EFO:0022828 | CHOP
EFO:0022829 | Comma-D
EFO:0022830 | DC2.4
EFO:0022831 | F111
EFO:0022832 | H19-7
EFO:0022833 | Hepa 1-6
EFO:0022834 | HIRc-B
EFO:0022835 | HL-1

**Comment by kalpanaps** [comment]
Thank you, Zoe!
___________________
Kalpana Panneerselvam

IntAct-Lead
European Bioinformatics Institute (EMBL-EBI)
United Kingdom
Tel: +44 1223 494 468
email: ***@***.***
