### ISSUE TITLE
New term request: HCASMC-hTERT

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2166]
## Preferred term label

HCASMC-hTERT

## Synonyms

n/a

## Textual definition

An immortalized human coronary artery smooth muscle cell derived cell line. 

Described in this publication: https://www.ahajournals.org/doi/10.1161/CIRCRESAHA.122.321692
"To overcome the limitations in replicative senescence in primary human coronary artery SMCs (HCASMCs), we generated an immortalized coronary artery SMC line via overexpression of hTERT (human telomerase reverse transcriptase)."

## Suggested parent term

EFO:0005735  - smooth muscle cell derived cell line

**Comment by zoependlington** [comment]
Term added as EFO_0022614, which will be available after the June (17th) release.
