### ISSUE TITLE
New term request for de Groot PMID 37410486

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2174]
For new term requests, please provide the following information:

## Preferred term label

multifocal choroiditis

## Existing term import request: 
https://www.ebi.ac.uk/ols4/ontologies/mondo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FMONDO_0023833

## Suggested parent term

choroiditis

**Comment by zoependlington** [comment]
Imported the Mondo term which will be available after the November release.
