### ISSUE TITLE
Missing synonyms after term obsoletion 

### ISSUE THREAD

**Issue by DSuveges** [EBISPOT/efo#2176]
There was an effort to enrich EFO term synonym list to reflect term usage in literature. (see ticket #1241). This work was completed and as a result, the number of disease/target evidence on OT Platform increased by ~1million. However upon replacing some of the affected terms (type II diabetes mellitus EFO_0001360 replaced by MONDO_0005148) the synonyms were not propagated, so we are losing these terms. 

- MONDO_0005148: T2D, T2DM would be important to be added.  (Pulling synonyms from EFO_0001360)
- MONDO_0005147: T1D, T1DM would be important to be added.  (Pulling synonyms from EFO_0001359)

As a more general question, upon such updates do you think it would make sense to superset the existing synonyms set from the old and new term?

**Comment by zoependlington** [comment]
Hi @DSuveges, thanks for letting us know about this. I've discussed this with Mondo and we hope to have all EFO synonyms and x-refs ingested into Mondo to prevent this from happening in the future. I've made a ticket with Mondo to have the above synonyms added which you can follow here: https://github.com/monarch-initiative/mondo/issues/7275
