### ISSUE TITLE
[NTR] Version specific Visium assays

### ISSUE THREAD

**Issue by jychien** [EBISPOT/efo#2178]
We are looking to have more specific ontology terms for Visium, as 10x has come out with variations of the assay. Here is some documentation regarding the version of the slide in the slide serial number:

- From [10x glossary](https://www.10xgenomics.com/support/software/space-ranger/latest/getting-started/space-ranger-glossary):
> Slide Serial Number: The unique identifier printed on the label of each Visium slide. The serial number starts with V, followed by a number that can range from 1-5, and ends with a dash and a three-digit number, such as 123. V1 = Visium Spatial Gene Expression Slide; V2 = Visium Gateway Gene Expression Slide; V4 = Visium CytAssist Spatial Gene Expression Slide v2 6.5 mm; V5 = Visium CytAssist Spatial Gene Expression Slide v2, 11 mm.

## Preferred term label
Visium Spatial Gene Expression V1
Visium CytAssist Spatial Gene Expression V2
Visium CytAssist Spatial Gene Expression, 6.5mm
Visium CytAssist Spatial Gene Expression, 11mm

## Synonyms
**Visium Spatial Gene Expression V1**: Visium V1
**Visium CytAssist Spatial Gene Expression V2**: Visium CytAssist
**Visium CytAssist Spatial Gene Expression, 6.5mm:** Visium CytAssist, 6.5mm
**Visium CytAssist Spatial Gene Expression, 11mm**: Visium CytAssist, 11mm

## Textual definition

- **Visium Spatial Gene Expression V1**: A 10x Genomics transcriptomics method that uses a spatially barcoded slide to capture and detect mRNA in intact tissue sections, where sample placement on the slide is a manual process. There is a total of 4992 spots in each capture area measuring 6.5mm x 6.5mm. 
- **Visium CytAssist Spatial Gene Expression V2:** A 10x Genomics transcriptomics method that uses a spatially barcoded slide to capture and detect mRNA in intact tissue sections, using the Visium CytAssist instrument to facilitate the transfer of tissue samples from standard plain glass slides to Visium slides.
- **Visium CytAssist Spatial Gene Expression, 6.5mm**: A 10x Genomics transcriptomics method that uses a spatially barcoded slide to capture and detect mRNA in intact tissue sections, using the Visium CytAssist instrument to facilitate the transfer of tissue samples from standard plain glass slides to Visium slides. There is a total of 4992 spots in each capture area measuring 6.5mm x 6.5mm. 
- **Visium CytAssist Spatial Gene Expression, 11mm**: A 10x Genomics transcriptomics method that uses a spatially barcoded slide to capture and detect mRNA in intact tissue sections, using the Visium CytAssist instrument to facilitate the transfer of tissue samples from standard plain glass slides to Visium slides. There is a total of 14336 spots in each capture area measuring 11mm x 11mm. 

## Suggested parent term

**Visium Spatial Gene Expression V1**: Visium Spatial Gene Expression (EFO:0010961)
**Visium CytAssist Spatial Gene Expression V2:** Visium Spatial Gene Expression (EFO:0010961)
**Visium CytAssist Spatial Gene Expression, 6.5mm**: Visium CytAssist Spatial Gene Expression V2
**Visium CytAssist Spatial Gene Expression, 11mm**: Visium CytAssist Spatial Gene Expression V2

## Attribution

https://orcid.org/0000-0003-4389-9821

**Comment by jychien** [comment]
Related issue: https://github.com/EBISPOT/efo/issues/2212

**Comment by jychien** [comment]
Hello @zoependlington, I am a curator for https://cellxgene.cziscience.com/, and we are hoping to use these Visium terms for our next schema update. Is there anything additional that you would need to help clarify or enable the addition of these terms to EFO? Thank you!

**Comment by jychien** [comment]
Hello, @zoependlington, was wondering if these version specific Visium terms made it into EFO for the September release? Thanks!

**Comment by brianraymor** [comment]
Hi @zoependlington - CELLxGENE support for Visium CytAssist is blocked by this issue. Could we get an update on the release schedule for this issue?

**Comment by zoependlington** [comment]
Terms have been added as the following and will be available after today's (15th) release:

**Visium Spatial Gene Expression V1:** EFO_0022857
**Visium CytAssist Spatial Gene Expression V2:** EFO_0022858
**Visium CytAssist Spatial Gene Expression, 6.5mm:** EFO_0022859
**Visium CytAssist Spatial Gene Expression, 11mm:** EFO_0022860
