### ISSUE TITLE
Duplicate terms in EFO

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#218]
See Google sheet:
https://docs.google.com/spreadsheets/d/1UGDmpO41LaDtfPRKApC6VXpIYp27xL_bzDUTDTVUU-w/edit?usp=sharing

**Comment by S2Ola** [comment]
Obsoleted EFO:1000743 into Orphanet:2337.

**Comment by zoependlington** [comment]
- [ ] **OBSOLETE** Klippel-Trenaunay syndrome (EFO:0007334)
     - Replaced by Orphanet:90308
     - Obsoleted in version 2.98

- [ ] **OBSOLETE** Legg-Calve-Perthes Disease (EFO:0007341)
     - Replaced by Orphanet:2380
     - Obsoleted in version 2.98

- [ ] **OBSOLETE** Birt-Hogg-Dube Syndrome (EFO:1001273)
     - Replaced by Orphanet:122
     - Obsoleted in version 2.98

 - [ ] **OBSOLETE** acrocephalosyndactylia (EFO:0004123)
     - Replaced by Orphanet:946
     - Obsoleted in version 2.98 

 - [ ] **OBSOLETE** Triple A Syndrome (EFO:1001997)
     - Replaced by Orphanet:869
     - Obsoleted in version 2.98 

- [ ] **OBSOLETE** carbohydrate metabolic disorder (EFO:1000061)
     - Replaced by Orphanet:79161
     - Obsoleted in version 2.98 

- [ ] **OBSOLETE** adrenocortical carcinoma (EFO:0003093)
     - Replaced by EFO:1000796
     - Ensure all synonyms and x-refs are moved over
     - Obsoleted in version 2.98

- [ ] **OBSOLETE** sea-blue histiocyte syndrome (EFO:1001170)
     - Replaced by Orphanet:158029
     - Ensure all synonyms and x-refs are moved over
     - Obsoleted in version 2.98 

**Still to make decision on:**

EFO:1001215 | Orphanet:1077
EFO:1000855 | Orphanet:597
EFO:0007267 | Orphanet:98878
EFO:0003775 | Orphanet:2314
EFO:0006452 | EFO:1000351
