### ISSUE TITLE
New term request for Radhakrishnan PMID 37105979

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2180]
For new term requests, please provide the following information:

## Preferred term label

Magnetic Resonance Imaging of the Heart

## Synonyms

cardiac MRI

## Textual definition

Magnetic resonance imaging of the heart

## Suggested parent term

heart function measurement http://purl.obolibrary.org/obo/NCIT_C137915

## Attribution

NA

NCIT term: http://purl.obolibrary.org/obo/NCIT_C137915

**Comment by zoependlington** [comment]
Term added as EFO_0022611, which will be available after the June (17th) release.
