### ISSUE TITLE
New term request for Lu PMID 38150807

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2184]
For new term requests, please provide the following information:

## Preferred term label

endocrine disruptor measurement

## Synonyms

endocrine-disrupting chemical measurement

## Textual definition

Quantification of Endocrine disrupting chemicals (EDCs), also known as endocrine disruptors, which are synthetic compounds which disrupt the functions of the endocrine (hormone) system

## Suggested parent term

environmental exposure measurement (http://www.ebi.ac.uk/efo/EFO_0008360)

## Attribution

NA

Chebi: CHEBI_138015

**Comment by ar-ibrahim** [comment]
Term has been created as **`OBA:2050419`** `level of endocrine disruptor in urine` and will be made available after the upcoming OBA and EFO releases.
