### ISSUE TITLE
One line docs of SPARQL validation queries

### ISSUE THREAD

**Issue by joncison** [EBISPOT/efo#219]
The SPARQL validation scripts (https://github.com/EBISPOT/efo/tree/master/src/sparql) are really useful examples (want to do something similar for EDAM) - what would help a lot if they each came with basic documentation (for those who are not yet expert in SPARQL).   Even just a single sentence describing the in english what each SPARQL script does.

**Comment by zoependlington** [comment]
@S2Ola and I have begun to write these descriptions, which for now can be found [here](https://docs.google.com/document/d/1H_DS4tlEWrCnk85S9G5CTnMZSYUdAzpR3b0qhGNILvs/edit?usp=sharing), but will eventually exist as comments on the SPARQL queries themselves.
