### ISSUE TITLE
Term requests for PMID 35693796

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#2192]
## Preferred term label

1. complicated appendicitis
2. gangrenous appendicits

## Textual definition

1. Appendicitis characterised by the presence of complications such as localised abscess, peritonitis and perforation.
2. Appendicitis classified as gangrenous due to the presence of necrosis, based on histological examination.

## Suggested parent term

appendicitis (EFO_0007149)

## Additional notes

There are similar terms in SNOMED for reference:
http://snomed.info/id/418171008
http://snomed.info/id/50846009

**Comment by zoependlington** [comment]
Added as EFO_0022612 and EFO_0022613 respectively. These terms will be available after the June (17th) release.
