### ISSUE TITLE
Term requests for 36583370

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#2195]
For new term requests, please provide the following information:

## Preferred term label

1. (trait in) response to loxoprofen
2. (trait in) response to clarithromycin
3. (trait in) response to traditional medicine

## Textual definition

1. A trait that affects the response to a stimulus with loxoprofen, a nonsteroidal anti-inflammatory drug (NSAID).
2. A trait that affects the response to a stimulus with clarithromycin, an antiobiotic used to treat various bacterial infections.
3. A trait that affects the response to a stimulus with traditional medicine products.

## Suggested parent term

1. "response to loxoprofen" could go under parent "response to non-steroidal anti-inflammatory" (http://www.ebi.ac.uk/efo/EFO_0005533)
2. "response to clarithromycin" could go under parent "response to antibiotic" (http://purl.obolibrary.org/obo/GO_0046677)
3. "reponse to traditional medicine" could go directly under "response to xenobiotic stimulus" (http://purl.obolibrary.org/obo/GO_0009410)

## General comments

* I have put "trait in" in brackets in the term labels as I can see that a couple of terms with this form have been imported from OBA, but the majority of "response" terms are still in the older format, so I'm not sure where we're at with this. I've written the definitions more in the form of the new OBA "trait in" terms, but happy for them to be rephrased as needed.
* We debated the traditional medicine term a bit as it is a vaguer class of substances than a particular drug or drug class (and maybe more a socially-determined class, rather than based on chemical properties or disease applications), but we still think it is a useful term for this paper. Happy to discuss further though!

**Comment by ar-ibrahim** [comment]
Terms have been created as:

`OBA:2050420 trait in response to loxoprofen`
`OBA:2050421 trait in response to clarithromycin`
`EFO:0803689 trait in response to traditional medicine`

and will be made available after the May releases: _OBA (13-05-2024) and EFO (15-05-2024)_.
