### ISSUE TITLE
NTRs for Parse Evercode WT v1-v3 and Parse Biosciences technologies

### ISSUE THREAD

**Issue by brian-mott** [EBISPOT/efo#2202]
Parse Biosciences has several versions of its Evercode Whole Transcriptome single cell sequencing kits. It would make sense to have terms for each version and also a parent term grouping for Parse Biosciences, similar to how 10x has a parent grouping term for its assays.

## Preferred term label
Parse Evercode Whole Transcriptome v1
Parse Evercode Whole Transcriptome v2
Parse Evercode Whole Transcriptome v3

## Synonyms
Parse Evercode WT v1
Parse Evercode WT v2
Parse Evercode WT v3

## Textual definition
Parse Evercode WT v1: Parse Biosciences single cell sequencing that utilizes combinatorial split-pool barcoding based off of SPLiT-seq.
Parse Evercode WT v2: Parse Biosciences single cell sequencing that utilizes combinatorial split-pool barcoding based off of SPLiT-seq.
Parse Evercode WT v3: Parse Biosciences single cell sequencing that utilizes combinatorial split-pool barcoding based off of SPLiT-seq.

## Suggested parent term
Ideally there is a parent term Parse Biosciences technology (or something similar) for the the above-proposed version terms and then this grouping has these parent terms:
Parse Biosciences technology: single cell library construction (EFO:0010183)
Parse Biosciences technology: SPLit-seq (EFO:0009919)

## Additional Information
https://www.biorxiv.org/content/10.1101/2022.08.27.505512v1.full
https://www.parsebiosciences.com

**Comment by zoependlington** [comment]
Added terms (EFO_0022600, EFO_0022601, EFO_0022602, and EFO_0022603) which will be available after the EFO May (15th) release.
