### ISSUE TITLE
NTRs for latest versions of 10x 3' and 5' assays

### ISSUE THREAD

**Issue by brian-mott** [EBISPOT/efo#2203]
10x has new versions for the following assays. There should be updated terms for these assays

## Preferred term label
10x 3' v4
10x 5' v3

## Synonyms
10x 3' v4: 10x 3' v4 sequencing, 10X 3' v4 sequencing, 10X 3' v4
10x 5' v3: 10x 5' v3 sequencing, 10X 5' v3 sequencing, 10X 5' v3

## Textual definition
10x 3' v4: 10X 3' v4 is the fourth version of the 10x sequencing technology that sequences from the 3' end of nucleic acid molecules.
10x 5' v3: 10X 5' v3 is the third version of the 10x sequencing technology that sequences from the 5' end of nucleic acid molecules. In the 5' assay, the polyd(T) is supplied in the RT Primer, and the template switch oligo (TSO) is part of the gel bead oligo.

## Suggested parent term
10x 3' v4: 10x 3' transcription profiling (EFO:0030003)
10x 5' v3: 10x 5' transcription profiling (EFO:0030004)

https://pages.10xgenomics.com/rs/446-PBO-704/images/10x_LIT000220_Product_Sheet_GEM-X-Single-Cell-Gene-Expression_Letter_Digital.pdf
https://pages.10xgenomics.com/rs/446-PBO-704/images/10x_LIT000221_Product_Sheet_GEM-X-Single-Cell-Immune-Profiling_Letter_Digital.pdf

**Comment by zoependlington** [comment]
Added as EFO_0022604 and EFO_0022605, which will be available after the EFO May release (15th).
