### ISSUE TITLE
NTR for 10x Gene Expression Flex

### ISSUE THREAD

**Issue by brian-mott** [EBISPOT/efo#2204]
10x has a new probe-based assay that can profile the human and mouse transcriptomes. 
## Preferred term label
10x gene expression flex

## Synonyms
10x gene expression flex, 10x Chromium FLEX, 10X gene expression flex, 10X Chromium FLEX

## Textual definition
10x Gene Expression Flex is a probe-based assay that allows for single cell transcriptome profiling of fresh, fixed, or frozen cells from either humans or mice. 

## Suggested parent term
Either 10x transcription profiling (EFO:0030080) or 10x technology (EFO:0008995). Open to other suggestions since this assay uses probes but can also be combined with multiome profiling techniques.

https://www.biorxiv.org/content/10.1101/2024.01.25.577066v2.full
https://www.10xgenomics.com/products/single-cell-gene-expression-flex

**Comment by zoependlington** [comment]
Added as EFO_0022606, which will be available after the May release (15th).
