### ISSUE TITLE
New term request 10x Xenium

### ISSUE THREAD

**Issue by Zethson** [EBISPOT/efo#2211]
For new term requests, please provide the following information:

## Preferred term label

10x Xenium

## Synonyms

Xenium

## Textual definition

Xenium is a spatial profiling technology from 10x Genomics that utilizes high-resolution imaging to simultaneously analyze the expression of hundreds of RNA targets within a single tissue section.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0008994

## Attribution

0000-0002-8937-3457

**Comment by zoependlington** [comment]
Term added as EFO_0022615 which will be available after the June (17th) release.
