### ISSUE TITLE
New term request for PMID 37731490

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2215]
For new term requests, please provide the following information:

## Preferred term label

anti-TSST-1 antibody measurement

## Synonyms

NA

## Textual definition

Quantification of one or more antibodies to the superantigen toxic shock syndrome toxin-1 (TSST-1) produced by Staphylococcus aureus, typically in serum.

## Suggested parent term

antibody measurement EFO_0004556

## Attribution

NA

**Comment by ar-ibrahim** [comment]
Term added as **EFO:0803691** and will be made available after the August release.
