### ISSUE TITLE
New term request for PMID: 37696869

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2216]
For new term requests, please provide the following information:

## Preferred term label

Polypoidal choroidal vasculopathy

## Synonyms

NA

## Textual definition

The presence of aneurysmal polypoidal lesions in the choroidal vasculature. The aneurysmal dilatations, also known as polyps, may be found at subfoveal, juxtafoveal, extrafoveal, peripapillary or even peripheral regions. These polypoidal dilatations may be visible as reddish-orange subretinal nodules during ophthalmoscopic examination. The polypoidal lesions are best detected on indocyanine green angiography (ICGA) and might be associated with a branching vascular network (BVN) of neovascularization. The presence of choroidal polyps and BVN can lead to recurrent episodes of exudative retinal detachment, serous or hemorrhagic pigment epithelial detachment (PED), subretinal hemorrhage, and subretinal exudation.

## Suggested parent term

Abnormal choroid morphology: http://purl.obolibrary.org/obo/HP_0000610

## Attribution

NA

The term is present in HP: 
Polypoidal choroidal vasculopathy: http://purl.obolibrary.org/obo/HP_0025569

**Comment by zoependlington** [comment]
Imported. Will be available after the August (15th) release.
