### ISSUE TITLE
New term request: HUDEP-2

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2217]
For new term requests, please provide the following information:

## Preferred term label

HUDEP-2

## Synonyms

HUDEP2; Human Umbilical cord blood-Derived Erythroid Progenitor-2

## Textual definition

An immortalized human erythroid progenitor cell line. 

## Suggested parent term

EFO:0005740

Other references:
https://www.cellosaurus.org/CVCL_VI06
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3606290/

**Comment by zoependlington** [comment]
Added as EFO_0022838, which will be available after the August (15th) release.
