### ISSUE TITLE
Request: add synonym for ONT GridION X5

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2218]
ONT GridION X5 (EFO:0008633) appears to be mentioned in vendor materials under a slightly different name, potentially due to the company renaming the device at some point. For example:

* Product page: https://store.nanoporetech.com/us/gridion.html "GridION Sequencing Device Mk1"
* Device detail sheet: https://community.nanoporetech.com/requirements_documents/gridion-mk1-spec.pdf "GridION Mk1" or "Oxford Nanopore Technologies® GridION™ Mk1"

Would it make sense to add "ONT GridION Mk1" as a synonym?

**Comment by zoependlington** [comment]
I've added a few synonyms based on the above links and suggestions, which will be available after the August (15th) release.
