### ISSUE TITLE
New Term Request: STORM-seq

### ISSUE THREAD

**Issue by Jchaffer787** [EBISPOT/efo#2219]
## Preferred term label

STORM-seq

## Textual definition

Single-cell TOtal RNA Miniaturized sequencing. A full-length single-cell ribo-reduced RNA sequencing protocol, optimized to profile thousands of cells per run. STORM-seq is built upon the Takara SMART-seq Stranded kit, allowing use of off-the-shelf reagents and standard equipment.

https://www.biorxiv.org/content/10.1101/2022.03.14.484332v3

## Suggested parent term

Smart-like (EFO:0010184) and RNA assay (EFO:0001457)

## Attribution
0000-0003-1653-8449

**Comment by zoependlington** [comment]
Term added as EFO_0022839, which will be available after our August (15th) release.
