### ISSUE TITLE
New terms request for Kalnapenkis PMID: 38565889

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2222]
There are 16 new proteins measured in plasma

There is also a list of 42 existing terms measured in blood serum, but for this paper, all the proteins are measured in plasma. I added these to Excel.

[new term_EFO.xlsx](https://github.com/EBISPOT/efo/files/15310243/new.term_EFO.xlsx)

**Comment by ar-ibrahim** [comment]
Hi Santhi! The terms have been added to this [template](https://docs.google.com/spreadsheets/d/1K0t21hZRRMI7vZSPaDtl0ib6Xb_f1NVfoNsUDR9UUR8/edit?gid=0#gid=0) and will be made available after the upcoming OBA and EFO (Sept 16th) releases.
