### ISSUE TITLE
Import term request - Hyperplasia of the endometrium

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2226]
## Request to import from HP:
Hyperplasia of the endometrium
http://purl.obolibrary.org/obo/HP_0040298

## Further info:
This is to replace an obsoleted MONDO term which was previously in EFO: 'endometrial hyperplasia' MONDO_0041161

**Comment by zoependlington** [comment]
This term is now added to our imports list and will be available after the August (15th) release.
