### ISSUE TITLE
Replacement suggestions for obsoleted MONDO terms

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2227]
6 MONDO terms which were previously imported to EFO and used in the GWAS Catalog are now obsolete without replacement terms stated. 

Here is a table of suggested replacement terms:

[Obsolete imported MONDO replacements - suggestions.txt](https://github.com/EBISPOT/efo/files/15393366/Obsolete.imported.MONDO.replacements.-.suggestions.txt)

**Comment by zoependlington** [comment]
I've added the suggested Mondo replacements to our imports list and they will be available after the August (15th) release. There will be no automatic link between the old and new terms, unfortunately, due to these terms being imported so they will need to be manually replaced on the GWAS side.
