### ISSUE TITLE
NTR: Illumina NovaSeq X and Illumina NovaSeq X Plus

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2235]
This new term request is for two Illumina sequencers.

A specification sheet from Illumina for both sequencers is available at: https://www.illumina.com/content/dam/illumina/gcs/assembled-assets/marketing-literature/novaseq-x-series-spec-sheet-m-us-00197/novaseq-x-series-specification-sheet-m-us-00197.pdf

## Preferred term label

Illumina NovaSeq X

## Synonyms
n/a

## Textual definition

The Illumina NovaSeq X is a high-throughput sequencing machine developed by Illumina.

## Suggested parent term

EFO:0002699  high throughput sequencer

----

## Preferred term label

Illumina NovaSeq X Plus

## Synonyms
n/a

## Textual definition

The Illumina NovaSeq X Plus is a high-throughput sequencing machine developed by Illumina.

## Suggested parent term

EFO:0002699  high throughput sequencer

**Comment by jenjou** [comment]
Hello, my group is still interested in having terms for these new Illumina sequencers. Is it possible to consider these terms? Please let me know if there is additional information I should provide. Thank you!

**Comment by zoependlington** [comment]
Added as EFO_0022840 and EFO_0022841, which will be available after our August (15th) release.
