### ISSUE TITLE
New Robot Form request for terms - Dhindsa PMID 37794183

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2240]
Robot form request for protein terms in blood. 
(The paper measured in blood plasma but agreed on Slack to use "blood". 

https://docs.google.com/spreadsheets/d/18PSveAXBZfT_-3e4uc3_0tMu_XrqGj8_/edit?usp=sharing&ouid=115603389613071004022&rtpof=true&sd=true

**Comment by ar-ibrahim** [comment]
Hey Lizzy! The terms have been added to this [template](https://docs.google.com/spreadsheets/d/18PSveAXBZfT_-3e4uc3_0tMu_XrqGj8_/edit?gid=1444815656#gid=1444815656) and will be made available after the upcoming OBA and EFO (Sept 16th) releases.

**Comment by earlEBI** [comment]
@ar-ibrahim Thank you!!
