### ISSUE TITLE
Edit OBA terms "in blood serum/plasma" request Dhindsa PMID 37794183

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#2241]
This is a request to edit 723 OBA terms from "in blood serum" (and in 2 cases "in blood plasma") to "in blood". 

https://docs.google.com/spreadsheets/d/1EV58b6KdVQWdSCAoIRLwxPOe1iWK1DZL/edit?usp=sharing&ouid=115603389613071004022&rtpof=true&sd=true

**Comment by ar-ibrahim** [comment]
Hey @earlEBI. The new terms have been added to your [template](https://docs.google.com/spreadsheets/d/1EV58b6KdVQWdSCAoIRLwxPOe1iWK1DZL/edit?gid=1764168076#gid=1764168076). They will be made available after the upcoming OBA and EFO (Sept) releases.
