### ISSUE TITLE
New term request for Liu PMID: 38867047

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2243]
For new term requests, please provide the following information:

## Preferred term label

mosaic loss of chromosome X measurement

## Synonyms

mLOX

## Textual definition

It is the most common clonal somatic alteration in leukocytes of female individuals

## Suggested parent term

genomic measurement http://www.ebi.ac.uk/efo/EFO_0004554

## Attribution

NA

**Comment by zoependlington** [comment]
Added as EFO_0022842 which will be available after the August (15th) release.
