### ISSUE TITLE
New ROBOT form request for Png PMID:34857772

### ISSUE THREAD

**Issue by Santhi1901** [EBISPOT/efo#2245]
Protein levels measured in blood 
[WC_20240625_measurement.xlsx](https://github.com/user-attachments/files/15984724/WC_20240625_measurement.xlsx)

**Comment by ar-ibrahim** [comment]
Hi Santhi! The terms have been added to this [template](https://docs.google.com/spreadsheets/d/1GzyP7uEIWz9jcbzXC3UmRY3Iu8ivU088Mo8zbgId0j8/edit?gid=0#gid=0) and will be made available after the upcoming OBA and EFO (Sept 16th) releases.
