### ISSUE TITLE
Obsolete Orphanet terms in EFO

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#225]
There are a number of obsolete terms from ORDO in EFO. The list with the ORDO replacement terms can be found here:
https://docs.google.com/spreadsheets/d/1ujyTzkj2dbpasqEC51xbu6jSll88roGlONb9jpwuWyk/edit?usp=sharing

The replacement terms need to be checked to see if they are a) already existing in EFO under either an EFO ID or as the replacement ORDO ID etc. and b) if they themselves are obsolete.

**Comment by S2Ola** [comment]
The list with the ORDO replacement terms have been reviewed and sorted using different colour codes to show the current status of these terms in EFO i.e some labels do not match with labels in EFO,  while others do not exists in EFO updates here: 
https://docs.google.com/spreadsheets/d/1ujyTzkj2dbpasqEC51xbu6jSll88roGlONb9jpwuWyk/edit?usp=sharing

**Comment by S2Ola** [comment]
The list is updated to show what needs to be reviewed in EFO based on differences between EFO and Orphanet, the column in light blue colour shows the aspects to be reviewed: 
https://docs.google.com/spreadsheets/d/1ujyTzkj2dbpasqEC51xbu6jSll88roGlONb9jpwuWyk/edit?usp=sharing

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT1** Orphanet_293864
     - gallbalder should be gallbladder
- [ ] **EFO:EDIT2** Orphanet_314632
     - Parkinsonim should be Parkinsonism

**Comment by S2Ola** [comment]
1.  EFO:EDIT1 Orphanet_293864
     gallbladder corrected 

2.  EFO:EDIT2 Orphanet_314632
     Parkinsonism Corrected
