### ISSUE TITLE
New term request: Singular G4

### ISSUE THREAD

**Issue by jenjou** [EBISPOT/efo#2265]
## Preferred term label

Singular G4

## Synonyms

n/a

## Textual definition

The G4 is a high-throughput sequencing machine developed by Singular Genomics.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0002699 "high throughput sequencer"

## Other info

Vendor's website is available at https://singulargenomics.com/g4/ .

**Comment by zoependlington** [comment]
Added as EFO_0022843, which will be available after our October (15th) release.
