### ISSUE TITLE
NTR Finngen traits

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#2284]
Hi!

I would like to request 11 new terms to be added to EFO. I haven't found it in other ontologies for it to be imported. They are endpoints from the latest Finngen release. The parent term is a suggestion, feel free to change if you have a more adequate term.

| Term Label                    | Definition                                                                                                                                                                      | Synonyms               | parent term                          | Referece    |
|-------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------|--------------------------------------|-------------|
| Pelvic neoplasm               | A tumor or abnormal growth occurring in the pelvic region, which can be benign or malignant.                                                                                    |                        | neoplasm (EFO_0000616)               | Finngen R11 |
| amino-acid transport disorder | medical conditions associated with a failure of amino acids to be absorbed from the kidney or intestine                                                                         |                        | metabolic disease (EFO_0000589)      | Finngen R11 |
| popliteal nerve lesion        | Damage to the popliteal nerve, which runs through the back of the knee, potentially causing weakness, numbness, or pain in the lower leg and foot.                              |                        | peripheral neuropathy (EFO_0003100)  | Finngen R11 |
| Phantom limb syndrome         | A condition in which individuals who have had a limb amputated experience sensations, including pain, in the absent limb.                                                       |                        | nervous system disease (EFO_0000618) | Finngen R11 |
| Thoracic root disorder        | A disorder involving irritation or compression of the nerve roots in the thoracic spine, often resulting in pain or sensory disturbances along the nerve pathway.               | thoracic radiculopathy | radiculopathy (MONDO_0002959)        | Finngen R11 |
| conjunctival scar             | Scar tissue formation on the conjunctiva, the thin membrane covering the white part of the eye, often resulting from injury or infection.                                       |                        | conjunctival disorder (EFO_1000203)  | Finngen R11 |
| otorrhagia                    | Bleeding from the ear, typically due to trauma, infection, or rupture of the eardrum.                                                                                           |                        | disorder of ear (MONDO_0021205)      | Finngen R11 |
| otorrhoea                     | Discharge from the ear, which may be caused by infection, inflammation, or trauma to the ear structures.                                                                        |                        | disorder of ear (MONDO_0021205)      | Finngen R11 |
| fallopian tube atrophy        | Degeneration or shrinking of the fallopian tubes, which may impair fertility and is often related to age or chronic conditions.                                                 |                        | fallopian tube disease (EFO_0009548) | Finngen R11 |
| ovary atrophy                 | Shrinking or reduction in function of the ovaries, often related to aging or hormonal changes.                                                                                  |                        | ovarian disease (EFO_0005771)        | Finngen R11 |
| Feeding problems of newborn   | Difficulties in the ability of a newborn to feed effectively, which can result from issues such as poor sucking reflex, swallowing difficulties, or gastrointestinal disorders. |                        | perinatal disease (EFO_0010238)      | Finngen R11 |

ORCID id: https://orcid.org/0000-0002-2417-7324

Thank you very much.

**Comment by zoependlington** [comment]
Added terms as IDs EFO_0022847 to EFO_0022856 respectively. They will be available after the October (15th) release.
