### ISSUE TITLE
Spinal muscular atrophy classification

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#229]
Review the classification of related spinal muscular atrophy diseases in EFO3

"Spinal Muscular Atrophy" is classified as a "Motor Neuron Disease" 
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008525

While "Proximal" and "Distal" forms are classified from ORDO and not connected to "Spinal Muscular Atrophy".

Can this be fixed please?
HP and Mondo have made the connections
https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0007269

**Comment by zoependlington** [comment]
All suggested child terms are imported Orphanet terms, therefore we are not able to alter the classification. Orphanet does not define any of these distal/proximal spinal muscular atrophies as a child of spinal muscular atrophy, in fact there is no direct term for spinal muscular atrophy although [proximal spinal muscular atrophy](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_70) seems to have the synonym SMA which may correlate. Needs discussion.

**Comment by paolaroncaglia** [comment]
I agree with @gkos-bio  that the ‘proximal’ and ‘distal’ terms should be made subclasses of ‘spinal muscular atrophy’. 

Note that MONDO hasn’t connected the ‘proximal’ term to ‘spinal muscular atrophy; we should suggest they do. 

Also note that MONDO doesn’t have a generic ‘distal’ term but rather the more specific one ‘distal spinal muscular atrophy type 3’, which is not the one we want.

**Comment by paolaroncaglia** [comment]
To do (in random order):

- [ ] Fix typos in def of EFO:0008525 'spinal muscolar atrophy'

(to be continued)
