### ISSUE TITLE
Entities with multiple labels

### ISSUE THREAD

**Issue by javfg** [EBISPOT/efo#2292]
While parsing the ontology, we've found 7 entries with multiple labels.

We're not sure if this is intended, as most entities have only one label. Most instances where this happens one label has the `xml:lang="en"` attribute, but the differences are not related to language.

The entities are:

`http://purl.obolibrary.org/obo/BFO_0000050`:
```
<rdfs:label>part of</rdfs:label>
<rdfs:label xml:lang="en">part of</rdfs:label>
<rdfs:label>part_of</rdfs:label>
```

`http://purl.obolibrary.org/obo/OBI_0001620`:
```
<rdfs:label>latitude</rdfs:label>
<rdfs:label xml:lang="en">latitude coordinate measurement datum</rdfs:label>
```

`http://purl.obolibrary.org/obo/OBI_0001621`:
```
<rdfs:label>longitude</rdfs:label>
<rdfs:label xml:lang="en">longitude coordinate measurement datum</rdfs:label>
```

`http://purl.obolibrary.org/obo/OBI_1110021`:
```
<rdfs:label>infect</rdfs:label>
<rdfs:label xml:lang="en">infection process</rdfs:label>
```

`http://purl.obolibrary.org/obo/OBI_1110122`:
```
<rdfs:label xml:lang="en">pathologic process</rdfs:label>
<rdfs:label>pathological process</rdfs:label>
```

`http://www.ebi.ac.uk/efo/EFO_0007409`:
```
<rdfs:label>Ornithine transcarbamylase deficiency</rdfs:label>
<rdfs:label>ornithine carbamoyltransferase deficiency</rdfs:label>
```

**Comment by zoependlington** [comment]
I've removed the duplicate labels for all except BFO_0000050 as the duplicate labels for this are coming from our imports. I will have to look into this in more depth. These changes will be available after the November (18th) release.
