### ISSUE TITLE
Incorrect OMIM xref for HIV infection

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#23]
When building mondo we came across this odd cluster:

![image](https://user-images.githubusercontent.com/50745/32241832-681d7b1a-be2e-11e7-9b74-25bb76b5a9d0.png)

we traced it to this class (HIV infection):

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000764

which has an xref to:

https://omim.org/entry/604201

HEPATIC FIBROSIS, SEVERE, SUSCEPTIBILITY TO, DUE TO SCHISTOSOMA MANSONI INFECTION

which is not related

**Comment by cmungall** [comment]
additional request: is it possible to have a github label for disease issues to help us in our reporting of how we make mondo.

**Comment by siiraa** [comment]
OMIM:604201 is removed from xRef.
@cmungall - label MonDO-request has been created. will apply this to other requests as well. Thank you
