### ISSUE TITLE
Protein C deficiency

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#230]
Protein C deficiency is a blood coagulation disease (coagulation disorder) and is not a rare disease.

## Preferred term label

Protein C deficiency

## Synonyms

protein C (PC) deficiency
Protein C deficiency (PCD)
Reduced protein C activity
Protein C Deficiency Disease

## Related diseases and measurements

related diseases (https://rarediseases.info.nih.gov/diseases/4521/protein-c-deficiency)
Hereditary thrombophilia due to protein C deficiency
Hereditary thrombophilia due to congenital protein C deficiency (Orphanet_745)
Hereditary thrombophilia due to PC deficiency
Autosomal recessive thrombophilia due to congenital protein C deficiency
Autosomal recessive thrombophilia due to PC deficiency
Severe hereditary thrombophilia due to congenital protein C deficiency

related measurement:
is related to http://www.ebi.ac.uk/efo/EFO_0004633

## Textual definition

Protein C deficiency is a disorder that increases a person's risk to develop abnormal blood clots due to a deficiency of the Protein C, a protein in the body that prevents blood clotting.[1][2] It may be inherited or acquired. [https://rarediseases.info.nih.gov/diseases/4521/protein-c-deficiency]

## X-refs

HP:0005543
SNOMEDCT_US_2018_03_01:76407009
OMIM:176860
NCI:C99025
MESH:D020151
UMLS_CUI:C0398625
ICD10CM:D68.59

## Suggested parent term

ou may want to represent "blood coagulation disease" (http://purl.obolibrary.org/obo/MONDO_0001531) and "thrombophilia" (http://purl.obolibrary.org/obo/MONDO_0002305) and then organise the subtypes in inherited and acquired.

Thrombophilia  -> blood coagulation disease -> hematological system disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW1** blood coagulation disease
     - subclass of hematological system disease (EFO_0005803)
     - **Synonyms:** Disorder, Blood Coagulation || Coagulation Disorder, Blood || Blood Coagulation Disorder || Disorders, Blood Coagulation || Coagulation Disorder || postpartum coagulation defect || postpartum coagulation defect with delivery || Coagulation Defect || Coagulopathy || Coagulation Disorders, Blood
     - **X-refs:** MESH:D001778 || UMLS:C0005779 || NCIT:C2902 || DOID:1247
     - **Definition:** A condition in which there is a deviation from or interruption of the normal coagulation properties of the blood. [ NCIT:C2902 ]

- [ ] **EFO:NEW2** thrombophilia
     - subclass of blood coagulation disease (EFO:NEW1)
     - **Synonyms:** Hypercoagulability || Hypercoagulability State || Excessive Blood Clotting || Hypercoagulable
     - **X-refs:** NCIT:C84479
     - **Definition:** A condition characterized by an abnormally high level of thrombi. Causes include thrombotic thrombocytopenic purpura, disseminated intravascular coagulation, bone marrow disorders, and antiphospholipid antibody syndrome. [ NCI ]

- [ ] **EFO:NEW3** protein c deficiency
     - subclass of thrombophilia (EFO:NEW2)
     - **Synonyms:** protein C (PC) deficiency || Protein C deficiency (PCD) || Reduced protein C activity || Protein C Deficiency Disease
     - **X-refs:** HP:0005543 || SNOMEDCT_US_2018_03_01:76407009 || OMIM:176860 || NCIt:C99025 || MESH:D020151 || UMLS_CUI:C0398625 || ICD10CM:D68.59
     - **Definition:** Protein C deficiency is a disorder that increases a person's risk to develop abnormal blood clots due to a deficiency of the Protein C, a protein in the body that prevents blood clotting. It may be inherited or acquired. [https://rarediseases.info.nih.gov/diseases/4521/protein-c-deficiency]

- [ ] **EFO:EDIT1** Hereditary thrombophilia due to congenital histidine-rich (poly-L) glycoprotein deficiency (Orphanet_217467)
     - add as subclass of thrombophilia (EFO:NEW2)

- [ ] **EFO:EDIT2** Hereditary thrombophilia due to congenital protein C deficiency (Orphanet_745)
     - add as subclass of thrombophilia (EFO:NEW2)

**Comment by zoependlington** [comment]
Here are the IDs for the new terms:
EFO_0009316 || protein c deficiency
EFO_0009315 || thrombophilia 
EFO_0009314 || blood coagulation disease
