### ISSUE TITLE
New chronic pain terms request

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#2304]
For new term requests, please provide the following information:

## Preferred term label

1. chronic back pain 
2. chronic neck pain 
3. chronic hip pain
4. chronic shoulder pain 
5. chronic bone pain

## Textual definition

1. A chronic pain phenotype that originates in the back muscles
2. A chronic pain phenotype that originates in the neck
3. A chronic pain phenotype that originates in the hip
4. A chronic pain phenotype that originates in the shoulder
5. A chronic pain phenotype that originates in the bones 

## Suggested parent term

EFO_0022195

**Comment by zoependlington** [comment]
Added as EFO_0022861, EFO_0022862, EFO_0022863, EFO_0022864, and EFO_0022865, which will be available after our November release.
