### ISSUE TITLE
Linear IgA Dermatosis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#231]
Missing from EFO2

Present in MONDO albeit with missing synonyms

## Preferred term label

Linear IgA Dermatosis

## Synonyms

Linear IgA bullous dermatosis
Chronic Bullous Disease of Childhood
Drug-induced Linear IgA Bullous Dermatosis
Drug-induced Linear IgA Dermatosis
Linear IgA IgG Bullous Dermatosis
Linear IgA IgG Dermatosis

## Textual definition

Autoimmune disease characterized by subepidermal blisters and linear deposition of autoantibodies at the dermoepidermal junction. The accumulated autoantibodies are of immunoglobulin A and occasionally immunoglobulin G classes against epidermal basement membrane proteins. The dermatosis is sometimes associated with malignancies and use of certain drugs (e.g., vancomycin). [ MESH:D062027 ]

## Suggested parent term

autoimmune bullous skin disease

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]  **EFO:NEW** Linear IgA Dermatosis
     - subclass of autoimmune bullous skin disease (EFO_0008598)
     - **Synonyms:** Linear IgA bullous dermatosis || Chronic Bullous Disease of Childhood || Drug-induced Linear IgA Bullous Dermatosis || Drug-induced Linear IgA Dermatosis || Linear IgA IgG Bullous Dermatosis || Linear IgA IgG Dermatosis
     - **X-refs:** Orphanet:46488 || MONDO:0018748 || MESH:D062027
     - **Definition:** Autoimmune disease characterized by subepidermal blisters and linear deposition of autoantibodies at the dermoepidermal junction. The accumulated autoantibodies are of immunoglobulin A and occasionally immunoglobulin G classes against epidermal basement membrane proteins. The dermatosis is sometimes associated with malignancies and use of certain drugs (e.g., vancomycin). [ MESH:D062027 ]

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO_0009313 || Linear IgA Dermatosis
