### ISSUE TITLE
EFO:0020001 - Incorrect synonym

### ISSUE THREAD

**Issue by SaverimuttuS** [EBISPOT/efo#2316]
Hi, 

Just wanted to bring to your attention that the entry [EFO:0020001](https://www.ebi.ac.uk/ols4/ontologies/efo/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0020001) has a NCIT ID (NCIT:C16523) as a synonym.

<img width="1567" alt="Screenshot 2024-11-07 at 12 23 17" src="https://github.com/user-attachments/assets/41460e09-7eb5-4bde-82a5-77f4001396e2">

Thanks 

Shirin

**Comment by zoependlington** [comment]
Thank you for catching this, I have updated this to be an x-ref rather than a synonym, which will be in our November release.
