### ISSUE TITLE
New "cell size selection" term

### ISSUE THREAD

**Issue by malloryfreeberg** [EBISPOT/efo#237]
For new term requests, please provide the following information:

## Preferred term label

cell size selection

## Synonyms

N/A

## Textual definition

A filtering process that either includes or excludes cells of a certain diameter using a physical filter.

*I'm not an expert; happy to have the definition tweaked.

## Suggested parent term

enrichment process >> sample enrichment

## Attribution

N/A

**Comment by malloryfreeberg** [comment]
@daniwelter

**Comment by malloryfreeberg** [comment]
@simonjupp where can I find what the term is that addresses this issue? Thanks!

**Comment by paolaroncaglia** [comment]
@malloryfreeberg 
Your new term is EFO:0009337 'cell size selection' and should be visible in the next EFO release, scheduled for next Monday October 15th. Any issue please let us know (Dani is away this week).
Thanks,
Paola

**Comment by malloryfreeberg** [comment]
@paolaroncaglia thank you!
