### ISSUE TITLE
question about xref for EFO_0004253 nephrolithiasis

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#24]
The class EFO_0004253 nephrolithiasis has an xref to [OMIM:605990](https://www.omim.org/entry/605990?search=605990&highlight=605990), which I think may be incorrect, as that class is named NEPHROLITHIASIS, URIC ACID, SUSCEPTIBILITY TO.

**Comment by nicolevasilevsky** [comment]
actually, the annotation is a OMIM_definition_citation, is that different than an xref? Apologies if so!

**Comment by siiraa** [comment]
Hi Nicole,
Does MonDO offer a mechanism to relate susceptibility to a disease? I think this crept in at one of our projects that needs to link an OMIM term from their resource to an EFO disease term. Reading OMIM definition, this seems to be related and this is probably their way of grouping the marker making the subject susceptible to a disease, to the actual disease. I probably should not remove this xRef yet at the moment. Is it breaking MonDO?

@simonjupp - we might need to have a conversation with OpenTargets re:susceptibility modeling. This has been a long standing issue.
