### ISSUE TITLE
Cross-reference of EFO:0000474

### ISSUE THREAD

**Issue by Elysheba** [EBISPOT/efo#240]
I noticed a (potential) wrong cross-reference of EFO:0000474 (epilepsy) to OMIM:617290 (Epilepsy, early-onset, vitamin b6-dependent). There seems to be no OMIM id that is equivalent to EFO:0000474, so I suggest to remove this cross-reference.

**Comment by zoependlington** [comment]
Agreed. I'll remove this cross reference. Thank you for bringing it to attention!

- [ ] **EFO:EDIT** epilepsy (EFO_0000474)
     - Remove OMIM:617290 cross reference
     - All other x-refs have been checked and are correct
