### ISSUE TITLE
EFO webpage referencing JIRA

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#241]
The submit page of the EFO website (https://www.ebi.ac.uk/efo/submit.html) and the FAQs (https://www.ebi.ac.uk/efo/faq.html#addatermtoefo) is causing confusion for users wishing to submit terms to EFO as it still directs them to submit through JIRA. This needs to be updated to direct to GitHub.

Also the about page (https://www.ebi.ac.uk/efo/about.html) still links to release notes and owl file on SourceForge.

**Comment by simonjupp** [comment]
- [ ] review links and update in https://github.com/EBISPOT/EFO-website
