### ISSUE TITLE
question about OMIM_definition_citation on EFO_0004124 Darier's disease

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#25]
There is an OMIM_definition_citation on EFO_0004124 Darier's disease to [OMIM:101900 ACROKERATOSIS VERRUCIFORMIS; AKV](https://www.omim.org/entry/101900?search=101900&highlight=101900). These diseases seem related but maybe not equivalent?

Related to: https://github.com/monarch-initiative/mondo-build/issues/10

**Comment by siiraa** [comment]
Also found Darier disease (Orphanet_218) in the process of investigating this. Terms are merged and OMIM xRef fixed.

**Comment by siiraa** [comment]
@nicolevasilevsky MeSH definition at https://meshb.nlm.nih.gov/record/ui?ui=D007644 has Acrokeratosis Verruciformis (OMIM:101900) as one of the alternative terms. I will keep this for now unless there is a strong objection that this is very wrong and will affect other use cases. Thank you.

**Comment by nicolevasilevsky** [comment]
ok, thanks @siiraa!
