### ISSUE TITLE
Webulous Submission for EFO diseases from UniProtKB

### ISSUE THREAD

**Issue by ggeorghiou** [EBISPOT/efo#251]
Hello,

Please find the link below for the OMIM terms I've mapped to ORDO for UniProt disease keywords.

https://docs.google.com/spreadsheets/d/1qRxF9TeJl99hbdkOKe3jaFuaZ6V3zKMj79u4jlfJQo8/edit?usp=sharing

Thanks in advance!

Best,

George Georghiou

**Comment by zoependlington** [comment]
Started to look over these. There are 8 new ORDO terms to import (no colour), 2 terms in EFO that have different labels to ORDO (blue), 1 term that is in EFO as an EFO namespace (purple) and the rest (green) are in EFO under ORDO namespace. Of the existing terms in EFO, I have gone through and found those with the OMIM x-refs already there (in bright green) and those that will require the x-refs to be added (yellow).

https://docs.google.com/spreadsheets/d/1F_oDNvXVhVJWmuazSiy57R1_TAVEyQgFyAzbQT0woHk/edit?usp=sharing

Spoke to @paolaroncaglia and I'll move this to the backlog for now and revisit soon due to new mappings being found and no new terms being needed yet.

**Comment by zoependlington** [comment]
@paolaroncaglia This sounds great! Definitely yes to import the new terms and add the OMIM xrefs.

I agree with rectifying Orphanet:306661 with adding new terms and mapping to MONDO, that sounds good to me!

Another of the terms with a different label in ORDO vs EFO is X-linked dominant intellectual disability-epilepsy syndrome (in EFO it's X-linked dominant intellectual disability - epilepsy, which isn't too different). Might just need to have the rdfs:label updated to reflect ORDO's label? Same with updating Orphanet_306661 label.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Thanks for confirming and for your additional suggestions; will do.

**Comment by paolaroncaglia** [comment]
Work in progress, but:
@ggeorghiou (and @zoependlington FYI)
Please note that ORDO Orphanet:79457 'Maculopapular cutaneous mastocytosis' is the same as EFO:1001229 'urticaria pigments'. I will edit the EFO term to better reflect the ORDO one.

**Comment by ggeorghiou** [comment]
Hi all, thanks for the update. I've got more terms that I would like to submit now that EFO v3 is live. Do we know if OpenTargets is going to be using EFO 3 anytime soon?

**Comment by zoependlington** [comment]
@ggeorghiou 

Currently, I believe that Open Targets is testing EFO 3 to ensure that nothing is broken in the pipeline. Every service using EFO should switch to EFO 3 before or around early 2019, which is when we are planning to stop production of EFO version 2 and will focus entirely on EFO 3.

Please feel free to submit the new set of terms as we are now working on expanding and developing both EFO 2 and EFO 3 simultaneously.

**Comment by ggeorghiou** [comment]
Right will do. Brace yourselves, it's a big list

**Comment by ggeorghiou** [comment]
I'll try my best to find one.

**Comment by paolaroncaglia** [comment]
Note for self - recapitulating what still needs to be done:

- [ ] For the terms in the rows with no colour: double-check that I haven't added unnecessary ORDO definition citations to newly-imported ORDO terms;

- [ ] As for the 2 terms in EFO that have different labels to ORDO (blue rows), that is actually 1 single ORDO term in EFO (Orphanet:306661 ‘Familial tumoral calcinosis’), and the situation could be rectified by creating new 2 EFO terms corresponding to 1) MONDO:0060714 ‘tumoral calcinosis, hyperphosphatemic, familial, 2’ (xrefs to OMIM:617993) and 2) MONDO:0060715 ‘tumoral calcinosis, hyperphosphatemic, familial, 3’ (xrefs to OMIM:617994); we could add to both new EFO terms the (less granular) xref to Orphanet_306661 ‘Familial hyperphosphatemic tumoral calcinosis/Hyperphosphatemic hyperostosis syndrome’;

- [ ] Add the OMIM xrefs marked in yellow (column M) to the corresponding terms that already exist in EFO;

- [ ] Another of the terms with a different label in ORDO vs EFO is X-linked dominant intellectual disability-epilepsy syndrome (in EFO it's X-linked dominant intellectual disability - epilepsy, which isn't too different). Might just need to have the rdfs:label updated to reflect ORDO's label? Same with updating Orphanet_306661 label.

**Comment by paolaroncaglia** [comment]
Left to do:

- [ ] Double-check if Orphanet_306661 in EFO is actually its ORDO parent instead...
