### ISSUE TITLE
adding subClassOf 'ESC derived cell line' [EFO:0005738] to various cell line terms

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#252]
We believe that the following terms should be subClassOf 'ESC derived cell line' [EFO:0005738]
H7-hESC [EFO:0005904] # distinction is in the definition
ZHBTc4-mESC [EFO:0005914] # distinction is in the definition
WW6 [EFO:0005915] # distinction is in the definition
ELF-1 [EFO:0005901] # distinction is in the definition
ES-CJ7 [EFO:0005916] # distinction is in the definition
ES-D3 [EFO:0005910] # distinction is in the definition
ES-E14TG2a.4 [EFO:0007751] # distinction is in the definition of EFO:0006275, which it is derived from
46C [EFO:0005484] # distinction is in the publication references for the definition of the term [PMID: 12524553]

Adding these relationships will help ENCODE organize our data.
Thank you,

**Comment by paolaroncaglia** [comment]
@jahilton 
Thank you. I double-checked and agree with all requests above and we’ll implement them:

- [ ] H7-hESC [EFO:0005904] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] ZHBTc4-mESC [EFO:0005914] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] WW6 [EFO:0005915] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] ELF-1 [EFO:0005901] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] ES-CJ7 [EFO:0005916] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] ES-D3 [EFO:0005910] subClassOf 'ESC derived cell line' [EFO:0005738]

- [ ] ES-E14TG2a.4 [EFO:0007751] subClassOf 'ESC derived cell line' [EFO:0005738]
- [ ] Also, for this one you wrote “distinction is in the definition of EFO:0006275, which it is derived from”; the definition of EFO:0006275 reads “This is a derivative of one of several mouse embryonal stem cell (ES) lines developed by M. Hooper in 1987.”, so we should make EFO:0006275 a subClassOf 'ESC derived cell line' [EFO:0005738] unless you disagree.

- [ ] 46C [EFO:0005484] subClassOf 'ESC derived cell line' [EFO:0005738]
- [ ] Also, we will improve the definition from “46C is an embryonic cell line” to “46C is an embryonic stem cell line”.

**Comment by jahilton** [comment]
That all sounds great. Thank you

**Comment by paolaroncaglia** [comment]
@jahilton 
All done, will be visible in next release. Thanks.
