### ISSUE TITLE
H4 ['EFO: 0002184'] is not 'embryonic cell line'

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#253]
We just came across the H4 cell line term listed as subClassOf 'embryonic cell line', but it is actually an adult cell line (37 yr, https://www.atcc.org/products/all/HTB-148.aspx#generalinformation), so the distinction of 'embryonic' is incorrect.

**Comment by jahilton** [comment]
Sounds great.

**Comment by paolaroncaglia** [comment]
@jahilton 
All done here too.
