### ISSUE TITLE
Annotare terms test

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#262]
Write a test for EFO that checks we still have all of these terms needed by annotare: https://github.com/arrayexpress/annotare2/blob/b70b8c7bb70f2fbf45aac40b579f195aaf8cac49/app/webapp/src/main/resources/Annotare-default.properties

**Comment by simonjupp** [comment]
- Set up new git repo with code for running this test 
- create bamboo job to periodically run once a month and alert us and AE curators

**Comment by S2Ola** [comment]
Created and cleaned the annotare term file

**Comment by zoependlington** [comment]
First pass at this is available here: https://github.com/EBISPOT/annotare-validator

**Comment by zoependlington** [comment]
@S2Ola We need to curl the Annotare term list rather than using a spreadsheet (can use Unix trickery - look into awk or grep or some sort of command, @warrenread offered to help with this 😄) Also need to put in a version of robot.jar!

**Comment by zoependlington** [comment]
The script now curls the term list from Annotare and the repo contains a bin directory with robot.jar.

To do:
- [ ] Set up Travis CI
- [ ] Set up Bamboo build plan
