### ISSUE TITLE
New term request: 184-hTERT

### ISSUE THREAD

**Issue by jujubix** [EBISPOT/efo#269]
For new term requests, please provide the following information:

## Preferred term label

184-hTERT

## Synonyms

184-hTert; 184hTERT

## Textual definition

Telomerase immortalized human breast epithelial cell line. PMID:17395154

Source: https://web.expasy.org/cellosaurus/CVCL_K053

## Suggested parent term

https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0001190

## Attribution

https://orcid.org/0000-0001-9203-6323

**Comment by paolaroncaglia** [comment]
Will do:

- [ ] Add EFO:NEW 184-hTERT
Subclass of EFO:0001190 ‘HMEC184’
Def: “Telomerase-immortalized human breast epithelial cell line.”
PMID_definition_citation: PMID:17395154
database_cross_reference: https://web.expasy.org/cellosaurus/CVCL_K053,
https://orcid.org/0000-0001-9203-6323

The ID of the new EFO term is ...

**Comment by paolaroncaglia** [comment]
@jujubix 
This is now done, your new term is EFO:0009375 "184-hTERT". Thanks.

**Comment by jujubix** [comment]
Awesome :)

**Comment by paolaroncaglia** [comment]
@jujubix 
The new term will be visible in our next release (Nov 15).
I'll leave this ticket open as we prefer to mark them as "done" rather than "closed", and then we change to "closed" during our fortnightly scrums. Thanks.
