### ISSUE TITLE
Overlap syndrome (OS) representation in EFO

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#27]
Context:

Overlapping connective tissue diseases (with shared autoimmunity)/rheumatic autoimmune disease and Asthma-COPD Overlap Syndrome (ACOS) classification.

**Rheumatic autoimmune disease**
Rheumatic autoimmune disease patients can been diagnosed with:

- Rheumatoid Arthritis (RA),
- Systemic lupus erythematosus (SLE),
- RA first and then with RA + SLE.

The last case is commonly seen in clinical practice.
So, they have been diagnosed with an overlap autoimmune disease that differs from those with 'pure' RA or 'pure' SLE. There is a controversial term coined in the litterature as 'Rhupus' or 'Rhupus syndrome' to categorise these patients with overlapping phenotypes from both SLE and RA.

**Asthma-COPD overlap syndrome**
Another example is Asthma and COPD commonly presented in clinical practice ant the challenge to identify whether the patients are ‘purely’ asthmatic or suffer from asthma-COPD overlap syndrome (ACOS). The asthma-COPD overlap syndrome (ACOS) has reemerged in the medical literature.
ACOS is characterized by persistent airflow limitation (FEV1 ≤ 80% predicted; FEV1/FVC ratio ≤70%) with several features shared with both asthma and COPD, including current or past smoking
(see section 4. below)

**Disease heterogeneity**
There is controversy concerning having overlapping/mixed disease classified as a separate entity due to heterogeneous clinical manifestations (there is no consensus on an ACOS definition, likely due to the heterogeneity of the disease), and especially, because there is an increasing tendency to shift away from fixed disease labels.

However, in terms of disease classification and of finding the relevant biomarkers and genetic information from text-mining, it make sense to acknowledge what disease labels are currently used in the clinical practice, medical reports and literature to characterise a group of related disorders with distinct co-morbidities.

**Overlap Connective Tissue Disease Syndromes:**

In general, overlap syndromes (OSs) - which I don't particularly like as a term from a patient point of view - is defined as entities satisfying classification criteria of at leas two connective tissue diseases occurring at the same time or at a different time in the same patient.

This include:

    systemic lupus erythematosus (SLE),
    rheumatoid arthritis (RA),
    systemic sclerosis (SSc),
    polymyositis/dermatomyositis (PDM), and
    Sjögren syndrome (SS).

For reference, please read:
http://www.sciencedirect.com/science/article/pii/S1568997212001218

Scleromyositis is another example that is both 'Systemic sclerosis' and 'polymyositis' and a synonym of 'scleroderma/polymyositis overlap syndrome'.

**Current classification in thesaurus and ontologies:**

What information is available in EFO?

**Mixed connective tissue disease**
Currently, there is a concept of 'mixed connective tissue disease' in EFO with a x-ref to DO and to MeSH.

In DO, the same concept is defined as 'A collagen disease that is considered an overlap of three diseases, systemic lupus erythematosus, scleroderma, and polymyositis with very high titers of circulating antinuclear antibody to a ribonucleoprotein antigen.'

In MeSH, it's a subtype of 'connective tissue diseases' and defined as 'A syndrome with overlapping clinical features of systemic lupus erythematosus, scleroderma, polymyositis, and Raynaud's phenomenon.'

In NCIt, it's labeled as Mixed Connective Tissue Disease (Code C84892).

In ORDO, it's defined as 'Mixed connective tissue disease (MCTD) is a rare connective tissue disorder combining clinical features of systemic lupus erythematosus (SLE), systemic sclerosis (SSc), polymyositis (PM) (see these terms) and/or rheumatoid arthritis (RA).'

**Localised scleroderma and scleroderma:**
Note that there is one child of mixed connective tissue disease in EFO: localised scleroderma.
However, it's not a mixed connective tissue disease and will have to be reclassified.
Scleroderma is indeed a connective tissue disease characterized by tissue fibrosis, vasculopathy and immune dysregulation.
Localised scleroderma is a subclass of scleroderma (see DO)

**Connective tissue disease:**
The concept is missing from EFO but present in DO, MeSH and NCIt (Connective Tissue Disorder (Code C26729)). This should be added.

**Overlap syndrome:**
The concept is missing from EFO

In ORDO, the concept of 'Overlapping connective tissue disease' is already defined with

- 'Mixed connective tissue disease' (MCTD), and
- 'Unclassified overlapping connective tissue disease' as subclasses of it.

**Suggested classification changes in EFO:**

__ Overlapping connective tissue disease (need synonyms like Overlap connective tissue disease syndrome)
--
__ Scleromyositis
__ dermatomyositis/systemic lupus erythematosus overlap syndrome (Dermatomyositis Overlap with Systemic Lupus Erythematosus)
__ Rhupus
__ Scleroderma overlap syndrome (PMID:27684895)
__ Mixed connective tissue disease
__Unclassified overlapping connective tissue disease

Reclassify Localised scleroderma has a subclass of scleroderma (to be defined)

**Asthma-COPD overlap syndrome (ACOS):**
Approximately one in four patients with chronic obstructive pulmonary disease (COPD) have asthmatic features consisting of wheezing, airway hyper-responsiveness or atopy ((PMID:28119742).

This can be classified in EFO under respiratory system disease but needs to be discussed after review.

We will to look exactly at the phenotypes from both Asthma and COPD and understand how the current classification of both diseases make sense in EFO

Look also at the following article for a different opinion:
Postma DS , Rabe KF . The asthma-COPD overlap syndrome. N. Engl. J. Med. 2015; 373: 1241–9.
http://www.nejm.org/doi/full/10.1056/NEJMra1411863

Best wishes,

Gautier

**Comment by siiraa** [comment]
see https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1370 for details

**Comment by simonjupp** [comment]
Consult Gautier on what needs to be done for this.

**Comment by gkos-bio** [comment]
Hello,
Is there any progress on this front?

Best regards,
Gautier

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,

I can move this ticket from the ‘backlog’ queue to the ‘next’ one. At a quick glance, it looks like some issues in this ticket would require a bit of reading, so if you’ve had a chance to clarify some of them in the meantime, it would be a great help if you could please update and summarise. Also, if there’s any area that has priority over others within this ticket, please point us to it, in case we can’t address them all in time for the next release.

We’d also need to check if/how those disorders are represented in MONDO (haven’t had time to do that yet), and if yes, in what measure the MONDO integration would address the issues in this ticket. Though I suspect there’s some manual work for EFO here. 

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@gkos-bio 
I'm copying part of the MONDO ticket above here as a summary of a general issue we're addressing here, in case you wish to comment:

"Based on the review above [https://www.sciencedirect.com/science/article/pii/S1568997212001218] and on a first look at the literature on one of those overlapping syndromes (rhupus), it seems that part of the medical field acknowledges those disorders as disease entities in their own right, whether they express specific antibodies or not (“...In some OS a specific autoantibody has been identified, supporting the hypothesis that these syndromes are not a mere association of two or more CTD in the same patient, but a well defined clinical entity with specific clinical characteristics”). Do you have any opinion on how representative of the field this statement is? Because if it is accepted, at least to some degrees, it seems that it would be safer and more correct NOT to classify ‘overlap syndrome of x and y’ as subclass of ‘x’ and ‘y’, but, rather, to capture with a different axiom the fact that ‘overlap syndrome of x and y’ shares some features with ‘x’ and ‘y’."

Thanks.

**Comment by paolaroncaglia** [comment]
Note for self: there's a Wikipedia entry on overlap syndromes that might be useful: https://en.wikipedia.org/wiki/Overlap_syndrome

**Comment by paolaroncaglia** [comment]
@gkos-bio 
FYI, here's a comment from a member of the medical informatics community in partial disagreement with representing overlap syndromes:
https://github.com/monarch-initiative/mondo/issues/359#issuecomment-429850494

**Comment by paolaroncaglia** [comment]
@gkos-bio 
When you have a chance, could you please review the thread in this MONDO ticket https://github.com/monarch-initiative/mondo/issues/359, and address some questions from @cmungall that would be useful to us (“Would be good to hear of use cases, what OT users would expect in queries for asthma, etc”), as well as the comment on the appropriateness and usefulness of joint disease concepts. I’m happy to add overlap syndromes to EFO if you think they will be helpful (one point I can’t judge on is whether treatments suggested for overlap syndromes are truly specific for them or not). In that case, would you consider as truly distinct disease concepts all the ones listed in the review https://www.sciencedirect.com/science/article/pii/S1568997212001218, or just the 3 that are associated with a specific autoantibody?
Otherwise, I’ll close this ticket, as all the connective tissue diseases listed in the review paper (as well as asthma and COPD) are already in EFO 3.
Thanks!

**Comment by paolaroncaglia** [comment]
@gkos-bio 
FYI there's a new comment in the thread on overlap syndromes, see
https://github.com/monarch-initiative/mondo/issues/359#issuecomment-431708327
Thanks.

**Comment by gkos-bio** [comment]
Thank you for looking into this and thanks to @msincan for his contribution to the discussion.
I agree with @msincan comments. 
There are more and more overlap syndromes defined but not necessarily well characterised. Ideally, we would like to capture the clinical features which are more relevant.

I was wondering how it will work in practice for the data providers, if we get an evidence from the literature about any overlapping syndrome.
Shall we ask the data provider to provide 2 pieces of evidence, i.e. one for Asthma and one for COPD. Or one for RA and one for SLE?

**Comment by paolaroncaglia** [comment]
@cmungall
@simonjupp 
@msincan
Would you have any feedback on @gkos-bio 's question above, please?

@simonjupp 
I think this ticket may be moved to 'Done' and then 'Closed', as long as we keep track of any pending discussion elsewhere, if necessary. Thanks.

**Comment by paolaroncaglia** [comment]
Resolution from today's EFO meeting: move to icebox.

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor:
If/when we come back to this ticket, remember to consider the discussion in https://github.com/monarch-initiative/mondo/issues/359.

**Comment by paolaroncaglia** [comment]
Moving to Done; we can always retrieve and reopen if the topic ever comes up again.
