### ISSUE TITLE
Address warnings for "Conflicting id definitions"

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#271]
When running 'make' on efo3dev, some warnings come up about conflicting id definitions, e.g.:

org.obolibrary.obo2owl.Owl2Obo.error(Owl2Obo.java:1634)  - Conflicting id definitions: 1) CL:0000545  2)BTO_0001678

We discussed these briefly at our last meeting. @simonjupp notes that those derive from the obo conversion; one option is, for the time being, let’s not have the obo file in the next release/comment out obo conversion? But that may not work for some external users? Later on we may want to fix though.

**Comment by zoependlington** [comment]
I think this may be fixed now due to the new EFO pipeline generating the obo file in a different way. Will move to done.
