### ISSUE TITLE
Revise classification of Asperger syndrome

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#275]
Tagging @cmungall and @nicolevasilevsky as this issue is present in MONDO too.

Stemming from https://github.com/EBISPOT/efo/issues/274. While reading the MONDO editors guide (https://docs.google.com/document/d/19bp9MpCHCxbjMmbntB2e5gZNzzNlu06DnDB8xcoSXK8/edit#), I came across this bit, wrt synonyms and labels:
“We try and avoid including things in this list: https://en.wikipedia.org/wiki/List_of_medical_eponyms_with_Nazi_associations but if it’s established (e.g. Wegener granulomatosis) may include as a syn and mark DEPRECATED”
Among the entries in the Wikipedia list above, ‘Asperger syndrome’ is still a primary label in both EFO and MONDO (and has 6 children in the latter). The Wikipedia entry for this disorder (https://en.wikipedia.org/wiki/Asperger_syndrome) reads:
“The exact cause of Asperger's is unknown. While it is probably partly inherited, the underlying genetics have not been determined conclusively. Environmental factors are also believed to play a role. Brain imaging has not identified a common underlying problem. _The diagnosis of Asperger's was removed in the 2013 fifth edition of the Diagnostic and Statistical Manual of Mental Disorders (DSM-5), and people with these symptoms are now included within the autism spectrum disorder along with autism and pervasive developmental disorder not otherwise specified (PDD-NOS). It remains within the tenth edition of the International Classification of Diseases (ICD-10) as of 2015._”
In ICD-11 (stable version for implementation release, to be submitted for endorsement in 2019), “Asperger” and other Asperger-containing names seem to be synonyms of 6A02.0 “Autism spectrum disorder without disorder of intellectual development and with mild or no impairment of functional language”, rather than primary labels (retrieved by searching https://icd.who.int/browse11/l-m/en with “Asperger”). EFO and MONDO may want to revise the classification of this term, possibly when ICD-11 becomes public. Thanks.

**Comment by nicolevasilevsky** [comment]
@cmungall let me know if you'd like me to make this revision now or wait until ICD-11 comes out.

Change label of MONDO_0005259 to Autism spectrum disorder without disorder of intellectual development and with mild or no impairment of functional language

There is also 
MONDO_0010340 'Asperger syndrome, X-linked, susceptibility to, 1'
MONDO_0010343 'Asperger syndrome, X-linked, susceptibility to, 2'

**Comment by cmungall** [comment]
I'm not sure we should factor the release of ICD-11 into the decision, there are overriding considerations based on what the clinical and patient community feel is correct, this could be a good topic for the meeting

**Comment by paolaroncaglia** [comment]
@cmungall 
@nicolevasilevsky 
@zoependlington 
Would you like to keep this ticket aside for discussion at the MONDO workshop in late November? 
Or, @zoependlington , should we address it in the current sprint?
Thanks!

**Comment by nicolevasilevsky** [comment]
I'm fine either way

**Comment by paolaroncaglia** [comment]
Thanks @nicolevasilevsky . At our EFO meeting today we resolved that @zoependlington will bring this ticket up for discussion at the MONDO workshop.

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor: 
FYI, there wasn't a chance to discuss this ticket at the MONDO workshop.

**Comment by paolaroncaglia** [comment]
Re. "The Problem with Asperger's" [naming],
I also found this interesting:
https://blogs.scientificamerican.com/observations/the-problem-with-aspergers/
It highlights ethical and medical reasons to drop the current label, as well as the importance of diagnosis to provide patients with adequate care (especially for young patients in school age).
Not sure how representative of the patient community that article is, but from a clinical perspective, I think renaming makes sense. Shall we adopt the updated classification from DSM-5 and ICD-11? Or do we need to consult with experts to confirm?

**Comment by nicolevasilevsky** [comment]
@pnrobinson - could you give us your expert opinion on this? :)

I think the plan would be to change label of `MONDO_0005259` to `Autism spectrum disorder without disorder of intellectual development and with mild or no impairment of functional language`

and change the labels for: 
MONDO_0010340 'Asperger syndrome, X-linked, susceptibility to, 1'
MONDO_0010343 'Asperger syndrome, X-linked, susceptibility to, 2'

And make Aspergers syndrome a syn and mark it 'A synonym that is historic and discouraged'

**Comment by pnrobinson** [comment]
MONDO_0010340 'Asperger syndrome, X-linked, susceptibility to, 1' is not a disease.
I have been trying to explain what is going on for the last two years @cmungall @mellybelly @nicolevasilevsky can we skype about this? There is a basic misunderstanding in so many places in MONDO about this

**Comment by nicolevasilevsky** [comment]
@pnrobinson I sent an email to you, Chris and Kristen to try to schedule a call

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky I understand you might have discussed whether to rename MONDO_0005259 'Asperger syndrome' or not at a recent meeting. If so, if/when you resolve on that issue, could you please post an update here. Many thanks in advance.

**Comment by nicolevasilevsky** [comment]
we didn't actually discuss the naming for Asperger syndrome.

@pnrobinson 
Do you think it would be okay to change the label of MONDO_0005259 to Autism spectrum disorder without disorder of intellectual development and with mild or no impairment of functional language

And make Aspergers syndrome a syn and mark it 'A synonym that is historic and discouraged'

**Comment by pnrobinson** [comment]
It looks like there are good reasons not to want to use this name. Still it is very familiar and the proposed replacement label is not. I would suggest that we follow the DSM here. I am not an expert here, but this website suggests

Individuals with a well-established DSM-IV diagnosis of autistic disorder, Asperger’s disorder, or pervasive developmental disorder not otherwise specified should be given the diagnosis of autism spectrum disorder. 

https://www.autismspeaks.org/dsm-5-criteria


And so I would say we have two issues.
1. Naming of this term (Asperger or not)
2. Whether or not the structure of Mondo reflects the DSM-V, and whether we have a plan for cases where we might want to diverge from DSM-V or if we say DSM-V is our sole source of truth in this area.

**Comment by paolaroncaglia** [comment]
@pnrobinson thank you for your input.
In summary, there is a bigger issue here, i.e. whether to adhere to the Diagnostic and Statistical Manual of Mental Disorders (DSM) in naming and classifying mental disorders, or not. I don't really have an opinion on this. I'd suggest to move this ticket to the MONDO tracker. Then, if you do opt for renaming Asperger syndrome, EFO3 would pick that up when building after the MONDO release, and we'd edit accordingly. We can discuss on Monday. Thanks!

**Comment by paolaroncaglia** [comment]
At the EFO-MONDO meeting yesterday, we resolved to move this ticket to the MONDO tracker, move the EFO ticket to "Done", and pick up MONDO changes if any following their release. The link to the MONDO ticket will be below this comment. Thanks.
