### ISSUE TITLE
Duplicate terms - inflammation

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/efo#278]
The following two terms are duplicates of each other:
inflammation http://purl.obolibrary.org/obo/MP_0001845
inflammation (MPATH) http://purl.obolibrary.org/obo/MPATH_212

They possibly also duplicate:
inflammatory response http://purl.obolibrary.org/obo/GO_0006954

Review which term is the most appropriate and remove the one or ones that are duplicates.

**Comment by zoependlington** [comment]
- [ ] inflammatory response is a GO term and has the gwas_trait true annotation - child of response to stimulus
- [ ] inflammation (MPATH) is related to mouse pathology - is a child of pathological entity
- [ ] inflammation (MP term) is a child of abnormality of the immune system BUT in the original ontology, this term is actually abnormal inflammatory response.

**Comment by paolaroncaglia** [comment]
@zoependlington @daniwelter @simonjupp 
I have a suggestion on how to resolve the multiple ‘inflammation’ terms in EFO, and your feedback would be welcome.

I agree with obsoleting ‘inflammation’ (MPATH) http://purl.obolibrary.org/obo/MPATH_212. It has no children. But we could retain it as a definition_citation for whatever term will end up being the high-level ‘inflammation’ term in EFO.

As for ‘inflammation’ http://purl.obolibrary.org/obo/MP_0001845, it’s a phenotype term (in EFO, child of ‘abnormality of the immune system’). It has a small number of descendants (14), small considering the many EFO terms that list inflammation in their definitions. Compare to MONDO:0021166 ‘inflammatory disease’ and all its descendants. This is probably one place where we need to take a stand between phenotype and disease, and I would favor disease. Also, merging a phenotype term (MP ‘inflammation’) with a biological process one (GO ‘inflammatory response’ http://purl.obolibrary.org/obo/GO_0006954) doesn’t seem entirely correct to me.

As for GO ‘inflammatory response’ http://purl.obolibrary.org/obo/GO_0006954, it is being used in GWAS but has no ‘disease’ children in EFO.

I suggest to:
- [ ] Create a new term for inflammation in the disease branch and link it to the GO term (see details below);
- [ ] Obsolete EFO MP ‘inflammation’ and rehouse its children under the new disease term above, but retain the MP ID as a definition_citation for the new term;
- [ ] Retain the EFO GO term, but don’t add disease terms under it;
- [ ] Add the new high-level disease term as parent to any disease term that contains ‘inflammation’ or ‘inflammatory’ in its definition.

The new disease term could be:
EFO:NEW inflammatory disease
Subclass of disease
“A disease involving an inflammatory response.”
Disease_has feature EFO GO ‘inflammatory response’ (or ‘has_part’?)
Definition_citations: MONDO:0021166, MPATH:212, MP:0001845
Synonym: inflammation

Any thoughts on this?
Thanks!

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] If/when we have an appropriate general term for 'inflammatory disease' or similar, consider a strategy to add it as an extra parent to all subtypes of inflammatory disease that already exist in EFO, such as 'nephritis'. E.g. searching for 'inflammation' and/or 'inflammatory' in definition of disease terms, adding appropriate axioms...

**Comment by paolaroncaglia** [comment]
I summarized and (hopefully) improved our suggestions in a new ticket, where I also mentioned MONDO and HP editors:
https://github.com/EBISPOT/efo/issues/372
So I'm moving this one to the Done queue.
