### ISSUE TITLE
Create an EFO term to capture self-reporting as opposed to diagnosis by objective/measurable criteria

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#28]
This is particularly needed for GWAS. Example term http://www.ebi.ac.uk/ols/ontologies/omit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOMIT_0026966

Unclear where this could go and what parent/siblings it should come with

**Comment by siiraa** [comment]
see if this fits in the scope of another ontology.

**Comment by paolaroncaglia** [comment]
We now have EFO:0009799 'self-reported trait' ("Characteristics of an individual that are reported by the individual, usually to medical staff, including via questionnaires, rather than observed or measured directly by medical staff."). We made it a subclass of 'quality'.
