### ISSUE TITLE
Autoimmune polyendocrinopathy type 1 synonym

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#281]
Can you please add 'Autoimmune-poly-endocrinopathy-candidiasis-ectodermal-dystrophy syndrome' as a synonym of APECED, please?
It's not represented currently while it's actually the full name of the disease.

https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_3453

**Comment by paolaroncaglia** [comment]
@gkos-bio 
I added the synonym "autoimmune-poly-endocrinopathy-candidiasis-ectodermal-dystrophy syndrome" to 'Autoimmune polyendocrinopathy type 1'. It will be visible after the next EFO release (Nov. 15th). Thanks.
