### ISSUE TITLE
Review 'measurement' hierarchy

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#29]
Currently there are several dozen factors all listed under the node "measurement".
As the EFO is used to annotate GWAS, and we consider the terms "pQTLs" (for protein level associations) and "mQTLs" (for metabolite associations) it would be useful to have specific nodes for "protein level measurement", "metabolite level measurement".
There seems to be another set of specific physiological measurements, for example "aortic root size". These may benefit from the MPO precedent of "organ morphology" and "organ physiology" terms.

Review 'mental or behavioural disorder measurement' hierarchy
The hierarchy is currently a little flat and could do with more structure and axiomatisation

**Comment by fauman** [comment]
Hi - I'm glad to see there are "protein measurement" and "metabolite measurement" nodes now.  However both could use a lot of cleanup.
To focus on the "protein measurement" node, it would be nice for all of the relevant terms to be tagged with the appropriate UNIPROT IDs.
Currently it looks like about 19 protein measurement terms do contain links to uniprot.  However there are (or will soon be) several thousand different protein measurement endpoints, and of course we could imagine one node for each unique human protein.
On a related note, the entry for IL6 receptor (EFO:0004814) lists two uniprot IDs.  One is for the IL6 receptor and one is for IL6 itself.  There is also a spurious "is_a" link to "cytokine measurement", but IL6 receptor is a cytokine receptor, not a cytokine.

**Comment by paolaroncaglia** [comment]
Tagging this for potential (internal) proposal in case anyone would like to help reviewing the measurement hierarchy.

**Comment by fauman** [comment]
Hey count me in - I'm not sure how much I can do directly, but I certainly have some strong opinions on the subject :)

**Comment by paolaroncaglia** [comment]
Thanks @fauman ! We'll keep you posted.

**Comment by paolaroncaglia** [comment]
@zoependlington I suspect that (at least part of) this older ticket would be addressed by more recent plans, e.g. #1553 and #1554 may be related but I don't have access to the full info there. If that's the case, this ticket can be closed; if not, is there any existing appropriate ticket or Epic that it should be linked to? Thanks.

**Comment by zoependlington** [comment]
I believe this is superseded by current tickets being worked on, therefore I'll close.
