### ISSUE TITLE
embryonic and synthetic lethality

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#293]
Would it be possible to define the following terms in EFO, please:
"embryonic lethality"
"synthetic lethality"

**Comment by paolaroncaglia** [comment]
@gkos-bio 
For "embryonic lethality", we could import MP:0008762 'embryonic lethality' (http://www.ontobee.org/ontology/MP?iri=http://purl.obolibrary.org/obo/MP_0008762). The MP definition "Death of an animal within the embryonic period prior to organogenesis (Mus: prior to E14) [database_cross_reference: MGI:csmith][database_cross_reference: MGI:csmith]" could be edited to make it broader: "Death of an animal (including human) within the embryonic period prior to organogenesis. In mouse, this is defined as prior to E14." 
So perhaps we'd prefer to mint a new EFO term instead and add a definition_citation of MP:0008762. Would this term be needed for human as well as mouse in Open Targets?

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor:
For "synthetic lethality", we should create a new EFO term and reference https://en.wikipedia.org/wiki/Synthetic_lethality as well as https://www.ebi.ac.uk/ols/ontologies/sbo/terms?iri=http%3A%2F%2Fbiomodels.net%2FSBO%2FSBO_0000502.

**Comment by paolaroncaglia** [comment]
- [ ] Add EFO:NEW ‘embryonic lethality’
Subclass of ‘phenotype’ (a bit generic, but I can’t see a more appropriate parent in EFO, and that’s where ‘premature birth’ sits)
Definition: "Death of an embryo (human or animal) within the embryonic period prior to organogenesis. In mouse, this is defined as prior to E14."
Definition_citation: MP:0008762 'embryonic lethality'
- [ ] Write ID of new EFO term here

- [ ] Add EFO:NEW ‘synthetic lethality’
Subclass of ‘phenotype’ (same as above)
Definition: “Death arising when a combination of deficiencies in the expression of two or more genes leads to cell death, whereas a deficiency in only one of these genes does not.”
Definition_citation: https://en.wikipedia.org/wiki/Synthetic_lethality;  https://www.ebi.ac.uk/ols/ontologies/sbo/terms?iri=http%3A%2F%2Fbiomodels.net%2FSBO%2FSBO_0000502
- [ ] Write ID of new EFO term here

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Your new terms are
EFO:0009427 ‘embryonic lethality’
EFO:0009428 ‘synthetic lethality’
They'll be live in the December release.
