### ISSUE TITLE
chromosome 1p36 deletion syndrome

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#294]
Missing in EFO but present in MONDO.
Will this be included in EFO3?

**Comment by zoependlington** [comment]
Hi @gkos-bio,
1p36 deletion syndrome is in EFO as Orphanet_1606, see [here](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_1606).

In EFO 3 it is mapped to [MONDO:0011929](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011929).

Let me know if there are any additions/edits to make to this term.

**Comment by gkos-bio** [comment]
Thank you. I found it.
