### ISSUE TITLE
Mycobacterium Infection

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#298]
A non tuberculous mycobacterium infection is a synonym of recurrent pneumonia.
Mycobacterium leprae infection is a synonym of leprosa.

Mycobacterium Infection should be a parent of both but is missing in EFO.

**Comment by zoependlington** [comment]
For self/other curator:

- [ ] **EFO:NEW** Mycobacterium infection
     - subclass of bacterial disease (EFO_0000771)
     - **Definition:** Infections with bacteria of the genus Mycobacterium.
     - **Synonym:** Mycobacterial infection
     - **X-ref:** NCIT:C26831

- [ ] **EFO:EDIT1** recurrent pneumonia (EFO_0007461)
     - add as subclass of Mycobacterium infection (EFO:NEW)

- [ ] **EFO:EDIT2** leprosy (EFO_0001054)
    - reclassify as subclass of Mycobacterium infection (EFO:NEW) not bacterial disease (EFO_0000771)
