### ISSUE TITLE
Infarction as a pathological process

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#299]
This would be the equivalent in MeSH
https://meshb.nlm.nih.gov/record/ui?ui=D007238
And in NCIt: Infarction  NCIT:C25738

**Comment by S2Ola** [comment]
EFO: NEW

- **subclass** of pathological process (OBI_1110122)
- **Definition:** A localised pathological necrosis of tissue resulting from obstruction of the blood supply usually by a thrombus, an embolus, or vascular torsion.

- **Synonyms:**  Infarcts

- **X-ref:**  NCI Thesaurus: C25738, MSH:D007238

**Comment by S2Ola** [comment]
New term infarction added as a subclass of pathological process 
[http://www.ebi.ac.uk/efo/EFO_0009463]
**term:** infarction
