### ISSUE TITLE
Import axioms that share entities in EFO 3

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#30]
If a subclass or equivalent axiom in the external ontology contains terms in the list of terms to be imported, we can safely import that axioms. E.g. if A subClassOf p some B and both A and B are on the slims list, then this axiom will be imported. If A subClassOf p some C and C is not in the slims, we will ignore this axiom.

**Comment by siiraa** [comment]
suspected this might have been done already, please close this if it is @simonjupp

**Comment by simonjupp** [comment]
done in EFO 3 pipeline
