### ISSUE TITLE
pulmonary fibrosis missing in EFO

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#300]
Please can you make sure that acute pulmonary fibrosis is classified under pulmonary fibrosis (with a new EFO id) when merging with MONDO?

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Just to make sure, by ‘acute pulmonary fibrosis’ do you mean EFO:0000768 ‘idiopathic pulmonary fibrosis’? If so, I will

- [ ] Add EFO:NEW pulmonary fibrosis
Subclass of ’interstitial lung disease’ and of ‘fibrosis’
Definition: “Chronic progressive interstitial lung disorder characterized by the replacement of the lung tissue by connective tissue, leading to progressive dyspnea, respiratory failure, or right heart failure. Causes include chronic inflammatory processes, exposure to environmental irritants, radiation therapy, autoimmune disorders, certain drugs, or it may be idiopathic (no identifiable cause).”
Definition_citation: MONDO:0002771

- [ ] Edit EFO:0000768 ‘idiopathic pulmonary fibrosis:
Reclassify it as subclass of ‘pulmonary fibrosis’
Add synonym ‘acute pulmonary fibrosis’?
