### ISSUE TITLE
Atherosclerotic lesion

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#301]
New term:
Atherosclerotic lesion  (HP:0031678), 
atherosclerotic lesions  (MP:0005338), 
Atherosclerotic Plaque  (NCIT:C78739),
Atherosclerotic Plaque (MeSH:D058226)

**Comment by paolaroncaglia** [comment]
@gkos-bio 
@simonjupp 
@zoependlington 
This is tricky. Atherosclerosis (already in EFO as a disease) is defined uniquely and solely by the build up of (atherosclerotic) plaques (a phenotype). The two terms might overlap perfectly, except that, I guess, clinicians may need to distinguish between an actual observation (via scans or in post-mortem tissues) and the diagnosis when the ‘disease’ is advanced and there are symptoms. HP has ‘Atherosclerotic lesion’ as an is_a child of ‘Atherosclerosis’, but this wouldn’t sound correct in EFO. Proposal:

- [ ] Create EFO:NEW ‘atherosclerotic lesion’ under EFO HP ‘Abnormality of the vasculature’, and
- [ ] Edit EFO ‘atherosclerosis’ by adding disease_has_feature  ‘atherosclerotic lesion’?

**Comment by zoependlington** [comment]
@paolaroncaglia this sounds like a great plan to me and makes the most sense!

**Comment by paolaroncaglia** [comment]
Agreed at today's meeting

**Comment by paolaroncaglia** [comment]
- [ ] Import HP:0031678 ‘atherosclerotic lesion’ 
Subclass of EFO HP ‘Abnormality of the vasculature’
“A lesion associated with atherosclerosis, a multifactorial and multipart progressive disease manifested by the focal development within the arterial wall of lesions. Atherosclerotic lesions range from the development of a fatty streak, plaque progression, and plaque disruption, and ddemonstrate consistent morphological characteristics, which indicate that each type may stabilize temporarily or permanently and that progression to the next type may require an additional stimulus.”
PMID:8172861
MP:0005338
NCIT:C78739
MeSH:D058226
Synonym: atherosclerotic plaque

- [ ] Copy ID of new term here
 
- [ ] Edit EFO ‘atherosclerosis’ by adding disease_has_feature ‘atherosclerotic lesion’
