### ISSUE TITLE
leiomyoma

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#303]
leiomyoma  is defined in MONDO 
MONDO:0001572
Can we check that this term will be in EFO when merging, please?

**Comment by zoependlington** [comment]
leiomyoma (MONDO_0001572) is definitely in EFO 3 as a child of benign smooth muscle neoplasm (EFO_1000121) and with the child terms: leiomyomatosis (MONDO_0003295), myofibroma (EFO_1000389), renal leiomyoma (EFO_1000050) and uterine fibroid (EFO_0000731).
