### ISSUE TITLE
hemolysis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#304]
Can 'hemolysis' be added to EFO as a pathological process please?

**Comment by S2Ola** [comment]
For self or EFO editor : 

**EFO :** NEW 
- **subclass** of pathological process (OBI_1110122)
- **Definition:**  Disruption of the integrity of the erythrocyte membrane causing release of hemoglobin. [ NCI ]
- **Synonyms:** hemolysis, hemolytic 
- **X-ref:** NCIT_C37965

**Comment by S2Ola** [comment]
For self or EFO Editor: 
**EFO:**  new axiom  'disease has feature' some hemolysis'

**Comment by S2Ola** [comment]
For Self or EFO Editor; 
**EFO:** new axiom ''disease has feature' some hemolysis'  makes all the subclasses of diseases to 'has feature' some hemolysis which may not be true in some cases like  " _alpers syndrome_ , _brain_ _edema_ among others.
