### ISSUE TITLE
Neuralgia

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#306]
Neuralgia is a frequent term used on Medical literature.
It's defined in MeSH as 'Neuralgia' and have subtypes too.

It's defined in MONDO as neuralgia  (MONDO:0021667).

This ticket is to make sure it's part of EFO in the future.

**Comment by zoependlington** [comment]
For self or other editor!

- [ ] **EFO:NEW** neuralgia
     - subclass of peripheral neuropathy (EFO_0003100)
     - **Def:** Intense painful sensation along a nerve or group of nerves. It is caused by irritation or trauma to a nerve or inflammation of a nerve. [ NCI ]
     - **X-refs:** MONDO:0021667 || NCIT:C79695 || OMIT:0010464
     - add to EFO 3 mapping file

- [ ] **EFO:EDIT1** facial neuralgia (EFO_0009380)
     - Remove subclass classification and make a child of neuralgia

- [ ] **EFO:EDIT2** trigeminal neuralgia (EFO_1001219)
     - Remove subclass classification to neuropathy and make a child of neuralgia
     - Keep disease location classification

- [ ] **EFO:EDIT3** Herpes Zoster (EFO_0006510)
    - disease has feature some neuralgia

**Comment by zoependlington** [comment]
Here is the ID for the new term:

EFO_0009430 | neuralgia
