### ISSUE TITLE
Transverse myelitis/Acute transverse myelitis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#308]
These diseases are present in MONDO but not in EFO.
Can we check this is indeed part of EFO3 after merging, please?
These diseases should be classified under myelitis:
http://www.ebi.ac.uk/efo/EFO_1001472

**Comment by zoependlington** [comment]
I have added acute transverse myelitis (http://purl.obolibrary.org/obo/MONDO_0015342) and transverse myelitis (http://purl.obolibrary.org/obo/MONDO_0021553) to our import file.

Both import as children of myelitis (EFO_1001472). Acute transverse myelitis also imports as a child of disorder of medulla oblongata (MONDO_0015141).
