### ISSUE TITLE
Fresh import of UBERON into EFO

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#310]
We need a fresh import of UBERON to be pulled into EFO3.

**Comment by S2Ola** [comment]
- [ ] Actions for self 
1.  All terms imported from UBERON i.e terms with UBERON IDs in Efo will be extracted and populated into a term file using a sparql query.  
2. The terms will be extracted from the current UBERON file 
3. The extracted terms from the current UBERON is the merged into EFO 
4. Review the merged terms in EFO to detect duplicates properties 
5. Remove every duplicates in EFO that is not from UBERON and keep the ones from EFO by tagging the EFO duplicate 
6.  Check that the UBERON terms in EFO only has same properties with the UBERON source file
7.  Write a script and included in the EFO makefile

**Comment by S2Ola** [comment]
- [1 ] Check the impact of the terms from UBERON on EFO
- [2 ] Compare and review the subclassOf the terms from updated UBERON with the updated EFO  terms  and write a report on the impact of the new imports
- [3 ] Use OWLAPI to do the comparison between the subclass of EFO and UBERON imported terms

Check redundant axioms to see if ;
- [1] the axioms are added into EFO by the editors
- [2] the axioms are added by UBERON and their relevance to EFO
- [3] write a report to identify the impacts

**Comment by S2Ola** [comment]
Actions : 

1. The list of all UBERON terms (uberon ID: oboInOwl:id) in EFO has been compiled through a sparql query via the RDF platform sparql endpoint
2. The list is used to create a subset ontology from latest UBERON ontology using  robot command extract --method BOT... 
3. The extracted Uberon subset ontology is been compared with updated EFO file  to see the impact of the new subclasses on EFO

**Comment by S2Ola** [comment]
Action : 
Look at the explanation for the unsatisfiable reasoning in protege. 
Report reason for this
