### ISSUE TITLE
Parse error of efo.owl

### ISSUE THREAD

**Issue by ppavlidis** [EBISPOT/efo#317]
**What is wrong**: Parsing of https://raw.githubusercontent.com/EBISPOT/efo/master/efo.owl with the Jena library fails with 

`(line 336086 column 41): {W116} ISO-639 does not define langauge: 'ebi'.`

This is the offending block (problem bolded):

> <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0004445">
        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/OBI_0000181"/>
        <obo:IAO_0000115>A cohort is a collection of material entities grouped together based on some common property of interest, such as age or disease stage.</obo:IAO_0000115>
        <obo:IAO_0000117 **xml:lang="ebi"**>Functional Genomics group </obo:IAO_0000117>
        <efo:NCI_Thesaurus_definition_citation rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCIt:C61512</efo:NCI_Thesaurus_definition_citation>
        <rdfs:label>cohort</rdfs:label>
    </owl:Class>

This is the only occurrence in the file.

**How to fix it**: Presumably remove that attribute, or suggest a work-around

Thank you!

**Comment by paolaroncaglia** [comment]
@ppavlidis Thanks for pointing that out. We'll fix it in time for our next release (scheduled for Dec. 17th), but should you need a patch urgently, please let us know. 

Note for self/EFO editor: "ebi" should be changed to "en" in the offending block above.

**Comment by simonjupp** [comment]
And check for any additional instance of this and fix

**Comment by zoependlington** [comment]
There are a handful of [language: fr] instances where the language is wrong, too, when doing a search in Protégé for "language:". e.g. Sezary's disease, where it seems all annotations have a language attribute that is French, the term editor is Sirarat Sarntivijai [language: fr] and in Sjögren-Larsson syndrome where the synonym "Sjogren-Larsson syndrome" has the "language: fr" attribute.
