### ISSUE TITLE
8 cell line NTRs

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#321]
On behalf of the ENCODE project, I am requesting EFO terms for the cell lines in this spreadsheet:
https://docs.google.com/spreadsheets/d/11nzBFfo9fRtIh4FDfIB1f8-gsyL-_6ij3PdhK4zC0KM/edit?usp=sharing
Thank you,
Jason

**Comment by paolaroncaglia** [comment]
Note for self: Jason's spreadsheet is view only, so I made a copy that I can edit (https://docs.google.com/spreadsheets/d/1NKqBNEsiJ71PVQ-PtxCcRi17z_m2RZtANorXG-79eik/edit#gid=0) as I will also need to modify some fields (e.g. replace article links with PMIDs).

**Comment by paolaroncaglia** [comment]
Notes for self:

- [ ] Edit EFO:0005705 'olfactory neurosphere cell line' to remove the synonyms C1 100 08 0003, C1 100 08 0013, C1 100 08 0002 (as they will now be represented by new terms)

**Comment by paolaroncaglia** [comment]
@simonjupp @daniwelter @zoependlington 
I assume we would not add URLs of "internal" protocol documents as definition citations (e.g. https://www.encodeproject.org/documents/ca3a16d0-3a6b-4b1c-8bf2-fc470ae0f9d8/@@download/attachment/Olfneurosphere_Crawford_protocol.pdf), or URLs of database entries (e.g. http://genome.cse.ucsc.edu/cgi-bin/hgEncodeVocab?ra=encode%2Fcv.ra&term=%22iPS_CWRU1%22). Is this correct?
Both examples are for human cell lines. The first example has a PMID so I can add that as def_cit; the second example has no other reference. Thanks.

(Note for self: depending on feedback, add URLs to EFO terms in spreadsheet if appropriate.)

**Comment by jahilton** [comment]
Thanks so much for your help and for the feedback on future term requests!

**Comment by paolaroncaglia** [comment]
@jahilton you're welcome!

**Comment by zoependlington** [comment]
Add the citations as a comment/appropriate property eg. definition citation (although we have misused it) so that it is not lost. 
May need to add column to Webulous template to support this.
