### ISSUE TITLE
Classification of mental/psychiatric/behavioural disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#324]
Stemming from https://github.com/monarch-initiative/mondo/issues/532
Summing up @cmungall: "I think we can do a much better job with mental/psychiatric disorders, this is not trivial and needs a lot of work".
We should keep an eye on how MONDO addresses classification of mental/psychiatric/behavioural disorders, and possibly modify our own classification of terms such as 'acute stress reaction' accordingly.

**Comment by paolaroncaglia** [comment]
Note for self/EFO editors: this will benefit from the discussion on whether to adhere systematically to the Diagnostic and Statistical Manual of Mental Disorders (DSM) or not - and what to do if not; discussion started in #275.

**Comment by paolaroncaglia** [comment]
Tagging this as potential proposal in case any experts wish to weigh in on the current classification of mental/psychiatric/behavioural disorders in EFO (and Mondo).

**Comment by zoependlington** [comment]
Agreed, this can be closed.
