### ISSUE TITLE
HFFc6 & HGADFN167 cell lines relationship to 'fibroblast'

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#326]
We have suggestions for more definitive connections between 2 cell lines to fibroblast. We think the connection existing for IMR-90 [EFO:0001196] is a good example of what should exist for these 2 terms...

HFFc6 [EFO:0009318] derives from some fibroblast [CL:0000057]
(rather than derives from some fibroblast derived cell line, a relationship that is already captured with SubclassOf)

HGADFN167 [EFO:0005909] derives from some fibroblast [CL:0000057]
(rather than derives from some cell type, which isn't all that informative)

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT1** HFFc6 (EFO:0009318)
     -  should be derives_from some (fibroblast and (part_of some ('prepuce of penis' and (part_of some 'Homo sapiens'))))

- [ ] **EFO:EDIT2** HGADFN167 (EFO:0005909)
     - should be derives_from some (fibroblast and (part_of some ('organism part' and (part_of some 'Homo sapiens'))))
