### ISSUE TITLE
Edit 'stage I/II endometrioid carcinoma'?

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#329]
See https://github.com/monarch-initiative/mondo/issues/490

**Comment by zoependlington** [comment]
- [ ] **EFO:EDIT1** stage I endometrioid carcinoma
          - Move to subclass of endometrioid carcinoma (EFO_0000466) rather than carcinoma
- [ ] **EFO:EDIT2** stage II endometrioid carcinoma
     - Move to subclass of endometrioid carcinoma (EFO_0000466) rather than carcinoma
     - Edit definition so last line reads: "The cancer has spread into connective tissue of the cervix, but has not spread outside the uterus." And there is a space after the first ".".
