### ISSUE TITLE
42 cell lines derives from updates

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#338]
Below are 42 cell lines with more specific annotations, mostly connecting to appropriate UBERON terms (in place of the generic 'organism_part')
Please let me know if I can provide additional information...

HS-5 [EFO:0005282]
should be derives_from some (fibroblast [CL:0000057] and (part_of some (bone marrow [UBERON:0002371] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CRL-11882.aspx

U2OS [EFO:0002869]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (bone [UBERON:0001474] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/HTB-96.aspx

UCH-1 [EFO:0004389]
should be derives_from some (cell_type [] and (part_of some (sacral vertebra [UBERON:0001094] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CRL-3217.aspx

HS-27A [EFO:0005283]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (bone marrow [UBERON:0002371] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/products/all/CRL-2496.aspx

SH-SY5Y [EFO:0002717]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (bone marrow [UBERON:0002371] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CRL-2266.aspx

glioblastoma H54 [EFO:0002782]
should be derives_from some (cell_type [] and (part_of some (brain [UBERON:0000955] and (part_of some 'Homo sapiens'))))
evidence:https://cansar.icr.ac.uk/cansar/cell-lines/D54/, http://genome.ucsc.edu/ENCODE/protocols/cell/human/D54_Crawford_protocol.pdf

SK-N-MC [EFO:0002860]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (brain [UBERON:0000955] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/products/all/HTB-10.aspx

HT1080 [EFO:0002059]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (connective tissue [UBERON:0002384] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CCL-121.aspx

NIH3T3 [EFO:0001222]
should be derives_from some (fibroblast [CL:0000057] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/products/all/CRL-1658.aspx

3T3-L1 [EFO:0001084]
should be derives_from some (fibroblast [CL:0000057] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/products/all/CL-173.aspx

S1 [EFO:0002078]
should be derives_from some (cell_type [] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Drosophila melanogaster'))))
evidence:https://dgrc.bio.indiana.edu/product/View?product=9

C3H10T1/2 [EFO:0002816]
should be derives_from some (fibroblast [CL:0000057] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/Products/All/CCL-226.aspx

ELF-1 [EFO:0005901]
should be derives_from some (embryonic stem cell [CL:0002322] and (part_of some (embryo [UBERON:0000922] and (part_of some 'Homo sapiens'))))
evidence:https://www.wicell.org/home/stem-cells/catalog-of-stem-cell-lines/elf1.cmsx?closable=true

Caki2 [EFO:0002150]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (kidney [UBERON:0002113] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/HTB-47.aspx

SW480 [EFO:0002083]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (colon [UBERON:0001155] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CCL-228.aspx

HCT116 [EFO:0002824]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (colon [UBERON:0001155] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/products/all/CCL-247.aspx

PC-9 [EFO:0002847]
should be derives_from some (cell_type [] and (part_of some (lung [UBERON:0002048] and (part_of some 'Homo sapiens'))))
evidence:https://www.sigmaaldrich.com/catalog/product/sigma/cb_90071810?lang=en&region=US

NCO-H460 [EFO:0003044]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (lung [UBERON:0002048] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/HTB-177.aspx

C2C12 [EFO:0001098]
should be derives_from some (myoblast [CL:0000056] and (part_of some (musculature [UBERON:0001015] and (part_of some 'Mus musculus'))))
evidence:https://www.atcc.org/Products/All/CRL-1772.aspx

OVACAR3 [EFO:0003061]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (ovary [UBERON:0000992] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/HTB-161.aspx

Panc1 [EFO:0002713]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (pancreas [UBERON:0001264] and (part_of some 'Homo sapiens'))))
evidence:https://www.sigmaaldrich.com/catalog/product/sigma/cb_87092802?lang=en&region=US

MEL cell line [EFO:0003971]
should be derives_from some (mouse erythroleukemia cell [EFO:0003970] and (part_of some (spleen [UBERON:0002106] and (part_of some 'Mus musculus'))))
evidence:https://www.ncbi.nlm.nih.gov/pubmed/21416373

D341Med [EFO:0002157]
should be derives_from some (cell_type [] and (part_of some (brain [UBERON:0000955] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/en/Products/Cells_and_Microorganisms/By_Tissue/Brain/HTB-187.aspx

HeLa-S3 [EFO:0002791]
should be derives_from some (epithelial cell [CL:0000066] and (part_of some (uterine cervix [UBERON:0000002] and (part_of some 'Homo sapiens'))))
evidence:https://atcc.org/Products/All/CCL-2.2.aspx?slp=1

GM12812 [EFO:0001155]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12812&product=CC

GM12813 [EFO:0001156]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12813&Product=CC

GM12872 [EFO:0001159]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12872&Product=CC

GM12873 [EFO:0001160]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12873&Product=CC

GM12874 [EFO:0001161]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12874&Product=CC

GM12875 [EFO:0001162]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12875&Product=CC

GM06990 [EFO:0002783]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM06990

GM12878 [EFO:0002784]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12878&Product=CC

GM12891 [EFO:0002785]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12891&Product=CC

GM12892 [EFO:0002786]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12892&Product=CC

GM19238 [EFO:0002788]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19238&Product=CC

GM19239 [EFO:0002789]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19239&Product=CC

GM19240 [EFO:0002790]
should be derives_from some (B cell [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19240&Product=CC

K562 [EFO:0002067]
should be derives_from some (lymphocyte [CL:0000542] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.sigmaaldrich.com/catalog/product/sigma/cb_89121407?lang=en&region=US&gclid=EAIaIQobChMIjriUsZWq3wIVEh6tBh01pwF_EAAYASAAEgLhBPD_BwE

NAMALWA [EFO:0002246]
should be derives_from some (B-Lymphocyte [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.sigmaaldrich.com/catalog/product/sigma/cb_87060801?lang=en&region=US&gclid=EAIaIQobChMIjPy10Jiq3wIVcyCtBh1y0wk_EAMYASAAEgLz8fD_BwE, https://www.atcc.org/products/all/CRL-1432.aspx#generalinformation

RPMI8226 [EFO:0002322]
should be derives_from some (B-Lymphocyte [CL:0000236] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.atcc.org/Products/All/CCL-155.aspx

CMK [EFO:0003037]
should be derives_from some (megakaryoblast [CL:0000553] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.ncbi.nlm.nih.gov/pubmed/2665839

HL-60 [EFO:0002793]
should be derives_from some (lymphocyte [CL:0000542] and (part_of some (blood [UBERON:0000178] and (part_of some 'Homo sapiens'))))
evidence:https://www.sigmaaldrich.com/catalog/product/sigma/cb_98070106?lang=en&region=US&gclid=EAIaIQobChMIw-Pa7aCq3wIVEMRkCh2bGA2iEAAYAiAAEgKrzPD_BwE

**Comment by paolaroncaglia** [comment]
@jahilton 
Thanks. Due to the holidays, there was a time lag in processing requests. We will address yours in the next sprint, therefore the changes will be visible in our mid-February release. Hopefully that will be acceptable to you, otherwise please let us know. Thanks.

**Comment by jahilton** [comment]
@paolaroncaglia Not a problem at all. Happy new year!

**Comment by paolaroncaglia** [comment]
@jahilton thanks, you too!

**Comment by zoependlington** [comment]
- [ ] HS-5 [EFO:0005282]
     - **Correct to:** derives_from some (fibroblast and (part_of some (bone marrow [UBERON:0002371] and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CRL-11882.aspx

- [ ] U2OS [EFO:0002869]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (bone and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/HTB-96.aspx

- [ ] UCH-1 [EFO:0004389]
     - **Correct to:** derives_from some (cell_type and (part_of some (sacral vertebra and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CRL-3217.aspx

- [ ] HS-27A [EFO:0005283]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (bone marrow and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/products/all/CRL-2496.aspx

- [ ] SH-SY5Y [EFO:0002717]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (bone marrow and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CRL-2266.aspx

- [ ] glioblastoma H54 [EFO:0002782]
     - **Correct to:** derives_from some (cell_type and (part_of some (brain and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://cansar.icr.ac.uk/cansar/cell-lines/D54/, http://genome.ucsc.edu/ENCODE/protocols/cell/human/D54_Crawford_protocol.pdf

- [ ] SK-N-MC [EFO:0002860]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (brain and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/products/all/HTB-10.aspx

- [ ] HT1080 [EFO:0002059]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (connective tissue and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CCL-121.aspx

- [ ] NIH3T3 [EFO:0001222]
     - **Correct to:** derives_from some (fibroblast and (part_of some (embryo and (part_of some 'Mus musculus'))))
     - **Def cite:** https://www.atcc.org/products/all/CRL-1658.aspx

- [ ] 3T3-L1 [EFO:0001084]
     - **Correct to:** derives_from some (fibroblast and (part_of some (embryo and (part_of some 'Mus musculus'))))
     - **Def cite:** https://www.atcc.org/products/all/CL-173.aspx

- [ ] S1 [EFO:0002078]
     - **Correct to:** derives_from some (cell_type and (part_of some (embryo and (part_of some 'Drosophila melanogaster'))))
     - **Def cite:** https://dgrc.bio.indiana.edu/product/View?product=9

- [ ] C3H10T1/2 [EFO:0002816]
     - **Correct to:** derives_from some (fibroblast and (part_of some (embryo and (part_of some 'Mus musculus'))))
     - **Def cite:** https://www.atcc.org/Products/All/CCL-226.aspx

- [ ] ELF-1 [EFO:0005901]
     - **Correct to:** derives_from some (embryonic stem cell and (part_of some (embryo and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.wicell.org/home/stem-cells/catalog-of-stem-cell-lines/elf1.cmsx?closable=true

- [ ] Caki2 [EFO:0002150]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (kidney and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/HTB-47.aspx

- [ ] SW480 [EFO:0002083]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (colon and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CCL-228.aspx

- [ ] HCT116 [EFO:0002824]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (colon and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/products/all/CCL-247.aspx

- [ ] PC-9 [EFO:0002847]
     - **Correct to:** derives_from some (cell_type and (part_of some (lung and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.sigmaaldrich.com/catalog/product/sigma/cb_90071810?lang=en&region=US

- [ ] NCI-H460 [EFO:0003044]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (lung and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/HTB-177.aspx

- [ ] C2C12 [EFO:0001098]
     - **Correct to:** derives_from some (myoblast and (part_of some (musculature and (part_of some 'Mus musculus'))))
     - **Def cite:** https://www.atcc.org/Products/All/CRL-1772.aspx

- [ ] OVCAR3 [EFO:0003061]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (ovary and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/HTB-161.aspx

- [ ] Panc1 [EFO:0002713]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (pancreas and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.sigmaaldrich.com/catalog/product/sigma/cb_87092802?lang=en&region=US

- [ ] MEL cell line [EFO:0003971]
     - **Correct to:** derives_from some (mouse erythroleukemia cell and (part_of some (spleen and (part_of some 'Mus musculus'))))
     - **Def cite:** https://www.ncbi.nlm.nih.gov/pubmed/21416373

- [ ] D341Med [EFO:0002157]
     - **Correct to:** derives_from some (cell_type and (part_of some (brain and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/en/Products/Cells_and_Microorganisms/By_Tissue/Brain/HTB-187.aspx

- [ ] HeLa-S3 [EFO:0002791]
     - **Correct to:** derives_from some (epithelial cell and (part_of some (uterine cervix and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://atcc.org/Products/All/CCL-2.2.aspx?slp=1

- [ ] GM12812 [EFO:0001155]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12812&product=CC

- [ ] GM12813 [EFO:0001156]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12813&Product=CC

- [ ] GM12872 [EFO:0001159]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12872&Product=CC

- [ ] GM12873 [EFO:0001160]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12873&Product=CC

- [ ] GM12874 [EFO:0001161]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12874&Product=CC

- [ ] GM12875 [EFO:0001162]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12875&Product=CC

- [ ] GM06990 [EFO:0002783]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM06990

- [ ] GM12878 [EFO:0002784]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12878&Product=CC

- [ ] GM12891 [EFO:0002785]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12891&Product=CC

- [ ] GM12892 [EFO:0002786]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM12892&Product=CC

- [ ] GM19238 [EFO:0002788]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19238&Product=CC

- [ ] GM19239 [EFO:0002789]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19239&Product=CC

- [ ] GM19240 [EFO:0002790]
     - **Correct to:** derives_from some (B cell and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.coriell.org/0/Sections/Search/Sample_Detail.aspx?Ref=GM19240&Product=CC

- [ ] K562 [EFO:0002067]
     - **Correct to:** derives_from some (lymphocyte and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.sigmaaldrich.com/catalog/product/sigma/cb_89121407?lang=en&region=US&gclid=EAIaIQobChMIjriUsZWq3wIVEh6tBh01pwF_EAAYASAAEgLhBPD_BwE

- [ ] NAMALWA [EFO:0002246]
     - **Correct to:** derives_from some (B-Lymphocyte and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.sigmaaldrich.com/catalog/product/sigma/cb_87060801?lang=en&region=US&gclid=EAIaIQobChMIjPy10Jiq3wIVcyCtBh1y0wk_EAMYASAAEgLz8fD_BwE, https://www.atcc.org/products/all/CRL-1432.aspx#generalinformation

- [ ] RPMI8226 [EFO:0002322]
     - **Correct to:** derives_from some (B-Lymphocyte and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.atcc.org/Products/All/CCL-155.aspx

- [ ] CMK [EFO:0003037]
     - **Correct to:** derives_from some (megakaryoblast and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.ncbi.nlm.nih.gov/pubmed/2665839

- [ ] HL-60 [EFO:0002793]
     - **Correct to:** derives_from some (lymphocyte and (part_of some (blood and (part_of some 'Homo sapiens'))))
     - **Def cite:** https://www.sigmaaldrich.com/catalog/product/sigma/cb_98070106?lang=en&region=US&gclid=EAIaIQobChMIw-Pa7aCq3wIVEMRkCh2bGA2iEAAYAiAAEgKrzPD_BwE
