### ISSUE TITLE
Check synonyms for Glioma (EFO_0005543)

### ISSUE THREAD

**Issue by MichaelaEBI** [EBISPOT/efo#340]
'Triple-Negative Breast Carcinoma' is listed as a synonym for '[Glioma](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0005543)'. Is this correct or should it be removed from the list of synonyms?

**Comment by paolaroncaglia** [comment]
Note for EFO editor:
Possibly due to a mistake, EFO:0005543 'glioma' has the incorrect xrefs NCIT:C71732 'Triple-Negative Breast Carcinoma' and the incorrect synonym 'Triple-Negative Breast Carcinoma'. 
- [ ] Delete both.
