### ISSUE TITLE
Add new EFO terms for non-cancer NCIT entries

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#341]
We need to add the following new EFO terms to represent non-cancer NCIT entries:
(remember to add NCIT and ICD10 xrefs)

- [x] Under 'injury':
abdominal injury
caustic injury
crush injury
head injury
heart injury
knee injury
leg injury
limb injury
peripheral nerve injury

EFO:0009502 abdominal injury
EFO:0009503 caustic injury
EFO:0009504 crush injury
EFO:0009505 head injury
EFO:0009506 heart injury
EFO:0009507 knee injury
EFO:0009508 leg injury
EFO:0009509 limb injury
EFO:0009510 peripheral nerve injury

- [x] Under 'bone fracture':
lower extremity fracture (then check if some children of 'bone fracture' should be classified under it)
multiple fractures
upper extremity fracture (then check if some children of 'bone fracture' should be classified under it)
wrist fracture

EFO:0009512 lower extremity fracture
EFO:0009513 multiple bone fractures
EFO:0009514 upper extremity fracture
EFO:0009515 wrist fracture

For the following, placement needs to be evaluated:

- [x] burn 
subclass of injury
"A traumatic injury involving interruption of tissue cohesiveness that results from exposure to caustic chemicals, extreme heat, extreme cold or excessive radiation. [ NCI ]"
(then classify 'eye burns' and 'sunburn' under it)

EFO:0009516 burn

- [x] checkup
subclass of medical procedure
"A general examination or inspection, especially one carried out by a doctor or dentist. [ NCI ]"

EFO:0009517 checkup

- [x] complication
subclass of disease (based on the NCIT definition; NCIT has it under 'finding')
"Any disease or disorder that occurs during the course of, or because of, another disease, treatment, or procedure. [ NCI ]"

EFO:0009518 complication

- [x] device complication
subclass of complication
"Any problem arising from the use of a medical device. [ NCI ]"

EFO:0009519 device complication

- [x] contraception
subclass of 'medical procedure'
"The prevention of conception or impregnation by the use of devices or drugs or surgery. [ NCI ]"

EFO:0009520 contraception

- [x] dislocation
subclass of injury
"A displacement of a part (especially a bone) from its normal position. [ NCI ]"

EFO:0009521 dislocation

- [x] disturbance of skin sensation
subclass of 'sensory system disease' and 'peripheral nervous system disease'
"Disruption of the normal functioning of the sensory nerves in the skin. [ NCI ]"

EFO:0009522 disturbance of skin sensation

- [ ] fall
NCIT has it under 'event'
"A sudden movement downward, usually resulting in injury. [ NCI ]"

- [x] fecal incontinence
subclass of 'intestinal disease'
"Involuntary passage of stool from the rectum. [ NCI ]"

EFO:0009523 fecal incontinence

- [x] female genital tract fistula
subclass of 'reproductive system disease'
"An abnormal communication between a female reproductive system organ and another organ or cavity. [ NCI ]"

EFO:0009524 female genital tract fistula

- [x] foreign body
subclass of 'test result' (NCIT has it under 'finding')
"Extraneous material within the body. [ NCI ]"

EFO:0009525 foreign body

- [x] foreign body in gastrointestinal tract
subclass of 'foreign body'
"Extraneous material located within the gastrointestinal tract. [ NCI ]"

EFO:0009526 foreign body in gastrointestinal tract

- [x] frostbite
subclass of injury
"An injury to the skin and/or its underlying tissues that results from exposure of the affected area to extreme cold. [ NCI ]"

EFO:0009527 frostbite
 
- [ ] high-risk pregnancy
subclass of 'complication'
"A fetal/maternal condition that is risky and portends complications for the mother and/or fetus, when compared to a normal pregnancy. [ NCI ]"

- [ ] intoxication (but first check if 'poisoning' could do)

- [ ] mosquito-borne hemorragic fever (with synonym '...haemorragic...')

- [ ] multiple gestation

- [ ] orthopedic nursing

- [ ] placental retention

- [ ] postpartum hemorrhage 
subclass of 'complication'
"Hemorrhage defined as a blood loss in excess of 500 mL after vaginal delivery or more than 1000 mL after a cesarean delivery. [ NCI ]"

- [ ] prophylactic surgery

- [ ] rehabilitation

- [ ] sprain
subclass of injury
"A stretching or tearing of a ligament. [ NCI ]"

**Comment by zoependlington** [comment]
Foreign body could be added under "role", but "test result" is okay for now - may need to revisit this.
