### ISSUE TITLE
Develop pattern and guidelines to model assays, measurements and outcomes

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#342]
This is a general issue: we need a pattern and guidelines for how to model an assay, what the assay was measuring and what the outcomes are/can be. Discussion stemmed from the example in https://github.com/EBISPOT/efo/issues/325#issuecomment-447872479, but was mentioned previously too. I'll copy the thread here for easy reference:

Problem:
Import NCIT:C127841 'Abnormal PAP smear' (with synonym 'abnormal smear (cervix)' and similar), but how should we classify it? In NCIT, it's a descendant of 'laboratory test result'.

Solutions:

@zoependlington : "HP tends to add terms like this under a phenotype eg. abnormal cardiac test is under abnormality of the cardiovascular system: https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0500015, so we could have it under abnormality of the female internal genitalia (HP_0000008)? Although I don't know if this is ideal..."

@simonjupp : "I’d be more inclined to represent this as a type of assay/measurement. We could have PAP smear and abnormal PAP smear as a child, maybe?
although abnormal in that context refers to the assay and not the result, which isn’t quire right either
which makes me inclined to model PAP smear as an assay and “abnormal PAP smear finding” as some kind of information entity
put this in the bucket of things that are tricky and inconsistently represented in EFO
this is why we need a pattern and guidelines for how to model the assay, what the assay was measuring and what the outcomes are/can be."

**Comment by zoependlington** [comment]
@paolaroncaglia Yes!
