### ISSUE TITLE
Development OLS for EFO v3 not responding

### ISSUE THREAD

**Issue by stevenwgen** [EBISPOT/efo#346]
The URL http://35.241.144.112/ontologies/efo for a development version of the EMBL-EBI Ontology Lookup Service containing EFO3, linked from the EFO v3 website https://github.com/EBISPOT/efo/tree/efo3 is not loading.

**Comment by paolaroncaglia** [comment]
@stevenwgen Thanks for reporting this. I believe that @simonjupp was planning to move the development version elsewhere, but I'm not sure if that's happened already.

@simonjupp are there any updates, please? Thanks.

**Comment by paolaroncaglia** [comment]
@stevenwgen 
FYI, EFO version 3 is now in OLS, see https://www.ebi.ac.uk/ols/ontologies/efo.
Please feel free to contact us again if you have any questions.
Thanks.

**Comment by paolaroncaglia** [comment]
This is resolved, but I'll assign to @simonjupp and myself for recording purposes.

**Comment by simonjupp** [comment]
Yep, this is now live so I'll close the issue
