### ISSUE TITLE
Add object property 'has modifier' in EFO 2?

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#356]
Currently, the object property 'has modifier' is in EFO 3, but not in EFO 2.
Do we need to add it in EFO 2 as well?
Use case example:
HP:0012532 'chronic pain' may be added has_modifier 'chronic'. 'chronic' is in EFO as HP:0011010.

**Comment by zoependlington** [comment]
Added in [this](https://github.com/EBISPOT/efo/commit/c7ee090f5068b4fb869c76666b28b7e52c51b4b5) commit.
