### ISSUE TITLE
RNA-seq of total RNA

### ISSUE THREAD

**Issue by peterwharrison** [EBISPOT/efo#358]
For new term requests, please provide the following information:

## Preferred term label

RNA-seq of total RNA

## Textual definition

An assay in which sequencing technology (e.g. Solexa/454) is used to generate RNA sequence, from the total cellular and organelle RNA molecules isolated from a specimen, to analyse these and/or to quantitate transcript abundance.

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0002770

## Attribution

https://orcid.org/0000-0002-4007-2899

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW** RNA-seq of total RNA
     - Child of 'transcription profiling by high throughput sequencing'
     - **Definition:** An assay in which sequencing technology (e.g. Solexa/454) is used to generate RNA sequence, from the total cellular and organelle RNA molecules isolated from a specimen, to analyse these and/or to quantitate transcript abundance.
     - **Definition citation:** https://orcid.org/0000-0002-4007-2899

**Comment by zoependlington** [comment]
The new term ID is: EFO_0009653
