### ISSUE TITLE
Re-classification of disease: "juvenile idiopathic arthritis"

### ISSUE THREAD

**Issue by Bionett** [EBISPOT/efo#362]
Currently, EFO groups the "juvenile idiopathic arthritis" set of conditions under the term "chronic childhood arthritis" (EFO:0002609). Its child terms and sub-structure do not represent the current consensus on this disease classification. Instead, the MONDO term "juvenile idiopathic arthritis" MONDO:0011429 and its child structure  better represent the current classification of the "juvenile idiopathic arthritis" set of conditions. Therefore, it would be good to replace the EFO:0002609 node and its child terms with the MONDO:0011429 and its underlying structure.

**Comment by paolaroncaglia** [comment]
@Bionett
Thanks for bringing this to our attention. I agree, this should be fixed.
Idiopathic refers to unknown cause, while chronic refers to persistency (so they’re not mutually exclusive, but have different meanings). The definition of EFO ‘chronic childhood arthritis’ starts with “Juvenile idiopathic arthritis (JIA), also known as juvenile rheumatoid arthritis (JRA), is the most common form of arthritis in children and adolescents.” and further says that the condition can be transient and self-limited or chronic, so the term should not be limited to chronic in its label. 
I suggest to:

- [ ] Rename EFO:0002609 ‘chronic childhood arthritis’ as ‘juvenile idiopathic arthritis’
- [ ] Add ‘chronic childhood arthritis’ as an alternative term (though strictly speaking it should be a narrow synonym)
- [ ] Add definition_citation MONDO:0011429 ‘juvenile idiopathic arthritis’
- [ ] Examine and, if necessary, fix placement of ‘pauciarticular juvenile rheumatoid arthritis’ (and improve its definition), ‘systemic juvenile idiopathic arthritis’ and ‘polyarticular juvenile idiopathic arthritis, rheumatoid factor negative’ (other children of EFO:0002609 would be in line with MONDO once we align EFO:0002609 with MONDO:0011429).

**Comment by paolaroncaglia** [comment]
Also,
- [ ] EFO ‘chronic childhood arthritis’ (will be renamed as ‘juvenile idiopathic arthritis’) can't be classified as an autoimmune disease by its definition, therefore it should be a class of 'arthritis' and not 'rheumatoid arthritis' (same as in MONDO).

**Comment by Bionett** [comment]
That is wright. Although some cases of Juvenile Idiopathic Arthritis mirror
autoimmunity, others mirror auto inflammatory diseases. However, all
conditions grouped as Juvenile Idiopathic Arthritis manifest arthritis as a
hallmark symptom.


Em seg, 18 de fev de 2019 às 10:12, paolaroncaglia <notifications@github.com>
escreveu:

**Comment by paolaroncaglia** [comment]
@Bionett thanks. I'm a bit confused though because the current definition of the EFO term says 
"Juvenile idiopathic arthritis (JIA), also known as juvenile rheumatoid arthritis (JRA), is the most common form of arthritis in children and adolescents. ... JIA is an **autoimmune**, non-infective, inflammatory joint disease... It differs significantly from arthritis commonly seen in adults (osteoarthritis, **rheumatoid arthritis**)..."
So shall I place it under 'arthritis' (instead of 'rheumatoid arthritis') as agreed above, but also as a subclass of 'autoimmune disease'? Thanks!

**Comment by paolaroncaglia** [comment]
Note for self re. EFO:0003114 pauciarticular juvenile rheumatoid arthritis:
- [ ] Remove the xref to DOID:6755 (that must have been a mistake, it corresponds to 'amyloid tumor'; I can't find any DOID term for 675 or 'pauciarticular juvenile rheumatoid arthritis', even among obsoletes);
- [ ] Remove synonyms pointing to amyloid tumor;
- [ ] Remove bioportal provenance;
- [ ] Improved definition to... (TBC)

**Comment by paolaroncaglia** [comment]
Note for self re. EFO:1001999 systemic juvenile idiopathic arthritis:
- [ ] Add definition_citation MONDO:0019434 systemic-onset juvenile idiopathic arthritis
- [ ] Add to MONDO mapping files

**Comment by paolaroncaglia** [comment]
@Bionett may I also consult you please about the most correct placement of EFO:1002020 'polyarticular juvenile idiopathic arthritis, rheumatoid factor negative'? EFO has it under 'systemic juvenile idiopathic arthritis', but the EFO definition of 'polyarticular juvenile idiopathic arthritis, rheumatoid factor negative' makes no reference to the systemic term and/or severity of non-articular symptoms. The corresponding MONDO term (MONDO:0018456 polyarticular juvenile idiopathic arthritis) has no definition, and is placed directly under 'juvenile idiopathic arthritis'. Thanks.

**Comment by Bionett** [comment]
@paolaroncaglia 
1. "shall I place it under 'arthritis' (instead of 'rheumatoid arthritis') as agreed above, but also as a subclass of 'autoimmune disease'?" I think so.
2. "pauciarticular juvenile rheumatoid arthritis" was the former name of "Oligoarticular Juvenile Idiopathic Arthritis" 
3. EFO:1001999 to MONDO:0019434. I agree.
4. EFO:1002020 polyarticular juvenile idiopathic arthritis, rheumatoid factor negative' is equivalent to MONDO:0019432 'rheumatoid factor-negative juvenile idiopathic arthritis' which is a child term of MONDO:0018456 'polyarticular juvenile idiopathic arthritis'.

**Comment by paolaroncaglia** [comment]
@Bionett Thanks!

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Classify EFO ‘chronic childhood arthritis’ (will be renamed as ‘juvenile idiopathic arthritis’) as a subclass of 'arthritis' (and not 'rheumatoid arthritis') AND as a subclass of 'autoimmune disease'

**Comment by Bionett** [comment]
@paolaroncaglia thanks for addressing the suggestion. If I understood correctly, the EFO:0002609 term will now be called ‘juvenile idiopathic arthritis’ and will have three child terms: 'oligoarticular juvenile idiopathic arthritis', 'polyarticular juvenile idiopathic arthritis, rheumatoid factor negative' and 'systemic juvenile idiopathic arthritis'. If so, I would also recommend:
- Include two new 'oligoarticular juvenile idiopathic arthritis' child terms: 'persistent oligoarticular juvenile idiopathic arthritis' and 'extended oligoarticular juvenile idiopathic arthritis'. Criteria and definitions based on the International League of Associations for Rheumatology (ILAR) classification recommended for 'juvenile idiopathic arthritis' PMID: 14760812.
- Include the generic term for polyarticular juvenile idiopathic arthritis as MONDO_0018456 (as a child term of 'juvenile idiopathic arthritis' and the parent term of 'polyarticular juvenile idiopathic arthritis, rheumatoid factor negative'). Once it is added, include the term 'polyarticular juvenile idiopathic arthritis, rheumatoid factor positive' as a child of the generic 'polyarticular juvenile idiopathic arthritis'.
- Include the term 'enthesitis-related juvenile idiopathic arthritis' MONDO_0019437 as a child of 'juvenile idiopathic arthritis' PMID: 14760812.
- Include the term 'psoriasis-related juvenile idiopathic arthritis' MONDO_0019436 as a child of 'juvenile idiopathic arthritis' PMID: 14760812.
- Include the term 'unspecified juvenile idiopathic arthritis' MONDO_0019607 as a child of 'juvenile idiopathic arthritis' PMID: 14760812.

**Comment by paolaroncaglia** [comment]
@Bionett thanks for your additional suggestions and references, very helpful. Over the next couple of weeks I will make all of the edits required, in time for the next EFO release (mid-March). I will keep you posted when this ticket is completed.

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] Add to MONDO mapping files as necessary.

**Comment by paolaroncaglia** [comment]
@Bionett 
I’ve now done all requested changes to the 'juvenile idiopathic arthritis' branch, except for the ones below where I’d need your help please. 
With regard to your request
“Include two new 'oligoarticular juvenile idiopathic arthritis' child terms: 'persistent oligoarticular juvenile idiopathic arthritis' and 'extended oligoarticular juvenile idiopathic arthritis'. Criteria and definitions based on the International League of Associations for Rheumatology (ILAR) classification recommended for 'juvenile idiopathic arthritis' PMID: 14760812.”
I don’t have access to the full text of PMID:14760812, could you please copy the definitions here?
Thanks,
Paola

**Comment by Bionett** [comment]
@paolaroncaglia 
As in PMID: 14760812,
"Oligoarthritis:
Definition: Arthritis affecting one to 4 joints during the first 6 months of disease. Two subcategories are recognized:
1. **Persistent** oligoarthritis: Affecting not more than 4 joints throughout the disease course
2. **Extended** oligoarthritis: Affecting a total of more than 4 joints after the first 6 months of disease

Exclusions:
a. Psoriasis or a history of psoriasis in the patient of first-degree relative.
b. Arthritis in an HLA-B27 positive male beginning after the 6th birthday.
c. Ankylosing spondylitis, enthesitis related arthritis, sacroiliitis with inflammatory bowel disease, Reiter's syndrome, or acute anterior uveitis, or history of one of these disorders in a first-degree relative.
d. The presence of IgM rheumatoid factor on at least 2 occasions at least 3 months apart.
e. The presence of systemic JIA in the patient."

**Comment by paolaroncaglia** [comment]
@Bionett 
Thanks!
Based on the definition of 'persistent oligoarthritis' ("Affecting not more than 4 joints throughout the disease course"), should that be a parent to 'oligoarticular juvenile idiopathic arthritis' ("A category of juvenile idiopathic arthritis defined by the presence of arthritis affecting between one and four separate joints during the first six months of disease.")? Or should 'persistent oligoarthritis' be a synonym of 'oligoarticular juvenile idiopathic arthritis'?
And should 'extended oligoarthritis' ("Affecting a total of more than 4 joints after the first 6 months of disease") be a child of 'polyarticular juvenile idiopathic arthritis', or a synonym thereof?
Thanks again.

**Comment by Bionett** [comment]
@paolaroncaglia 
Thanks for considering the suggestions.
'persistent oligoarticular juvenile idiopathic arthritis' (_def: oligoarticular juvenile idiopathic arthritis affecting not more than 4 joints throughout the disease course_) and 'extended oligoarticular juvenile idiopathic arthritis' (_def: oligoarticular juvenile idiopathic arthritis affecting a total of more than 4 joints after the first 6 months of disease_) should be child terms of 'oligoarticular juvenile idiopathic arthritis' based on the criteria and definitions of the International League of Associations for Rheumatology (ILAR) classification recommended for 'juvenile idiopathic arthritis' PMID: 14760812.

Summarizing:

'juvenile idiopathic arthritis'
 |
 ⤷ 'oligoarticular juvenile idiopathic arthritis'
 | `  ` `  ` ⤷ 'persistent oligoarticular juvenile idiopathic arthritis'
 | `  ` `  ` ⤷ 'extended oligoarticular juvenile idiopathic arthritis'
 |
 ⤷ 'polyarticular juvenile idiopathic arthritis'
 | `  ` `  ` ⤷ 'polyarticular juvenile idiopathic arthritis, rheumatoid factor positive'
 |  `  ` `  ` ⤷ 'polyarticular juvenile idiopathic arthritis, rheumatoid factor negative'
 |
  ⤷ 'enthesitis-related juvenile idiopathic arthritis'
 |
  ⤷ 'psoriasis-related juvenile idiopathic arthritis'
 |
  ⤷ 'unspecified juvenile idiopathic arthritis'

**Comment by paolaroncaglia** [comment]
@Bionett 
Thanks, I'll add those last two terms in time for Monday's EFO release.

**Comment by paolaroncaglia** [comment]
@Bionett 
Last 2 terms added are 
EFO:0009745 persistent oligoarticular juvenile idiopathic arthritis
EFO:0009746 extended oligoarticular juvenile idiopathic arthritis
All changes will be visible after the EFO release on Monday March 18th.
Thanks.
