### ISSUE TITLE
New EFO terms for 'reference sample' and 'abnormal sample'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#365]
As per email exchange with @mbaudis, we will add new terms to EFO under the parent term “material sample” (OBI:0000747). This parent term is a subclass of ‘specimen’, and is defined as “A material which is collected with the intention of being representative of a greater whole (i.e. a sample).”

We suggest to add new EFO terms as following:

- [ ] "reference sample": Which will encompass the idea of germline reference sample / germline/inherited/baseline.

- [ ] "abnormal sample": Which will encompass the idea of neoplastic/tumor/altered sample or abnormal tissue/sample. It would have the axiom has_quality PATO “abnormal”.

As we have specific anatomical meaning to “tissue” in EFO, keeping these terms broader and referencing “sample” rather than “tissue” would be preferred. 

- [ ] We could then add specific children to these new terms as needed, e.g. “neoplastic sample” as a child of “abnormal sample”. The “reference sample” term could be added synonyms of “non-neoplastic sample”, "native sample" (in keeping with CL) etc. We could add details of usage in the new terms’ definitions. Some initial suggestions from Michael for definitions are:
"|-* (material derived from) cells or tissue representing a physiologically or phenotypically normal state"
|- * (material derived from) cells or tissue representing a physiologically or phenotypically abnormal state"
    - * (material derived from) cells or tissue with a neoplastic phenotype
    - * (material derived from) cells or tissue with an inflammatory phenotype"
and

"Maybe expand the abnormal definition:
* (material derived from) cells or tissue representing an observed or suspected physiological, genomical or phenotypical abnormal state"
... same for "neoplastic" etc."

**Comment by zoependlington** [comment]
- [ ] **EFO:NEW1** reference sample
     - Subclass of material sample (OBI_0000747)
     - **Definition:** A material sample derived from cells or tissue representing a physiologically or phenotypically normal state.
     - **Synonyms:** germline reference sample||inherited reference sample||baseline reference sample||non-neoplastic sample||native sample
     - **X-refs:** CL:0000003

- [ ] **EFO:NEW2** abnormal sample
     - Subclass of material sample (OBI_0000747)
     - has_quality some abnormal
     - **Definition:** A material sample derived from cells or tissue representing an observed or suspected physiological, genomical or phenotypical abnormal state
     - **Synonyms:** altered sample||abnormal tissue sample

- Could also add synonyms of "neoplastic sample" and "tumor sample" to "abnormal sample" or add child term to "abnormal sample" for these as "neoplastic sample". @mbaudis, which would you prefer? Also please advise if the above is adequate or if there are any edits/extras you would like to add. Thanks!

**Comment by mbaudis** [comment]
@zoependlington @paolaroncaglia I'm +1 in general, and specifically for the "neoplastic" as a subclass as outlined by Zoë.
Maybe additionally making it clearer that this does not replace a histological or anatomical quality? While "neoplastic" seems desirable, any further specification (benign, malignant, grade ...; anatomical attribution...) should not become part of this subtree. Decision & wording up to you.

**Comment by paolaroncaglia** [comment]
@mbaudis @zoependlington 
Thanks Michael. Zoe, I suggest adding an editor note to ‘neoplastic sample’: “Note that this term is not meant to replace a histological or anatomical quality. While the neoplastic specification was desirable in the context of one particular use case, any further specification of children of ‘reference sample’ or ‘abnormal sample’ (e.g. benign, malignant, grade, anatomical attribution) should not become part of this subtree.”

**Comment by zoependlington** [comment]
@mbaudis, thank you for your quick response! We will get these terms into EFO prior to our release on Monday.

@paolaroncaglia I agree here.

Updated the above plan to be:

- [ ] **EFO:NEW1** reference sample
     - Subclass of material sample (OBI_0000747)
     - **Definition:** A material sample derived from cells or tissue representing a physiologically or phenotypically normal state.
     - **Synonyms:** germline reference sample||inherited reference sample||baseline reference sample||non-neoplastic sample||native sample
     - **X-refs:** CL:0000003

- [ ] **EFO:NEW2** abnormal sample
     - Subclass of material sample (OBI_0000747)
     - has_quality some abnormal
     - **Definition:** A material sample derived from cells or tissue representing an observed or suspected physiologically, genomically or phenotypically abnormal state
     - **Synonyms:** altered sample||abnormal tissue sample

- [ ] **EFO:NEW3** neoplastic sample
     - Subclass of abnormal sample (EFO:NEW2)
     - **Definition:** A material sample derived from neoplastic cells or tissue.
     - **Synonyms:** tumor sample
     - **Editor note:** Note that this term is not meant to replace a histological or anatomical quality. While the neoplastic specification was desirable in the context of one particular use case, any further specification of children of ‘reference sample’ or ‘abnormal sample’ (e.g. benign, malignant, grade, anatomical attribution) should not become part of this subtree.

**Comment by zoependlington** [comment]
@mbaudis The new term IDs are:
EFO_0009656 || neoplastic sample 
EFO_0009655 || abnormal sample
EFO_0009654 || reference sample

These will be available after our February 2019 release (Monday 18th February).
