### ISSUE TITLE
Discuss changes to CAROTID ATHEROSCLEROTIC DIS

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#374]
These changes were requested by GWAS:
- CAROTID ATHEROSCLEROTIC DIS is a synonym of carotid artery disease, looks like it should be a child instead

- Looks like CAROTID ATHEROSCLEROTIC DIS should be synonym of carotid plaque

- Looks like CAROTID ATHEROSCLEROTIC DIS should also be child of atherosclerosis

**Comment by paolaroncaglia** [comment]
Hi @twhetzel ,

You asked for feedback on the following: 
“These changes were requested by GWAS:
CAROTID ATHEROSCLEROTIC DIS is a synonym of carotid artery disease, looks like it should be a child instead
Looks like CAROTID ATHEROSCLEROTIC DIS should also be child of atherosclerosis”

Correct. (Though it’s likely that most occurrences of ‘carotid artery disease’ in the literature refer to carotid atherosclerosis.) We should:

- [ ] Add a new term for ‘carotid atherosclerosis’
Subclass of ‘carotid artery disease’ and ‘atherosclerosis’
“A thickening and loss of elasticity of the walls of carotid arteries that occur with formation of atherosclerotic plaques.”
Synonym: carotid atherosclerotic disease
(Please add a definition citation of some sort)

- [ ] Remove from ‘carotid artery disease’ all atherosclerosis-like synonyms, and, if they are meaningful, add them to the new term above   

As for GWAS' question
“Looks like CAROTID ATHEROSCLEROTIC DIS should be synonym of carotid plaque”:
I can’t find any term in EFO labelled ‘carotid plaque’. There is ‘carotid plaque build’ but that’s a measurement term. If there were a ‘carotid plaque’ term, the correct relationship would be 
‘carotid atherosclerosis’ disease_has_feature ‘carotid plaque’
similarly to http://www.ebi.ac.uk/efo/EFO_0003914

Thanks!

**Comment by paolaroncaglia** [comment]
@twhetzel 
I'll remove the "help wanted" label - hopefully I've addressed your query :-)

**Comment by twhetzel** [comment]
@paolaroncaglia where did you find the definition above for "carotid atherosclerosis"?

**Comment by paolaroncaglia** [comment]
@twhetzel I based my suggested definition of ‘carotid atherosclerosis’ on its parent terms, that's why I didn't add a specific xref ;-) I'm confident that it will be a valid definition, but it would be nice to find a paper that supports it (as there are no matches in OLS). Thanks.

**Comment by zoependlington** [comment]
@twhetzel @paolaroncaglia Could base definition off: https://www.bmj.com/content/346/bmj.f1485

**Comment by paolaroncaglia** [comment]
@twhetzel @zoependlington Yes that looks good. That'd be PMID_definition_citation PMID:23507536. Thanks!
