### ISSUE TITLE
Fix definition of EFO:1001317 'Epiphyses, Slipped'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#375]
The definition of EFO:1001317 'Epiphyses, Slipped' currently reads:

"ne of the most common adolescent hip disorders and represents a unique type of instability of the proximal femoral growth plate. Four separate clinical groups are seen:"

Look up its definition citations and fix/complete the definition accordingly.

**Comment by zoependlington** [comment]
Change def to: "One of the most common adolescent hip disorders and represents a unique type of instability of the proximal femoral growth plate. Four separate clinical groups are seen: Pre-slip (wide epiphyseal line without slippage), acute form (10-15% - slippage occurs suddenly, normally spontaneous), acute-on-chronic (slippage occurs acutely where there is already existing chronic slip) and chronic (85% - steadily progressive slippage, the most common form)."
