### ISSUE TITLE
Fix EFO CL:0000446 'parathyroid'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#376]
In EFO, the term 'parathyroid' is a subclass of 'gland', but is imported from CL and defined (mostly) as a cell type. In CL itself, CL:0000446 is currently labeled as 'chief cell of parathyroid gland'. I'd suggest to rename and rehouse CL:0000446 as a cell-type term (also check its definition citations), and import the relevant UBERON term to represent the gland. The EFO CL term may then be made part_of the EFO UBERON term.

**Comment by paolaroncaglia** [comment]
I started to look at the definition citations of EFO CL:0000446 'parathyroid':

- [ ] The BTO definition citation BTO:0000997 points to parathyroid gland

- [ ] EHDAA (Human developmental anatomy, abstract version) is now deprecated, so delete the xrefs EHDAA:3870 and EHDAA:3864

To be continued.

**Comment by paolaroncaglia** [comment]
Note that currently EFO CL:0000446 'parathyroid' is used in axioms as if it were the anatomy term (e.g. 'parathyroid gland carcinoma' has disease location 'parathyroid'). This occurs for 5 disease terms at the moment. So the best strategy would be to import UBERON:0001132 'parathyroid gland' and replace EFO CL:0000446 'parathyroid' with it. The 'true' CL term for 'chief cell of parathyroid gland' doesn't seem to be necessary in EFO at the moment, but to avoid any potential trouble due to its removal, we could update its placement, label etc. and make it part_of the UBERON term.

**Comment by paolaroncaglia** [comment]
@S2Ola 
Asking because I know you've been working on UBERON import and terms lately. Would you be able to tell me please if UBERON:0001132 'parathyroid gland' is among the terms that you plan to import in EFO as part of https://github.com/EBISPOT/efo/issues/167? If not I'm happy to import it myself, just making sure we don't duplicate efforts. Thanks.

**Comment by zoependlington** [comment]
@paolaroncaglia I do believe it has been imported into EFO 3 through Ola's pipeline.

**Comment by S2Ola** [comment]
@paolaroncaglia I can confirm that UBERON:0001132 'parathyroid gland'  has been imported into EFO3 via my pipeline. 
Thanks

**Comment by paolaroncaglia** [comment]
Thanks @zoependlington and @S2Ola.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Check "Class usage" tab in Protege for EFO CL:0000446 'parathyroid' and confirm that it is only ever used (erroneously) in axioms where it's meant as an anatomy term instead
- [ ] Check that EFO CL:0000446 'parathyroid' is not required in collaborators' pipelines
- [ ] Import UBERON:0001132 'parathyroid gland' in EFO2 if needed (it's already in EFO3)
- [ ] Replace CL:0000446 'parathyroid' with UBERON:0001132 'parathyroid gland' in all axioms where that's necessary
- [ ] Obsolete CL:0000446 'parathyroid', with a replaced_by annotation.
