### ISSUE TITLE
Add species Herbaspirillum seropedicae SmR1 for Annotare submitter

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#38]
Annotare submitter would like the following species added.

Herbaspirillum seropedicae SmR1
Taxonomy ID: 757424

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=757424

For now he will pick another species and we'll change the species during processing but it would be good if the species was in the list for his next submission.

**Comment by simonjupp** [comment]
- [ ] add this under EFO organism

**Comment by paolaroncaglia** [comment]
- [ ] Import NCBITaxon:757424 Herbaspirillum seropedicae SmR1
Subclass of ‘Bacteria’
Synonyms: Herbaspirillum seropedicae str. SmR1, Herbaspirillum seropedicae strain SmR1

Should I use the Webulous template “Import plant term” as it includes Taxon?

**Comment by paolaroncaglia** [comment]
Note for self: if it's just 1 term that needs importing (or any number below 3 really), the advice is to do it manually.

**Comment by zoependlington** [comment]
Species term now imported into EFO!
