### ISSUE TITLE
Re-organize disease term for "chronic central serous retinopathy"

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#380]
The GWAS curators have requested that the term "central serous retinopathy" be added as a child of "retinopathy" with the definition "Central serous retinopathy, also known as central serous chorioretinopathy, is an eye disease that causes visual impairment, usually in one eye. When the disorder is active it is characterized by leakage of fluid under the retina that has a propensity to accumulate under the central macula. This results in blurred or distorted vision (metamorphopsia). Patients with the chronic form have prolonged presence of fluid with progressive loss of vision and reduced quality of life. "

Related to adding the term above, the existing EFO term "chronic central serous retinopathy", EFO:0009363 should be added as a child of the new term above and the definition should be changed to "The chronic form of central serous retinopathy.  Patients with the chronic form have prolonged presence of fluid with progressive loss of vision and reduced quality of life. ". to only refer to the chronic form.

@paolaroncaglia @zoependlington are there any issues with making this change?

Per 
https://www.rnib.org.uk/eye-health/eye-conditions/central-serous-retinopathy

Most cases of CSR resolve in under 12 months, cases >12 mo (termed 
chronic) are very rare.

**Comment by paolaroncaglia** [comment]
@twhetzel at a quick glance I think there are no issues with making the changes you suggest.
I might add a couple of ideas though. One is to take away the last sentence from the definition of the non-chronic form, as there will be a chronic-specific child. Another is to cross-reference the non-chronic form to MONDO:0018616 'central serous chorioretinopathy' (and add to the two MONDO mapping files when you build EFO 3). Lastly, please add 'central serous chorioretinopathy' as a synonym of the non-chronic form. Thanks! :-)

**Comment by paolaroncaglia** [comment]
@twhetzel I'll remove the "help wanted" label from here as well, thanks.
