### ISSUE TITLE
Review EFO:1000782 altitude sickness

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#383]
Stemming from a GWAS user query.
EFO:1000782 altitude sickness is currently a child of 'cardiovascular disease'. It is "caused by acute exposure to low partial pressure of oxygen at high altitude" and "It presents as a collection of nonspecific symptoms", therefore the current parentage may be not fully correct. Note that hypoxia is a phenotype term in EFO, so we can't link it to that (other than by disease_has_feature). The matching term in MONDO (MONDO:0006625 altitude sickness) has the same parentage, but that's probably because it derives from EFO itself. Review and consider if perhaps EFO:0005803 hematologic disease may be a better parent (on the ground that the problem originates due to low oxygen in the blood). If the placement of the EFO term is indeed revised, notify MONDO too.

**Comment by zoependlington** [comment]
@paolaroncaglia Had a chat with David and Ola about this term. Hematologic disease isn't a 100% fit with the description as right now hematologic disease is defined as disorders of the blood and blood forming tissues (also needs to be linked to our term for blood e.g. has_disease_location some blood or part_of some blood!), but is a much better fit than cardiovascular disease. We definitely need to add disease_has_feature some hypoxia to altitude sickness and possibly add to the definition to reflect the hypoxia link along with the reclassification? Does this sound good?

**Comment by paolaroncaglia** [comment]
@zoependlington thanks. Here are a few more comments:

- [ ] The matching term for ‘hematologic disease’ in MONDO (‘hematological system disease’) has disease location ‘hematopoietic system’ (so that’s the disease location axiom we should add, I think). ‘Blood’ is part_of ‘hematopoietic system’, so if we wanted to be really precise we should create a child of ‘hematologic disease’ to represent blood disorders only, but I suspect that wouldn’t be advisable because some disorders would affect not just blood itself. (MONDO doesn’t make the distinction.) 

- [ ] At any rate: I checked several sources and they all cite generic lack of oxygen in the body causing hypoxia as the cause of altitude sickness; generic as opposed to lack of oxygen specifically in the blood causing hypoxemia. Then, to play it safe, I guess we could only place ‘altitude sickness’ directly under ‘disease’ (instead of ‘cardiovascular disease’)

- [ ] To reflect the link to hypoxia, in addition to adding the disease_has_feature axiom, we could edit the definition to read: 
“A pathological effect of high altitude on humans, occurring when exposure to low partial pressure of oxygen, typically at high altitudes, causes hypoxia (a decrease in the amount of oxygen in the body). It commonly occurs above 2,400 metres (8,000 feet). It presents as a collection of nonspecific symptoms, resembling a case of "flu, carbon monoxide poisoning, or a hangover". It is hard to determine who will be affected by altitude sickness, as there are no specific factors that correlate with a susceptibility to altitude sickness. However, most people can ascend to 2,400 metres (8,000 ft) without difficulty.”

Thanks.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Perhaps run this by MONDO as they got the term from EFO; see if they agree or have alternative suggestion for the placement.

**Comment by zoependlington** [comment]
@paolaroncaglia 

I agree with adding hematopoietic system as the disease location. I don't believe we need a specific blood disorder parent (our hematologic disease has a synonym of blood disorder), so this should be sufficient.

This was the hesitation I had regarding classifying as a hematologic disease, but after talking to David we concluded it was better to be placed under hematologic disease than general disease as long as we refer to hypoxia and edit the definition. So these changes to the definition are great.

Thanks!

**Comment by zoependlington** [comment]
@cmungall @nicolevasilevsky Do you have any objection to these changes or alternatives for reclassifying altitude sickness? Thanks.

**Comment by nicolevasilevsky** [comment]
reclassifying altitude sickness as a child of disease makes sense to me, and I like the suggested text def.

**Comment by paolaroncaglia** [comment]
To confirm, for 'altitude sickness' in the end @zoependlington and I opted for the broad parent 'disease' rather than the more specific 'hematologic disease' because of its multi-systemic nature (see https://www.ncbi.nlm.nih.gov/pubmed/8570999, https://www.liebertpub.com/doi/pdf/10.1089/1527029041352126 and https://en.wikipedia.org/wiki/Altitude_sickness#Primary_symptoms).
