### ISSUE TITLE
Revise labels and synonyms of breast neoplasm terms

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#385]
@zoependlington received an email from Adam on 6/3/2019:

"Looking at EFO3 3.3.1, I can see that there is the "breast carcinoma"
term EFO_0000305, and a "breast cancer" term MONDO_0007254, and
"breast neoplasm" EFO_0003869. That's going to a bit confusing to our
users, but I can accept that it is technically the correct medical
classification.

However, EFO_0000305 ("breast carcinoma") has synonyms including
"Breast Neoplasm" and "Breast Cancer" - which are the labels of the
other terms.

It would be ideal if we could have labels / synonyms that do not
overlap, if such a thing is possible? Or at least overlap less?
Otherwise it is going to be quite confusing for our search results,
and for data mapping e.g. with Zooma/OLS."

While we do this for breast-related neoplasm entries, we should also check that the placement of the terms is correct.

**Comment by zoependlington** [comment]
- [ ] Breast carcinoma is the only problematic one here
     - should be equivalent to carcinoma and has_disease_location some (breast or (part_of some breast))
     - has many definitions that are duplicates of each other, these need to be double checked and the correct ones kept.
     - remove all synonyms and definitions related to "cancer". Should be a child of breast cancer, which it is in EFO3 (only exists in EFO3).
     - remove all synonyms and definitions related to "neoplasm".

**Comment by paolaroncaglia** [comment]
@afaulconbridge (and @zoependlington FYI) 
I have now edited 'breast carcinoma' so that it doesn't include any synonym or other links to cancer, tumor or neoplasm, to avoid confusion. (I did not add 'breast cancer' to EFO 2 because it is already in EFO 3, and that will be the only EFO release from next month onward, but let me know if you'd need that added now.) If you spot any other troublesome cases please let us know. Thanks!
