### ISSUE TITLE
GM25256 cell line NTR

### ISSUE THREAD

**Issue by jahilton** [EBISPOT/efo#386]
On behalf of the ENCODE project, I am requesting an EFO term for the GM25256 cell line as specified in this spreadsheet: https://docs.google.com/spreadsheets/d/1v2Y9L2qfT4PFYTaD0o4YfErwONobUasRyOwLvVRVZDM/edit?usp=sharing

Thank you,
Jason

**Comment by zoependlington** [comment]
Hi Jason,
The URI for this new term is EFO_0009747.
It will be available in EFO after our release on Monday (18th March).
Thanks!
