### ISSUE TITLE
Investigate results of ROBOT report

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#387]
The results using the default queries from ROBOT were:

Violations: 55746
-----------------
ERROR:      7762
WARN:       45371
INFO:       2613

In summary, the errors are for duplicate definitions, multiple equivalent classes, missing labels, misused obsolete label, missing ontology description, duplicate labels, multiple definitions, missing ontology license, missing ontology title and multiple labels.

See report here: https://docs.google.com/spreadsheets/d/1BPZSpa1cc3NC2mT274G7qJ8IrLyfIEzL-JcznLg8zj8/edit?usp=sharing

**Comment by zoependlington** [comment]
Added the second tab for results of report after the duplicate MONDO terms are removed in #261 (which still needs make errors to be solved).

Summary of this report:

Violations: 37081
-----------------
ERROR:      3339
WARN:       31351
INFO:       2391

**Comment by paolaroncaglia** [comment]
Notes from the last EFO planning meeting:
- [ ] Write a brief plan of how to address each error, e.g. how to remove a duplicate label
- [ ] Implement the duplicate labels script to the make file

**Comment by paolaroncaglia** [comment]
- [ ] I'll address the errors here: https://docs.google.com/spreadsheets/d/1h5dG17VSJMA3iBtebySUKN3Yk8PFfP2BT8lIvxbdL5Y/edit#gid=0
(I made a new spreadsheet because the one with the full ROBOT report takes forever to load and edit.)

**Comment by paolaroncaglia** [comment]
@daniwelter kindly helped with some errors from the previous comment.
@zoependlington: at this stage, EFO is locked for release and I know you're looking into some errors, so I'll unassign myself from this ticket, and we can come back to it if/as you instruct (presumably after the release if errors still persist). Thanks!

**Comment by paolaroncaglia** [comment]
Moving to "Done" in favor of https://github.com/EBISPOT/efo/issues/420

**Comment by paolaroncaglia** [comment]
This is done, but I'm assigning it to @zoependlington , @daniwelter and myself to record/document work done. Thanks.
