### ISSUE TITLE
missing subsumption in embryonal neoplasia for orphanet terms

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#39]
most common embryonal neoplasms asserted. challenge is whether these are truly derived from embryonal tissues or merely resembl them. both defs are in the NCIt. Orphanet tumours need to be addressed. amppimg to NCit terms would be optimal.

**Comment by simonjupp** [comment]
- [ ] needs a review and cross checked against MONDO

**Comment by paolaroncaglia** [comment]
Here are my thoughts:

Classification under EFO:0005784 ‘embryonal neoplasm’ is richer (more abundant as well as more complex) in EFO 3 than EFO 2 (compare http://35.241.144.112/ontologies/efo/terms?short_form=EFO_0005784 to https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0005784); 

All terms under EFO:0005784 ‘embryonal neoplasm’ in EFO 3 have NCIt mappings, except for the following terms: http://purl.obolibrary.org/obo/MONDO_0016708 (but its two children have NCIt mappings), http://www.orpha.net/ORDO/Orphanet_2151, http://www.ebi.ac.uk/efo/EFO_0006391, http://purl.obolibrary.org/obo/MONDO_0000551; 

We could probably consider this ticket addressed in EFO 3. We might come back to individual terms if specific issues are raised. I’ll leave this ticket open so others may comment if they disagree, else I’ll move it to ‘Done’ in a couple of weeks.

@simonjupp 
@zoependlington

**Comment by paolaroncaglia** [comment]
This is now available in EFO 3.
