### ISSUE TITLE
Ribo-Seq EFO_0008891

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#395]
The term "Ribo-Seq" is currently wrongly classified as "DNA assay" EFO_0001456.
It should be a child of "RNA assay" EFO_0001457 and "assay by sequencer" EFO_0003740.
The latter is needed to correctly classify the experiment type as sequencing (vs. array) in ArrayExpress.
As we want to include this term in ArrayExpress, I would like to request to change the spelling from capital "Seq" to lower case "seq" to match with the other ArrayExpress experiment types. 
Thank you. Let me know if you have any questions.

**Comment by paolaroncaglia** [comment]
Note for self: edit EFO:0008891 Ribo-Seq to:
- [ ] Change parentage from subclass of 'DNA assay' to subclass of 'RNA assay'and 'assay by sequencer'
- [ ] Edit label from Ribo-Seq to Ribo-seq
- [ ] Expand definition from "Ribosome profiling (Ribo-Seq)" to "Ribosome profiling (also named ribosome footprinting) that uses specialized messenger RNA (mRNA) sequencing to determine which mRNAs are being actively translated. It produces a “global snapshot” of all the ribosomes active in a cell at a particular moment, known as a translatome."
- [ ] Add Wikipedia:Ribosome_profiling
- [ ] Add synonyms: Ribo-Seq, ribosome profiling, ribosome footprinting

**Comment by paolaroncaglia** [comment]
@anjaf EFO:0008891 Ribo-Seq has been edited as requested. Changes will be visible in the mid-April release. Thanks!
