### ISSUE TITLE
New EFO terms for Open Targets

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#398]
Integration of safety risk data in the platform requires adverse effects/targets to be added to EFO. Eirini has created a spreadsheet of mappings which can be accessed here: https://docs.google.com/spreadsheets/d/1boZarjRzDPy8w8b_9dxy1UK6r6H8u5zVMRP2iPbTqME/edit?usp=sharing

There are 89 HPO terms and 96 other terms that require importing/creation in EFO.

**Comment by paolaroncaglia** [comment]
Update for EFO editors: Zoe met Eirini on 26/3; Eirini will put everything into a Webulous template and find the parent terms, so we'll wait to hear from her. I've added an item to the agenda for our next EFO meeting to discuss if we want to import OAE terms into EFO since there are going to be a lot of adverse events terms coming into EFO.

**Comment by zoependlington** [comment]
Add the following to the MONDO terms txt file:

- [ ] MONDO_0016474  #  drug-induced lupus erythematosus
- [ ] MONDO_0019054  #  congenital limb malformation

**Comment by EPetsalaki** [comment]
@zoependlington, thank you for adding the MONDO term. On the second one, the Genetic congenital limb malformation would not be ok, because it would refer mostly to a genetic issue, rather than an adverse effect caused by a drug treatment.

**Comment by zoependlington** [comment]
@EPetsalaki Thanks for feedback! I'll do the following:
- [ ] Remove mapping of MONDO_0019054 "congenital limb malformation" to Orphanet_183536 "Genetic congenital limb malformation" in EFO.
- [ ] Add MONDO_0019054 "congenital limb malformation" to txt file to be imported as a separate entity.

**Comment by EPetsalaki** [comment]
Hi again, 

Thanks for the help with the MONDO terms! 

I've finished the mapping for terms that are in HPO which you can find [here ](https://drive.google.com/open?id=1yMFtoKVEhBvXjRZFTkNExmRocvrd8ZLF9iRdf3B4Y_4).

There are two sheets to this spreadsheet, please use whichever one is most convenient for you. They are the same terms more or less, with a difference in organisation:

1. The first only has EFO terms as parent terms, with notes on which intermediate terms I feel would be better to be included as well (as a branch).
2. In the second sheet I've included the parent terms to be included, colour coded according to their priority. So the first ones (red background) are the ones needed before moving forward with the second set (orange) and these are then needed for the third (yellow) set of parent terms. After these I have the requested terms at the last level (using as parent terms the terms that are colour coded).

Note that some parent terms were not in the dropdown list of available parent terms, even though they were in EFO. I've marked these with a comment in red.

Let me know if I've done something wrong. Thanks!!

**Comment by EPetsalaki** [comment]
Good morning, 

I've made some small changes to the HPO term request form, and I've also finished the term request for the GO terms. You can find the GO terms requested[here](https://drive.google.com/open?id=1WoTzgrXFaBv8ScOTMlGrd45X1-u3Kao6NY8Z0PGco2U). 

I know you didn't need the names of the terms but I included them next to the actual GO terms for my reference (so that I didn't request terms all over the place) and for your information when reviewing the requested terms. 

I'll now move on to the request forms from the other ontologies. I have one question on MP terms. You (@zoependlington) mentioned that I can use the HP template for these, but I'm having a hard time finding parent MP terms on EFO. Should I just request them as new terms like the other ontologies? It's only 8 terms.

**Comment by EPetsalaki** [comment]
EDIT: [Here ](https://drive.google.com/open?id=1yQ3d45f9snyfTLcK4x9K93oiR1IYN7Ou4v6VQVR4NvM) you can find the request form for the terms from ontologies NCIT, SYMP & NBO. 
Another question: Should I wait to hear from you about the OAE (Ontology of Adverse Events) terms, or should I include these in the above form?
That's it on my side for now, I'll wait to hear back from you on what to do with the MP and OAE terms, and whether there is any issues with the completed forms as they are are right now.

**Comment by zoependlington** [comment]
Thank you @EPetsalaki!
This all sounds great. I'll take a look at these spreadsheets ASAP and let you know if I have any questions. To answer some of your queries/comments:

The term not appearing in the drop-down is an issue with Google sheet validation - EFO has more terms than Google sheets allows, therefore not all of them are loaded into the validator. As long as they're in EFO (which you can confirm with OLS), then don't worry about that warning.

I can take a look at the 8 MP terms and see the level of work needed to import them regarding parents, please add them to the bottom of HPO template and fill in as much as possible (definition, x-refs, synonyms etc.) leaving the parent blank if you can not find a good suggestion.

For OAE, we have decided to consider the import on a case by case basis so you can leave those with us!

If I have any questions/there are any issues, I'll let you know! Thanks again!

**Comment by EPetsalaki** [comment]
Great, thank you for the feedback! I'll add the MP terms now so that this is done as well.

**Comment by zoependlington** [comment]
### HPO and GO

All terms have now been imported from HPO and GO. These will be available in our May release.

### New request Webulous

Terms have all been added and will be available in our May release, their IDs are:

EFO_0009833 | kidney injury
EFO_0009832 | cellular infiltration
EFO_0009843 | substance-induced sleep disorder
EFO_0009842 | respiratory depression
EFO_0009841 | irregular respiration
EFO_0009840 | tachypnea
EFO_0009839 | bradypnea
EFO_0009838 | alteration in respiration
EFO_0009837 | Bronchodilation
EFO_0009836 | bronchoconstriction
EFO_0009835 | increased respiratory secretion
EFO_0009834 | respiratory process
EFO_0009853 | convulsion
EFO_0009852 | exhaustion
EFO_0009851 | muscle atrophy
EFO_0009850 | masculinization of female, CTCAE
EFO_0009849 | sexual arousal
EFO_0009848 | antiemetic effect
EFO_0009847 | dizziness
EFO_0009846 | muscle cramp
EFO_0009845 | catalepsy
EFO_0009844 | nightmare

### To do:

OAE term review and MP term review.

**Comment by EPetsalaki** [comment]
Great, thank you very much!

**Comment by zoependlington** [comment]
@EPetsalaki 
I have done a quick review of the terms in the OAE mappings sheet. A lot of the "source terms" could be mapped to terms existing in EFO (green) or importable ontologies like HP (yellow). Those that are red require further looking into, but we may be able to create new terms for these. If you have any objection to the mappings [here](https://docs.google.com/spreadsheets/d/12YJTx-V9lEx7c-IfMmzCiKc_c99f6hWUgwMBC4JXOHs/edit?usp=sharing), please let me know! If there are no objections, I'll review the red terms again and import the yellow terms into EFO. You can then update your mapping file with these mappings.

**Comment by EPetsalaki** [comment]
Hi @zoependlington, thank you for these! Looking at them, only two feel a bit off: hyperthermia -> fever and neurotoxicity -> toxic encephalopathy. Both are too narrow, if there is a general term upstream that would probably be better! Other than these two, the rest seem fine to me, and I can update my mapping.

**Comment by zoependlington** [comment]
Hi @EPetsalaki, thanks for your prompt response! Both fever and toxic encephalopathy have the synonyms of the terms requested (i.e. hyperthermia is a synonym of fever and neurotoxicity is a synonym for toxic encephalopathy).

Alternatively, hyperthermia could be mapped to 'abnormality of temperature regulation' (HP:0001945), which is currently in EFO?

I feel that any more general term for neurotoxicity may be too broad as toxic encephalopathy is a direct child of nervous system disease. I'll research neurotoxicity and toxic encephalopathy more to see if they are equivalent or if we need a new term created.

**Comment by EPetsalaki** [comment]
Hi @zoependlington, thank you for looking into these. 

Since fever is a synonym of hypothermia in EFO and it's not really that far off, I can use that term. My only issue with encephalopathy was that it is brain-centric (according to the greek word it is derived from and a double-check on wikipedia), so it wouldn't include for example neurological issues with fingers. However, the term as it is defined in EFO doesn't exclude these, so I'll use that one as well. 

Thanks for your help!

**Comment by zoependlington** [comment]
**To import:**
- [ ] Bradycardia | HP_0001662
- [ ] Immunodeficiency | HP_0002721
- [ ] Abnormal stool composition | HP_0031685
- [ ] Abnormality of the uterus | HP_0000130

**New terms:**
- [ ] **EFO:NEW1** pulmonary vascular congestion
     - Subclass of abnormal lung morphology (HP_0002088) and abnormality of the vasculature (HP_0002597)
     - Definition: Obstruction of the normal flux of blood within the blood vessel network of the lung resulting in engorgement of pulmonary vessels; frequently precedes pulmonary edema.
     - Synonyms: congested lung vasculature||lung vascular congestion||pulmonary congestion||PVC
     - X-ref: MP:0010018
- [ ] **EFO:NEW2** dysphoria
     - Subclass of mental or behavioural disorder
     - Definition: Dysphoria is a profound state of unease or dissatisfaction. In a psychiatric context, dysphoria may accompany depression, anxiety, or agitation. Common reactions to dysphoria include emotional distress or indifference.
     - X-ref: OAE:0001946||Wikipedia:Dysphoria
- [ ] **EFO:NEW3** sedation
     - Subclass of medical procedure
     - Definition: The process of allaying nervous excitement or the state of being calmed.
     - X-ref: NCIT:C21097||UMLS_CUI:C0344106
- [ ] **EFO:NEW4** xerostomia
     - Subclass of abnormality of the mouth
     - Definition: Dryness of the mouth resulting from reduced salivary secretion.
     - Synonyms: dry mouth
     - X-ref: MP:0000624
- [ ] **EFO:NEW4** bone metastasis
     - Subclass of metastasis
     - Definition: Transfer of a neoplasm from its primary site to bones.
     - Synonyms: metastasis to bone
     - X-ref: OAE:0001175

**Other:**
- [ ] **NEEDS DISCUSSION** drug-drug interaction potential
- [ ] **NEEDS DISCUSSION** drug-drug interaction
- [ ] Look over MP terms

**Comment by zoependlington** [comment]
@EPetsalaki I've updated the OAE remapping spreadsheet (https://docs.google.com/spreadsheets/d/12YJTx-V9lEx7c-IfMmzCiKc_c99f6hWUgwMBC4JXOHs/edit?usp=sharing) with all mappings. Those in green are in EFO, yellow are in the above comment's import list, orange are terms to create.

**Comment by zoependlington** [comment]
Here are all of the new terms for OAE and MP terms:
EFO_0009880 | teratogenicity
EFO_0009879 | gastric hemorrhage
EFO_0009878 | drug interaction
EFO_0009877 | decreased bone mass
EFO_0009876 | abnormal lipolysis
EFO_0009875 | thymus atrophy
EFO_0009874 | decreased anxiety-related response
EFO_0009873 | decreased cardiac output
EFO_0009872 | increased cardiac output
EFO_0009871 | increased heart weight
EFO_0009870 | bone metastasis 
EFO_0009869 | xerostomia
EFO_0009868 | sedation
EFO_0009867 | dysphoria
EFO_0009866 | pulmonary vascular congestion

**Comment by EPetsalaki** [comment]
Thank you very much @zoependlington for your help! I'll let you know if I see something that needs changing, but everything looks great for now!

**Comment by EPetsalaki** [comment]
No worries about the NBO cross-reference, it's my fault!
HP:00254228 is fine for bronchospasm, I must have missed that one :). I'll also add the other two terms to my list and then wait for a green light from you on the mapped terms before moving forward with these.
Thank you very much for your help!

**Comment by EPetsalaki** [comment]
No worries for the NBO term, it's my fault!
The bronchospasm term is fine, I must have missed that one :). I'll also add the other two terms to my list and wait for the ok from you before moving forward with these. 
Thank you very much for your help!

**Comment by EPetsalaki** [comment]
Hi, I seem to have trouble replying! I've posted the same thing a few times :). The jist of it is that I'll include these 3 terms to my file and wait for the ok from you. And of course, many thanks!

**Comment by zoependlington** [comment]
Hi @EPetsalaki,

I'll remove the x-ref to NBO in EFO:0009832 - apologies for not catching that one!

As far as bronchospasm goes, we have a HP term in EFO, 'bronchospasm' (HP:0025428), which should be okay for you to use. Please let me know if it isn't!

The URI for vascular smooth muscle hypertrophy is: http://www.ebi.ac.uk/efo/EFO_0009829. I missed it from the above list, apologies again! This will be available with the next release alongside the second MONDO term (MONDO_0019054).

I'll also double check your mapping file to make sure nothing is missing from EFO. Thanks for your reply! :)

**Comment by zoependlington** [comment]
@EPetsalaki 

All terms in your spreadsheet of mappings are now double checked and definitely in EFO and will be available in the next release (15th May).

**Comment by EPetsalaki** [comment]
Great! Thank you for double checking @zoependlington :)
