### ISSUE TITLE
Revise classification of EFO:1001986 'connective tissue disease'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#399]
In EFO, 'connective tissue disease' is a child of 'skeletal system disease'.
But in UBERON, 'skeletal tissue' is a child of 'connective tissue' (where UBERON 'skeletal tissue' is part_of 'skeletal element' which is part_of 'skeletal system').

**Comment by zoependlington** [comment]
MONDO classifies connective tissue disease directly under disease (see here: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003900) so I propose mirroring this in EFO.

**Comment by zoependlington** [comment]
Obsoleted CL_0000388 and imported UBERON_0002384.
