### ISSUE TITLE
Add term for "disease remission"

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#403]
The GWAS Curators have requested the term "disease remission" for PMID: 29786918. OGMS has the term "remission" as a child of "disease stage" childOf "process". Suggest to add both of the OGMS terms will be added to EFO.

**Comment by twhetzel** [comment]
Chatted with @zoependlington about other options such as childOf "biological process" or childOf "diease course". This will be discussed at the EFO meeting.

**Comment by daniwelter** [comment]
After some discussion, EFO editors have agreed to put the term under 'disease staging' for now, but have identified this category as one that needs a wider review.

Term should be a new EFO term, with xref to the existing term.

**Comment by zoependlington** [comment]
- [ ] EFO:NEW remission
     - Child of disease staging (EFO_0000410)
     - **Definition:** A disease stage which is characterized by the lack of a manifestation of a disease.
     - **X-refs:** OGMS:0000106||NCIT:C18246||UMLS_CUI:C0544452
     - **Synonyms:** disease remission

**Comment by zoependlington** [comment]
@twhetzel 

New ID is:
http://www.ebi.ac.uk/efo/EFO_0009785 | remission
