### ISSUE TITLE
Adding human patient quality

### ISSUE THREAD

**Issue by arturolp** [EBISPOT/efo#407]
Could you help add a new term

## Preferred term label

patient derived primary cultured human fibroblast cell

## Synonyms

patient fibroblast

## Textual definition

Fibroblast cells taken from a patient usually from a biopsy.

## Suggested parent term

The parent should be:
CLO:0037301 primary cultured fibroblast cell

## Attribution

Stanford ClinGen Informatics Core

**Comment by zoependlington** [comment]
Hello @arturolp,

We believe that this term would be more suited to being a part of the Cell Line Ontology (CLO); http://www.clo-ontology.org/. Their GitHub issue tracker can be found here: https://github.com/CLO-ontology/CLO/issues. We are able to import CLO terms into EFO if you also require this term to be in EFO, once CLO has minted the new term.

However, the development status of CLO is currently unknown to us. Therefore, if you require this term to be created quickly (our next release will be 15th May, which will be when new terms become available) or receive no response from the CLO team, we will then be happy to create an EFO term for this request.

I will move this issue to the Done queue, which will then be closed in our next scrum. Please feel free to re-open or comment on this ticket if you require us to take action.

Thanks!
