### ISSUE TITLE
Duplicate term in EFO

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#411]
- interleukin 1 beta measurement (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008166)

vs. 

- interleukin-1 beta measurement (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0004812)

For EFO plans, are these types of duplicates planned for review?

**Comment by paolaroncaglia** [comment]
@twhetzel 
Thanks for spotting this. I believe that so far we checked for the presence of duplicates with exact same label or where the only difference in label was capitalization. I'd expect we could implement checks for nearly-exact labels too. We can bring this up at the next scrum.

**Comment by daniwelter** [comment]
I have obsoleted the newer of the two terms, http://www.ebi.ac.uk/efo/EFO_0008166, in favour of the older term, http://www.ebi.ac.uk/efo/EFO_0004812. All axiomatisations have been preserved in the remaining term.
