### ISSUE TITLE
Review axiomatisation of 'autoimmune disease'

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#42]
many common disease loci have an autoimmune disease annotation.
Create an axiom e.g.

'autoimmune disease' subClassOf realized_in some ('disease course' and 'has part' some ('immune system process’ and 'bearer of' some abnormal))

and
has_disease_location some immune system or part_of

example ORDO classes to include - Immunodeficiency syndrome with autoimmunity

**Comment by simonjupp** [comment]
decided to close until we have definitive way to reference the autoimmune system
