### ISSUE TITLE
Write a blog post for Open Targets about changes in EFO 3

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#429]
@zoependlington and @paolaroncaglia have reviewed and commented on a draft provided by Adam and Denise.
Blog might be published around end of May (rough estimate from Denise).
Will wait for further instructions from them.

**Comment by zoependlington** [comment]
- [ ] Decide on hero image
- [ ] Decide on images between the text

**Comment by paolaroncaglia** [comment]
Also,
- [ ] mention changes in annotation properties (e.g. possibility to discriminate between exact and non-exact synonyms in EFO3)

**Comment by paolaroncaglia** [comment]
Dani suggests an image of relevant disease ontology area in OLS overlayed with EFO logo

**Comment by paolaroncaglia** [comment]
OT haven't switched to EFO3 yet, so maybe this task can be delayed in favor of other tickets? @zoependlington

**Comment by deniseOme** [comment]
@paolaroncaglia @zoependlington, do delay this task in favour of other tickets on your end. 

EFO3 will not be released in our upcoming Open Targets Platform release, which is due at the end of June (release 19.06).

We are looking into the August release 19.08, although there is a possibility this will be pushed to September.

**Comment by deniseOme** [comment]
@paolaroncaglia @zoependlington, it's confirmed that the new release of the Open Targets Platform due at the end of November will contain EFO3.

Could we resume working on the EFO3 blog post? https://docs.google.com/document/d/1nO40wG95BcDLXZLuuyt9-uGg8uWCKYrMVYrxoJGsGpU/edit#

I think we could actually release this before the Nov release blog post, as a heads-up for what is to come.
Would aiming at publishing this blog by mid Nov work for you both?

Happy to meet face to face when/if needed.

@d0choa

**Comment by paolaroncaglia** [comment]
@deniseOme @d0choa
Thanks for following up. Sure, publishing the blog by mid Nov would work for us. I moved this ticket so it's now in our "In progress" queue (as we already have a draft for the doc). @zoependlington kindly offered to work on it around mid-next week. 
I'll leave the ticket assigned to both of us as a reminder for me (Zoe, you'll let me know if/when you'd like me to review/comment/contribute).

**Comment by paolaroncaglia** [comment]
An update that the current draft is now https://docs.google.com/document/d/1OwumeV_GPoFUCBu6BS9dgeMJ0m6TWmFVlEWdz2ZnppQ/edit.

**Comment by deniseOme** [comment]
Sorry for the confusion @paolaroncaglia @zoependlington. Upon discussion yesterday with @d0choa we have decided to move away from a Q&A format. The publishing date has also been pushed back to 1 week after the release 19.11 of the Open Targets Platform. We expect the latter to be released in the last week of Nov. So expecting the EFO3 blog to be published by the 7th Dec, the latest (first week of Dec).

**Comment by paolaroncaglia** [comment]
@deniseOme 
@d0choa
Thanks for clarifying. @zoependlington and I will then give priority to other tasks. Zoe may still be able to review the draft around mid-next week, so @d0choa you may want to wait until after that to check on the progress. Thanks!

**Comment by paolaroncaglia** [comment]
Update on the blog post for Open Targets: this is now in Open Targets' hands. But I'll keep this ticket in the "In progress" queue so it stays in our radar.

**Comment by paolaroncaglia** [comment]
Update on the blog post for Open Targets: Sandra, Denise and David sent us their draft today and we're working on it.

**Comment by zoependlington** [comment]
Blog post has been reviewed by us and will be published on the Open Targets blog soon. Moving to done as there is no AI for us outstanding.

**Comment by dhimmel** [comment]
## Published location

**EFO3: A community-driven ontology to advance clinical discoveries**
Open Targets Blog (2019-12-19) <https://blog.opentargets.org/2019/12/19/efo3-a-community-driven-ontology-to-advance-clinical-discoveries/>

## Question about image

Is the cover image a screenshot of a publicly available URL?

> ![](https://blog.opentargets.org/content/images/2019/12/Screen-Shot-2019-12-13-at-11.54.36-5.png)

I'm interested in seeing the subgraphs for other diseases than Crohn's.

**Comment by hammer** [comment]
@dhimmel see https://alpha.targetvalidation.org/disease/EFO_0000384
