### ISSUE TITLE
Multiple rdfs:labels for some UBERON import terms

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#434]
Some of the UBERON terms in the EFO3 build have 2 rdfs:labels (e.g. UBERON:0000004 has 2 rdfs:labels of 'nose' and 'olfactory apparatus') which is causing issues with the OBO file. Should only have the label from UBERON.

**Comment by S2Ola** [comment]
This has been fix through the pipeline by removing all UBERON annotations in EFO, and re-importing the annotations in UBERON for all the UBERON terms in EFO , this link to ticket [#436 ](https://github.com/ebispot/efo/issues/436)
