### ISSUE TITLE
Wrongly formatted X-refs

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#436]
These are IDs that are formatted incorrectly and require fixing. Most exist in EFO2, so require editing from the edit file but some exist only in EFO3 and need further investigation.

**Class          Xref**
<http://www.ebi.ac.uk/efo/EFO_0009290>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009291>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009285>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009287>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009286>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009288>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009283>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009289>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009284>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0005128>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009282>	"29403010"
<http://www.ebi.ac.uk/efo/EFO_0009750>	"Dissociation_(psychology)"
<http://www.ebi.ac.uk/efo/EFO_1000640>	"D020144"
<http://www.ebi.ac.uk/efo/EFO_0009706>	"Latent_autoimmune_diabetes_in_adults"
<http://www.ebi.ac.uk/efo/EFO_0008466>	"29212897"
<http://www.ebi.ac.uk/efo/EFO_1000643>	"D013036"
<http://www.ebi.ac.uk/efo/EFO_0009389>	"27863252"
<http://www.ebi.ac.uk/efo/EFO_0009390>	"27863252"
<http://www.ebi.ac.uk/efo/EFO_0009388>	"27863252"
<http://www.ebi.ac.uk/efo/EFO_1000282>	"C98291"
<http://www.ebi.ac.uk/efo/EFO_0008470>	"29212900"
<http://www.orpha.net/ORDO/Orphanet_140944>	"ICD10CQ87.3"
<http://purl.obolibrary.org/obo/CHEBI_76084>	"(2R)-3-hydroxy-2-[(9Z,12Z)-octadeca-9,12-dienoyloxy]propyl 2-(trimethylazaniumyl)ethyl phosphate"
<http://purl.obolibrary.org/obo/UBERON_0001572>	"MFMO_0000064"
<http://www.ebi.ac.uk/efo/EFO_0008388>	"28922980"
<http://www.ebi.ac.uk/efo/EFO_0008468>	"29237677"
<http://www.ebi.ac.uk/efo/EFO_0008469>	"29237677"
<http://www.ebi.ac.uk/efo/EFO_0008452>	"29158487"
<http://www.ebi.ac.uk/efo/EFO_0008451>	"29158487"
<http://www.ebi.ac.uk/efo/EFO_0008453>	"29158487"
<http://www.ebi.ac.uk/efo/EFO_0008454>	"29158487"
<http://www.ebi.ac.uk/efo/EFO_1000015>	"C1112553"
<http://www.orpha.net/ORDO/Orphanet_107>	"Orphanet107"
<http://www.ebi.ac.uk/efo/EFO_1000784>	"Orphanet727"
<http://www.ebi.ac.uk/efo/EFO_0008449>	"29093028"
<http://www.ebi.ac.uk/efo/EFO_0008450>	"29093028"
<http://purl.obolibrary.org/obo/UBERON_0003830>	"thoracic segment muscle"
<http://www.ebi.ac.uk/efo/EFO_0005741>	"IDO_0000436"
<http://www.ebi.ac.uk/efo/EFO_1000642>	"D006432"
<http://purl.obolibrary.org/obo/UBERON_0010890>	"pelvic complex muscle"
<http://purl.obolibrary.org/obo/UBERON_0010891>	"pectoral complex muscle"
<http://www.ebi.ac.uk/efo/EFO_1000650>	"DOID_0060078"
<http://www.ebi.ac.uk/efo/EFO_0008467>	"29251981"
<http://purl.obolibrary.org/obo/UBERON_0008196>	"muscle of pectoral girdle"

**Comment by zoependlington** [comment]
All have been rectified apart from the following that are in EFO3 only:
http://purl.obolibrary.org/obo/UBERON_0001572	"MFMO_0000064"
http://www.orpha.net/ORDO/Orphanet_107	"Orphanet107"
http://purl.obolibrary.org/obo/UBERON_0003830	"thoracic segment muscle"
http://purl.obolibrary.org/obo/UBERON_0010890	"pelvic complex muscle"
http://purl.obolibrary.org/obo/UBERON_0010891	"pectoral complex muscle"
http://purl.obolibrary.org/obo/UBERON_0008196	"muscle of pectoral girdle"

**Comment by zoependlington** [comment]
@S2Ola Can you investigate where the UBERON x-refs in the comment above have come from? X-refs should be PREFIX:IDNUMBER not PREFIX_IDNUMBER or any other variant, e.g. MFMO_0000064 should be MFMO:0000064. If they're from UBERON and the UBERON import itself, then we'll need to create a ticket on their tracker. If it's something else, then we'll need to fix it. Thanks.

**Comment by S2Ola** [comment]
Awaits updated release from UBERON as the Obsoleted terms in UBERON remains in the hierarchy in OLS

**Comment by S2Ola** [comment]
The x-refs have been fixed in the new uberon import pipeline.
