### ISSUE TITLE
EFO 'animal component' vs UBERON 'anatomical structure'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#439]
For https://github.com/EBISPOT/efo/issues/372, and following up on discussion with MONDO editors to try and align on axioms used for diseases, I'll need to add an axiom to 'inflammatory disease' in EFO to mirror the one in MONDO, which is
MONDO:0021166 'inflammatory disease' 
equivalent to 
disease or disorder and (disease has inflammation site some anatomical structure)
where 'anatomical structure' is UBERON:0000061.
EFO does not have UBERON:0000061 'anatomical structure', but rather EFO:0000787 'animal component', which is parent to all anatomy terms in EFO, but is not used in axioms. 
I'm happy to add the axiom I need in EFO as 
'inflammatory disease' equivalentTo: disease and (has_inflammation_site some ('animal component' or (part_of some 'animal component')))
but just wanted to double-check with other EFO editors in case we'd want to replace EFO:0000787 'animal component' with the UBERON term. (Asking because there may have been some high-level-term discussion/decision in the past on how to represent anatomy parts in EFO that I'm unaware of.) Note that the UBERON term seems by all means to refer to animals and exclude plants and fungi (http://purl.obolibrary.org/obo/UBERON_0000061). 
Going forward with EFO3, wouldn't import/update/alignment processes benefit from that replacement?

**Comment by zoependlington** [comment]
In favour of switching with the UBERON term, but should inform users of this in the next release notes/by email. 

I'll double check that this is not being used by Annotare or Open Targets.

**Comment by paolaroncaglia** [comment]
In summary:
- [ ] @zoependlington to check if EFO:0000787 'animal component' is used by Annotare or Open Targets;
- [ ] @paolaroncaglia to import UBERON:0000061 'anatomical structure' and switch from EFO:0000787 'animal component' to 'UBERON:0000061 'anatomical structure';
- [ ] @zoependlington to inform users of the switch in release notes and release email. Thanks!

**Comment by paolaroncaglia** [comment]
All done. The next EFO release (June 17th) will be done by @daniwelter , so I'll hand her the last action item above please, i.e.
- [ ] inform users, in release notes and release email, that we switched from using EFO:0000787 'animal component' to using UBERON:0000061 'anatomical structure'. 
I'll assign this ticket to @daniwelter for that. Thanks Dani!
