### ISSUE TITLE
Add Disease terms "major coronary event" and  "ankle injury" submitted through Webulous

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#44]
Review the terms "major coronary event" and  "ankle injury" submitted here [1] and add to EFO and make available the term and URI in GWAS Curation app.

[1] https://docs.google.com/spreadsheets/d/1Fab4PKP8OVmq2fRUaooD89xODfSmQQ5yoNC7tXImwek/edit#gid=113400521

**Comment by twhetzel** [comment]
The requested term "major coronary event" should not be added to EFO and alternative terms that represent the trait in PMID:28753643 should be suggested to the curators.

**Comment by siiraa** [comment]
Discussed that major coronary event should not be a new term, use cardiovascular disease instead. 
Ankle injury is a new term under injury.

**Comment by twhetzel** [comment]
Ankle injury added and new files pushed.
