### ISSUE TITLE
Fresh import of GO?

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#444]
Stemming from https://github.com/ebispot/efo/issues/228#issuecomment-492569799 where 35 GO terms lacking definition in EFO were identified. I understand that GO terms may not be a priority for EFO, but in GO they've all had definitions for as long as I can remember :-) Moreover, GO terms in EFO might be stale under other aspects too, e.g. among the 35 lacking definition I spotted one that was merged 3 years ago, so the ID in EFO is now secondary in GO in favour of another term (EFO GO:0016023). 
@simonjupp should we consider doing a fresh import of GO terms in EFO?

**Comment by paolaroncaglia** [comment]
@zoependlington could you please link this ticket to the Epic https://github.com/EBISPOT/efo/issues/623? I seem to have lost permission. Thank you.

**Comment by paolaroncaglia** [comment]
(Or if it's no longer desired, please feel free to close)

**Comment by zoependlington** [comment]
@paolaroncaglia It already seems to be linked... Is your Zenhub up to date? I'll look into why permissions may seem to be lost.
