### ISSUE TITLE
EFO:0000789 'plant component' and EFO PO:0025131 'plant anatomical entity'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#455]
While working on 'animal component' (#439), I noticed the following.
'anatomy basic component' has subclasses for animals, fungi and plants. For plants there are two terms that are equivalent:

EFO:0000789 'plant component' 
and 
EFO PO:0025131 'plant anatomical entity'

EFO:0000789 'plant component' has a MAT dbxref and nothing else.
EFO PO:0025131 'plant anatomical entity' has this comment: "Definition editor's comment: This is a retrofitting realignment of structure to compromise the pre-PO MAT classification to reflect a now (2016) more OBO-complied organism part classification by making equivalent of EFO:'plant component' and now-imported PO:'plant anatomical entity'. MAT (the Minimal Anatomy Terminology) is now deprecated in OBO."

Both terms have subclasses (a mix of mostly PO terms and a few EFO ones).
Should we obsolete EFO:0000789 'plant component' and replace it with EFO PO:0025131 'plant anatomical entity'?
Tagging @simonjupp and @zoependlington to confirm as this is a high-level term.

If we do,
- [x] Follow obsolete/merge procedure with replacement
- [x] Check if unwanted term is used by GWAS, Annotare or Open Targets (it doesn't have any gwas_trait annotation and I can't find EFO_0000789 in the GWAS Catalog; it isn't in the list of terms needed by Annotare or among OT therapeutic areas)
- [x] Look up unwanted term in Ontobee, is it used in other ontologies?
- [x] Inform users of the switch in release notes and release email.

(Zoe agrees; I'll ask Simon when he's back.)

**Comment by simonjupp** [comment]
+1  to obsolete the EFO term.

**Comment by paolaroncaglia** [comment]
Assigning to @daniwelter so she can inform our users, in the release notes and release email, that we switched from EFO:0000789 'plant component' to PO:0025131 'plant anatomical entity'. Thanks.
