### ISSUE TITLE
Term replaced by links broken due to typos

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#457]
Found by @matentzn 

Typos in term replaced by in the following terms:
http://www.ebi.ac.uk/efo/EFO_0002556
http://www.ebi.ac.uk/efo/EFO_0001290
http://www.ebi.ac.uk/efo/EFO_0004218

**Comment by daniwelter** [comment]
Fixed the first two (in EFO2). Can't reproduce the 3rd one - will review after I've built EFO3.

**Comment by daniwelter** [comment]
Final term now also fixed - this was the result of a double obsolence issue in the EFO3-MONDO import.
