### ISSUE TITLE
Problem with "connective tissue disease" vs "musculoskeletal system disease" 

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#462]
At the moment terms such as `bone disease` are under both terms defining separate paths to disease.

Should perhaps "connective tissue disease" be under "muskuloskeletal system disease"?

**Comment by d0choa** [comment]
The MedDRA ontology contains at the moment a combined term named [Musculoskeletal and connective tissue disorders](https://bioportal.bioontology.org/ontologies/MEDDRA/?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMEDDRA%2F10028395)

**Comment by paolaroncaglia** [comment]
Closing as duplicate of #495
