### ISSUE TITLE
New terms proposed for GWAS curation of PMID:31015401

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#469]
From the GWAS Curators:
Wu et al look at medication use in UK Biobank.  The authors group current medication usage (according to the ATAC system) into 23 traits.  'Drug use measurement' is an appropriate parent term, but I need some input on how best to represent the groupings in EFO for maximal re-usability.

We could make new EFO terms for each reflecting the trait, e.g. 'antithrombotic agent use measurement' as children of 'drug use measurement'

And/or we could use the ATC classifications, e.g. 'ATC Code A alimentary tract and metabolism drug use measurement', if we think that would be useful.

The 23 traits examined are:

ATC code	REPORTED_TRAIT
A02B	Medication use (drugs for peptic ulcer and gastro-oesophageal reflux disease)
A10	Medication use (drugs for diabetes)
B01A	Medication use (antithrombotic agents)
C01D	Medication use (vasodilators used in cardiac diseases)
C02	Medication use (antihypertensives)
C03	Medication use (diuretics)
C07	Medication use (beta blocking agents)
C08	Medication use (calcium channel blockers)
C09	Medication use (agents acting on the renin-angiotensin system)
C10AA	Medication use (HMG CoA reductase inhibitors)
H03A	Medication use (thyroid preparations)
L04	Medication use (immunosuppressants)
M01A	Medication use (anti-inflammatory and antirheumatic products, non-steroids)
M05B	Medication use (drugs affecting bone structure and mineralization)
N02A	Medication use (opioids)
N02BA	Medication use (salicylic acid and derivatives)
N02BE	Medication use (anilides)
N02C	Medication use (antimigraine preparations)
N06A	Medication use (antidepressants)
R03A	Medication use (adrenergics, inhalants)
R03BA	Medication use (glucocorticoids)
R06A	Medication use (antihistamines for systemic use)
S01E	Medication use (antiglaucoma preparations and miotics)

Since this is related to UKBB data and measurement, are there existing plans to expand the ATC section of EFO? Are there any objections to adding these proposed ATC terms?

**Comment by paolaroncaglia** [comment]
@twhetzel 
A few quick comments from me. (As I mentioned, I can't answer about plans to expand the ATC codes node in EFO.) The codes above are "(reported) traits" by their own naming and as described by you. Are the authors looking to _measure_ how much drug a patient uses? Or do they simply need to capture that a patient takes a drug? That is, do you need measurement terms or trait terms? To me, the ATC codes above, as such, could be used for traits, but if you need measurement terms, I'd use the ATC codes as cross-references. Curious to hear what others think. Thanks!

**Comment by daniwelter** [comment]
@twhetzel Could you please post a link to the paper so I can review the methodology? I have some thoughts on how to address this but I'd like more context first.

**Comment by twhetzel** [comment]
This was for PMID: 31015401. This was changed to a more general request for the measurement term "antithrombotic agent use measurement" and was added to EFO.
