### ISSUE TITLE
import FBBI terms for CORBEL

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#47]
(https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1433)

Hi,

To follow up on this, you'll find in attachment a list of terms we'd like to use as part of EFO. Some terms are in FBBI but not all as far as I could tell. I am happy to help in getting them into the ontology, just let me know what you'd like me to do.
Do you have a timeline for when the FBBI would be included into EFO ?
Also, EFO has a biological process term. Does it come from GO ? If so can more/all of GO be included ? At the moment, we're using GO separately in our system because the terms we need are not in EFO.

Thanks

Cheers

J-K

https://www.ebi.ac.uk/panda/jira/secure/attachment/22893/microscopy_method_terms.txt

**Comment by siiraa** [comment]
@simonjupp Do you have a full contact of J-K? I have no idea where he is.

**Comment by siiraa** [comment]
https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1432 - Eleanor Williams

Import Fbbi Imaging Method branch into EFO:
The Image Data Resource uses FBbi terms to describe imaging experiments but it is likely that we will need to add terms.  It would be good to import FBbi imaging method branch ( http://purl.obolibrary.org/obo/FBbi_00000222)  into EFO and then add missing terms as needed.

**Comment by eleanorwilliams** [comment]
I think the current plan is to have a call with the EDAM/Nubias group to see if it would be feasible to include FBBI as a subset of EDAM-BIOIMAGING under the branch Topic > Imaging.  @simonjupp and @joshmoore are the main contacts.  Simon has J-K's contact email (not sure if I should put it here).

**Comment by simonjupp** [comment]
Not heard from these people for a while. I think they are using EDAM for this now. Will close the ticket and reopen if this comes up again.
