### ISSUE TITLE
Import terms to EFO - FGPTO-1008

### ISSUE THREAD

**Issue by lauhuema** [EBISPOT/efo#48]
FGPTO-1008 for importing new terms

**Comment by lauhuema** [comment]
This is the list of terms to be imported: https://docs.google.com/spreadsheets/d/1q4El_SOa2ZvL5GYkDFUxrtXJJ5Bg88TifT95qDsPz9g/edit#gid=0

**Comment by siiraa** [comment]
@lauhuema is it possible to have the webulous sheet for this request please?

**Comment by simonjupp** [comment]
contacted Laura for update

**Comment by paolaroncaglia** [comment]
@simonjupp 
Did you hear back from @lauhuema about this ticket, please? Thanks.

**Comment by paolaroncaglia** [comment]
@simonjupp @zoependlington I believe this ticket might be closed as out-of-date? I can't access Laura's spreadsheet, so can't check if her requested imports are in EFO already. Thanks.

**Comment by zoependlington** [comment]
@paolaroncaglia I believe Laura has left EBI now, it may be worth finding out who her replacement is to see if they know anything about this ticket?

**Comment by paolaroncaglia** [comment]
@simonjupp Laura from AE/GXA opened this issue and linked a list of terms to be imported, but she's left the EBI now and we can't access her spreadsheet. Would you know who her replacement is please so we can ask, or shall we close this ticket as out-of-date? Thanks.

**Comment by daniwelter** [comment]
Anja, Nancy and Silvie at AE/GXA have all taken over some parts of Laura's work - she doesn't have a direct replacement

**Comment by paolaroncaglia** [comment]
Thanks @daniwelter !

**Comment by paolaroncaglia** [comment]
@zoependlington and I are moving this ticket to "Done" as we can't access the submitted spreadsheet, and there have been two attempts to follow up on our part without success. The submitter is no longer at EBI. We're confident that if her team still need those terms, they will let us know.
