### ISSUE TITLE
Review placement of EFO MONDO:0021154 'dermis disease'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#483]
Need to double-check, but I think that EFO MONDO:0021154 'dermis disease' should be a child of 'skin disease', since dermis is part of skin...
David O. suggests to look at subcutaneous tissue disease too.

**Comment by d0choa** [comment]
We’ll include more details on this issue later today

**Comment by paolaroncaglia** [comment]
Closing as duplicate of #491
