### ISSUE TITLE
Open Targets therapeutic area: Infections and Infestations

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#488]
Proposed TA name:     Infections and Infestations
Current EFO TA name: Infectious Disease
Priority for OT: Intermediate
Justification: As per definition, an infestation from e.g. ticks, mites, parasites is not the same as an infection (although may lead to one). Therefore infestations should not be sitting under infections, but alongside it.

Infestation = parasitic attack or subsistence on the skin and/or its appendages, as by insects, mites, or ticks; sometimes used to denote parasitic invasion of the organs and tissues, as by helminths. https://medical-dictionary.thefreedictionary.com/infestation
infection = invasion and multiplication of microorganisms in body tissues, as in an infectious disease. https://medical-dictionary.thefreedictionary.com/infection

Currently in EFO - Parasitic infection is sitting under infectious disease
[OLS view of 'parasitic infection'

ACTION: 
Change TA name to Infections and Infestations
Create 2 groups of ‘infection’ and ‘Infestation’ sitting under the TA Infections and infestations

Issue covering the synonyms in #481

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor: 
- [ ] Check synonyms of 'parasitic infection' that refer to 'infestation' and fix them as appropriate (e.g. make them broad or related rather than exact synonyms).
- [ ] Check if there are other uses of 'infestation' in EFO.

**Comment by paolaroncaglia** [comment]
@d0choa and Sandra
To address this request, I suggest to:

- [ ] Create EFO:NEW ‘infections and infestations’ or ‘infections or infestations’
Subclass of ‘disease’
In sunset ‘therapeutic areas’
With appropriate definition

Then
OT asks to “Create 2 groups of ‘infection’ and ‘Infestation’ sitting under the TA Infections and infestations”. In the disease branch, it would be complicated to separate infestations from infections completely. If I have to think of infestations where an infection is not necessarily involved, I think of rodents in a house; but that is not a disease. Compare with Wikipedia: “In general, the term "infestation" refers to parasitic diseases caused by animals such as arthropods (i.e. mites, ticks, and lice) and worms, but excluding (except) conditions caused by protozoa, fungi, bacteria, and viruses, which are called infections. Infestations can be classified as either external or internal with regards to the parasites' location in relation to the host. External or ectoparasitic infestation is a condition in which organisms live primarily on the surface of the host (though porocephaliasis can penetrate viscerally) and includes those involving mites, ticks, head lice and bed bugs. An internal (or endoparasitic) infestation is a condition in which organisms live within the host and includes those involving worms (though swimmer's itch stays near the surface). _Medically, the term "infestation" is often reserved only for external ectoparasitic infestations while the term infection refers to internal endoparasitic conditions._” (https://en.wikipedia.org/wiki/Infestation) 
All terms referring to ‘infestation’ in their label or definition currently in EFO and MONDO are children or descendants of ‘infectious disease’. There is even a specific term for ‘parasitic ectoparasitic infectious disease’ (child of ‘parasitic skin disease’), but that is still an infectious disease, same as all other parasitic infections. So I suggest that 

- [ ] EFO:NEW ‘infections and infestations’ (or ‘infections or infestations’) should have a single child, i.e. EFO:0005741 ‘infectious disease’.

We would also
- [ ] Check synonyms of 'parasitic infection' that refer to 'infestation' and fix them as appropriate (e.g. make them broad or related rather than exact synonyms).

Would that be acceptable please?

**Comment by smnorthen** [comment]
@ paolaroncaglia
Infestation = parasitic attack or subsistence on the skin and/or its appendages, as by insects, mites, or ticks; sometimes used to denote parasitic invasion of the organs and tissues, as by helminths. https://medical-dictionary.thefreedictionary.com/infestation

All tick/mite/ectoparasite children should ideally be sitting under ‘infestation’ under the new TA (infection or infestation).

As an example, Ectoparasitic skin infection could go to infestations as well and have another secondary path to the Skin TA.

**Comment by paolaroncaglia** [comment]
Note for self: issues in this ticket have been addressed via creation of an OT TA slim/profile.
