### ISSUE TITLE
Open Targets therapeutic area: Cysts, Polyps and Neoplasms

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#489]
Proposed TA name:     Cysts, Polyps and Neoplasms (benign, malignant and unspecified)
Current EFO TA name: Neoplasms
Priority for OT: Intermediate
Justification: Cysts and Polyps are clinically different to Neoplasms, but they are all grouped under neoplasm

Cyst = 1. Bladder, 2. an abnormal closed epithelium-lined sac in the body that contains a liquid or semisolid substance. Most are harmless, but they should be removed when possible because they occasionally may change into malignant growths, become infected, or obstruct a gland. There are four main types of cysts: retention cysts, exudation cysts, embryonic cysts, and parasitic cysts, 3. a stage in the life cycle of certain parasites https://medical-dictionary.thefreedictionary.com/cyst
Polyp = any growth or mass protruding from a mucous membrane. https://medical-dictionary.thefreedictionary.com/polyp
Neoplasm = tumor; any new and abnormal growth, specifically one in which cell multiplication is uncontrolled and progressive. Neoplasms may be benign or malignant. https://medical-dictionary.thefreedictionary.com/neoplasm

Currently in EFO - Polyp exists and goes to Neoplasm. Cyst itself does not exist in EFO (only specific type of cysts).
[OLS views of 'polyp' and 'kidney cyst']

ACTION: 
Change TA name to Cysts, Polyps and Neoplasms (benign, malignant and unspecified)
Create 3 groups under the new TA: 1. Neoplasms, 2. Cysts, 3. Polyps
Change cell proliferation disorder to neoplastic, precancerous and hyperplastic disease
Only temporary solution. There are a lot of inconsistent things under cell proliferation disease

**Comment by d0choa** [comment]
UPDATED ACTION:
- Change "cell proliferation disorder" to "neoplastic, precancerous and hyperplastic disease"

Note: Only temporary solution. There are a lot of inconsistent things under cell proliferation disease

**Comment by zoependlington** [comment]
Closing this ticket as all relevant work is in https://github.com/EBISPOT/efo/issues/607
