### ISSUE TITLE
Open Targets therapeutic area: Skin and subcutaneous tissue disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#491]
Proposed TA name: Skin and subcutaneous tissue disorders
Current EFO TA name:  Integumentary system disease 
Priority for OT: Low
Justification: Skin, subcutaneous tissues and hair, nail events should be captured separately and should not include cysts/neoplastic or gastrointestinal events. This TA requires clean-up of some of the events sitting underneath.
Related issue: 483

Skin = the outer covering of the body (...) The skin consists of two main parts: an outer layer, the epidermis, and an inner layer, the corium (or dermis). https://medical-dictionary.thefreedictionary.com/skin
Subcutaneous = beneath the skin. https://medical-dictionary.thefreedictionary.com/subcutaneous
Integumentary = 1. pertaining to or composed of skin. 2. serving as a covering https://medical-dictionary.thefreedictionary.com/Integumentary

Currently in EFO - Skin disease is sitting under integumentary system disease. No generic ‘subcutaneous disorder’ exists, only specific subcutaneous disorder types
[OLS views of 'skin disease' and 'subcutaneous neurofibromas']

ACTION: 
Keep TA name for now
Add Synonym that would be easier to understand
Fix list of terms that shouldn’t be under this term: Cornea, Lip, bartholin gland neoplasm, etc…

**Comment by paolaroncaglia** [comment]
- [ ] Also look at #483

**Comment by zoependlington** [comment]
Note to self:
Integumentary system is from MONDO (MONDO_0002051).

The integumentary system is an organ system consisting of the skin, hair, nails, and exocrine glands. Clean up the children that do not fit into one of these categories under integumentary system disease: https://docs.google.com/spreadsheets/d/1I9-mkMKWF0Bdf32exwYCUg2j-9EcjJjoZt0Ec2EBII4/edit?usp=sharing

**Comment by smnorthen** [comment]
@paolaroncaglia @zoependlington 
Please update TA name: 'Integumentary system disease' to 'Skin or subcutaneous tissue disease' to allow for easier understanding of the TA name. All hair and nail related children should continue to stay in this TA.
If it is structurally easier to create a new TA name of ''Skin or subcutaneous tissue disease' and move the current children of 'Integumentary system disease' underneath the new TA, then that would also be acceptable for OT.

**Comment by smnorthen** [comment]
@paolaroncaglia @zoependlington
Please keep TA name: 'Integumentary system disease'. After additional discussions, it is more accurate as it incorporates the hair, nails as well as skin. Sorry for the change (again)!
However, if possible, please can you add ''Skin or subcutaneous tissue disease" as a synonym?

**Comment by paolaroncaglia** [comment]
@smnorthen sure!
