### ISSUE TITLE
Open Targets therapeutic areas: Reproductive System and Breast Disorders + Renal and Urinary System Disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#492]
Proposed TA name:     
1. Reproductive System and Breast Disorders
2. Renal and Urinary System Disorders
Current EFO TA name:  Reproductive System Disease (IS NOT A TA AT THE MOMENT); Urinary System Disease TA; Disease of Genitourinary System
Priority for OT: High
Justification: The Renal/Urinary system and the reproductive system have separate bodily functions. These should be separated for more clarity.

Reproductive system = The bodily system concerned with reproduction, especially sexual reproduction, including in mammals the gonads, associated ducts, and external genitals. https://medical-dictionary.thefreedictionary.com/Reproductive+system
breast = the front of the chest, especially the modified cutaneous, glandular structure it bears, the mamma. In women the breasts are secondary sex organs with the function of producing milk after childbirth. The term breast is less commonly used to refer to the breasts of the human male, which neither function nor develop. https://medical-dictionary.thefreedictionary.com/breast+disorders
Renal = pertaining to the kidney. https://medical-dictionary.thefreedictionary.com/Renal
Urinary = pertaining to, containing, or secreting urine.https://medical-dictionary.thefreedictionary.com/urinary
genitourinary =  pertaining to the genital and urinary organs https://medical-dictionary.thefreedictionary.com/genitourinary

Currently in EFO:
[OLS views of:
breast disease
reproductive system (in EFO)
kidney disease
genitourinary system disorder
urinary system disease]

ACTION: 
Urinary system disease TA  should be renamed to Renal and Urinary system disease
Merge ‘disease of genitourinary system’ TA with the renamed ‘Renal and Urinary system disease’ TA
Create new Reproductive System and Breast Disorders TA
Add Breast disease as child of Reproductive System and Breast Disorders
Move reproductive system disease from the Renal and Urinary system disease (previously called genitourinary system) to the new term Reproductive System and Breast Disorders 
Opened issue: #464  (we might want to close it and open a different one for this action)

**Comment by paolaroncaglia** [comment]
- [ ] Also look at #464

**Comment by paolaroncaglia** [comment]
(TA = therapeutic area)

Currently, EFO has under ‘disease’:

- EFO MONDO:0021199 disease by anatomical system
- - EFO:0009663 disease of genitourinary system (is not a TA)
- - - EFO:0000512 reproductive system disease (is a TA)
- - EFO:0009690 urinary system disease (is not a TA)
- - - EFO:0003086 kidney disease (exact synonym: renal disease; is a TA)
- EFO MONDO:0024505 disorder by anatomical region
- - EFO MONDO:0000651 thoracic disease
- - - EFO:0009483 breast disease (is not a TA)

I have a few comments on the request to have TAs for “Reproductive System and Breast Disorders + Renal and Urinary System Disorders”:

disease of genitourinary system:
I believe that this grouping is meaningful from a medical standpoint (e.g. think urethra in mammalian males, has functions in both systems). We can make it a TA if desired, but we should keep it as is in EFO. MONDO has the same.

reproductive system disease:
It is already a TA. It can be cleaned up a bit (see previous comment), but I’d leave it as is. 

breast disease:
We can certainly make it a TA if desired. It may benefit from some minor edits (see previous comment), but I’d leave it as is otherwise. I’m not entirely convinced of having a TA that collects disorders of reproductive system and breast, as that would cover very diverse illnesses and in both genders, but we could certainly create it if that grouping is required for a specific reason.

urinary system disease:
We can certainly make it a TA if desired. It should be a subclass of disease of genitourinary system; MONDO has the same, we’ll let them know. As per its placement and children, “The urinary system, also known as the renal system or urinary tract, consists of the kidneys, ureters, bladder, and the urethra” (https://en.wikipedia.org/wiki/Urinary_system); also see UBERON:0001008 renal system). So, urinary system disease, and its child kidney disease (exact synonym: renal disease; already a TA), should stay as they are.

**Comment by paolaroncaglia** [comment]
Proposed action items as per today's meeting:

- Make 'urinary system disease' a subclass of 'disease of genitourinary system'
- Open a ticket with MONDO as they have the same issue
- Create TA "Reproductive System or Breast Disorders"
- Clean up ‘reproductive system disease’ branch as per https://github.com/EBISPOT/efo/issues/492#issuecomment-507671863
- Remove EFO MONDO:0024505 'disorder by anatomical region' in the EFO slim we'll build for OTAR TAs

To be double-checked with OTAR wrt "Renal and Urinary System Disorders":
“The urinary system, also known as the renal system or urinary tract, consists of the kidneys, ureters, bladder, and the urethra” (https://en.wikipedia.org/wiki/Urinary_system); also see UBERON:0001008 renal system). So, 

- Would OTAR be ok with EFO:0009690 'urinary system disease' being a TA (that would encompass its child EFO:0003086 'kidney disease' (exact synonym: renal disease; already a TA)
or
- Would OTAR prefer a different solution?

**Comment by d0choa** [comment]
EFO:0009690 'urinary system disease' becoming a TA will be the perfect solution for us.

A possible action is to review the current children of "disease by genitourinary system" not currently contained in "urinary system disease" that should indeed be children of "urinary system disease". After a quick look it doesn't seem to be a problem. Most of them (e.g. renal tuberculosis) are linked to both.

**Comment by paolaroncaglia** [comment]
Reviewing this ticket and listing pending AIs:
- [ ] Move 'calcium oxalate urolithiasis' under 'urolithiasis' (more granular than 'urinary system disease')
TBC
