### ISSUE TITLE
Open Targets therapeutic area: Metabolism and Nutrition Disorder

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#494]
Proposed TA name: Metabolism and Nutrition Disorder
Current EFO TA name:  N/A
Priority for OT: High
Justification:  Metabolism and Nutrition go hand in hand as the nutrition can influence one’s metabolic rate. So both terms should be combined in a new TA. Metabolism is the means by which the body derives energy and synthesizes the other molecules it needs from the fats, carbohydrates and proteins we eat as food, by enzymatic reactions helped by minerals and vitamins. https://www.ncbi.nlm.nih.gov/books/NBK22259/
Related issue: Issue 461

Metabolism = 1. the sum of all the physical and chemical processes by which living organized substance is produced and maintained (anabolism), and also the transformation by which energy is made available for the uses of the organism (catabolism). 2. Biotransformation metabolic https://medical-dictionary.thefreedictionary.com/Metabolism
Nutrition = the taking in and metabolism of nutrients (food and other nourishing material) by an organism so that life is maintained and growth can take place.  https://medical-dictionary.thefreedictionary.com/nutrition

Currently in EFO:
[OLS views of
metabolic process
nutritional disorder]

**Comment by paolaroncaglia** [comment]
- [ ] Take into account discussion in #461

**Comment by zoependlington** [comment]
Note to self:
@paolaroncaglia wrote on the previous ticket: "place EFO 'metabolic disease' as a child of (subclass of) MONDO 'nutritional or metabolic disease'." and David agreed with this approach.

**Comment by zoependlington** [comment]
Closing this ticket as the necessary steps for the slim are done and the clean up for EFO is outlined in https://github.com/EBISPOT/efo/issues/618
