### ISSUE TITLE
Open Targets therapeutic area: Musculoskeletal and connective tissue disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#495]
Proposed TA name: Musculoskeletal and connective tissue disorders
Current EFO TA name: Musculoskeletal system disease and connective tissue disease (Separate TAs)
Priority for OT: High
Justification: The skeletal system includes the bones of the skeleton and the cartilages, ligaments, and other connective tissue that stabilize or connect the bones. It should therefore be considered as a single TA and not separated out. https://my.clevelandclinic.org/health/articles/12254-musculoskeletal-system-normal-structure--function
Related issue: 462 

Musculoskeletal system =  all of the muscles, bones, joints, and related structures, such as the tendons and connective tissue, that function in the movement of body parts and organs. https://medical-dictionary.thefreedictionary.com/musculoskeletal+system
Connective tissue = a fibrous type of body tissue with varied functions; it supports and connects internal organs, forms bones and the walls of blood vessels, attaches muscles to bones, and replaces tissues of other types following injury. Connective tissue consists mainly of long fibers embedded in noncellular matter, the ground substance. https://medical-dictionary.thefreedictionary.com/Connective+tissue

Currently in EFO:
[OLS views of
musculoskeletal system disease
connective tissue disease]
 
ACTION
Create new term “Musculoskeletal and connective tissue disease” (TA)
Include ‘musculoskeletal system disease’ and ‘connective tissue disease’ under the new term

**Comment by paolaroncaglia** [comment]
- [ ] Also look at #462

**Comment by zoependlington** [comment]
Note to self:

Musculoskeletal system disease is currently a child of disease and disease by anatomical system.

Connective tissue disease is currently a child of disease.

Creating a new term, musculoskeletal and connective tissue disorder seems fine in this context and moving the above two terms under it.

**Comment by zoependlington** [comment]
This has been solved by the OTAR slim/profile.
