### ISSUE TITLE
Open Targets therapeutic area: Ear and Labyrinth disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#496]
Proposed TA name: Ear and Labyrinth disorders
Current EFO TA name:  Terms: Disease of ear and specific Labyrinth Terms exist (NOT A TA AT THE MOMENT)
Priority for OT: High
Justification: The Ear and the inner ear labyrinth are a separate organ with a unique biological function (hearing and balance) and should be its own TA. Including them in ‘Head and Neck’ is not specific enough. 

Ear: the organ of hearing and equilibrium. (See Plates.) It is made up of the outer (external) ear, the middle ear, and the inner (internal) ear. https://medical-dictionary.thefreedictionary.com/ear
Labyrinth: the inner ear, consisting of the vestibule, cochlea, and semicircular canals. The cochlea is concerned with hearing and the vestibule and semicircular canals with the sense of equilibrium. https://medical-dictionary.thefreedictionary.com/Labrynth

Currently in EFO:
[OLS views of
disease of ear
osseous labyrinth vestibule (in EFO)]

ACTION
Create new TA of Ear and Labyrinth disorders

**Comment by zoependlington** [comment]
Ear disease exists as disease of ear (MONDO:0021205), child of head disease, otorhinolaryngologic disease and sensory system disease. Many sibling terms may need reclassifying as a child of disease of ear.

Labyrinth disease exists as inner ear disease (EFO:0009672), child of auditory system disease and disease of ear. Should this remain a child of disease of ear?

Can these remain a child of auditory system disease? Children of auditory system disease (e.g. middle ear disease) may be able to be moved to child of disease of ear, but others (e.g. auditory system cancer) are more broad than disease of ear and would end up being sibling terms.

**Comment by paolaroncaglia** [comment]
@zoependlington 
Making a quick note here of my email conversation with Sandra today:
"...The TA (named 'ear or labyrinth disease') contains 'disease of ear' only at the moment; but then we have 'auditory system disease' currently under 'nervous system disease' which houses, among others, 'vestibular disease' referring to vestibular labyrinth. Looking at this very quickly, I think the solution will be to clean up children of 'auditory system disease' so we can remove that grouping term and its link to the nervous system TA. Then we'll have anything relating to ear and/or labyrinth under the appropriate TA. Some sub-terms like 'hearing disorder' may live in both the ear and nervous TAs."

**Comment by smnorthen** [comment]
@paolaroncaglia 
Thank you for looking into this issue. Looking at this TA again in full and the children sitting underneath as well as considering that 'labyrinth' is part of the inner ear in Uberon, the TA should be just 'Ear disorder', which is shorter and cleaner. Looking at the children now, it seems unnecessary to include 'labyrinth' in the TA name.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Your suggestion above sounds sensible to me. Again, @zoependlington will kindly implement it next time she builds the file. Thank you both.
