### ISSUE TITLE
Open Targets therapeutic area: Eye disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#497]
Proposed TA name: Eye disorders
Current EFO TA name:  Eye Disease (NOT A TA AT THE MOMENT)
Priority for OT: High
Justification: All eye related conditions should go to the eye, but they are not all nervous system disease (e.g. cataract)

Eye - 1. The organ of vision that consists of the eyeball and the optic nerve; Synonym(s): oculus, 2. The area of the eye, including lids and other accessory organs of the eye; the contents of the orbit (common). https://medical-dictionary.thefreedictionary.com/eye

Currently in EFO: Eye Disease sitting under ‘Disease of visual system’
[OLS views of
sensory system disease + eye disease (parents)
sensory system disease (children)]

ACTION
Assign therapeutic area to  ‘Disease of Visual system’
“Disease of Visual system” should be moved as a child of “disease by anatomical system”. Some of the descendants might also maintain links to the “nervous system disease”
Probably remove sensory system disease. Remap childrens underneath to appropiate TA (not critical)

Ticket raised by another department:  https://github.com/monarch-initiative/mondo/issues/525

**Comment by zoependlington** [comment]
Note to self:
Disease of visual system is currently a child of sensory system disease which is a child of nervous system disease.

Need to look through children to see if any require link to nervous system disease.

Sensory system disease is fine to delete as is not connected to GWAS, however it has many children that will require clean up.

**Comment by d0choa** [comment]
Comment from S.:
- Disease of visual system should be sitting as a TA under Disease as well as Disease of anatomical system.

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor, and for @d0choa and @smnorthen for their information:
The issue of 'eye disease' (and 'ear infection') being a descendant of 'nervous system disorder' has now been fixed in MONDO following my request (see https://github.com/monarch-initiative/mondo/issues/747). The latest MONDO release with that fix is not in OLS yet, but will be very soon.

**Comment by zoependlington** [comment]
This has been solved through the creation of the OTAR slim/profile.
