### ISSUE TITLE
Open Targets therapeutic area: Injury, Poisoning and Complications

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#498]
Proposed TA name: Injury, Poisoning and Complications
Current EFO TA name:  Injury is a TA, Poisoning and complication (NOT A TA)
Priority for OT: Intermediate
Justification: These diseases are currently scattered in different places in the ontology. It would be good to group them, as they are caused by external influences. 

Injury - harm or hurt; usually applied to damage inflicted on the body by an external force. Called also trauma and wound. https://medical-dictionary.thefreedictionary.com/injury
Poisoning - Poisoning occurs when any substance interferes with normal body functions after it is swallowed, inhaled, injected, or absorbed. https://medical-dictionary.thefreedictionary.com/poisoning
Procedure - Act or conduct of diagnosis, treatment, or operation. https://medical-dictionary.thefreedictionary.com/procedure
Complication  - 1. one or more disease(s) concurrent with another disease., 2. the occurrence of two or more diseases in the same patient., 3. an injury or disorder occurring in a patient with a pre-existing condition https://medical-dictionary.thefreedictionary.com/complication

Currently in EFO: 
[OLS view of
injury
poisoning
complication]

ACTION
Create a new term named ‘Injury, Poisoning and complications’ under “disease” (it will become a TA)
Move “injury”, “poisoning” and “complication” as children of this node

**Comment by zoependlington** [comment]
Note for self: Poisoning is currently a child of chemically-induced disorder, should it remain as a child here and be added as a child of the new term too?

**Comment by d0choa** [comment]
Comment from S.
- Poisoning should not be a child of chemically-induced injury as it could be due to food, chemical or non-chemical agents. Suggest keeping it as a child of Injury, Poisoning and complication TA.
