### ISSUE TITLE
Open Targets therapeutic area: Respiratory, thoracic and mediastinal disorders

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#499]
Proposed TA name: Respiratory, thoracic and mediastinal disorders
Current EFO TA name:  Respiratory System Disease (TA), Thoracic Disease (TA) and Mediastinal Disease (NOT A TA AT THE MOMENT)
Priority for OT: High
Justification: Anatomically, it’s valuable to group thoracic, mediastinal and respiratory diseases together. 
Related issue: #465 

Respiration - 1. the exchange of oxygen and carbon dioxide between the atmosphere and the body cells, including inhalation and exhalation, diffusion of oxygen from the pulmonary alveoli to the blood and of carbon dioxide from the blood to the alveoli, followed by the transport of oxygen to and carbon dioxide from the body cells. See also ventilation (def. 2) and see Plates., 2. the metabolic processes by which living cells break down carbohydrates, amino acids, and fats to produce energy in the form of adenosine triphosphate (ATP); called also cell respiration. https://medical-dictionary.thefreedictionary.com/respiration
Thorax - the part of the body between the neck and abdomen; it is separated from the abdomen by the diaphragm. Its walls are formed by the 12 pairs of ribs, attached to the sides of the spine and curving toward the front. The principal organs in the thoracic cavity are the heart with its major blood vessels and the lungs with the bronchi, which bring in the body's air supply. The trachea enters the thorax to connect with the lungs, and the esophagus travels through it to connect with the stomach below the diaphragm. https://medical-dictionary.thefreedictionary.com/thorax
Mediastinum = 1. a median septum or partition., 2. the mass of tissues and organs separating the sternum in front and the vertebral column behind, containing the heart and its large vessels, trachea, esophagus, thymus, lymph nodes, and other structures and tissues. It is divided into anterior, middle, posterior, and superior regions.https://medical-dictionary.thefreedictionary.com/Mediastinal+diseases

Currently in EFO: 
[OLS views of:
respiratory system disease
thoracic disease
mediastinal disease]

ACTION
Create new term ‘Respiratory, thoracic and mediastinal disorders’ (TA)
Move “respiratory system disease” inside new TA
Move Thoracic disease to new TA ‘Respiratory, thoracic and mediastinal disorders’
Move Mediastinal Disease to new TA ‘Respiratory, thoracic and mediastinal disorders’

**Comment by paolaroncaglia** [comment]
- [ ] Also look at #465

**Comment by zoependlington** [comment]
- Respiratory system disease (EFO:0000684) is able to be moved as a child of the new term easily
- Thoracic disease (MONDO:0000651) is classified in MONDO as child of disorder by anatomical region.
     - Requires has_disease_location (chest?) - is this in MONDO?
     - Do we need to mint an EFO term and map with MONDO?
- Mediastinal disease (MONDO:0043707) is classified in MONDO as a child of thoracic disease and disease by anatomical system.
     - Requires has_disease_location (mediastinum) - is this in MONDO?
     - Do we need to mint an EFO term and map with MONDO?

**Comment by smnorthen** [comment]
We would like to change the TA name to just: Respiratory or thoracic disease. The structure of the TA remains exactly the same. As the mediastinum is part of the thorax and considering the type of children under this TA, this naming would be more appropriate for EFO.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Sure, that makes sense. @zoependlington will update the label the next time she re-builds the owl file (thanks Zoe).
