### ISSUE TITLE
Import compound terms to EFO - FGPTO-1007

### ISSUE THREAD

**Issue by lauhuema** [EBISPOT/efo#50]
Import new terms to EFO request

**Comment by lauhuema** [comment]
Those are the compounds to be imported: https://docs.google.com/spreadsheets/d/19JrixUppcI533njsT05kgTGTdyvQNh2pFpwe0IOMUA0/edit#gid=0

**Comment by lauhuema** [comment]
This terms need to be added to EFO. We can import them rom CHEBI:
nitric oxide (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16480)
everolimus. Synomyn: 40-O-(2-hydroxyethyl)-rapamycin (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=E0D466DDF9CC1B23A7CB7B45D0E4897C?chebiId=CHEBI:68478)
amitrole. Synonym: 3-amino-1,2,4-triazole (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=8663AFCB9A40830D95117E9194952B15?chebiId=CHEBI:40036)
NS398. Synonyms: NS-398 (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=9CD103F2FBDD61F9D3E4E0F706DFA95F?chebiId=CHEBI:73458)
insulin-like growth factor-1 (Homo sapiens) (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=14A40E8FF34FCC5A9CBBCC7EFD6BDCCD?chebiId=CHEBI%3A80343)
transforming growth factor, beta 1 (http://www.ebi.ac.uk/interpro/entry/IPR003939)
ribavirin (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=B3D7272B1AD66ECC6D302F2286C6F4FE?chebiId=CHEBI:63580)
parathyroid hormone (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:80273)
L-arginine (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16467)
PD0332991. Synonym: palbociclib (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=F7792659787C1023F535B582D8A97581?chebiId=CHEBI:85993)
AG825. Synonym: tyrphostin AG 825 (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=BC93054D1EEB016924AC71CB97100065?chebiId=CHEBI:75405)
isopropyl alcohol. Synonym: propan-2-ol; isopropanol (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:17824)
Nutlin-3 (http://www.ebi.ac.uk/chebi/searchId.do;jsessionid=6199043402109D6D9989749BEC5CB840?chebiId=CHEBI:46742)
trovafloxacin (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:9763)
tryptamine (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:16765)
tyrosol. Synonym: 2-(4-hydroxyphenyl)ethanol (http://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:1879)
I couldn't find the next terms in CHEBI. I added the definition for some of them and the reference.
I found most of the terms in https://pubchem.ncbi.nlm.nih.gov
LMP-420. Definition: LMP-420 is a boronic acid-containing purine nucleoside analogue that transcriptionally inhibits TNF production but is non-cytotoxic to TNF-producing cells (PMID:18331642) (http://pubchem.ncbi.nlm.nih.gov/compound/497668)
PHA-665752. Definition: PHA-665752 ia a c-Met kinase inhibitor. PHA-665752 is ATP-competitive, an active-site inhibitor with greater than 50-fold selectivity for c-Met vs a panel of tyrosine and serine-threonine kinases (http://www.ncbi.nlm.nih.gov/pccompound?term=PHA-665752) (http://www.sigmaaldrich.com/catalog/product/sigma/pz0147?lang=en&region=GB)
NSC319726 (http://pubchem.ncbi.nlm.nih.gov/compound/5351307)
transforming growth factor beta 2 (Homo sapiens) (http://pubchem.ncbi.nlm.nih.gov/compound/56842206)
PD169316 (http://www.ncbi.nlm.nih.gov/pccompound?term=PD169316)
1R-Chl. Synonym: 1R-ChI-polyamide (http://www.ncbi.nlm.nih.gov/pccompound?term=1R-Chl)
versican. Definition: It is a large extracellular matrix proteoglycan, belonging to the family of hyaluronan-binding proteoglycans, that is present in a variety of tissues (PMID:12231358)
granulocyte colony-stimulating factor (Homo sapiens) (https://en.wikipedia.org/wiki/Granulocyte_colony-stimulating_factor)
granulocyte colony-stimulating factor (Mus musculus). Synonym: G-CSF. Definition: Granulocyte colony-stimulating factor is a lineage-restricted hematopoietic growth factor, stimulating final mitotic divisions and the terminal cellular maturation of the partially differentiated hematopoietic progenitors (http://www.sigmaaldrich.com/catalog/product/sigma/g8160?lang=en&region=GB)
HhAntag. Synonym: Hedgehog inhibitor (http://pubchem.ncbi.nlm.nih.gov/compound/9911630)
ICG-001 (http://pubchem.ncbi.nlm.nih.gov/compound/11238147)
IPI504. Synonym: retaspimycin hydrochloride (http://www.ncbi.nlm.nih.gov/pccompound?term=ICG-001)
methoxyacetic acid (http://pubchem.ncbi.nlm.nih.gov/compound/12251)
monobutyl phthalate (http://pubchem.ncbi.nlm.nih.gov/compound/8575)
N-hydroxy-PHIP (http://pubchem.ncbi.nlm.nih.gov/compound/104954)
protocatechuic aldehyde. Synonym: 3,4-dihydroxybenzaldehyde (http://pubchem.ncbi.nlm.nih.gov/compound/8768) (https://en.wikipedia.org/wiki/Protocatechuic_aldehyde)
quisinostat (http://pubchem.ncbi.nlm.nih.gov/compound/11538455) (https://en.wikipedia.org/wiki/Quisinostat)
tetradecylthioacetic acid (http://pubchem.ncbi.nlm.nih.gov/compound/114924) (https://en.wikipedia.org/wiki/Tetradecylthioacetic_acid)
thaxtomin A (http://pubchem.ncbi.nlm.nih.gov/compound/180098)

**Comment by siiraa** [comment]
@lauhuema Can you generate separate Webulous sheets for each group of imports (grouped by different ontology) please?

**Comment by paolaroncaglia** [comment]
(Simon contacted Laura for update today)

**Comment by paolaroncaglia** [comment]
@simonjupp 
You contacted @lauhuema for an update on this ticket some time ago. Did you hear back please? Cheers.

**Comment by paolaroncaglia** [comment]
Similar to #48. Laura from AE/GXA opened this ticket and requested one or two lists of terms to be imported (mostly chemicals; can't say if the two lists are the same or not because I can't access her spreadsheet), but she's left the EBI now. I searched 3 random terms from the second list and they aren't in EFO. In the other ticket, Dani wrote that "Anja, Nancy and Silvie at AE/GXA have all taken over some parts of Laura's work - she doesn't have a direct replacement". @simonjupp should we follow up with AE/GXA, or close these two tickets as out of date? Thanks.

**Comment by daniwelter** [comment]
Closing because we can no longer access the original spreadsheet. If this is still an issue, please refile as a new ticket.
