### ISSUE TITLE
Add 4DN assay terms to EFO

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/efo#504]
The 4DN project have requested a number of new EFO assay terms plus updates (mostly within the hierarchy) of existing assay terms.

New terms in template: https://docs.google.com/spreadsheets/d/19I490vfNl6AM4ry9l_b0Sg6C1kvc89gpSCYIPJ9B8ws/edit#gid=289179103

Requested term updates:
https://docs.google.com/document/d/1nod5ir3_9exFw12NmXl3BgUBEn9uiI5RsMQ2M-Tlxsg/edit

Additional diagram;
https://docs.google.com/presentation/d/1khYXhbsCwlpMZgaiwivx3biEzELrj8d0PubyRk7iKW0/edit#slide=id.g51ab5d37ae_1_0

**Comment by sbreiff** [comment]
Hello,

I'm the curator from 4DN who requested these terms - one update is that for the MC-Hi-C term I'd originally had in the new term spreadsheet, it's looking like there's still some discussion in the community about whether the official term should be MC-Hi-C or MC-3C or C-Walks - I've deleted the row for now, and may request the term at a later date when there is more of a consensus. I hope that doesn't cause too much trouble.

Thanks
Sarah

**Comment by daniwelter** [comment]
I'm afraid the term has already been generated. Would you like it to be obsoleted?

**Comment by sbreiff** [comment]
Alright, if it goes through in this release, will it be possible to obsolete it and replace it with another term in the next release?

**Comment by daniwelter** [comment]
Of course, incorrect terms are obsoleted or updated all the time.

**Comment by sbreiff** [comment]
Ok, let's opt for that then. I'm sorry for the trouble and I do appreciate your efforts to get everything in to this Monday's release.

**Comment by daniwelter** [comment]
All terms created or updated as requested, ready for release on Monday.
