### ISSUE TITLE
Review placement of Pubic Symphysis Diastasis

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#505]
Comment from S.:

Review placement of EFO:1001833 Pubic Symphysis Diastasis (currently subclass of reproductive system disease). The pubic symphysis is located near genitalia in males and females, but is indeed a cartilaginous joint. See https://en.wikipedia.org/wiki/Pubic_symphysis and UBERON:0003699. - Maybe this would be best linking to the Musculoskeletal & Connective tissue Disorder TA

**Comment by zoependlington** [comment]
https://github.com/EBISPOT/efo/issues/492

**Comment by paolaroncaglia** [comment]
Closing as duplicate of (part of) https://github.com/EBISPOT/efo/issues/492.
