### ISSUE TITLE
Hierarchical information in efo.json

### ISSUE THREAD

**Issue by Elysheba** [EBISPOT/efo#510]
Hi, 

when parsing the efo.json file, I noticed that there are EFO ids missing as parents/subjects and child terms/objects from the graph edges. This information is present on https://www.ebi.ac.uk/ols/ontologies/efo/.

For example: 
EFO:0003769 has 32 objects/child terms but is not a higher level term itself. In addition, this information is present on the website (https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0003769) where it has 2 parents (EFO_0000616, EFO_0001379) and 35 child terms. 

Similarly for EFO:0002916, on the hierarchy present on the website it has 2 parent terms (EFO_0000313, EFO_0009544) and 3 child terms (EFO_0005922, EFO_0000478, MONDO_0007648), but in the graph edges from the efo.json, it has no parents and only one child term (EFO_0005922).

So there seems to be a discrepancy between the efo.json and the online hierarchy here?

Thanks
Liesbeth

**Comment by henrietteharmse** [comment]
Hi Liesbeth,

With efo.json I assume that you refer to the json response from 
https://www.ebi.ac.uk/ols/api/ontologies/efo/terms?short_form=EFO_0003769.

To access the parent/child information you have follow the _links.parents/_links.children hrefs respectively. I.e., a new call need to be made to OLS:

Getting parents: 
https://www.ebi.ac.uk/ols/api/ontologies/efo/terms/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0003769/parents

Getting children: 
https://www.ebi.ac.uk/ols/api/ontologies/efo/terms/http%253A%252F%252Fwww.ebi.ac.uk%252Fefo%252FEFO_0003769/children

For further information on the REST API, you can visit https://www.ebi.ac.uk/ols/docs/api.

Keep well,
Henriette
