### ISSUE TITLE
Duplicate classes: SELEX and SELEX-seq

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/efo#514]
I think these are duplicates so one should be obsoleted.

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor: 
- [ ] Double-check the PMID references of the two terms before merging/obsoleting, as they are not the same.

**Comment by paolaroncaglia** [comment]
In summary:
- [ ] SELEX and SELEX-seq are duplicates, so, I'll merge (obsolete) SELEX into SELEX-seq; keep both PMIDs;
- [ ] gSELEX-Seq should be a child of SELEX-seq based on its definition;
- [ ] HT-SELEX should also be a child of SELEX-seq based on its definition.
