### ISSUE TITLE
Edit reference to GWAS in EFO website front page (and fix broken link)

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#527]
The external-facing EFO website front page (https://www.ebi.ac.uk/efo/) reads:
(all italics are mine, for clarity)

"The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for _external projects_ such as the _NHGRI_ GWAS catalog. It combines parts of several biological ontologies..."

I suggest changing to

"The Experimental Factor Ontology (EFO) provides a systematic description of many experimental variables available in EBI databases, and for _projects_ such as the _NHGRI-EBI_ GWAS catalog [where "NHGRI-EBI GWAS catalog" hyperlinks to https://www.ebi.ac.uk/gwas/]. It combines parts of several biological ontologies..."

Note that the same change should be made in the EFO release notes, in section 
4. Scope of the Ontology 
(https://github.com/EBISPOT/efo/blob/master/ExFactor%20Ontology%20release%20notes.txt).

**Comment by paolaroncaglia** [comment]
Also in https://www.ebi.ac.uk/efo/, this link is broken:
"... If you are new to ontologies, there is a short introduction on the subject available..."
"short introduction" hyperlinks to http://ontogenesis.knowledgeblog.org/66, not working at the moment.

**Comment by zoependlington** [comment]
All changes made to the EFO Website. I will change the release notes during the release.
