### ISSUE TITLE
Define design patterns to describe HCA experiments

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#53]
Relationships between entities describing experiments (protocol, assay, instruments, ...) will be established in HCA metadata V5.

- Define the design patterns that describe these relaionships
- Diagram may help.

**Comment by daniwelter** [comment]
Reviewed axiomatisation of seq assay in OBI and this looks pretty good so we should reuse this. They don't cover single cell sequencing but current EFO term axioms cover this part so we could merge the two.

**Comment by daniwelter** [comment]
https://docs.google.com/document/d/1zW_Zhm2Npy4hZIqoXas6cz-dtnMAk3KYg8qKkaOPcSk/edit#
