### ISSUE TITLE
IRI for ProcessualEntity appears false?

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#536]
Currently: 
http://www.ifomis.org/bfo/1.1/span#ProcessualEntity

All other BFO 1.1 terms:
http://www.ifomis.org/bfo/1.1/snap#XYZ

**Comment by paolaroncaglia** [comment]
@matentzn 
Zoe believes this is fixed now (updated to BFO:0000015). So we're moving to Done, but feel free to object. Cheers :-)

**Comment by paolaroncaglia** [comment]
This is done, but I'm assigning to @matentzn and @zoependlington for the records.
