### ISSUE TITLE
Define classification differentia of experimental process in EFO

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#54]
Examine OBI for the experimental process differentia/classification:
EFO's "experimental process" lacks clear differentia/criteria. OBI classification in combination with #53 should provide an idea on how to fix the classification of experimental process in EFO.

**Comment by paolaroncaglia** [comment]
@daniwelter 
Asking for your feedback on this ticket please, as it's labeled HCA and I see that the other ticket Sira mentioned above was closed by you. Should we close this one too? Or should we keep it open and maybe make it an epic? Thanks.

**Comment by daniwelter** [comment]
@paolaroncaglia This ticket should remain open or be replaced with a wider one to punt some or all of our experimental process hierarchy to OBI. We have quite a lot of terms in EFO that aren't in OBI but we should explore if we can get these into OBI, and put a more general pipeline in place to request new process terms via OBI. This was on my long-term radar but I won't get around to it before I go on maternity leave.

**Comment by paolaroncaglia** [comment]
Thanks @daniwelter.

**Comment by daniwelter** [comment]
Covered/replaced by #501
