### ISSUE TITLE
New EFO Terms for Single Cells Atlas

### ISSUE THREAD

**Issue by S2Ola** [EBISPOT/efo#545]
- Create the following new terms in the google sheets: https://docs.google.com/spreadsheets/d/1cpo6Gm1NX5sDrFGwfnLZhaXX3YsDRKnWviT_dJ5s6Es/edit#gid=0

-  FACS | Move FACS from sample dissociation to single cell isolation after creating single cell isolation 
-  Fluidigm C1 | Move from sample dissociation to single cell isolation

- Droplet based isolation | Create a new term for '10x based cell isolation'

- cell picking | Need a definition for this

- mouth pipette | Need a definition for this

- laser capture micro dissection | Keep as both laser capture and add as new child 

-  cDNA   library construction |   | Add synonym

- single cell library   construction |   | create this, with synonym for preparation

**Comment by zoependlington** [comment]
- [ ] Single cell isolation
    - Child of sample enrichment, agreed with Anja - no need for cell isolation.
    - Definition in spreadsheet
    - Desired children in spreadsheet

- [ ] Library preparation should NOT be renamed. This is an OBI term. 
     - library construction is already a synonym.

- [ ] single cell library construction
     - Spreadsheet suggestion is fine, a lot of the children have the requested synonyms already so double check those.

- Children of Information entity (the final block of terms), should be OBI or EFO terms.
