### ISSUE TITLE
head disease oddities

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#55]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000524

The definition is:

"The name of the pathology diagnosed in the organism from which the biomaterial was derived. The disease state is normal if no disease has been diagnosed. E.g Acute Lymphocytic Leukemia"

This is obviously for something different.

Additionally: is this a useful grouping?

Perhaps a more useful grouping is head+neck?

**Comment by siiraa** [comment]
yea, it is not very clear why this was created. Agreed that it's not really helpful. There is a 'head and neck neoplasia' whose definition is very specific to oncologists. Might be more useful to have 'head and neck disorder' (https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C27571) instead, so then we can move 'head and neck neoplasia' under this parent.

**Comment by siiraa** [comment]
modified EFO_0000524 and reclassified EFO_0005950 for better grouping
