### ISSUE TITLE
error with Cystic Fibrosis subclass?

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#553]
see ticket: https://github.com/monarch-initiative/mondo/issues/685

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
I'm assuming you are referring to
EFO:0004608 'cystic fibrosis associated meconium ileum'
being a subclass of EFO Orphanet 'Cystic fibrosis'?
I agree that that's not ideal; EFO:0004608 'cystic fibrosis associated meconium ileum' is defined as "Cystic fibrosis associated meconium ileum is a thickening and congestion of the meconium in the ileum in newborns, often the first sign of cystic fibrosis. In cystic fibrosis, the meconium can form a bituminous black-green mechanical obstruction in a segment of the ileum. Beyond this there may be a few separate grey-white globular pellets. Below this level, the bowel is a narrow and empty micro-colon. Above the level of the obstruction, there are several loops of hypertrophied bowel distended with fluid. No meconium is passed, and abdominal distension and vomiting appear soon after birth. About 20% of cases of cystic fibrosis present with meconium ileus, while approximately 20% of one series of cases of meconium ileus did not have cystic fibrosis The presence of meconium ileus is not related to the severity of the cystic fibrosis. [ EFO:0004608 ]"
I suggest to 
- [ ] make EFO:0004608 'cystic fibrosis associated meconium ileum' a subclass of an appropriate term in the intestinal disease branch instead; also make it a subclass of perinatal disease or similar
- [ ] fix another, bigger problem I noticed with EFO Orphanet 'Cystic fibrosis': of all its current parents in EFO, only 'autosomal recessive disease' should stay; all other parents should be deleted bcs they represent symptoms/phenotypes, CF is a multi-systemic disease.

**Comment by paolaroncaglia** [comment]
The issue of incorrect parents of EFO Orphanet 'Cystic fibrosis' came up again today in a discussion with Open Targets, where it causes undesirable consequences, so I'll up its priority.

**Comment by paolaroncaglia** [comment]
Summing up:

- [ ] Make EFO:0004608 'cystic fibrosis associated meconium ileum' a subclass of 'small intestine disease' instead of 'cystic fibrosis'
- [ ] Narrow down its disease location to 'ileum'
- [ ] When a term is created for 'perinatal disease' or similar (see https://github.com/EBISPOT/efo/issues/490), add it as a parent of 'cystic fibrosis associated meconium ileum'.

TBC

**Comment by paolaroncaglia** [comment]
The most urgent edits for cystic fibrosis terms are done, so I'll remove the high-priority pin. 
I'll leave the ticket open as a reminder of the last bits.

**Comment by paolaroncaglia** [comment]
Reviewing this ticket now that Mondo has released its changes:
- [ ] Add the Mondo mapping and the Mondo term back in their respective files:
http://purl.obolibrary.org/obo/MONDO_0005413	http://www.ebi.ac.uk/efo/EFO_0004608	cystic fibrosis associated meconium ileum cystic fibrosis associated meconium ileum
http://purl.obolibrary.org/obo/MONDO_0005413
TBC

**Comment by paolaroncaglia** [comment]
Note for self: Mondo released yesterday, so the edits in my previous comment may be ready to go.
