### ISSUE TITLE
Revise definition of 'function'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#554]
EFO 'function' (http://www.ifomis.org/bfo/1.1/snap#Function) is currently defined as:
"A function is an entity which is an essentially end-directed activity of a material entity in virtue of that entity being a specific kind of entity in the kind or kinds of contexts that it is made for. For example,"
However, that def is incomplete. We should check if it's changed in BFO2. Also, there's an extra space before "For example". Note, this term is an Open Targets therapeutic area, and the change will need to be implemented in any OT slim/profile if not done automatically via pipeline.

**Comment by d0choa** [comment]
We also have a [ticket open](https://github.com/opentargets/platform/issues/543) on whether we should ignore this term. The only reason why we keep it is because some of the children terms being relevant for GWAS studies. We don't need a `Function` term per se.

**Comment by paolaroncaglia** [comment]
Moving this to Done as it will be addressed as part of https://github.com/ebispot/efo/issues/535.
