### ISSUE TITLE
Review deleted terms in EFO OT TA slim/profile

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#576]
cc @zoependlington 
A quick note that @simonjupp  suggested going through the list of “removed” terms in the EFO Open Targets Therapeutic Areas slim/profile, and deciding if they’re a good candidate for obsoletion in actual EFO too, e.g. 'disease by anatomical system'.

**Comment by paolaroncaglia** [comment]
Note for self: fine to leave this ticket for after the mid-October release.

**Comment by zoependlington** [comment]
All currently removed terms:

> p
> http://purl.obolibrary.org/obo/MONDO_0021199
> http://www.ebi.ac.uk/efo/EFO_0000319
> http://purl.obolibrary.org/obo/MONDO_0021195
> http://www.ebi.ac.uk/efo/EFO_0001058
> http://purl.obolibrary.org/obo/MONDO_0000651
> http://purl.obolibrary.org/obo/MONDO_0024505
> http://purl.obolibrary.org/obo/MONDO_0018652
> http://www.ebi.ac.uk/efo/EFO_0009470
> http://purl.obolibrary.org/obo/MONDO_0044965
> http://purl.obolibrary.org/obo/MONDO_0020595
> http://purl.obolibrary.org/obo/MONDO_0020683
> http://www.ebi.ac.uk/efo/EFO_0009714
> http://purl.obolibrary.org/obo/MONDO_0024236
> http://purl.obolibrary.org/obo/MONDO_0021668
> http://purl.obolibrary.org/obo/MONDO_0024317
> http://purl.obolibrary.org/obo/MONDO_0021147
> http://www.orpha.net/ORDO/Orphanet_79389
> http://purl.obolibrary.org/obo/MONDO_0020012
> http://www.ebi.ac.uk/efo/EFO_0000524
> http://purl.obolibrary.org/obo/MONDO_0024623
> http://www.ebi.ac.uk/efo/EFO_0009903
> http://purl.obolibrary.org/obo/MONDO_0043786
> http://purl.obolibrary.org/obo/MONDO_0019038
> http://purl.obolibrary.org/obo/MONDO_0005042
> http://purl.obolibrary.org/obo/MONDO_0044999
> http://www.ebi.ac.uk/efo/EFO_0009479
> http://purl.obolibrary.org/obo/MONDO_0002254
> http://purl.obolibrary.org/obo/MONDO_0021073
> http://purl.obolibrary.org/obo/MONDO_0100079
> http://purl.obolibrary.org/obo/MONDO_0021670
> http://purl.obolibrary.org/obo/MONDO_0021674
> http://purl.obolibrary.org/obo/MONDO_0021673
> http://purl.obolibrary.org/obo/MONDO_0021669
> http://purl.obolibrary.org/obo/MONDO_0044990
> http://purl.obolibrary.org/obo/MONDO_0044989
> http://purl.obolibrary.org/obo/MONDO_0044967
> http://purl.obolibrary.org/obo/MONDO_0044987
> http://purl.obolibrary.org/obo/MONDO_0015938
> http://purl.obolibrary.org/obo/MONDO_0017259
> http://purl.obolibrary.org/obo/MONDO_0017261
> http://purl.obolibrary.org/obo/MONDO_0017368
> http://purl.obolibrary.org/obo/MONDO_0017260
> http://purl.obolibrary.org/obo/MONDO_0044974
> http://purl.obolibrary.org/obo/MONDO_0044971
> http://purl.obolibrary.org/obo/MONDO_0044979
> http://purl.obolibrary.org/obo/MONDO_0021017
> http://purl.obolibrary.org/obo/MONDO_0044969
> http://purl.obolibrary.org/obo/MONDO_0044975
> http://purl.obolibrary.org/obo/MONDO_0044977
> http://purl.obolibrary.org/obo/MONDO_0021194
> http://purl.obolibrary.org/obo/MONDO_0044976
> http://purl.obolibrary.org/obo/MONDO_0024626
> http://purl.obolibrary.org/obo/MONDO_0021197
> http://purl.obolibrary.org/obo/MONDO_0021196
> http://purl.obolibrary.org/obo/MONDO_0044980
> http://purl.obolibrary.org/obo/MONDO_0021635
> http://www.ebi.ac.uk/efo/EFO_1000755
> http://purl.obolibrary.org/obo/MONDO_0020150
> http://www.ebi.ac.uk/efo/EFO_0009664
> http://purl.obolibrary.org/obo/MONDO_0024627
> http://purl.obolibrary.org/obo/MONDO_0021016

**Comment by zoependlington** [comment]
Part of the strategy ongoing is to review and obsolete these terms if they are not required in EFO

**Comment by paolaroncaglia** [comment]
@zoependlington I suspect that this ticket may be out of date, e.g. the "disease/disorder by" terms coming from Mondo have been obsoleted there since. Close?

**Comment by zoependlington** [comment]
Yes, this is now mostly solved through Mondo so can be closed.
