### ISSUE TITLE
Ribo-seq EFO_0008891 not under "assay by sequencer" any more?

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#581]
As previously requested the term "Ribo-seq" was put under "assay by sequencer" EFO_0003740 (see issue #395). However, now the term is not a child of EFO_0003740 any more. Can this please be put back? ArrayExpress submissions processing is relying on this classification for the automatic MIAME/MINSEQE scoring.

**Comment by paolaroncaglia** [comment]
@anjaf 
@zoependlington will look into this asap, we're not sure what happened. Thanks for reporting!

**Comment by zoependlington** [comment]
@anjaf This should be fixed now. Not sure why it suddenly disappeared, very perplexing! If there are any terms that you are relying on to have specific relationships, would it be possible to collect these and send them to us? I can set up a validator to ensure that these relationships are always in EFO and will throw an error if we build the ontology and they're missing. Thanks!

**Comment by anjaf** [comment]
Thanks for your quick action @zoependlington!
I wish we had a list for all of the specific EFO dependencies too! I will start having a look into collection them. Unfortunately most of these occur in our many legacy systems. If it is fine with you guys, in the mean time we keep on reporting whenever something breaks. Which hasn't happen that often so far (fingers crossed!).

**Comment by zoependlington** [comment]
Of course @anjaf 😄 Let's keep our fingers crossed that something breaking continues to not be a common occurrence. Please don't hesitate to let us know if there's anything we can change/add!
