### ISSUE TITLE
Fungal diseases should not be children of immune system disease

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#582]
There are a number of fungal diseases, e.g. cryptococcosis (EFO_0007229) that are currently children of immune system disease. Many of these reference affecting immunocompromised people more often - but the same can be said with any infection and therefore this does not justify being under immune system disease.

**Comment by paolaroncaglia** [comment]
Note, this is an EFO-only issue: the affected terms are EFO ones, and the placement of the corresponding classes in Mondo are correct.

**Comment by zoependlington** [comment]
All have been edited apart from geotrichosis, which inherits connection to immune system disease from Mondo (see: https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0005772)
