### ISSUE TITLE
Animal disease clean up

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#584]
Many terms under animal disease also fall under human disease categories in EFO. This may cause issues for Open Targets. The following should be children of animal disease only:

- heartwater disease (EFO_1000960)
- parasitic disease, non-human animal (MONDO_0024969) - need to check Mondo
- visna (EFO_0007542)
- steatitis (EFO_1001191)
- actinobacillosis (EFO_0007127)
- enzootic pneumonia of calves (EFO_0007256)
- peste des petits ruminants infectious disease (EFO_0007431)

**Comment by paolaroncaglia** [comment]
At the EFO-Mondo call today, we agreed that EFO will (temporarily?) remove the Mondo mappings for animal disease terms.

**Comment by paolaroncaglia** [comment]
Please also note Open Targets' request that "the related scrapie - EFO:1001168 should be moved to animal disease" (from https://github.com/EBISPOT/efo/issues/580). But 'scrapie' is under 'prion disease', which is correct, and prion disease is a broad term that encompasses the bovine as well as the human host.
