### ISSUE TITLE
UniProtKB 2019_09 release OMIM to EFO mappings

### ISSUE THREAD

**Issue by ggeorghiou** [EBISPOT/efo#588]
Hi all,

We have new a new release with OMIM terms that I have mapped to EFO. In cyan are the new term requests, red is phenotypes that I have not mapped (I know you don't need them but for the sake of record keeping internally I left them in), and ones not highlighted are OMIM IDs that can be mapped to existing EFO terms or MONDO/Orphanet terms that we'd like to see added to EFO. The link is below.

https://docs.google.com/spreadsheets/d/1Fou1js3hik7fR2ih7k1dBF6vY2Qh8avXr_bEDLld07U/edit?usp=sharing

Thanks in advance.

**Comment by paolaroncaglia** [comment]
Pinning this ticket as, ideally, we should address it before its submitter leaves EBI, in case we have questions. Therefore I'll aim to complete it before the end of November.

**Comment by paolaroncaglia** [comment]
Note for self:
I've collated the spreadsheets from this ticket and from its "sibling" https://github.com/EBISPOT/efo/issues/593 into one table, at https://docs.google.com/spreadsheets/d/1FB2NVE4qVNf58NEhxmh-sirJ2t4gotj700YUIlrlNN4/edit#gid=1920751655.

**Comment by zoependlington** [comment]
ROBOT template mappings have been added.

**Comment by paolaroncaglia** [comment]
@ggeorghiou 
All done now - OMIM mappings from UniProtKB 2019_09 and 2019_10 releases are now in EFO.
All details, including IDs for new EFO and Mondo terms, plus my comments, are in this spreadsheet https://docs.google.com/spreadsheets/d/1FB2NVE4qVNf58NEhxmh-sirJ2t4gotj700YUIlrlNN4/edit#gid=1920751655, in the tab "All entries, no phenotypes, A-Z". 
Thanks to @zoependlington for helping with adding 24 OMIM mappings via ROBOT. 
All mappings will be visible in our next EFO release planned for Dec 16th.
All the best,
Paola
