### ISSUE TITLE
Cicatricial alopecia (and related terms)

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#60]
## Preferred term label
Cicatricial alopecia
https://rarediseases.org/rare-diseases/cicatricial-alopecia/

## Synonyms
alopecia cicatrisata
scarring alopecia
scarring hair loss

## Textual definition
Scarring hair loss, also known as cicatricial alopecia, is the loss of hair which is accompanied with scarring. This is in contrast to non scarring hair loss.
Source: https://en.wikipedia.org/wiki/Scarring_hair_loss

## Suggested parent term
This needs a bit of reorganisation in EFO
Alopecia is the parent term (should map to HP corresponding term by the way)
Alopecia should be a child of skin diseases in EFO.
'alopecia areata' should be a child of Alopecia too.
('androgenetic alopecia' is already a child of Alopecia)

## x-refs
ICD10: L66

## Attribution

https://orcid.org/0000-0002-6315-0263

**Comment by siiraa** [comment]
Alopecia is a child of rare genetic skin disease (ORDO-defined) which we have classified the 'rare genetic skin disease' as a skin disease, so you should see Alopecia as a child of skin disease already (skin disease -> rare genetic skin disease -> genetic epidermal appendage anomaly -> genetic hair anomaly -> alopecia). will work to add cicatricial alopecia to this class.
