### ISSUE TITLE
Difference between "Influenza" and "Influenza infection"

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#600]
Both [influenza]( http://www.ebi.ac.uk/efo/EFO_0007328) and [influenza infection]( http://www.ebi.ac.uk/efo/EFO_0001669) are two separate terms in EFO with two independent lineages (disease vs biological process) but there are **NO** clear differences between them. Apparently _influenza infection_ `has_phenotype` _influenza_ but this is not shown in the hierarchy. In addition, the descriptions of both terms are identical and _influenza infection_ is a synonym of _influenza_.

All in all, these terms seem to be duplicates of each other and they are causing some issues for Open Targets as they have different targets associated to them. Are they really two separate things or should they be merged?

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
Thanks for catching and reporting this.
The two terms are indeed duplicates. 'influenza infection' was most likely added first. 'influenza' is more correctly placed, has more cross-references (including all the ones in 'influenza infection' except for  SNOMEDCT:6142004), and is aligned with Mondo. I suggest to merge the 2 in favour of 'influenza'.

**Comment by paolaroncaglia** [comment]
Addendum to the strategy above for fixing the duplication of 'influenza' terms in EFO:
The SNOMEDCT xref is already in EFO:0007328 via Mondo, so no action item there;
- [ ] When EFO_0001669 is merged into EFO_0007328, notify Mondo, as MONDO:0005812 'influenza' xrefs both http://purl.obolibrary.org/obo/EFO_0007328
and 
http://purl.obolibrary.org/obo/EFO_0001669.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
The duplication of 'influenza' terms is now resolved. Edits will be visible in the EFO release scheduled for Feb 17th. Thanks.

**Comment by AsierGonzalez** [comment]
Fantastic, thank you @paolaroncaglia
