### ISSUE TITLE
Unable to locate efo_inferred.owl

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#602]
As we move to EFO3 in Open Targets we need to update the EFO urls that some of our tools use. One of such tools uses a file called `efo_inferred.owl` that used to be in the main directory, e.g. https://raw.githubusercontent.com/EBISPOT/efo/v2019-03-18/efo_inferred.owl and that it is not there since any more (apparently is has not been there since the move to EFO3), i.e. https://github.com/EBISPOT/efo/raw/master/efo_inferred.owl does not exist.
The EFO2 readme suggested that https://www.ebi.ac.uk/efo/efo_inferred.owl was the same file. This url still exists but this information is not in the readme. Can you confirm that it is still the same type of file and that it has the latest version?

**Comment by zoependlington** [comment]
Hi @AsierGonzalez,

The EFO3 released efo.owl file is the inferred version of EFO now, we do not release separate asserted and inferred versions, just the inferred. This can be found attached to all of our releases (found [here](https://github.com/EBISPOT/efo/releases)) if you would like individual versions or at https://www.ebi.ac.uk/efo/efo.owl. I will make this more clear in our readme.

Please let us know if you have any other questions or if there is anything else we can do.

**Comment by AsierGonzalez** [comment]
Thank you @zoependlington, this is all I needed to know. I'll use the URL that points to the latest release then.
