### ISSUE TITLE
Terms to describe incident or recurrent cases of a disease

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#603]
It would be helpful for the [Polygenic Score Catalog](http://www.pgscatalog.org) to have a flexible way to describe recurrent or incident cases of disease using EFO rather than making an explicit child term for each disease.

## Preferred term labels
"incident" and "recurrent"

## Synonyms
N/A

## Textual definition
"Recurrent" refers to episodes of disease that occur in individuals who have already had the disease. This term is present in the [NCIT ontology](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C14173&viewMode=All&siblings=false) and the [Human Phenotype Ontology](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0031796).

"Incident" cases of a disease are defined as individuals that change from a non-disease to a disease status over the course of a study (or during a specific period of time). An explanation of the term as used by epidemiologists can be found [here](https://sph.unc.edu/files/2015/07/nciph_ERIC1.pdf).

## Suggested parent term

I couldn't find a suitable parent in the EFO at the moment. I suggest a new parent term in the "information entity" category like "Disease qualifier" as in NCIT.

## Attribution
ORCID: [0000-0001-8222-008X](http://orcid.org/0000-0001-8222-008X)

**Comment by paolaroncaglia** [comment]
@smlmbrt 
(cc @zoependlington and @twhetzel )
Thanks for your input. I'd suggest to add the two new terms 'incident' and 'recurrent' as subclasses of EFO:0009813 'disease characteristic' (http://www.ebi.ac.uk/efo/EFO_0009813). A second option would be as subclasses of EFO HP:0012823 'clinical modifier' 
(http://purl.obolibrary.org/obo/HP_0012823). I have a mild preference for the first option. We might check with Mondo as they have several 'recurrent' disease terms. Also, for 'recurrent' we should add xrefs to NCIT and HP as @smlmbrt suggests, and to PATO:0000427.

**Comment by smlmbrt** [comment]
@paolaroncaglia 
Thanks for the feedback! I'd agree that _recurrent_ seems like it might fit best under 'disease characteristic'. In the case of the _incident_ term it actually depends more on the study design used to ascertain the phenotype. Maybe their top-level in the disease characteristic section could be 'clinical course' like [here](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0031797&viewMode=All&siblings=false).

**Comment by paolaroncaglia** [comment]
@smlmbrt @zoependlington 
Thanks for the extra input. Looking into this again, strictly speaking 'incident' is not a characteristic of a disease (the disease stays the same, what changes is whether it's observed as a new case within the study period). So I'd lean towards adding 'incident' as a subclass of 'clinical modifier' ("This subontology is designed to provide terms to characterize and specify the phenotypic abnormalities defined in the Phenotypic abnormality subontology, with respect to severity, laterality, age of onset, and other aspects.") (http://purl.obolibrary.org/obo/HP_0012823). It may not be perfect, but I think it'd fit well enough. (I'd still add 'recurrent' as a subclass of 'disease characteristic', as agreed above.) Would you both agree with this plan?

**Comment by zoependlington** [comment]
@paolaroncaglia This sounds like a good plan to me, makes more sense than both being a disease characteristic.

**Comment by smlmbrt** [comment]
@paolaroncaglia that sounds good to me as well.

**Comment by paolaroncaglia** [comment]
@twhetzel 
I'll leave this to you for the edits, as agreed, but let me know if anything else is needed. Thanks.

**Comment by twhetzel** [comment]
- [ ] add 'incident' as a subclass of 'clinical modifier' (http://purl.obolibrary.org/obo/HP_0012823)
_Definition_: A disease that is observed as a new case within the study period.

- [ ] add "recurrent" as a subclass of EFO:0009813 'disease characteristic' (http://www.ebi.ac.uk/efo/EFO_0009813)
_Definition_: Episodes of disease that occur in individuals who have already had the disease.
