### ISSUE TITLE
Osteomalacia / Adult Osteomalacia classification in EFO

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#61]
## Preferred term label

Osteomalacia (https://en.wikipedia.org/wiki/Osteomalacia)

## Synonyms

Adult Osteomalacia
Adult Rickets
rachitis tarda
adult rickets
late rickets

## Textual definition

Disorder caused by an interruption of the mineralization of organic bone matrix leading to bone softening, bone pain, and weakness. It is the adult form of rickets resulting from disruption of VITAMIN D; PHOSPHORUS; or CALCIUM homeostasis.

Source: https://meshb.nlm.nih.gov/record/ui?ui=D010018

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0005583

## X-refs
MP:0009445
HP:0002749
MESH:D010018
ICD10M:M83
https://en.wikipedia.org/wiki/Osteomalacia

## Attribution

https://orcid.org/0000-0002-6315-0263

**Comment by siiraa** [comment]
Hi @gkos-bio ,

Is this a request for a new term, or a re-classification of an exisiting term? I can't seem to find the term so I'm guessing this is a new term? Please advise.

Thank you,
Sira
