### ISSUE TITLE
Complement component C1q deficiency

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/efo#611]
Can you please create a new EFO term for this OMIM term? It's already in CCO for some reason.

For new term requests, please provide the following information:

## Preferred term label:
Complement component C1q deficiency

## Synonyms:
C1QD

## Textual definition:
A disorder caused by impaired activation of the complement classical pathway. It generally leads to severe immune complex disease with features of systemic lupus erythematosus and glomerulonephritis.

## Suggested parent term:
OMIM:613652 [EXACT]

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo):
I really don't know how diseases are ontologically classified.
probably is_a MONDO:0003832
maybe even is_a MONDO:0000015

## Attribution:
0000-0003-4062-6158

Thanks,
Birgit

Note to self: Complex C1q, EBI-6264901/CPX-1919

**Comment by paolaroncaglia** [comment]
Hi @bmeldal !
We could import MONDO:0013343 C1Q deficiency (has the OMIM term you're looking for, OMIM:613652, as an xref, and C1QD as a related synonym), and give it an exact synonym 'complement component C1q deficiency'. I'd place it as a child of  EFO > MONDO:0000015 'classic complement early component deficiency' (the legend of figure 1 in this paper is a reference that C1q is an early component: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4753731/). The term would come with the long Mondo definition, but I assume that will be ok. We'll also add your ORCid ID.
Let us know if you have any comment.
Thanks,
Paola

**Comment by bmeldal** [comment]
Hi @paolaroncaglia 

Good to hear from you!

Yes, that looks like a good idea. 

2 amendments:

1. Can we fix one issue in the def:
- "C1q is a protein and together with other proteins, C1r and C1s,..."
+"C1q is a COMPLEX and together with other proteins, C1r and C1s,..."
because C1q constitute of C1QA , C1QB and C1QC.

2. C1QD is also EXACT synonym

**Comment by paolaroncaglia** [comment]
@bmeldal 
Good then, we'll import MONDO:0013343 C1Q deficiency.
The definition (and synonym scope if required) would need to be edited at the source, i.e. you should open a ticket in the Mondo tracker please (https://github.com/monarch-initiative/mondo/issues). We (EFO) can add to terms imported from Mondo, but we can't change what they have as we import from them dynamically (our changes would be reverted at every Mondo release, unless they make the changes themselves).

**Comment by paolaroncaglia** [comment]
@bmeldal 
P.S. If you do open a ticket in Mondo, you might also mention please that the def of MONDO:0013343 seems to have plenty of typos, they could fix them all in one go. Thanks!

**Comment by bmeldal** [comment]
2 MONDO tickets opened.

Thanks.

**Comment by bmeldal** [comment]
MONDO tickets have been closed. You can pull in the term now.

**Comment by paolaroncaglia** [comment]
@bmeldal 
Thanks. The revised Mondo term MONDO:0013343 C1Q deficiency (i.e. including your suggested changes) will be available with Mondo's December release (they usually release at the start of each month). We can then import it into EFO in time for our mid-December release. I'll update this ticket when that's done. I _think_ that, if you wish to annotate your complex with a disease ontology ID already, you can use MONDO:0013343 already as the ID and the PURL won't change after we import in EFO. But if your annotation requires info other than a Mondo ID, then I'm not sure.
Thanks and I'll keep you posted when this ticket is done.

**Comment by paolaroncaglia** [comment]
Note for self (cc @bmeldal ): 
Mondo released yesterday, so I'll check if all's well with MONDO:0013343 C1Q deficiency and will then import it into EFO, before our next release (Dec 16).

**Comment by paolaroncaglia** [comment]
@bmeldal 
MONDO:0013343 C1Q deficiency is now in EFO. It will be publicly visible when OLS picks up the next EFO release. (The release is scheduled for Dec 16, and the OLS update usually requires a day or so.)
