### ISSUE TITLE
NTR: MONDO:0013419 complement component C1s deficiency

### ISSUE THREAD

**Issue by bmeldal** [EBISPOT/efo#612]
For new term requests, please provide the following information:

Please pull in existing term MONDO:0013419. I have opened a ticket with MONDO to add a definition and fix the synonyms (https://github.com/monarch-initiative/mondo/issues/959)

## Preferred term label
Complement component C1s deficiency

## Synonyms
C1SD [EXACT]
C1s deficiency [EXACT]

## Textual definition

A rare defect resulting in C1 deficiency and impaired activation of the complement classical pathway. C1 deficiency generally leads to severe immune complex disease with features of systemic lupus erythematosus and glomerulonephritis. 

PMID:11390518

(Taken from UniProt entry P09871 as there isn't a def on this entry.)

## Suggested parent term
is_a EFO > MONDO:0000015 'classic complement early component deficiency'

## Attribution
ORCID id:0000-0003-4062-6158

Thanks,
Birgit

Note to self: Complex C1, EBI-6269273/CPX-1920

**Comment by paolaroncaglia** [comment]
@bmeldal 
See https://github.com/EBISPOT/efo/issues/611#issuecomment-553988327 for general comments and timeline (in this case, Mondo hasn't done your suggested edits yet, but I tentatively assigned https://github.com/monarch-initiative/mondo/issues/959 to their December milestone).
I'll comment on this EFO ticket when it's done.

**Comment by paolaroncaglia** [comment]
Note for self (cc @bmeldal ):
Mondo released yesterday, so I'll check if all's well with MONDO:0013419 complement component C1s deficiency and will then import it into EFO, before our next release (Dec 16).

**Comment by paolaroncaglia** [comment]
@bmeldal
MONDO:0013419 complement component C1s deficiency is now in EFO. It will be publicly visible when OLS picks up the next EFO release. (The release is scheduled for Dec 16, and the OLS update usually requires a day or so.)
