### ISSUE TITLE
Open Targets: Psychiatric disease TA

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#626]
Please can Psychiatric Disorder TA for OT be changed to Psychiatric Disease TA in the OT slim?

**Comment by zoependlington** [comment]
@smnorthen Of course. I'll get this done this afternoon and update the release files.

**Comment by zoependlington** [comment]
Sorry for the delay! All updated here: https://github.com/EBISPOT/efo/releases/tag/v3.12.0
