### ISSUE TITLE
Discuss coffee consumption vs. coffee consumption measurement

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#63]
Interested to discuss the difference between these terms, "coffee consumption" vs. "coffee consumption measurement". While going through the Ensembl REST API course the term "coffee consumption" is used as an example for the Phenotype annotations endpoints [1]. Are both of these terms needed? Is data in GWAS annotated consistently between these two terms?

[1] http://rest.ensembl.org/

**Comment by simonjupp** [comment]
Both terms are not needed, but we need discussion with GWAS team about plans for measurement
