### ISSUE TITLE
No EFO ids

### ISSUE THREAD

**Issue by tutajm** [EBISPOT/efo#633]
We downloaded the EFO ontology in OBO format. However, we noticed that some terms, like 'process' or 'quality' do NOT have EFO ids assigned.

We would like you to ask to assign EFO ids to all terms that do not have them (for terms like 'process'  with ids that that do not follow the usual convention 'ONTOLOGY_ACRONYM:ONTOLOGY_ID'). Our ontology loader is now stuck with these terms and we are scratching our heads and we are still not sure what to do with these terms.

Thank you,
Marek Tutaj
Programmer/Analyst, tasked with loading EFO ontology in OBO format

**Comment by zoependlington** [comment]
Thanks for letting us know @tutajm. I will look into a solution to this problem and hopefully will have a rectified version ready for our next release (16th December).

**Comment by helenp** [comment]
Some history here @zoependlington -  these terms flagged by this user are imports from BFO and they don't therefore have an EFO id and this was by design - see MIREOT paper. I suspect this is happening as the id format for the BFO terms isn't a proper id and so the parsing of this fails. If we took this to a logical conclusion we'd have to re-identify all imported terms with an EFO id and that's not desirable.

**Comment by zoependlington** [comment]
@helenp Thank you for the background. @matentzn and I have looked into it and the solution looks like it may be updating BFO (where the URI for "quality" was http://www.ifomis.org/bfo/1.1/snap#Quality) to BFO2 (where the URI for "quality" is now http://purl.obolibrary.org/obo/BFO_0000019). As we are gradually updating all of our current imports in EFO, this was on the to do list anyway and can just be brought forward. Right now there are 9 terms that are causing the above problems in the OBO file as far as Nico and I can see. I will try and update these terms to the new URIs from BFO2 and obsolete the old URIs in a test branch and see if this rectifies the problem in the efo.obo file.

**Comment by helenp** [comment]
Thanks @zoependlington for the plan.

**Comment by zoependlington** [comment]
@tutajm I have converted the old BFO IDs to the new BFO2 IDs which has rectified the problem. They are now as follows:

```
http://www.ifomis.org/bfo/1.1/snap#Disposition --> http://purl.obolibrary.org/obo/BFO_0000016
http://www.ifomis.org/bfo/1.1/snap#Function --> http://purl.obolibrary.org/obo/BFO_0000034
http://www.ifomis.org/bfo/1.1/snap#MaterialEntity --> http://purl.obolibrary.org/obo/BFO_0000040
http://www.ifomis.org/bfo/1.1/span#ProcessualEntity --> http://purl.obolibrary.org/obo/BFO_0000015
http://www.ifomis.org/bfo/1.1/snap#Quality --> http://purl.obolibrary.org/obo/BFO_0000019
http://www.ifomis.org/bfo/1.1/snap#Role --> http://purl.obolibrary.org/obo/BFO_0000023
http://www.ifomis.org/bfo/1.1/snap#Site --> http://purl.obolibrary.org/obo/BFO_0000029
http://www.ifomis.org/bfo/1.1/snap#SpecificallyDependentContinuant --> http://purl.obolibrary.org/obo/BFO_0000020
```

This will be available in our 16th December release.

**Comment by tutajm** [comment]
Thank you very much for taking care of it so promptly!

Best regards,
Marek
