### ISSUE TITLE
Fresh OBI import

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#638]
Required by HCA, the OBI import needs to also be made a dynamic import rather than static.

**Comment by paolaroncaglia** [comment]
Also see https://github.com/EBISPOT/efo/issues/501 (may want to link this ticket to that Epic?).

**Comment by paolaroncaglia** [comment]
Hi @zoependlington ,
Now that we are reviewing HCA requests, I took the liberty to bump this one from Backlog to Next, and assign it to both of us. Perhaps we could discuss it at our meeting next week, I'll make a note. Thanks!

**Comment by zoependlington** [comment]
This needs looking into further due to a few obsolete terms that need replacing (e.g. OBI 'realizes') in order for this to pass the QC checks.
