### ISSUE TITLE
Review placement of EFO MONDO:0002436 nose disease and children

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#639]
Due to the obsoletion of its parent 'sensory system disease', EFO MONDO:0002436 'nose disease' is now sitting under 'other' in the Open Targets therapeutic areas EFO slim/profile, which is undesirable. Before the next EFO release (hence the 'high priority'), we need to fix this. Quick considerations:
- [x] See if children of 'nose disease' have, or can be given, other parents
- [ ] If necessary, evaluate if we really need 'nose disease' at all. I suspect it was imported for the UK Biobank mappings.

**Comment by smnorthen** [comment]
@paolaroncaglia
I am not keen on 'nose disease' as it is very broad and could refer to the nasal mucosa, the nasal septum, the nasal sinuses etc. I would be happy to make it obsolete if it's not needed

**Comment by paolaroncaglia** [comment]
Notes for self:
I checked our masterfile of mappings for the UK Biobank work and couldn't find 'nose disease', so we did not import it because of that.
The term in EFO doesn't have any annotation that isn't already in Mondo, i.e. we didn't add any mapping etc. to it.
I searched the EFO issue tracker with "MONDO:0002436" and "nose disease" and couldn't find mention of us explicitly wanting to import it (though that search can only provide indications as the term may be hidden e.g. in a spreadsheet linked to a ticket).
So it's likely that none of our users asked for/need the term itself, and it may have gotten into EFO to place one or more of its children more easily ('paranasal sinus disease' sounds familiar from the UKB work).
I'll look at the children more carefully and evaluate our options, from less to more drastic:
- [ ] remove term from OT TA profile
- [ ] obsolete term in EFO
- [ ] ask Mondo to obsolete term.

**Comment by paolaroncaglia** [comment]
EFO MONDO:0002436 'nose disease' has 3 children, and they all have additional parents that would make the first and second option above easily feasible. The term is a descendant of 'head and neck disorder', which is present in EFO and Mondo; that branch has already been raised as problematic (see https://github.com/monarch-initiative/mondo/issues/525). So while that conversation continues, I suggest to go for the simplest solution for now and only remove 'nose disease' from the OT TA profile.
@smnorthen 
@zoependlington 
Any objection please?

**Comment by d0choa** [comment]
Sounds good in our side.

**Comment by zoependlington** [comment]
@paolaroncaglia MONDO:0002436 isn't in our list of terms (mondo_terms.txt), so it must be pulled in due to child terms. We can add it to the mondo_blacklist.txt file to remove it.

**Comment by paolaroncaglia** [comment]
Agreed with @zoependlington that she'll take care of the rest. Thanks!

**Comment by zoependlington** [comment]
@paolaroncaglia  Nose disease has been removed from the slim. See here: https://github.com/EBISPOT/otar_profiler

**Comment by paolaroncaglia** [comment]
Update on 'nose disease': FYI, Mondo is considering its obsoletion, see https://github.com/monarch-initiative/mondo/issues/525#issuecomment-560386922.
