### ISSUE TITLE
New assay terms into EFO

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/efo#64]
This ticket is for a review and addition of new assay terms collected from the literature and from EBI archive databases. I have the full list of terms. 

These need to be cross-checked against what we already have in EFO and cross-referenced to OBI where possible. We can use the Webulous Assay template to import the rest.

**Comment by siiraa** [comment]
@simonjupp can you upload the list here please?

**Comment by simonjupp** [comment]
Tasks

1. Move spreadsheet to a google sheet
2. Identify terms already in EFO
3. Markup rest as either assay or protocol

**Comment by paolaroncaglia** [comment]
Simon also noted that we'll need to consult with ArrayExpress if we need to do major changes.

**Comment by daniwelter** [comment]
Links to Google docs:
Spreadsheet: https://docs.google.com/spreadsheets/d/1msTWt6jri0wAj__AOKZ47h7_84dqnyB0I8DrKUi4rfA/edit#gid=1707009639
I've started to identify any assays that are already in EFO
Design patterns doc:
https://docs.google.com/document/d/1zW_Zhm2Npy4hZIqoXas6cz-dtnMAk3KYg8qKkaOPcSk/edit
This is the start of a brain dump on my part, give me a couple of days to flesh it out.

**Comment by paolaroncaglia** [comment]
@daniwelter 
Thanks for the links. I took a look and added a comment. I know you're away today, so let's re-adjourn when you are back and perhaps we could have a quick chat about the strategy (before or after the holidays as you prefer).

**Comment by siiraa** [comment]
are you guys watching some of the terms requested at OBI? - https://github.com/obi-ontology/obi/issues

**Comment by siiraa** [comment]
https://www.nature.com/articles/nmeth.4558

I think the spreadsheet they gave us is cross linked to the “enseqlopedia" http://enseqlopedia.com/enseqlopedia/

We want to have this and EFO in sync. 

Cheers
Simon

**Comment by paolaroncaglia** [comment]
Update FYI: @daniwelter and I are working on the spreadsheet https://docs.google.com/spreadsheets/d/1msTWt6jri0wAj__AOKZ47h7_84dqnyB0I8DrKUi4rfA/edit#gid=1102729345
We added two tabs, and are looking for and adding information where missing. I'll resume that task next week. We aim for the mid-March EFO release.

**Comment by paolaroncaglia** [comment]
Quick update/summary following discussion at weekly meeting:
If assays are already in EFO, no action required.
If they aren’t, add them in EFO with just a basic classification and description (don’t do a deep curation). Add them via Webulous, in fact this could be a nice use case for having a ROBOT template. 
Also Dani might do a quick pass with those assay types in ZOOMA to see if they are in OBI or not. Could also contact OBI to ask them for accessions and give them some time (a month?) to provide them.
Dani notes that it’s hard to come up with a comprehensive design pattern for assay types, so she might have one last quick look at the Google document and then close it.

**Comment by paolaroncaglia** [comment]
Quick update.
Kevin Maxkwee updated the spreadsheet to their version, by adding 62 assay types in the first tab of the spreadsheet here https://docs.google.com/spreadsheets/d/1msTWt6jri0wAj__AOKZ47h7_84dqnyB0I8DrKUi4rfA/edit#gid=1707009639. So there are 447 entries now. However the new entries only contain information on publications, so we asked Kevin to supply additional info (mainly DNA vs RNA, and assay category). We think that it’s worth waiting to hear back from Kevin before pushing the terms into EFO, as retrieving the needed info manually would take quite a bit of time. This means that we’d now aim for the April EFO release. In the meantime, we completed filling in the ‘DNA vs RNA’ fields where possible (second tab, towards the bottom, column ’Substrate’). Zoe looked at a few entries too. The rows marked in yellow are all the ones that we looked at.

**Comment by paolaroncaglia** [comment]
The plan is to re-adjourn when we hear back from Kevin, assess if we have enough info or not, strategize missing work if any, then Dani will push using ROBOT.

**Comment by daniwelter** [comment]
Needed for HCA: in-vitro transcription (child of nucleic acid library library construction)
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5449089/

**Comment by daniwelter** [comment]
About 350 terms imported for the April release of EFO (2.95), about 75 terms still outstanding due to missing information
