### ISSUE TITLE
Add new publication status term: preprint

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#643]
For new term requests, please provide the following information:

## Preferred term label

preprint

## Synonyms

pre-print

## Textual definition

In academic publishing, a preprint is a version of a scholarly or scientific paper that precedes formal peer review and publication in a peer-reviewed scholarly or scientific journal.
(from Wikipedia)

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0001742
(publication status)

## Attribution

0000-0002-8674-0039

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] dbxref: Wikipedia:Preprint
- [ ] creator: http://orcid.org/0000-0002-8674-0039

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
The new term EFO:0010558 'preprint' has been added, and will be visible in the mid-February EFO release. Thank you.
