### ISSUE TITLE
Broken IRI: MONDO:0018906

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#647]
[MONDO:0018906](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2Fhttp%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018906) has a broken IRI.

**Comment by zoependlington** [comment]
Broken IRI from incorrect import: http://www.ebi.ac.uk/efo/http://purl.obolibrary.org/obo/MONDO_0018906
Given EFO ID (http://www.ebi.ac.uk/efo/EFO_0010338), obsoleted, and replaced by http://purl.obolibrary.org/obo/MONDO_0018906
