### ISSUE TITLE
UniProtKB_Swiss-Prot Release 2019_11 OMIM to EFO mappings

### ISSUE THREAD

**Issue by Yvonne-Lussi** [EBISPOT/efo#650]
Dear all,

We have new a new release with OMIM terms that I have mapped to EFO. In cyan are the new term requests, and ones not highlighted are OMIM IDs that can be mapped to existing EFO terms or MONDO/Orphanet terms that we'd like to see added to EFO. The link is below. Please be aware that this is my first time mapping OMIM IDs to EFO terms, so hopefully the mapping is fine.

https://docs.google.com/spreadsheets/d/1DoSxyY3b20Y8_X2wSER1B8_7oiJ7vdgvbJGRJq7tXvs/edit?usp=sharing

Please let me know of you require further information.
Thank you in advance,
Yvonne Lussi

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
Thanks. I'll address this ticket after our EFO December release, and will let you know if I have any comment or question.
Paola

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
I'm reviewing your spreadsheet of new term requests and suggested mappings for OMIM terms in EFO (https://docs.google.com/spreadsheets/d/1DoSxyY3b20Y8_X2wSER1B8_7oiJ7vdgvbJGRJq7tXvs/edit#gid=0). Thank you for your helpful input. I added a few columns to the right of the spreadsheet for my own convenience. There are a few cases where I suggest a different course of action, and I've added a brief explanation in column I in case it's helpful. If you have any concern, please let me know. Only a few OMIM terms left to examine; I'll aim to commit everything to EFO in time for our mid-February release. Thank you.
Paola

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] When this is completed, ask Mondo if they'd like to add some of the manually curated mappings at the source too.

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
I'm working on the OMIM mappings you requested, and I noticed you highlighted in orange some of my notes in the spreadsheet https://docs.google.com/spreadsheets/d/1DoSxyY3b20Y8_X2wSER1B8_7oiJ7vdgvbJGRJq7tXvs/edit#gid=0. Please let me know if you have any concern with my suggestions, or if I can go ahead and make those edits. Thanks.

**Comment by Yvonne-Lussi** [comment]
Hi Paola
Sorry about that. I have highlighted them because it is not clear to me from your comment which would the parent EFO terms be for those OMIM diseases I have highlighted. Could you tell me which one you were thinking of?
Best,
Yvonne

**Comment by paolaroncaglia** [comment]
Hi Yvonne,
No problem at all. I have expanded on my note in line 14 of the spreadsheet to make it clearer; the other 3 cases are analogous. Please let me know if that's helpful. Thank you,
Paola

**Comment by Yvonne-Lussi** [comment]
Ok, I see, thank you very much for your explanation, I am fine with those edits. Thank you also very much for your previous feedback for the other mappings, I appreciate your help. I will now work on the OMIM Diseases from SwissProt Release 2020_01 and will let you know once I have finished. I hope I make some progress in the next mapping:-)
Thank you and best regards,
Yvonne

**Comment by paolaroncaglia** [comment]
Thanks Yvonne, happy to help, and your input is much appreciated. I'll comment here when all the OMIM mappings are in EFO. Speak soon, bye.

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
All the requested OMIM mappings are now in EFO; IDs of new EFO terms are in the spreadsheet if needed. All edits will be visible in the mid-Feb EFO release. Thank you.
