### ISSUE TITLE
Inaccurate "King-Denborough syndrome" xref to "CARDIOMYOPATHY, FAMILIAL HYPERTROPHIC, 12; CMH12"

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#656]
While troubleshooting an issue in Open Targets data, I have noticed that the [OLS API](https://www.ebi.ac.uk/ols/api/ontologies/efo/terms/http%253A%252F%252Fwww.orpha.net%252FORDO%252FOrphanet_99741) cross-references "CARDIOMYOPATHY, FAMILIAL HYPERTROPHIC, 12; CMH12" ([OMIM:612124](https://www.omim.org/entry/612124)) for "King-Denborough syndrome" ([Orphanet_99741](http://www.orpha.net/ORDO/Orphanet_99741)), which seems to be incorrect as they seem to be different things even though both are myopathies . It seems that either "familial hypertrophic cardiomyopathy" ([MONDO_0024573](http://purl.obolibrary.org/obo/MONDO_0024573)) or "Rare familial disorder with hypertrophic cardiomyopathy" ([Orphanet_99739]( http://www.orpha.net/ORDO/Orphanet_99739)) would be better xrefs and they are both in EFO.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
Thanks for reporting this. I looked into it and agree with your suggestions. I will
- [ ] Remove the dbxref OMIM:612124 from "King-Denborough syndrome" (Orphanet_99741)
- [ ] Map OMIM:612124 to "familial hypertrophic cardiomyopathy" (MONDO_0024573) instead.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
All done, will be visible in the mid-Feb EFO release. Thanks.

**Comment by AsierGonzalez** [comment]
Thank you @paolaroncaglia, much appreciated.
