### ISSUE TITLE
New term request: Abnormal bowel sounds

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#659]
New term request of Abnormal bowel sounds
Needed for Open Targets PheWas mapping.

**Comment by paolaroncaglia** [comment]
Update on Open Targets PheWas mapping tickets (this one plus 4 more with same labels):
@zoependlington and I met with @smnorthen today. These 5 tickets are part of a larger effort. Sandra will group requests based on what needs done (import from HP/Mondo or create EFO classes) in a spreadhseet and will submit that as a ticket probably in early March. We'll make that ticket an Epic and we can then close the tickets above/link to the Epic.
