### ISSUE TITLE
New term request: Aphakia

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#662]
New term request of Aphakia.
This currently only exists as a congential condition in EFO.
Required for GWAS mapping.

**Comment by smnorthen** [comment]
@paolaroncaglia  - sorry, this is for the PheWAS mapping, not GWAS. Please can you remove the GWAS flag? Sorry!

**Comment by paolaroncaglia** [comment]
@smnorthen done, no problem at all.

**Comment by paolaroncaglia** [comment]
@smnorthen done, no problem at all.
