### ISSUE TITLE
Double-check a few more tasks left for Open Targets Therapeutic Areas

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#667]
A quick note for self:
- [x] I need to double-check if anything is left to do for the red and orange rows here (children of heart disease only):

https://docs.google.com/spreadsheets/d/1Q6YFHVx5YIEbuhyCqxbg75irgaTc_keHDQ52BHDTncA/edit#gid=624809743

**Comment by paolaroncaglia** [comment]
@smnorthen @d0choa (cc @zoependlington )
Hi, I'm wrapping up some pending tasks from the therapeutics area work, and I have a question about 'pericardium disease' please. Do I remember correctly that you wished it placed under 'heart disease' in the OT TA profile? Currently, it's a child of 'thoracic disease' in the profile, and a child of both 'thoracic disease' and 'cardiovascular disease' in EFO3 (screenshot attached). I'm fine with the current solution, but double-checking because if you'd like 'pericardium disease' to be in the 'heart disease' TA instead (or additionally), @zoependlington will need to force that parentage, and I will need to discuss with Mondo if they're willing to change the disease location axiom for their 'heart disease' term from 'heart' to UBERON:0015410 'heart plus pericardium'. Thanks.
![Screen Shot 2020-02-19 at 12 02 13](https://user-images.githubusercontent.com/4982516/74829400-40818180-5311-11ea-86b0-f69b0470d758.png)
![Screen Shot 2020-02-19 at 12 01 38](https://user-images.githubusercontent.com/4982516/74829403-41b2ae80-5311-11ea-8a27-7d3911054021.png)

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] Look into potential duplication (and correct placement) of 'coronary artery disease' and 'coronary heart disease'; note that Mondo has only the former (but mapped to the latter), and that according to Mondo as well as Wikipedia (https://en.wikipedia.org/wiki/Coronary_artery_disease), the wordings are synonymous.

**Comment by paolaroncaglia** [comment]
@zoependlington , no hurry, but could you please
- [ ] Edit MONDO:0018797 'genetic cardiac malformation' in the OT TA slim/profile to add the extra parent 'genetic, familial or congenital disease'. Thanks.

**Comment by paolaroncaglia** [comment]
EFO:0005297 Granulomatosis with Polyangiitis needs work. It's a form of vasculitis (see e.g. https://en.wikipedia.org/wiki/Granulomatosis_with_polyangiitis), but in EFO and Mondo it has several incorrect parents derived from ORDO. 
- [ ] In EFO, delete all parents except for 'autoimmune disease' (based on def) and 'vasculitis'; delete all disease location axioms;
- [ ] Ask Mondo to revise all their parents (may need to bring in an expert to say if the more specific parents related to immune system and vasculitis are appropriate?).

**Comment by paolaroncaglia** [comment]
Note for self: revision of orange and red rows in https://docs.google.com/spreadsheets/d/1Q6YFHVx5YIEbuhyCqxbg75irgaTc_keHDQ52BHDTncA/edit#gid=624809743 to be continued from row 22 included.

**Comment by smnorthen** [comment]
@paolaroncaglia
Thank you for all your help with this. Yes, ideally pericardium would go with 'cardiac disease' and not 'thoracic disease' if that's possible. I just think it makes clinically more sense.

**Comment by paolaroncaglia** [comment]
@zoependlington 
No hurry, but in the OT TA slim/profile, could you please
- [ ] Edit/force the parentage of 'pericardium disease' so it's no longer a subclass of 'thoracic disease' but of 'heart disease' instead, as per Sandra's request above. Thanks.

**Comment by paolaroncaglia** [comment]
@smnorthen 
I opened a ticket with Mondo about the pericardium disease location issue. It may take a while for them to discuss and resolve, but we'll bring it up in our next discusson with them. Then the action item is for me to 
- [ ] Keep an eye on Mondo's resolution (https://github.com/monarch-initiative/mondo/issues/1189) and edit EFO (and the slim/profile) as/if necessary.

**Comment by zoependlington** [comment]
@paolaroncaglia Sure thing, Paola! I've assigned myself so I don't lose this.

**Comment by zoependlington** [comment]
@paolaroncaglia edits are now made in the profile/slim.

**Comment by zoependlington** [comment]
@paolaroncaglia 'genetic cardiac malformation' is now a child of 'genetic, familial or congenital disease' as well

**Comment by paolaroncaglia** [comment]
Note for self: EFO:0009012 Polyarteritis nodosa needs work:
- [ ] Remove location axioms for PNS, skin, heart and kidney
- [ ] Check corresponding Mondo term

**Comment by paolaroncaglia** [comment]
@smnorthen 
May I please ask for your feedback on EFO:1001416 'Rheumatic Nodule'.
It is currently defined as "A small round or oval, mostly subcutaneous nodule made up chiefly of a mass of Aschoff bodies and seen in cases of rheumatic fever. It is differentiated from the RHEUMATOID NODULE which appears in rheumatoid arthritis, most frequently over bony prominences. (From Dorland, 27th ed)", and is a subclass of 'heart disease'. We already touched upon it (me: "Modify definition to make it clearer that it's a heart disease; refer to https://en.wikipedia.org/wiki/Aschoff_body. Open EFO ticket."; you: "it may be worth updating the term to: Rheumatic fever nodule or similar, so it is not confused with Rheumatoid nodules (which I thought it meant at a first glance)"). Looking into this again, my thoughts are:
- [ ] Yes, modify label to 'rheumatic fever nodule' for disambiguation;
- [ ] The definition points to subcutaneous nodules, but also refers to Aschoff bodies, which I understand are found in heart. If we went by the broader part of the definition, we should place this term not under 'heart disease' but rather 'sign or symptom' or in the phenotype branch. Opinions? Mondo doesn't have the term (unsurprisingly); NCIT has it in the 'Finding' branch.

Thanks.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Another term for your review please. EFO:1001442 'Tuberculosis, Cardiovascular': "Pathological conditions of the CARDIOVASCULAR SYSTEM caused by infection of MYCOBACTERIUM TUBERCULOSIS. Tuberculosis involvement may include the HEART; the BLOOD VESSELS; or the PERICARDIUM.". Previous notes: me: "Based on its def, this should be a child of both heart and vascular TAs?"; you: "Agree". However, at a quick glance, most publications/links refer to heart rather than broader cardiovascular system; the corresponding Mondo term is 'cardiac tuberculosis' and subclass of 'heart disease' (plus others). I'm wondering what the most correct definition is. The correct disease location axiom will depend on that - as things are now, I'm a bit reluctant to add a vascular parent in OT/leave the cardiovascular location axiom in EFO.
Thanks.

**Comment by paolaroncaglia** [comment]
Note for self - all issues noted in the spreadsheet are now ticketed.

**Comment by smnorthen** [comment]
@paolaroncaglia 
Thank you for updating the label to make it clearer. It may be worth adding 'Rheumatic Aschoff Nodule' as it's sometimes referred to (see https://www.ncbi.nlm.nih.gov/pubmed/8575737) as a synonym too.  And yes, I am fine with adding it to the phenotype signs/symptoms hierarchy as long as it's consistent with other placements.

**Comment by smnorthen** [comment]
@paolaroncaglia
Re: EFO:1001442 'Tuberculosis, Cardiovascular'

Would it be possible to update the term label to 'Cardiac Tuberculosis' (as it's the most likely scenario) or import the corresponding Mondo term into EFO instead? I understand that the majority of publications are mainly focusing on heart-related TB and that you would want to link it to 'heart disease' only in EFO. I think this would be cleaner than linking 'cardiovascular tuberculosis' to just heart disease.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Many thanks for your prompt feedback, I'll implement the changes in time for the next release. 
When you have a chance, please let me know if you have any objection to my other proposal here 
https://github.com/ebispot/efo/issues/667#issuecomment-588172575
I tagged you, but I was editing a previous comment so you probably did not get any notification. Thanks.

**Comment by smnorthen** [comment]
@paolaroncaglia
Re: 'coronary artery disease' 

Thank you for your thorough explanation. I agree that 'coronary heart disease' and 'coronary artery disease' are synonymous.  Merging both into 'coronary artery disease', would also be my preference out of the two. thanks!

**Comment by paolaroncaglia** [comment]
Note for self/EFO editor: 
- [ ] Tasks left to do for this ticket are listed in https://github.com/EBISPOT/efo/issues/667#issuecomment-588172575.

**Comment by zoependlington** [comment]
EFO_0000378 (coronary artery disease) has been merged into EFO_0001645 (renamed to coronary artery disease from coronary heart disease), children have been cleaned.
