### ISSUE TITLE
arthrogryposis OMIM xrefs

### ISSUE THREAD

**Issue by cmungall** [EBISPOT/efo#67]
https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0003857

![image](https://user-images.githubusercontent.com/50745/34449820-a4f13a84-ecb1-11e7-933e-ead5829f07ea.png)

This xrefs a dubious and largely unrelated OMIM entry: https://omim.org/entry/205000 - I think this xref is wrong

**Comment by cmungall** [comment]
Parent ticket: https://github.com/monarch-initiative/mondo-build/issues/51

**Comment by siiraa** [comment]
fixed.
