### ISSUE TITLE
Add synonym to EFO:0003971

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#677]
Hello, the ENCODE Project would to request a synonym to be added to the EFO term, EFO:0003971 (MEL cell line). 

Could "MEL" be added as synonym? Currently, EFO:0003971 is classified as a cell line, so having "MEL cell line" causes some redundancy. 

Thank you!

**Comment by paolaroncaglia** [comment]
@bonitalam 
Sure, we'll add the requested synonym in time for the mid-February EFO release. Thank you.

**Comment by paolaroncaglia** [comment]
@bonitalam 
I confirm that the requested synonym for EFO:0003971 (MEL cell line) is now in EFO and will be visible after our next release, scheduled for Feb. 17th.

**Comment by bonitalam** [comment]
Great, thank you very much @paolaroncaglia!
