### ISSUE TITLE
Add Term: Blastic Plasmacytoid Dendritic Cell Neoplasm

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#678]
I couldn't find an equivalent in EFO

## Preferred term label
Blastic Plasmacytoid Dendritic Cell Neoplasm

## Synonyms
Blastic NK-Cell Lymphoma, BPDCN, Agranular CD4+ Natural Killer Cell Leukemia, Blastic Natural Killer Leukemia/Lymphoma, Agranular CD4+ CD56+ Hematodermic Neoplasm/Tumor, Monomorphic NK-Cell Lymphoma, CD4+/CD56+ Hematodermic Neoplasm, Blastic Plasmacytoid Dendritic Cell Neoplasm

## Textual definition
NCI definition

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)
## X-refs
http://purl.obolibrary.org/obo/NCIT_C7203

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] Add EFO:NEW blastic plasmacytoid dendritic cell neoplasm
subclass of EFO > MONDO:0044881 'hematopoietic and lymphoid cell neoplasm'
"A clinically aggressive neoplasm derived from the precursors of plasmacytoid dendritic cells (also called professional type I interferon-producing cells or plasmacytoid monocytes), with a high frequency of cutaneous and bone marrow involvement and leukemic dissemination. (WHO 2017) [ NCI ]"
dbxref: NCIT:C7203
Synonyms: Blastic NK-Cell Lymphoma, BPDCN, Agranular CD4+ Natural Killer Cell Leukemia, Blastic Natural Killer Leukemia/Lymphoma, Agranular CD4+ CD56+ Hematodermic Neoplasm/Tumor, Monomorphic NK-Cell Lymphoma, CD4+/CD56+ Hematodermic Neoplasm

**Comment by paolaroncaglia** [comment]
@gkos-bio 
EFO:0010580 blastic plasmacytoid dendritic cell neoplasm
will be visible in the Feb 17th EFO release. Thanks.
