### ISSUE TITLE
Add term: ALECT2 amyloidosis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#680]
For new term requests, please provide the following information:

## Preferred term label
ALECT2 amyloidosis

## Synonyms
LECT2 amyloidosis

(e.g., Absent spleen)

## Textual definition
See definition of http://www.orpha.net/ORDO/Orphanet_439224

## Suggested parent term
amyloidosis

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Import MONDO:0018588 ALECT2 amyloidosis
- [ ] Add synonym LECT2 amyloidosis
- [ ] Add def "A rare, systemic amyloidosis characterized by slowly progressive renal disease presenting with proteinuria, hypertension and decreased glomerular filtration rate leading to progressive renal failure. Histology reveals amyloid deposits of leukocyte chemotactic factor-2 protein in the renal cortical interstitium, tubular basement membranes, glomeruli and the vessel walls. Extra-renal deposits can be seen in the liver, lungs, spleen and adrenal glands."

**Comment by paolaroncaglia** [comment]
@gkos-bio 
MONDO:0018588 'ALECT2 amyloidosis' is now in EFO and will be visible in EFO's Feb 17th release.
I asked Mondo to add definition and synonym as you suggested, at the source, so those should be in EFO's mid-March release. Thanks.
