### ISSUE TITLE
Self-cross-references relationships in EFO ontology

### ISSUE THREAD

**Issue by Elysheba** [EBISPOT/efo#684]
Hi,

while using the EFO ontology, I noticed that there are some EFO identifiers, as well as MONDO and Orphanet identifiers that were incorporated, that refer back to another EFO identifier. So these are a sort of self-cross-reference that is established this way within EFO to nodes of a different level. Is this something to expect and how should these therm then be interpreted?

I have aggregated a list below with the examples I could identify (I only checked EFO/MONDO/Orphanet identifiers within the EFO ontology and whether they have an EFO cross-reference, the inverse is more difficult to ascertain). Based on the online OLS interface, some are obtained through MONDO ontology and it's cross-references. 

Many thanks,
Liesbeth

[efo_self_crossref.txt](https://github.com/EBISPOT/efo/files/4108879/efo_self_crossref.txt)

**Comment by paolaroncaglia** [comment]
Hi @Elysheba ,

Thanks for your message. I had a quick look at the first pair in your file, i.e.
"DB1"	"id1"	"DB2"	"id2"
"MONDO"	"0024306"	"EFO"	"1000036"
As you guessed, that's a Mondo term ('acquired lactid acidosis') that EFO imported and that already came with an EFO xref (to EFO 'lactic acidosis'). I interpret it as a broad mapping in Mondo - possibly, at the time when Mondo was built, it didn't have a broad term for 'lactic acidosis'. But now it has one (MONDO:0006040), and that doesn't have an EFO xref. My quick thoughts are that we should
- [ ] Check a few more cases from your file
- [ ] Get in touch with Mondo to have them "update" their EFO xref(s) at the source
- [ ] Further action items, if necessary, based on the outcome of the first step above.

Thanks,

Paola

**Comment by dhimmel** [comment]
We recently noticed this on EFO Otar Slim v0.43.0, which presumably has the same xrefs as EFO. We found 5580 xrefs whose target was a term in EFO. We can further subdivide this into:

1. self-xrefs where the source and target node are the same (900 occurrences). See also https://github.com/EBISPOT/efo/issues/752. These are harmless but unnecessary & clutter.

2. xrefs to a different term in EFO (4680 occurrences). These are problematic because they contradict the ontology.

Here's a spreadsheet of all xrefs, but currently filtered for `xref_in_efo` (xref points to a term in EFO): [efo-otar-slim-xrefs.xlsx](https://github.com/EBISPOT/efo/files/9021624/efo-otar-slim-xrefs.xlsx).

Perhaps EFO could filter all xrefs that point to terms in the EFO release? That would be a good quick fix, but many of the "xrefs to a different term in EFO" seem to point to deeper inconsistencies between ontologies. CC @paolaroncaglia @zoependlington @matentzn

**Comment by matentzn** [comment]
@dhimmel 

I will leave @zoependlington to hash out a plan for this but may I say:

hasDbXref means _nothing_. I can add hasDbXref between all terms if I want to, its meaning may have once been "kinda the same", but now its "kinda related" and I would recommend _not_ to use it to map data for anything other than perhaps machine learning (which can handle the noise). The fact that that there are thousands of xrefs within EFO alone should ring an alarm bell..

That said, its a matter of 10 minutes to at a SPARQL update query to EFO to get rid of of these xrefs, @zoependlington can contact me if she wants me to add it to the release pipeline! :)

**Comment by dhimmel** [comment]
> hasDbXref means nothing

Hmm in practice it seems to mean that the predicate is the most equivalent term to the subject in the predicate's vocabulary.

How else does one convert external identifiers (like from MeSH, ICD10, etc) to EFO without hasDbXref? In https://github.com/EBISPOT/efo/issues/935 we discussed `mondo:exactMatch` and `skos:exactMatch`, but my understanding is that this is not widely implemented in EFO.

> That said, its a matter of 10 minutes to at a SPARQL update query to EFO to get rid of of these xrefs, @zoependlington can contact me if she wants me to add it to the release pipeline!

Nice!

**Comment by matentzn** [comment]
@dhimmel 

> How else does one convert external identifiers (like from MeSH, ICD10, etc) to EFO without hasDbXref?

Of course, I was just a bit ... direct :D 

If you want to get this to the mapping thing to the next level, can you share with me a list of prefixes you really _need_ for OTAR? like between what and what kind of terms do you _need_ mappings?

**Comment by zoependlington** [comment]
This should now be fixed so moving to done. All self-xrefs in [this spreadsheet](https://docs.google.com/spreadsheets/d/1P2DyV9B-mvcRCnwpm3OpOm3Jza9R1B9rzOB6ARco2ds/edit?usp=sharing) will be removed upon release.
