### ISSUE TITLE
Remove "lower grade glioma" synonym for "brain glioma" (MONDO_0005499)

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#685]
`Lower grade glioma` is one of the listed synonyms for `brain glioma` which does not seem to be correct given that `low grade glioma` (MONDO_0021637) is already in the ontology and seems to be more specific.

**Comment by paolaroncaglia** [comment]
Hi @AsierGonzalez ,
'brain glioma' (with synonym "lower grade glioma") and "low grade glioma" are both Mondo terms, hence the action item would be for them to remove the incorrect synonym. (In Protege I can further see that the synonym "lower grade glioma" comes from DOID, but in OLS this is not clear.). I'll open a ticket with them. When they fix the synonym and release a new version (which they do monthly) with the correction, EFO will automatically import the change and it will be visible ~2 weeks after the Mondo release.

**Comment by paolaroncaglia** [comment]
Hi again @AsierGonzalez ,
I opened https://github.com/monarch-initiative/mondo/issues/1115, so I'll move this EFO ticket to Done. Thanks.

**Comment by AsierGonzalez** [comment]
That sounds great, thanks @paolaroncaglia!
