### ISSUE TITLE
Requesting new term "Proteome"

### ISSUE THREAD

**Issue by AlexandraPhil** [EBISPOT/efo#686]
Hi, I would like to request a new term,

## Preferred term label

Proteome

## Synonyms

proteome, total expressed protein

## Textual definition

The actual total expressed protein complement of an organism or the identifiable proteins of a single tissue or cell type or subcellular compartment. 
(http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C18276)

## Suggested parent term

material entity (http://purl.obolibrary.org/obo/BFO_0000040)

Thanks,
Alexandra

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] Add 
EFO:NEW proteome
Subclass of 'material entity'
"The actual total expressed protein complement of an organism or the identifiable proteins of a single tissue or cell type or subcellular compartment."
dbxref: NCIT:C18276
Synonym: total expressed protein

**Comment by paolaroncaglia** [comment]
Hi @AlexandraPhil ,
Your requested new term EFO:0010579 'proteome' will be visible in the EFO release scheduled for Feb 17th. Thanks.
Paola

**Comment by AlexandraPhil** [comment]
Hi @paolaroncaglia ,

Thank you very much!

Alexandra
