### ISSUE TITLE
merge synonymous terms 'A1C measurement' and 'Glycosylated Hemoglobin Measurement'

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#689]
I think that these terms should be merged:

EFO_0004541 'A1C measurement'
EFO_0009207  'Glycosylated Hemoglobin Measurement'

‘HbA1c measurement’ would be a more appropriate name for the merged term, with ‘A1c measurement’ and ‘glycosylated hemoglobin measurement’ as synonyms. It would be accurate to give the merged term the parentage of both existing terms.

**Comment by paolaroncaglia** [comment]
Hi @mariacos (cc @twhetzel and @zoependlington ),

I agree with your suggestions above. The Wikipedia entry says "Glycated hemoglobin is preferred over glycosylated hemoglobin to reflect the correct (non-enyzmatic) process. Early literature often used glycosylated as it was unclear which process was involved until further research was performed. The terms are still sometimes used interchangeably in English language literature." (https://en.wikipedia.org/wiki/Glycated_hemoglobin) and I believe the final sentence is true in this case - EFO_0009207 cross-references NCIT Glycosylated Hemoglobin Measurement (Code C64849) which has a synonym "Glycated Hemoglobin" and refers to Hba1c. So I will
- [ ] Merge EFO_0009207 'Glycosylated Hemoglobin Measurement' into EFO_0004541 'A1C measurement' i.e. obsolete the former in favor of the latter, as that has the gwas trait = true annotation.

@zoependlington please let me know if you have any concern, as you created EFO_0009207.
@twhetzel if you think that GWAS would have any objection, please let me know.

@mariacos just curious - may I please ask if your requests (this ticket and 5 others) are for a specific project? 

Thanks, and best wishes,

Paola

**Comment by mariacos** [comment]
Hi Paola,

Thanks for working on these requests! In our Knowledge Portal resources (e.g. type2diabetesgenetics.org <http://type2diabetesgenetics.org/>) we aggregate and organize GWAS results. We’ve been using free text to express the associated phenotypes, but want to start at least mapping our terms to EFO, and ultimately will probably just use the EFO terms directly. Since you work with the GWAS Catalog, many of these terms already exist, but there are a few gaps so I’ll continue to make requests sporadically.

Best,
Maria


Maria C. Costanzo, Ph.D.
Creative Lead, MPG Portals
Broad Institute of MIT and Harvard
75 Ames St.
Cambridge, MA 02142
mariacos@broadinstitute.org
617-714-7922
type2diabetes.org
KP4CD.org

**Comment by twhetzel** [comment]
@paolaroncaglia no objections on the change.

**Comment by paolaroncaglia** [comment]
Hi @mariacos ,

> Hi Paola, Thanks for working on these requests! In our Knowledge Portal resources (e.g. type2diabetesgenetics.org <http://type2diabetesgenetics.org/>) we aggregate and organize GWAS results. We’ve been using free text to express the associated phenotypes, but want to start at least mapping our terms to EFO, and ultimately will probably just use the EFO terms directly. Since you work with the GWAS Catalog, many of these terms already exist, but there are a few gaps so I’ll continue to make requests sporadically. Best, Maria

Thanks for your reply, great to hear you'll be using EFO! 
I will continue to address your tickets and will comment on them when I have updates. (FYI, one of my colleagues, who's more in touch with the GWAS curators, is helping with some specific queries.) Thanks and best wishes, 

Paola

**Comment by paolaroncaglia** [comment]
Hi @mariacos ,
The changes above are now in EFO and will be available with the next release. Normally this would have been in mid-May, but we're running a patch release (possibly today) so the change will be available soon. (We send out an email to the efo-users mailing list every time we do a release; I assume you're a recipient, but if not, please let me know.)
Thanks,
Paola

**Comment by mariacos** [comment]
Hi Paola,

That’s great, thanks so much! I’m not on the email list but would like to be - where do I sign up?

Best,
Maria

**Comment by paolaroncaglia** [comment]
Hi @mariacos ,
Please see if you can access this link to subscribe to the efo-users mailing list:
https://listserver.ebi.ac.uk/mailman/listinfo/efo-users
If not, please email Efo-users@ebi.ac.uk and one of us will add you in.
The list is low-traffic :-)
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Note for self - Maria is now on the efo-users mailing list.
