### ISSUE TITLE
github repo for EFO

### ISSUE THREAD

**Issue by ckongEbi** [EBISPOT/efo#69]
Hi, 

We used in our pipeline: 
https://sourceforge.net/p/efo/code/HEAD/tree/trunk/src/efoinowl/InferredEFOOWLview/efo_inferred_all.owl?format=raw

and since move the github, should it now be:
https://raw.githubusercontent.com/EBISPOT/efo/master/efo_inferred_all.owl

also what is the key difference between: 
efo.owl 
efo_inferred.owl
efo_inferred_all.owl

Many thanks!
ck

**Comment by simonjupp** [comment]
efo.owl contains all the logical axioms and needs an OWL reasoner to compute the class hierarchy. 
efo_inferred.owl is the computed hierarchy but has the logical axioms removed. 
efo_inferred.owl is the computed hierarchy but keeps all the logical axioms.

**Comment by ckongEbi** [comment]
great thanks!
