### ISSUE TITLE
Add a new term, 'insulin secretion measurement’

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#690]
Add a new term, 'insulin secretion measurement’
definition: Measurement of compounds, generally C-peptide or mature insulin, whose levels quantify insulin secretion from the pancreas.

Note: I'm requesting this term because the similar existing term, EFO_0008001 'insulin secretion rate measurement', isn't an appropriate parent for measures of insulin secretion that don't generate a rate. Alternatively, perhaps EFO_0008001 could be edited to remove 'rate' from the name and definition.

**Comment by paolaroncaglia** [comment]
@twhetzel 
Please see request above. I'd be inclined to edit EFO_0008001 'insulin secretion rate measurement' to make it broader, but only if it hasn't been used in GWAS to refer specifically to the rate of secretion, rather than more generically to quantify secretion. If it's too complicated/time-consuming to verify, I'll create a new term instead (and make it a parent of EFO_0008001). Thanks!

**Comment by twhetzel** [comment]
I'll check out what data is annotated to this term and ping the curators about the proposed change to remove "rate" from the term name.

**Comment by paolaroncaglia** [comment]
Note for self:
Edit EFO_0008001 'insulin secretion rate measurement':
- [ ] Change label to 'insulin secretion measurement’
- [ ] Move 'insulin secretion rate measurement' to be a synonym
- [ ] Replace def with "Measurement of compounds, generally C-peptide or mature insulin, whose levels quantify insulin secretion from the pancreas."

@mariacos 
Please send me your ORCID and 
- [ ] I'll add it as a dbxref.

Thanks!

**Comment by mariacos** [comment]
Thanks Paola! My ORCID is 0000-0001-9043-693X.

Best,
Maria

**Comment by paolaroncaglia** [comment]
@mariacos 
EFO_0008001 'insulin secretion rate measurement' has now been edited as requested. Changes will be visible after the next EFO release, scheduled for April 15th. Thanks.
