### ISSUE TITLE
Additional parentage for EFO_0005187, 'C-peptide measurement'

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#691]
EFO_0005187, 'C-peptide measurement', should be a child of the new term, ‘insulin secretion measurement', that I requested in issue #690.

(Note that EFO_0008001 ' insulin secretion rate measurement' is not an appropriate parent, because C-peptide levels don’t indicate the *rate* of insulin secretion.)

**Comment by paolaroncaglia** [comment]
@mariacos 

> EFO_0005187, 'C-peptide measurement', should be a child of the new term, ‘insulin secretion measurement', that I requested in issue #690.
> (Note that EFO_0008001 ' insulin secretion rate measurement' is not an appropriate parent, because C-peptide levels don’t indicate the _rate_ of insulin secretion.)

This is now done and will be visible in the next EFO release, scheduled for Sept 15th. Thanks.
