### ISSUE TITLE
Add a new term, 'fasting C-peptide measurement'

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#692]
Add a new term, 'fasting C-peptide measurement', as a child of EFO_0005187, 'C-peptide measurement'

definition: A measurement of serum C-peptide levels at a predetermined point after a patient has fasted.

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Add with dbxref http://orcid.org/0000-0001-9043-693X

**Comment by paolaroncaglia** [comment]
@mariacos 

> Add a new term, 'fasting C-peptide measurement', as a child of EFO_0005187, 'C-peptide measurement'
> definition: A measurement of serum C-peptide levels at a predetermined point after a patient has fasted.

This is now added as EFO:0010813 'fasting C-peptide measurement' and will be in the next release. Thanks.
