### ISSUE TITLE
Add a new term, 'proinsulin measurement'

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#693]
Add a new term, 'proinsulin measurement'
child of EFO_0004467 'insulin measurement'
definition: Measurement of proinsulin, an insulin precursor that is processed into mature insulin and C-peptide.
reference: https://en.wikipedia.org/wiki/Proinsulin

**Comment by paolaroncaglia** [comment]
Note for self,
- [ ] Add dbxref http://orcid.org/0000-0001-9043-693X too.

**Comment by paolaroncaglia** [comment]
@mariacos 

> Add a new term, 'proinsulin measurement'
> child of EFO_0004467 'insulin measurement'
> definition: Measurement of proinsulin, an insulin precursor that is processed into mature insulin and C-peptide.
> reference: https://en.wikipedia.org/wiki/Proinsulin

The new term EFO:0010814 'proinsulin measurement' will be visible in the next release. Thanks.
