### ISSUE TITLE
Add a new term, 'remnant cholesterol measurement'

### ISSUE THREAD

**Issue by mariacos** [EBISPOT/efo#694]
Add a new term, 'remnant cholesterol measurement'
child of EFO_0004732 'lipoprotein measurement'
definition: Measurement of remnant cholesterol (remnant lipoprotein), which is an atherogenic lipoprotein composed primarily of very low-density lipoprotein (VLDL) and intermediate-density lipoprotein (IDL).
reference: https://en.wikipedia.org/wiki/Remnant_cholesterol

**Comment by paolaroncaglia** [comment]
Note for self, 
- [ ] Also add dbxref http://orcid.org/0000-0001-9043-693X.

**Comment by paolaroncaglia** [comment]
@mariacos 

> Add a new term, 'remnant cholesterol measurement'
> child of EFO_0004732 'lipoprotein measurement'
> definition: Measurement of remnant cholesterol (remnant lipoprotein), which is an atherogenic lipoprotein composed primarily of very low-density lipoprotein (VLDL) and intermediate-density lipoprotein (IDL).
> reference: https://en.wikipedia.org/wiki/Remnant_cholesterol

Lastly, EFO:0010815 'remnant cholesterol measurement' will be in the next release. Best wishes!
