### ISSUE TITLE
Acute and Chronic need to be reclassified

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#697]
http://purl.obolibrary.org/obo/HP_0011009
http://purl.obolibrary.org/obo/HP_0011010

Currently do not have an appropriate superclass in EFO, its connection "clinical modifier" in HP was severed (by HP editors). Please advice on where in the hierarchy you want them now @zoependlington

**Comment by matentzn** [comment]
(I reviewed diffs and all, I think this is all that needs fixing for the [PR](https://github.com/EBISPOT/efo/pull/698/files) to be merged

**Comment by paolaroncaglia** [comment]
@zoependlington 
@matentzn 
The easiest fix would be to create a new term in EFO namespace for 'clinical modifier' (subclass of 'quality') to be a parent for acute and chronic as well as the other current children of EFO HP 'clinical modifier'. An alternative may be to consider EFO 'disease characteristic' as a superclass for all current children of EFO HP 'clinical modifier'. (Mondo has a grouping term for 'disease characteristic' too, but their 'acute disease' is not classified under it.)

**Comment by matentzn** [comment]
You guys no best! No opinion/objection here.

**Comment by zoependlington** [comment]
I think both options are good... It would be nice to remain in alignment with Mondo as much as possible for sure and considering we do map the disease characteristic branch with Mondo, maybe we don't want to add the confusion of acute being directly under disease characteristic? Unless this might be a good discussion for our call?

**Comment by paolaroncaglia** [comment]
@zoependlington 
I suggest to go with the first option then. That will ensure we can fix quickly and will not affect current alignment. Let me know if you'd like me to do the edits.

**Comment by matentzn** [comment]
I think you are right Zoe. Maybe Option 1 is cleaner.

**Comment by zoependlington** [comment]
@paolaroncaglia Please feel free to go ahead if you're planning on editing today. If not, I can hopefully squeeze it in this afternoon.

**Comment by matentzn** [comment]
@zoependlington Better you do it on the branch - else there will be conflicts you will have to resolve :D

**Comment by matentzn** [comment]
(which may take you longer than making the term)

**Comment by paolaroncaglia** [comment]
@zoependlington I'll leave it to you then, thanks!

**Comment by zoependlington** [comment]
Ah! Yes, you're right. I'll do it this afternoon before my brain forgets. Thanks!

**Comment by zoependlington** [comment]
Added the new term in the branch, replacing http://purl.obolibrary.org/obo/HP_0012823 (which is obsoleted as per EFO policy):  http://www.ebi.ac.uk/efo/EFO_0010569

Other issues noted:
-  **Disease vs Phenotype.** Duplicate labels of EFO:0008575 and HP:0040188 (Osteochondrosis). The HP term used to be Osteochondritis. Do we want to obsolete the EFO disease term (It is currently mapped to MONDO:0018381)? Obsolete the HP term? Rename the EFO term?
- Missing term HP_0011007 (was age of onset) seems to have disappeared from HPO altogether. There is HP_0003674 (onset) which has the synonym of age of onset that we could replace this term with? MSH x-ref for HP_0011007 currently maintained through the pipeline.

**Comment by matentzn** [comment]
> Disease vs Phenotype. Duplicate labels of EFO:0008575 and HP:0040188 (Osteochondrosis). The HP term used to be Osteochondritis. Do we want to obsolete the EFO disease term (It is currently mapped to MONDO:0018381)? Obsolete the HP term? Rename the EFO term?

If they mean the same thing, then the EFO term should be obsoleted.

> Missing term HP_0011007 (was age of onset) seems to have disappeared from HPO altogether. There is HP_0003674 (onset) which has the synonym of age of onset that we could replace this term with? MSH x-ref for HP_0011007 currently maintained through the pipeline.

I would favour replacing with HP:0003674, but no strong opinion.

Agree to rest. :)

**Comment by zoependlington** [comment]
- [x] Obsoleted EFO:0008575 in branch, replaced by HP:0040188. Blacklisted MONDO:0018381.
- [x] Obsoleted HP_0011007 in branch, replaced by HP_0003674
- [x] Obsoleted HP_0000833 in branch, replaced by HP:0001952
