### ISSUE TITLE
Can't find ancient version v2.38

### ISSUE THREAD

**Issue by FuqiX** [EBISPOT/efo#705]
Hi,

I am looking into ontology provenance. Term, [obsolete_mammary gland](https://www.ebi.ac.uk/ols/ontologies/efo/terms?short_form=EFO_0000854), was deprecated in v2.38. I would like to see how this term related to other terms before the deprecation.

However, in the [release history](https://github.com/EBISPOT/efo/releases/tag/v2017-12-15), the oldest version available is v2.92.

Could you please point me to ealier version, v2.38 and v2.37? 

Thanks a lot!

**Comment by paolaroncaglia** [comment]
@simonjupp 
Could you please advise on retrieving old EFO versions pre-GitHub era? I guess one could use the suggestion in the "Download" section here https://www.ebi.ac.uk/efo/, but I don't know the release dates of versions v2.38 and v2.37.

@FuqiX 
In the meantime, if it's useful, EFO:0000854 'obsolete_mammary gland' was replaced by a Uberon term with the same label. In similar cases, where an EFO term is replaced by a corresponding one from a more specific/appropriate ontology, I suspect that the placement of the old term wasn't much different from the new one.

Thanks,
Paola

**Comment by FuqiX** [comment]
Hi, @paolaroncaglia 

Thanks for your prompt reply. 

BioSamples use ontology term hierarchy in the search. It's possible that deprecating ontology term will affect the search result in BioSamples. I was curious about how deprecation affects our search results, so that we can better tune the BSD search function.

I understand it can be difficult to track versions before using GitHub. If v2.38 is not available, I can try other approaches to look into this.

Best,
Fuqi

**Comment by helenp** [comment]
Hi Fuqi,
you might be interested in a now finished project called Diachron which allowed us to diff between ontology versions @simonjupp could provide some input. The release notes also have detailed information about changes,
thanks
Helen

**Comment by paolaroncaglia** [comment]
@FuqiX 
You may see an example output of Diachron, for 'obsolete_mammary gland', by clicking on the "Term history" tab here http://www.ebi.ac.uk/efo/EFO_0000854. Based on that, I'd think that the EFO version _with_ the obsoletion was released on 2017-12-19, but I'm not sure because trying https://www.ebi.ac.uk/efo/releases/v2017-12-19/efo.owl returns an error (again, possibly due to transitioning to GitHub). I'll leave it to @simonjupp from here. 
Thanks,
Paola

**Comment by FuqiX** [comment]
Thanks, Helen and Paola. Simon has shared with me some Diachron links before. I'll follow up with him :)

Cheers,
Fuqi
