### ISSUE TITLE
Improve ontology mapping for `CORONARY ARTERY DISEASE, AUTOSOMAL DOMINANT 2; ADCAD2`(OMIM:610947)

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#712]
Currently mapping the OMIM condition `CORONARY ARTERY DISEASE, AUTOSOMAL DOMINANT 2; ADCAD2` to EFO produces one of two outcomes depending on the approach followed:

1. `coronary artery disease` ([EFO_0000378](http://www.ebi.ac.uk/efo/EFO_0000378)): OLS
2. `Coronary artery disease - hyperlipidemia - hypertension - diabetes - osteoporosis` [(Orphanet_94062)](http://www.orpha.net/ORDO/Orphanet_94062): Both with EFO cross-references and ZOOMA (based on EVA/ClinVar)

The evidence we received at Open Targets for this condition is mapped to the Orphanet term, which is an issue because it is not a child of coronary artery disease. It would be good to review what would be the best mapping for this condition, also considering that there is a MONDO term ([MONDO_0012586](http://purl.obolibrary.org/obo/MONDO_0012586)) that is an exact match but is not available in EFO.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
Thanks for reporting this. We will
- [ ] Remove the OMIM:610947 xref from EFO Orphanet:94062 'Coronary artery disease - hyperlipidemia - hypertension - diabetes - osteoporosis'
- [ ] Import MONDO_0012586 'coronary artery disease, autosomal dominant 2' that already comes with the correct OMIM mapping
- [ ] Orphanet:94062 can't be found in ORDO, not even using the obsolete terms option in OLS; Googling it only retrieved an entry from 2014, I presume it was deleted from ORDO entirely? Obsolete in EFO without replacement? Ask ORDO? Or leave as is and it will be dealt with when we "update" the ORDO subset in EFO by replacing with Mondo equivalents. Discuss with @zoependlington.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
The edits above are now in EFO and will be visible after the EFO mid-April release. Thanks.
Paola

**Comment by AsierGonzalez** [comment]
Thank you @paolaroncaglia! Feel free to close the issue when you think it is appropriate.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez Thanks. Just FYI, we move completed tickets to the "Done" queue in ZenHub (you may not be able to see that), and close them during our fortnightly OntoTools scrums. Best wishes,
Paola

**Comment by AsierGonzalez** [comment]
Sure, I didn't want to close the ticket myself as I didn't know if that would affect your tracking system.
