### ISSUE TITLE
New term request: immunophenotype

### ISSUE THREAD

**Issue by ngeorgeebi** [EBISPOT/efo#715]
For new term requests, please provide the following information:

## Preferred term label
immunophenotype

## Synonyms
FACS_marker; FACS marker; immuno phenotype; immuno_phenotype; immuno-phenotype

## Textual definition

Characterisation of a set of cells according to the (surface level) antigens expressed
(https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C20072)
## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0000651

## Attribution

0000-0002-8674-0039

**Comment by ngeorgeebi** [comment]
Hi Zoe, thanks for taking this on. Is there any update to this?

**Comment by paolaroncaglia** [comment]
Hi @ngeorgeebi ,

I'll take this ticket while Zoe is busy with another priority. I'll make sure the term you requested is in the next EFO release (mid-April). Thanks.

Paola

**Comment by paolaroncaglia** [comment]
Note for self: 
- [ ] Add EFO:NEW immunophenotype
subclass of phenotype
"The characteristics of a set of cells according to the (surface level) antigens expressed."
database xrefs: NCIT:C20072
createdBy: 0000-0002-8674-0039
Synonyms: FACS_marker; FACS marker; immuno phenotype; immuno_phenotype; immuno-phenotype
(@ngeorgeebi : I'm suggesting a slightly rephrased definition to fit a phenotype term better; "Characterisation of ..." sounded more like an experimental process. Thanks.)

**Comment by paolaroncaglia** [comment]
@ngeorgeebi 
The new term EFO:0010649 immunophenotype is now in EFO and will be visible after the mid-April release. Thanks.

**Comment by ngeorgeebi** [comment]
thanks paola! much appreciated
