### ISSUE TITLE
New ontology term request (anterior temporal lobe)

### ISSUE THREAD

**Issue by Ananth-Prakash** [EBISPOT/efo#716]
For new term requests, please provide the following information:

## Preferred term label

anterior temporal lobe

## Synonyms

Brodmann area 38, BA38, temporopolar area 38 (H), temporal pole

## Textual definition

The anterior temporal lobe (ATL) is the most anterior tip of the temporal lobe, and is located rostral to the perirhinal cortex. PMID: 22421014

## Suggested parent term

Temporal lobe (UBERON_0001871)

## Attribution

No

**Comment by paolaroncaglia** [comment]
@Ananth-Prakash 
The term you requested, 'anterior temporal lobe' with suggested synonyms "Brodmann area 38, BA38, temporopolar area 38 (H), temporal pole", seems to be the same as UBERON:0006479 'Brodmann (1909) area 38' (see https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0006479). Therefore, we will
- [ ] Import UBERON:0006479 in EFO
- [ ] Ask Uberon to add synonyms 'temporopolar area 38 (H)', 'temporal pole', 'anterior temporal lobe' and 'anterior end of the temporal lobe' (all other synonyms are already in the Uberon entry), plus dbxref PMID: 22421014.
Please let us know if you have any question or concern.
Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@Ananth-Prakash 
UBERON:0006479 'Brodmann (1909) area 38' is now in EFO and will be visible after our next release, scheduled for March 16th. Once UBERON adds the requested synonyms and publication reference at the source, and releases a new version, those changes will be picked up by EFO too.
Thanks,
Paola
