### ISSUE TITLE
extrinsic cardiomyopathy and cardiomyopathy

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#724]
Extrinsic cardiomyopathy (http://purl.obolibrary.org/obo/MONDO_0002824) and cardiomyopathy (http://www.ebi.ac.uk/efo/EFO_0000318) are both in EFO. Extrinsic cardiomyopathy is going to the parent of cardiomyopathy.
However, 'extrinsic cardiomyopathy' (which is a secondary cardiomyopathy) is also a synonym for 'cardiomyopathy' (broad concept term) which is confusing when they both represent separate terms in EFO.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Thanks for bringing this up. We will 
- [ ] Remove the synonym 'extrinsic cardiomyopathy' from EFO 'cardiomyopathy'.

**Comment by paolaroncaglia** [comment]
@smnorthen 
FYI, I removed the synonym 'extrinsic cardiomyopathy' from EFO 'cardiomyopathy'. Will be visible in mid-April EFO release. Best wishes.
