### ISSUE TITLE
broken xref

### ISSUE THREAD

**Issue by nicolevasilevsky** [EBISPOT/efo#725]
## term label
EFO:1001001 keratoconjunctivitis sicca

## xref
OMIM:MTHU017601

This xref does not lead anywhere. I am going to remove it in Mondo

**Comment by nicolevasilevsky** [comment]
Also, there is a typo in the def, I did a PR to fix this in Mondo:

Drying and inflammation of the conjunctiva as a result of insufficient lacrimal secretion. When found in association with xerostomia and polyarthritis, it is called sjogren'S syndrome. [ MESH:D007638 ]

**Comment by paolaroncaglia** [comment]
@nicolevasilevsky 
Thanks for reporting this.
- [ ] We'll need to look into this further, it appears that there are 31 occurrences of OMIM:MTHUetc in EFO. I also found this old ticket (which Nicole may not be able to access - it basically says "several terms are mapped as OMIM ids with MTHU identifiers, which could be LOINC IDs"): https://www.ebi.ac.uk/panda/jira/browse/FGPTO-1436. @nicolevasilevsky , not sure if there are other instances of such OMIM IDs in Mondo too?
- [ ] The typos in the def are from Mondo, presumably the result of en-masse decapitalization ;-) The EFO def is fine, but thanks for the heads up.
- [ ] We'll also need to look into a possible duplication:
EFO:1001001 keratoconjunctivitis sicca, with synonym Dry Eye Syndrome, mapped to MONDO:0006818 
EFO:1000906 dry eye syndrome, with synonym keratoconjunctivitis sicca, mapped to MONDO:0006733 
@nicolevasilevsky , let us know if you have any suggestions, thanks.

**Comment by nicolevasilevsky** [comment]
there are 11 classes in Mondo that xref MTHU

I actually created a ticket yesterday to merge keratoconjunctivitis sicca with Dry Eye Syndrome.
https://github.com/monarch-initiative/mondo/issues/1236

I cc'd you @paolaroncaglia and added the EFO label.

**Comment by nicolevasilevsky** [comment]
I will create a ticket to fix the xrefs to MTHU

**Comment by paolaroncaglia** [comment]
- [ ] Merge (obsolete) EFO:1001001 keratoconjunctivitis sicca (mapped to MONDO:0006818), which is a duplicate, into EFO:1000906 dry eye syndrome (mapped to MONDO:0006733)
- [ ] Double-check that MONDO:0006818 is gone from Mondo terms and Mondo mapping files
