### ISSUE TITLE
Importing HP and Mondo terms for PheWAS

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#728]
Import of ~100 terms from HP and Mondo for PheWAS term mapping.

CC: @smnorthen

**Comment by smnorthen** [comment]
@zoependlington
Thank you!

**Comment by zoependlington** [comment]
71 HP terms from spreadsheet and 22 Mondo terms from spreadsheet have been imported into EFO and will be available in the next EFO release (16th March).

**Comment by smnorthen** [comment]
@zoependlington 
Many thanks! I have a few more terms which I have missed off the original list. Could these be included in the new release by any chance if I send them over later today?

**Comment by paolaroncaglia** [comment]
@smnorthen @zoependlington 
As per email, I'll import the last batch of terms you need before the release (scheduled for Monday afternoon).

**Comment by paolaroncaglia** [comment]
@smnorthen 
The last batch of HP and Mondo terms are now in EFO. @zoependlington is going ahead with the EFO release this afternoon. 
Best,
Paola

**Comment by smnorthen** [comment]
@paolaroncaglia
@zoependlington
Amazing. Thank you very much!
