### ISSUE TITLE
Hepatobiliary Neoplasm

### ISSUE THREAD

**Issue by zbyslaw** [EBISPOT/efo#73]
I would like to add the following neoplasm to submit new evidence to Open Targets for the February release.

## Preferred term label

Hepatobiliary Neoplasm

## Synonyms

Hepatic and Biliary Neoplasms|Hepatic and Biliary Tumors|Hepatic, Biliary, and Gallbladder Neoplasms|Hepato-Biliary Neoplasm|Hepato-Biliary Tumor|Hepatobiliary Tumor|Hepatobiliary Tumors|Liver and Biliary Neoplasm|Liver and Biliary System Neoplasm

## X-refs

MONDO: http://purl.obolibrary.org/obo/MONDO_0002514
NCIT:C8614 (MONDO:equivalentTo)
UMLS:C0854196 (NCIT:C8614)
DOID:3117 (MONDO:equivalentTo)

## Textual definition

A benign or malignant neoplasm that affects the liver parenchyma, bile ducts, and gallbladder. Representative examples of benign neoplasms include hepatocellular adenoma, bile duct adenoma, and gallbladder lipoma. Representative examples of malignant neoplasms include hepatocellular carcinoma, intrahepatic and extrahepatic cholangiocarcinoma, and gallbladder carcinoma. [ NCIT:C8614 ] 

## Suggested parent term

Digestive system neoplasm which is defined in MONDO and NCIT:
http://purl.obolibrary.org/obo/MONDO_0021223

Digestive system neoplasm should be a child of neoplasm in EFO.
The consequence is that all digestive system neoplasm subtypes already defined under neoplasm in EFO should be moved under 'digestive system neoplasm'.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @zbyslaw ,
Would it be ok to have this in for the March EFO release? Unfortunately the February release is only a few days away and I'm on leave until then (and Sira is away too). If it really can't wait, please ask Simon and he'll see if someone else can do it. Thanks.
Paola

**Comment by paolaroncaglia** [comment]
Note for self:
Below is a summary for this new term request:

- [ ] Create new term:
EFO:NEW1 digestive system neoplasm
Subclass of neoplasm
Subclass of digestive system disease
Equivalent to neoplasm and has_disease_location some (digestive system or part_of some digestive system)
Def: A benign or malignant neoplasm involving any part of the digestive system.
NCI_Thesaurus_definition_citation: NCIT:C3052 
Xref: MONDO:0021223
Synonyms: GI Neoplasm; Digestive Neoplasm; Digestive System Neoplasm; Neoplasm of the Gastrointestinal System; Neoplasm of Gastrointestinal System; Gastrointestinal System Tumor; Digestive Tumor; Neoplasm of GI System; Gastrointestinal Tumor; Tumor of the Digestive System; GI System Tumor; Tumor of the Gastrointestinal System; Tumor of GI System; Tumor of the GI System; GI System Neoplasm; Neoplasm of Digestive System; Gastrointestinal System Neoplasm; Neoplasm of the Digestive System; Tumor of Digestive System; Tumor of Gastrointestinal System; Neoplasm of the GI System; Gastrointestinal Neoplasm; Digestive System Tumor; GI Tumor

- [ ] Edit existing term:
EFO:1000217 Digestive System Adenoma
add Subclass of digestive system neoplasm

- [ ] Edit existing term:
EFO:1000218 Digestive System Carcinoma
add Subclass of digestive system neoplasm

- [ ] Create new term:
EFO:NEW2 Hepatobiliary Neoplasm
Subclass of digestive system neoplasm
has_disease_location UBERON:0002423 hepatobiliary system
Def: A benign or malignant neoplasm that affects the liver parenchyma, bile ducts, and gallbladder. Representative examples of benign neoplasms include hepatocellular adenoma, bile duct adenoma, and gallbladder lipoma. Representative examples of malignant neoplasms include hepatocellular carcinoma, intrahepatic and extrahepatic cholangiocarcinoma, and gallbladder carcinoma.
NCI_Thesaurus_definition_citation: NCIT:C8614
X-refs: MONDO:0002514, NCIT:C8614, UMLS:C0854196, DOID:3117
Synonyms: Hepatic and Biliary Neoplasms|Hepatic and Biliary Tumors|Hepatic, Biliary, and Gallbladder Neoplasms|Hepato-Biliary Neoplasm|Hepato-Biliary Tumor|Hepatobiliary Tumor|Hepatobiliary Tumors|Liver and Biliary Neoplasm|Liver and Biliary System Neoplasm

**Comment by paolaroncaglia** [comment]
Still to be done:

- [ ] add synonyms for 'digestive system neoplasm' (use Webulous template?)

- [ ] add database cross-references and synonyms for 'Hepatobiliary Neoplasm'
