### ISSUE TITLE
EFO v3.15.0 doesn't conform with OBO 1.4 specification

### ISSUE THREAD

**Issue by diekhans** [EBISPOT/efo#732]
EFO fails with software expecting 1.4,  it would be good to conform; although it appears that OBO 1.4  has been stuck in working draft for 8 years

[https://github.com/althonos/pronto/issues/65](https://github.com/althonos/pronto/issues/65)

**Comment by zoependlington** [comment]
Hi @diekhans. EFO has never complied with the OBO standard as it is an application ontology. Moving from version 2 to version 3, we have tried to align with the OBO standard more, but EFO will not full comply to 1.4 as we cater to importing and creating terms based on user requirements. As we continue to improve EFO gradually, we will continue to align with OBO principles as much as possible. If there is anything in particular causing software to break with EFO, please let us know and we can investigate alternative solutions.

**Comment by zoependlington** [comment]
Tagging @matentzn in case he has any ideas/comments.

**Comment by matentzn** [comment]
We can solve individual issues perhaps, but not OBO compliance in general - this needs to be done on tool level. We can probably beat some aspects of EFO into submission though...

**Comment by diekhans** [comment]
Thanks!  I send this before realizing the full state of OBO 1.4.
It has been an "working draft" for 8 years.  I walked down
the path tying to used the python package pronto (probably
the easiest to use); which supports 1.4, but sometimes works
on 1.2, so they don't check.

Sorry about the noise.

stay well
Mark

**Comment by zoependlington** [comment]
@diekhans No worries! Please let us know if we can help in any way from the EFO side. I will move this ticket to done now, but you're more than welcome to comment if you have further questions and we will reopen it. Take care!
