### ISSUE TITLE
UniProtKB 2020_02 release OMIM to EFO mappings

### ISSUE THREAD

**Issue by Yvonne-Lussi** [EBISPOT/efo#738]
Dear All,
I hope this finds you well. We have a new release with OMIM terms that I have mapped to EFO. In cyan are the new term requests, and the ones not highlighted are OMIM IDs that can be mapped to existing EFO terms or MONDO/Orphanet terms that we'd like to see added to EFO. Please find the link to the google spreadsheet below.
https://docs.google.com/spreadsheets/d/1h6LT3x6ofur_OwnnznMSPmOpuOm3CakA8S8I6gSPJf0/edit?usp=sharing
Many thanks in advance and best regards,
Yvonne

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
I assigned this ticket to myself for consistency with previous tickets of the same kind (UniProt OMIM to EFO mappings). I'll comment here when I have updates. Thanks.
Paola

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
Just a quick update. I started going through your latest spreadsheet of OMIM mappings. When in doubt between creating a very specific term that is not very different from an existing parent, and mapping to the broader parent instead, I'll probably go for the latter, considering that in the hopefully near future we may be able to import Mondo terms for many more OMIM entries, see https://github.com/EBISPOT/efo/issues/754. Then, the OMIM mappings may be updated in EFO. This way we will limit potential duplication of EFO and Mondo terms, and speed up addition of the mappings you need. But if you have any concern, please let me know. Thanks and best wishes, I hope you are safe and well,
Paola

**Comment by Yvonne-Lussi** [comment]
Good morning Paola
I hope you are safe and well, too. Thank you for your information regarding the potential future mapping updates. I will keep in mind to look for broader mapping when possible instead of creating a new term in EFO. 
Thank you very much for your work.
Take care and best wishes,
Yvonne

**Comment by paolaroncaglia** [comment]
Note for self: I committed edits for the top 10 OMIM entries; continue from row 12 down (included).

**Comment by paolaroncaglia** [comment]
Note for self: continue from row 24 down (included).

**Comment by paolaroncaglia** [comment]
@Yvonne-Lussi 
All OMIM mappings above are now in EFO, and will be visible after the next EFO release, scheduled for Wed April 15th. Thanks.

**Comment by Yvonne-Lussi** [comment]
Dear Paoloa
I hope you had a good Easter weekend. Thank you very much for the mapping of the OMIM terms and creating the new EFO terms.
Best,Yvonne
