### ISSUE TITLE
dyspepsia

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#74]
Please can you add 'dyspepsia' and its 2 parent terms (functional gastric disease, stomach disease) to EFO?

## Preferred term label

dyspepsia

## Synonyms

Dyspepsia, indigestion NOS, indigestion

## database cross reference

http://purl.obolibrary.org/obo/DOID_2321
SNOMEDCT_US_2016_03_01:155722007
MESH:D004415
SNOMEDCT_US_2016_03_01:196752002
UMLS_CUI:C0013395
ICD10CM:R10.13
ICD10CM:K30
NCI:C26756
SNOMEDCT_US_2016_03_01:139299007
SNOMEDCT_US_2016_03_01:162031009
SNOMEDCT_US_2016_03_01:87548005
SNOMEDCT_US_2016_03_01:249510006
SNOMEDCT_US_2016_03_01:266505001

## Textual definition

An uncomfortable, often painful feeling in the stomach, resulting from impaired digestion. Symptoms include burning stomach pain, bloating, heartburn, nausea, and vomiting. Causes include gastritis, gastric ulcer, gastroesophageal reflux disease, pancreatic disease, and gallbladder disease. [ NCIT:C26756 ]

## Suggested parent term

functional gastric disease => stomach disease => digestive system disease
NOT IN EFO (Mondo) => NOT IN EFO (Mondo) => IN EFO (http://www.ebi.ac.uk/efo/EFO_0000405)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Thanks @gkos-bio , this too will go in the March EFO release, as the February release is just a few days away and Sira and I are both on leave at the moment. Thanks.

**Comment by siiraa** [comment]
dyspepsia created under digestive system disease. For multiple term request (if need be), please provide info. However, this seems to be an issue of aligning with MONDO, I would leave this here with MONDO cross-referenced to this term (done). When we integrate the use of MONDO hierarchy with EFO-disease, this should be resolved with that integration approach (and not to create the duplicates of MONDO under EFO namespace)
