### ISSUE TITLE
Open Targets Slim EFO - cardiovascular disease term addition

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#740]
@paolaroncaglia
@zoependlington

cc: @AsierGonzalez

Please can the term: cardiovascular disease (http://www.ebi.ac.uk/efo/EFO_0000319) added back into the OT slim EFO file as we see a lot of invalid evidence strings due to the removal of the term from the slim.

Would it be possible to add it as a child term going to the Cardiac TA and the Vascular TA?

**Comment by paolaroncaglia** [comment]
@smnorthen 
cc @AsierGonzalez and @zoependlington 

Hi Sandra. I'd imagine that 'cardiovascular disease' may be added back into the OT EFO slim/profile, Zoe may confirm. However, as for its placement, normally it would not be ontologically correct to add it as a child term of 'cardiac disease' and 'vascular disease'. For any child of cardiovascular disease, the path up the hierarchy would always have to be true. It may be true now that we have cleaned up - i.e. now that, hopefully, any remaining child of cardiovascular disease would pertain to both cardiac and vascular system. Could you please provide more details of the invalid evidence strings you're seeing? Should we discuss this while sharing screens? 

Thanks,
Paola

**Comment by smnorthen** [comment]
@paolaroncaglia 
cc @AsierGonzalez and @zoependlington

I understand your concern and we may have to make 'cardiovascular disease' the parent term and new TA and then have vascular disease and cardiac disease as group terms sitting underneath. Would that be possible?

**Comment by zoependlington** [comment]
@smnorthen I can experiment hopefully this afternoon and see which is more feasible and sustainable long term for the slim. I think your latest suggestion will be easiest to implement, but I will need to look at it in more depth.

**Comment by d0choa** [comment]
Thanks everyone. We agreed to minimise complexity in the task:

- Rescue the cardiovascular disease term 
- Make cardiovascular disease a TA
- Keep vascular disease and heart disease as children of CVD (same as EFO)
- Remove the TA assignment to vascular disease and heart disease

The only unknown from my side is whether any action is required in the other children of CVD. (@smnorthen?):

- autoimmune disease of cardiovascular system
- cardiovascular neoplasm
- congenital anomaly of cardiovascular system
- pericardium disease

@AsierGonzalez will soon add some numbers on the impact of not having cardiovascular disease for OT.

If this change is made on the EFO 3.16 OT slim profile, we could use it in our upcoming release.

**Comment by AsierGonzalez** [comment]
These are the number of invalid evidence strings we have per data source because they are annotated with `EFO_0000319`:
```
 640 "chembl"
28504 "europepmc"
3888 "ot_genetics_portal"
 377 "phewas_catalog"
Total: 33,409
```

**Comment by smnorthen** [comment]
@d0choa 

Regarding the following children of cardiovascular disease:
•autoimmune disease of cardiovascular system - this sits also under immune system TA
•cardiovascular neoplasm - this sits also under neoplasm TA
•congenital anomaly of cardiovascular system - This will need to be moved to the congenital TA
•pericardium disease - we included pericardium as part of the heart anatomy for the slim, so this should go to heart disease TA

**Comment by paolaroncaglia** [comment]
Thank you all. For future sustainability and ontology correctness, I too would highly recommend making 'cardiovascular disease' the parent, rather than child, of 'cardiac disease' and 'vascular disease'.

**Comment by zoependlington** [comment]
I have managed to swap cardiovascular disease to be the TA with heart disease and vascular disease as child terms. Please see the screenshots below and let me know if there is anything else that needs to be changed. If not, I can update the 3.16.0 profile and slim files accordingly so they will be ready for the upcoming Open Targets release.

![image](https://user-images.githubusercontent.com/36990116/76978596-d0c1df00-692e-11ea-8604-e2fc4fd1b872.png)
![image](https://user-images.githubusercontent.com/36990116/76978662-e0d9be80-692e-11ea-8524-276cc25ad60a.png)

**Comment by smnorthen** [comment]
@zoependlington

Many thanks. That looks great. 
I am wondering if it would make sense to move following (below), too:

•autoimmune disease of cardiovascular system - keep only in immune system TA
•cardiovascular neoplasm - keep only in cell proliferation TA
•congenital anomaly of cardiovascular system - move to genetic TA

Thank you!

**Comment by d0choa** [comment]
The changes look great thanks @zoependlington 

Regarding @smnorthen suggestion, I agree with the observation but I think is part of a systematic problem. Many other TAs (e.g. integumentary, neuronal, etc.) have cancers or congenital diseases on them. This probably needs to be handled systematically not only in the context of cardiovascular disease.

**Comment by zoependlington** [comment]
Perfect! I have updated the release versions of the slim and profile to the version in the screenshots yesterday.

Just a note that it will be easier to maintain the slim the closer that it align with EFO, so removing these terms from the new cardiovascular disease TA where they definitely belong (e.g. autoimmune disease of cardiovascular system which absolutely _is_ a cardiovascular disease and is in EFO as such) may cause the slim to be more difficult to build or could result in some key associations being missed between therapeutic areas.
