### ISSUE TITLE
Suggested change to EFO_0004518

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#741]
## Suggested change

Suggest changing the main label for http://www.ebi.ac.uk/efo/EFO_0004518 from "serum creatinine measurement" to "creatinine measurement". The reason for this is to make metabolite terms more general and reusable, and to avoid having multiple terms for each metabolite depending on where in the body they are measured.

Suggest making "serum creatinine measurement" a synonym instead.

The definition should also be changed. To try to avoid causing any problems for anyone else using the term, my suggested changes try to preserve as much of the original content as possible. 
Old: "A serum creatinine measurement is a measure of the metabolite creatinine performed in the serum, and is used in assessment of kidney function."
Suggested: "A creatinine measurement is a measure of the metabolite creatinine in a sample. For example, in the serum, where it can be used in assessment of kidney function."

**Comment by zoependlington** [comment]
Thanks @eks-ebi! Changes have been made and will appear in the next release.

**Comment by twhetzel** [comment]
Thanks, I've updated the term label in the GWAS database.
