### ISSUE TITLE
Clarify term submission process for EVA imports

### ISSUE THREAD

**Issue by tskir** [EBISPOT/efo#745]
This is related to https://github.com/EBISPOT/efo/issues/744. I have a few questions about importing/adding terms to EFO to ensure we're doing everything correctly on the EVA side.

Internally we have two categories of terms:

## IMPORT terms

This is when we found something from MONDO/ORDO/HP which is not in EFO, but we'd like to have it. Our current approach is to list those terms in the “Add EFO disease” sheet and populate some fields with an in-house script which queries OLS and OxO and gets details from there.

Questions:
1. Can you confirm if we use the right template for this purpose, and whether we are using the template itself correctly?
2. This isn't really a question, but I just wanted to point out that in the template there are `def_cite` fields for MONDO and Orphanet, but not for HP. Because of this, we can't provide those cross-references even though we have them. For example, “Abnormality of radial ray” which we want to add in https://github.com/EBISPOT/efo/issues/744 is actually http://purl.obolibrary.org/obo/HP_0410049.
3. Given that data in that sheet which we submit ultimately comes from OLS and OxO, the whole thing seems a bit redundant. Is there a simpler established process you'd like us to follow for importing the existing terms?

## NEW terms

This is when we want to add something which is not from MONDO/ORDO/HP ontologies.

4. Our current protocol is to specify those terms manually in the issue description (this wasn't yet done in https://github.com/EBISPOT/efo/issues/744, but will be corrected shortly). However, it looks like for these terms we could also use the “Add EFO disease” sheet. Is my assumption correct? Could you suggest the optimal way to proceed here?
5. Virtually all NEW terms which we want to add come from MedGen and OMIM ontologies. Has there been any harmonisation effort between those ontologies and EFO, similarly to how it was done for MONDO/ORDO/HP? Is there a possibility, current or planned, to “import” terms from MedGen and OMIM, so that their names, descriptions and cross-references can be used? What is the best way to submit those terms to you to minimise the amount of work for everyone?

**Comment by paolaroncaglia** [comment]
Dear @tskir (cc @zoependlington ),
 
I see that the related ticket is assigned to Zoe, so I'll leave most questions here to her for now, but I'll mention a couple of things FYI about cross-referencing to OMIM in EFO. Lately, we've been adding mappings to OMIM (or new terms as appropriate) regularly, ~20-30 every month, to meet UniProt's needs. See e.g. their latest requests in https://github.com/EBISPOT/efo/issues/738. Also, Mondo has plans to refresh their OMIM imports soon, and EFO could then benefit from that work, by importing missing OMIM entries as Mondo terms. See https://github.com/monarch-initiative/mondo/issues/1283.

Best wishes,
Paola

**Comment by zoependlington** [comment]
@tskir For importing terms, if they come from an ontology that we currently import dynamically (currently this is HP, CL, Mondo and UBERON) you can send us simply the URI of the term in a separate tab of the spreadsheet (perhaps labelled "To import into EFO"). This will save you time and us time during the review :-)

For new terms: The template is currently out of date. If you have any other x-refs, these can go in the "definition citation" column. Our Webulous templates will be updated in time, although they are not the current top priority. I may be able to create a different template for your purposes that we can use with ROBOT but this will take a little time to get pulled together and right now my bandwidth is stretched. For now, please include all new term requests in the "Add EFO disease" template.

If you would like a call to run through these suggestions or demonstrate, I'm more than happy to have one. That way we can streamline the process for everyone involved.
