### ISSUE TITLE
Additional HP/Mondo terms for importing into EFO

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#751]
Would you be able to import the following terms into EFO please.
This is for Open Targets/PheWAS (last lot). I assume that the 1 Orphanet term at the end could also be loaded in?

http://purl.obolibrary.org/obo/HP_0030878
http://purl.obolibrary.org/obo/HP_0025324
http://purl.obolibrary.org/obo/HP_0200065
http://purl.obolibrary.org/obo/HP_0000405
http://purl.obolibrary.org/obo/HP_0008419
http://purl.obolibrary.org/obo/HP_0011227
http://purl.obolibrary.org/obo/HP_0011227
http://purl.obolibrary.org/obo/HP_0003565
http://purl.obolibrary.org/obo/HP_0020174
http://purl.obolibrary.org/obo/HP_0020139
http://purl.obolibrary.org/obo/HP_0001386
http://purl.obolibrary.org/obo/HP_0100014
http://purl.obolibrary.org/obo/HP_0005230
http://purl.obolibrary.org/obo/HP_0000264
http://purl.obolibrary.org/obo/HP_0010769
http://purl.obolibrary.org/obo/HP_0100699
http://purl.obolibrary.org/obo/MONDO_0003265
http://purl.obolibrary.org/obo/MONDO_0043237
http://purl.obolibrary.org/obo/MONDO_0000988
http://purl.obolibrary.org/obo/MONDO_0006816
http://purl.obolibrary.org/obo/MONDO_0000923
http://purl.obolibrary.org/obo/MONDO_0000924
http://purl.obolibrary.org/obo/MONDO_0019479
http://www.orpha.net/ORDO/Orphanet_522548

**Comment by paolaroncaglia** [comment]
Hi @smnorthen ,
I will 
- [ ] Import the HP and Mondo terms above
- [ ] The Orphanet term above has no definition and a potentially problematic hierarchy under itself. Instead I'll create a new EFO term for 'syndromic genetic cataract' (subclass of EFO Orphanet:98641 'Syndromic cataract') and map it to Orphanet:522548 (PMID:28611546). I suspect that most children of 'Syndromic cataract' should go under the new genetic term, but let's leave that for the Orphanet overhaul... Alternatively, do you think that the existing EFO Orphanet:98641 'Syndromic cataract' would do, seen as many of its children seem to be of genetic nature anyway, at least at a quick glance? (Mondo has a similar situation.) 

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
Also, @smnorthen , when you have a chance, please let us know if the previous EFO tickets labeled "PheWAS mapping" (numbers 659 to 663) are still needed. Thanks!

**Comment by smnorthen** [comment]
@paolaroncaglia 
Thank you. If the orphanet term is causing issues then I will go with 'syndromic cataract' for now. So please don't worry. 
Any yes, none of the other 'PheWAS' tickets are needed anymore and may be closed.

**Comment by paolaroncaglia** [comment]
@smnorthen thanks!

**Comment by paolaroncaglia** [comment]
@smnorthen the last lot of HP and Mondo terms for Open Targets/PheWAS are now in EFO and will be visible after the April 15th EFO release. Thanks.

**Comment by smnorthen** [comment]
@paolaroncaglia 
Amazing. Thank you!
