### ISSUE TITLE
mixed connective tissue disease synonyms

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#76]
For new term requests, please provide the following information:

## Preferred term label

mixed connective tissue disease

## Synonyms

MCTD

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
- [ ] Add ‘MCTD’ as alternative_term of ‘mixed connective tissue disease’
