### ISSUE TITLE
New term requested: soluble gp130 measurement 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#763]
New term requested: soluble gp130 measurement.

Details below:

https://docs.google.com/spreadsheets/d/1uAwQqEgw9lPiX12N6uPVnhPoD9sbkWc6U08GJIJJHuc/edit#gid=1272510144

**Comment by twhetzel** [comment]
@zoependlington this term looks ok to me based on how others of this type exist in EFO. Handing over to you.

**Comment by twhetzel** [comment]
Added to EFO.
