### ISSUE TITLE
problematic URI

### ISSUE THREAD

**Issue by sbreiff** [EBISPOT/efo#765]
Hello,

In the current (v3.17.0) efo.owl available on the EBI site, there is a term "elevated lactate dehydrogenase" with the URI "http://urigen_local_uri/33f82e6a-03d5-430b-91a4-f1356c8807eb/CL_0018004" (this also appears in the current EFO release notes). It seems like there must have been a mistake here with the URI generation, additionally because I can't find any record of this as a cell ontology term, or anywhere else for that matter. 

Thanks,
Sarah

**Comment by paolaroncaglia** [comment]
@sbreiff 
Thank you for reporting. We are looking into this and will update you as soon as it's fixed.
Best wishes,
Paola

**Comment by paolaroncaglia** [comment]
@sbreiff 

The mistake has been fixed (and I checked that there are no others; also my colleague @zoependlington is double-checking the check we have in place to avoid those errors).
The correct URI for the (phenotype) term 'elevated lactate dehydrogenase' is http://www.ebi.ac.uk/efo/EFO_0010695. This will be visible in a patch release we will provide as soon as possible and detail in an email to the efo-users mailing list. I assume you are a recipient of that, if not please let me know.
Thanks again for reporting, and apologies for any inconvenience.

Kind regards,
Paola

**Comment by sbreiff** [comment]
I wasn't in the mailing list but just subscribed. I did get the github notification for release 3.17.1, though. Thanks.

**Comment by paolaroncaglia** [comment]
@sbreiff 
Great, thank you!

**Comment by zoependlington** [comment]
Test has been added to the build and the release is done on GitHub (just waiting for the website to update), so moving this to 'done'. Please let us know if you spot any issues with the patch release, @sbreiff!
