### ISSUE TITLE
New term requested: stress urinary incontinence

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#766]
Webulous form:
https://docs.google.com/spreadsheets/d/11e-90noxgiZ55mioTvSPBPSbJySr6GNhm3rWSddt3cg/edit#gid=918781252

## Preferred term label

stress urinary incontinence

## Synonyms

NA

## Textual definition

Stress urinary incontinence is a form of urinary incontinence whereby the involuntary leakage of urine is immediately preceeded by an activity such as coughing, sneezing, or exercising.

## Suggested parent term

urinary incontinence

## Attribution

NA

**Comment by twhetzel** [comment]
There is an HP term for "stress urinary incontinence".
