### ISSUE TITLE
enrichment of phosphorylated Protein

### ISSUE THREAD

**Issue by ypriverol** [EBISPOT/efo#774]
For new term requests, please provide the following information:

## Preferred term label

enrichment of phosphorylated Protein

## Synonyms

phosphorylation enrichment, phosphorylation 

## Textual definition

The enrichment of phosphorylation in PRoteins using different methods such as Titanium dioxide (TiO2) 

## Suggested parent term

https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0009090

**Comment by paolaroncaglia** [comment]
@ypriverol 
Thank you for your request. 
- [ ] We'll add the term as
EFO:NEW enrichment of phosphorylated protein
subclass of EFO:0009090 'enrichment process'
"The enrichment of phosphorylation in proteins using different methods such as the use of titanium dioxide (TiO2)."
synonyms: phosphorylation enrichment, phosphorylation

We'll comment in this ticket when the new EFO ID is ready.

Note for self:
- [ ] Improve def of EFO:0009090 'enrichment process' (from "process which results in the increased concentration of an entity of interest" to "An experimental process which results in the increased concentration of an entity of interest.").

**Comment by paolaroncaglia** [comment]
@ypriverol 
The new term EFO:0010806 'enrichment of phosphorylated protein' has been added, and will be visible in OLS after the next EFO release, scheduled for Sept 15th. Thanks.

**Comment by paolaroncaglia** [comment]
@ypriverol 
I'm re-opening this ticket as we prefer to keep completed tickets in our own internal "Done" queue until we have a group meeting and review work done in a scrum period. Thanks anyway!
