### ISSUE TITLE
Terms found with multiple labels

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#775]
As part of the process of loading EFO into Virtuoso, I noticed a few warnings of terms with multiple labels. Here are the URIs:
- http://www.ebi.ac.uk/efo/EFO_0010216
- http://purl.obolibrary.org/obo/GO_0008283
- http://purl.obolibrary.org/obo/UBERON_0001124
- http://purl.obolibrary.org/obo/CHEBI_25682
- http://purl.obolibrary.org/obo/CHEBI_17929

**Comment by zoependlington** [comment]
- EFO_0010216 -> second label (An oligonucleotide primer with random sequence) should be definition - potentially should be renamed to be more obvious as currently is just "random", speak to Ola as he created this term.
- GO_0008283 -> label should be cell population proliferation, remove cell proliferation (should be related synonym)
- UBERON_0001124 -> is obsolete and has no labels
- CHEBI_25682 -> symmetric dimethylarginine should be related synonym
- CHEBI_17929 -> asymmetic dimethylarginine should be related synonym
