### ISSUE TITLE
Suggested improvements for EFO:0010192 primer

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#779]
**Work in progress**

EFO:0010192 primer
currently
"An oligonucleotide used to start the reaction in a polymerase-chain reaction."
Subclass of: single cell library information
Please consider
- [x] Adding synonym "oligonucleotide primer"
- [ ] Actually, to disambiguate from other uses of "primer", I'd make "oligonucleotide primer" the primary label, and "primer" a broad synonym 
- [ ] For the same reason and for consistency, I'd rename EFO:0010216 'random' as 'oligonucleotide random primer', and EFO:0010215 'oligo-dT' as 'oligo-dT primer' 
- [ ] Making EFO:0010192 broader as primers are used in other types of experiments too, not only single cell library construction, so a primer is not always (not necessarily) a subclass of 'single cell library information'.    

Update: label changes are stalled until we ensure that SCEA's pipeline isn't affected.

Further update: we're aware that, at present, changing primary labels can affect some EBI resources. The labels listed in this ticket are not incorrect, just potentially ambiguous. So, to progress, I added exact synonyms to disambiguate, but didn't change the labels. Similarly, wrt changing parentage of terms used by AE/GXA/SCA, at present that may cause issues in drop-down menus. The link to 'single cell library information' is not incorrect, just potentially incomplete, so let's leave it for now.

**Comment by twhetzel** [comment]
@zoependlington @paolaroncaglia do you want me to add the synonym?
