### ISSUE TITLE
Mastocytosis

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#78]
This myeloproliferative neoplasm and subtypes are not defined in EFO.
A text search in EPMC suggests > 6,000 articles related to Mastocytosis and Mast Cell Activation Syndrome

You may consider enhancing the classification of hematopoietic and lymphoid cell neoplasm at the same time.

## Preferred term label

Mastocytosis

## Synonyms

Mast Cell Activation Disease
Mast Cell Activation Syndrome
Mast Cell Activation Syndromes
MCAS
Mast Cell Disease
Mast-Cell Disease

## Textual definition

A clonal myeloproliferative neoplasm characterized by the proliferation and accumulation of neoplastic mast cells in one or multiple organs or organ systems. It is a heterogeneous group of neoplasms, ranging from cutaneous proliferations which may regress spontaneously, to aggressive neoplasms associated with organ failure and short survival. [ NCI ]

## X-refs

HP:0100495
NCIT:C116977
SNOMEDCT_US:397007003
SNOMEDCT_US:125541005
MSH:D008415
UMLS:C0024899

## Suggested parent term

Mastocytosis => Mast Cell Neoplasm => Myeloid Neoplasm => Hematopoietic and Lymphoid Cell Neoplasm

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
- [ ] Add new term:
EFO:NEW Hematopoietic and Lymphoid Cell Neoplasm
Intermediate between lymphoid neoplasm and Myeloid Neoplasm? Need to check.

- [ ] Add new term:
EFO:NEW Mast Cell Neoplasm
Subclass of Myeloid Neoplasm
…

- [ ] Add new term:
EFO:NEW Mastocytosis
Subclass of EFO:NEW Mast Cell Neoplasm
Definition: “A clonal myeloproliferative neoplasm characterized by the proliferation and accumulation of neoplastic mast cells in one or multiple organs or organ systems. It is a heterogeneous group of neoplasms, ranging from cutaneous proliferations which may regress spontaneously, to aggressive neoplasms associated with organ failure and short survival. [ NCI ]”
Synonyms:
Mast Cell Activation Disease
Mast Cell Activation Syndrome
Mast Cell Activation Syndromes
MCAS
Mast Cell Disease
Mast-Cell Disease
X-refs:
HP:0100495
NCIT:C116977
SNOMEDCT_US:397007003
SNOMEDCT_US:125541005
MSH:D008415
UMLS:C0024899

- [ ] The ID for the new terms are …

- [ ] There are 2 terms related to mastocytosis already in EFO:
1) Systemic Mastocytosis with Associated Clonal Hematological non-Mast-Cell Lineage Disease (is_a 'hematological system disease’)
2) cutaneous mastocytosis (is_a ‘skin neoplasm’)
They might need reclassifying.
