### ISSUE TITLE
Update term label for NCBITaxon_559292

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#790]
A minor revision for "Saccharomyces cerevisiae S288c" (NCBITaxon_559292): 

The taxon name was changed to "Saccharomyces cerevisiae S288C" (with capital "C").

This is important for us since Annotare get the species names from EFO and the spelling needs to match exactly for samples to be submitted to ENA. 

Thanks!

**Comment by paolaroncaglia** [comment]
@anjaf 
Your requested edit will be visible in the upcoming EFO release (scheduled for tomorrow May 18th).

@zoependlington 
@matentzn 
Making a note here that we may want to discuss refreshing the NCBITaxon entries in EFO - not sure if there's any plan already - in case there are other changes that would be good to pick up.

**Comment by anjaf** [comment]
Great, thanks!
