### ISSUE TITLE
Mondo and HP terms to be loaded into EFO

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#791]
Please could the Mondo and HP terms (attached in spreadsheet) be loaded into EFO. They are required for the FinnGen mapping for the Open Targets genetics portal.

**Comment by smnorthen** [comment]
[Mondo_HP_Terms_FinGen.xlsx](https://github.com/EBISPOT/efo/files/4649766/Mondo_HP_Terms_FinGen.xlsx)

**Comment by smnorthen** [comment]
@paolaroncaglia
One more that is missing of the list to add please:
http://purl.obolibrary.org/obo/NBO_0000003

**Comment by paolaroncaglia** [comment]
Hi @smnorthen ,
I imported the HP and Mondo terms from your spreadsheet, they'll be in the mid-June EFO release.
As for the NBO term, I believe we don't import from NBO directly, so
- [ ] I'll create a new EFO term referencing http://purl.obolibrary.org/obo/NBO_0000003.

**Comment by paolaroncaglia** [comment]
@smnorthen 
Actually, could you please add that to the new terms you'd like to get in via template? @zoependlington will reply to your email about those with a new template I believe. Thanks!

**Comment by smnorthen** [comment]
thank you @paolaroncaglia - will do!
