### ISSUE TITLE
New terms from FinnGen to be added to EFO

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#793]
Please can the terms in the attached spreadsheet be added to EFO? Please can you double check the format and spelling and let me know if anything else is required from my side. Please note that I have left the 'emotional behaviour' term off the list (I have adjusted the mapping for FinnGen accordingly).

[New Terms for EFO_FinnGen.xlsx]
(https://github.com/EBISPOT/efo/files/4657622/New.Terms.for.EFO_FinnGen.xlsx)

**Comment by zoependlington** [comment]
@smnorthen The 4 terms have been added as follows and will be available after our June release (15th):
- EFO_0010722 | 'ophthalmic procedure'
- EFO_0010721 | 'lung transplantation'
- EFO_0010720 | 'invasive mechanical ventilation'
- EFO_0010719 | 'continuous positive airway pressure'

**Comment by smnorthen** [comment]
Great. Thank you @zoependlington!
