### ISSUE TITLE
Addition of disease-phenotype links

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#794]
Update pipeline to include disease-phenotype links from Mondo.

**Comment by d0choa** [comment]
any updates on this task? We have looked at systematically estimating phenotypic similarities between diseases using this data with very promising results. We look forward to having this data available

**Comment by zoependlington** [comment]
@d0choa I have discussed adding the disease-phenotype links into EFO with @matentzn and we have a potential plan in place. Hopefully we will be able to implement it soon. As the EFO release is next week (Tuesday 15th), it most likely will not be available in the September release. However, we will try and add these links before the October release and potentially do a patch release for you to test this prior to the official release.

**Comment by d0choa** [comment]
There is no need to rush it on our side. We will be ok if it's ready in the October release. If there is any patch release, we are happy to try it out and provide feedback before the official release.

**Comment by matentzn** [comment]
@d0choa 

I am thinking of providing an EFO component that you can use in isolation or something we merge in that:

1. taps Mondo and HPOA datasources for the disease2phenotype associations
2. asserts them as annotation assertions (rather than object property assertions, which are harder to handle for you), using a new EFO property `disease_to_phenotype`

Do you want provenance on each such link (source where d2p came from)? Downside is that the filesize may increase quite a bit, upside is the links can be interpreted easier from your end. Let me know what you think!

**Comment by matentzn** [comment]
@d0choa one last thing. Do you want:

1. given all diseases and phenotypes in EFO, get the d2p links between them.
2. given all diseases in EFO, get _all_ d2p links and import any missing phenotypes into EFO.
3. given all d2p links, import all associated diseases and phenotypes and make the link

`3` could cause a major blow-up in size of EFO; if `3` is your answer, I will propose an alternative solution for you, where @zoependlington will curate a spreadsheet with all the links for you, which will be published alongside EFO. Let me know your. needs :)

**Comment by d0choa** [comment]
*2* sounds the most reasonable. There will still be a significant number of HPOs that are currently not present in EFO based on our analysis.

**Comment by matentzn** [comment]
Thanks!

**Comment by zoependlington** [comment]
@d0choa This is now done and will be available in the Open Targets EFO profile and slim (although the slim does not contain any HP terms) at the next release. All links are available under the skos:related annotation.

**Comment by d0choa** [comment]
great! let me clarify. The slim will contain a similar set of terms as in the previous release, whereas the profile will have all the missing HP terms that are mapped through `skos:related annotation` ?

**Comment by zoependlington** [comment]
They both have the skos:related annotation with the link to HP terms, just the profile file actually contains most of these HP terms while the slim file doesn't - the annotation is in both files.

One question is, if a disease term has a link to a HP phenotype term but the phenotype term is not in EFO, would you want the HP term imported?

**Comment by zoependlington** [comment]
For example these are the disease phenotype links for cone rod dystrophy where one term is in EFO (visual impairment) but the other 4 are not:

![image](https://user-images.githubusercontent.com/36990116/95448730-b21f4600-095b-11eb-9fbb-8fc022cb5d3e.png)

**Comment by d0choa** [comment]
It would make sense for us to have a version of the file where as much as the HP terms have been imported. Otherwise, we will have to list only the phenotypes that are present in EFO, which might raise many questions. Do you anticipate any issue with the import?

**Comment by zoependlington** [comment]
Importing HP terms into EFO is easy, I'm just not sure how many there are to import right now. I'll do some digging and see if I anticipate any issues, but right now it should be simple.

**Comment by d0choa** [comment]
After investigation of the produced profile https://github.com/opentargets/platform/issues/1212 we are quite convinced by the value of the `skos:related` axiom and the inclusion of the missing HP terms.

Can we propagate the changes currently applied to the profile into the slim?

Happy to open a different ticket if you think it's appropriate. (#870 could as well be closed once changes are propagated)
