### ISSUE TITLE
EFO:0000510 'genetic modification' may need revision

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#796]
(Stemming from COVOC work)

EFO:0000510 'genetic modification'
Is defined as "A genetic modification of the genome of an organism which may occur naturally by spontaneous mutation, or be introduced by some experimental means. Examples of genetic modification include specification of a transgene or the gene knocked-out or details of transient transfection."
But is child of 'experimental process' only. 
Suggestions to correct the situation are below. However, EFO:0000510 'genetic modification' is in the list of key properties for Annotare (see https://raw.githubusercontent.com/arrayexpress/annotare2/master/app/webapp/src/main/resources/Annotare-default.properties). So we probably need to run any change by them. 
- [x] Discuss with @zoependlington .

- [x] Then, we may want to consider the following:

- Make EFO:0000510 'genetic modification' a child of the broader parent 'process'; I think this would be the safest approach, considering that any listed modification may be either natural or experimental;
- Alternatively, create 2 terms for 'natural/spontaneous genetic modification' and 'experimental/induced genetic modification';
- Either way, revise children of EFO:0000510 'genetic modification' and add parents if/as appropriate under 'biological process' or 'experimental process'.

- [x] Stemming from the above, consult with @zoependlington about the use of the object property "organizational_class" with annotation = true in EFO. It seems to be a mix of things so its usage is not completely clear to me. Update: Zoe wrote "I believe "organizational_class" was originally used for Array Express, although I'm not 100% sure on this"; so we might want to review the matter with AE/GXA at a later date. (Update: I'll check this box now, we can address this question if/when it comes up again.)

**Comment by zoependlington** [comment]
@paolaroncaglia I believe "organizational_class" was originally used for Array Express, although I'm not 100% sure on this. To me, moving "genetic modification" to be a child of process and adding the two extra classes (experimental genetic modification and natural genetic modification) as children so we can organise the current children to on of these new classes sounds like a good plan.

@anjaf @ngeorgeebi, do you have any objection to these proposals? If there is anyone else we should ask, could you tag them or let us know please?

**Comment by paolaroncaglia** [comment]
@zoependlington 
Thanks for your feedback! I plan to
- [ ] Move EFO:0000510 'genetic modification' up the hierarchy to be a child of 'process' rather than 'experimental process' 
For the time being, I would not create specific children terms for 'experimental genetic modification' and 'natural genetic modification' because in theory any child of 'genetic modification' may be both. E.g. a deletion may occur spontaneously as well as by engineering. The only current children of EFO:0000510 'genetic modification' that can't be both are
a) spontaneous mutation (can only be natural by definition)
b) all the following (can only be experimental):
gene knock in
gene knock out
gene trap
induced mutation
targeted mutation
transgenic
I'm not sure if there is a real need to create 'experimental genetic modification' and 'natural genetic modification', but I don't have strong feelings either way. Meanwhile, I'll do the important edit in time for the release. Thank you.

**Comment by anjaf** [comment]
To add the impact assessment from ArrayExpress' side. Yes, we are using this term. Renaming or removing it would cause problems for us. I think adding child terms and regrouping children would be fine. 
For the parents, I think we would need to keep it under "experimental process" (while adding it in other places too should be fine). Although this might not be an absolute requirement. As long as it keeps the current EFO accession and name, we should be alright.

**Comment by paolaroncaglia** [comment]
@anjaf 
Thanks for your feedback. Yesterday I moved EFO:0000510 'genetic modification' up the hierarchy to be a child of 'process' rather than 'experimental process'. I did not rename or remove it, and the accession number hasn't changed. I did that change because I think it's more correct - e.g. 'genetic modification' has the child EFO:0004018 'spontaneous mutation' ("A genetic modification which has arisn by a spontaneous mutation in an individual") and it would be incorrect for that to be a descendant of 'experimental process' ("A process performed as part of an experiment or wider study, i.e. intentionally designed."). From what you write I understand that the change I applied would still be acceptable to you, but if that's not the case please let us know as soon as possible so we have time to do things differently (EFO will be released on Monday).

Note for self/EFO editor:
- [ ] Fix typos in def of EFO:0004018 'spontaneous mutation' ("A genetic modification which has arisn by a spontaneous mutation in an individual" => "A genetic modification which has arisen by a spontaneous mutation in an individual.")
