### ISSUE TITLE
Revise EFO:0000727 'treatment' branch

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#799]
Stemming from COVOC work.

EFO:0000727 'treatment'
"A process in which the act is intended to modify or alter some other _material_ entity,"
but children (rightfully) include 'cognitive behavioural therapy' where the object of the treatment is hardly material. Consider rewording/broadening the definition, and broadening the placement:

- [x] Looking at the children of EFO 'treatment', I think that the def could safely be edited to e.g. "A planned process intended to modify or alter a condition or characteristic of an organism or individual."
- [x] Move from being a subclass of 'experimental process' to 'planned process'
- [x] If keeping the current def, replace end "," with "."
- [x] Consider editing the label of the child EFO:0000470 'environmental stress' to 'environmental stress _treatment_' (as per its definition) to disambiguate it from a stimulus-like term.
- [x] Explicitly state the changes above in the release notes to notify our users
- [x] Consult with @zoependlington on the changes above (in particular, double-check if broadening the parentage would be ok for a term that has organizational class = true)
- [x] Note, the term is organizational class = true, do we need to consult with anyone before making changes? I can't remember exactly; @zoependlington please? Zoe thinks there's no need to consult if we're just editing a def.

**Comment by zoependlington** [comment]
@paolaroncaglia These changes are fine to do, please go ahead. We can explicitly state this in the release notes to notify, but should be okay.
