### ISSUE TITLE
Term definitions are swapped for EFO_0008401 and EFO_0008402

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/efo#804]
Term definitions are swapped for EFO_0008401 and EFO_0008402. Check for original template to see if only definitions are swapped or URI was applied to incorrect term.

**Comment by twhetzel** [comment]
The original template is here:
https://docs.google.com/spreadsheets/d/1AitYACDAt1xeWNjKH6vHq6xluHdiAaRP8hg_tArYLQY/edit#gid=858475039

**Comment by twhetzel** [comment]
Looks like only the term definitions were swapped.

@zoependlington did you suggest that each of these terms should be obsoleted and then re-added with their corrected definition?

**Comment by twhetzel** [comment]
NOTE: If the terms are obsoleted and new ones added, a GWAS developer should update the data in the GWAS (spotpro) database to account for the changes.

**Comment by zoependlington** [comment]
Definitions have been corrected.
