### ISSUE TITLE
UniProtKB Swiss-Prot Release 2020_04 Disease Mappings

### ISSUE THREAD

**Issue by Antonialock** [EBISPOT/efo#805]
Hi  Paola
We require a number of new mappings between DI-IDs and EFO.
See the attached spreadsheet

Most map exact to existing EFO or MONDO terms

Where OMIM discuss 'genetic heterogeneity' for a disorder I have marked this and suggested broad mapping (if there isn't an existing MONDO term). This seems to be true for most 
X disorder #
with the exception of immunodeficiency 66.

There is a couple of NTRs.

Let me know if I can make the suggestions more helpful! Thanks.

Link here
https://docs.google.com/spreadsheets/d/1xQZpO4JvMX4P4nJUi58cNH0AgYoaJRK6sGCUIv3S_fM/edit#gid=0

**Comment by paolaroncaglia** [comment]
@Antonialock 
Thanks for your input on this. I will
- [ ] Import Mondo terms that are exact mappings
- [ ] Look into other mappings and address them.
Will keep you posted!

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
To start with, I imported the 16 Mondo terms that are exact mappings, see the tab "Paola's copy" in https://docs.google.com/spreadsheets/d/1xQZpO4JvMX4P4nJUi58cNH0AgYoaJRK6sGCUIv3S_fM/edit#gid=696638968. These will be visible in our next EFO release, scheduled for June 15th.

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
I have added comments and action items in column H, tab "Paola's copy" of the [spreadsheet](https://docs.google.com/spreadsheets/d/1xQZpO4JvMX4P4nJUi58cNH0AgYoaJRK6sGCUIv3S_fM/edit#gid=696638968). Some action items are for you please (where you need a broad mapping to a Mondo term, that needs to be added at the source). For the bottom 5 lines, I've added brief explanations, let me know if anything is unclear. For 'immunodeficiency 66', EFO would rather add a broad mapping than create a new very granular term; if the OMIM term is ingested by Mondo in the future, we will import the Mondo term. Any question or concern please let me know, thanks.

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,
FYI, I've now added the OMIM mappings to EFO and Orphanet terms as per spreadsheet. They'll be visible in the mid-July EFO release. Left to do (hopefully in time for the release):
- [ ] Import MONDO_0011773
- [ ] Create EFO terms for the last 4 OMIM entries (bottom rows in spreadsheet).

**Comment by Antonialock** [comment]
Thank you, I made a ticket on mondo github for the mappings but it hasn't been resolved yet
https://github.com/monarch-initiative/mondo/issues/1735

**Comment by paolaroncaglia** [comment]
@Antonialock 
> Thank you, I made a ticket on mondo github for the mappings but it hasn't been resolved yet
> [monarch-initiative/mondo#1735](https://github.com/monarch-initiative/mondo/issues/1735)

FYI, I just had a meeting with Nicole and asked her for an update. It's in progress - her colleague Shahim is working on the pipeline and needs input from Chris about something. Also, Nicole will investigate with OMIM about how often they create classes, and plan accordingly if Mondo should make regular, fresh ingests from OMIM e.g. every 1-2 months or so.

**Comment by paolaroncaglia** [comment]
@Antonialock 
FYI, an update on OMIM ingests in Mondo. 
Nicole set an action item to "Set up schedule to ingest OMIM into Mondo (dependent on Shahim/Chris)", and also asked Ada from OMIM:
"...could you let us know how often new terms come out in OMIM? Is there a regular release cycle or do new terms get added as needed? We are working to keep the OMIM ingest into Mondo up to date, and if you have a regular cycle, we’ll try to refresh the ingest on a similar cycle."
Ada replied:
"New terms are added as needed, but you can track new gene-phenotype relationships, additions to phenotypic series, and new phenotypic series by following MIMmatch."
Going forward, please feel free to contact Nicole/Mondo if you'd like more updates. Thanks.

**Comment by paolaroncaglia** [comment]
@Antonialock 
I have now added EFO terms for the last 4 OMIM entries (bottom rows in tab "Paola's copy" in this [spreadsheet](https://docs.google.com/spreadsheets/d/1xQZpO4JvMX4P4nJUi58cNH0AgYoaJRK6sGCUIv3S_fM/edit#gid=696638968)). The EFO IDs are listed in the "Done?/Action item" column. Thanks.

**Comment by Antonialock** [comment]
thanks Paola

**Comment by paolaroncaglia** [comment]
(@Antonialock - in EFO we close tickets during our fortnightly scrums, that's why I re-opened. We move them to "Done" in our ZenHub queues but you can't see that. Thanks anyway! :-) )
