### ISSUE TITLE
Revise placement of EFO:0007948 HIV-associated neurocognitive disorder

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#806]
EFO:0007948 HIV-associated neurocognitive disorder

is defined as 
"HIV-associated neurocognitive disorder (HAND) remains a common complication of HIV infection in the combination antiretroviral therapy (ART) era. Although modern ART has substantially improved life expectancy and reduced the incidence of HIVassociated dementia (HAD), milder forms of HAND remain prevalent, including asymptomatic neurocognitive impairment (ANI) and mild neurocognitive disorder (MND). The overall prevalence of HAND is 30–50% among unselected HIV-infected persons."

and is
Subclass of:
Cognitive impairment
infectious disease biomarker
is_about some HIV infection

The connection to the biomarker/measurement branch seems incorrect (infectious disease biomarker = A quantification of some biomarker used in the diagnosis or management of infectious disease.). 
- [ ] Please consider severing the connection. 

Tagging @twhetzel as 'HIV-associated neurocognitive disorder' is gwas = true.

**Comment by kallia-p** [comment]
@zoependlington It appears that the connection of HIV-associated neurocognitive disorder to the biomarker/measurement branch is no longer there see screenshot below and if you are happy with the classification as it stands I can move this to DONE.
![image](https://user-images.githubusercontent.com/77484553/112628659-16ab6000-8e2b-11eb-9486-35e1d98eb33a.png)

**Comment by zoependlington** [comment]
Great! Then this can be moved to done!
