### ISSUE TITLE
Request for new EFO term for 'hyperphosphatemia'

### ISSUE THREAD

**Issue by vthawfeek** [EBISPOT/efo#808]
Hi. Could you please import the HP term for 'hyperphosphatemia' ([HP_0002905](https://hpo.jax.org/app/browse/term/HP:0002905)) into EFO.

**Comment by paolaroncaglia** [comment]
@vthawfeek 
The requested HP term is now in EFO and will be available with tomorrow's release.

**Comment by vthawfeek** [comment]
@paolaroncaglia Many thanks!  Is the term available now? Could I please have the EFO ID.

**Comment by paolaroncaglia** [comment]
@vthawfeek 
Yes, the term is available now and visible in OLS, see [here](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0002905).
It was imported from HP, so it has the HP ID HP:0002905.

**Comment by vthawfeek** [comment]
@paolaroncaglia  Many thanks!
