### ISSUE TITLE
Revise some terms under EFO OBI:0100051 'specimen'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#811]
EFO OBI:0100051 'specimen' is defined as "A material which is obtained and stored for potential use during an investigation.".
This child doesn't quite fit, please revise its placement:

- [x] GO:0005575 'cellular component' 
"The part of a cell or its extracellular environment in which a gene product is located. ..."
I'd suggest under 'organism part' or more specifically under 'anatomical entity'. (Update - we opted for 'material entity')

Also,
- [x] EFO:0000542 'individual'
This one might stay based on its definition: "An individual used a specimen in an experiment, from which a material sample was derived." but please add "as" in "An individual used _as_ a specimen...".

- [x] And there's a missing "." at the end of the def of 'specimen vial'.

**Comment by zoependlington** [comment]
No objection from me, that sounds logical.
