### ISSUE TITLE
HP and MONDO import for FinnGen

### ISSUE THREAD

**Issue by smnorthen** [EBISPOT/efo#815]
Please can the terms in the attached spreadsheet be imported into EFO for Open Target for the updated FinnGen mappings.

cc: @d0choa, @AsierGonzalez
[FinnGen_HP_and_MONDO_to_be_imported.xlsx](https://github.com/EBISPOT/efo/files/4891792/FinnGen_HP_and_MONDO_to_be_imported.xlsx)

**Comment by paolaroncaglia** [comment]
@smnorthen @d0choa @AsierGonzalez
HP and Mondo terms for FinnGen mappings are now imported in EFO and will be available with tomorrow's release.
