### ISSUE TITLE
Response to diet clean-up

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#818]
A couple of terms in the 'response to stimulus branch' could be tidied up under a 'response to diet' term.
e.g. response to low sodium diet, response to low calorie diet etc

## Preferred term label

response to diet

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

response to stimulus
Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Thanks @aoifemcm, I'll do this clean up before our August release.

**Comment by zoependlington** [comment]
Response to diet terms should now be all under the new term:

EFO_0010757 || response to diet

This will be available after our August release.
