### ISSUE TITLE
New EFO terms with missing definitions

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#825]
Dear EFO team, 

This is regarding the new EFO terms that Ola created for the Expression Atlas curation team a while ago (see https://github.com/EBISPOT/efo/issues/545). 
While reviewing those, I discovered a few terms have their definition missing or the wrong one. It would be great if you can add/update those.

Definition to be added:

Term label			| Definition
:---|:---
inferred cell type		| A cell type classification that is determined as result of a single-cell analysis, such as cell clustering or trajectory analysis.
single cell identifier		| A unique identifier for a single cell specimen.
random				| An oligonucleotide primer with random sequence.
UMI barcode read		| The sequencing read that contains the UMI barcode.
UMI barcode offset	| 	The offset in the sequence where the UMI barcode starts.
UMI barcode size	|	The length of the UMI barcode.
cell barcode read	|	The sequencing read that contains the cell barcode.
cell barcode offset	|	The offset in the sequence where the cell barcode starts.
cell barcode size	| The length of the cell barcode.
sample barcode read	|	The sequencing read that contains the sample barcode.
sample barcode offset	|	The offset in the sequence where the sample barcode starts.
sample barcode size	| The length of the sample barcode.

Definition needs correction:

Term label	|	Correct definition
:---|:---
cell barcode		| A short nucleotide sequence that is added during a single cell library preparation to identify reads from an individual cell.

**Comment by zoependlington** [comment]
Thank you @anjaf, I will make sure these definitions are added/changed before our August release.

**Comment by zoependlington** [comment]
These are now updated/added. Please let me know if there are any issues.

**Comment by anjaf** [comment]
Thank you @zoependlington!
