### ISSUE TITLE
Move single cell library construction terms

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#826]
Dear EFO team, 

Related to https://github.com/EBISPOT/efo/issues/545, the single cell library construction terms are now weirdly split between "library preparation" (OBI:0000711) and "single cell library construction" (EFO:0010183). 

I suggest to move the following terms from "library preparation" to be children "single cell library construction" as these are all single cell methods:
Smart-seq
Smart-seq2
Seq-Well
MARS-seq
Fluidigm C1-based library preparation
inDrop
sci-RNA-seq

**Comment by S2Ola** [comment]
@anjaf  This issue will be attended to and updated as required. Thank you

**Comment by anjaf** [comment]
Hello, just following up on this issue. Would be great if this can be done. Do you need any more information from me? 
Also related to this, I've created a new issue with more terms to be included under "single cell library construction" https://github.com/EBISPOT/efo/issues/875

**Comment by paolaroncaglia** [comment]
Hello @anjaf,
I'll address this ticket before the next EFO release, thank you,
Best wishes,
Paola Roncaglia

**Comment by paolaroncaglia** [comment]
Notes for self: to do before the next EFO release:
- [ ] Move the following terms to be direct children of 'single cell library construction’:
Smart-seq
Smart-seq2
Seq-Well
MARS-seq
Fluidigm C1-based library preparation
inDrop
sci-RNA-seq

Less urgent:
- [ ] Add definition to 'single cell library construction’
- [ ] Make definitions of ‘Smart-seq’ and ‘Smart-seq2’ different (look at their PMID xrefs)
- [ ] Add end period to definitions of terms in the 'library preparation' branch where needed.

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
All edits above will be in next Monday's EFO release, thanks.
