### ISSUE TITLE
Incorrect is_a assertions

### ISSUE THREAD

**Issue by daniwelter** [EBISPOT/efo#828]
There are a number of incorrect `is_a` assertions in the `single cell library information` (EFO:0010186) hierarchy. They include the child terms of `UMI barcode`, `cell barcode`, `sample barcode`, `cDNA read` and `spike in` (see attached screenshot). The child terms are not in fact more specific terms of their parents as implied by the `is_a` relationships but aspects of the parents, eg UMI and cell barcodes both have attributes such as offsets, sizes and reads but a UMI barcode offset is not a type of UMI barcode. 

Please correct the hierarchy by creating the following additional terms under `single cell library information` (EFO:0010186) and moving existing terms as suggested :
- nucleotide sequence offset (-> children: barcode offset, cDNA read offset)
definition: distance between the start of a nucleotide sequence and the start of the actual read
- nucleotide sequence size (-> children: barcode size, cDNA read size)
definition: number of nucleotides in a sequence
- barcode read  (-> children: UMI barcode read, cell barcode read, sample barcode read)
definition: the sequencing read in which the barcode is found
- barcode offset (-> children: UMI barcode offset, cell barcode offset, sample barcode offset)
definition: the 0-based offset of the start of the barcode in the read
- barcode size   (-> children: UMI barcode size, cell barcode size, sample barcode size)
definition: the length of the barcode in nucleotides

Make `spike in dilution` a child of `single cell library information` (EFO:0010186) (sibling of its current parent). 

`inferred cell type`(EFO:0010196) is also incorrectly classified. It should be a child of `cell type` (EFO:0000324) or possibly both `cell type` and its current parent.

<img width="274" alt="Screenshot 2020-07-27 at 17 13 52" src="https://user-images.githubusercontent.com/1267974/88559070-a72b6980-d02c-11ea-9f1e-80d29636ac17.png">

**Comment by zoependlington** [comment]
Thanks for spotting this @daniwelter, I'll implement these changes before the August release.

**Comment by zoependlington** [comment]
Here are the IDs for the new terms which will be available after our 17th August release:
EFO_0010755 | barcode size
EFO_0010754 | barcode offset
EFO_0010753 | barcode read
EFO_0010752 | nucleotide sequence size
EFO_0010751 | nucleotide sequence offset

**Comment by daniwelter** [comment]
Thanks for the quick resolution @zoependlington, much appreciated 👍
