### ISSUE TITLE
Import missing MONDO ids used by ClinGen to EFO

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#830]
Hello, could you please import the 56  MONDO ids in [unmapped_diseases_clingen.txt](https://github.com/EBISPOT/efo/files/5023203/unmapped_diseases_clingen.txt) to EFO? They are [MONDO disease ids used by ClinGen](https://search.clinicalgenome.org/kb/gene-validity) that I could not find in EFO neither directly nor as xrefs of current terms.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 

> Hello, could you please import the 56 MONDO ids in [unmapped_diseases_clingen.txt](https://github.com/EBISPOT/efo/files/5023203/unmapped_diseases_clingen.txt) to EFO? They are [MONDO disease ids used by ClinGen](https://search.clinicalgenome.org/kb/gene-validity) that I could not find in EFO neither directly nor as xrefs of current terms.

This is all done now and will be visible in the next EFO release (scheduled for August 17th). Thanks.

**Comment by AsierGonzalez** [comment]
That is fantastic news, thank you @paolaroncaglia
