### ISSUE TITLE
Add new EFO diseases - FGPTO-1490

### ISSUE THREAD

**Issue by lauhuema** [EBISPOT/efo#84]
All available info is in this spreadsheet: https://docs.google.com/spreadsheets/d/17Tzuo7TK1m-7yxE9SfhC6UWBJwF33nTdQX76cWb3nZ4/edit#gid=201247134

## Preferred term label 
AE/GXA

**Comment by siiraa** [comment]
@lauhuema - I have copied over the reference URLs to the def_cite column, and moved the comments from Wikipedia def_cite to comments column. Hope this is ok.

**Comment by siiraa** [comment]
template updated at https://docs.google.com/spreadsheets/d/1VhEJMh3EiwdL5v4jWQmXHTH-O3_jZ_FZNGnkxB6AwGo/edit#gid=652574045

**Comment by siiraa** [comment]
@lauhuema 
I've re-classified your requested dysplasia under neoplasm, and 'chronic lung allograft dysfunction' under 'lung disease', both to avoid having them classified under a general disease class.

you also have requested 'chronic hepatitis' to be classified under a "PHENOTYPE" term hepatitis. If you're ok with it being a phenotype, then it is asserted as-is.

**Comment by paolaroncaglia** [comment]
@lauhuema @simonjupp 
I'll close this ticket, as Sira committed all necessary changes. Any problem please let us know @lauhuema . Thanks.
