### ISSUE TITLE
EVA-EFO import 8/2020

### ISSUE THREAD

**Issue by joj0s** [EBISPOT/efo#843]
This release consists of 1 potential entries to import and 0 potential terms to create.

Spreadsheet: https://docs.google.com/spreadsheets/d/1EBGXExr-nVN5WLd-alV6ROsGt1vyrFM9jmZ-KEuPMTQ

**Comment by joj0s** [comment]
Hi, this issue was accidentally created as part of the testing process of the new manual curation platform's automatic issue submission process. It should be closed, sorry for the inconvenience.

**Comment by zoependlington** [comment]
@joj0s No trouble! Glad to see the ticket creation is working! Let us know if we can help in any way. I'll move this ticket to our done queue.
