### ISSUE TITLE
10 cell line updates

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#847]
Hello, we would like to request some relations to UBERON or other EFO terms for the following cell lines. 

PC-3 [EFO:0002074]
add Subclass of cancer cell line [EFO:0001639]
evidence: https://www.atcc.org/products/all/CRL-1435.aspx

G401 [EFO:0002179]
add Subclass of cancer cell line [EFO:0001639]
evidence: https://www.atcc.org/Products/All/CRL-1441.aspx

MEL cell line [EFO:0003971]
add Subclass of cancer cell line [EFO:0001639]
evidence: PMID: 21416373

UCH-1 [EFO:0004389]
add Subclass of cancer cell line [EFO:0001639]
evidence: https://www.atcc.org/Products/All/CRL-3217.aspx

adipose tissue derived mesenchymal stem cell [EFO:0005023]
add derives_from some (part_of some (adipose tissue [UBERON:0001013]))

HCEC 1CT [EFO:0009500]
add derives_from some (part_of some (colon [UBERON:0001155]))
evidence: PMID: 19962984

G1E-ER4 [EFO:0002055]
add derives_from some (part_of some (embryo [UBERON:0000922]))
evidence: PMID: 12832487

G1E [EFO:0002034]
add derives_from some (part_of some (embryo [UBERON:0000922]))
evidence: PMID: 12832487

DU 145 [EFO:0005441]
add derives_from some (part_of some (prostate gland [UBERON:0002367]))
evidence: https://www.atcc.org/products/all/HTB-81.aspx

THP-1 [EFO:0001253]
add derives_from some (part_of some (blood [UBERON:0000178]))
evidence: https://www.atcc.org/products/all/TIB-202.aspx

Thank you, please let me know if you need any further information.

**Comment by paolaroncaglia** [comment]
@bonitalam 
The edits you requested above are now in EFO and will be visible after the mid-September EFO release.
Please note that I did not add the axiom 
"HCEC 1CT [EFO:0009500]
add derives_from some (part_of some (colon [UBERON:0001155]))" 
because it is already inherited from the parent of the term.
Thanks,
Paola

**Comment by bonitalam** [comment]
Thanks for the clarification about HCEC 1CT and implementing the other changes @paolaroncaglia!
