### ISSUE TITLE
Zika virus infectious disease

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#848]
For new term requests, please provide the following information:

## Preferred term label
Zika virus infectious disease

## Synonyms
Zika Virus Infection
Zika virus disease
Zika Virus Disease
Congenital Zika Syndrome
Congenital Zika Virus Infection
Fever, Zika
ZikV Infection
Zika Fever
Zika

## Textual definition
An infection that is caused by the Zika virus, which is primarily transmitted via mosquitoes; it is characterized by fever, skin rash, arthralgia, and conjunctivitis. [NCIt]

## X-refs
NCIT:C128423
Orphanet:448237
MeSH:D000071243
DOID:0060478

## Suggested parent term
Viral Infection (EFO:0000763)

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Dear @gkos-bio ,

For this, we will 
- [ ] Import [MONDO:0018661 Zika virus infectious disease](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0018661). It already has all the required xrefs and synonyms, except for the following which 
- [ ] We can ask Mondo to add: 
Congenital Zika Syndrome
Congenital Zika Virus Infection
Fever, Zika
ZikV Infection
Along with fixing a typo in the Mondo definition (mosquito should read Mosquito).

Thanks,
Paola

**Comment by paolaroncaglia** [comment]
@gkos-bio 
MONDO:0018661 Zika virus infectious disease is now in EFO and will be visible after the mid-September EFO release. Thanks.

**Comment by gkos-bio** [comment]
That's fantastic. Thank you for adding the term to EFO.
