### ISSUE TITLE
Female Infertility

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#85]
For new term requests, please provide the following information:

## Preferred term label

female infertility

## Textual definition

Diminished or absent ability of a female to achieve conception. [ MESH:D007247 ]

## X-refs

HP:0008222
MP:0001926
UMLS:C0021361
SNOMEDCT_US:6738008
MSH:D007247
MONDO:0021124

## Suggested parent term

fermale infertility => infertility (EFO:0000545)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ]  Create new term:
EFO:NEW1 female infertility
Subclass of infertility (EFO:0000545)
realized_in some ('disease course' and ('has quality' some abnormal) and (has_disease_location some ('female reproductive system' or ('part of' some 'female reproductive system'))))
Def: Diminished or absent ability of a female to achieve conception. [ MESH:D007247 ]
X-refs: HP:0008222
MP:0001926
UMLS:C0021361
SNOMEDCT_US:6738008
MSH:D007247
MONDO:0021124

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008560 | female infertility
