### ISSUE TITLE
Missing HP_0003614 (Trimethylaminuria) - MONDO_0011182 ("trimethylaminuria (disease)") xref

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#850]
Hello, one of our algorithms fails to map the MONDO term for trimethylaminuria ([MONDO_0011182- "trimethylaminuria (disease)"](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0011182)) to EFO although there seems to be an equivalent HP term: [HP_0003614 - Trimethylaminuria](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHP_0003614). Tha mapping would succeed if there was a xref from HP_0003614 to MONDO_0011182  as it already exists in MONDO in the opposite direction. Is it possible to add it?

**Comment by paolaroncaglia** [comment]
Hi @AsierGonzalez ,

Unfortunately we can't add a mapping to an HP term in EFO as our HP import is dynamic, so the mapping would be lost at the next import. You'd need to ask HP to add the mapping please (tracker is https://github.com/obophenotype/human-phenotype-ontology/issues). Not sure how they'd feel to map a phenotype term to a disease one... also not sure when their next release would be.

Alternatively we could import the MONDO term for trimethylaminuria (MONDO_0011182- "trimethylaminuria (disease)") in EFO in time for the mid-Sept release, and you could use that.  

Please let me know what you prefer. Thanks,
Paola

**Comment by AsierGonzalez** [comment]
I see, it's a tricky one. Importing the MONDO term would be the simpleat solution but I feel it would mean the same concept would be duplicated in the ontology. For Open Targets two separate terms would mean that we would have some evidence for MONDO_0011182 and some for HP_0003614, which is not what we want.

As we are not in a rush to sort this out for the next release I will first reach out to the HP team. Thank you for pointing me to their GitHub page.

**Comment by paolaroncaglia** [comment]
@AsierGonzalez 
Thanks for your prompt feedback. I agree with your suggested strategy. I will close this ticket now, and you may re-open it (or open a new ticket) if/as needed.
