### ISSUE TITLE
MONDO_0010427 - syndromic X-linked intellectual disability Raymond type: import or xref?

### ISSUE THREAD

**Issue by AsierGonzalez** [EBISPOT/efo#851]
Another MONDO term I cannot currently map to EFO is [MONDO_0010427 - syndromic X-linked intellectual disability Raymond type](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0010427). The simple solution would be to just import MONDO_0010427 but I have noticed that ORDO have a term with the same label ([Orphanet_163953 - X-linked intellectual disability, Raymond type](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_163953)) that they have deprecated in favour of [Orphanet_776 - X-linked intellectual disability with marfanoid habitus](https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_776), which is already in [EFO](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_776). Therefore, the alternative would be to use the latter approach and to xref `MONDO_0010427` to `Orphanet_776`.

Unfortunately, I don't know enough about the disease to make an informed decision. What I like about the second approach is that we already have evidence for the same disease that is mapped to `Orphanet_776`. What I don't like about it is that it is a child of [MONDO_0100000 - MED12-related intellectual disability syndrome](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0100000&viewMode=All&siblings=false) which suggests that the disease is caused by a mutation in MED12 and, from what I have seen, it does not seem to be the case.

**Comment by paolaroncaglia** [comment]
Hi again @AsierGonzalez ,

I would bring this issue up with Mondo. I, too, don't know enough about the disease to make an informed decision, and I lack some elements (e.g. the evidences you wish to map). Looking at the definition of 'MED12-related intellectual disability syndrome', one could say that it is a legitimate parent for 'X-linked intellectual disability with marfanoid habitus', but again I don't have the elements that you might be referring to. Note that Mondo may not have updated their Orphanet ingest and therefore not picked up on the obsoletion of Orphanet_163953 yet. They are better connected to Orphanet curators and should be able to help. Ultimately and ideally, the most correct representation of the disease you're looking for should be captured in Mondo first, and then imported in EFO, so it's worth checking with them for more than one reason.

Please let me know if you have any concern. If not, this ticket may be closed. 
Thanks,
Paola

**Comment by AsierGonzalez** [comment]
Thank you @paolaroncaglia, I will raise this with MONDO then. Is their [GitHub issue tracker](https://github.com/monarch-initiative/mondo/issues) the correct place to ask them about it?

**Comment by paolaroncaglia** [comment]
@AsierGonzalez yes that's it! Thanks.
