### ISSUE TITLE
smallpox

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#855]
I couldn't find it in EFO.

## Preferred term label

smallpox

## Synonyms

variola virus
Variola Virus VAR 
Variola Virus 
VARIOLA VIRUS 
Smallpox Virus

## Textual definition

See x-refs below

## Suggested parent term

See: 
http://purl.obolibrary.org/obo/DOID_8736
http://purl.obolibrary.org/obo/NCIT_C96527
http://purl.obolibrary.org/obo/MONDO_0004651

for possible classification

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@gkos-bio 
- [ ] I will import MONDO:0004651 smallpox. 
- [ ] I will ask Mondo to add the following synonyms:
variola virus [related]
Variola Virus VAR [related]
Variola Virus [related]
VARIOLA VIRUS [related]
Smallpox Virus [related]

The DOID xref is already attached to the Mondo term.
The NCIT xref is for the virus itself, not the disease.
Thanks.

**Comment by gkos-bio** [comment]
Thanks

**Comment by paolaroncaglia** [comment]
@gkos-bio 
MONDO:0004651 smallpox will be visible in tomorrow's EFO release.
Synonyms requested to Mondo will take a bit longer, if approved. 
Thanks.
