### ISSUE TITLE
new term request for PMID 32546850 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#856]
Info on new term request can be found in this webulous template: https://docs.google.com/spreadsheets/d/1lD3QVrNyvKVvtSFjaPPicIOhbjIU7Gg4y4iYLs0sR5c/edit#gid=854636201.
New term is: self-injurious ideation -child term of self-injurious behaviour  
@zoependlington

**Comment by zoependlington** [comment]
"self-injurious ideation" added as http://www.ebi.ac.uk/efo/EFO_0010817
