### ISSUE TITLE
New term request for GWAS (PMID 32516399)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#857]
For new term requests, please provide the following information:

## Preferred term label

sensory perception of dietary content

## Synonyms

sensory perception of food content

## Textual definition

A measurement of some aspect of an individual's perception or recognition of the contents of food or drink.

## Suggested parent term

diet measurement - http://www.ebi.ac.uk/efo/EFO_0008111

**Comment by zoependlington** [comment]
"sensory perception of dietary content" added as http://www.ebi.ac.uk/efo/EFO_0010818
