### ISSUE TITLE
New term request for GWAS (PMID 32516399) #2

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#858]
For new term requests, please provide the following information:

## Preferred term label

dietary fat liking measurement

## Synonyms

fat liking measurement

## Textual definition

Quantification of an individual's appreciation of lipids or fats in food or drink.

## Suggested parent term

taste liking measurement - http://www.ebi.ac.uk/efo/EFO_0010155

**Comment by zoependlington** [comment]
This term has been added as "dietary fat liking measurement" (http://www.ebi.ac.uk/efo/EFO_0010816).
