### ISSUE TITLE
term request for PMID 32518416 GWAS Dawoud

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#859]
see email to gwas-term-request for query and link webulous

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
https://docs.google.com/spreadsheets/d/1kS_l0XKVNCryl3Q5GoEtiNsHFIsa9ysp6eznbR8KPcQ/edit#gid=2143365184

**Comment by zoependlington** [comment]
"clonal hematopoiesis" added as http://www.ebi.ac.uk/efo/EFO_0010819
