### ISSUE TITLE
diaphragmatic/abdominal hernia

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#86]
2 new terms with some reclassification

## Preferred term label

diaphragmatic hernia
abdominal hernia

### diaphragmatic hernia
NCIT_C34687
MP_0003924
MSH:D006548
ICD10_K44

### abdominal hernia
NCIT_C98700
UMLS_C0178282
ICD10_K46

### diaphragmatic hernia
A congenital or acquired weakness or opening in the diaphragm which allows abdominal contents to protrude into the chest cavity; congenital diaphragmatic hernias are caused when the embryonic diaphragm fails to fuse. [ NCI ]

### abdominal hernia
The protrusion of abdominal contents through a congenital or acquired defect in the abdominal wall. [ NCI ]

### diaphragmatic hernia
congenital diaphragmatic hernia => diaphragmatic hernia => diaphragm disease
traumatic diaphragmatic hernia => diaphragmatic hernia => diaphragm disease

congenital diaphragmatic hernia => diaphragmatic hernia => hernia
traumatic diaphragmatic hernia => diaphragmatic hernia => hernia

### abdominal hernia
ventral hernia => abdominal hernia => hernia

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Create new term:
EFO:NEW1 diaphragmatic hernia
Subclass of diaphragm disease (EFO:0007233)
Subclass of Hernia (HP:0100790)
Def: A congenital or acquired weakness or opening in the diaphragm which allows abdominal contents to protrude into the chest cavity; congenital diaphragmatic hernias are caused when the embryonic diaphragm fails to fuse. [ NCI ]
X-refs: NCIT:C34687 || MP:0003924 || MSH:D006548 || ICD10:K44

- [ ] Edit existing term:
EFO:0007216 (congenital diaphragmatic hernia)
Remove as subclass of diaphragm disease
Subclass of EFO:NEW1 diaphragmatic hernia

- [ ] Edit existing term:
EFO:1001861 (traumatic diaphragmatic hernia)
Remove as subclass of diaphragm disease
Subclass of EFO:NEW1 diaphragmatic hernia

There is an existing term, 'Hernia of the abdominal wall' (HP:0004299) that is a class of Hernia (HP:0100790). Will look into this term and edit with proceeding plans for abdominal hernia and editing the classification of ventral hernia (EFO:1001866).

**Comment by zoependlington** [comment]
Here is the ID for the new term:
EFO:0008561 | diaphragmatic hernia

Still to do:
There is an existing term, 'Hernia of the abdominal wall' (HP:0004299) that is a class of Hernia (HP:0100790). Will look into this term and edit with proceeding plans for abdominal hernia and editing the classification of ventral hernia (EFO:1001866).

**Comment by zoependlington** [comment]
- [ ] EFO:EDIT 'Hernia of the abdominal wall' (HP:0004299)
Synonyms: abdominal hernia
X-refs: NCIT_C98700
UMLS_C0178282
ICD10_K46
Def: The protrusion of abdominal contents through a congenital or acquired defect in the abdominal wall. [ NCI ]

- [ ] EFO:RECLASSIFY ventral hernia (EFO:1001866)
Subclass of 'Hernia of the abdominal wall' (HP:0004299)
