### ISSUE TITLE
New term request for Saw PMID 32887874

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#860]
For new term requests, please provide the following information:

Preferred term label
spontaneous coronary artery dissection

Synonyms
SCAD

Textual definition
The spontaneous occurrence of a dissection of the coronary artery. The clinical recognition of this phenomenon has increased as coronary angiography is becoming more commonly used in the treatment of acute coronary syndrome. The etiology of the condition has not been fully elucidated, but the mean age of presentation is 30-45 years, more than 70% are women, and 30% of cases occur in the peripartum period. 

Suggested parent term
Coronary artery disease- http://www.ebi.ac.uk/efo/EFO_0000378 

Attribution
Annalisa Buniello

NOTE: please see https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C165532

**Comment by zoependlington** [comment]
"spontaneous coronary artery dissection" added as http://www.ebi.ac.uk/efo/EFO_0010820
