### ISSUE TITLE
EFO for 32766472 Park SL

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#861]
For new term requests, please provide the following information:

## Preferred term label

Liver fat measurement

## Textual definition

A quantification of the fat content of the liver such as liver fat fraction, typically assessed by MRI.

## Suggested parent term

liver disease biomarker
http://www.ebi.ac.uk/efo/EFO_0006845

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
"liver fat measurement" has been added as http://www.ebi.ac.uk/efo/EFO_0010821
