### ISSUE TITLE
New term request for GWAS Catalog (Okamura 32558222)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#863]
For new term requests, please provide the following information:

## Preferred term label

response to rhododendrol

## Synonyms

response to 4-(4-Hydroxyphenyl)-2-butanol

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a rhododendrol stimulus. Rhododendrol is an organic compound that is present in many plants (e.g. rhododendron) and has been used as a tyrosinase inhibitor (e.g. in skin-lightening cosmetics).

## Suggested parent term

response to drug

## Note

The compound rhododendrol is in ChEBI: https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:81278

**Comment by zoependlington** [comment]
Added to EFO as EFO_0010824

**Comment by zoependlington** [comment]
To Do:

Import CHEBI term and add is_about to new term
