### ISSUE TITLE
New term request for Traylor, PMID 29715290

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#864]
#Preferred term label

Response to fluoropyrimidines

#Synonyms 

5-FU, Capecitabine

#Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of a fluoropyrimidine stimulus. 5-fluorouracil and Capecitabine are pyrimidine analogues used in treatment of cancer.

#Suggested parent term

Response to antimetabolite http://purl.obolibrary.org/obo/GO_0097329

#Attribution

Annalisa Buniello

**Comment by zoependlington** [comment]
Added as EFO_0010825
