### ISSUE TITLE
UniProtKB 2020_06 release OMIM to EFO mappings 

### ISSUE THREAD

**Issue by Antonialock** [EBISPOT/efo#865]
Hi Paola,

I have made a new spreadsheet of the new terms that need mapping to EFO. 

Do we need to request MONDO IDs for the ones that do not map to MONDO?

@paolaroncaglia @nicolevasilevsky 
Cheers!
Antonia

**Comment by Antonialock** [comment]
Link to sheet: https://docs.google.com/spreadsheets/d/1_Mtmbsr21hCTMblaxZazlgu_txcBrXxOL1Wl9q3GOH0/edit#gid=0

**Comment by paolaroncaglia** [comment]
Hi @Antonialock ,

I'm now on a different project within SPOT, so I'll leave this request to @zoependlington please (when she's back from annual leave). For the OMIM IDs that aren't in Mondo yet, yes please, the best course of action would be to liaise with them first, and then import all Mondo terms in EFO.

Best wishes,

Paola

**Comment by Antonialock** [comment]
Thanks Paola, best of luck with the new role.

**Comment by zoependlington** [comment]
Mondo Repo ticket: https://github.com/monarch-initiative/mondo/issues/2039

**Comment by zoependlington** [comment]
@Antonialock I anticipate that these terms will be added to Mondo for their late-November release so will keep an eye on the Mondo ticket.

**Comment by zoependlington** [comment]
@Antonialock These terms are now in EFO and will be available after our November (16th) release.

Let me know if there are any issues!
