### ISSUE TITLE
Poor standardization of term replaced by URIs

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#868]
A common task is updating ontology terms that have been replaced with newer ontology terms.

We can query EFO with SPARQL to get "term replaced by" (`obo:IAO_0100001`) relationships:

```sparql
PREFIX obo: <http://purl.obolibrary.org/obo/>
SELECT *
WHERE {
  ?efo_uri obo:IAO_0100001 ?replaced_by.
}
```

However, the `?replaced_by` object values are are poorly standardized.

## Value is a URI

Most of the time, `?replaced_by` is a string. However in certain cases it is a URI:

```sparql
  # add to the WHERE clause
  FILTER isURI(?replaced_by)
```

?efo_uri | ?replaced_by
-- | --
<http://purl.obolibrary.org/obo/CL_0000002> | <http://purl.obolibrary.org/obo/CLO_0000019>
<http://purl.obolibrary.org/obo/HP_0012823> | <http://www.ebi.ac.uk/efo/EFO_0010569>
<http://purl.obolibrary.org/obo/UBERON_0001124> | <http://purl.obolibrary.org/obo/UBERON_0006849>
<http://purl.obolibrary.org/obo/UBERON_0005284> | <http://purl.obolibrary.org/obo/UBERON_0008998>

Should `?replaced_by` be a string or URI?

## Value is a string with trailing whitespace

```sparql
  # add to the WHERE clause
  FILTER REGEX(?replaced_by, " ")
```

 row | efo_uri | replaced_by
 -- | -- | --
1 | efo:EFO_0000103 | "http://www.orpha.net/ORDO/Orphanet_98895 "
2 | efo:EFO_0000192 | "http://www.orpha.net/ORDO/Orphanet_550 "
3 | efo:EFO_0000204 | "http://www.orpha.net/ORDO/Orphanet_806 "
4 | efo:EFO_0000247 | "http://www.orpha.net/ORDO/Orphanet_50 "

<details>
<summary>expand for full table</summary>

 row | efo_uri | replaced_by
 -- | -- | --
1 | efo:EFO_0000103 | "http://www.orpha.net/ORDO/Orphanet_98895 "
2 | efo:EFO_0000192 | "http://www.orpha.net/ORDO/Orphanet_550 "
3 | efo:EFO_0000204 | "http://www.orpha.net/ORDO/Orphanet_806 "
4 | efo:EFO_0000247 | "http://www.orpha.net/ORDO/Orphanet_50 "
5 | efo:EFO_0000334 | "http://www.orpha.net/ORDO/Orphanet_178 "
6 | efo:EFO_0000338 | "http://www.orpha.net/ORDO/Orphanet_379 "
7 | efo:EFO_0000359 | "http://www.orpha.net/ORDO/Orphanet_191 "
8 | efo:EFO_0000367 | "http://www.orpha.net/ORDO/Orphanet_1572 "
9 | efo:EFO_0000390 | "http://www.orpha.net/ORDO/Orphanet_586 "
10 | efo:EFO_0000463 | "http://www.orpha.net/ORDO/Orphanet_261 "
11 | efo:EFO_0000491 | "http://www.orpha.net/ORDO/Orphanet_269 "
12 | efo:EFO_0000505 | "http://www.orpha.net/ORDO/Orphanet_44890 "
13 | efo:EFO_0000533 | "http://www.orpha.net/ORDO/Orphanet_399 "
14 | efo:EFO_0000665 | "http://www.orpha.net/ORDO/Orphanet_738 "
15 | efo:EFO_0000671 | "http://www.orphanet.org/rdfns#pat_id_2670 "
16 | efo:EFO_0000690 | "http://www.orpha.net/ORDO/Orphanet_797 "
17 | efo:EFO_0000697 | "http://www.orpha.net/ORDO/Orphanet_232 "
18 | efo:EFO_0000757 | "http://www.orpha.net/ORDO/Orphanet_98473 "
19 | efo:EFO_0000766 | "http://www.orphanet.org/rdfns#pat_id_8649 "
20 | efo:EFO_0000774 | "http://www.orpha.net/ORDO/Orphanet_3389 "
21 | efo:EFO_0001079 | "http://www.orpha.net/ORDO/Orphanet_778 "
22 | efo:EFO_0001381 | "http://purl.obolibrary.org/obo/UBERON_0001211 "
23 | efo:EFO_0002505 | "http://www.orpha.net/ORDO/Orphanet_102 "
24 | efo:EFO_0002611 | "http://www.orpha.net/ORDO/Orphanet_145 "
25 | efo:EFO_0002619 | "http://www.orpha.net/ORDO/Orphanet_99408 "
26 | efo:EFO_0002632 | "http://www.orpha.net/ORDO/Orphanet_54260 "
27 | efo:EFO_0002923 | "http://www.orpha.net/ORDO/Orphanet_790 "
28 | efo:EFO_0002946 | "http://www.orphanet.org/rdfns#pat_id_194 "
29 | efo:EFO_0003079 | "http://www.orpha.net/ORDO/Orphanet_47 "
30 | efo:EFO_0003089 | "http://www.orpha.net/ORDO/Orphanet_98755 "
31 | efo:EFO_0003090 | "http://www.orpha.net/ORDO/Orphanet_94147 "
32 | efo:EFO_0003091 | "http://www.orpha.net/ORDO/Orphanet_98759 "
33 | efo:EFO_0003092 | "http://www.orpha.net/ORDO/Orphanet_636 "
34 | efo:EFO_0003098 | "http://www.orpha.net/ORDO/Orphanet_2495 "
35 | efo:EFO_0003107 | "http://www.orpha.net/ORDO/Orphanet_98920 "
36 | efo:EFO_0003109 | "http://www.orpha.net/ORDO/Orphanet_79364 "
37 | efo:EFO_0003111 | "http://www.orpha.net/ORDO/Orphanet_216 "
38 | efo:EFO_0003112 | "http://www.orpha.net/ORDO/Orphanet_168491 "
39 | efo:EFO_0003113 | "http://www.orphanet.org/rdfns#pat_id_2523 "
40 | efo:EFO_0003470 | "http://purl.obolibrary.org/obo/UBERON_0003922 "
41 | efo:EFO_0003494 | "http://purl.obolibrary.org/obo/UBERON_0003073 "
42 | efo:EFO_0003622 | "http://purl.obolibrary.org/obo/UBERON_0005562 "
43 | efo:EFO_0003903 | "http://www.orpha.net/ORDO/Orphanet_906 "
44 | efo:EFO_0003910 | "http://www.orpha.net/ORDO/Orphanet_903 "
45 | efo:EFO_0003954 | "http://www.orpha.net/ORDO/Orphanet_861 "
46 | efo:EFO_0004121 | "http://www.orpha.net/ORDO/Orphanet_15 "
47 | efo:EFO_0004131 | "http://www.orpha.net/ORDO/Orphanet_72 "
48 | efo:EFO_0004132 | "http://www.orpha.net/ORDO/Orphanet_77 "
49 | efo:EFO_0004136 | "http://www.orphanet.org/rdfns#pat_id_207 "
50 | efo:EFO_0004137 | "http://www.orphanet.org/rdfns#pat_id_2079 "
51 | efo:EFO_0004139 | "http://www.orpha.net/ORDO/Orphanet_1310 "
52 | efo:EFO_0004140 | "http://www.orpha.net/ORDO/Orphanet_140 "
53 | efo:EFO_0004147 | "http://www.orpha.net/ORDO/Orphanet_821 "
54 | efo:EFO_0004148 | "http://www.orpha.net/ORDO/Orphanet_166 "
55 | efo:EFO_0004150 | "http://www.orpha.net/ORDO/Orphanet_184 "
56 | efo:EFO_0004151 | "http://www.orpha.net/ORDO/Orphanet_52 "
57 | efo:EFO_0004153 | "http://www.orpha.net/ORDO/Orphanet_1452 "
58 | efo:EFO_0004217 | "http://www.orpha.net/ORDO/Orphanet_30391 "
59 | efo:EFO_0004223 | "http://www.orpha.net/ORDO/Orphanet_156071 "
60 | efo:EFO_0004241 | "http://www.orpha.net/ORDO/Orphanet_388 "
61 | efo:EFO_0004250 | "http://www.orpha.net/ORDO/Orphanet_2573 "
62 | efo:EFO_0004275 | "http://www.orpha.net/ORDO/Orphanet_166282 "
63 | efo:EFO_0004523 | "http://www.orpha.net/ORDO/Orphanet_2133 "
64 | efo:EFO_0004538 | "http://www.orpha.net/ORDO/Orphanet_70589 "
65 | efo:EFO_0004688 | "http://www.orphanet.org/rdfns#pat_id_658 "
66 | efo:EFO_0004689 | "http://www.orpha.net/ORDO/Orphanet_90647 "
67 | efo:EFO_0004690 | "http://www.orphanet.org/rdfns#pat_id_10670 "
68 | efo:EFO_0004691 | "http://www.orpha.net/ORDO/Orphanet_130 "
69 | efo:EFO_0004692 | "http://www.orpha.net/ORDO/Orphanet_3286 "
70 | efo:EFO_0004716 | "http://www.orpha.net/ORDO/Orphanet_79102 "
71 | efo:EFO_0004721 | "http://www.orpha.net/ORDO/Orphanet_355 "
72 | efo:EFO_0004797 | "http://www.orpha.net/ORDO/Orphanet_524 "
73 | efo:EFO_0004882 | "http://www.orphanet.org/rdfns#pat_id_13980 "
74 | efo:EFO_0004883 | "http://www.orpha.net/ORDO/Orphanet_126 "
75 | efo:EFO_0004924 | "http://www.orpha.net/ORDO/Orphanet_100 "
76 | efo:EFO_0006311 | "http://purl.obolibrary.org/obo/HP_0011141 "

</details>

One challenge with these values containing whitespace is that they are not the actual URI and cause warnings when passed through SPARQL's `URI` function.

**Comment by zoependlington** [comment]
Thank you for finding this @dhimmel, I will make sure the whitespace containing properties are edited. All replaced by annotations should be just URIs.

**Comment by dhimmel** [comment]
> All replaced by annotations should be just URIs.

That makes sense. I'm currently writing a query where I want to do:

```sparql
?source_efo_uri obo:IAO_0100001+ ?replaced_by.
```

The `+` indicates one or more replaced by relationships to extract situations where a term has been replaced by a term that has been replaced. I think this will only work when `?replaced_by` is a URI.

**Comment by dhimmel** [comment]
# Broken orphanet URIs?

Some terms are replaced by URIs like http://www.orphanet.org/rdfns#pat_id_11237. However, if I try to [lookup this term](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http://www.orphanet.org/rdfns#pat_id_11237) in EFO, I get an error.

efo_uri | obsoleted | efo_id | efo_label | replaced_by_efo_uri | replaced_by_efo_id | replaced_by_efo_label | obsoleted_version | obsoleted_reason
-- | -- | -- | -- | -- | -- | -- | -- | --
http://www.ebi.ac.uk/efo/EFO_0000492 | true | EFO:0000492 | obsolete_familial combined hyperlipidemia | http://www.orphanet.org/rdfns#pat_id_11237 | rdfns#pat_id:11237 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0000671 | true | EFO:0000671 | obsolete_progeria syndrome | http://www.orphanet.org/rdfns#pat_id_2670 | rdfns#pat_id:2670 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_267...
http://www.ebi.ac.uk/efo/EFO_0000758 | true | EFO:0000758 | obsolete_limb-girdle muscular dystrophy | http://www.orphanet.org/rdfns#pat_id_8734 | rdfns#pat_id:8734 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_873...
http://www.ebi.ac.uk/efo/EFO_0000766 | true | EFO:0000766 | obsolete_hereditary leiomyomatosis and renal c... | http://www.orphanet.org/rdfns#pat_id_8649 | rdfns#pat_id:8649 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_864...

Is something wrong with these URIs?
<details>
<summary>expand for full table</summary>


efo_label | replaced_by_efo_uri | replaced_by_efo_id | replaced_by_efo_label | obsoleted_version | obsoleted_reason
-- | -- | -- | -- | -- | --
http://www.ebi.ac.uk/efo/EFO_0000492 | true | EFO:0000492 | obsolete_familial combined hyperlipidemia | http://www.orphanet.org/rdfns#pat_id_11237 | rdfns#pat_id:11237 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0000671 | true | EFO:0000671 | obsolete_progeria syndrome | http://www.orphanet.org/rdfns#pat_id_2670 | rdfns#pat_id:2670 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_267...
http://www.ebi.ac.uk/efo/EFO_0000758 | true | EFO:0000758 | obsolete_limb-girdle muscular dystrophy | http://www.orphanet.org/rdfns#pat_id_8734 | rdfns#pat_id:8734 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_873...
http://www.ebi.ac.uk/efo/EFO_0000766 | true | EFO:0000766 | obsolete_hereditary leiomyomatosis and renal c... | http://www.orphanet.org/rdfns#pat_id_8649 | rdfns#pat_id:8649 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_864...
http://www.ebi.ac.uk/efo/EFO_0002512 | true | EFO:0002512 | obsolete_supranuclear palsy, progressive | http://www.orphanet.org/rdfns#pat_id_846 | rdfns#pat_id:846 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0002620 | true | EFO:0002620 | obsolete_primary hyperparathyroidism | http://www.orphanet.org/rdfns#pat_id_5545 | rdfns#pat_id:5545 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0002631 | true | EFO:0002631 | obsolete_arrhythmogenic right ventricular card... | http://www.orphanet.org/rdfns#pat_id_8591 | rdfns#pat_id:8591 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0002946 | true | EFO:0002946 | obsolete_alpha-1-antitrypsin deficiency | http://www.orphanet.org/rdfns#pat_id_194 | rdfns#pat_id:194 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_194...
http://www.ebi.ac.uk/efo/EFO_0003113 | true | EFO:0003113 | obsolete_polycystic lipomembranous osteodyspla... | http://www.orphanet.org/rdfns#pat_id_2523 | rdfns#pat_id:2523 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_252...
http://www.ebi.ac.uk/efo/EFO_0003916 | true | EFO:0003916 | obsolete_cerebral arteriovenous malformation | http://www.orphanet.org/rdfns#pat_id_2264 | rdfns#pat_id:2264 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0004135 | true | EFO:0004135 | obsolete_Machado-Joseph disease | http://www.orphanet.org/rdfns#pat_id_13774 | rdfns#pat_id:13774 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0004136 | true | EFO:0004136 | obsolete_basal cell nevus syndrome | http://www.orphanet.org/rdfns#pat_id_207 | rdfns#pat_id:207 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_207...
http://www.ebi.ac.uk/efo/EFO_0004137 | true | EFO:0004137 | obsolete_epidermolytic hyperkeratosis | http://www.orphanet.org/rdfns#pat_id_2079 | rdfns#pat_id:2079 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_207...
http://www.ebi.ac.uk/efo/EFO_0004146 | true | EFO:0004146 | obsolete_central core myopathy | http://www.orphanet.org/rdfns#pat_id_65 | rdfns#pat_id:65 | None | 2.33 | duplicate of class http://www.orphanet.org/rdf...
http://www.ebi.ac.uk/efo/EFO_0004688 | true | EFO:0004688 | obsolete_long QT syndrome | http://www.orphanet.org/rdfns#pat_id_658 | rdfns#pat_id:658 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_658...
http://www.ebi.ac.uk/efo/EFO_0004690 | true | EFO:0004690 | obsolete_short QT syndrome | http://www.orphanet.org/rdfns#pat_id_10670 | rdfns#pat_id:10670 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_106...
http://www.ebi.ac.uk/efo/EFO_0004882 | true | EFO:0004882 | obsolete_avelline corneal dystrophy | http://www.orphanet.org/rdfns#pat_id_13980 | rdfns#pat_id:13980 | None | 2.32 | use 'http://www.orphanet.org/rdfns#pat_id_139...


</details>

**Comment by zoependlington** [comment]
All whitespace trailing replaced by strings have been fixed and I have implemented a QC check in our build process to make sure this doesn't happen again.

As for the strange Orphanet URIs, they are indeed odd and I will need to investigate these further to figure out what is going on with them.

**Comment by zoependlington** [comment]
@dhimmel I have updated all strange Orphanet URIs, so they should be correct now, and ensured the obsolete term replaced by entries are strings where possible - as many of these are coming from an external ontology through dynamic imports we can not control the annotations as they will update from the domain ontology with each build.

With that, I believe all tasks in this ticket are complete so I will move this to "Done". Thanks!
