### ISSUE TITLE
Deprecated terms whose owl:deprecated value is a str not a boolean true

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#869]
The README notes:

> Deprecated terms are no longer children of obsolete class (http://www.geneontology.org/formats/oboInOwl#ObsoleteClass), instead, they are given the annotation property owl:Deprecated (http://www.w3.org/2002/07/owl#deprecated).

On EFO v3.22.0, it appears almost all deprecated nodes have the boolean value `true` for `owl:deprecated`.

However, there are two nodes that don't use `true` to indicate deprecation, and instead have a string value:

```sparql
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT *
WHERE {
  ?efo_uri owl:deprecated ?deprecated.
  # retains ?deprecated values that are strings, but not booleans
  FILTER( ?deprecated != " ")
}
ORDER BY ?efo_uri
```

?efo_uri | ?deprecated
-- | --
<http://purl.obolibrary.org/obo/BTO_0001679> | Duplicate class
<http://www.ebi.ac.uk/efo/EFO_0001992> | replaced with PO term

Should these notes on why the term is deprecated go in `efo:reason_for_obsolescence` instead?

**Comment by zoependlington** [comment]
Thank you @dhimmel, all terms should have a boolean true so I will investigate why this isn't the case for all.

**Comment by dhimmel** [comment]
Thanks @zoependlington! Much appreciated.

Down the road, I was wondering whether checking for this type of issue could be automated? For example, could you enforce a schema that required `owl:deprecated` to be a boolean?

I see something that looks like testing at (still familiarizing myself with the ecosystem):

https://github.com/EBISPOT/efo/blob/1d63bdde584ba89d6b6df7e783625b3b40a6cc33/src/ontology/Makefile#L280-L291

**Comment by zoependlington** [comment]
Absolutely! The Makefile lines you quoted allows a series of SPARQL validation checks to run (all which can be found in our SPARQL directory), so I will add an extra one in for this case. Thank you for helping to improve EFO!

**Comment by zoependlington** [comment]
These terms have been cleaned up and the SPARQL violation query has been added.

**Comment by dhimmel** [comment]
Thanks @zoependlington. Really cool to see the commit addressing this.

I made a comment on https://github.com/EBISPOT/efo/commit/dd87da97b1f1ab769b5e234ce256947879fca2b3 about whether the new violation query enforces that the value of `owl:deprecated` is a boolean.

**Comment by zoependlington** [comment]
Thanks @dhimmel, the query has been updated.

**Comment by dhimmel** [comment]
> Thanks @dhimmel, the query has been updated.

Cool linking to the update in https://github.com/EBISPOT/efo/commit/6f096f43941e00b3a753e1fe11dacac823e60c30.

Will test it out in a little bit.

**Comment by dhimmel** [comment]
On v3.22.0, the updated query in https://github.com/EBISPOT/efo/commit/6f096f43941e00b3a753e1fe11dacac823e60c30, doesn't return any results for me in ontotext-graphdb:

https://github.com/EBISPOT/efo/blob/6f096f43941e00b3a753e1fe11dacac823e60c30/src/sparql/deprecated-violation.sparql#L7-L12

I'm newish to SPARQL, so not sure whether there is a strong reason to use the regex function for the match here. What about a query like:

```sparql
# find owl:deprecated literals that are not true booleans.
# see https://github.com/EBISPOT/efo/issues/869
SELECT ?cls ?dep WHERE {
  ?cls a owl:Class .
  ?cls owl:deprecated ?dep .
  FILTER (DATATYPE(?dep) != xsd:boolean || ?dep != 'true'^^xsd:boolean ) .
}
ORDER BY ?cls
```

This finds the two problematic records currently:

![image](https://user-images.githubusercontent.com/1117703/97710227-da4d2100-1a91-11eb-893e-bef84eb0ecf7.png)

And it should find any owl:deprecated values that are false. Not sure if there are any other edge cases this would miss. I removed the `FILTER (!isBlank(?cls))` since that didn't remove any results, but not sure whether that's important for the future.
