### ISSUE TITLE
New term request for "scATAC-seq"

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#874]
For new term requests, please provide the following information:

## Preferred term label

scATAC-seq

## Synonyms

single-cell ATAC-seq
single cell ATAC-seq
single cell ATAC-sequencing
single cell assay for transposase-accessible chromatin using sequencing
ATAC-seq (single cell)

## Textual definition

PMID: 26083756

A method for detecting the accessible chromatin in individual cells by transposase-accessible chromatin sequencing assay

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0007045
http://www.ebi.ac.uk/efo/EFO_0010183

## Attribution

0000-0002-8674-0039

**Comment by paolaroncaglia** [comment]
@anjaf 
The term you requested above already exists in EFO with the same PMID xref as the one you indicate:
EFO:0008904 ’scATAC-seq (Microfluidics)'
I will 
- [ ] Add the synonyms you suggest to this existing term
- [ ] Add the parents you suggest
- [ ] Add your ORCID 

Also, may I please ask for your feedback on this other existing term, EFO:0008925 ’Single cell ATAC-seq (cell index)’. At a very quick reading, it looks like this term should continue to exist separately from EFO:0008904 ’scATAC-seq (Microfluidics)’ as they don’t represent the exact sam technique. Would you agree? Either way, I will 
- [ ] Add to it the same parents as you suggested for the “sibling” term.

Thanks,
Paola

**Comment by anjaf** [comment]
Hi Paola, 
This is interesting. Yes, it seems that the two existing terms refer to the two method papers that came out at the same time (one in Nature and one in Science) and therefore specify their difference, which is in the way individual cells get separated (either by microfuidics or by combinatorial indexing). See: https://pubmed.ncbi.nlm.nih.gov/26294014/#&gid=article-figures&pid=fig-1-uid-0
Now there is also droplet based scATAC-seq (e.g. from 10x Genomics). So what I had in mind was a more generic term just describing ATAC-seq of single cells regardless of how cells were separated. From the logic the two existing terms would be child terms of "scATAC-seq" as they are more specific. Perhaps the more common term can reference both publications? What do you think?

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
Thanks for clarifying, very helpful. Yes, let’s have a new generic term for scATAC-seq, and place the existing, more specific ones as its children. The generic term will cross-reference your ORCID and the wikipedia entry for scATAC-seq, while the children term will keep their PMID xrefs to the specific papers.

Details/notes for self:

- [ ] Add EFO:NEW ‘scATAC-seq’:
Subclass of ‘ATAC-seq’ and ‘single cell library construction’
“A method for detecting the accessible chromatin in individual cells by transposase-accessible chromatin sequencing assay.” 
Dbxrefs: http://orcid.org/0000-0002-8674-0039, https://en.wikipedia.org/w/index.php?title=ATAC-seq&oldid=984332600#Single-cell_ATAC-seq
Synonyms: 
single-cell ATAC-seq
single cell ATAC-seq
single cell ATAC-sequencing
single cell assay for transposase-accessible chromatin using sequencing
ATAC-seq (single cell)

- [ ] Edit EFO:0008904 ’scATAC-seq (Microfluidics)’:
Make it subclass of EFO:NEW ‘scATAC-seq’

- [ ] Edit EFO:0008925 'Single cell ATAC-seq (cell index)’:
Make it subclass of EFO:NEW ‘scATAC-seq’

**Comment by paolaroncaglia** [comment]
@anjaf ,
This is done too, will be in next Monday's EFO release.
