### ISSUE TITLE
Single cell assay terms to be added as children of EFO_0010183

### ISSUE THREAD

**Issue by anjaf** [EBISPOT/efo#875]
Dear EFO team, 

I would like to request a few more single cell assay terms to be added as child terms of EFO_0010183 (single cell library construction), as we plan to use this term for a drop-down selection of assay types in Annotare. 

Can the following terms please be added under EFO_0010183?

- http://www.ebi.ac.uk/efo/EFO_0009294 (CITE-seq)
- http://www.ebi.ac.uk/efo/EFO_0008905 (scBS-seq)
- http://www.ebi.ac.uk/efo/EFO_0009919 (SPLiT-seq)
- http://www.ebi.ac.uk/efo/EFO_0010550 (sci-RNA-seq)
- http://www.ebi.ac.uk/efo/EFO_0008906 (scChIP-seq)
- http://www.ebi.ac.uk/efo/EFO_0009979 (single cell Hi-C)

I have an open related issue in the same context: https://github.com/EBISPOT/efo/issues/826

Thank you!

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] Check if any of the above still needs doing.

**Comment by paolaroncaglia** [comment]
Hi @anjaf ,
All done, will be in next Monday's EFO release. Thanks.
