### ISSUE TITLE
56 cell line NTRs

### ISSUE THREAD

**Issue by bonitalam** [EBISPOT/efo#876]
Hello - ENCODE would like to request EFO terms to be made for the cell lines in this spreadsheet: https://docs.google.com/spreadsheets/d/1W9nj5MdDa2KtTnSxljr8pzrE_c5W818pCnK6bS4CRcs/edit?usp=sharing

There are currently no terms for these cell lines in CLO or BTO. They are available through Coriell and were a part of the 1000 Genomes Project.  

Thank you!

**Comment by zoependlington** [comment]
Thanks @bonitalam, we will try to get these into EFO for our November release.

**Comment by bonitalam** [comment]
Great, thank you @zoependlington!

**Comment by zoependlington** [comment]
All terms have been added and will be available in our next release (16th November).

Here are the IDs:

http://www.ebi.ac.uk/efo/EFO_0010890 | HG03575 
http://www.ebi.ac.uk/efo/EFO_0010889 | HG03571 
http://www.ebi.ac.uk/efo/EFO_0010888 | HG03565 
http://www.ebi.ac.uk/efo/EFO_0010887 | HG03558 
http://www.ebi.ac.uk/efo/EFO_0010886 | HG03521
http://www.ebi.ac.uk/efo/EFO_0010885 | HG03520
http://www.ebi.ac.uk/efo/EFO_0010884 | HG03469
http://www.ebi.ac.uk/efo/EFO_0010883 | HG03460
http://www.ebi.ac.uk/efo/EFO_0010882 | HG03457
http://www.ebi.ac.uk/efo/EFO_0010881 | HG03442
http://www.ebi.ac.uk/efo/EFO_0010880 | HG03439
http://www.ebi.ac.uk/efo/EFO_0010879 | HG03432
http://www.ebi.ac.uk/efo/EFO_0010878 | HG03378
http://www.ebi.ac.uk/efo/EFO_0010877 | HG03354
http://www.ebi.ac.uk/efo/EFO_0010876 | HG03342
http://www.ebi.ac.uk/efo/EFO_0010875 | HG03280
http://www.ebi.ac.uk/efo/EFO_0010874 | HG03196
http://www.ebi.ac.uk/efo/EFO_0010873 | HG03175
http://www.ebi.ac.uk/efo/EFO_0010872 | HG03159
http://www.ebi.ac.uk/efo/EFO_0010871 | HG03139
http://www.ebi.ac.uk/efo/EFO_0010870 | HG03135
http://www.ebi.ac.uk/efo/EFO_0010869 | HG03108
http://www.ebi.ac.uk/efo/EFO_0010868 | HG03103
http://www.ebi.ac.uk/efo/EFO_0010867 | HG03097
http://www.ebi.ac.uk/efo/EFO_0010866 | HG03095
http://www.ebi.ac.uk/efo/EFO_0010865 | HG03066
http://www.ebi.ac.uk/efo/EFO_0010864 | HG03064
http://www.ebi.ac.uk/efo/EFO_0010863 | HG03060
http://www.ebi.ac.uk/efo/EFO_0010862 | HG03045
http://www.ebi.ac.uk/efo/EFO_0010861 | HG03039
http://www.ebi.ac.uk/efo/EFO_0010860 | HG03025
http://www.ebi.ac.uk/efo/EFO_0010859 | HG02981
http://www.ebi.ac.uk/efo/EFO_0010858 | HG02973
http://www.ebi.ac.uk/efo/EFO_0010857 | HG02970
http://www.ebi.ac.uk/efo/EFO_0010856 | HG02943
http://www.ebi.ac.uk/efo/EFO_0010855 | HG02938
http://www.ebi.ac.uk/efo/EFO_0010854 | HG02885
http://www.ebi.ac.uk/efo/EFO_0010853 | HG02884
http://www.ebi.ac.uk/efo/EFO_0010852 | HG02870
http://www.ebi.ac.uk/efo/EFO_0010851 | HG02852
http://www.ebi.ac.uk/efo/EFO_0010850 | HG02840
http://www.ebi.ac.uk/efo/EFO_0010849 | HG02798
http://www.ebi.ac.uk/efo/EFO_0010848 | HG02763
http://www.ebi.ac.uk/efo/EFO_0010847 | HG02759
http://www.ebi.ac.uk/efo/EFO_0010846 | HG02678
http://www.ebi.ac.uk/efo/EFO_0010845 | HG02642
http://www.ebi.ac.uk/efo/EFO_0010844 | HG02623
http://www.ebi.ac.uk/efo/EFO_0010843 | HG02610
http://www.ebi.ac.uk/efo/EFO_0010842 | HG02588
http://www.ebi.ac.uk/efo/EFO_0010841 | HG02571
http://www.ebi.ac.uk/efo/EFO_0010840 | GM21786
http://www.ebi.ac.uk/efo/EFO_0010839 | GM21737
http://www.ebi.ac.uk/efo/EFO_0010838 | GM21515
http://www.ebi.ac.uk/efo/EFO_0010837 | GM19043
http://www.ebi.ac.uk/efo/EFO_0010836 | GM19025
http://www.ebi.ac.uk/efo/EFO_0010835 | GM19023

**Comment by bonitalam** [comment]
Thanks so much @zoependlington!
