### ISSUE TITLE
femur fracture

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#88]
femur fracture is wrongly assigned to hip fracture as a synonym.
It should be it's own concept.

## Preferred term label

femur fracture

## Synonyms

Fracture of Femur

## X-refs

NCIT_C26774 
UMLS_CUI_C0015802

## Textual definition

A traumatic or pathologic injury to the femur in which the continuity of the femur is broken. [ NCI ]

## Suggested parent term

bone fracture

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
- [ ] Edit existing term:
EFO:0003964 hip fracture
remove alternate_term femur fracture

- [ ] New term:
EFO: femur fracture
Subclass of bone fracture
has_disease_location some (femur or (part_of some femur))
Def: A traumatic or pathologic injury to the femur in which the continuity of the femur is broken. [ NCI ]
NCI_Thesaurus_definition_citation: NCIT:C26774
Xref: UMLS_CUI_C0015802
Synonyms: Fracture of Femur

**Comment by zoependlington** [comment]
Here's the ID of the new term: EFO_0008553 | femur fracture
