### ISSUE TITLE
Additional xrefs for impetigo (EFO:1000714)

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#885]
As of v.3.23.0, http://www.ebi.ac.uk/efo/EFO_1000714 / impetigo xrefs:

- ICD10:L01
- DOID:8504

Would it be possible to add the following:

- icd9:684 https://icd.codes/icd9cm/684
- mesh:D007169 https://id.nlm.nih.gov/mesh/D007169.html
- snomedct:48277006 https://snomedbrowser.com/Codes/Details/48277006

I noticed these were missing when I was looking into Informa diseases that didn't map to EFO (we're doing this mapping via ICD9, ICD10, MeSH, and SNOMED-CT, with the later two being much more reliable in general.

Also, I'd be interested in learning how to add this contribution via a pull request. Is there anywhere that describes how I'd do that?

**Comment by zoependlington** [comment]
These have been added and will be available at our next release (16th November).

Due to our editing process, we prefer to be able to make the edits to the ontology ourselves and are happy to accept requests for additional x-refs through our ticket tracker. If you have a large number of x-refs you would like adding to EFO, we can do this through a ROBOT template - just get in touch with us if that is the case so we can set up the template for you. Ontology edit pull requests may be something we explore in the future.

**Comment by dhimmel** [comment]
Thanks! Closing since resolved by https://github.com/EBISPOT/efo/commit/156a0fdbffd6475cb70eeb43e555412faacc7d65

> Due to our editing process, we prefer to be able to make the edits to the ontology ourselves and are happy to accept requests for additional x-refs through our ticket tracker.

Got it! It was nice to see that the portion of the diff in https://github.com/EBISPOT/efo/commit/156a0fdbffd6475cb70eeb43e555412faacc7d65 that added the xrefs was simple:

```patch
diff --git a/src/ontology/efo-edit.owl b/src/ontology/efo-edit.owl
index 72ede24..15c80ff 100644
--- a/src/ontology/efo-edit.owl
+++ b/src/ontology/efo-edit.owl
@@ -255599,7 +255599,9 @@ New Label : Meningioma</efo:reason_for_obsolescence>
         <obo:IAO_0000115 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">A bacterial infectious process affecting any part of the urinary tract, most commonly the bladder and the urethra. Symptoms include urinary urgency and frequency, burning sensation during urination, lower abdominal discomfort, and cloudy urine.</obo:IAO_0000115>
         <obo:IAO_0000117 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Tomasz Adamusiak</obo:IAO_0000117>
         <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ICD10:O23</oboInOwl:hasDbXref>
+        <oboInOwl:hasDbXref>MESH:D014552</oboInOwl:hasDbXref>
         <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NCIt:C50791</oboInOwl:hasDbXref>
+        <oboInOwl:hasDbXref>SNOMEDCT:68566005</oboInOwl:hasDbXref>
         <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">INFECTION, URINARY TRACT</oboInOwl:hasExactSynonym>
         <oboInOwl:hasExactSynonym rdf:datatype="http://www.w3.org/2001/XMLSchema#string">TRACT, INFECTION OF URINARY</oboInOwl:hasExactSynonym>
         <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">urinary tract infection</rdfs:label>
@@ -546597,6 +546599,9 @@ Use: Orphanet_464 Label: Incontinentia pigmenti</efo:reason_for_obsolescence>
         <obo:IAO_0000117 rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Sirarat Sarntivijai</obo:IAO_0000117>
         <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">DOID:8504</oboInOwl:hasDbXref>
         <oboInOwl:hasDbXref rdf:datatype="http://www.w3.org/2001/XMLSchema#string">ICD10:L01</oboInOwl:hasDbXref>
+        <oboInOwl:hasDbXref>ICD9:684</oboInOwl:hasDbXref>
+        <oboInOwl:hasDbXref>MESH:D007169</oboInOwl:hasDbXref>
+        <oboInOwl:hasDbXref>SNOMEDCT:48277006</oboInOwl:hasDbXref>
         <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">impetigo</rdfs:label>
     </owl:Class>
     <owl:Axiom>
```

I am curious about the rest of the changes which seem to be reordering of lines and adoption of preferred formats / nomenclature. Is this something that the editing software automatically applies to a term whenever you make a change? Or are these changes that you explicitly decided to make along with the xrefs in this commit?

> If you have a large number of x-refs you would like adding to EFO, we can do this through a ROBOT template

Was not familiar with [ROBOT](http://robot.obolibrary.org/template.html). From a quick glance it seems like if I post a tabular format of missing xrefs (e.g. with one column for EFO term URI and a second for xrefs to add), then it should be easy to upload those into the OWL with ROBOT?
