### ISSUE TITLE
Additional xrefs for urinary tract infection, EFO:0003103

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#886]
Suggesting the following xrefs for http://www.ebi.ac.uk/efo/EFO_0003103:

- mesh:D014552 https://identifiers.org/mesh:D014552 Urinary Tract Infections
- snomedct:68566005 https://identifiers.org/snomedct:68566005 Urinary tract infectious disease (disorder)

**Comment by zoependlington** [comment]
These have been added and will be available at our next release (16th November)

**Comment by dhimmel** [comment]
Thanks! Closing since resolved by https://github.com/EBISPOT/efo/commit/156a0fdbffd6475cb70eeb43e555412faacc7d65

**Comment by zoependlington** [comment]
@dhimmel, I'm reopening this ticket as we close the tickets ourselves after review at our scrum meetings.
