### ISSUE TITLE
New term request for Yuan PMID 32805626

### ISSUE THREAD

**Issue by JalMacArthur** [EBISPOT/efo#888]
For new term requests, please provide the following information:

## Preferred term label
Tumor necrosis factor measurement

## Synonyms
TNF measurement

## Textual definition
The determination of the amount of tumor necrosis factor present in a sample.

## Suggested parent term
Blood protein measurement http://www.ebi.ac.uk/efo/EFO_0007937

## Attribution
Jacqueline MacArthur

**Comment by zoependlington** [comment]
tumor necrosis factor measurement || http://www.ebi.ac.uk/efo/EFO_0010834

This term has been added to EFO and will be available after our EFO release on 16th November.
