### ISSUE TITLE
Import missing MONDO ids used by ClinGen to EFO

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#889]
Hello, 

We have identified 33 MONDO terms in ClinGen's data that we cannot map with any EFO term, neither directly nor as xrefs of current terms. Would you be so kind to incorporate them? [unmapped_clingen_2011.txt](https://github.com/EBISPOT/efo/files/5525526/unmapped_clingen_2011.txt)

Thanks!

**Comment by zoependlington** [comment]
Hi @ireneisdoomed,

I will import these terms into EFO as soon as possible so they should be available at our next release (16th November).

Zoë

**Comment by ireneisdoomed** [comment]
That's perfect. Thank you very much!

Let me know if you need anything.

**Comment by zoependlington** [comment]
All of these terms should now be in EFO and available after the release on the 16th! Please let me know if there are any issues.
