### ISSUE TITLE
New term request for Folkersen PMID 33067605

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#892]
Measurement terms listed in the webulous form below:

https://docs.google.com/spreadsheets/d/1S_JbK4YEdfQIgDDB_5IiZ0Qy4_633Mf8w3_LWKtKBBM/edit#gid=278821001

**Comment by zoependlington** [comment]
Here are the IDs for the new terms, they will be available at our next release (15th):

http://www.ebi.ac.uk/efo/EFO_0010932 | 'urokinase plasminogen activator surface receptor measurement' | EFO | zoe | 2020-12-09 11:45:02
http://www.ebi.ac.uk/efo/EFO_0010931 | 'tumor necrosis factor receptor 1 measurement' | EFO | zoe | 2020-12-09 11:45:01
http://www.ebi.ac.uk/efo/EFO_0010930 | 'TNF-related apoptosis-inducing ligand receptor 2 measurement' | EFO | zoe | 2020-12-09 11:45:01
http://www.ebi.ac.uk/efo/EFO_0010929 | 'TNF-related activation-induced cytokine measurement' | EFO | zoe | 2020-12-09 11:45:01
http://www.ebi.ac.uk/efo/EFO_0010928 | 'SIR2-like protein 2 measurement' | EFO | zoe | 2020-12-09 11:45:01
http://www.ebi.ac.uk/efo/EFO_0010927 | 'proto-oncogene tyrosine-protein kinase Src measurement' | EFO | zoe | 2020-12-09 11:45:01
http://www.ebi.ac.uk/efo/EFO_0010926 | 'proteinase-activated receptor 1 measurement' | EFO | zoe | 2020-12-09 11:45:00
http://www.ebi.ac.uk/efo/EFO_0010925 | 'protein S100-A12 measurement' | EFO | zoe | 2020-12-09 11:45:00
http://www.ebi.ac.uk/efo/EFO_0010924 | 'proheparin-binding EGF-like growth factor measurement' | EFO | zoe | 2020-12-09 11:45:00
http://www.ebi.ac.uk/efo/EFO_0010923 | 'pentraxin-related protein PTX3 measurement' | EFO | zoe | 2020-12-09 11:44:59
http://www.ebi.ac.uk/efo/EFO_0010922 | 'P-selectin glycoprotein ligand 1 measurement' | EFO | zoe | 2020-12-09 11:44:59
http://www.ebi.ac.uk/efo/EFO_0010921 | 'N-terminal prohormone brain natriuretic peptide measurement' | EFO | zoe | 2020-12-09 11:44:59
http://www.ebi.ac.uk/efo/EFO_0010920 | 'membrane-bound aminopeptidase P measurement' | EFO | zoe | 2020-12-09 11:44:58
http://www.ebi.ac.uk/efo/EFO_0010919 | 'melusin measurement' | EFO | zoe | 2020-12-09 11:44:58
http://www.ebi.ac.uk/efo/EFO_0010918 | 'lectin-like oxidized LDL receptor 1 measurement' | EFO | zoe | 2020-12-09 11:44:58
http://www.ebi.ac.uk/efo/EFO_0010917 | 'kidney injury molecule 1 measurement' | EFO | zoe | 2020-12-09 11:44:58
http://www.ebi.ac.uk/efo/EFO_0010916 | 'interleukin-27 measurement' | EFO | zoe | 2020-12-09 11:44:57
http://www.ebi.ac.uk/efo/EFO_0010915 | 'heat shock 27 kDa protein measurement' | EFO | zoe | 2020-12-09 11:44:57
http://www.ebi.ac.uk/efo/EFO_0010914 | 'fatty acid-binding protein, adipocyte measurement' | EFO | zoe | 2020-12-09 11:44:57
http://www.ebi.ac.uk/efo/EFO_0010913 | 'eosinophil cationic protein measurement' | EFO | zoe | 2020-12-09 11:44:57
http://www.ebi.ac.uk/efo/EFO_0010912 | 'endothelial cell-specific molecule 1 measurement' | EFO | zoe | 2020-12-09 11:44:56
http://www.ebi.ac.uk/efo/EFO_0010911 | 'C-X-C motif chemokine 16 measurement' | EFO | zoe | 2020-12-09 11:44:56
http://www.ebi.ac.uk/efo/EFO_0010910 | 'C-C motif chemokine 20 measurement' | EFO | zoe | 2020-12-09 11:44:56
http://www.ebi.ac.uk/efo/EFO_0010909 | 'adrenomedullin measurement' | EFO | zoe | 2020-12-09 11:44:56
