### ISSUE TITLE
NTR: cytokine secretion assay

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#893]
From https://github.com/HumanCellAtlas/ontology/issues/69

## Preferred term label
cytokine secretion assay

## Synonyms
pan-cytokeratin staining

## Textual definition
A protein assay measuring the types and amounts of cytokines that are released as the consequence of a signaling event. Cytokines can be quantitated using e.g. ELISA-based kits or PCR arrays.

Dbxref BAO:0003003 cytokine secretion assay

## Suggested parent term
subclass of EFO:0001458 protein assay

## Attribution
https://orcid.org/0000-0002-7431-4139

**Comment by rachadele** [comment]
https://orcid.org/0000-0002-7431-4139

**Comment by paolaroncaglia** [comment]
@rachadele 
The term you requested is now in EFO as EFO:0010935 'cytokine secretion assay'.
It will be visible in the EFO release scheduled for tomorrow, and will be included in the HCAO release scheduled for Jan 21st. 
(We last released HCAO on Dec 3rd, and we won't do another one in December due to the holidays, but going forward we plan to do regular HCAO releases around the 18th-21st of each month, see point 6) in the [minutes of the Dec 9th meeting](https://docs.google.com/document/d/1PXLco-VtpRIFA1DuDDafxqQl2PSW2ZZMG82qA_-1xIE/edit#heading=h.pmazbh81wixz)).
