### ISSUE TITLE
Import missing MONDO ids used by Genomics England to EFO

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#894]
Hello,

We have identified 93 terms in Genomics England's data that we cannot map with any EFO term. Except one obsolete EFO term, the rest are coming from Orphanet. As discussed, the majority of them have been cross-referenced with MONDO terms, currently not available in EFO. Would you be so kind to incorporate them?

Some of these terms have been tagged as `no mapping` since we've not found any correspondent MONDO term. They can be found at the end of the attached document so that their inclusion can be assessed. 
[unmapped_PanelApp_2011.csv.gz](https://github.com/EBISPOT/efo/files/5589921/unmapped_PanelApp_2011.csv.gz)

We've also found some cases where the phenotype indicated at source is present for the Orphanet term but not for the MONDO ID. It would be great if these could be potentially imported as a synonym in EFO. Here's the list:

Disease ID | Source Phenotype | MONDO Term
-- | -- | --
http://www.orpha.net/ORDO/Orphanet_528105 | "HELIX syndrome" | http://purl.obolibrary.org/obo/MONDO_0033939
http://www.orpha.net/ORDO/Orphanet_536471 | "Spondylodysplastic EDS" | http://purl.obolibrary.org/obo/MONDO_0034021
http://www.orpha.net/ORDO/Orphanet_536516 | "Myopathic EDS" | http://purl.obolibrary.org/obo/MONDO_0034022
http://www.orpha.net/ORDO/Orphanet_536545 | "Kyphoscoliotic EDS", "EDS VI" | http://purl.obolibrary.org/obo/MONDO_0034024
http://www.orpha.net/ORDO/Orphanet_566231 | "Resistance to thyroid hormone alpha" | http://purl.obolibrary.org/obo/MONDO_0034216

Thanks!

**Comment by zoependlington** [comment]
@ireneisdoomed I have imported the MONDO term (and the one HP term) you requested from your spreadsheet.

As for the unmapped terms:

The following is a potential mapping that I can import into EFO if it seems okay to you:
http://www.orpha.net/ORDO/Orphanet_123322 | "renal amyloidosis" | http://purl.obolibrary.org/obo/HP_0001917

http://www.orpha.net/ORDO/Orphanet_157855 | "HARP syndrome" exists as a synonym for http://www.orpha.net/ORDO/Orphanet_808 which is also mapped to http://purl.obolibrary.org/obo/MONDO_0019342 and is already in EFO.

As for the remaining "gene with protein product" terms, we do not currently have a good branch that these could fit into so I will investigate the best way to add these terms into EFO - can I request that you open a new ticket with these terms as you require them please? If you can make a copy of [this template](https://docs.google.com/spreadsheets/d/1qfxB9aUlMcglX3iqkcpozuDKIEnleE_Cn31UQ3kiBxs/edit?usp=sharing) and include as much information as possible in the spreadsheet, that would be greatly appreciated.

As for the inclusion of new synonyms to Mondo terms - I unfortunately am not able to do this, but you can request these on the [Mondo tracker](https://github.com/monarch-initiative/mondo/issues). Then, once Mondo have done a release, I will be able to import them into EFO.

Thank you.

**Comment by ireneisdoomed** [comment]
@zoependlington Thank you very much for the indications, I am opening a ticket to consider the `gene with protein product` terms and another to MONDO.

As for `Orphanet_123322 ` the inclusion of `HP_0001917` seems fair, thank you.

**Comment by zoependlington** [comment]
I double checked and I misread - the synonym is for Harper’s syndrome. Orphanet_157855 is deprecated in Orphanet now with the replacement of Orphanet:216866 which is mapped to MONDO:0016304 which can be imported into EFO.

To do:
Double check there is no outstanding EFO term that can be mapped to this Mondo term, if not then import.

**Comment by zoependlington** [comment]
I can confirm that MONDO:0016304 is mapped to Orphanet_216866, which is already in EFO. 

I have also imported http://purl.obolibrary.org/obo/HP_0001917 into EFO.
