### ISSUE TITLE
Include missing synonyms used by Genomics England to EFO terms

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#895]
Hello,

We have identified 9 terms in Genomics England's data that we could not programmatically map with any EFO term. Although these terms exist, EFO is not listing them as synonyms. Would you be so kind to see if they are potentially susceptible of being incorporated? 
[synonyms_panelapp_2011.csv.gz](https://github.com/EBISPOT/efo/files/5589968/synonyms_panelapp_2011.csv.gz)

Thanks!

**Comment by zoependlington** [comment]
I have added the synonyms for EFO and Orphanet terms (as we do not currently dynamically import Orphanet into EFO), however I am unable to add the synonyms to the Mondo terms. You can request synonyms for Mondo terms on the [Mondo tracker](https://github.com/monarch-initiative/mondo/issues), which will then be imported into EFO after a Mondo release containing the changes.
