### ISSUE TITLE
UniProtKB 2021_01 release EFO mappings 

### ISSUE THREAD

**Issue by Antonialock** [EBISPOT/efo#896]
Hi  @zoependlington 

We need another batch of EFO terms.

I made a spreadsheet with MONDO mappings where possible:
https://docs.google.com/spreadsheets/d/1SMXDRC0Qmv0ji98B90f7ntvGlte96yMgpY3on3SIgqg/edit#gid=0

I also opened a ticket for new MONDO IDs as required:
https://github.com/monarch-initiative/mondo/issues/2362

Thanks!

**Comment by zoependlington** [comment]
I have imported all Mondo terms and they will be available in the upcoming release on Monday (18th).

I believe they're still missing the DI x-refs, but I will chat to the Mondo team about including these.
