### ISSUE TITLE
[sensory perception of sweet taste] missing from EFO

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#898]
This term should have been imported from GO (GO:0050916) last year.  It was available in the GWAS Catalog curation interface, used in Hwang PMID:31005972, and published.
A gwas-info has highlighted that the EFO term/URI are blank e.g. GCST008769.
It doesn't not appear to be in EFO (under parent https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0050909&viewMode=All&siblings=false)

For new term requests, please provide the following information:

## Preferred term label

sensory perception of sweet taste

## Synonyms

sensory perception of sweetness
sweet taste perception
sweet taste sensitivity

## Textual definition
The series of events required to receive a sweet taste stimulus, convert it to a molecular signal, and recognize and characterize the signal. This is a neurological process.

## Suggested parent term

sensory perception of taste
http://purl.obolibrary.org/obo/GO_0050909

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
This term (GO:0050916) has been added and will be available at our next release (15th December).

**Comment by aoifemcm** [comment]
Thanks Zoe,
I assume I don't need to do anything to the publication that is already published and uses this term?

**Comment by zoependlington** [comment]
I don't think so, it has the exact same ID as the interface, so all should be well.
