### ISSUE TITLE
New terms request for Butler-Laporte G-PMID 33204752 

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#899]
For new term requests, please provide the following information:

https://docs.google.com/spreadsheets/d/1IQ-9uEfldxQfIUjkRo-lun_Dw6anACYePVig0RiLK6U/edit#gid=1909577919

**Comment by zoependlington** [comment]
Here are the IDs for the new terms, they will be available after our next release (15th December):
http://www.ebi.ac.uk/efo/EFO_0010908 | Epstein-Barr virus seropositivity | EFO | zoe | 2020-12-09 09:01:17
http://www.ebi.ac.uk/efo/EFO_0010907 | polyomavirus 2 seropositivity | EFO | zoe | 2020-12-09 09:00:16
http://www.ebi.ac.uk/efo/EFO_0010906 | merkel cell virus seropositivity | EFO | zoe | 2020-12-09 08:59:14
http://www.ebi.ac.uk/efo/EFO_0010905 | BK polyomavirus seropositivity | EFO | zoe | 2020-12-09 08:57:53
http://www.ebi.ac.uk/efo/EFO_0010904 | anti-BK polyomavirus antibody measurement | EFO | zoe | 2020-12-09 08:56:03
http://www.ebi.ac.uk/efo/EFO_0010903 | anti-chlamydia trachomatis antibody measurement | EFO | zoe | 2020-12-09 08:55:12
http://www.ebi.ac.uk/efo/EFO_0010902 | anti-herpes simplex virus 7 antibody measurement | EFO | zoe | 2020-12-09 08:53:54
http://www.ebi.ac.uk/efo/EFO_0010901 | anti-herpes simplex virus 6 antibody measurement | EFO | zoe | 2020-12-09 08:52:53
http://www.ebi.ac.uk/efo/EFO_0010900 | anti-polyomavirus 2 antibody measurement | EFO | zoe | 2020-12-09 08:51:50
http://www.ebi.ac.uk/efo/EFO_0010899 | anti-merkel cell virus antibody measurement | EFO | zoe | 2020-12-09 08:50:26
