### ISSUE TITLE
Generate disease-prevalence statement

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#9]
Hi SIra

I'm interested in having this data available but it may be of EBI-wide interest particularly for EVA.

The use case is as follows:

Given a mutation that is reported for a disease, what are the odds that this is not a chance observation. If you know the incidence of the disease, and the occurrence of the mutation in a randomly sampled set of exon sequence e.g. the EXAC database, you can calculate a probability of the observation occurring by chance. We could use thisin our scoring in Open targets, but would also be of general interest I think.

Cheers

Ian

**Comment by simonjupp** [comment]
Simon  will follow up with Ian on this ticket

**Comment by paolaroncaglia** [comment]
@d0choa
Zoe and I are reviewing our backlog. Do you think this ticket is still relevant, please? It wouldn't be for wider distribution, but just so we know if we should keep it in the Backlog or not. Thanks.

**Comment by d0choa** [comment]
It's a very fundamental research question with plenty of ramifications. I believe it's outside the scope of EFO.

**Comment by paolaroncaglia** [comment]
Thanks @d0choa . I'll move this ticket to Done then.
