### ISSUE TITLE
Potential duplicates between ontologies

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#900]
Good morning,

when analysing some discrepancies between the manual mapping of indications made by ChEMBL and ours, systematically done, we have found some potential terms that can be duplicates.

For a number of the cases we've appreciated that we systematically map to a MONDO or HP term when there's an equivalent EFO term. In these cases the indication, the queried term, is in MONDO as an exact or related synonym, hence the exact match.

Here is a table with the 16 records. 
[potential_duplicates.csv.gz](https://github.com/EBISPOT/efo/files/5629569/potential_duplicates.csv.gz)

There is a particular case between two terms coming from EFO, EFO:1000869 and EFO:0008507 are very similar in terms of their description.

We would be very thankful if you could review these cases.

**Comment by ireneisdoomed** [comment]
Hi @zoependlington, I was wondering if you have had a chance to look over these cases. This issue is correlated with the more thorough analysis described in #925, so it may be useful to analyse them altogether.
Please let me know if you have any questions or comments about it. Happy to help.

**Comment by zoependlington** [comment]
Hi @ireneisdoomed! I haven't had a chance to look through all of these yet, but they're on my list to do before the EFO release  on the 18th January.

I will let you know if I run into any problems!

**Comment by zoependlington** [comment]
Apologies for the delay on this ticket @ireneisdoomed. I have created a review document [here](https://docs.google.com/spreadsheets/d/16hAlYerZgPBvXJxCHmQP4J_XRbgYeqIVu58GJVdfA2Y/edit?usp=sharing) so you can view whether these terms are in fact duplicates.
