### ISSUE TITLE
Wrong synonym for EFO:0000702 

### ISSUE THREAD

**Issue by ireneisdoomed** [EBISPOT/efo#901]
Good morning,

We've come across this term `Carcinoma, Small Cell` which is pointing to [EFO:0000702](http://www.ebi.ac.uk/efo/EFO_0000702), because it’s an exact synonym, when [EFO:0008524](http://www.ebi.ac.uk/efo/EFO_0008524) seems to be more accurate and specific.

We kindly ask to review this case and, if applicable, please swap the synonym between both terms.

Thank you.

**Comment by zoependlington** [comment]
Thank you, @ireneisdoomed, I have removed the incorrect synonyms. This will be available at our next release (15th December).
