### ISSUE TITLE
Look into cancer branch GWAS issue

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#902]
Issue with EFO_0009260 stemming from https://github.com/EBISPOT/gwas-user-requests/issues/4

**Comment by smlmbrt** [comment]
Just wanted to re-up the request from `#trait_efo` to look into the skin cancer/carcinoma branch of EFO. My example: ALL squamous cell carcinomas [(EFO:0000707)](http://www.ebi.ac.uk/efo/EFO_0000707) are being labeled as skin cancers in EFO, but some of these will likely be errors. One such example is ovarian squamous cell carcinoma ([EFO:1000432](http://www.ebi.ac.uk/efo/EFO_1000432)) which shouldn't be a child skin cancer/carcinoma. The parentage of the ovarian SCC term and other SCCs are correct in MONDO ([MONDO:0003494](http://purl.obolibrary.org/obo/MONDO_0003494)).

**Comment by aoifemcm** [comment]
@zoependlington @smlmbrt 
Another re-up for this request. I've just mapped another GWAS study to a non-skin squamous cell carcinoma (lung in this case); this study will be affected by the error in the cancer branch.

https://www.ebi.ac.uk/gwas/curation/studies/63073635
PMID 32889700

**Comment by zoependlington** [comment]
Apologies for the delay in this ticket, we have been working on the cancer branch rewrite which has been a far larger task and has taken more time than initially planned. However, this issue should be rectified in our August (16th) release.

**Comment by smlmbrt** [comment]
Thanks for taking it on, I'm sure it was a big undertaking but I'm sure it will be an even bigger improvement! Will a lot of terms become obsolete or get renamed in the release? I guess I should double-check any cancer terms that I've mapped to before to make sure they're still the best ones?

**Comment by zoependlington** [comment]
There may be some renaming, loss or gain of synonyms, changes in x-refs and the hierarchy in general - the pipeline is not 100% complete so I can't give you definite answers here, but I would expect a lot of changes. The IDs for terms will remain the same, so there should be no loss of terms entirely. So far I have only obsoleted one term but there is a replacement term in place. It's the first step to improvement so if there are any issues that you see with the new branch next week please do get in touch and I'll prioritise them. :-)

**Comment by smlmbrt** [comment]
@zoependlington, I took a look at the updated ontology (3.33.0) on OLS and I think the following two examples still persist as children of skin cancer "A carcinoma that arises from epithelial cells of the zone of skin":
> ALL squamous cell carcinomas [(EFO:0000707)](http://www.ebi.ac.uk/efo/EFO_0000707) are being labeled as skin cancers in EFO, but some of these will likely be errors. One such example is ovarian squamous cell carcinoma ([EFO:1000432](http://www.ebi.ac.uk/efo/EFO_1000432)) which shouldn't be a child skin cancer/carcinoma. The parentage of the ovarian SCC term and other SCCs are correct in MONDO ([MONDO:0003494](http://purl.obolibrary.org/obo/MONDO_0003494)).

> squamous cell lung carcinoma [(EFO_0000708)](http://www.ebi.ac.uk/efo/EFO_0000708)

**Comment by smlmbrt** [comment]
@zoependlington, I took a look at the updated ontology (3.33.0) on OLS and I think the following two examples still persist as children of skin cancer :
> ALL squamous cell carcinomas [(EFO:0000707)](http://www.ebi.ac.uk/efo/EFO_0000707) are being labeled as skin cancers in EFO, but some of these will likely be errors. One such example is ovarian squamous cell carcinoma ([EFO:1000432](http://www.ebi.ac.uk/efo/EFO_1000432)) which shouldn't be a child skin cancer/carcinoma. The parentage of the ovarian SCC term and other SCCs are correct in MONDO ([MONDO:0003494](http://purl.obolibrary.org/obo/MONDO_0003494)).

> squamous cell lung carcinoma [(EFO_0000708)](http://www.ebi.ac.uk/efo/EFO_0000708)

**Comment by zoependlington** [comment]
Thanks for checking @smlmbrt, I'll double check why this is the case - may be an inheritance from Mondo due to the old EFO hierarchy.

**Comment by zoependlington** [comment]
I have checked both ovarian squamous cell carcinoma and squamous cell lung carcinoma and neither are children or descendants of skin cancer or skin carcinoma in my local version of EFO, so not sure why this is still the case in OLS...

![image](https://user-images.githubusercontent.com/36990116/130599316-e15526c4-2717-460d-9148-60276f98cd2d.png)

**Comment by zoependlington** [comment]
This seems to be an OLS issue as the problem is rectified in EFO. Moving to done.
