### ISSUE TITLE
New ontology term request (dilated left atrium)

### ISSUE THREAD

**Issue by Ananth-Prakash** [EBISPOT/efo#904]
## Preferred term label

dilated left atrium

## Synonyms

enlarged left atrium, left atrial enlargement, left atrial dilation

## Textual definition

Left atrial enlargement (LAE) or left atrial dilation refers to enlargement of the left atrium (LA) of the heart, and is a form of cardiomegaly.

http://europepmc.org/article/MED/32291283#id707398
https://en.wikipedia.org/wiki/Left_atrial_enlargement

## Suggested parent term

cardiomyopathy
http://www.ebi.ac.uk/efo/EFO_0000318 

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
@zoependlington this HP term may be appropriate: http://purl.obolibrary.org/obo/HP_0031295

**Comment by zoependlington** [comment]
HP_0031295 has been imported into EFO.
