### ISSUE TITLE
New term request: Comparative Genomic Hybridization (CGH)

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#909]
## Preferred term label

Comparative Genomic Hybridization (CGH)

## Synonyms

chromosomal Comparative Genomic Hybridization

## Textual definition

Comparative Genomic Hybridization is an _in-situ hybridization_ method for the analysis of regional genomic copy number imbalances (CNA / CNV), based on the hybridization of test (e.g. tumor) and reference DNA to chromosomal metaphase preparations from healthy donors. 

## Suggested parent term

* in-situ hybridization assay
    - <http://purl.obolibrary.org/obo/OBI_0001686>
* DNA assay
    - <http://www.ebi.ac.uk/efo/EFO_0001456>

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
Thanks @mbaudis ,

I'll add the new assay term as suggested, and will confirm when it's ready. Same for your other two assay requests.

Best wishes,

Paola

**Comment by mbaudis** [comment]
@paolaroncaglia Thank you for the fast work!

**Comment by paolaroncaglia** [comment]
@mbaudis 
Your requested term is now in EFO as EFO:0010937 'comparative genomic hybridization (CGH)'.
It will be available in tomorrow's EFO release (add 1-2 days for OLS).
Thanks,
Paola

**Comment by mbaudis** [comment]
👏
