### ISSUE TITLE
New Term Request: Large-Insert Clone DNA Microarray

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#910]
## Preferred term label

Large-Insert Clone DNA Microarray

## Synonyms

spotted DNA microarray

## Textual definition

Large-Insert Clone DNA Microarrays consist of usually several thousands of spots of DNA from bacterial artificial chromosome (BAC) and P1 artificial chromosome (PAC) clones. The main application of those arrays is for array Comparative Genomic Hybridization (aCGH) experiments.

## Suggested parent term

* DNA array
    - <http://www.ebi.ac.uk/efo/EFO_0002701>

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
@mbaudis 
This is EFO:0010938 'comparative genomic hybridization (CGH)'.

**Comment by mbaudis** [comment]
👏 (but I think you meant EFO:0010937 for CGH; ..38 is the next one  - large insert clone ... :-)

**Comment by paolaroncaglia** [comment]
@mbaudis 

> 👏 (but I think you meant EFO:0010937 for CGH; ..38 is this one one - large insert clone ... Look good in the commit :-)

Yes indeed :-) Thanks.
Paola
