### ISSUE TITLE
New Term Request: Oligonucleotide DNA Microarray

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#911]
## Preferred term label

Oligonucleotide DNA Microarray

## Textual definition

Oligonucleotide DNA Microarrays consist of usually thousands to many hundreds of thousands spots of 
DNA oligonucleotides (25- to 60 bases) which have been created by either _in situ_ synthesis or deposition of presynthesized oligonucleotides on a carrier substrate. Applications for those arrays are in the detection of copy number variations or small structural changes as well as in genotyping (if oligonucleotides have been designed for SNP detection).

## Suggested parent term

* DNA array
    - <http://www.ebi.ac.uk/efo/EFO_0002701>

## Child term

* SNP array
  - http://www.ebi.ac.uk/efo/EFO_0002703

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
@mbaudis 
Lastly, this is EFO:0010939 'oligonucleotide DNA microarray'.
Best wishes,
Paola

**Comment by mbaudis** [comment]
👏
