### ISSUE TITLE
Consider replacing EFO:0009462 'granuloma' with HP:0032252 'Granuloma'

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#913]
EFO:0009462 'granuloma' is in the 'pathological process' branch, but the term may fit better as a phenotype as currently in HP.
Diseases characterized by granulomas, instead, exist in the EFO disease branch, and their placement is confirmed by Mondo entries.

**Comment by zoependlington** [comment]
EFO:0009462 'granuloma' now replaced with HP:0032252 'Granuloma'
