### ISSUE TITLE
Use of wrong RO relations

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#916]
Hey @zoependlington 

I am on a mission to harmonize relation usage across all ontologies:
https://github.com/orgs/OBOFoundry/projects/5

http://purl.org/obo/owl/OBO_REL#role_of
or
http://purl.org/obo/owl/OBO_REL#bearer_of
or
http://www.obofoundry.org/ro/ro.owl#derived_into
or
http://www.obofoundry.org/ro/ro.owl#contained_in

These should be normalised to their respective RO ids..

If you want, we can schedule a meeting in the new year and do it together - will take us both less than an hour to fix all of these!

**Comment by zoependlington** [comment]
This sounds great, I'll contact you to organise a meeting in January.

**Comment by matentzn** [comment]
- [ ] http://www.obofoundry.org/ro/ro.owl#has_participant
- [X] http://purl.org/obo/owl/OBO_REL#role_of
- [X] http://purl.org/obo/owl/OBO_REL#bearer_of
- [ ] http://www.obofoundry.org/ro/ro.owl#derived_into
- [ ] http://www.obofoundry.org/ro/ro.owl#contained_in
