### ISSUE TITLE
New Term Request: "metastasis sample"

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#917]
## Preferred term label

* metastasis sample

## Synonyms

metastasis

## Textual definition

* a biosample material derived from a cancer metastasis (**not** a primary tumor)

## Suggested parent term

* [EFO:0009656](http://www.ebi.ac.uk/efo/EFO_0009656) neoplastic sample

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
Quick notes for self/editor:
- [ ] Consider the existing comment on the proposed EFO parent term;
- [ ] 'metastasis' already exists as EFO:0009708, so it shouldn't be an _exact_ synonym of the proposed new term.

**Comment by mbaudis** [comment]
@paolaroncaglia @zoependlington So everything should be good. As the mentioned `metastasis` declares:

    “metastasis” refers to the process of cancer cell migration, not to the tumor mass itself

And the proposed terms neither describe a histology, anatomy ... diagnosis etc. but a derived property of the material.
Descriptions could be amended in that those should not be used in a disease description context etc.

**Comment by mbaudis** [comment]
@paolaroncaglia +1 - and Happy New Year!

**Comment by paolaroncaglia** [comment]
@mbaudis 
'metastasis sample' was added as EFO_0010941 and will be available in the next EFO release (scheduled for Jan 18th). Thanks.
