### ISSUE TITLE
New Term Request: primary tumor sample

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#918]
## Preferred term label

* primary tumor sample

## Synonyms

* primary tumor
* primary neoplasia

## Textual definition

* a biosample material derived from a primary tumor (**not** a metastasis)
* the tumor itself can be _metastasized_, e.g. have distant metastases; however, this is not considered part of the material attribute itself

## Suggested parent term

* [EFO:0009656](http://www.ebi.ac.uk/efo/EFO_0009656) neoplastic sample

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
Notes for self/editor: wrt parent, see my comment in #917 ; wrt synonyms, they should be related, not exact.

**Comment by paolaroncaglia** [comment]
@mbaudis I will 

- [ ] Add EFO:NEW primary tumor sample
subclass of EFO:0009656 neoplastic sample
A neoplastic sample derived from a primary tumor (not from a cancer metastasis).
dbxref http://orcid.org/0000-0002-9903-4248
alternative_term primary tumour sample, primary neoplasia sample
has_related_synonym primary tumor, primary tumour, primary neoplasia
refs:comment This term is meant to describe a material sample, and should not be used for disease or disease stage/grade. The tumor that the sample derives from may be metastasized, i.e. have distant metastases, however those should not be considered part of the material attribute itself.

**Comment by mbaudis** [comment]
@paolaroncaglia +1 !

**Comment by paolaroncaglia** [comment]
@mbaudis 
'primary tumor sample' is EFO_0010942.
