### ISSUE TITLE
New Term Request: recurrent tumor sample

### ISSUE THREAD

**Issue by mbaudis** [EBISPOT/efo#919]
## Preferred term label

* recurrent tumor sample

## Synonyms

* recurrent tumor
* recurrent neoplasia
* relapsed cancer

## Textual definition

* a biosample material derived from a recurrent tumor (**not** a primary occurrence)
* the definition of what is considered a recurrence stays with the submitter

## Suggested parent term

* [EFO:0009656](http://www.ebi.ac.uk/efo/EFO_0009656) neoplastic sample

## Attribution

* @mbaudis
* 0000-0002-9903-4248

**Comment by paolaroncaglia** [comment]
See my comments in #917 and #918 .

**Comment by paolaroncaglia** [comment]
@mbaudis I will 

- [ ] Add EFO:NEW recurrent tumor sample
subclass of EFO:0009656 neoplastic sample
A neoplastic sample derived from a recurrent tumor (not from a primary occurrence of a neoplasm).
dbxref http://orcid.org/0000-0002-9903-4248
alternative_term recurrent tumour sample
has_related_synonym recurrent tumor, recurrent tumour, recurrent neoplasia, relapsed cancer
refs:comment This term is meant to describe a material sample, and should not be used for disease or disease stage/grade.

**Comment by mbaudis** [comment]
@paolaroncaglia +1 !

**Comment by paolaroncaglia** [comment]
@mbaudis 
Lastly, 'recurrent tumor sample' is EFO_0010943. All terms will be visible in OLS around mid-next week.
Best wishes,
Paola
