### ISSUE TITLE
efo_otar_profile.owl contains subClassOf obsolete term (EFO:0004264, obsolete_Postthrombotic Syndrome)

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#927]
`efo_otar_profile.owl` from [v3.25.0](https://github.com/EBISPOT/efo/releases/tag/v3.25.0) contains a rdfs:subClassOf relationship from an obsolete node:

efo_uri | child_efo_id | child_efo_uri | efo_id
-- | -- | -- | --
http://www.ebi.ac.uk/efo/EFO_0004264 | EFO:1001405 | http://www.ebi.ac.uk/efo/EFO_1001405 | EFO:0004264

The row above is a subset of the output of the SPARQL query:

```sparql
# find subClassOf relationships
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT *
WHERE {
  ?efo_uri rdf:type owl:Class.
  FILTER(!isBlank(?efo_uri))
  BIND( REPLACE( STR(?efo_uri), "^http.+/([^:]+)_(.+)$", "$1:$2" ) AS ?efo_id )
  ?child_efo_uri rdfs:subClassOf ?efo_uri .
  FILTER(!isBlank(?child_efo_uri))
  BIND( REPLACE( STR(?child_efo_uri), "^http.+/([^:]+)_(.+)$", "$1:$2" ) AS ?child_efo_id )
}
ORDER BY ?efo_id ?child_efo_id
```

`EFO:1001405` is labeled "obsolete_Postthrombotic Syndrome". The regular `efo.owl` does not contain any `rdfs:subClassOf` triples for obsolete nodes, so I'm guessing this is an OpenTargets addition? Nothing https://github.com/EBISPOT/efo/issues/926 for documenting how efo differs from efo_otar_profile.

Is this okay or something that should be fixed? We're interested in converting EFO-OTAR to a [nxontology](https://github.com/related-sciences/nxontology) (networkx Python representation of the directed acyclic graph using rdfs:subClassOf). But we don't include obsolete terms as nodes, so adding the edge failed.

**Comment by zoependlington** [comment]
The Open Targets slim and profile files contain some forced parentage, and this is a forced subclass relationship that will be updated/removed in the January release (18th), thank you for spotting this! I have also implemented QC checks for the slim/profile to avoid this happening in the future.

**Comment by dhimmel** [comment]
Thanks @zoependlington as always for the help!

> The Open Targets slim and profile files contain some forced parentage, and this is a forced subclass relationship that will be updated/removed in the January release

Ah that makes sense. Where are theses forced parentage relationships defined? Is the source for them in this repository? This could help with #926 (understanding the difference between EFO and EFO-OTAR).

> I have also implemented QC checks for the slim/profile to avoid this happening in the future.

Is there a commit or set of commits that apply these QC checks?

**Comment by zoependlington** [comment]
The forced relationships are defined in the subclasses templates file found in the OTAR_profiler here: https://github.com/EBISPOT/otar_profiler

Just a note that the "final" version for use by Open Targets is the slim file, which only contains the therapeutic areas that are useful for annotating their data. The profile is our master EFO with a few extra terms, which will eventually be added to the master EFO file once we have completed the ongoing work with our profile and slim files to be compatible with the Open Targets pipelines and their needs.

The QC checks can be found in the sparql directory.
