### ISSUE TITLE
Trigeminal Nerve Disorder

### ISSUE THREAD

**Issue by gkos-bio** [EBISPOT/efo#93]
## Preferred term label

facial nerve disease
trigeminal nerve disorder
facial neuralgia

### trigeminal nerve disorder
Disorders of trigeminal nerve
trigeminal nerve disease
Cranial Nerve V Diseases
Fifth Cranial Nerve Diseases
Raeder Paratrigeminal Syndrome
Trigeminal Nerve Disorders
Trigeminal Neuropathy
Trigeminal Neuropathy, Idiopathic

### trigeminal nerve disorder
A non-neoplastic or neoplastic disorder affecting the trigeminal nerve (fifth cranial nerve). [ NCI ]

### trigeminal nerve disorder
NCIT:C26952
UMLS_CUI:C0152177
MESH:D020433
ICD9:350.8
ICD10:G50

## Suggested parent term

facial neuralgia => facial nerve disease
trigeminal nerve disorder => facial neuralgia
trigeminal neuralgia => trigeminal nerve disorder
trigeminal nerve neoplasm => trigeminal nerve disorder

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @gkos-bio ,

This request may have been addressed by the integration with MONDO. In fact, in EFO 3,

‘trigeminal nerve disorder’ is an exact synonym for MONDO:0003543 ‘trigeminal nerve disease’, see http://35.241.144.112/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0003543;

‘facial nerve disease’ is MONDO:0002098 (http://35.241.144.112/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0002098);

‘facial neuralgia’ is not yet in EFO 3, but it exists in MONDO, so 
- [ ] we could import it from there (https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0001818). 

Please check and let us know if you believe that anything is missing/incorrect. Thanks.

**Comment by gkos-bio** [comment]
Thank you.
Please include 'facial neuralgia' too.
'facial neuralgia' is an approximate synonym of 'Disorder of facial nerve, unspecified' in ICD10 
Can you add the ICD10 diagnosis Code G51.9 as a x-ref to 'facial neuralgia' please?

**Comment by paolaroncaglia** [comment]
@gkos-bio 
Sure. I will

- [ ] Create a new EFO term in EFO 2 for 'facial neuralgia', copying over info from MONDO:0001818 (see https://www.ebi.ac.uk/ols/ontologies/mondo/terms?short_form=MONDO_0001818), and adding ICD10 database_cross_reference G51.9.

- [ ] Write here the ID of the new EFO term.

**Comment by paolaroncaglia** [comment]
@gkos-bio 
All done, your new term is EFO:0009380 'facial neuralgia'. It will be visible after the next release (Nov 15th). Thanks.
