### ISSUE TITLE
Remove d2p module from otar-efo profile

### ISSUE THREAD

**Issue by matentzn** [EBISPOT/efo#933]
As discussed in email, its not needed. Lets comment out rather than delete in case we want to build something similar for other relations :)

**Comment by zoependlington** [comment]
D2P commented out on the otar_profiler repo

**Comment by matentzn** [comment]
What I wonder now is wether David and Cinzia will only take the HPOA relations from source, but still want the mondo relations (which are more complicated to extract); we can discuss this in the next tete a tete.

**Comment by d0choa** [comment]
We believe we were able to get them. The only ones causing as some problems will be fixed once #939 is addressed
