### ISSUE TITLE
Relationship between mondo:closeMatch, mondo:exactMatch, and oboInOwl:hasDbXref?

### ISSUE THREAD

**Issue by dhimmel** [EBISPOT/efo#935]
Terms in EFO appear to be linked/mapped to external terminologies using the following 3 predicates:

- oboInOwl:hasDbXref (database cross reference)
- mondo:closeMatch (closeMatch)
- mondo:exactMatch (exactMatch)

These categories show up on the EBI EFO browser ([example](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000311)). Running a SPARQL query on the OWL EFO graph also retrieves these external mappings:

```SPARQL
# find exactMatches and closeMatches
PREFIX mondo: <http://purl.obolibrary.org/obo/mondo#>
PREFIX efo: <http://www.ebi.ac.uk/efo/>
SELECT ?efo_uri ?predicate ?close_match
WHERE {
  VALUES ?predicate {mondo:closeMatch mondo:exactMatch}
  ?efo_uri ?predicate ?close_match
  # FILTER (?efo_uri = efo:EFO_0000311)
}
```

Some of the output rows:

efo_uri | predicate | close_match
-- | -- | --
efo:EFO_0000311 | mondo:closeMatch | http://identifiers.org/mesh/D009371
efo:EFO_0000311 | mondo:closeMatch | http://identifiers.org/snomedct/154432008
efo:EFO_0000311 | mondo:closeMatch | http://identifiers.org/snomedct/154433003
efo:EFO_0000311 | mondo:exactMatch | http://identifiers.org/snomedct/363346000
efo:EFO_0000311 | mondo:exactMatch | http://linkedlifedata.com/resource/umls/id/C0006826
efo:EFO_0000311 | mondo:exactMatch | obo:DOID_0050686
efo:EFO_0000311 | mondo:exactMatch | obo:DOID_0050687
efo:EFO_0000311 | mondo:exactMatch | obo:DOID_162
efo:EFO_0000311 | mondo:exactMatch | obo:NCIT_C9305

I am not clear about the difference between mondo:closeMatch, mondo:exactMatch, and oboInOwl:hasDbXref. I don't see any information on closeMatch or exactMatch in the [MONDO Axiom Annotations Summary Table](https://mondo.readthedocs.io/en/latest/editors-guide/f-entities/#axiom-annotations-summary-table).

My main questions:

- Any place these predicates are documented that I could review?
- Are closeMatch and exactMatch essentially subclasses (more specific types) of hasDbXref?
- Is the eventual goal for remove hasDbXref in favor of the more specific closeMatch and exactMatch?
- Are all 3 annotation types added separately by curators?
- Do any of these annotations automatically generate other annotations? For example, would an exactMatch to foreign_term_x automatically add a hasDbXref annotation?
- Should the identifier.org URLs be formatted like `http://identifiers.org/snomedct:363346000` rather than `http://identifiers.org/snomedct/363346000`, since these URLs appear to follow the `namespace:accession` rather than `provider_code/namespace:accession` [identification scheme](https://docs.identifiers.org/articles/docs/identification_scheme.html).

My main goal is to extract cross-references from EFO to other terminologies. In the past I've just been using `oboInOwl:hasDbXref`, but the ability to differentiate between a close and exact match would be helpful.

**Comment by dhimmel** [comment]
@zoependlington looking forward to learning more here, if you've got time to take a look at this issue. 🙏

**Comment by zoependlington** [comment]
Hi @dhimmel,

The Mondo close and exact matches are inherited from Mondo and potentially other external ontologies when we run our imports - they're not something we create in EFO ourselves. Currently EFO only creates term x-refs with the hasDBXref annotation. It would be nice to be able to implement this into EFO, but right now it is not a priority task.

**Comment by matentzn** [comment]
I think it is time these are cleaned up and provenance. @dhimmel @zoependlington my feeling is that the best way to go about this is: 
1. add provenance two all matches (where they come from)
2. settle on skos:*Match for cross ontology matches
3. Add a page to the EFO docs saying that db:xrefs are not save to be used for anything other than Machine Learning due to their total lack of semantics.

@dhimmel I would recommend for right now, you use Mondo directly to confirm the disease matches in EFO, until we have provenance sorted.
