### ISSUE TITLE
New term request for Richard PMID 33048379

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#937]
For new term requests, please provide the following information:

## Preferred term label

response to cranial radiation therapy

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of cranial radiation therapy. 

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

response to antineoplastic agent

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
A quick note of caution: 'response to antineoplastic agent' is not an ideal parent because an antineoplastic agent is a substance while radiation isn't.

**Comment by zoependlington** [comment]
I added this term as a child of response to radiation.

response to cranial radiation therapy | EFO_0010950

This will be available at our next release (18th Jan)
