### ISSUE TITLE
Obsoleted MONDO_0018797 still present in OTAR slim

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#938]
While MONDO_0018797 has been obsoleted from MONDO (https://github.com/monarch-initiative/mondo/issues/1175) and later in EFO, it's still present in the EFO OTAR slim. Extracted from OWL file: 

```
    <!-- http://purl.obolibrary.org/obo/MONDO_0018797 -->

    <Class rdf:about="http://purl.obolibrary.org/obo/MONDO_0018797">
        <rdfs:subClassOf rdf:resource="http://www.ebi.ac.uk/efo/OTAR_0000018"/>
    </Class>
```

Can we remove this term as well to be aligned?

We have checked systematically the OWL and this is the only term presenting this issue. Downstream activities here: https://github.com/opentargets/platform/issues/1211

**Comment by dhimmel** [comment]
Was about to open an issue about `MONDO:0018797`, which only exists in EFO-OTAR and not EFO, missing a label. Sounds like this is why.

Regarding obsolete node issues with EFO-OTAR, https://github.com/EBISPOT/efo/issues/927 might also be of interest.

**Comment by zoependlington** [comment]
This will be removed in the upcoming January release - the relationship was forced in our subclasses template and so was not removed from the final file. I have also implemented a check to make sure obsolete terms so not appear within the hierarchy.

**Comment by d0choa** [comment]
I can confirm the term has been removed from EFO OTAR slim in 3.26. Thanks!

```
❯ grep MONDO_0018797 efo_otar_slim.owl
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <mondo:excluded_subClassOf rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>
        <annotatedTarget rdf:resource="http://purl.obolibrary.org/obo/MONDO_0018797"/>

```
