### ISSUE TITLE
Missing hasDbXref for imported terms

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#939]
We believe a number of terms lack `hasDbXref` from the resource they were imported from.
The ones we are suspicious about are listed next:

Expected to have a MONDO `hasDbXref`:
- EFO_0002689
- EFO_0008615
- EFO_1000036
- EFO_1001321
- EFO_1001399
- EFO_1001490
- EFO_1001933
- EFO_1001993

Expected to have an Orphanet `hasDbXref`
- Orphanet_101685
- Orphanet_116
- Orphanet_157846
- Orphanet_158673
- Orphanet_166002
- Orphanet_171829
- Orphanet_183466
- Orphanet_183469
- Orphanet_1900
- Orphanet_199343
- Orphanet_2072
- Orphanet_209951
- Orphanet_221008
- Orphanet_221016
- Orphanet_231568
- Orphanet_247691
- Orphanet_269567
- Orphanet_269570
- Orphanet_276061
- Orphanet_300373
- Orphanet_300605
- Orphanet_3055
- Orphanet_352582
- Orphanet_363306
- Orphanet_365
- Orphanet_398073
- Orphanet_404577
- Orphanet_437
- Orphanet_487
- Orphanet_77243
- Orphanet_79282
- Orphanet_79284
- Orphanet_90307
- Orphanet_93296
- Orphanet_99900

Please feel free to reach out for any clarification

**Comment by zoependlington** [comment]
**NOTE TO SELF:** EFO_0002689 needs to be added to the Mondo mapping list as
`http://purl.obolibrary.org/obo/MONDO_8000010	http://www.ebi.ac.uk/efo/EFO_0002689	antiphospholipid syndrome	antiphospholipid syndrome`

Orphanet terms will also be replaced by Mondo terms or EFO terms soon, but should still ensure there is an Orphanet x-ref in these cases. This should be checked again post Orphanet switch.

**Comment by zoependlington** [comment]
We have updated our pipeline to make sure that EFO terms that should have Mondo x-refs now have those x-refs. Due to the plans to replace Orphanet terms with Mondo, we haven't focused on those. Therefore I'll move this to done, but please let me know if any terms are still missing expected x-refs.
