### ISSUE TITLE
NTR: RNA extraction protocol

### ISSUE THREAD

**Issue by PhiBabs935** [EBISPOT/efo#940]
Hi, I am requesting an EFO term for 'RNA extraction protocol' in order to import it to the Influenza Ontology. We have a term with this label already, but this term is more broad than influenza so I would like to deprecate and replace it. -Shane

## Preferred term label

RNA extraction protocol

## Textual definition

Nucleic acid extraction protocol that specifies a procedure for separating and recovering the RNA fraction of an input material. [PMID: 31159762 PMID: 31348903]

## Suggested parent term

EFO:nucleic acid extraction protocol

## Attribution
Shane Babcock
https://orcid.org/0000-0003-0798-114X

**Comment by paolaroncaglia** [comment]
@PhiBabs935 
Thanks, I'll add the new term as suggested in time for the next EFO release (mid-Feb).

**Comment by PhiBabs935** [comment]
@paolaroncaglia Awesome. Thank you.

**Comment by paolaroncaglia** [comment]
Hi @PhiBabs935 ,
Your requested term 'RNA extraction protocol' was added as EFO:0010959.
It will be visible in the next EFO release, scheduled for Feb. 15th. 
May take an extra day or so to show up in OLS. Thanks.
Paola
