### ISSUE TITLE
Fixing parentage of 'change measurements'

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#941]
Should ‘change measurements’ in EFO usually be children of the non-change version of the term? It seems like some but not all are, e.g. this seems to be the case for 'triglyceride change measurement' [EFO:0007681](http://www.ebi.ac.uk/efo/EFO_0007681).

For example, it would be ideal if:
- 'GFR change measurement' [EFO:0006829](http://www.ebi.ac.uk/efo/EFO_0006829) was a child of 'glomerular filtration rate' [EFO:0005208](http://www.ebi.ac.uk/efo/EFO_0005208).

**Comment by zoependlington** [comment]
I've double checked and all seem to now be the children of the non-change parent term, please let me know if you spot any others I may have missed! This will be available at our next release on the 15th Feb.
