### ISSUE TITLE
New term requests for PMID:33462484

### ISSUE THREAD

**Issue by smlmbrt** [EBISPOT/efo#942]
Probably relevant to GWAS Catalog curators as well, the paper has PGS and GWAS.

### Synonyms from other ontologies 
blood phosphate concentration (EUPATH:0021213), blood phosphate level (CMO:0000504)
### Textual definition
The amount of phosphorus, measured as inorganic phosphate, in a specified sample of blood. [From CMO:0000504]
### Suggested parent term
measurement (EFO_0001444) 

## Urine Potassium Measurement
Exact term could be imported from NCIT NCIT:C61047
#### Textual definition
A quantitative measurement of the total amount of potassium present in a sample of urine. [ NCI ]
### Suggested parent term
urinary metabolite measurement (EFO_0005116) 

## Attribution
0000-0001-8222-008X

**Comment by kallia-p** [comment]
Added urinary potassium measurement (EFO_0010952) as subclass of urinary metabolite measurement (EFO_0005116)

**Comment by dosumis** [comment]
Should use CHEBI phosphate ion - as the general phosphate term groups lots of different phosphate

**Comment by kallia-p** [comment]
Added blood phosphate measurement (EFO:0010972) as a subclass of measurement

**Comment by kallia-p** [comment]
Added blood phosphate measurement (EFO:0010972) as a subclass of measurement
