### ISSUE TITLE
EFO term request for pulmonary non-tuberculous mycobacterial infection

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#946]
Suggest importing term from MONDO: http://purl.obolibrary.org/obo/MONDO_0018469

For new term requests, please provide the following information:

## Preferred term label

pulmonary non-tuberculous mycobacterial infection

## Synonyms

non-tuberculous mycobacterial lung disease

## Textual definition

(see MONDO definition)

## Suggested parent term

mycobacterial infectious disease (http://purl.obolibrary.org/obo/MONDO_0020590)

> The above term has previously been imported into EFO, and is the parent term of the requested term in MONDO.

**Comment by zoependlington** [comment]
I will import the Mondo term (http://purl.obolibrary.org/obo/MONDO_0018469) into EFO for this, thanks @eks-ebi.
