### ISSUE TITLE
New term request for PMID:33357513 (pneumonia severity measurement)

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#947]
For new term requests, please provide the following information:

## Preferred term label

pneumonia severity measurement

## Textual definition

Quantification of the severity of the symptoms of pneumonia, an inflammation of the lung parenchyma caused by an infection.

## Suggested parent term

* lung disease severity measurement (http://www.ebi.ac.uk/efo/EFO_0007744)

**Comment by zoependlington** [comment]
Added to EFO as http://www.ebi.ac.uk/efo/EFO_0010966, which will be available at our next release (15th)
