### ISSUE TITLE
Update Travis

### ISSUE THREAD

**Issue by zoependlington** [EBISPOT/efo#948]
Travis is no longer running due to a change on the Travis side, this needs to be investigated and updated.

**Comment by d0choa** [comment]
Free tiers are more limited now. We had to move to a paid plan, in case this helps

**Comment by zoependlington** [comment]
I have migrated everything over, but it seems like all of the free credits have been used up so we may need to consider an alternative like github actions. I will look into this.

**Comment by zoependlington** [comment]
Nico is working on the GitHub actions here: https://github.com/EBISPOT/efo/pull/1001.

I will close this ticker.
