### ISSUE TITLE
New term request for Sinnott-Armstrong PMID 33462484

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#949]
For new term requests, please provide the following information:

## Preferred term label

Phosphate measurement

## Textual definition

Quantification of phosphate levels in a sample.

**Comment by zoependlington** [comment]
Added to EFO as http://www.ebi.ac.uk/efo/EFO_0010968, which will be available in our next release on the 15th

**Comment by dosumis** [comment]
@kallia-p - Please check paper for whether this refers to free phosphate rather than the phosphate compound grouping term currently used.
