### ISSUE TITLE
Broken link in front EFO GitHub page

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#95]
In this page
https://github.com/EBISPOT/efo
and more precisely in this section
https://github.com/EBISPOT/efo/blob/master/README.md
this link is broken and needs updating to https:
"Please get the latest version of EFO by visiting http://wwww.ebi.ac.uk/efo."

**Comment by simonjupp** [comment]
This can be fixed in here https://github.com/EBISPOT/EFO-website/blob/master/src/main/webapp/index.html and run the EFO-web bamboo plan to release a new version of the website.

**Comment by paolaroncaglia** [comment]
@simonjupp 
The EFO webpage on the EBI site looks fine to me, it is already https://www.ebi.ac.uk/efo/
It's just the link in the README on the GitHub page that needs fixing. The link you added above is to change the EBI website instead, right? :-)

**Comment by simonjupp** [comment]
sorry, yes. In which case it's even easier to fix :)

**Comment by paolaroncaglia** [comment]
Done.
