### ISSUE TITLE
New term request for Sinnott-Armstrong PMID 33462484

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#950]
For new term requests, please provide the following information:

## Preferred term label

Urinary microalbumin measurement

## Textual definition

The quantification of microalbumin in urine.

## Suggested parent term

urinary metabolite measurement

**Comment by zoependlington** [comment]
Added to EFO as http://www.ebi.ac.uk/efo/EFO_0010967, which will be available in our next release on the 15th.
