### ISSUE TITLE
Convert efo-edit.owl to functional syntax

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/efo#952]
Could we convert the editors file to functional syntax ASAP?  This should be completely painless.  It will not have any effect on the content & diffs with bubastis should not be affected.  If we do this then it will be possible to do branch edits without announcing a lock on EFO first.   I think this will be needed for Kallia's work.  You can continue to work on the master with your current locking SOP.  Any issues with clashes will be the responsibility of editors working on a branch, so there should be no increase in workload involved for regular editing.

**Comment by dosumis** [comment]
CC @matentzn - do you know of any reason this might cause problems?  Seems unlikely, but asking in case there's some legacy code issue.  Figured you'd know if anyone does.

**Comment by matentzn** [comment]
I dont think there would be a problem, and I would very much applaud the move.

**Comment by matentzn** [comment]
There were in the past some pipeline steps that operated on the XML structure of the ontology - if that's the case, we will see that during the move and add an intermediate product to operate on instead. But in the EFO case, I don't think so!
