### ISSUE TITLE
add synonyms to EFO:0010713

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#954]
## Synonyms

10X VDJ, 10X V(D)J, Chromium Single Cell V(D)J

it would be great to add the above synonyms so that term shows up when searching VDJ or V(D)J

Thanks!

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
Synonyms added. Will be in next Monday's EFO release. Thanks,
Paola
