### ISSUE TITLE
[NTR] Visium Spatial Gene Expression

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#955]
## Preferred term label

Visium Spatial Gene Expression

## Synonyms

10X Visium, Visium

## Textual definition

Visium Spatial Gene Expression is a method developed by 10X genomics that measures either the whole transcriptome or a defined set of transcripts in intact tissue sections and maps where gene activity is occurring.

ref: https://pages.10xgenomics.com/rs/446-PBO-704/images/10x_LIT059_ProductSheet_VisiumSpatialGeneExpression_Letter_digital.pdf

## Suggested parent term

10X sequencing - http://www.ebi.ac.uk/efo/EFO_0008995
also under spatial transcriptomics- http://www.ebi.ac.uk/efo/EFO_0008994

## Attribution

0000-0001-7505-5418

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
If you're aware of one or more publications where Visium Spatial Gene Expression is used, possibly associated to datasets you may be looking at, please provide PMIDs. Not mandatory but helpful. Thanks!

**Comment by paolaroncaglia** [comment]
Note for self:
- [ ] add HCA tag

**Comment by mshadbolt** [comment]
there are a bunch here https://www.10xgenomics.com/resources/publications?sortBy=10x-publications-dev-relevance&refinementList%5BproductGroups%5D%5B0%5D=Spatial%20Gene%20Expression&page=1 

do you mean ones that just use it or describe the method itself?

**Comment by paolaroncaglia** [comment]
Thanks @mshadbolt ,

> there are a bunch here https://www.10xgenomics.com/resources/publications?sortBy=10x-publications-dev-relevance&refinementList%5BproductGroups%5D%5B0%5D=Spatial%20Gene%20Expression&page=1
> 
> do you mean ones that just use it or describe the method itself?

I can use the [product sheet](https://pages.10xgenomics.com/rs/446-PBO-704/images/10x_LIT059_ProductSheet_VisiumSpatialGeneExpression_Letter_digital.pdf) as a reference that describes the method. But if there are papers that use the method, those are nice to add too. (URLs for commercial web sites and reports may not be stable over time, while PMIDs usually are, unless retracted!). Thanks.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Term added, will be in next Monday's EFO release. I didn't add PMIDs because it wasn't immediately clear which abstracts referred to Visium rather than other 10x spatial transcriptomics methods. Feel free to re-open this ticket if you'd like to add specific PMIDs. Thanks!

**Comment by paolaroncaglia** [comment]
@mshadbolt 
Forgot to mention that the next HCAO release is planned for Feb 18th, and will hopefully be in OLS by Feb 20th.
