### ISSUE TITLE
[EDITS] ATAC-seq terms

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#956]
### EFO:0008925 - Single cell ATAC-seq (cell index)
add synonym 'sci-ATAC-seq' 

There's also a typo in 'sinlge cells' should be 'single'

I had come up with this definition which may make it more clear or could be combined:
> Multiplex single-cell profiling of chromatin accessibility by combinatorial cellular indexing. In this method, single nuclei are identified by the unique combination of n5 barcodes and indices rather than by isolation.

### EFO:0008904 - scATAC-seq (Microfluidics)

The definition for this term is not very descriptive and doesn't capture the key part of the assay, i.e. that it was performed using a microfluidics device, perhaps it could be expanded as follows:

> Mapping single cell genomes for transposase-accessible chromatin where single nuclei are isolated using a microfluidics platform such as Fluidigm C1.

## Attribution

0000-0001-7505-5418

**Comment by paolaroncaglia** [comment]
Hi @mshadbolt ,
Edits done. I also made the primary labels consistent (scATAC-seq rather than single cell ATAC-seq, but kept the latter wording as synonym). Will all be visible in the Feb 15 EFO release.
