### ISSUE TITLE
NTR: Illumina NextSeq 1000 & 2000

### ISSUE THREAD

**Issue by mobilegenome** [EBISPOT/efo#957]
In the NextSeq range, Illumina released two new sequencers which are not yet included in the EFO. 

For simplicity, I'm opening one issue for both terms, hope thats OK. 

## Preferred term label

Illumina NextSeq 1000
Illumina NextSeq 2000

## Synonyms

(none)

## Textual definition

The Illumina NextSeq 1000/2000 is a benchtop high-throughput sequencing machine developed by Illumina. Its primary applications include exome sequencing, small whole-genome sequencing, whole-transcriptome sequencing and cytogenomic arrays. In contrast to the smaller NextSeq 550 model, an additional key application field is miRNA & Small RNA sequencing. It has a maximum output of 330 Gb. 

## Suggested parent term

high throughput sequencer
http://www.ebi.ac.uk/efo/EFO_0002699

**Comment by paolaroncaglia** [comment]
Hi @mobilegenome ,

Thanks for suggesting these new terms, we'll be happy to add them (and yes, opening one ticket for two closely related requests is perfectly fine). Could you please provide the following:
- [ ] References describing the technologies and/or publications where they've been used. PMIDs are preferable, but company technical reports would also work.
- [ ] Minimum information to differentiate Illumina NextSeq 1000 from Illumina NextSeq 2000. (I'm aware that some of the existing Illumina terms have identical definitions, but that's not ideal.)
- [ ] Your ORCID. Not mandatory, but nice to provide micro-attributions of new terms.

Thank you!
Paola

**Comment by mobilegenome** [comment]
Hi Paolo, 

references are difficult, they don't seem to be any whitepapers in scholarly databases. I found the following PDF, which might serve the purpose: 
https://www.illumina.com/content/dam/illumina/gcs/assembled-assets/marketing-literature/nextseq-1000-2000-spec-sheet-770-2019-030/nextseq-1000-2000-spec-sheet-770-2019-030.pdf

A way to differentiate could be the maximum output which is 120 Mb and 330 Mb for the 1000 and 2000 model, respectively. However, it might be possible these figures change in the future with new chemistry. Alternatively, one could describe the 2000-model having a higher capacity. Otherwise they are pretty much identical and I couldn't find detailed tech-specs outlining their differences. 

ORCID: 0000-0002-3110-8220

Thanks, 

Fritjof

**Comment by paolaroncaglia** [comment]
Hi @mobilegenome (Fritjof),

Thanks very much. I'll reference the Illumina report, and I'll differentiate between the two machines by saying that when they were first commercialized, their maximum output was 120 Mb and 330 respectively.

Best wishes,
Paola

**Comment by paolaroncaglia** [comment]
@mobilegenome 
The terms you requested were added as
EFO_0010962 (Illumina NextSeq 1000)
EFO_0010963 (Illumina NextSeq 2000)
and will be in the upcoming EFO release scheduled for Feb. 15th.
Best wishes,
Paola
