### ISSUE TITLE
NTR: barcoded plate-based single cell RNA-seq

### ISSUE THREAD

**Issue by paolaroncaglia** [EBISPOT/efo#958]
cc @ami-day
Stemming from https://github.com/HumanCellAtlas/ontology/issues/76:

barcoded plate-based single cell RNA-seq
"A single-cell RNA sequencing library construction method that generates barcoded libraries and is plate-based. An example would be a plate-based method that is not Smart-seq2 or a modified, barcoded version of Smart-seq2."
Def dbxref: Ami's ORCID; PMID if provided
Suggested parent term: single-cell library construction
Subset: added_for_HCA

**Comment by paolaroncaglia** [comment]
@ami-day
Could you please provide your ORCID?
A PMID for the new term would also be helpful, thanks.

**Comment by paolaroncaglia** [comment]
@ami-day
The term you requested was added as EFO_0010964 (barcoded plate-based single cell RNA-seq).
It will be in the next EFO release (Feb 15th) and then in the HCAO release (Feb 18th).

**Comment by mshadbolt** [comment]
hi @paolaroncaglia it doesn't seem like there was an HCAO release in february? Our ontology repo hasn't been edited since December 2020 https://github.com/HumanCellAtlas/ontology

**Comment by zoependlington** [comment]
Hi @mshadbolt, the HCAO repo has been moved to https://github.com/ebi-ait/ontology and has been released every month since December. Today (18th March) is the next release.

**Comment by mshadbolt** [comment]
uuum ok, why are we still making issues and asking questions here https://github.com/HumanCellAtlas/ontology/issues?

**Comment by zoependlington** [comment]
The new repo is a forked version so doesn't have an issue tracker attached to it, so we're still using the old issue tracker. There should be no change to your pipeline for requests/questions.

**Comment by mshadbolt** [comment]
ah k right, I wasn't aware it had moved. Seems weird to spread it across two repos.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
@zoependlington 
This said, it looks like EFO_0010964 (barcoded plate-based single cell RNA-seq) may not have made it into HCAO after all, despite being tagged as "added_for_HCA" in EFO. This might be due to an error in how I initially created the tag in EFO, I'm not sure; tomorrow I'll ask Zoe for help on how to fix this if indeed it needs fixing (the file efo_added_for_hca.txt is empty while I'd have expected 10 terms to be in it). 
I'll comment back here with news. Thanks.
Paola

**Comment by mshadbolt** [comment]
ok thanks for letting us know, it is stopping us from submitting a project as it will fail validation until the term is added.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
@zoependlington and I looked into the issue above, I opened a separate ticket that I'll take care of (https://github.com/EBISPOT/efo/issues/1018). At any rate, we'll ensure that the term from this original ticket request makes it into the HCAO patch release.

**Comment by paolaroncaglia** [comment]
@mshadbolt 
To confirm, EFO_0010964 (barcoded plate-based single cell RNA-seq) and all other EFO terms recently added for HCA are now indeed in HCAO. Those terms had in fact been picked up by the makefile as we expected, but they weren't available to you because the OLS instance hadn't been redeployed from your side yet (see https://github.com/ebi-ait/hca-ebi-dev-team/issues/387). So you should be able to submit your project now.
Best,
Paola
