### ISSUE TITLE
clean up definition IRI!!!! and get rid of it from any webulous templates

### ISSUE THREAD

**Issue by siiraa** [EBISPOT/efo#96]
We have rolled out the old definition IRI (efo.ac.uk/efo/defition) and replaced it with IAO_0000115. However, it keeps reappearing in EFO, suspecting some Webulous templates still need to be updated to replect the use of the new definition IRI. 

- update/review _all_ Webulous templates to use IAO_0000115 for definition
- refactor all definitions to use IAO IRI in EFO

**Comment by simonjupp** [comment]
@twhetzel are you able to look at updating these?

**Comment by twhetzel** [comment]
Yes, I can look at this.

**Comment by twhetzel** [comment]
One place this is coming from is the Webulous GWAS EFO Measurement template. I'll check the others and make updates next week.

**Comment by twhetzel** [comment]
Updated the GWAS EFO Measurement template and confirmed change in newly generated OWL file from Webulous. Will check the other templates.

**Comment by twhetzel** [comment]
Templates updated to use "IAO_0000115" for the definition property for terms:
- Add EFO disease
- Add EFO measurement
- Add EFO Cell Line
- Add EFO Assay
- Import UBERON term
- Import plant term (EFO, EO, PO, TO, Taxon, ChEBI, GO)
- Import HP term
- Import ChEBI term
- Add EFO response to stimulus
- Add EFO phenotype

NOTE: the "HCA import template" uses the EFO "definition" property. Will leave as-is pending feedback from @daniwelter

**Comment by twhetzel** [comment]
Also updated "HCA import template".

**Comment by twhetzel** [comment]
The "Import HP term" and "Import plant term (EFO, EO, PO, TO, Taxon, ChEBI, GO)" template updates are sending error messages.

**Comment by twhetzel** [comment]
Added "http://www.ebi.ac.uk/efo/efo.owl" in the list of "Imported ontology URIs" for the HP template and that fixed the issue, but the Plant template is still failing.

**Comment by simonjupp** [comment]
I updated the "Import plant term (EFO, EO, PO, TO, Taxon, ChEBI, GO)" template and it is working now. there was an owl imports conflict.

**Comment by twhetzel** [comment]
Thanks! I saw the update come through and that it completed or didn't fail as it did with my earlier attempts. Can we close this now?

**Comment by paolaroncaglia** [comment]
@twhetzel Simon's preference is for placing tickets in the "Done" column of the ZenHub board and then moving them to the "Closed" queue during scrums or planning meetings, rather than each of us closing them independently. :-) I'm sure we can move this ticket to "Closed" when we all meet today. Thanks!
