### ISSUE TITLE
Request for prostate specific antigen measurement to be added as a child of protein measurement

### ISSUE THREAD

**Issue by helenp** [EBISPOT/efo#963]
prostate specific antigen measurement http://www.ebi.ac.uk/efo/EFO_0004624
protein measurement  http://www.ebi.ac.uk/efo/EFO_0004747

Requested by Eric Fauman, GWAS user extraordinaire. 

For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/efo)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Hi @helenp ,

'prostate specific antigen measurement' is now a child of 'protein measurement'. Will be in next Monday's EFO release.

Best,

Paola
