### ISSUE TITLE
[NTR] RNAscope

### ISSUE THREAD

**Issue by mshadbolt** [EBISPOT/efo#964]
For new term requests, please provide the following information:

## Preferred term label

RNAscope

## Synonyms

(e.g., Absent spleen)

## Textual definition

RNAscope is a novel multiplex nucleic acid in situ hybridization (ISH) assay for detecting and visualising gene expression within intact cells.

(I copied this from here: https://aquila-bm.com/services/specialist-histology/rnascope/ )

PMID:22166544

## Suggested parent term

Under smFISH http://www.ebi.ac.uk/efo/EFO_0009918

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by paolaroncaglia** [comment]
Notes for self: add as above, plus
- [ ] has exact synonym: RNAscope in situ hybridization assay
- [ ] subset: added_for_HCA

**Comment by paolaroncaglia** [comment]
@mshadbolt 
EFO_0010965 (RNAscope) will be in the next EFO release (Feb 15th) and then in the HCAO release (Feb 18th).
