### ISSUE TITLE
term request for Dauber 32652002 - short stature

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#965]
For new term requests, please provide the following information:

## Preferred term label

Short stature
import from HP http://purl.obolibrary.org/obo/HP_0004322

## Synonyms
from HP

## Textual definition

from HP

## Suggested parent term

Growth delay (in EFO already imported from HP)
http://purl.obolibrary.org/obo/HP_0001510

Note that many of the children of 'growth delay' in EFO should be children of short stature.   So the short stature ones (disproportionate/disproportionate etc)  should be made children of the new 'short stature' term.  'Severe intrauterine growth retardation', 'delayed puberty' and 'postnatal growth retardation' should not be children of 'short stature'. I think.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by aoifemcm** [comment]
Sorry Zoe, there's another term request for this publication:

'Response to growth hormone'
Synonyms: response to human growth hormone, response to HGH

child of response to drug
CHEBI for growth hormone is http://purl.obolibrary.org/obo/CHEBI_37845
Standard response language.

**Comment by zoependlington** [comment]
Imported HP term and added http://www.ebi.ac.uk/efo/EFO_0010969, which will be available at our next release on the 15th.

**Comment by aoifemcm** [comment]
Hey Zoe,
I see you import the short stature term, thanks, did you also see the 'response to growth hormone' request that I added in comment above?
