### ISSUE TITLE
New term request for Kisia PMID 31420016

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#966]
For new term requests, please provide the following information:

## Preferred term label

severe malarial anemia

## Synonyms

SMA

## Textual definition

Severe malarial anemia is a leading cause of malaria-related morbidity and mortality in children. Inefficient erythropoiesis is a central pathogenic feature.

## Suggested parent term

anemia (disease)

**Comment by zoependlington** [comment]
Added as EFO_0010970. This will be available at our next release on the 15th.
