### ISSUE TITLE
New cell line suggestion

### ISSUE THREAD

**Issue by scorbett-ebi** [EBISPOT/efo#967]
## Preferred term label

NOZ

## Synonyms

NOZAWA; NOZC-1

## Textual definition

Human cancer cell line, gallbladder carcinoma, PMID: 3154020 describes it as “established from ascites of a patient of peritonitis carcinomatosa… adenocarcinoma tubular ++, moderately differentiated… composed of polygonal, spindle and round shaped cells.”  It is included in Cellosauraus: https://web.expasy.org/cellosaurus/CVCL_3079

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_1000262

I couldn’t find a “gallbladder adenocarcinoma cell line” term, which I assume would be most suitable.

**Comment by zoependlington** [comment]
Added as new term EFO_0010973, which will be available after our 15th March release.
