### ISSUE TITLE
New GWAS term request for PMID 33138277

### ISSUE THREAD

**Issue by eks-ebi** [EBISPOT/efo#968]
For new term requests, please provide the following information:

## Preferred term label

response to metamizole

## Textual definition

Any process that results in a change in state or activity of a cell or an organism (in terms of movement, secretion, enzyme production, gene expression, etc.) as a result of metamizole stimulus. Metamizole is an analgesic that carries a risk of causing agranulocytosis.

## Suggested parent term

response to drug (http://purl.obolibrary.org/obo/GO_0042493)

## Notes

Please link to chemical entity CHEBI:62088 "metamizole"

**Comment by zoependlington** [comment]
Added as http://www.ebi.ac.uk/efo/EFO_0010971. This will be available at our next release on the 15th Feb!
