### ISSUE TITLE
Suggestion for amendment re. Mouse strain classification: CAROLI/EiJ,  SPRET/EiJ

### ISSUE THREAD

**Issue by mobilegenome** [EBISPOT/efo#973]
Hi, 

the following mouse strains are derived from wild mice that taxonomically and evolutionarily distinct from the domestic mouse _Mus musculus_. In the EFO they are classified as children of _Mus musculus_. Placing them under the species-terms from which they originate would reflect the underlying biology more accurate.  

## CAROLI/EiJ

- Existing label: http://www.ebi.ac.uk/efo/EFO_0007839
- Suggested parent term: http://purl.obolibrary.org/obo/NCBITaxon_10089
- Reference: https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=585379#null

## SPRET/EiJ

- Existing label: http://www.ebi.ac.uk/efo/EFO_0007734
- Suggested parent term http://purl.obolibrary.org/obo/NCBITaxon_10096
- In addition, to my understanding, the suggested parent term  `Mus spretus` is considered an own species in the genus _Mus_. This would be better reflected if placed under the higher-level term http://purl.obolibrary.org/obo/NCBITaxon_10088. See also the ITIS database: https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=585407#null

**Comment by paolaroncaglia** [comment]
Hi @mobilegenome ,
Thank you for reporting these issues.
In time for the next EFO release (scheduled for mid-March), I will

- [ ] Move ‘CAROLI/EiJ’ under ‘Mus caroli’. I will not include the ITIS reference as that’s about Mus caroli, but I’ll add your ORCID (https://orcid.org/0000-0002-3110-8220). 

- [ ] Move ‘SPRET/EiJ’ under ‘Mus spretus’, and I’ll add your ORCID. I’ll also add the synonym “SPRET/Ei” based on the term def and literature usage.

- [ ] Move ‘Mus spretus’ under ‘Mus’, as per your advice and its NCBI taxonomical classification (https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=862507&lvl=3&p=has_linkout&p=blast_url&p=genome_blast&keep=1&srchmode=1&unlock). 

- [ ] Based on the same classification, I will also move ‘Mus musculus x Mus spretus’ under ‘Mus’.

**Comment by paolaroncaglia** [comment]
Hi @mobilegenome ,
I've made the changes you suggested. They'll be visible after the next EFO release scheduled for Monday (March 15th). 
Thank you,
Paola
