### ISSUE TITLE
New term requests for Calvo-Serra B PMID 33283231

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#975]
Created a Webulous form for urinary metabolite paper https://docs.google.com/spreadsheets/d/1FkkafczC01lPRHmU4yzTXfqKr7KRIgeT4aMKpVRWA8I/edit#gid=1955062823

@zoependlington @kallia-p

**Comment by zoependlington** [comment]
Added the following, which will be available after out 15th March release:

http://www.ebi.ac.uk/efo/EFO_0011005 | 'urea measurement'
http://www.ebi.ac.uk/efo/EFO_0011004 | 'trimethylamine oxide measurement'
http://www.ebi.ac.uk/efo/EFO_0011003 | 'trimethylamine measurement'
http://www.ebi.ac.uk/efo/EFO_0011002 | 'succinate measurement'
http://www.ebi.ac.uk/efo/EFO_0011001 | 'scyllo-inositol measurement'
http://www.ebi.ac.uk/efo/EFO_0011000 | 'proline beatine measurement' 
http://www.ebi.ac.uk/efo/EFO_0010999 | 'p-hydroxyphenylacetate measurement'
http://www.ebi.ac.uk/efo/EFO_0010998 | 'p-cresol sulfate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010997 | 'n1-methyl-nicotinamide measurement'
http://www.ebi.ac.uk/efo/EFO_0010996 | 'n-methylpicolinic acid measurement' 
http://www.ebi.ac.uk/efo/EFO_0010995 | 'n-methylnicotinic acid measurement' 
http://www.ebi.ac.uk/efo/EFO_0010994 | 'n-methyl-2-pyridone-5-carboxamide measurement' 
http://www.ebi.ac.uk/efo/EFO_0010993 | 'n-acetyl neuraminic acid measurement' 
http://www.ebi.ac.uk/efo/EFO_0010992 | 'hippurate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010991 | 'formate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010990 | 'dimethylamine measurement' 
http://www.ebi.ac.uk/efo/EFO_0010989 | 'acetone measurement' 
http://www.ebi.ac.uk/efo/EFO_0010988 | '5-oxoproline measurement' 
http://www.ebi.ac.uk/efo/EFO_0010987 | '4-deoxythreonic acid measurement' 
http://www.ebi.ac.uk/efo/EFO_0010986 | '4-deoxyerythronic acid measurement' 
http://www.ebi.ac.uk/efo/EFO_0010985 | '3-Indoxylsulfate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010984 | '3-hydroxyisovalerate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010983 | '3-hydroxyisobutyrate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010982 | '3-hydroxybutyrate measurement'
http://www.ebi.ac.uk/efo/EFO_0010980 | '3-aminoisobutyrate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010979 | '2-hydroxyisobutyrate measurement' 
http://www.ebi.ac.uk/efo/EFO_0010978 | chemotherapy-induced cytotoxicity measurement 
http://www.ebi.ac.uk/efo/EFO_0010977 | macrovascular complications of diabetes
