### ISSUE TITLE
New term request for Mulford, AJ PMID 33575800

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#977]
For new term requests, please provide the following information:

## Preferred term label

chemotherapy-induced cytotoxicity measurement

## Synonyms
NA

## Textual definition

quantification of some aspect of cytotoxity such as survival time or cell viability, as a response to a chemotherapic drug

## Suggested parent term

cytotoxicity measurement, http://www.ebi.ac.uk/efo/EFO_0006952

**Comment by zoependlington** [comment]
Added as EFO_0010978, which will be available after our next release (15th March).
