### ISSUE TITLE
Increase EFO - Meddra Xref coverage

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#978]
1436 EFO terms currently have MedDRA Xrefs (BTW with different spellings e.g. MedDRA or MEDDRA).

In Open Targets we are very interested on increasing this coverage to improve the mapping of pharmacovigilance adverse drug reactions to EFO.

Are there any systematic approaches that could help with these Xrefs?

**Comment by zoependlington** [comment]
It may be possible to use a similar approach that we used for our Mondo mappings, which used PAXO to generate a spreadsheet of potential mappings. I shall look into this to see if it is possible.

As for the x-ref inconsistencies, this is also something I'm looking into currently in https://github.com/EBISPOT/efo/issues/878

**Comment by d0choa** [comment]
Let us know if can help reviewing the potential mappings.

**Comment by zoependlington** [comment]
This is currently being done in https://github.com/EBISPOT/efo/issues/1088, so I will close this ticket.
