### ISSUE TITLE
Obsoleted terms missing in efo_otar_slim.owl

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#979]
The official OWL contains obsoleted classes like the next:

```
    <!-- http://www.ebi.ac.uk/efo/EFO_0000378 -->

    <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0000378">
        <rdfs:subClassOf rdf:resource="http://www.w3.org/2002/07/owl#Thing"/>
        <obo:IAO_0100001>http://www.ebi.ac.uk/efo/EFO_0001645</obo:IAO_0100001>
        <efo:obsoleted_in_version>3.24.0</efo:obsoleted_in_version>
        <efo:reason_for_obsolescence>Duplication with http://www.ebi.ac.uk/efo/EFO_0001645</efo:reason_for_obsolescence>
        <rdfs:label>obsolete_coronary artery disease</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:Class>

```

This is useful to keep track that the term `EFO_0000378` has been obsoleted because it's a duplicate of `EFO_0001645`. In our case, if somebody annotates data using `EFO_0001645`, we can safely translate it to the standing term `EFO_0000378`.

However, this information is not available in the slim. Could we have this information added?

Or alternatively, is there a logic in the slim that would help us retrieve the `EFO_0000378` -> `EFO_0001645` relationship? Is the `has_alternative_id` the way to go? If this is the case,  `EFO_0000378` -> `EFO_0001645` is not captured by `has_alternative_id`.

**Comment by d0choa** [comment]
@zoependlington is including the obsoleted terms in the slim the way to go?

**Comment by zoependlington** [comment]
Hi @d0choa I'm still working on making these available. Currently, obsolete terms are available in the profile but not the slim so the build process needs to be changed around. I should be able to generate a test file by tomorrow that can be tested before the official release.

**Comment by d0choa** [comment]
Wonderful! Thanks @zoependlington . Feel free to include the `has_disease_location` on this one as well, as we will stick to the changes you made in #981

**Comment by zoependlington** [comment]
Hi @d0choa, here is the test file including all obsolete terms and the has_disease_location relationships in the slim file: [efo_otar_slim_obsoletes.owl.zip](https://github.com/EBISPOT/efo/files/6085059/efo_otar_slim_obsoletes.owl.zip)
