### ISSUE TITLE
include has_disease_location in efo_otar_slim.owl

### ISSUE THREAD

**Issue by d0choa** [EBISPOT/efo#981]
As discussed recently, we are very interested in the disease location information contained in EFO.

For example, the psoriasis term (EFO_0000676) contains information regarding which body part is affected by the disease. Using the `has_disease_location` (EFO_0000784) it can be mapped to the body part `zone of skin` (UBERON_0000014). 

```
    <!-- http://www.ebi.ac.uk/efo/EFO_0000676 -->

    <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0000676">
    ...
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.ebi.ac.uk/efo/EFO_0000784"/>
                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000014"/>
            </owl:Restriction>
    ...
    
```

Whereas this information is available in the main efo.owl, it's not available in the efo_otar_slim.owl file. Would it be possible to add this information?

**Comment by zoependlington** [comment]
I have edited the slim generation pipeline to allow the slim to contain the has_disease_location axiom

I have attached the test slim file here: [efo_otar_slim_disease_location_test.owl.zip](https://github.com/EBISPOT/efo/files/6042696/efo_otar_slim_disease_location_test.owl.zip)

Please let me know if this is okay and if so, I shall implement these changes for our March (15th) release.

**Comment by d0choa** [comment]
We'll try to provide some feedback promptly. Thanks @zoependlington

**Comment by zoependlington** [comment]
Thank you, @d0choa!

**Comment by cmalangone** [comment]
@zoependlington @d0choa 
I gave a look to the file that you gave us and I have a question related to this specific version vs 3.26 version.
I noticed that there are extra info about Synonym section.
For instance:
```
        <oboInOwl:hasExactSynonym rdf:resource="http://purl.obolibrary.org/obo/hp#uk_spelling"/>
        <oboInOwl:hasExactSynonym>Low blood cell count</oboInOwl:hasExactSynonym>
```
Our script fails due the new `df:resource="http://purl.obolibrary.org/obo/hp#uk_spelling"/>`.
Is it this a new format that you are going to use for the next release, pleae?

Please let me know if the question is not clear.

**Comment by cmalangone** [comment]
@zoependlington cc: @d0choa 
Is it possible to avoid the nested info inside the section, please?
 ```
       <rdfs:subClassOf>
            <Restriction>
                <onProperty rdf:resource="http://www.ebi.ac.uk/efo/EFO_0000784"/>
                <someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0000014"/>
            </Restriction>
        </rdfs:subClassOf>
```

**Comment by d0choa** [comment]
I don’t think we want to diverge (more) from the official EFO. Keep in mind you can technically have multiple constrains of different type. For our current application we are only interested on EFO_0000784, but there could be others.

**Comment by cmalangone** [comment]
@d0choa : it makes sense. So, I can confirm the data for location are there.
@zoependlington : please let me know about the format of synonyms

**Comment by zoependlington** [comment]
This comes from our dynamic import of HP, so there are always risks of having these new additions for synonyms or cross references. Many of the OBO ontologies are including language tags, e.g. UK spelling, so I would imagine more of the ontologies will include these extra annotations for synonyms.

**Comment by d0choa** [comment]
Hi @zoependlington, thanks for the update. @cmalangone and I believe the data is only included for some cases.

Whereas the slim works for cases like pulmonary sarcoidosis (DOID_13406)...
 
```
    <!-- http://purl.obolibrary.org/obo/DOID_13406 -->
...
            <Restriction>
                <onProperty rdf:resource="http://www.ebi.ac.uk/efo/EFO_0000784"/>
                <someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0001004"/>
            </Restriction>
        </rdfs:subClassOf>
...
```

... it does not contain more complex cases like `hepatic tuberculosis` (EFO_0007302). Missing in the slim and present in the official release:

```
    <!-- http://www.ebi.ac.uk/efo/EFO_0007302 -->

    <owl:Class rdf:about="http://www.ebi.ac.uk/efo/EFO_0007302">
...
            <owl:Restriction>
                <owl:onProperty rdf:resource="http://www.ebi.ac.uk/efo/EFO_0000784"/>
                <owl:someValuesFrom>
                    <owl:Class>
                        <owl:unionOf rdf:parseType="Collection">
                            <rdf:Description rdf:about="http://purl.obolibrary.org/obo/UBERON_0002107"/>
                            <owl:Restriction>
                                <owl:onProperty rdf:resource="http://purl.obolibrary.org/obo/BFO_0000050"/>
                                <owl:someValuesFrom rdf:resource="http://purl.obolibrary.org/obo/UBERON_0002107"/>
                            </owl:Restriction>
                        </owl:unionOf>
                    </owl:Class>
                </owl:someValuesFrom>
            </owl:Restriction>
        </rdfs:subClassOf>
```

**Comment by zoependlington** [comment]
Thanks for spotting this! I'll investigate.

**Comment by zoependlington** [comment]
I've included all 'part of' relationships, which will allow the more complex has_disease_location axioms: [efo_otar_slim_part_of.owl.zip](https://github.com/EBISPOT/efo/files/6100788/efo_otar_slim_part_of.owl.zip)
