### ISSUE TITLE
New term request for Neuvonen PMID 32961594

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#991]
For new term requests, please provide the following information:

## Preferred term label

glycodeoxycholate 3-O-glucuronide measurement

## Synonyms

GDCA-3G

## Textual definition

Quantification of the amount of glycodeoxycholate 3-O-glucuronide in a sample.

## Suggested parent term

measurement

**Comment by zoependlington** [comment]
Added as EFO_0011010, which will be available at our next release (15th March)
