### ISSUE TITLE
New term request for Thareja G -PMID 33623009

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#993]
For new term requests, please provide the following information:

## Preferred term label

sitting height measurement

## Synonyms

NA

## Textual definition

quantification of some aspect of height, when assuming a sitting position 

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0004302

**Comment by zoependlington** [comment]
Added as EFO_0011011, which will be available at our next release (15th March)
