### ISSUE TITLE
New term request for Thareja G -PMID 33623009

### ISSUE THREAD

**Issue by buniello** [EBISPOT/efo#995]
For new term requests, please provide the following information:

## Preferred term label

blood bicarbonate measurement

## Synonyms

blood sodium bicarbonate measurement 

## Textual definition

The determination of the amount of bicarbonate present in a blood sample

## Suggested parent term

http://www.ebi.ac.uk/efo/EFO_0005664

**Comment by zoependlington** [comment]
Added as EFO_0011012, which will be available at our next release (15th March)
