### ISSUE TITLE
term request for Mehta PMID 32723796 

### ISSUE THREAD

**Issue by aoifemcm** [EBISPOT/efo#997]
For new term requests, please provide the following information:

## Preferred term label

vaginal microbiome measurement

## Synonyms

vaginal microbiota measurement, vaginal flora measurement

## Textual definition

quantification of some aspect of an individual's microbiome of the vagina 

## Suggested parent term

microbiome measurement
http://www.ebi.ac.uk/efo/EFO_0007882

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by zoependlington** [comment]
Added as EFO_0011013, which will be available at our next release (15th March)
