### ISSUE TITLE
New term request for Adjel PMID 33578652 

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#998]
For new term requests, please provide the following information:

## Preferred term label

health-related quality of life measurement

## Synonyms

HRQOL

## Textual definition

A measure to assess health-related quality of life (HRQOL), which domains include physical health, emotional health, cognitive functioning, fatigue and pain.

## Suggested parent term

measurement

- suggest above 'quality of life during menstruation measurement' ?

**Comment by zoependlington** [comment]
Added as EFO_0011014, which will be available at our next release (15th March)
