### ISSUE TITLE
New term request for Donati PMID 33594131

### ISSUE THREAD

**Issue by earlEBI** [EBISPOT/efo#999]
For new term requests, please provide the following information:

## Preferred term label

educational attainment

## Synonyms

academic attainment

## Textual definition

A measure of academic performance through educational benchmarks such as national exams and curriculum assessments

## Suggested parent term

measurement
parent of 'self reported educational attainment'

**Comment by zoependlington** [comment]
Added as EFO_0011015, which will be available at our next release (15th March)
